Update API.md to reflect microtime keyed errors
Expensify/App pull request #10145
Opened 2022-07-27 23:46 UTC by yuwenmemon

@iwiznia @bondydaa @neil-marcellini @Gonals @chiragsalian @MariaHCD please review

Update the API.md docs to reflect the fact that we want errors returned in an array keyed by the microtime.

2022-07-27 23:46 UTC, yuwenmemon commented
I'm actually curious how we want to handle the "other additional properties" case - should those also be keyed under the microtime?

2022-07-28 14:11 UTC, PauloGasparSv submitted a review, later dismissed
LGTM
Just couldn't find Onyx::getErrorMicroTime on main.

@yuwenmemon feel free to merge, not merging so people can have time to look and discuss your last comment.

2022-07-28 14:14 UTC, MariaHCD reviewed
> I'm actually curious how we want to handle the "other additional properties" case - should those also be keyed under the microtime?

I'm thinking it makes sense to associate the additional properties with the same microtime key. For instance, in [UpdatePersonalDetailsForWallet](https://github.com/Expensify/Web-Expensify/pull/34326) the API might return an additional prop `'errorCode' => 'ssnError'` and later we might also return a different errorCode `kbaNeeded`. 

If we didn't have the additional properties keyed under microtime the onyxData would look like:

```php
[
    [
        'onyxMethod' => Onyx::METHOD_MERGE,
        'key' => OnyxKeys::WALLET_ADDITIONAL_DETAILS,
        'value' => [
            'errors' => [
                microtime() => 'We\'re having trouble verifying your SSN. Please enter the full 9 digits of your SSN.',
                microtime() => 'We need to ask you a few more questions to finish validating your identity',
            ],
            'errorCode' => self:: WALLET_ERROR_KBA, // This will indicate to the frontend that the user must be redirected to the AnswerQuestionsForWallet step
            'idNumber' => $idNumber,
            'questions' => $questions,
        ],
    ],
];
```

The `errorCode` would be overwritten by the second error and while this wouldn't matter too much for this command since it's pattern C but if it were pattern B, we wouldn't want that prop to be overwritten, correct?

So perhaps it would be better if the onyxData looked like:

```php
[
    [
        'onyxMethod' => Onyx::METHOD_MERGE,
        'key' => OnyxKeys::WALLET_ADDITIONAL_DETAILS,
        'value' => [
            'errors' => [
               microtime() => [
                    'error' => 'We\'re having trouble verifying your SSN. Please enter the full 9 digits of your SSN.',
                    'errorCode' => 'ssnError', // We'll use this code on the frontend to alter the ssn field to accept the full 9 digit ssn
                ]
               microtime() => [
                    'error' => 'We need to ask you a few more questions to finish validating your identity',
                    'errorCode' => self:: WALLET_ERROR_KBA, // This will indicate to the frontend that the user must be redirected to the AnswerQuestionsForWallet step
                    'idNumber' => $idNumber,
                    'questions' => $questions,
                ]
            ],
        ],
    ],
];
```

Thoughts?

2022-07-28 19:00 UTC, neil-marcellini requested changes

2022-07-28 19:00 UTC, neil-marcellini commented on contributingGuides/API.md
> +Error messages should be returned and stored as an object under the `errors` property, keyed by a [microtime](https://www.php.net/manual/en/function.microtime.php). If absolutely needed, additional e
> keyed by a microtime

I think you should mention that it is an int, and update it to use `Onyx::getErrorMicroTime()` instead. We can wait until that PR is merged.

2022-07-28 20:38 UTC, iwiznia submitted a review, later dismissed

2022-07-28 21:59 UTC, PauloGasparSv approved these changes, later dismissed

2022-07-28 23:31 UTC, chiragsalian approved these changes, later dismissed

2022-07-29 15:10 UTC, yuwenmemon commented
@neil-marcellini updated for your suggestion!

2022-07-29 15:12 UTC, PauloGasparSv approved these changes

2022-07-29 17:32 UTC, chiragsalian approved these changes

2022-07-29 17:37 UTC, neil-marcellini approved these changes
Looks good, thanks 😄

2022-08-01 17:24 UTC, merged

2022-08-01 17:30 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-08-01 22:38 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2778074139) to staging by @yuwenmemon in version: 1.1.87-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|failure ❌
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|failure ❌

2022-08-04 20:50 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2799401529) to production by @yuwenmemon in version: 1.1.87-9 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅