Adds a set password page
Expensify/App pull request #1017
Opened 2020-12-18 21:15 UTC by tgolen

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/148712

### Tests
1. Sign out
2. Go to http://localhost:8080/#/setpassword/test
3. Submit the form without a password and verify there is an error the password is required
4. Enter a password and submit the form
5. Verify that (for now) you are just taken back to the sign in page

### Screenshots
![image](https://user-images.githubusercontent.com/1228807/102662121-6945f380-413b-11eb-8c04-2961fe74ef37.png)

2020-12-18 21:17 UTC, tgolen commented on src/pages/SignInPage.js
> +                    <View style={[styles.signInPageInner]} accessibilityRole="form">
FYI this removes a warning in the JS console about a password field not being inside of a form.

2020-12-18 21:27 UTC, tgolen commented
I have read the CLA Document and I hereby sign the CLA

2020-12-18 21:43 UTC, TomatoToaster requested changes

2020-12-18 21:43 UTC, TomatoToaster commented on src/pages/SetPasswordPage.js
> +        password: PropTypes.bool,
I think this should be type string.

2020-12-18 21:51 UTC, tgolen commented on src/pages/SetPasswordPage.js
> +        password: PropTypes.bool,
Oh yes indeed!

2020-12-18 21:52 UTC, tgolen commented
Updated

2020-12-18 21:54 UTC, TomatoToaster submitted a review, later dismissed

2020-12-18 21:55 UTC, TomatoToaster commented
Do you know how I can clear the credentials object so I can try that page again. I could've sworn that it wouldn't let me submit the password after the error showed up even if I entered something non-blank (had to refresh the page).

2020-12-18 22:25 UTC, tgolen commented
Yeah, you can to JS console > Application > Local Storage > localhost (right click) > clear

2020-12-18 22:27 UTC, tgolen commented
I was able to get it to submit the form even after entering no password, but I see that it doesn't clear the error. I will fix that.

2020-12-18 22:28 UTC, tgolen commented
Updated

2020-12-18 22:33 UTC, TomatoToaster approved these changes

2020-12-21 17:29 UTC, stitesExpensify approved these changes

2020-12-21 17:33 UTC, merged