[WIP] Create DeleteWorkspaceAvatar
Expensify/App pull request #10393
Opened 2022-08-16 15:13 UTC by Gonals

### Details

### Fixed Issues

$ GH_LINK

### Tests

- [ ] Verify that no errors appear in the JS console

### PR Review Checklist

#### Contributor (PR Author) Checklist
- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The Contributor+ will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct [...]

2022-08-17 14:41 UTC, Gonals commented
OFF WIP!

2022-08-19 17:46 UTC, neil-marcellini requested changes
Looking good. I have a couple of comments.

I will be adding the RBR to get to the general settings page in [this PR](https://github.com/Expensify/App/pull/10400), so only adding the error under the avatar here is fine. Also, it's very unlikely that we will see errors with this flow.

2022-08-19 17:46 UTC, neil-marcellini commented on src/libs/actions/Policy.js
> +                        [DateUtils.getMicroseconds()]: 'Sorry, there was an unexpected problem deleting your workspace avatar.',
I recently learned from [this Slack post](https://expensify.slack.com/archives/C03TQ48KC/p1660838478754859) that we are supposed to use `Localize.translateLocal` when setting errors on the front end.

2022-08-19 17:46 UTC, neil-marcellini commented on src/libs/actions/Policy.js
> +function deleteWorkspaceAvatar(policyID) {
Please add a JSDoc documenting the param type.

2022-08-19 17:46 UTC, neil-marcellini commented on src/libs/actions/Policy.js
> +function clearAvatarErrors(policyID) {
JSDoc please.

2022-08-22 15:34 UTC, Gonals commented
Comments addressed!!

2022-08-23 08:39 UTC, neil-marcellini approved these changes
Good to go! One NAB comment. I would update the title to [HOLD Web-E 34598] so it's clear what we're holding on.

2022-08-23 08:39 UTC, neil-marcellini commented on src/languages/en.js
> +        deleteWorkspaceError: 'Sorry, there was an unexpected problem deleting your workspace avatar.',
NAB: I was told to get a copy check for a similar error message. [Here](https://github.com/Expensify/Expensify/issues/219957#issuecomment-1222177053) is where that conversation is happening.

2022-08-23 09:18 UTC, Luke9389 approved these changes

2022-08-23 15:41 UTC, Gonals commented
OFF HOLD!

2022-08-23 15:44 UTC, neil-marcellini commented
It should still be on HOLD until the Web PR is deployed, otherwise it might fail on staging and create deploy blockers.

2022-08-23 15:48 UTC, Gonals commented
> It should still be on HOLD until the Web PR is deployed, otherwise it might fail on staging and create deploy blockers.

Really? I thought they could move in parallel! My bad!

2022-08-24 14:49 UTC, Gonals commented
Web PR is on Staging. This is OFF HOLD!
@MonilBhavsar, go for it!

2022-08-24 14:51 UTC, neil-marcellini commented
> Web PR is on Staging. This is OFF HOLD!

I appreciate the urgency, but App staging calls the production Web api, so we need to wait until it's on prod 😞

2022-08-24 14:53 UTC, Gonals commented
> > Web PR is on Staging. This is OFF HOLD!
> 
> I appreciate the urgency, but App staging calls the production Web api, so we need to wait until it's on prod 😞

Oh, damn :(

2022-08-25 11:49 UTC, MonilBhavsar approved these changes
Looks good and works well!

2022-08-25 12:34 UTC, neil-marcellini commented
[Web](https://github.com/Expensify/Expensify/issues/219963) was just deployed to production so we can merge!

2022-08-25 14:11 UTC, merged

2022-08-25 17:55 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2928190658) to staging by @MonilBhavsar in version: 1.1.90-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-08-26 10:27 UTC, Julesssss commented
Testing well in staging

<img width="372" alt="Screenshot 2022-08-26 at 12 26 44" src="https://user-images.githubusercontent.com/10736861/186884502-ab6b804e-aee1-40f4-8cc8-ff838bc5d1f5.png">