[WIP] Use `window.location.href` for current URL
Expensify/App pull request #10494
Opened 2022-08-23 17:39 UTC by arosiclair

Replaces react-router logic for tracking the current URL

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/217505

### Tests

1. Log into a new OldDot account with no policies
2. Use the "Get started with our free plan" inbox task to create a Workspace
3. Verify the workspace is successfully created in NewDot
4. Sign out of NewDot
5. Log back in and verify another workspace is NOT created
6. Sign out again and leave the tab open
7. Return to OldDot and navigate to Settings > Policies > Group
8. Create another free plan policy
9. Verify only 1 additional workspace (2 in total) is created in the second NewDot tab.

- [x] Verify that no errors appear in the JS console

### PR Review Checklist

#### Contributor (PR Author) Checklist
- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The Contributor+ will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e [...]

2022-08-23 19:16 UTC, marcaaron requested changes

2022-08-23 19:16 UTC, marcaaron commented on src/libs/Navigation/NavigationRoot.js
> -        }
These logs are very useful for debugging and should not be removed.

2022-08-23 19:16 UTC, marcaaron commented on src/libs/Navigation/currentUrl/index.js
> +export default function getCurrentUrl() {
```suggestion
/**
 * @returns {String}
 */
export default function getCurrentUrl() {
```

2022-08-23 19:16 UTC, marcaaron commented on src/libs/Navigation/currentUrl/index.native.js
> +export default function getCurrentUrl() {
```suggestion
/**
 * @returns {String}
 */
export default function getCurrentUrl() {
```

2022-08-24 08:16 UTC, tgolen submitted a review, later dismissed
Love it! This is a great clean-up. Thank you ❤️

2022-08-31 08:30 UTC, marcochavezf requested changes
LGTM, just a minor jsdoc change

2022-08-31 08:30 UTC, marcochavezf commented on src/libs/actions/App.js
>   * @param {string} currentPath
`currentPath` is no longer a param of this function
```suggestion
```

2022-09-01 07:45 UTC, marcochavezf approved these changes

2022-09-01 12:43 UTC, arosiclair commented
@marcaaron friendly bump

2022-09-02 07:57 UTC, marcaaron approved these changes

2022-09-02 07:58 UTC, merged

2022-09-02 08:02 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-09-05 09:13 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2991935016) to staging by @marcaaron in version: 1.1.97-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2022-09-05 17:50 UTC, kavimuru commented
@arosiclair Do we have to login to mWeb / chrome browser or OldDot app for step 1 "`Log into a new OldDot account with no policies"` ?

2022-09-06 08:56 UTC, arosiclair commented
> @arosiclair Do we have to login to mWeb / chrome browser or OldDot app for step 1 "`Log into a new OldDot account with no policies"` ?

desktop chrome browser

2022-09-07 16:38 UTC, kavimuru commented
@arosiclair  Web environment was tested already.  How to test in iOS , Android  and Desktop?

2022-09-07 17:01 UTC, arosiclair commented
> @arosiclair Web environment was tested already. How to test in iOS , Android and Desktop?

This feature is not supported on these platforms so No QA for them

2022-09-09 09:28 UTC, Julesssss commented
Just mentioning here that this PR was a suspect for this [fireroom](https://expensify.slack.com/archives/C04210TST89/p1662684471388059). It would be great for anyone with context to take a look at [this issue](https://expensify.slack.com/archives/C04210TST89/p1662684471388059). Thanks!