Add check for team.expensify.com emails for default workspace rooms
Expensify/App pull request #10855
Opened 2022-09-07 09:10 UTC by thienlnam

### Details

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/227011

### Tests

- [ ] Verify that no errors appear in the JS console

### PR Review Checklist

#### Contributor (PR Author) Checklist
- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The Contributor+ will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging th [...]

2022-09-07 10:56 UTC, alex-mechler commented
Did you test after turning all the betas off?

2022-09-07 10:58 UTC, thienlnam commented
> Did you test after turning all the betas off?

Yup, overrode checks for canUsePolicyRooms and canUseAllBetas.  I tested on main with these as well and checked that the opposite case worked as well.  This might actually have to end up being No QA unless we get team.expensify.com emails in time

> Same as QA steps EXCEPT make sure to locally override checks for canUsePolicyRooms to false and canUseAllBetas to false

2022-09-07 11:53 UTC, Gonals submitted a review, later dismissed

2022-09-07 16:32 UTC, alex-mechler requested changes

2022-09-07 16:32 UTC, alex-mechler commented on src/pages/home/ReportScreen.js
>          // We let Free Plan default rooms to be shown in the App - it's the one exception to the beta, otherwise do not show policy rooms in product
Update this comment

2022-09-07 16:32 UTC, alex-mechler commented on src/pages/home/ReportScreen.js
> +            && ReportUtils.hasExpensifyGuidesEmails(lodashGet(this.props.report, ['participants'], []))
This should be a `!` right? This is filtering out reports, not checking if we can add them

2022-09-07 16:32 UTC, alex-mechler commented on src/libs/OptionsListUtils.js
>          // We let Free Plan default rooms to be shown in the App - it's the one exception to the beta, otherwise do not show policy rooms in product
Update this comment please

2022-09-08 07:46 UTC, alex-mechler submitted a review, later dismissed

2022-09-08 07:46 UTC, alex-mechler commented on src/libs/OptionsListUtils.js
> +            && !ReportUtils.hasExpensifyGuidesEmails(logins)
Very very very minor nab, but this check is in a different order than the others

2022-09-08 08:48 UTC, alex-mechler approved these changes

2022-09-08 09:07 UTC, Gonals approved these changes

2022-09-08 09:07 UTC, merged

2022-09-08 09:12 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-09-09 04:10 UTC, mvtglobally commented
@thienlnam @Gonals @alex-mechler Can we run this PR with Expensifail.com account to QA? 
If not, Can you validate this internally

2022-09-09 06:07 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3019072663) to staging by @Gonals in version: 1.1.99-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2022-09-09 08:59 UTC, thienlnam commented
> @thienlnam @Gonals @alex-mechler Can we run this PR with Expensifail.com account to QA?
If not, Can you validate this internally

This won't work with an expensifail.com account, we'll do the QA for this internally

2022-09-09 10:21 UTC, thienlnam commented
I created a new account and added a new collect policy for this user

This is what my NewDot looks like before adding a team.expensify.com email
<img width="1500" alt="Screen Shot 2022-09-09 at 10 54 03 AM" src="https://user-images.githubusercontent.com/30609178/189323805-3c04e92d-deba-46d2-8e1d-7430cf04ccce.png">

In OldDot, I added a @team.expensify.com email address to the policy as an auditor

This is what my NewDot looks like after:
<img width="1507" alt="Screen Shot 2022-09-09 at 11 21 40 AM" src="https://user-images.githubusercontent.com/30609178/189328907-4473d7c7-a979-43c4-8aff-64e0c751c953.png">