Graphical alignment issues in chat upon first sign-in
Expensify/App pull request #1086
Opened 2020-12-24 07:16 UTC by ilijaprzeski

### Details
When develop react native app, style definition should be wrapped by StyleSheet.create function. If not, some style can be removed by react native library itself, such as alignItems, justifyContent, position and so on.

### Fixed Issues
Fixes [Expensify/Expensify.cash/issues/1031](https://github.com/Expensify/Expensify.cash/issues/1031)

### Tests
1. Start the app on in an Incognito browser
2. Hard refresh the page
3. type in your username and password, and tap 'Log in'
4. Once you're logged in, tap the hamburger menu, type in concierge@ in the text box, and tap on the Concierge user
5. Notice the center paperclip icon and aligned presence indicator (green dot)

2020-12-24 07:16 UTC, ilijaprzeski commented
**I have read the CLA Document and I hereby sign the CLA**

2020-12-24 07:24 UTC, ilijaprzeski commented
**I have read the CLA Document and I hereby sign the CLA**

2020-12-24 08:29 UTC, ilijaprzeski commented
**I have read the CLA Document and I hereby sign the CLA**

2020-12-24 08:45 UTC, ilijaprzeski commented
I have read the CLA Document and I hereby sign the CLA

2020-12-24 08:48 UTC, ilijaprzeski commented
**I have read the CLA Document and I hereby sign the CLA**

2020-12-24 08:50 UTC, ilijaprzeski commented
https://github.com/Expensify/Expensify.cash/pull/1086#issuecomment-750783563

2020-12-25 16:22 UTC, marcaaron requested changes
Thanks @ilijaprzeski. Going to wait for some input from @shawnborton on this one as he is our designer and will have better opinions about the styles. It looks like using `StyleSheet.create()` has fixed the cases we had issues with but also has affected the previous designs. Is there any explanation why?

Please refer to these screenshots:

**Before:**
![2020-12-25_06-17-39 (1)](https://user-images.githubusercontent.com/32969087/103138669-f4ae1000-4678-11eb-9db0-1be25883ac9a.png)

**After:**

First sign in...
![2020-12-25_06-19-34](https://user-images.githubusercontent.com/32969087/103138707-52daf300-4679-11eb-8fe5-7f4cf955a432.png)

After page refresh (improved but still incorrect)
![2020-12-25_06-19-51](https://user-images.githubusercontent.com/32969087/103138721-730ab200-4679-11eb-8056-1afeb1fcea72.png)

2020-12-26 16:44 UTC, shawnborton commented
I don't have much to add for input, but it does seem like this input doesn't solve the root of the problem and is creating a lot of breaking design changes elsewhere.

2020-12-29 19:18 UTC, marcaaron commented
Please open **one** PR per issue. Feel free to reopen whichever single PR you are proposing as a solution.

2020-12-29 19:18 UTC, closed without merging