Chat view padding issue removed
Expensify/App pull request #1110
Opened 2020-12-28 19:34 UTC by muhammadusama95

<If necessary, assign reviewers that know the area or change well. Feel free to tag any additional reviewers you see fit.>

### Details
Implemented Solution is:
Go to ReportActionCompose.js File. Go to Parent View then there are multiple containers i.e. attachments, send button, and input text field. There was a problem with the input text field view styles. There wad Unnecessary padding of the input text field which was causing the extra space at the top and was not setting the input text view to the center of the parent view So we removed that and input text is at the center of the parent view and the top spacing has been removed using top, bottom padding value to 0 and I have tested this.
I am waiting to add me to the git link SO I can push the code to my branch and your team can review the code.

### Fixed Issues
Remove Top Padding from chatView.

### Tests
Tested on Android OnePlus 3 Mobile.
Tested on iOS iPhone X emulator.

### Tested On
- [ ] iOS
- [ ] Android

#### iOS

#### Android

2020-12-28 22:48 UTC, roryabraham commented
Hi @muhammadusama95 - just a few early comments on this PR:

1) Please include the link to the issue you've been assigned under the **Fixed Issue** header
2) Please be sure to test any and all changes on all platforms, including screenshots (web, desktop, mobile web, iOS, Android). Right now, I only see iOS and Android
3) Looking at the screenshot you provided on Android, the text in the input field is vertically misaligned

2020-12-29 16:19 UTC, muhammadusama95 commented
Hi, @roryabraham Thanks for your review of my code.
I just made a new commit, Added Comments on code where I changed for the fixing of the top padding issue. So you can easily
identify my code.
Below are my answers to all your questions:
1: https://github.com/Expensify/Expensify.cash/issues/1002

2: Yeah As per my discussion with Michael, This is a cross-platform app So I have tested it on both iOS and Android. Not included web, desktop, or mobile web version.

3: By mistakenly added an old android screenshot Please see attached updated android screenshot too.
![UpdatedAndroidScreenshot](https://user-images.githubusercontent.com/49236138/103297891-05fd7080-4a1b-11eb-8761-a8bc40b3bce1.jpeg)

4: Now I added comments in the new commit So you can quickly identify my changes.

5: There is no new lint error or warnings in my branch as I just changed the values of padding.

2020-12-29 17:18 UTC, roryabraham requested changes
Hi @muhammadusama95, sorry if I wasn't clear before, but I have a few new comments.

1) All the code style changes you have made to `src/styles/styles.js` are unacceptable, because they do not conform to our code style guidelines and the code format throughout the rest of the codebase. Adding comments to identify your code is not a valid solution - the comments would litter the codebase with irrelevant information. So to be clear, we will not merge any PR containing extraneous changes not relevant to the issue which you have been assigned. Why did you remove all indentation from the file?
2) _All_ PRs must be tested on 5 platforms: web, mobile web, desktop, android, and iOS. The same code is used to build the application on all 5 platforms, so we need to make sure your changes don't cause undesirable effects in the other platforms.
3) It seems like the screenshots you've provided render only the `ReportActionCompose` component in isolation, not the complete application.
4) I noticed that your code contains a platform-check, like so:

```
if (Platform.OS == 'ios') {
    ...
}
```

This is something we have decided to intentionally avoid in this codebase. Instead, check out the [README section covering platform-specific file extensions](https://github.com/Expensify/Expensify.cash#platform-specific-file-extensions).

2020-12-30 20:34 UTC, muhammadusama95 commented
Hi @roryabraham,
Please check the last 3 commits So you can check the indentation Set, Comments removed, and padding issue fixed.

Now I have tested it using login through Expensify app and check below screenshots of both iOS and Android respectively.
![iOS_ScreenShot_updated](https://user-images.githubusercontent.com/49236138/103379564-db3d1600-4b07-11eb-90f2-645d52c8f84c.png)
![Android_ScreenShot_updated](https://user-images.githubusercontent.com/49236138/103379567-dd06d980-4b07-11eb-8b18-8678f1a04587.png)

About testing it on All Platforms @michaelhaxhiu had chat with me on android and iOS only. Check Below Screenshot.
![Michael_ScreenShot](https://user-images.githubusercontent.com/49236138/103379680-4850ab80-4b08-11eb-850a-187787305665.PNG)

2020-12-30 20:45 UTC, roryabraham commented
Hi @muhammadusama95. Regardless of what others may have told you, _all PRs must be tested on all platforms_. So that means that your code changes must be tested on:

1) Web (from a laptop)
2) Desktop (from a mac computer - let me know if you don't have a mac)
3) Web (from a mobile device or simulator)
4) iOS
5) Android

2020-12-30 20:49 UTC, roryabraham requested changes
The diff is more reasonable now, but please review the diff and remove all non-critical changes.

2020-12-31 17:10 UTC, roryabraham requested changes

2020-12-31 17:10 UTC, roryabraham commented on src/styles/styles.js
> +// Utility classes
This indentation change is unnecessary, please revert

2020-12-31 17:10 UTC, roryabraham commented on src/pages/home/report/ReportActionCompose.js
> +
Please remove this blank line

2020-12-31 17:10 UTC, roryabraham commented on src/styles/styles.js
> +
Please remove this blank line

2020-12-31 17:10 UTC, roryabraham commented on src/styles/styles.js
> +
Please remove this blank line

2020-12-31 17:10 UTC, roryabraham commented on src/styles/styles.js
> +
Please remove this blank line

2020-12-31 17:10 UTC, roryabraham commented on src/styles/styles.js
> +
Please remove this blank line

2020-12-31 17:10 UTC, roryabraham commented on src/styles/styles.js
> +// Actions
This indentation change is unnecessary, please revert

2020-12-31 17:10 UTC, roryabraham commented on src/styles/styles.js
> +// Sidebar Styles
Please indent this comment four spaces

2020-12-31 17:10 UTC, roryabraham commented on src/styles/styles.js
> +// App Content Wrapper styles
This indentation change is unnecessary, please revert

2020-12-31 17:10 UTC, roryabraham commented on src/styles/styles.js
> +// Chat Item
This indentation change is unnecessary, please revert

2020-12-31 17:10 UTC, roryabraham commented on src/styles/styles.js
> +        fontWeight: '600',
The change to `fontWeight` here shouldn't be necessary - please use `fontWeightBold` instead

2020-12-31 17:10 UTC, roryabraham commented on src/styles/styles.js
> +// As of react-native-render-html v6, don't declare distinct styles for
This indentation change is unnecessary, please revert

2020-12-31 17:10 UTC, roryabraham commented on src/styles/styles.js
> +// Overwrite default HTML margin for blockquotes
This indentation change is unnecessary, please revert

2021-01-01 16:39 UTC, muhammadusama95 commented
Hi @roryabraham,
Please find All Platform tested screenshots.
1: Android
![Android_ScreenShot_updated](https://user-images.githubusercontent.com/49236138/103442631-caacad00-4c79-11eb-9ebf-553da8adada0.png)
2:iOS
![iOS_ScreenShot_updated](https://user-images.githubusercontent.com/49236138/103442630-c3859f00-4c79-11eb-8d47-adb811c1d2dd.png)
3:Mobile Web
![mobile_web](https://user-images.githubusercontent.com/49236138/103442606-a0f38600-4c79-11eb-8c7e-036e6be414f3.png)
4:Web
![web_](https://user-images.githubusercontent.com/49236138/103442616-acdf4800-4c79-11eb-9488-5be127d22334.png)
5:MAC-Desktop
![mac_desktop](https://user-images.githubusercontent.com/49236138/103442614-abae1b00-4c79-11eb-8496-42377e897b27.png)

2021-01-06 17:47 UTC, roryabraham commented
Looks like you've got a merge conflict

2021-01-06 17:53 UTC, roryabraham requested changes

2021-01-06 17:53 UTC, roryabraham commented on src/pages/home/report/ReportActionCompose.js
> -                <ReportTypingIndicator reportID={this.props.reportID} />
Please remove this unnecessary whitespace change

2021-01-06 17:53 UTC, roryabraham commented on src/styles/styles.js
> +    mt2: {
Please don't change the indentation utils here. If you need `marginTop: 20`, use `mt5`

2021-01-06 17:53 UTC, roryabraham commented on src/styles/styles.js
> +    mt2: {
Also please make sure that these are arranged sequentially like `mt1, mt2, mt3...`

2021-01-06 17:53 UTC, roryabraham commented on src/styles/styles.js
> -    mt4: {
Why did you remove these three styles?

2021-01-06 17:53 UTC, roryabraham commented on src/styles/styles.js
> -    mb5: {
Why did you remove these two styles?

2021-01-06 17:53 UTC, roryabraham commented on src/styles/styles.js
> -    width50p: {
Why did you remove this style?

2021-01-06 17:53 UTC, roryabraham commented on src/styles/styles.js
> -        fontFamily: fontFamily.GTA,
Why did you remove the fontFamily?

2021-01-06 17:53 UTC, roryabraham commented on src/styles/styles.js
> -    link: {
Why did you remove these styles?

2021-01-06 17:53 UTC, roryabraham commented on src/styles/styles.js
> +   // As of react-native-render-html v6, don't declare distinct styles for
These comments need to be indented by one space

2021-01-07 13:08 UTC, michaelhaxhiu commented
Let's give @roryabraham a chance to review, as he's been doing 🔧

2021-01-07 18:18 UTC, roryabraham commented
@muhammadusama95 There are still lots of unresolved comments that would need to be addressed before this could be merged. Not to mention there's a merge conflict, so it's not even possible to merge presently.

2021-01-08 07:25 UTC, muhammadusama95 commented
@michaelhaxhiu @roryabraham Can you please assign this issue to @ahmad.zahid2000@gmail.com. I will create a new branch and take a pull request instead of resolving these comments by doing this it's hardly 20-25 minutes work.

2021-01-08 07:27 UTC, muhammadusama95 commented
On the new branch, you will get only the required changes. Nothing else.

2021-01-08 14:56 UTC, michaelhaxhiu commented
@muhammadusama95 We have decided to move forward with another contributor. Thanks for your assistance thus far, but no further action is required from your side.

I'm closing this PR and going to pay you in Upwork shortly.

2021-01-08 14:56 UTC, closed without merging