Move config files around to clean up root
Expensify/App pull request #1113
Opened 2020-12-28 22:05 UTC by AndrewGable

Please review @tgolen 
cc @marcaaron 

### Details
Moving the various config files around to make the root have less files.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/146267

### Tests
Make sure all platforms build successfully

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

2020-12-28 22:43 UTC, tgolen requested changes
Did you want to move the eslint file back into the root to make it easier on the lives of our contributors?

2020-12-28 22:43 UTC, tgolen commented on src/CONFIG.js
> +    DISPLAY_NAME: 'Expensify Cash',
It doesn't look like this is ever used?

2020-12-28 23:18 UTC, AndrewGable commented
@marcaaron has a PR [here](https://github.com/Expensify/Expensify.cash/pull/1103) that is handling the eslint file.

2020-12-28 23:19 UTC, AndrewGable commented on src/CONFIG.js
> +    DISPLAY_NAME: 'Expensify Cash',
Yeah, good point, I will remove!

2020-12-29 21:03 UTC, tgolen approved these changes

2020-12-29 21:04 UTC, merged