Fixed: If the last message is deleted, the previous one becomes partially hidden #10765
Expensify/App pull request #11752
Opened 2022-10-12 14:04 UTC by advaitasol9

@JmillsExpensify 
### Details

Deleting the last message of a conversation was resulting in the previous message getting partially/completely hidden because of extra scrolling, we have added required padding at the bottom of Flatlist to compensate the space required by 'recipient local time'.

### Fixed Issues

$ https://github.com/Expensify/App/issues/10765
$ https://github.com/Expensify/App/issues/10765#issuecomment-1254544138

### Tests

1. From home screen, start a chat with anyone.
2. Send 2-3 messages to the recipient.
3. Delete the last message.
4. After deleting the last message, the previous message should be visible and should not be partially or completely hidden.
- [x] Verify that no errors appear in the JS console

### PR Review Checklist

#### PR Author Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The reviewer will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIco [...]

2022-10-13 17:48 UTC, ctkochan22 commented
Looks okay to me, @Santhosh-Sellavel can you be a hero and test this PR?

2022-10-13 20:05 UTC, Santhosh-Sellavel commented
@ctkochan22 Can you reproduce this issue now?

2022-10-13 20:10 UTC, Santhosh-Sellavel reviewed
Adds unnecessary spacing below the last message, if we want to make this change lets loop in the design team here, as this could be called a regression from a design point of view!

2022-10-17 22:21 UTC, ctkochan22 commented
Thats a good catch. We don't want that extra padding there

2022-10-26 16:59 UTC, JmillsExpensify commented
@advaitasol9 are you planning on coming back to this PR and making updates this week? This one looks close to the finish line, let's get it merged!

2022-10-26 17:28 UTC, advaitasol9 commented
Yes @JmillsExpensify, will update in next few days.

2022-10-28 12:31 UTC, advaitasol9 commented
@Santhosh-Sellavel @JmillsExpensify  Updated

2022-11-02 06:17 UTC, advaitasol9 commented
Hi @JmillsExpensify @Santhosh-Sellavel please take a look here.

2022-11-02 20:20 UTC, Santhosh-Sellavel commented
Oops, I forgot to submit the review!
![Uploading Screenshot 2022-11-03 at 1.49.52 AM.png…]()

2022-11-02 20:20 UTC, Santhosh-Sellavel commented
Oops, I forgot to submit the review!
<img width="1087" alt="Screenshot 2022-11-03 at 1 49 52 AM" src="https://user-images.githubusercontent.com/85645967/199594562-8306bda7-de6b-46d9-adde-60bd7db37096.png">

2022-11-02 20:20 UTC, Santhosh-Sellavel requested changes

2022-11-03 11:40 UTC, advaitasol9 commented on src/pages/home/report/ReportActionsList.js
> +                        shouldShowReportRecipientLocalTime && styles.pt3 && styles.mtn4,
@Santhosh-Sellavel our original solution resulted in extra gap between the last message and 'Recipient Local time' as mentioned by you in previous comments, hence to counter the extra spacing we are providing negative margin, during testing i found -16 margin was perfect for our case.

2022-11-03 14:08 UTC, Santhosh-Sellavel commented on src/pages/home/report/ReportActionsList.js
> +                        shouldShowReportRecipientLocalTime && styles.pt3 && styles.mtn4,
Why do we need to add a -16 margin, what's causing the issue?

2022-11-04 07:24 UTC, advaitasol9 commented on src/pages/home/report/ReportActionsList.js
> +                        shouldShowReportRecipientLocalTime && styles.pt3 && styles.mtn4,
In ios, the flatlist seems to scroll down more than required in absence of padding on rerendering with less items than before, hence we gave it a 12 padding first, but that padding caused to build a gap at bottom of list, to counter that gap we gave it a negative margin of 12 initially, but the negative margin of 12 still was off from the original design. Hence the -16 margin.

2022-11-04 13:48 UTC, Santhosh-Sellavel commented on src/pages/home/report/ReportActionsList.js
> +                        shouldShowReportRecipientLocalTime && styles.pt3 && styles.mtn4,
@ctkochan22 Are we okay with this, can we loop in design to check if are we good with this?

2022-11-09 04:36 UTC, ctkochan22 commented
Trying to sort this out by testing now on main. And I can't reproduce. 

Can you guys help me out and confirm that the repro steps are
1. Send message 1
2. Send message 2
3. Delete most recent (message 2)
4. And it should jump above past message 1

2022-11-12 01:42 UTC, Santhosh-Sellavel commented
Unable to reproduce this any more!

2022-12-05 16:42 UTC, Santhosh-Sellavel commented
@advaitasol9 close this as it's no longer needed!

2022-12-05 19:29 UTC, ctkochan22 commented
Agreed that this isn't the right fix

2022-12-05 19:29 UTC, closed without merging