Add write a proposal in the issue before submitting a PR
Expensify/App pull request #1193
Opened 2021-01-07 22:03 UTC by iwiznia

### Details
Clarifying about sending a proposal.

Just a readme change, no tests.

2021-01-07 22:06 UTC, iwiznia commented
I have read the CLA Document and I hereby sign the CLA

2021-01-08 20:05 UTC, Jag96 requested changes
Just some notes for more details here

2021-01-08 20:05 UTC, Jag96 commented on CONTRIBUTING.md
> +1. *Before writing any code* write a proposal for the solution in the issue
Can you add more detail about what a proposal entails? Maybe something like

```
**Before writing any code**, please post a proposal of the solution you plan to implement as a comment in the GH issue. This should include a brief technical explanation of the changes you will make.
```

2021-01-08 20:05 UTC, Jag96 commented on CONTRIBUTING.md
> +1. Wait for Expensify to review and provide feedback on the proposal within the GH issue, and assign the GH issue to you
I'd also mention here `Please do not move forward with creating a Pull Request until your proposal is approved`

2021-01-08 21:28 UTC, iwiznia commented
Updated

2021-01-09 02:05 UTC, Jag96 approved these changes

2021-01-09 02:05 UTC, merged