fix: blue outline appears for a moment on buttons
Expensify/App pull request #12090
Opened 2022-10-24 15:28 UTC by MarkCSmith

Remove focus from the chat action button, emoji picker, and the video chat button immediately after the buttons are clicked/tapped.

### Details
A blue focus ring is displayed when a button has focus, but this is undesirable.  By immediately calling blur() on the element we can suppress the focus ring.

### Fixed Issues
$ https://github.com/Expensify/App/issues/11433
$ PROPOSAL https://github.com/Expensify/App/issues/11433#issuecomment-1267234502

### Tests

For MacOS Chrome and MacOS Desktop:
1.  Navigate to a chat.
2.  Click on the Actions button.
3.  Press up or down arrow to select Send money.
4.  Press enter.
5.  Verify visually that no blue ring exists on the Actions button.
6.  Close the Send money panel.
7.  Click on the Call button.
8.  Press arrow key.
9.  Press escape.
10. Verify visually that no blue ring exists on the Call button.
11. Click on the Emoji button.
12. Use the arrow keys to choose an emoji.
13. Press enter.
14. Verify visually that no blue ring exists on the Emoji button.
15. Close the chat and click on the FAB.
16. Use the arrow keys to select Send money.
17. Verify visually that no blue ring briefly appears on the FAB button.

For iOS/native, Android/native, iOS/Safari, and Android/Chrome:
1.  Navigate to a chat.
2.  Tap on the Actions button.
3.  Tap above the actions menu to dismiss it.
4.  Verify visually that no blue ring exists on the Actions button.
5.  Tap on the Call button.
6.  Tap above the call menu to dismiss it.
7.  Verify visually that no blue ring exists on the Actions button.
8.  Tap on the Emoji button.
9.  Tap an emoji.
10. Verify visually that no blue ring briefly appears on the Emoji button.
11. Close the chat and tap on the FAB.
12. Tap outside the menu to dismiss it.
13. Verify visually that no blue ring exists on the FAB button.

Note: on Android/Chrome in the device we used for testing, the focus ring
was orange instead of blue.

- [x] Verify that no errors appear in the JS console

### QA Steps

For MacOS Chrome and MacOS Desktop:
1.  Navigate to a chat.
2.  Click on the Actions button.
3.  Press up or down arrow to select Send money.
4.  Press enter.
5.  Verify visually that no blue ring exists on the Actions button.
6.  Close the Send money panel.
7.  Click on the Call button.
8.  Press arrow key.
9.  Press escape.
10. Verify visually that no blue ring exists on the Call button.
11. Click on the Emoji button.
12. Use the arrow keys to choose an emoji.
13. Press enter.
14. Verify visually that no blue ring exists on the Emoji button.
15. Close the chat and click on the FAB.
16. Use the arrow keys to select Send money.
17. Verify visually that no blue ring briefly appears on the FAB button.

For iOS/native, Android/native, iOS/Safari, and Android/Chrome:
1.  Navigate to a chat.
2.  Tap on the Actions button.
3.  Tap above the actions menu to dismiss it.
4.  Verify visually that no blue ring exists on the Actions button.
5.  Tap on the Call button.
6.  Tap above the call menu to dismiss it.
7.  Verify visually that no blue ring exists on the Actions button.
8.  Tap on the Emoji button.
9.  Tap an emoji.
10. Verify visually that no blue ring briefly appears on the Emoji button.
11. Close the chat and tap on the FAB.
12. Tap outside the menu to dismiss it.
13. Verify visually that no blue ring exists on the FAB button.

Note: on Android/Chrome in the device we used for testing, the focus ring
was orange instead of blue.

- [x] Verify that no errors appear in the JS console

### PR Review Checklist
#### PR Author Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on all platforms(https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and f [...]

2022-10-24 18:48 UTC, MarkCSmith commented
I have read the CLA Document and I hereby sign the CLA

2022-10-27 20:51 UTC, thesahindia requested changes

2022-10-27 20:51 UTC, thesahindia commented on src/pages/home/report/ReportActionCompose.js
> +                                                            this.actionButton.blur(); // Drop focus to avoid blue focus ring.
Let's not use inline comments. Please move it to a new line above.

2022-10-27 20:51 UTC, thesahindia commented on src/components/VideoChatButtonAndMenu/BaseVideoChatButtonAndMenu.js
> +                                this.videoChatButton.blur(); // Drop focus to avoid blue focus ring.
Same here.

2022-10-27 20:51 UTC, thesahindia commented on src/components/FAB/FAB.js
> +                        this.fabPressable.blur(); // Drop focus to avoid blue focus ring.
Same.

2022-10-27 20:51 UTC, thesahindia commented on src/components/EmojiPicker/EmojiPicker.js
> +            emojiPopoverAnchor.blur(); // Drop focus to avoid blue focus ring.
Here too.

2022-10-27 20:52 UTC, thesahindia commented
@MarkCSmith, please address this as well -
1. The proposal link should be prefixed with PROPOSAL (at "Fixed Issues" section)
2. Please attach videos for desktop and web, we don't have this issue at other platforms so screenshots are fine for them.

2022-10-28 15:55 UTC, MarkCSmith commented
> @MarkCSmith, please address this as well -
> 
>     1. The proposal link should be prefixed with PROPOSAL (at "Fixed Issues" section)
>     2. Please attach videos for desktop and web, we don't have this issue at other platforms so screenshots are fine for them.

Thanks for your feedback.  Done!

2022-10-28 17:58 UTC, thesahindia commented
Thanks for the changes!  Everything looks good but we got some conflicts. Please pull the latest changes and resolve them and we will be good to go 🚀.

2022-10-28 18:24 UTC, MarkCSmith commented
> Thanks for the changes! Everything looks good but we got some conflicts. Please pull the latest changes and resolve them and we will be good to go 🚀.

@thesahindia Should I create a new PR, or what is the best way to publish a rebased branch?

2022-10-28 19:12 UTC, thesahindia commented
> @thesahindia Should I create a new PR, or what is the best way to publish a rebased branch?

You can pull the changes using `git pull origin main`, then resolve the conflicts and just commit and push it. Just make sure you fetch the latest changes at main branch of your forked repo

2022-10-31 15:20 UTC, MarkCSmith commented
> > @thesahindia Should I create a new PR, or what is the best way to publish a rebased branch?
> 
> You can pull the changes using `git pull origin main`, then resolve the conflicts and just commit and push it. Just make sure you fetch the latest changes at main branch of your forked repo

Thanks!  Hopefully I did things correctly.

2022-10-31 16:55 UTC, roryabraham commented
@MarkCSmith this PR is unmergable as-is because it contains one unsigned commit. Please try this command to retroactively sign the commits on this PR:

```bash
git -c core-editor=true rebase -i --exec 'git commit --amend --no-edit -n -S' a93beb77befef329810af5068caef370f5eb0784
```

Then force-push to this branch with `git push --force origin issue11433-blue-outline`

2022-10-31 17:15 UTC, thesahindia commented
Changes looks good. @MarkCSmith, please address https://github.com/Expensify/App/pull/12090#issuecomment-1297385838 (sorry for not catching this earlier)
<details>
<summary>
Screenshots
</summary>

**Web**


https://user-images.githubusercontent.com/83179295/199067154-96b95560-38c6-49e1-adcf-3f41cd1e93c7.mov







**Mobile Web - Chrome**




https://user-images.githubusercontent.com/83179295/199067180-3277b9a2-08d4-4204-bba1-469a05f5bb02.mov






**Mobile Web - Safari**



https://user-images.githubusercontent.com/83179295/199067204-b095bd91-dfc0-4c3a-9669-fcd217a7f5ad.mov









**Desktop**




https://user-images.githubusercontent.com/83179295/199067237-d9675571-232c-42f7-95ae-bc6e61248e34.mov





**iOS**


https://user-images.githubusercontent.com/83179295/199067295-88a0c786-6895-42f6-83e1-91d2c9543032.mov









**Android**




https://user-images.githubusercontent.com/83179295/199067268-cf167f6d-8528-4ef6-88f7-86778f635fc3.mov




</details>

2022-10-31 19:59 UTC, MarkCSmith commented
> @MarkCSmith this PR is unmergable as-is because it contains one unsigned commit. Please try this command to retroactively sign the commits on this PR:
> 
> ```shell
> git -c core-editor=true rebase -i --exec 'git commit --amend --no-edit -n -S' a93beb77befef329810af5068caef370f5eb0784
> ```

Thanks.  The above command is asking me to manually resolve dozens of conflicts (a painful and potentially error-prone process).  But I was able to undo the merge to current main, run the above command to add the missing signature, and then re-do the merge to main.  I will force push the revised branch.

2022-10-31 20:11 UTC, thesahindia commented
Looks good and tests well!

cc: @roryabraham 

C+ reviewed 🎀👀🎀

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

2022-10-31 20:12 UTC, thesahindia submitted a review, later dismissed

2022-11-12 20:46 UTC, roryabraham submitted a review, later dismissed
Sorry for the review delay

2022-11-12 20:47 UTC, roryabraham commented
Unfortunately this PR now has conflicts that need to be resolved. I apologize for the  inconvenience @MarkCSmith

2022-11-15 21:30 UTC, thesahindia approved these changes

2022-11-15 21:32 UTC, thesahindia commented
- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

2022-11-15 21:33 UTC, thesahindia approved these changes

2022-11-15 21:34 UTC, thesahindia commented
Not sure, why the PR Reviewer Checklist test is failing.

2022-11-15 21:35 UTC, roryabraham commented
@thesahindia it's probably related to https://github.com/Expensify/App/pull/12429

2022-11-15 21:37 UTC, roryabraham approved these changes

2022-11-15 21:39 UTC, roryabraham commented
@thesahindia try following the instructions in [this comment](https://github.com/Expensify/App/pull/12754#issuecomment-1315885307) in this PR

2022-11-15 21:52 UTC, thesahindia commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>


https://user-images.githubusercontent.com/83179295/199067154-96b95560-38c6-49e1-adcf-3f41cd1e93c7.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/83179295/199067180-3277b9a2-08d4-4204-bba1-469a05f5bb02.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/83179295/199067204-b095bd91-dfc0-4c3a-9669-fcd217a7f5ad.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/83179295/199067237-d9675571-232c-42f7-95ae-bc6e61248e34.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/83179295/199067295-88a0c786-6895-42f6-83e1-91d2c9543032.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/83179295/199067268-cf167f6d-8528-4ef6-88f7-86778f635fc3.mov

</details>

2022-11-15 21:53 UTC, thesahindia approved these changes

2022-11-15 21:53 UTC, merged

2022-11-15 21:57 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-11-17 08:25 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3486190647) to staging by @roryabraham in version: 1.2.29-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2022-11-22 17:05 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3525034437) to production by @AndrewGable in version: 1.2.29-7 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅