[HOLD Web-E] Add new Display Name page
Expensify/App pull request #12142
Opened 2022-10-26 14:24 UTC by Beamanator

### Details

### Fixed Issues
$ https://github.com/Expensify/App/issues/11572

### Tests
Coming (see design doc)

- [ ] Verify that no errors appear in the JS console

### QA Steps
TBD

- [ ] Verify that no errors appear in the JS console

### PR Review Checklist

#### PR Author Checklist
- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The reviewer will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
     [...]

2022-10-26 14:25 UTC, Beamanator commented on src/languages/es.js
> +        isShownOnProfile: 'Su nombre para mostrar se muestra en su perfil.',
Getting confirmation on these here: https://expensify.slack.com/archives/C21FRDWCV/p1666786645260019

2022-10-27 14:26 UTC, Beamanator commented on src/languages/es.js
> +        isShownOnProfile: 'Su nombre para mostrar se muestra en su perfil.',
Got confirmation

2022-11-01 13:05 UTC, Beamanator commented
@eVoloshchak FYI you probably can't test this yet, till the server-side changes make it to Staging

2022-11-02 14:57 UTC, eVoloshchak commented
I don't have the bandwidth right now, could you unassign me please?

2022-11-02 15:52 UTC, Beamanator commented
Thanks for letting me know @eVoloshchak !

2022-11-02 15:53 UTC, Beamanator commented
@stitesExpensify do you have time to test this or do you prefer we assign a new C+? FYI it's not possible for C+ to test in staging **YET** (waiting on a Web-E PR)

2022-11-02 16:03 UTC, stitesExpensify commented
I can test it. I'll try to get to it today

2022-11-02 17:25 UTC, Beamanator commented
Thanks @stitesExpensify !

2022-11-02 22:25 UTC, stitesExpensify commented
I'll do this tomorrow. Looks like web is still in review as well

2022-11-03 19:10 UTC, stitesExpensify requested changes
FYI the offline test does not appear to be working (on both android/web, and web/incognito). LMK if I'm doing something wrong


https://user-images.githubusercontent.com/42391420/199812517-9db52048-6f57-4d38-944a-e2bd9d02783c.mp4

2022-11-04 11:33 UTC, Beamanator commented
Huh I swear that was working when I tested 😆

2022-11-04 11:44 UTC, Beamanator commented
Weird, I just tested (Chrome, normal + incognito) and I saw it working as expected 😡 Video:

https://user-images.githubusercontent.com/3885503/199964566-e4695285-1f5e-4a5c-b10b-915c515c085a.mov

Just to make sure, you did pull `main` in Web-E right?

2022-11-04 14:52 UTC, stitesExpensify commented
hmm I could have sworn I did, but I'll try again!

2022-11-07 16:01 UTC, Beamanator commented
Merging main so we're testing on latest 👍

2022-11-07 16:34 UTC, stitesExpensify commented
Sorry for the delay, I found out that my local pusher was broken which caused it to not work (obviously). Test passed!

2022-11-07 16:47 UTC, stitesExpensify approved these changes
Code looks great! Nice work!

2022-11-07 16:47 UTC, merged

2022-11-07 16:53 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-11-08 10:10 UTC, Beamanator commented
Removing emergency label, I guess the PR reviewer checklist may not have been filled out when this was merged 😅

2022-11-08 15:35 UTC, stitesExpensify commented
I could have sworn I checked all of those boxes 🙃 My bad

2022-11-08 19:38 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3422214865) to staging by @stitesExpensify in version: 1.2.25-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-11-09 21:13 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3431746197) to production by @yuwenmemon in version: 1.2.25-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅