add Other hub and update description in hub pages
Expensify/App pull request #12270
Opened 2022-10-28 21:02 UTC by marcochavezf

cc @roryabraham 

### Details

Coming from this [convo](https://expensify.slack.com/archives/C02QSAC6BJ8/p1666978058174249?thread_ts=1665788470.427459&cid=C02QSAC6BJ8), we want to [remove](https://github.com/Expensify/App/pull/12248) the `Coming soon` page, but there are some changes that need to be done first. Some those changes included in this PR are:
- Add the `Other` hub in the homepage and LHN.
- Update descriptions for the hub pages (Send money, Request money and Other).
- Remove the dummy text (lorem ipsum).

### Fixed Issues

N/A

### Tests

Pre-requisites (only in dev):

In order to run the site locally you would need ruby and bundler installed in your machine, more info [here](https://github.com/Expensify/App/tree/main/docs#pre-requisites).

Then just execute the following commands in your command-line:
```
cd docs
bundle install
bundle exec jekyll serve
```

Steps:

1. Open the site (http://localhost:4000/main in dev, https://help.expensify.com/main in production)
2. Verify the Other hub is displayed on both the homepage and the LHN.
3. Navigate to the other hubs and verify the description is updated according to [these comments](https://github.com/Expensify/Expensify/issues/238867#issuecomment-1295326508).
4. Verify the navigation is working correctly between hub pages, articles, and the home page.
5. Verify there's no `lorem ipsum` text anymore in the homepage.

- [x] Verify that no errors appear in the JS console

### QA Steps

Same steps as `Test` section (test only in production).

- [ ] Verify that no errors appear in the JS console

### PR Review Checklist

#### PR Author Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The reviewer will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all pl [...]

2022-10-31 13:32 UTC, mananjadhav commented
@marcochavezf Could you please help me with the context for this one?  Are these pages for new expensify app?

2022-10-31 14:58 UTC, johncschuster commented
@mananjadhav These are pages for our new help site. For a bit of historical context, we've been using a community forum platform (vanillaforums) to host our help site for a few years but found the platform doesn't serve us well, so we opted to move to use GitHub Pages to host our help site articles.

Does that help? Let me know if you need any more context!

2022-10-31 16:19 UTC, mananjadhav commented
Okay thanks @johncschuster. I’ll get to it in a few hours

2022-10-31 17:00 UTC, grgia approved these changes
LGTM 
<img width="1776" alt="Screen Shot 2022-10-31 at 9 59 24 AM" src="https://user-images.githubusercontent.com/38015950/199065584-2dd9c73d-1340-4c5f-9677-a77be0487e3f.png">
<img width="1776" alt="Screen Shot 2022-10-31 at 9 59 31 AM" src="https://user-images.githubusercontent.com/38015950/199065570-c94cf570-a6bc-450d-9d36-85af5e901b4b.png">

2022-10-31 17:16 UTC, roryabraham commented on docs/_sass/_main.scss
> -    @include card-border($color-gray2, 1px);
Why did we just get rid of the card-borders? I really liked them stylistically and couldn't find any context for that decision.

2022-10-31 17:16 UTC, roryabraham requested changes
Why did we just get rid of the colored card borders? I really liked them stylistically and couldn't find any context for that decision.

2022-10-31 17:17 UTC, roryabraham commented
Oh, looks like it just came from [here](https://github.com/Expensify/Expensify/issues/238765#issue-1424335010)

2022-10-31 17:31 UTC, marcochavezf commented
> Why did we just get rid of the colored card borders? I really liked them stylistically and couldn't find any context for that decision.

Ah yup, the design was updated in this [GH](https://github.com/Expensify/Expensify/issues/236858).

2022-10-31 18:45 UTC, roryabraham approved these changes
LGTM, tests well. We don't need C+ reviews on HelpDot PRs, because it's a totally separate beast and still behind beta.

2022-10-31 18:45 UTC, merged

2022-10-31 18:46 UTC, roryabraham commented
Not an emergency, just ignored the NewDot checklist for this HelpDot PR. Probably shouldn't do that in the future.

2022-10-31 18:47 UTC, mananjadhav commented
Ohh! @roryabraham I just did all the testing and was about to submit the screenshots.

<img width="370" alt="Screenshot 2022-11-01 at 12 16 51 AM" src="https://user-images.githubusercontent.com/3069065/199085910-dc4edf73-b732-47cb-bbf7-d413a3859d7e.png">

<img width="1496" alt="Screenshot 2022-11-01 at 12 16 18 AM" src="https://user-images.githubusercontent.com/3069065/199085937-8e14df4f-48b6-468a-b860-c2e75f532eaf.png">

2022-10-31 18:50 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-10-31 18:52 UTC, roryabraham commented
No worries, we can make the payment in this case

> We don't need C+ reviews on HelpDot PRs

This isn't an "official policy", just my opinion that hasn't been widely discussed. We can issue the payment this time since you did the work.

2022-10-31 18:59 UTC, mananjadhav commented
Okay thanks for the consideration.

2022-11-02 20:22 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3380275664) to staging by @roryabraham in version: 1.2.23-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-11-03 02:45 UTC, johncschuster commented
Adding myself to the Assignee list to get an Upwork job put together. I'll ping you when I've got that created, @mananjadhav 👍

2022-11-11 11:38 UTC, mananjadhav commented
@johncschuster @marcochavezf This is deployed on production for 7 days and eligible for C+ Review payment. Can someone please help with this?

2022-11-12 00:14 UTC, marcochavezf commented
Sure, I asked [internally](https://expensify.slack.com/archives/C01SKUP7QR0/p1668211886107129) how to proceed with the payment.

2022-11-14 04:00 UTC, mananjadhav commented
@marcochavezf Did you get anyone to help with this?

2022-11-14 18:10 UTC, marcochavezf commented
Hey @mananjadhav, @dylanexpensify will help us to proceed with the payment 👍🏽

2022-11-14 18:38 UTC, mananjadhav commented
Okay thanks for the update and thanks @dylanexpensify for taking this up.

2022-11-15 08:38 UTC, dylanexpensify commented
Upwork here: https://www.upwork.com/jobs/~01902bdefab70e957b let's get you paid!!! @mananjadhav

2022-11-15 08:40 UTC, mananjadhav commented
@dylanexpensify Applied.

2022-11-15 09:27 UTC, dylanexpensify commented
Offer sent!

On Tue, Nov 15, 2022 at 8:40 AM Manan ***@***.***> wrote:

> @dylanexpensify <https://github.com/dylanexpensify> Applied.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Expensify/App/pull/12270#issuecomment-1314972419>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOKVCAC4ELMMII2OQARWVZ3WIND73ANCNFSM6AAAAAARRNMTPE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-15 13:01 UTC, dylanexpensify commented
payment sent, job closed, contract ended