Subscribe report event when report successfully created
Expensify/App pull request #12365
Opened 2022-11-02 07:27 UTC by mollfpr

### Details

The subscribe event pusher `AuthenticatePusher` failed to load after creating a report chat/group or workspace room. This happens because the optimistic data is not yet successful, and the server couldn't find the `reportID` provided.

We should wait for the optimistically created report success first before starting subscribing to the reported event `Report.subscribeToReportTypingEvents`.

### Fixed Issues

$ https://github.com/Expensify/App/issues/11800   
$ https://github.com/Expensify/App/issues/11800#issuecomment-1296259755

### Tests

**Test on Web/Desktop with inspect element open**
1. Login with the beta account (such as _applausetester+0704sveta@applause.expensifail.com_)
2. Click on FAB then **New Room** / **New Chat** / **New Group**
3. Enter the data to create a **New Room** / **New Chat** / **New Group**
4. Verified that when the command `AuthenticatePusher` was called in the **Network** tab it returned a `200` status response.

- [x] Verify that no errors appear in the JS console

### QA Steps

**Test on Web/Desktop with inspect element open**
1. Login with the beta account (such as _applausetester+0704sveta@applause.expensifail.com_)
2. Click on FAB then **New Room**
3. Enter the data to create a New Room
4. Verified that when the command `AuthenticatePusher` was called in the **Network** tab is returned a `200` status response.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The reviewer will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos fo [...]

2022-11-02 20:45 UTC, dangrous commented on src/pages/home/report/ReportActionsView.js
> +        const didReportSuccessfullyCreated = !this.props.report.pendingFields
Making this a bit cleaner
```suggestion
        const didCreateReportSuccessfully = !this.props.report.pendingFields
```

2022-11-02 20:45 UTC, dangrous commented on src/pages/home/report/ReportActionsView.js
> +        if (!this.didSubscribeToReportTypingEvents && didReportSuccessfullyCreated) {
```suggestion
        if (!this.didSubscribeToReportTypingEvents && didCreateReportSuccessfully) {
```

2022-11-02 20:48 UTC, dangrous commented on src/pages/home/report/ReportActionsView.js
> +        // The other reports created will have empty field on `pendingFields`.
```suggestion
        // Ensures subscription event succeeds when the report/workspace room is created optimistically.
        //  Check if the optimistic `OpenReport` or `AddWorkspaceRoom` has succeeded by confirming
        // any `pendingFields.createChat` or `pendingFields.addWorkspaceRoom` fields are set to null.
        // Existing reports created will have empty fields for `pendingFields`.
```

2022-11-02 20:49 UTC, dangrous requested changes
Just a couple changes to make the code a bit clearer.

Can you double check that the typing events are actually coming through, on both the newly created as well as existing reports? Thanks!

2022-11-02 22:06 UTC, thesahindia commented
I just saw that `componentDidUpdate` doesn't get called on navigating to a chat in some cases which will cause problem. I will try looking into it in the morning. (It's 3 am for me right now)

@mollfpr, let me know if you find something before me.

2022-11-03 13:43 UTC, thesahindia commented
> I just saw that `componentDidUpdate` doesn't get called on navigating to a chat in some cases, which will cause problem. I will try looking into it in the morning. (It's 3 am for me right now)

Umm it's strange, I found that it is only happening with 2-3 specific chats. It's a different issue so I think we can move forward.

2022-11-03 13:49 UTC, thesahindia commented on src/pages/home/report/ReportActionsView.js
> +        //  Check if the optimistic `OpenReport` or `AddWorkspaceRoom` has succeeded by confirming
NAB:
```suggestion
        // Check if the optimistic `OpenReport` or `AddWorkspaceRoom` has succeeded by confirming
```

2022-11-03 13:52 UTC, thesahindia commented
@mollfpr, please try to keep the commit message specific to the change. For example when changing the comment you can use "update comment".

2022-11-03 14:08 UTC, mollfpr commented
Thanks @thesahindia I’ll keep that in mind.

2022-11-03 16:32 UTC, thesahindia commented
<details>
<summary>
Screenshots
</summary>

**Web**


https://user-images.githubusercontent.com/83179295/199776786-14e714f2-d9d0-4883-8745-6c3b2b1c0335.mov











**Mobile Web - Chrome**


<img width="329" alt="Screenshot 2022-11-03 at 9 45 40 PM" src="https://user-images.githubusercontent.com/83179295/199776242-69638166-e2d5-46d3-94b5-0ce735c82592.png">






**Mobile Web - Safari**

<img width="344" alt="Screenshot 2022-11-03 at 9 10 04 PM" src="https://user-images.githubusercontent.com/83179295/199776272-558b7e2b-52ef-4b9a-af12-f58e1855f173.png">









**Desktop**

https://user-images.githubusercontent.com/83179295/199776300-dbdb3714-8506-4f7e-8162-b991703b0438.mov








**iOS**






<img width="344" alt="Screenshot 2022-11-03 at 9 08 43 PM" src="https://user-images.githubusercontent.com/83179295/199776613-73b76725-a941-41c8-847e-84bd5e709989.png">




**Android**

<img width="329" alt="Screenshot 2022-11-03 at 9 46 34 PM" src="https://user-images.githubusercontent.com/83179295/199777582-8e0db2d6-ec7b-4933-90ab-5f363983c29a.png">





</details>

LGTM!

cc: @dangrous 

C+ reviewed 🎀👀🎀

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

2022-11-03 16:32 UTC, thesahindia approved these changes

2022-11-03 16:53 UTC, dangrous commented on src/pages/home/report/ReportActionsView.js
> +        //  Check if the optimistic `OpenReport` or `AddWorkspaceRoom` has succeeded by confirming
Oops that was me, sorry!

2022-11-03 18:34 UTC, dangrous approved these changes
LGTM!

2022-11-03 18:35 UTC, merged

2022-11-03 18:40 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-11-04 17:52 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3395575377) to staging by @dangrous in version: 1.2.24-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-11-08 19:38 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3422206876) to production by @yuwenmemon in version: 1.2.24-4 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2022-11-08 21:07 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3422206876) to production by @yuwenmemon in version: 1.2.24-4 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2022-11-08 21:38 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3422206876) to production by @yuwenmemon in version: 1.2.24-4 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅