Collapse multiple consecutive spaces into a single space
Expensify/App pull request #12968
Opened 2022-11-23 19:51 UTC by aldo-expensify

Part a group of PRs to:
- make the optimistic conversion from `message[0].html` to `message[0].text` consistent with what the API does here:
- improve the consecutive whitespace collapsing into a single whitespace

https://github.com/Expensify/expensify-common/pull/474: `ExpensiMark.htmlToText` no longer collapse multiple `<br />` into a single space

### Details

### Fixed Issues

$ GH_LINK   
PROPOSAL: GH_LINK_ISSUE(COMMENT)

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The reviewer will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for expected offline behavior are in the `Offline steps` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos  [...]

2022-11-30 01:57 UTC, aldo-expensify commented on src/pages/home/report/ReportActionItemFragment.js
>              // This is done to render emojis with line breaks between them as text.
I'm guessing that rendering something with `<Text>` instead of `<RenderHTML>` is more performant too.

2022-11-30 21:36 UTC, aldo-expensify commented
Done!

2022-11-30 23:03 UTC, aldo-expensify commented
> @aldo-expensify Is it possible that [Web-Expensify/pull/35658](https://github.com/Expensify/Web-Expensify/pull/35658) introduced this _bug_? (can't be accessed externally)

Nop, this PR has not reached production yet. Good thinking in testing with offline though :)

That's probably another "bug" we could tackle in a different set of PR because it being caused by something different

2022-11-30 23:25 UTC, rushatgabhane requested changes
> that is normal behaviour for markdown I think, I'm not sure if we would want to change it

nice catch, i agree.

@aldo-expensify 
small bug: sending a single message with multiple lines, only shows the first line in LHN.


1. send this message
```
line 1
line 2
```
2. check that LHN shows "line 1" only.
3. after `API.AddComment` is complete, LHN show "line 1 line 2"

What should be the expected result? We could change the server side to show "line 1" only.
But we must be showing all lines for a reason. So let's update the client side to show  all lines seperated by a space.

What do you think?

https://user-images.githubusercontent.com/29673073/204929160-ba677c85-d44f-40f5-8160-0d92fedfab85.mov

2022-11-30 23:57 UTC, aldo-expensify commented
> > that is normal behaviour for markdown I think, I'm not sure if we would want to change it
> 
> nice catch, i agree.
> 
> @aldo-expensify small bug: sending a single message with multiple lines, only shows the first line in LHN.
> 
> 1. send this message
> 
> ```
> line 1
> line 2
> ```
> 
> 2. check that LHN shows "line 1" only.
> 3. after `API.AddComment` is complete, LHN show "line 1 line 2"
> 
> What should be the expected result? We could change the server side to show "line 1" only. But we must be showing all lines for a reason. So let's update the client side to show all lines seperated by a space.

Yes, this is because the server side PR https://github.com/Expensify/Web-Expensify/pull/35658 has not been merged and deployed yet.. so when you get the response, it is the old way of calculating `lastMessateText`. I think you should only test this offline so you don't get confused by whatever outdated thing the server is responding. There will be a few days with these glitches while the front and back end PR are not in production at the same time, and I don't see an easy way to avoid it.

2022-12-01 04:25 UTC, rushatgabhane approved these changes
## Reviewer Checklist

@MariaHCD LGTM! 

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.


### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/29673073/204964448-1cc0b09e-95c3-4ba0-b68c-e36819100225.mov


</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/29673073/204965301-c9f553ee-d8aa-4c03-8289-501adba0725d.mp4



</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/29673073/204965440-f1a3dc4f-4fb7-477a-bda6-f69dd424a2d3.mov


</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/29673073/204966278-fc89454d-21ed-4356-ab33-200b752b61e0.mov



</details>

<details>
<summary>iOS</summary>


https://user-images.githubusercontent.com/29673073/204965795-6b849da3-c6f5-43df-b610-68216f7f12d6.mov


</details>

<details>
<summary>Android</summary>


https://user-images.githubusercontent.com/29673073/204962683-188f86b3-0005-43aa-919e-c043cbf250bb.mp4


</details>

2022-12-01 20:49 UTC, aldo-expensify commented
@rushatgabhane I thought a bit more about this: https://github.com/Expensify/App/pull/12968#issuecomment-1332839662

I think maybe we should report it as a separate bug because it is inconsistent with other cases. In markdown, many line breaks together always get collapsed into one:

![image](https://user-images.githubusercontent.com/87341702/205156323-51780bfe-61ac-4f19-8c42-257c2c849290.png)

but this is not the case in our chat, we respect all line breaks except when it comes to two consecutive quoted blocks. I think the [argument](https://github.com/Expensify/App/pull/12968#issuecomment-1332849555) I made about it being like that in markdown doesn't apply here.

2022-12-02 17:47 UTC, MariaHCD approved these changes

2022-12-02 17:48 UTC, merged

2022-12-02 17:54 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-12-02 19:42 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3604247225) to staging by @MariaHCD in version: 1.2.36-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-12-08 02:03 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3644465624) to production by @francoisl in version: 1.2.36-4 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅