Password toggle cursor state
Expensify/App pull request #13103
Opened 2022-11-28 21:23 UTC by Someone-here

@Julesssss  @eVoloshchak 

### Details

Added a checkbox native file that takes care of the events `onMouseDown` and `onPress` which seem to be causing this issue.

### Fixed Issues

$ https://github.com/Expensify/App/issues/12018
PROPOSAL: https://github.com/Expensify/App/issues/12018#issuecomment-1314225656

### Tests

1. Click on the password text input to bring it into focus
2. Enter some text
3. Press the show/hide button
4.  Notice that cursor stays on the same place

- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

1. Click on the password text input to bring it into focus
2. Enter some text
3. Press the show/hide button
4.  Notice that cursor stays on the same place

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The reviewer will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for expected offline behavior are in the `Offline steps` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I checked that screenshots or videos are incl [...]

2022-11-28 21:32 UTC, Someone-here commented
Hey, This is a new PR. I closed the previous one by mistake. I hope you understand

2022-11-29 18:00 UTC, Julesssss commented
Hey @Someone-here, unfortunately I think you'll need to resubmit the PR with signed commits as [this test](https://github.com/Expensify/App/actions/runs/3568771259/jobs/6014910167#step:2:6) is failing and we have no way to override it.

2022-11-29 18:03 UTC, Someone-here commented
Okay, I'll fix the styling and sign the commit. And Do you mean that I should create a new branch from the forked repo and open a new PR from that?

2022-11-29 18:09 UTC, Julesssss commented
> Okay, I'll fix the styling and sign the commit. And Do you mean that I should create a new branch from the forked repo and open a new PR from that?

Yeah, that's how I'm usually able to test a PR. Thanks for your patience here, next time should be easier :)

2022-11-29 18:10 UTC, Someone-here commented
Okay, so should I close this PR now?

2022-11-29 18:30 UTC, Someone-here commented
I fixed the styling and signed with gpg key as well.

2022-11-30 02:13 UTC, Someone-here commented
Please once try to test the commit if possible on this branch. In the future, I will always make PR from a new branch in the fork

2022-11-30 12:53 UTC, eVoloshchak commented
@Someone-here, the signed commits check is failing, could you please [rebase](https://superuser.com/questions/397149/can-you-gpg-sign-old-commits) your commits with the signed ones? (all of the commits have to be signed)

2022-11-30 13:06 UTC, eVoloshchak requested changes

2022-11-30 13:07 UTC, Someone-here commented on src/components/Checkbox/BaseCheckbox.js
> +        if (props.onPress && props.onMouseDown) {
Okay, sure! Will do now

2022-11-30 13:07 UTC, Someone-here commented
> @Someone-here, the signed commits check is failing, could you please [rebase](https://superuser.com/questions/397149/can-you-gpg-sign-old-commits) your commits with the signed ones? (all of the commits have to be signed)
> 
> Or it's probably easier to create a new PR, that will allow you to open it from a branch in your forked repo

Okay, then I'll create a new PR....

2022-11-30 13:10 UTC, eVoloshchak commented
> Okay, then I'll create a new PR....

It's up to you, you can just rebase the commits if that's more convenient

2022-11-30 13:46 UTC, Someone-here commented
Made the new PR https://github.com/Expensify/App/pull/13187
Please close this if you wish

2022-11-30 14:54 UTC, eVoloshchak commented
> Made the new PR #13187 Please close this if you wish

I think only the author can close the PR

2022-11-30 14:59 UTC, Someone-here commented
Ok, closing.

2022-11-30 14:59 UTC, closed without merging