Add a created report action for bill splits
Expensify/App pull request #13465
Opened 2022-12-09 01:28 UTC by neil-marcellini

### Details

### Related Issues

$ https://github.com/Expensify/Expensify/issues/247417
PROPOSAL: N/A

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

</details>

2022-12-22 01:59 UTC, neil-marcellini commented
I know this is on hold but I could still use an early review @danieldoglas. Also @chiragsalian @youssef-lr @flodnv if you can take a look.

2023-01-03 16:35 UTC, danieldoglas submitted a review, later dismissed
LGTM

2023-01-03 16:35 UTC, danieldoglas commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Mobile Web - Chrome</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Mobile Web - Safari</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Desktop</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>iOS</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Android</summary>

<!-- add screenshots or videos here -->

</details>

2023-01-12 17:58 UTC, flodnv commented
@danieldoglas this is ready for you to test please 🙇 Make sure you're on the latest main of Web-E and Auth (just merged some PRs there)

2023-01-12 18:19 UTC, danieldoglas commented
Will test it now, building auth locally.

2023-01-12 18:47 UTC, danieldoglas commented
@neil-marcellini,

Test A, step 2

![image](https://user-images.githubusercontent.com/5818999/212152851-854378e4-b5d1-4f1e-a1f7-a203c06d31d2.png)

2023-01-12 18:48 UTC, danieldoglas requested changes

2023-01-12 18:48 UTC, danieldoglas commented on src/libs/actions/IOU.js
> +            createdReportActionID: groupCreatedReportActionData[0].reportActionID,
This line too

2023-01-13 13:04 UTC, flodnv commented
@danieldoglas my bad, sorry 🤦 Updated and actually tested this time

2023-01-13 14:39 UTC, danieldoglas commented
So, for the test cases that were described in the PR, it worked as expected. But there's a new warning in the console:

There's also a new warning in console.
```
Warning: Failed prop type: The prop `iouReport` is marked as required in `IOUAction`, but its value is `undefined`.
    at IOUAction (webpack-internal:///./src/components/ReportActionItem/IOUAction.js:81:36)
    at withNetwork(IOUAction)
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2095:73)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at ReportActionItemSingle (webpack-internal:///./src/pages/home/report/ReportActionItemSingle.js:78:20)
    at withPersonalDetails(ReportActionItemSingle)
    at withLocalize(withPersonalDetails(ReportActionItemSingle))
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at OfflineWithFeedback (webpack-internal:///./src/components/OfflineWithFeedback.js:101:85)
    at withNetwork(OfflineWithFeedback)
    at withLocalize(withNetwork(OfflineWithFeedback))
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at Hoverable (webpack-internal:///./src/components/Hoverable/index.js:39:86)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at Pressable (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/Pressable/index.js:40:24)
    at PressableWithSecondaryInteraction (webpack-internal:///./src/components/PressableWithSecondaryInteraction/index.js:43:86)
    at ReportActionItem (webpack-internal:///./src/pages/home/report/ReportActionItem.js:127:86)
    at withReportActionsDrafts_(ReportActionItem)
    at withPrivate_blockedFromConcierge(withReportActionsDrafts_(ReportActionItem))
    at withNetwork(withPrivate_blockedFromConcierge(withReportActionsDrafts_(ReportActionItem)))
    at withWindowDimensions(withNetwork(withPrivate_blockedFromConcierge(withReportActionsDrafts_(ReportActionItem))))
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at VirtualizedListCellContextProvider (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/VirtualizedList/VirtualizedListContext.js:73:23)
    at CellRenderer (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/VirtualizedList/index.js:1475:86)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/ScrollView/ScrollViewBase.js:68:24)
    at eval (webpack-internal:///./node_modules/create-react-class/factory.js:897:37)
    at ScrollView
    at VirtualizedListContextProvider (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/VirtualizedList/VirtualizedListContext.js:44:24)
    at VirtualizedList (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/VirtualizedList/index.js:170:86)
    at FlatList (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/FlatList/index.js:181:86)
    at BaseInvertedFlatList (webpack-internal:///./src/components/InvertedFlatList/BaseInvertedFlatList.js:60:86)
    at InvertedFlatList (webpack-internal:///./src/components/InvertedFlatList/index.js:52:86)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at AnimatedComponent (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js:59:88)
    at AnimatedComponentWrapper
    at ReportActionsList (webpack-internal:///./src/pages/home/report/ReportActionsList.js:102:86)
    at withNetwork(ReportActionsList)
    at withPersonalDetails(withNetwork(ReportActionsList))
    at withWindowDimensions(withPersonalDetails(withNetwork(ReportActionsList)))
    at WithDrawerState (webpack-internal:///./src/components/withDrawerState.js:23:92)
    at ReportActionsView (webpack-internal:///./src/pages/home/report/ReportActionsView.js:106:86)
    at withNetwork(ReportActionsView)
    at withLocalize(withNetwork(ReportActionsView))
    at withWindowDimensions(withLocalize(withNetwork(ReportActionsView)))
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at FullPageNotFoundView (webpack-internal:///./src/components/BlockingViews/FullPageNotFoundView.js:59:13)
    at withLocalize(FullPageNotFoundView)
    at Suspender (webpack-internal:///./node_modules/react-freeze/dist/index.modern.js:10:21)
    at Suspense
    at Freeze (webpack-internal:///./node_modules/react-freeze/dist/index.modern.js:30:22)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at KeyboardAvoidingView
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at SafeAreaConsumer
    at ScreenWrapper (webpack-internal:///./src/components/ScreenWrapper/index.js:64:86)
    at withNetwork(ScreenWrapper)
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2095:73)
    at withWindowDimensions(Component)
    at WithNavigation (webpack-internal:///./src/components/withNavigation.js:23:93)
    at ReportScreen (webpack-internal:///./src/pages/home/ReportScreen.js:158:86)
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2095:73)
    at withNetwork(Component)
    at WithDrawerState (webpack-internal:///./src/components/withDrawerState.js:23:92)
    at withWindowDimensions(Component)
    at withLocalize(withWindowDimensions(Component))
    at StaticContainer (webpack-internal:///./node_modules/@react-navigation/core/lib/module/StaticContainer.js:13:16)
    at EnsureSingleNavigator (webpack-internal:///./node_modules/@react-navigation/core/lib/module/EnsureSingleNavigator.js:17:5)
    at SceneView (webpack-internal:///./node_modules/@react-navigation/core/lib/module/SceneView.js:23:5)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at Background (webpack-internal:///./node_modules/@react-navigation/elements/lib/module/Background.js:16:5)
    at Screen (webpack-internal:///./node_modules/@react-navigation/elements/lib/module/Screen.js:24:102)
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)
    at NativeScreen (webpack-internal:///./node_modules/react-native-screens/lib/module/index.js:58:1)
    at AnimatedComponent (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js:5 [...]

2023-01-13 19:53 UTC, roryabraham commented
> There's also a new warning in console ... Failed prop type: The prop `iouReport` is marked as required in `IOUAction`, but its value is `undefined`

I don't know if this was a _new_ warning, but it should be fixed now

2023-01-13 20:33 UTC, roryabraham commented
While testing this I did encounter a duplicate IOU action on a report:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/47436092/212413817-ee3b486c-46b7-4985-b61b-50ef02e0c9ed.png">

<img width="711" alt="image" src="https://user-images.githubusercontent.com/47436092/212414040-db681f1a-77bb-4816-90c7-3bd2bdb15d9d.png">

```
Warning: Encountered two children with the same key, `.$79836681347098461`.
```

2023-01-13 20:54 UTC, roryabraham commented
Pushed a fix to the duplicate IOU actions even though the bug wasn't introduced by this PR.

2023-01-13 20:58 UTC, roryabraham commented
I also noticed that when you create a new group in the Split Bill flow originating from the global create menu, the optimistically created group chat does not appear in the LHN.

2023-01-13 21:49 UTC, thienlnam commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Mobile Web - Chrome</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Mobile Web - Safari</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Desktop</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>iOS</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Android</summary>

<!-- add screenshots or videos here -->

</details>

2023-01-13 22:05 UTC, thienlnam commented
<img width="378" alt="Screenshot 2023-01-13 at 2 01 41 PM" src="https://user-images.githubusercontent.com/30609178/212427358-504a891a-698f-4103-a20f-f7a4c2c9381d.png">

I'm still consistently running into the bug you mentioned here https://github.com/Expensify/App/pull/13465#issuecomment-1382358556

From the global create menu, split a bill with 1 person you DO NOT have an existing chat with

https://user-images.githubusercontent.com/30609178/212427885-65c95629-63bd-4690-ac1b-aaa8de960ac8.mov

2023-01-13 23:03 UTC, roryabraham commented
Good testing @thienlnam, it was still happening when you split a bill with only one person. Created https://github.com/Expensify/Web-Expensify/pull/36080 to fix this.

2023-01-16 21:29 UTC, mountiny commented
@danieldoglas @thienlnam This is off hold!

2023-01-16 22:01 UTC, roryabraham commented
For transparency, there is an _existing and unrelated_ problem with the offline Split Bill flow which was not introduced by this PR, and which I reported [here](https://expensify.slack.com/archives/C049HHMV9SM/p1673903364260589)

2023-01-16 22:08 UTC, danieldoglas commented
I've created a Split with someone that never used Expensify, and the action duplicated in the chat

![image](https://user-images.githubusercontent.com/5818999/212772516-56c3aa94-783e-4177-ad5f-ff025c794295.png)

2023-01-16 22:09 UTC, roryabraham commented
@danieldoglas can you please confirm that you are:

1. On an up-to-date version of Auth main
1. Have rebuilt Auth and restarted the Auth service in the VM
1. On an up-to-date version on Web-Expensify main

?

2023-01-16 22:14 UTC, danieldoglas commented
I'm using production API, which has Web-E and Auth on latest version with the PRs that this depended on deployed. So this shouldn't be happening

2023-01-16 22:17 UTC, danieldoglas commented
I think it's something in the app, since one of those is appearing on top of the avatar with the `Beginning of the you chat` message. 

The request is `78aa30ff9f13a51d-SAN`

2023-01-16 23:53 UTC, danieldoglas approved these changes
LGTM

2023-01-16 23:54 UTC, merged

2023-01-18 18:13 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/3951140881) to staging by @danieldoglas in version: 1.2.56-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅