Fix linking to account for staging URLs
Expensify/App pull request #14487
Opened 2023-01-23 22:08 UTC by jasperhuangg

### Details
The code here handles

### Fixed Issues

$ GH_LINK   
PROPOSAL: GH_LINK_ISSUE(COMMENT)

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

</details>

2023-01-23 23:07 UTC, alex-mechler approved these changes

2023-01-23 23:07 UTC, alex-mechler commented
> This updates it to also handle NewDot URLs.

Should this say staging?

2023-01-23 23:09 UTC, alex-mechler requested changes
Actually, your QA steps should be updated. If the link is clicked in desktop, it should be opened in the desktop app as well. In addition, please provide videos of you testing this

2023-01-24 17:10 UTC, Santhosh-Sellavel commented
PR is failing for me, I set up the environment as STAGING in .env.

Still navigates to the old dot 

https://user-images.githubusercontent.com/85645967/214360622-791f163e-54fc-428d-a7f3-fa164148ff4e.mov

@alex-mechler does it passes for you? 

cc: @jasperhuangg

2023-01-24 17:50 UTC, jasperhuangg commented
Hey guys sorry, I should have left this on draft, was about to test it but something came up last minute. I'm gonna put this back on draft for the time being.

2023-01-24 17:55 UTC, Santhosh-Sellavel reviewed
Adding myself as a reviewer!

2023-01-30 23:41 UTC, jasperhuangg commented
I'm testing this locally and I can't seem to get it to navigate me to OldDot (without my changes), it just opens the report in the same client as expected. I'm checking to see if there were any PRs merged that aren't on staging yet (since this behavior still happens on staging).


https://user-images.githubusercontent.com/31285285/215621685-02e33c8c-a80d-4158-9659-449ae10b7c83.mov

2023-01-30 23:44 UTC, Santhosh-Sellavel commented
@jasperhuangg try setting environment as staging locally then perform test steps

2023-01-30 23:57 UTC, jasperhuangg commented
Figured it out, thanks @Santhosh-Sellavel I thought I had set up my `.env` correctly for staging but turns out it wasn't.

2023-01-31 00:20 UTC, jasperhuangg commented
@Santhosh-Sellavel @alex-mechler thanks for your patience, ready for review!

2023-01-31 00:39 UTC, Santhosh-Sellavel requested changes

2023-01-31 00:39 UTC, Santhosh-Sellavel commented on src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
>                                      && attrPath;
`(Url.hasSameExpensifyOrigin(attrHref, CONFIG.EXPENSIFY.EXPENSIFY_URL) || Url.hasSameExpensifyOrigin(attrHref, CONFIG.EXPENSIFY.STAGING_EXPENSIFY_URL))`

This check is not DRY, can we compute once and use it everywhere

2023-01-31 02:19 UTC, Santhosh-Sellavel approved these changes
LGTM, tests well!

2023-01-31 17:21 UTC, jasperhuangg commented
> @jasperhuangg Just asking for confirmation should it open admins chat or 1:1 with a dedicated specialist?

@Santhosh-Sellavel I'm honestly not entirely sure, I just know it's supposed to navigate directly to the report, I'm not changing how the URL is generated (that's handled in the back-end). Perhaps @alex-mechler can answer this?

2023-01-31 17:48 UTC, alex-mechler approved these changes

2023-01-31 17:50 UTC, alex-mechler commented
> Based on how there's a message from what seems like a setup specialist I think that behavior is expected though. @alex-mechler can you confirm?

Correct, the communication between the guide (setup specialist)  and the customer will largely be in the #admins room, as then other admins can also see the conversation. It is expected to go to #admins as a result


---

All you @amyevans

2023-01-31 18:57 UTC, amyevans approved these changes
Looks good!

2023-01-31 18:57 UTC, merged

2023-01-31 19:02 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-01-31 20:32 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4057634749) to staging by https://github.com/amyevans in version: 1.2.63-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-02-01 23:58 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4069689276) to production by https://github.com/thienlnam in version: 1.2.63-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅