Added Hover effect on Sidebar rows
Expensify/App pull request #1463
Opened 2021-02-11 20:12 UTC by parasharrajat

Please review.

### Details
Added existing Hoverable Component as a wrapper to the OptionRow Component and based on the hover state added a style with the Background color to show the feedback.
Now we have another prop on `OptionRow` component `hoverStyle` which takes value of `styles.sidebarLinkHover` and this prop is set to `styles.modalLinkHover` on the common ancestor of all Sidebar modals(NewChat, NewGroup,SearchView) `OptionSelector`.

### Fixed Issues
Fixes #1439

### Tests
Open the app and hover over the sidebar rows to see the feedback.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

#### Web

https://user-images.githubusercontent.com/24370807/107692744-40715300-6cd3-11eb-9c95-ca7ec2d06596.mp4

#### Desktop

https://user-images.githubusercontent.com/24370807/107692754-45ce9d80-6cd3-11eb-8a9a-39f7c51371a4.mp4

2021-02-11 20:21 UTC, shawnborton commented
Looks great!

2021-02-11 22:38 UTC, roryabraham requested changes
Overall looks pretty good – just a few small changes.

2021-02-11 22:38 UTC, roryabraham commented on src/components/OptionsSelector.js
> +                    optionHoveredStyle={[styles.modalLinkHover]}
Please refactor `styles.modalLinkHovered` and it's usages (including this one) to something more generic like `styles.hoveredComponentBG`.

2021-02-11 22:38 UTC, roryabraham commented on src/components/OptionsSelector.js
> +                    optionHoveredStyle={[styles.modalLinkHover]}
Also, there's no need for square brackets here, you could just do:

```
optionHoveredStyle={styles.hoveredComponentBG}
```
```

2021-02-11 22:38 UTC, roryabraham commented on src/pages/home/sidebar/OptionRow.js
> +    hoverStyle: PropTypes.arrayOf(PropTypes.object),
```suggestion
    hoverStyle: PropTypes.object,
```

2021-02-11 22:38 UTC, roryabraham commented on src/pages/home/sidebar/OptionRow.js
> +    hoverStyle: [],
```suggestion
    hoverStyle: styles.sidebarLinkHover,
```

2021-02-11 22:38 UTC, roryabraham commented on src/pages/home/sidebar/OptionRow.js
> +    const hoveredStyle = hoverStyle ? [styles.sidebarLinkHover, ...hoverStyle] : [styles.sidebarLinkHover];
```suggestion

```

2021-02-11 22:38 UTC, roryabraham commented on src/pages/home/sidebar/OptionRow.js
> +                        hovered && !optionIsFocused ? hoveredStyle : null,
```suggestion
                        hovered && !optionIsFocused ? hoverStyle : null,
```

2021-02-11 22:39 UTC, roryabraham commented
Also, it looks like E2E tests are failing. They can be a bit flaky, so I would push the requested changes and if they're still failing then you might have to figure out what's going wrong

2021-02-12 05:17 UTC, parasharrajat commented
Updated.

2021-02-12 05:32 UTC, roryabraham commented on src/pages/home/sidebar/OptionRow.js
> +                            <View style={styles.ml2}>
Looks like this `<View>` and its children should be indented by four more spaces.

2021-02-12 05:32 UTC, roryabraham commented on src/pages/home/sidebar/OptionRow.js
> +                            <View style={styles.ml2}>
Same with this one.

2021-02-12 05:34 UTC, roryabraham requested changes
I'm not sure why `optionHoveredStyle` needs to be a prop of the `OptionsList` component. It looks like that prop is only used once, and we're passing a static value of `styles.hoveredComponentBG`. So instead of:

1) Passing `styles.hoveredComponentBG` from `OptionsSelector` to `OptionsList`
2) Then passing it from `OptionsList` to `OptionRow`

We should just pass `styles.hoveredComponentBG` from `OptionsList` to `OptionRow`. Does that make sense?

2021-02-12 05:41 UTC, parasharrajat commented
@roryabraham `OptionList` is a generic component and it is used in different locations where we need two different designs from `OptionRow`. So by default, we gave one and one we are passing from the `OptionSelector` Component which is the common ancestor.

2021-02-12 17:32 UTC, roryabraham approved these changes
Okay, LGTM 👍

2021-02-12 17:33 UTC, merged