Conditionally require password for adding a debit card
Expensify/App pull request #15117
Opened 2023-02-14 03:02 UTC by NikkiWines

### Details
Removes password requirement for adding a debit card if user is passwordless 

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/261738
PROPOSAL: N/A

### Tests
1. Log into new Expensify with an account that is on the passwordless beta 
2. Navigate to Settings > Payments > Add Payment Method > Debit Card
3. Confirm that you do **not** see a field for the `Expensify Password` in the debit card form 
4. Fill out the form with any details but use the card number `4242424242424242`
5. Confirm you can successfully add the card 
6. Log into new Expensify with an account that is **not** on the passwordless beta 
7. Navigate to Settings > Payments > Add Payment Method > Debit Card
8. Confirm you do see the field for the `Expensify Password` in the form 
9. Fill everything out except the password 
10. Try to submit the form and confirm you're unable to do so and receive an error

- [x] Verify that no errors appear in the JS console

### Offline tests
N/A behavior is the same as online tests

### QA Steps
1. Log into new Expensify with an account that is on the passwordless beta 
2. Navigate to Settings > Payments > Add Payment Method > Debit Card
3. Confirm that you do **not** see a field for the `Expensify Password` in the debit card form 
4. Fill out the form with any details but use the card number `4242424242424242`
5. Confirm you can successfully add the card 
6. Log into new Expensify with an account that is **not** on the passwordless beta 
7. Navigate to Settings > Payments > Add Payment Method > Debit Card
8. Confirm you do see the field for the `Expensify Password` in the form 
9. Fill everything out except the password 
10. Try to submit the form and confirm you're unable to do so and receive an error

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    -[x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes  [...]

2023-02-14 03:42 UTC, NikkiWines commented
Having trouble getting the android emulator to run the app but will try again in the morning 🍀

2023-02-14 17:36 UTC, NikkiWines commented
Updated with videos for android testing, this should be all good 🚀

2023-02-14 18:10 UTC, thesahindia requested changes

2023-02-14 18:27 UTC, NikkiWines commented on src/pages/settings/Payments/AddDebitCardPage.js
> +                    {!Permissions.canUsePolicyRooms(this.props.betas) && (
Oops yes, sorry - updated!

2023-02-14 19:11 UTC, thesahindia approved these changes
Looks good to me!

cc: @chiragsalian

2023-02-14 22:09 UTC, NikkiWines commented
I just realized `src/pages/settings/AddSecondaryLoginPage.js`  and `src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js` also use a password field but will follow up with a PR for those components separately

2023-02-14 23:49 UTC, chiragsalian approved these changes
LGTM

2023-02-14 23:50 UTC, merged

2023-02-14 23:53 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-02-15 18:29 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4186486659) to staging by https://github.com/chiragsalian in version: 1.2.72-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-02-16 18:27 UTC, NikkiWines commented
Looks like this will need a supplementary auth change for it to work as expected for the passwordless flow because of the other betas required for adding a debit card. 

Testing on a non-passwordless accoutn now, just waiting for the wallet beta to be applied. 

If the non-passwordless flow goes through, I think we can go ahead with this PR since the passwordless logic isn't rolled out beyond internal employees yet.

2023-02-16 19:28 UTC, francoisl commented
Reverting this via https://github.com/Expensify/App/pull/15217, I'm going to edit the OP so it doesn't close 261738.

2023-02-16 21:37 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4198237138) to production by https://github.com/francoisl in version: 1.2.72-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅