feat: add/remove reaction
Expensify/App pull request #15210
Opened 2023-02-16 14:55 UTC by hannojg

### Details

⚠️ This is still work in progress, and not yet ready for review.

https://user-images.githubusercontent.com/16821682/219399255-22363455-3eeb-4480-9c58-09966fe4b0a7.mov

- Web implementation done as far as I can see
- Mobile app still needs to be handled

### Fixed Issues

$ https://github.com/Expensify/App/issues/15125
PROPOSAL: GH_LINK_ISSUE(COMMENT)

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

</details>

2023-02-19 16:29 UTC, hannojg commented
CLA Assistant GitHub actions seems to be broken

2023-02-19 16:31 UTC, hannojg commented
Oh, there is still one bug, hold on …

2023-02-19 17:09 UTC, stitesExpensify reviewed
Looking good! Just a couple of quick comments I noticed while reading through

2023-02-19 17:09 UTC, stitesExpensify commented on src/components/Reactions/EmojiReactionBubble.js
> +    senderIDs: PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.string, PropTypes.number])),
```suggestion
    reactionUsers: PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.string, PropTypes.number])),
```

2023-02-19 17:09 UTC, stitesExpensify commented on src/components/Reactions/MiniQuickEmojiReactions.js
> + * @returns {JSX.Element}
Same thing here, I don't think we need the `param` and `returns`

2023-02-19 17:09 UTC, stitesExpensify commented on src/components/Reactions/MiniQuickEmojiReactions.js
> +                        StyleUtils.getEmojiReactionTextStyle(1.3),
Let's move this to a variable to make it more clear what it is for

2023-02-20 12:23 UTC, hannojg commented on src/components/BaseMiniContextMenuItem.js
> + * @param {Object} props
If I don't, eslint complaints that its not a proper JSDoc comment:

![Screenshot 2023-02-20 at 13 23 25](https://user-images.githubusercontent.com/16821682/220106358-8c3c105d-8d50-4ea7-9947-2bf1baedf2bb.png)

2023-02-20 15:02 UTC, stitesExpensify commented
@0xmiroslav if you could give this an initial review today that would be much appreciated!

2023-02-20 22:53 UTC, deetergp submitted a review, later dismissed
Super exciting stuff!

2023-02-20 22:58 UTC, stitesExpensify commented on src/components/BaseMiniContextMenuItem.js
> + * @param {Object} props
Oh okay haha nvm

2023-02-22 15:22 UTC, stitesExpensify commented
My apologies if I wasn't clear before. We want to review now so that Hanno can make any necessary changes, and then this can immediately be merged when it goes off of hold

2023-02-24 20:52 UTC, stitesExpensify commented
@0xmiroslav have you had a chance to take a look at this yet?

2023-02-27 17:11 UTC, stitesExpensify reviewed
Let's update the commands so that this is calling the right thing when the API goes live (Should be on staging today)

2023-02-27 17:11 UTC, stitesExpensify commented on src/libs/actions/Report.js
> +    //     reaction: emoji.name,
This param is called `emojiCode`

2023-02-27 17:11 UTC, stitesExpensify commented on src/libs/actions/Report.js
> +    // API.write('AddReaction', parameters, {optimisticData});
the name of this is endpoint is `AddEmojiReaction`

2023-02-27 17:11 UTC, stitesExpensify commented on src/libs/actions/Report.js
> +    // API.write('RemoveReaction', parameters, {optimisticData});
`RemoveEmojiReaction`

2023-02-27 17:11 UTC, stitesExpensify commented on src/libs/actions/Report.js
> +    //     reaction: emojiCode,
`emojiCode:`

2023-03-04 17:44 UTC, hannojg commented
Hey, thx for the review!

I just added the actual API calls, however I am experiencing a bug where Onyx data changes but the connected components do not rerender (if I move the cursor away from the message, thus changing the hovering state the component gets re-rendered with the latest data):

https://user-images.githubusercontent.com/16821682/222920865-4a77888c-08c5-47df-b393-09422934bf48.mov

Not sure if anyone has seen something like that before with onyx? 
Will fix that first and then fix the bugs as named in the review.

2023-03-05 11:35 UTC, hannojg commented
@stitesExpensify When getting the `preferredSkinTone` from onyx its sometimes still `"default"`. I thought we changed that to `-1`? Can you please check what's going on there? I suspect that we didn't change the initial value somewhere?

https://github.com/Expensify/App/pull/15210/commits/e9ba4f526f4599ff29f0a6edcd28817e21204c2b

2023-03-06 13:49 UTC, stitesExpensify commented
> When getting the preferredSkinTone from onyx its sometimes still "default"

Some users probably still have "default" saved in the DB, and it won't be changed until we either:
1. Do a data migration to change that
or
2. The user manually changes their skin tone

For now I think we should just accept both

2023-03-06 15:11 UTC, stitesExpensify reviewed
Looking great! Just some minor comments!

2023-03-06 15:11 UTC, stitesExpensify commented on src/libs/actions/Report.js
> +    if (hasCurrentUserReacted) {
Let's make this inline instead of creating a var that's only used once

2023-03-06 15:11 UTC, stitesExpensify commented on src/libs/actions/Report.js
> +        r => r != null,
```suggestion
        reportObject => reportObject != null,
```

2023-03-06 17:07 UTC, stitesExpensify reviewed
Looking great! 1 more small change and I think we're good to go code wise! Testing everything now

2023-03-06 17:07 UTC, stitesExpensify commented on src/languages/es.js
> +        addReactionTooltip: 'Añadir una reacción...',
Hm this looks different than the other one. I think this is just 3 `.` instead of the `...` symbol? Let's update this one to match

2023-03-06 17:11 UTC, stitesExpensify commented
@0xmiroslav if you could give this a final review that would be much appreciated!

2023-03-06 17:34 UTC, hannojg commented
Thanks for the early feedback, will incorporate your suggestions now!

2023-03-06 17:52 UTC, hannojg commented
> can we match selected skin tone everywhere?

added

2023-03-06 17:54 UTC, hannojg commented
2. Reproduction of the bug


https://user-images.githubusercontent.com/16821682/223191190-16d06b70-f636-4d7c-be65-ea08f3356c43.mov

2023-03-06 18:01 UTC, deetergp approved these changes, later dismissed

2023-03-06 18:01 UTC, hannojg commented
2. Bug solved

2023-03-06 18:06 UTC, hannojg commented
@0xmiroslav addressed all of your suggestions

2023-03-06 18:30 UTC, stitesExpensify commented
@0xmiroslav if we could get another final review that would be great!

2023-03-06 19:01 UTC, stitesExpensify commented
@0xmiroslav can you also confirm testing on iOS for me? My environment isn't working at the moment

2023-03-06 19:13 UTC, hannojg commented
@0xmiroslav 

> When double click reaction, final result should be original reaction. For now, it works as if clicked 1 time. Or is this expected?

Sorry what do you mean by that? Do you maybe have a video recording of the behaviour you are describing?

2023-03-06 19:20 UTC, hannojg commented
@0xmiroslav oh that's a known bug, related to how we receive pusher events.
It has been discussed here: https://expensify.slack.com/archives/C01GTK53T8Q/p1678029220184279

and we agreed on fixing that not in this PR.

2023-03-06 22:00 UTC, hannojg commented
Fixed

2023-03-06 22:05 UTC, stitesExpensify approved these changes, later dismissed
Looks great!

2023-03-06 22:09 UTC, hannojg commented
The small emoji bubbles underneath the message receive a custom tooltip, as it can be seen here: 

- https://github.com/Expensify/App/pull/15671

I added the tooltip to the context menu emoji reactions

2023-03-06 22:12 UTC, hannojg commented on src/components/Reactions/QuickEmojiReactions/BaseQuickEmojiReactions.js
> +                    key={emoji.name}
man you are the best, thx for spotting those issues <3

2023-03-06 22:13 UTC, hannojg commented on src/components/Reactions/QuickEmojiReactions/BaseQuickEmojiReactions.js
> +                    key={emoji.name}
fixed

2023-03-06 22:52 UTC, stitesExpensify commented
Sounds good. If you could prioritize this in the morning it would be much appreciated as we're trying to get this merged ASAP!

2023-03-07 15:15 UTC, 0xmiroslav requested changes

2023-03-07 20:42 UTC, hannojg commented on src/components/Tooltip/index.js
> -                focusable
Okay, I turned that to a prop, which is default `true`. The perusable component automatically sets focusable to true. So when rendering the reaction bubbles for the context menu we set focusable to false, as the children will handle the focus on their own

2023-03-07 21:05 UTC, hannojg commented on src/components/withCurrentUserPersonalDetails.js
> +                    ...props.session,
oh lord, good catch, that was a temp workaround while some backend functionality wasn't there yet. Reverted that change

2023-03-07 21:20 UTC, hannojg commented on src/components/Tooltip/index.js
> -                style={this.props.containerStyles}
your reviews are the best, well catched. Probably removed that during testing. Added it back

2023-03-07 21:27 UTC, hannojg commented
The IOU issue is very likely a backend issue. As this PR has urgency for demoing purposes on expansiconx we may skip reactions for IOU messages in the frontend for now, until the backend is fixed properly.

2023-03-07 21:35 UTC, stitesExpensify commented
Great! Looks awesome to me, what about you @0xmiroslav

2023-03-07 21:47 UTC, stitesExpensify submitted a review, later dismissed
Looks great!

2023-03-08 04:03 UTC, stitesExpensify commented
@0xmiroslav we had an internal conversation and decided that because the edit message bug is a backend problem, we are okay with releasing this feature without fixing it. Apologies for not letting you know here on the issue

2023-03-08 04:14 UTC, stitesExpensify commented
> this issue and IOU message issue are temporary and should be fixed after ECX right?

That is correct, they will be fixed either after or during ECX 😄

2023-03-08 04:33 UTC, stitesExpensify commented
Nice catch! So that's (half) intentional. You can have multiple of the same reaction if there _are_ different skin tone options, but you shouldn't be able to have multiple of the same reaction if there _aren't_ different skin tone options. 

@hannojg seems like we need to update this logic to include checking if the emoji actually supports skin tones or not 

https://github.com/Expensify/App/pull/15210/files#diff-8afe5b71ee0436c21364148c86dadd640f2bff3e3d916addbb1f1f6f7e5b6a43R1234-R1245

2023-03-08 10:30 UTC, hannojg commented
Hey @0xmiroslav & @stitesExpensify in regards to this:

https://github.com/Expensify/App/pull/15210#issuecomment-1459429273

Its working as agreed in the design doc. As in slack you can add the same emoji multiple times to a reaction with different skin tones. Clicking on the group of reactions will remove the whole group (see this video from slack):


https://user-images.githubusercontent.com/16821682/223688978-7e672bfd-f58a-4050-9ef5-b1e22664403b.mov

@stitesExpensify I think the rest of the video is also correct. The message has the following reactions added by the other participant in the chat: "👍🏽", "😄". The user then adds his own reaction to it, and this is working as expected as from what i can see.

(Correct me if i am wrong pls)

2023-03-08 10:45 UTC, hannojg commented
Oh you are absolutely right, will fix it 😊

2023-03-08 11:09 UTC, hannojg commented
@0xmiroslav Okay, pushed all fixes. Can you please test again?

2023-03-08 12:21 UTC, hannojg commented
@0xmiroslav to me that seems like the buggy behaviour with the API where pusher events overwrite local state with stale data

2023-03-08 13:18 UTC, 0xmiroslav submitted a review, later dismissed
Follow-up issues:
- support reaction on edit message
- support reaction on IOU message
- last reaction reverted when react multiple times quickly

2023-03-08 13:46 UTC, stitesExpensify reviewed
So close, last change!

2023-03-08 13:46 UTC, stitesExpensify commented on src/libs/actions/Report.js
> +    const skinTone = emoji.types == null ? null : paramSkinTone; // only use skin tone if emoji supports it
```suggestion
    const skinTone = emoji.types === null ? null : paramSkinTone; // only use skin tone if emoji supports it
```

2023-03-08 13:47 UTC, deetergp submitted a review, later dismissed
Thanks for the changes and additional tests!

2023-03-08 13:53 UTC, stitesExpensify approved these changes
LGTM and tests well 🎉  LET'S DO THIS!

2023-03-08 13:55 UTC, stitesExpensify commented
Waiting for verify_podfile....

2023-03-08 13:56 UTC, merged

2023-03-08 14:24 UTC, stitesExpensify commented on src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js
> +                        }
Honestly I think this is a good warning to have, I wouldn't mind keeping it

2023-03-09 04:20 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4370735956) to staging by https://github.com/stitesExpensify in version: 1.2.81-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-04-03 20:12 UTC, puneetlath commented
Friendly FYI: this PR created a very small regression in the copy: https://github.com/Expensify/App/issues/15867. Should've been `Edit reaction` instead of `Edit Reaction` in order to be consistent with how we do it everywhere else in the app.

2023-04-05 16:25 UTC, stitesExpensify commented
Ach dangit. Thanks for letting me know

2023-04-12 07:03 UTC, sobitneupane commented
This PR created a regression: https://github.com/Expensify/App/issues/16384. On navigation to Add reaction bubble using keyboard, the emoji picker appears in top left corner.

2023-04-21 11:53 UTC, sobitneupane commented
With [this PR](https://github.com/Expensify/App/issues/15815), we have updated the size of emoji in reaction of a message to 28px with a font size of 15px, in mini context menu to 20px with a font size of 13px and in context menu to 34px with a font size of 17px.

Those changes might have been missed or not considered in this PR.

2024-10-02 08:55 UTC, rushatgabhane reviewed
Small bug fixed: [Clicking on same emoji reaction changes skin tone instead of removing](https://github.com/Expensify/App/issues/46387#top)