Anthony 1542 issue pinned report
Expensify/App pull request #1584
Opened 2021-02-27 16:27 UTC by anthony-hull

### Details
Skipping filtering of reports which have no messages but also are pinned

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/1542

### Tests - Unit
`npm run test`
I updated the test file OptionsListUtilsTest.js to count the number of pinned reports. One of the pinned reports doesn't have any messages. 

### Tests - Functional
1. Press the + button to start a new chat with an individual who you have never messaged before.
2. Before sending any message, pin the chat.
3. The chat should be pinned in the chat list on the left.
4. Click on another chat.
5. The chat should still pinned in the chat list on the left.
6. Click back on the chat and unpin the chat.
7. The chat should still be in the list but no longer be pinned.
8. Click on another chat
9. Chat should disappear from the chat list on the left.

### Tested On

- [X] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

As this is only logic in the data layer I didn't test this on other platforms. I'm relying on the unit tests and

2021-03-01 23:15 UTC, deetergp requested changes

2021-03-01 23:15 UTC, deetergp commented on src/libs/OptionsListUtils.js
> +            && !report.isPinned;
This PR looks good overall, just have one minor request: Having this condition by itself on a separate line looks odd. Either put them all on the same line (I think the linter just warns about being over 120 chars, which is fine) or put each condition on its own line.

2021-03-02 21:57 UTC, deetergp submitted a review, later dismissed
Looks good Anthony, thanks!

2021-03-02 21:59 UTC, deetergp commented
Looks like you've got a merge conflict to deal with. It looks like you just need to move your test down to the bottom of the page--nothing too complicated.

2021-03-02 22:01 UTC, anthony-hull commented
That’s a conflict  my other PR that just merged. It was a race to the finish on both ^^

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Scott Deeter <notifications@github.com>
Sent: Tuesday, March 2, 2021 9:59:42 PM
To: Expensify/Expensify.cash <Expensify.cash@noreply.github.com>
Cc: Anthony Hull <anthony.hull@hotmail.co.uk>; Author <author@noreply.github.com>
Subject: Re: [Expensify/Expensify.cash] Anthony 1542 issue pinned report (#1584)


Looks like you've got a merge conflict to deal with. It looks like you just need to move your test down to the bottom of the page--nothing too complicated.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FExpensify%2FExpensify.cash%2Fpull%2F1584%23issuecomment-789249880&data=04%7C01%7C%7C43ab75904bf24daaaa5b08d8ddc67ca9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637503191841393795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GQu0NLs7cmWx3hkEKtAzxtR9WOPouUvQYj5ORtJxY0A%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALH7R5SCVEOCB3GJAQDSUCTTBVNU5ANCNFSM4YKCUWCQ&data=04%7C01%7C%7C43ab75904bf24daaaa5b08d8ddc67ca9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637503191841393795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7%2B1DxS6a6aApgWX2ZcdRkkO9WaR21KvnTvIgB%2FBi5qw%3D&reserved=0>.

2021-03-02 23:28 UTC, deetergp approved these changes
Looks good & no more conflicts. Thanks!

2021-03-02 23:28 UTC, merged