pass user session information when opening the electron app from web platform
Expensify/App pull request #16043
Opened 2023-03-16 15:12 UTC by ntdiary

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/15651
PROPOSAL: https://github.com/Expensify/App/issues/15651#issuecomment-1467954112

### Tests

1. Login with account A in the desktop app.
2. Login with account B in the web app.
3. Navigate to the user profile page in the web app.
4. Refresh the browser.
5. A prompt should appear asking to 'Open the app in Electron'.
6. Click on it and wait for the desktop app to open.
7. Verify the user profile page for account B is displayed in the desktop app.

- [x] Verify that no errors appear in the JS console

### Offline tests

1. Login with account A in the desktop app.
2. Login with account B in the web app.
3. Navigate to the user profile page in the web app.
4. Refresh the browser.
5. A prompt should appear asking to 'Open the app in Electron'.
6. Turn off the network.
7. Click on 'Open the app in Electron' and wait for the desktop app to open.
8. Verify the login page is displayed in the desktop app.

### QA Steps

1. Login with account A in the desktop app.
2. Login with account B in the web app.
3. Navigate to the user profile page in the web app.
4. Refresh the browser.
5. A prompt should appear asking to 'Open the app in Electron'.
6. Click on it and wait for the desktop app to open.
7. Verify the user profile page for account B is displayed in the desktop app.

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified  [...]

2023-03-16 16:58 UTC, hayata-suenaga commented
@ntdiary I'm looking at your questions right now. I'll get back to you after I get insights into these.

2023-03-16 17:51 UTC, hayata-suenaga commented
@ntdiary FYI the desktop deeplink [is not working on main currently](https://github.com/Expensify/App/issues/15965).

2023-03-16 19:36 UTC, hayata-suenaga commented on src/components/DeeplinkWrapper/index.website.js
> +        if (!this.props.authenticated) {
We have [custom URL scheme.](https://github.com/Expensify/App/blob/0efe6acf41eb985a0d6e42b47a8d91ab9cef6559/src/CONST.js#L272) `new-expensify://`.

I think somewhere in the code, if the desktop is registering that URL schema with Mac OS, telling it that if OS detects user opening any URL that starts with `new-expensify://`, please let the desktop app handle what to do with the URL.

2023-03-20 15:09 UTC, hayata-suenaga commented
I'm looking at your [comment](https://github.com/Expensify/App/pull/16043#issuecomment-1475817110) now I have to be offline now and I'm OOO today, but if I can find a time tonight, I'll get back to you.

2023-03-21 04:17 UTC, hayata-suenaga commented
@ntdiary thank you for checking on auth token lifespan.

> I temporarily let the app jump to the home page instead of getting stuck on the /transition page.

Is it possible for us to intercept the event of clicking on `Open Electron` button and navigate the user back to the home page?

2023-03-22 15:42 UTC, hayata-suenaga commented
@ntdiary does the user have to sign in again? not just refreshing the screen?

2023-03-22 16:10 UTC, hayata-suenaga commented
I'll wait @shawnborton's response but shouldn't we display "Please refresh again" instead?

And @ntdiary how do you suggest we trigger the change of the screen when the token expires?

2023-03-22 16:33 UTC, hayata-suenaga approved these changes, later dismissed
ohhh I completely misunderstood. yes it makes sense to prompt the user to log in again on the desktop side. let's wait for @shawnborton's review but otherwise LGTM!

2023-03-22 17:27 UTC, hayata-suenaga commented
there is a suggestion that we should implement a new screen for expired session and deprecate `DeeplinkWrapper`. @ntdiary please let me know if you're up to this 👀

https://expensify.slack.com/archives/C049HHMV9SM/p1679504172500439?thread_ts=1678823496.930569&cid=C049HHMV9SM
https://expensify.slack.com/archives/C049HHMV9SM/p1679505364500279?thread_ts=1678823496.930569&cid=C049HHMV9SM

2023-03-23 16:14 UTC, hayata-suenaga commented
>  LogInWithShortLivedAuthTokenPage (not yet committed)

@ntdiary I'll wait for your commit in the expired session screen.

2023-03-23 22:34 UTC, hayata-suenaga commented on src/languages/es.js
> +        signIn: 'Por favor, inicie sesión de nuevo.',
did you check for the translation on slack?

2023-03-23 22:34 UTC, hayata-suenaga commented on src/ONYXKEYS.js
>  };
should we use `isTokenValid` instead?

2023-03-27 11:26 UTC, pecanoro requested changes

2023-03-27 11:26 UTC, pecanoro commented on src/languages/es.js
> +        signIn: 'Por favor, inicie sesión de nuevo.',
```suggestion
        signIn: 'Por favor, inicia sesión de nuevo.',
```

2023-03-27 11:26 UTC, pecanoro commented on src/languages/es.js
> +        expired: 'Su sesión ha expirado.',
```suggestion
        expired: 'Tu sesión ha expirado.',
```

2023-03-28 12:14 UTC, thesahindia requested changes
Looks good! Just a minor change. 

I will test and fill the checklist in a few minutes

2023-03-28 13:48 UTC, thesahindia submitted a review, later dismissed

2023-03-28 15:17 UTC, pecanoro requested changes

2023-03-28 15:17 UTC, pecanoro commented on src/pages/LogInWithShortLivedAuthTokenPage.js
> +    isTokenValid: PropTypes.bool,
All props need a comment explaining what they are for

2023-03-28 16:18 UTC, thesahindia submitted a review, later dismissed

2023-03-29 13:57 UTC, hayata-suenaga commented on src/libs/actions/Session/index.js
>      // If the user is transitioning to newDot from a different account on oldDot the credentials may be tied to
should we update the comments here since we're also dealing with the situation of transitioning from web NewDot to desktop NewDot?

2023-03-29 18:04 UTC, pecanoro commented on src/components/DeeplinkWrapper/index.website.js
> +        }).catch(() => {
Why catch and not always?

2023-03-31 11:49 UTC, hayata-suenaga commented
@ntdiary I'm waiting for @thesahindia's review.

2023-03-31 14:28 UTC, thesahindia approved these changes
It looks good to me @hayata-suenaga

2023-04-03 15:05 UTC, hayata-suenaga approved these changes
LGTM!

2023-04-03 17:10 UTC, pecanoro approved these changes

2023-04-03 17:11 UTC, merged

2023-04-03 17:14 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-04-03 19:27 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4600028104) to staging by https://github.com/pecanoro in version: 1.2.94-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2023-04-05 02:28 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4614236319) to production by https://github.com/thienlnam in version: 1.2.94-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-04-13 13:49 UTC, tgolen reviewed
Hi, I'm sorry to be coming into this late, but someone asked me about some of the code implemented in this PR and I had many questions about it.

2023-04-13 16:28 UTC, hayata-suenaga commented
@tgolen thank you very much for the comments. we should have done more thorough review.

Some of the fixes suggested changed are being implemented in this [PR](https://github.com/Expensify/App/pull/17364)

@ntdiary are you up for a followup PR for fixing the original one?

2023-04-14 13:54 UTC, tgolen commented
Great, thank you so much for addressing these! It's gonna make this code a lot cleaner. 👍

2023-04-18 05:46 UTC, s77rt commented
I think this PR caused a regression https://github.com/Expensify/App/issues/17391 (details [here](https://github.com/Expensify/App/issues/17391#issuecomment-1512464169)). This PR adds the transition prefix to all deeplinks and I think we should not do that because the transition prefix is only for OLDDOT -> NEWDOT and not WEB -> DESKTOP.