Fix/16448: Reset displayListViewBorder if user don't select option
Expensify/App pull request #16875
Opened 2023-04-03 16:31 UTC by tienifr

### Details
The displayListViewBorder is set to false if the user selects an option, but is not if the user blurs out of the GooglePlacesAutocomplete. So we need to set the displayListViewBorder to false when the user blurs the address search input and the options list.
### Fixed Issues

$ https://github.com/Expensify/App/issues/16448
PROPOSAL: https://github.com/Expensify/App/issues/16448#issuecomment-1492881279

### Tests

1. Open the app
2. Open Workspaces > connect bank account
3. Click on connect manually
4. Fill in step 1 information (eg data: routing number = 210021002, acc no = 1234)
5. In the company address, type in address but don't select any option
6. Click outside (ex: click on the city field)
7. Verify that the suggestion text below the company address is displayed

- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

1. Open the app
2. Open Workspaces > connect bank account
3. Click on connect manually
4. Fill in step 1 information (eg data: routing number = 210021002, acc no = 1234)
5. In the company address, type in address but don't select any option
6. Click outside (ex: click on the city field)
7. Verify that the suggestion text below the company address is displayed
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `mai [...]

2023-04-04 14:58 UTC, tienifr commented
We need to merge [this PR] or hash the commit     
```
"react-native-google-places-autocomplete": "git+https://github.com/Expensify/react-native-google-places-autocomplete.git#499b779e86db546377a6a6289762b9a80117c5a3",

```
 in package.json
to run this PR

2023-04-05 12:10 UTC, eVoloshchak requested changes

2023-04-05 12:10 UTC, eVoloshchak commented on src/components/AddressSearch.js
> +                            DisplayListViewborder.resetDisplayListViewborderWhenBlur(event, containerRef, setDisplayListViewBorder);
```suggestion
                            resetDisplayListViewBorderOnBlur(event, containerRef, setDisplayListViewBorder);
```

2023-04-05 12:10 UTC, eVoloshchak commented on src/libs/resetDisplayListViewborderWhenBlur/index.js
I think these files should be in `components/AddressSearch` folder. There's only a single place where we're using this method, it's not universal

2023-04-05 12:10 UTC, eVoloshchak commented on src/libs/resetDisplayListViewborderWhenBlur/index.js
And please add a comment explaining why this logic is needed (and why it isn't needed on mobile)

2023-04-06 04:54 UTC, tienifr commented on src/libs/resetDisplayListViewborderWhenBlur/index.js
@eVoloshchak Just updated, Could you check again?

2023-04-06 11:23 UTC, eVoloshchak requested changes

2023-04-06 11:23 UTC, eVoloshchak commented on src/components/AddressSearch/AddressSearch.js
This can be renamed to `src/components/AddressSearch/index.js`

2023-04-06 11:23 UTC, eVoloshchak commented on src/components/AddressSearch/resetDisplayListViewBorderWhenBlur/index.js
No need to have a separate `resetDisplayListViewBorderWhenBlur` folder, we can just have two files called  `resetDisplayListViewBorderWhenBlur.js` and `resetDisplayListViewBorderWhenBlur.native.js`, similar to how other components are structured

2023-04-06 11:23 UTC, eVoloshchak commented on src/components/AddressSearch/AddressSearch.js
> +                            resetDisplayListViewBorderWhenBlur(event, containerRef, setDisplayListViewBorder);
```suggestion
                            resetDisplayListViewBorderOnBlur(event, containerRef, setDisplayListViewBorder);
```

2023-04-06 11:44 UTC, tienifr commented
@eVoloshchak Thanks for your comment. I just updated, could you help to check again?

2023-04-06 12:45 UTC, eVoloshchak requested changes

2023-04-06 12:45 UTC, eVoloshchak commented on src/components/AddressSearch/resetDisplayListViewBorderOnBlur.native.js
> +resetDisplayListViewBorderOnBlur.displayName = 'resetDisplayListViewBorderOnBlur';
```suggestion
```

2023-04-06 12:45 UTC, eVoloshchak commented on src/components/AddressSearch/resetDisplayListViewBorderOnBlur.js
> +resetDisplayListViewBorderOnBlur.displayName = 'resetDisplayListViewBorderOnBlur';
```suggestion
```

2023-04-06 12:45 UTC, eVoloshchak commented on src/components/AddressSearch/resetDisplayListViewBorderOnBlur.native.js
> +const resetDisplayListViewBorderOnBlur = (event, containerRef, setDisplayListViewBorder) => {
```suggestion
const resetDisplayListViewBorderOnBlur = () => {
```

2023-04-06 12:45 UTC, eVoloshchak commented on src/components/AddressSearch/index.js
> +                            props.onBlur(event);
```suggestion
                            props.onBlur(event);
```

Do we need to pass `event` to `onBlur` here?

2023-04-06 15:35 UTC, eVoloshchak commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Mobile Web - Chrome</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Mobile Web - Safari</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Desktop</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>iOS</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Android</summary>

<!-- add screenshots or videos here -->

</details>

2023-04-06 15:54 UTC, eVoloshchak commented
Looks good and test well!
Before this can be merged we need to
1. Merge https://github.com/Expensify/react-native-google-places-autocomplete/pull/3
2. Change this [line](https://github.com/Expensify/App/blob/55a7132deb32a1b1afce390b6238067f8a2e32e4/package.json#L99) to be pointed to the latest commit

@iwiznia, could you take a look at https://github.com/Expensify/react-native-google-places-autocomplete/pull/3 please? 
It didn't request a review from you automatically and I can't do it manually

2023-04-23 16:04 UTC, eVoloshchak commented
@tienifr, looks like we can merge this PR 
Could you please merge with main and change this [line](https://github.com/Expensify/App/blob/55a7132deb32a1b1afce390b6238067f8a2e32e4/package.json#L99) to be pointed to the latest commit of `Expensify/react-native-google-places-autocomplete`, so we could re-test this

2023-04-24 04:53 UTC, tienifr commented
@eVoloshchak Conflicts resolved and fork version updated.

2023-04-24 13:25 UTC, eVoloshchak reviewed
Re-tested all the platforms, everything works as expected
@tienifr, there still seem to be some merge conflicts

2023-04-24 16:05 UTC, tienifr commented
@eVoloshchak I've resolved the conflicts.

2023-04-24 16:26 UTC, eVoloshchak approved these changes
LGTM
cc: @iwiznia

2023-04-25 16:42 UTC, iwiznia approved these changes

2023-04-25 16:50 UTC, tienifr commented
@iwiznia I've resolved it.

2023-04-25 18:42 UTC, merged

2023-04-25 18:50 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-04-26 06:34 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4805236166) to staging by https://github.com/iwiznia in version: 1.3.6-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-04-27 04:49 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4815987914) to production by https://github.com/jasperhuangg in version: 1.3.6-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅