Pinning icon alignment
Expensify/App pull request #1737
Opened 2021-03-12 00:03 UTC by aliabbasmalik8

### Details
Fixed regression that caused due to my PR 
### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/1728
https://github.com/Expensify/Expensify.cash/pull/1721

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-03-12 00:22 UTC, roryabraham requested changes

2021-03-12 00:25 UTC, aliabbasmalik8 commented on src/styles/styles.js
> +    iconsRow: {
Okay, on it

2021-03-12 00:29 UTC, aliabbasmalik8 commented on src/styles/styles.js
> +    iconsRow: {
Updated PR according to your feedback.
Thanks

2021-03-12 00:29 UTC, roryabraham approved these changes
LGTM, thanks for fixing

2021-03-12 13:16 UTC, Dal-Papa approved these changes

2021-03-12 13:16 UTC, merged

2021-03-16 20:56 UTC, shawnborton commented
Hmm actually I think this did not fix the issue. 

You can see from the outline that the entire row is not clickable:
![image](https://user-images.githubusercontent.com/2319350/111378647-66a75b80-86a2-11eb-8379-71a5d969051a.png)

The outline should encompass the entire row, and the pin & pencil icons should be nested inside of the row and they should be clickable.