Fix: Redundant URL param `openOnAdminRoom` on log out
Expensify/App pull request #17447
Opened 2023-04-14 07:05 UTC by tienifr

### Details

On logging out, the `openOnAdminRoom` URL param is redundant. It should be omitted if it's undefined. This PR fixes that.

### Fixed Issues

$ GH_LINK
PROPOSAL: GH_LINK_ISSUE(COMMENT)

### Tests

1. Login in with any account
2. Logout from the app
3. Verify that the URL does not contain `?openOnAdminRoom=false` param i.e. `https://new.expensify.com`
- [x] Verify that no errors appear in the JS console

### Offline tests

Same above

### QA Steps

1. Login in with any account
2. Logout from the app
3. Verify that the URL does not contain `?openOnAdminRoom=false` param i.e. `https://new.expensify.com`
- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

[Screencast from 14-04-2023 13:27:32.webm](https://user-images.githubusercontent.com/113963320/231961057-3c3f9dda-10c8-4a5b-8aae-2fb5a5ac42de.webm)

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/113963320/231968804-0055d315-fc03-41e8-a021-cb79339f6368. [...]

2023-04-14 11:39 UTC, situchan commented
Hopefully, this would get fixed in this PR

<img width="757" alt="console error" src="https://user-images.githubusercontent.com/108292595/232033998-e8bbd87a-6bc2-4e61-aa81-c52e4801c990.png">

2023-04-15 17:47 UTC, tienifr commented
@situchan I can't reproduce the warning. Could you give more context?

2023-04-17 05:35 UTC, tienifr commented
@situchan I think the type warning is already resolved in this PR/commit: https://github.com/Expensify/App/commit/394ab323636530c8cca5bae3218ca0ccb8b3143d

Before the change, `openOnAdminRoom` is passed as a raw string (i.e. `'true'` or `'false'`).

2023-04-17 17:09 UTC, tienifr commented on src/libs/ValidationUtils.js
> +function stringToBool(value) {
@thesahindia I think this's the most precise we can do. I'm also ok with using the simpler `initialParams={{openOnAdminRoom: openOnAdminRoom === 'true' ? true : undefined}}` if you think we're over-engineering it.

2023-04-18 01:44 UTC, amyevans requested changes

2023-04-18 05:12 UTC, tienifr commented on src/libs/ValidationUtils.js
> +function stringToBool(value) {
Upstream PR: https://github.com/Expensify/expensify-common/pull/518, waiting for review.

However I think we can proceed this current PR no matter whether the upstream PR is merged or not as it won't yield a different result. The upstream PR is only for future prevention, not critical to the current PR.

2023-04-18 13:29 UTC, amyevans commented on src/libs/ValidationUtils.js
> +function stringToBool(value) {
> However I think we can proceed this current PR no matter whether the upstream PR is merged or not
Agreed!

2023-04-18 13:29 UTC, amyevans submitted a review, later dismissed

2023-04-18 13:30 UTC, amyevans commented
@thesahindia All you 😄

2023-04-18 17:21 UTC, tienifr commented
@thesahindia Didn't think the upstream's merge that fast 😄! I've updated the package version accordingly.

2023-04-18 17:22 UTC, amyevans approved these changes, later dismissed

2023-04-19 08:52 UTC, tienifr commented
@thesahindia This is the expected behavior. If `openOnAdminRoom` is `true`, the URL still needs to display it. Otherwise, it should be hidden. Correct me if I misunderstood your comment.

> Verify that the URL does not contain `?openOnAdminRoom=false` param

2023-04-19 17:11 UTC, tienifr commented
Thank you all for your clarification and contribution. @bernhardoj's solution seems great to me but is the flickering OK and will it cause regression? I think we need more time to investigate this issue to make sure it won't cause any regression and all expected behaviors're fulfilled.

2023-04-20 11:15 UTC, tienifr commented
@amyevans Just wonder if the flickering in the URL when logging out is OK with you?

2023-04-20 14:27 UTC, amyevans commented
The "flickering" in the URL is fine, that's pretty typical behavior across the web IMO.

> will the clear-all-param cause regression?

This, and whether this is the optimal solution, are the unanswered questions for me and I don't know off the top of my head. @thesahindia can you take an initial look and weigh in?

2023-04-21 03:05 UTC, bernhardoj commented
From my testing, `setParams` merge the params. So, we need to pass null to each params object, for example
`openOnAdminRoom: null`, `exitTo:null`, etc.

I have been trying to find a way to clear all of them but can't find one.

2023-04-21 11:09 UTC, tienifr commented
@thesahindia @amyevans I think we don't need to reset the whole route, we can reset all the params by doing the following:
1. Retrieve all current params of the `Home` route
2. set all above params to null and use `setParams` to reset all of them at once
We can write some utils for the above and use it in `redirectToSignIn`

I think we can combine this with the current solution, this will help clearing the params on log out, the current solution will help make sure `openOnAdminRoom` will not flicker as `false` when log out even though we do not set it.

With the above, feel free to highlight if you still want me to ask for others to weigh in. Since I think resetting all params are light weight and there's no potential issue that can happen like if we reset the whole route.

2023-04-24 16:39 UTC, tienifr commented
@thesahindia @amyevans Please help take a look at the implementation. Need your review before updating PR details & screenshots.

2023-04-24 16:52 UTC, tienifr commented
@amyevans @thesahindia Tests well with both `true` and `false`! Also notice that the `flickering` no longer happens. Please help take a look at the implementation.

[Screencast from 24-04-2023 23:49:41.webm](https://user-images.githubusercontent.com/113963320/234063713-3f5afe67-8c76-4aaf-ad0c-08f66f446246.webm)
[Screencast from 24-04-2023 23:50:41.webm](https://user-images.githubusercontent.com/113963320/234063724-313ffa3d-121f-46c1-ab30-063da50270bd.webm)

2023-04-25 12:42 UTC, situchan commented
> Hopefully, this would get fixed in this PR
> 
> <img alt="console error" width="757" src="https://user-images.githubusercontent.com/108292595/232033998-e8bbd87a-6bc2-4e61-aa81-c52e4801c990.png">

This is still happening on main

2023-04-25 17:21 UTC, tienifr commented
@situchan Still cannot reproduce. Can you give more context?

2023-04-25 17:32 UTC, situchan commented
> @situchan Still cannot reproduce. Can you give more context?

visit http://localhost:8080/?openOnAdminRoom=false and login

2023-04-27 09:44 UTC, thesahindia submitted a review, later dismissed
LGTM!

All yours @amyevans

2023-04-28 14:27 UTC, amyevans requested changes
Looks good and tests well, just the 1 comment, plus please update your QA steps to cover the second scenario as well:
1. Create a new free policy in OldDot
2. Verify that you're redirected to the Workspace #admins room in NewDot
3. Logout
4. Verify the URL is the login page, without any query parameters

2023-04-28 14:27 UTC, amyevans commented on src/libs/actions/SignInRedirect.js
> +        const homeRoute = lodashFind(routes, route => route.name === SCREENS.HOME);
```suggestion
        const homeRoute = _.find(routes, route => route.name === SCREENS.HOME);
```
Nitpick but can we use `_.find()` instead here? Seems to be our go-to throughout the App

2023-04-28 16:28 UTC, amyevans approved these changes

2023-05-01 14:51 UTC, thesahindia approved these changes
Sorry for the delay. I was away. 

LGTM!

2023-05-01 15:05 UTC, merged

2023-05-01 15:12 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-05-03 00:07 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4866484804) to staging by https://github.com/amyevans in version: 1.3.9-12 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-05-09 04:07 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4922047640) to production by https://github.com/roryabraham in version: 1.3.12-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅