Add new vertical line separator instead of borderRight
Expensify/App pull request #18022
Opened 2023-04-26 11:10 UTC by narefyev91

### Details
Remove blurry border right - which were overlapped by Composer TextInput 

### Fixed Issues
$ https://github.com/Expensify/App/issues/16848
$ https://github.com/Expensify/App/issues/16848#issuecomment-1514329351

### Tests
1. Launch the app -> Login in account
2. Navigate any chat conversation
3. Notice composer input (from left side it overlaps)

- [ ] Verify that no errors appear in the JS console

### Offline tests
Same as above

### QA Steps
Same as above

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

<img width="998" alt="web" src="https://user-images.githubusercontent.co [...]

2023-04-26 16:05 UTC, s77rt commented
Hi @narefyev91 :wave: Can we please have an update here? I see the PR is marked as draft now. I noticed the separator looks a little different especially since it's surrounded by the outside border, they look mismatched. Is this put on hold for that matter or something else? Let me know what should be done to move this forward

2023-04-27 07:25 UTC, narefyev91 commented
> Hi @narefyev91 👋 Can we please have an update here? I see the PR is marked as draft now. I noticed the separator looks a little different especially since it's surrounded by the outside border, they look mismatched. Is this put on hold for that matter or something else? Let me know what should be done to move this forward

Hey - based on internal process my changes should be checked by our QA first - and after approval i can mark PR as ready to review.

2023-04-27 07:56 UTC, narefyev91 commented
@s77rt I do not know why no one raise this before - but this is what i see on main branch on my emulator (mWeb for android) - not sure if it happens only for me. Border top overlaps borderRight - and this is seems a new issue
<img width="661" alt="Screenshot 2023-04-27 at 10 54 31" src="https://user-images.githubusercontent.com/28352309/234797055-670515d4-d4a0-451e-8407-35e04720c116.png">

2023-04-27 10:12 UTC, s77rt commented
@narefyev91 If the issue exists on main then it's technically out of the scope of this PR. I'm not referring to that, I'm referring to the change on width. Open two tabs staging and localhost and notice the diff. On localhost (dev) the separator looks a littler thicker.

![Screenshot from 2023-04-27 11-09-01](https://user-images.githubusercontent.com/16493223/234831724-10666d57-23e7-405a-aaaa-654a8ae75f2a.png)
![Screenshot from 2023-04-27 11-08-58](https://user-images.githubusercontent.com/16493223/234831732-1e94e366-9e38-4e25-9aed-cfd23a6898ba.png)


___

Weirdly if you zoom enough, they will appear identical
![Screenshot from 2023-04-27 11-11-06](https://user-images.githubusercontent.com/16493223/234832292-4dbdf5e6-87c6-4a15-891f-5d7dfcee73fa.png)
![Screenshot from 2023-04-27 11-11-02](https://user-images.githubusercontent.com/16493223/234832298-a92aa268-1d51-470c-9b55-54d53437c5fd.png)

2023-04-27 10:15 UTC, narefyev91 commented
> @narefyev91 If the issue exists on main then it's technically out of the scope of this PR. I'm not referring to that, I'm referring to the change on width. Open two tabs staging and localhost and notice the diff. On localhost (dev) the separator looks a littler thicker.
> 
> ![Screenshot from 2023-04-27 11-09-01](https://user-images.githubusercontent.com/16493223/234831724-10666d57-23e7-405a-aaaa-654a8ae75f2a.png) ![Screenshot from 2023-04-27 11-08-58](https://user-images.githubusercontent.com/16493223/234831732-1e94e366-9e38-4e25-9aed-cfd23a6898ba.png)
> 
> Weirdly if you zoom enough, they will appear identical ![Screenshot from 2023-04-27 11-11-06](https://user-images.githubusercontent.com/16493223/234832292-4dbdf5e6-87c6-4a15-891f-5d7dfcee73fa.png) ![Screenshot from 2023-04-27 11-11-02](https://user-images.githubusercontent.com/16493223/234832298-a92aa268-1d51-470c-9b55-54d53437c5fd.png)

LOL - maybe some visual effects?

2023-04-27 11:52 UTC, s77rt commented
The problems that originate from 1px are really one of a kind :sweat_smile:. This is one may be related to browser optimisation. Can you please check how can we make it look as before?

2023-04-27 12:38 UTC, narefyev91 commented
> The problems that originate from 1px are really one of a kind :sweat_smile:. This is one may be related to browser optimisation. Can you please check how can we make it look as before?

Maybe we can try some platform separation ?

2023-04-27 12:46 UTC, s77rt commented
I would really prefer not to go that way

2023-04-27 12:50 UTC, narefyev91 commented
> I would really prefer not to go that way

Agree ! Seems our case https://stackoverflow.com/questions/42710882/css-border-1px-appear-as-0-667px-or-1px-depending-on-the-computer-display-res

2023-04-27 16:09 UTC, narefyev91 commented
@s77rt i added border-box item, and i could not really see a difference on mac safari, chrome, firefox browsers.

2023-04-27 19:18 UTC, s77rt commented
@narefyev91 box-sizing: border-box is already the default. I still see the diff.

2023-04-28 06:44 UTC, narefyev91 commented
> @narefyev91 box-sizing: border-box is already the default. I still see the diff.

Can you maybe post in which browser and machine you see the diff?

2023-04-28 07:09 UTC, narefyev91 commented
@s77rt seems width will not work also - based on discovering later at nigh - browser will still making calculation based on monitor size - and will apply different border width - while width itself will be the same. That's why you can see that difference on your machine.
I came up with other idea. Attachment button - in which we initially have issue - is not a wrong place - it doesn't create an issue. The bad place - right area in which we have input, which taken some border space from other View.
What if we remove border from attachment (as we discussed earlier) and apply border to View in which right section is presented? Now the View in which right section presented will push textinput to right (without overlapping) and we remove 1px from left - which will not make any impact on element positions. And in all platforms we will not see any differences
Some result from devices
<img width="95" alt="Screenshot 2023-04-28 at 10 01 14" src="https://user-images.githubusercontent.com/28352309/235079069-b6dc6d21-8125-43e6-ab53-9f2ba5154fbb.png">
<img width="70" alt="Screenshot 2023-04-28 at 10 08 20" src="https://user-images.githubusercontent.com/28352309/235079078-2e85a99f-beaa-4db8-9705-cbf766714bc2.png">

2023-04-28 07:34 UTC, s77rt commented
What a solution! :joy: Given that this is an equally valid solution I'm okay with that. But let's keep the border in a class so just rename chatItemAttachBorder to something fitting and use on in text input instead of attachment button.

2023-04-28 07:52 UTC, narefyev91 commented
> What a solution! 😂 Given that this is an equally valid solution I'm okay with that. But let's keep the border in a class so just rename chatItemAttachBorder to something fitting and use on in text input instead of attachment button.

Yup - sorry that didn't get to this idea initially....
Updated based on your comment!

2023-04-28 08:01 UTC, s77rt requested changes

2023-04-28 08:01 UTC, s77rt commented on src/pages/home/report/ReportActionCompose.js
> +                                    <View style={[styles.textInputComposeSpacing, styles.chatItemComposeBoxBorder]}>
Maybe textInputComposeBorder is better here?

2023-04-28 10:04 UTC, s77rt requested changes

2023-04-28 10:04 UTC, s77rt commented on src/styles/styles.js
> +    textInputComposeBorder: {
NAB: Can you please move this to be below `textInputComposeSpacing` just for visibility.

2023-04-28 10:19 UTC, s77rt commented
@narefyev91 Please tag me again once this is ready for review

2023-04-28 13:09 UTC, m4rtag commented
**RETESTS SUMMARY**

This fix is verified on Branch PR Draft **narefyev91:add-new-separator-for-action-composer**  

Tests are conducted on the following devices:
Google Chrome Version 112.0.5615.121 (Official Build) (arm64) at Mac OS Ventura 13.3.1
Safari Version 16.4 (18615.1.26.11.23) at Mac OS Ventura 13.3.1
Expensify Desktop app - New Expensify Electron Version v1.3.1-0, Electron Version 22.3.6 (22.3.6)
iOS native app - iPhone Simulator Version 14.2 (986.5), iOS 16.2, SimulatorKit 627, CoreSimulator 885.2
Safari on iOS - iPhone Simulator 14 iOS 16.2
Android native app v1.3.1-0 - Android Emulator -Nexus_5X_API_TiramisuPrivacySandbox:5554 
Chrome 101.0.4951.74, Operating system Android13; Build/TRA4.221021.001.B1 

**The above tests are executed with a 100% pass value**

![separator Android native](https://user-images.githubusercontent.com/40687528/235156071-5879a509-1133-4882-a095-bcc0963dc1b0.png)
![separator- web Android](https://user-images.githubusercontent.com/40687528/235156074-713e6813-5a75-4896-b855-746e852016ab.png)
![separator web iOS](https://user-images.githubusercontent.com/40687528/235156078-4e154a5b-ecd1-41dc-81be-861c5f05d964.png)
![separator -native iOS](https://user-images.githubusercontent.com/40687528/235156079-75e51b77-fd8f-4928-ba12-f2aff7c301b0.png)
![separator desktop](https://user-images.githubusercontent.com/40687528/235156080-ca337cc2-24f1-4350-a5f9-9970050fe662.png)
![separator web](https://user-images.githubusercontent.com/40687528/235156083-14f18963-b776-49d8-aa11-0f0cd86db339.png)

2023-04-28 14:03 UTC, narefyev91 commented
@s77rt ready for review

2023-04-28 16:28 UTC, s77rt commented
## Reviewer Checklist

- [X] I have verified the author checklist is complete (all boxes are checked off).
- [X] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [X] I verified the steps for local testing are in the `Tests` section
    - [X] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [X] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [X] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I verified tests pass on **all platforms** & I tested again on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [X] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [X] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

<!-- add screenshots or videos here -->
![web](https://user-images.githubusercontent.com/16493223/235202420-3499f360-aa20-4bba-97b6-de25371dd225.png)

</details>

<details>
<summary>Mobile Web - Chrome</summary>

<!-- add screenshots or videos here -->
![mweb-chrome](https://user-images.githubusercontent.com/16493223/235202400-80c560b8-bb74-4379-9611-3ca0587625b1.png)

</details>

<details>
<summary>Mobile Web - Safari</summary>

<!-- add screenshots or videos here -->
![mweb-safari](https://user-images.githubusercontent.com/16493223/235202382-fce874c9-2336-490b-b7d9-3b5b5470c42d.png)

</details>

<details>
<summary>Desktop</summary>

<!-- add screenshots or videos here -->
![de [...]

2023-04-28 16:33 UTC, s77rt commented
@narefyev91 Can you please update the tests to:

1. Open App
2. Open any chat
3. Verify the composer border does not overlap with the attachment button

and tag me again

2023-04-29 11:13 UTC, narefyev91 commented
> @narefyev91 Can you please update the tests to:
> 
> 1. Open App
> 2. Open any chat
> 3. Verify the composer border does not overlap with the attachment button
> 
> and tag me again

@s77rt done

2023-04-29 12:09 UTC, s77rt commented
@narefyev91 Thank you!

2023-04-29 12:09 UTC, s77rt approved these changes
LGTM! :rocket: 

cc @puneetlath

2023-05-01 17:29 UTC, puneetlath approved these changes
It's beautiful!

2023-05-01 17:29 UTC, merged

2023-05-01 17:36 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-05-03 00:07 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4866484804) to staging by https://github.com/puneetlath in version: 1.3.9-12 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-05-09 04:07 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4922047640) to production by https://github.com/roryabraham in version: 1.3.12-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅