Fix GBR and RBR show up at the same time in the LHN
Expensify/App pull request #18137
Opened 2023-04-28 09:40 UTC by hungvu193

### Details

This PR fixes problem with GBR and RBR show up at the same time in the OptionRowLHN
### Fixed Issues

$ https://github.com/Expensify/App/issues/17912
PROPOSAL: https://github.com/Expensify/App/issues/17912#issuecomment-1521284332

### Tests

1. Request money from userA to userB
2. As userB notice the GBR indicator in the LHN
3. Perform an action that will result in an error
4. Verify that only RBR show up

- [x] Verify that no errors appear in the JS console
### Offline tests

### QA Steps

1. Request money from userA to userB
2. As userB notice the GBR indicator in the LHN
3. Perform an action that will result in an error
4. Verify that only RBR show up

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this P [...]

2023-05-01 06:22 UTC, luacmartins requested changes
@hungvu193 can we also address [this comment](https://github.com/Expensify/App/issues/17912#issuecomment-1525850943)? We also have conflicts now.

2023-05-01 12:02 UTC, hungvu193 commented
@luacmartins sure, I updated the PR.

2023-05-01 18:25 UTC, mananjadhav commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/3069065/235505655-14f7eaf9-c2c3-49ea-958f-79b5ec7da905.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/3069065/235505767-d329c1c0-91d9-4d62-bcea-19632f25958d.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/3069065/235505824-534929be-bff5-444b-b1d5-7f8f01101001.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/3069065/235505893-81aac5e1-a8fe-434a-9237-8e02ed2c1097.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/3069065/235505927 [...]

2023-05-01 18:25 UTC, mananjadhav approved these changes, later dismissed

2023-05-01 19:01 UTC, luacmartins commented
@hungvu193 Thanks for addressing my previous comment. As I mentioned before, we are still displaying the pinned icon and according to our new design, the green/red indicator should replace the pinned icon. Could you please address that?

<img width="376" alt="Screenshot 2023-05-01 at 9 00 08 PM" src="https://user-images.githubusercontent.com/22219519/235511799-b853fd1b-0d9a-4c3f-bf41-eb37768eb439.png">

2023-05-01 19:16 UTC, mananjadhav commented
@luacmartins Sorry I didn't understand the change. Can you elaborate what we mean by should replace the pinned icon?

The chat mentioned [here](https://github.com/Expensify/App/issues/17912#issuecomment-1525850943) talks about removing the indicator from between the pin and pencil, but not about replacing?

2023-05-02 07:26 UTC, luacmartins commented
My comment comes from the new [design doc](https://docs.google.com/document/d/17jFcMsAotXvsMhXivoF3u7fyzeyXkKpRGXR88Ud0oWY/edit#) and the section that introduced this behavior:

>When an admin needs to pay a request, a green dot will appear on the expense/IOU report row for them. The report will also remain auto-pinned in the LHN until the report is settled, because they have an action they need to take. 
Note: We replace the pin icon with the green dot icon in this case to minimize clutter in the LHN chat row.

2023-05-02 07:27 UTC, luacmartins commented
I thought that's what Shawn had mentioned in his comment, but I can see how that was confusing.

2023-05-02 07:36 UTC, hungvu193 commented
> When an admin needs to pay a request, a green dot will appear on the expense/IOU report row for them. The report will also remain auto-pinned in the LHN until the report is settled, because they have an action they need to take.
> Note: We replace the pin icon with the green dot icon in this case to minimize clutter in the LHN chat row.


@luacmartins if we replace the pin icon in LHN when green dot is visible, should we need to replace the pin icon in the header inside LHN? I think it's confused for user when they didn't see the pin icon outside but still saw it inside of LHN.
Also the purpose of this PR was fixing the logic between RBR and GBR, do you think it's out of scope of this PR?

2023-05-02 08:24 UTC, luacmartins commented
@hungvu193 I don't think we should change the logic in the header, this should affect the LHN only. I think it's an easy enough change to incorporate in this PR.

2023-05-02 08:26 UTC, hungvu193 commented
@luacmartins just to confirm, when the green dot is visible, we also need to hide the pin icon right?

2023-05-02 08:29 UTC, luacmartins commented
Yes

2023-05-02 08:35 UTC, hungvu193 commented
@luacmartins Cool, I've updated the PR again.

2023-05-02 09:24 UTC, luacmartins approved these changes

2023-05-02 09:24 UTC, luacmartins commented
LGTM!

2023-05-02 09:24 UTC, luacmartins commented
@mananjadhav do you wanna review again since we changed some of the logic?

2023-05-02 09:32 UTC, mananjadhav commented
@luacmartins I was just reviewing and testing it. I just want to confirm, if we have a RBR, we can always have Pin and Pencil icon right?

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/3069065/235631152-766dc076-c2c1-468f-993c-0eaa440f8d3d.png">

I tried accessing the design doc google link, but it says Access denied.

2023-05-02 09:45 UTC, luacmartins commented
@mananjadhav yes, that seems to be the expected behavior for RBR.

2023-05-02 11:03 UTC, mananjadhav commented
@luacmartins I've updated the new screenshots on the same checklist [here](https://github.com/Expensify/App/pull/18137#issuecomment-1530046165). Does that work?

2023-05-02 11:21 UTC, luacmartins commented
Yea, that's good

2023-05-02 11:23 UTC, merged

2023-05-02 11:29 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-05-02 12:49 UTC, hungvu193 commented on src/components/LHNOptionsList/OptionRowLHN.js
> +                                    fill={colors.green}
I think that's from previous commit, cc @puneetlath, since I think that's diff from you

2023-05-02 13:25 UTC, luacmartins commented on src/components/LHNOptionsList/OptionRowLHN.js
> +                                    fill={colors.green}
Nice catch @aimane-chnaif! We should [not import colors](https://github.com/Expensify/App/blob/854de26b67bf82ee5b4955709cd593f218c05a3e/src/styles/colors.js#L2) directly 😬

2023-05-02 13:25 UTC, luacmartins commented on src/components/LHNOptionsList/OptionRowLHN.js
> +                                    fill={colors.green}
I see that we are doing that in multiple places though. I think we should put up a PR to fix that.

2023-05-02 13:27 UTC, mananjadhav commented on src/components/LHNOptionsList/OptionRowLHN.js
> +                                    fill={colors.green}
I think we should create a separate issue for this.

2023-05-02 13:28 UTC, shawnborton commented on src/components/LHNOptionsList/OptionRowLHN.js
> +                                    fill={colors.green}
Agree that we should be using `success` here

2023-05-03 00:07 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4866484804) to staging by https://github.com/luacmartins in version: 1.3.9-12 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-05-04 07:07 UTC, mountiny commented
@mananjadhav @hungvu193 @aimane-chnaif could you please test this in staging just to make sure, I think QA has tested it but forgot to check off the checklist.

2023-05-09 04:07 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4922047640) to production by https://github.com/roryabraham in version: 1.3.12-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅