refactor: migrate MagicCodeInput to function component
Expensify/App pull request #18398
Opened 2023-05-04 11:14 UTC by BeeMargarida

### Details
Ported `MagicCodeInput` to function component

### Fixed Issues

$ https://github.com/Expensify/App/issues/18332
PROPOSAL: --

### Tests

1. Use passwordless login (modify `Permissions.js` method `canUsePasswordlessLogins` to return `true`)
2. Enter the app (logged out) and set your email
3. Should see the new component
4. Add the code and submit (should work similar to how it was before in terms of submit logic)

- [X] Verify that no errors appear in the JS console

### Offline tests

Same tests as above, but with the submission failing

### QA Steps

1. Use passwordless login (modify `Permissions.js` method `canUsePasswordlessLogins` to return `true`)
2. Enter the app (logged out) and set your email
3. Should see the new component
4. Add the code and submit (should work similar to how it was before in terms of submit logic)

- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new pag [...]

2023-05-04 13:32 UTC, BeeMargarida commented on src/components/MagicCodeInput.js
> +        setNumbers(decomposeString(props.value));
Great suggestion, thank you!

2023-05-04 13:52 UTC, ArekChr approved these changes, later dismissed
Left some minor comments with `useRef` object
Overall LGTM 🙌

2023-05-04 13:52 UTC, ArekChr commented on src/components/MagicCodeInput.js
> +                                ref={ref => inputRefs[index] = ref}
```suggestion
                                ref={ref => inputRefs.current[index] = ref}
```

2023-05-04 13:52 UTC, ArekChr commented on src/components/MagicCodeInput.js
> +            inputRefs[0].focus();
```suggestion
            inputRefs.current[0].focus();
```

2023-05-04 13:52 UTC, ArekChr commented on src/components/MagicCodeInput.js
> +            inputRefs[0].focus();
```suggestion
            inputRefs.current[0].focus();
```

2023-05-04 13:52 UTC, ArekChr commented on src/components/MagicCodeInput.js
> +        inputRefs[editIndex].blur();
```suggestion
        inputRefs.current[editIndex].blur();
```

2023-05-04 13:52 UTC, ArekChr commented on src/components/MagicCodeInput.js
> +            focusTimeout = setTimeout(() => inputRefs[0].focus(), CONST.ANIMATED_TRANSITION);
```suggestion
            focusTimeout = setTimeout(() => inputRefs.current[0].focus(), CONST.ANIMATED_TRANSITION);
```

2023-05-04 13:52 UTC, ArekChr commented on src/components/MagicCodeInput.js
> +        inputRefs[0].focus();
```suggestion
        inputRefs.current[0].focus();
```

2023-05-04 13:52 UTC, ArekChr commented on src/components/MagicCodeInput.js
> +                inputRefs[newFocusedIndex].focus();
```suggestion
                inputRefs.current[newFocusedIndex].focus();
```

2023-05-04 13:52 UTC, ArekChr commented on src/components/MagicCodeInput.js
> +            inputRefs[newFocusedIndex].focus();
```suggestion
            inputRefs.current[newFocusedIndex].focus();
```

2023-05-04 13:52 UTC, ArekChr commented on src/components/MagicCodeInput.js
> +            inputRefs[newFocusedIndex].focus();
```suggestion
            inputRefs.current[newFocusedIndex].focus();
```

2023-05-04 13:52 UTC, ArekChr commented on src/components/MagicCodeInput.js
> +
```suggestion
```

2023-05-05 10:13 UTC, m4rtag commented
**TESTS SUMMARY**

The new component is verified on Branch PR Draft **BeeMargarida:refactor/18332-magic_code_input_function_component*  

Tests are conducted on the following devices:

1. > Google Chrome Version 112.0.5615.121 (Official Build) (arm64) at Mac OS Ventura 13.3.1
2. > Safari Version 16.4 (18615.1.26.11.23) at Mac OS Ventura 13.3.1
3. > Expensify Desktop app - New Expensify Electron Version v1.3.1-0, Electron Version 22.3.6 (22.3.6)
4. > iOS native app - iPhone Simulator Version 14.2 (986.5), iOS 16.2, SimulatorKit 627, CoreSimulator 885.2
5. > Safari on iOS - iPhone Simulator 14 iOS 16.2
6. > Android native app v1.3.1-0 - Android Emulator -sdk_gphone64_arm64, Nexus_5X_API_TiramisuPrivacySandbox:5554 
7. > Chrome (113.0.5672.76), Operating system Android13; Build/TRA4.221021.001.B1 

**The above tests are executed with a 100% pass value**

https://user-images.githubusercontent.com/40687528/236431080-e51f7abf-3635-4d7d-90f2-01f852dda29a.mp4

https://user-images.githubusercontent.com/40687528/236431117-e225e638-2c97-4971-b83c-41d35ba11f0e.mp4

https://user-images.githubusercontent.com/40687528/236431177-8e4d1823-87e6-41fe-92ae-4ff96359e48b.mp4

https://user-images.githubusercontent.com/40687528/236431188-c69e0e16-9468-415a-95d8-df2b3e7d1268.mp4

https://user-images.githubusercontent.com/40687528/236431134-7d4af0dc-1627-4f9b-bc30-6f392face56b.mp4

https://user-images.githubusercontent.com/40687528/236431153-559fddb7-1fb1-4637-a875-ecc7d4582f02.mp4

https://user-images.githubusercontent.com/40687528/236431026-628817a8-35d1-403e-ab04-8bdc1568ee4e.mp4

2023-05-10 07:42 UTC, BeeMargarida commented
@aimane-chnaif @cristipaval Conflicts are solved and prettier was run, ready for a review!

2023-05-10 10:56 UTC, cristipaval commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Mobile Web - Chrome</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Mobile Web - Safari</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Desktop</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>iOS</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Android</summary>

<!-- add screenshots or videos here -->

</details>

2023-05-10 11:15 UTC, cristipaval requested changes
https://github.com/Expensify/App/assets/18078393/20c375c5-0fbf-429b-80b8-10de22d6b18d

It doesn't work on iOS Native

2023-05-10 11:23 UTC, BeeMargarida commented
Yes, as @aimane-chnaif mentioned, it's currently broken for simulators running iOS 16.4. I've stopped investigation for a while since I'm currently focusing on other issues.

2023-05-10 11:26 UTC, cristipaval commented
> @cristipaval thanks for checklist. I was about to review today 🙂

I removed you as this is a class component refactor and we decided internally that we can remove the C+  for this kind of PRs. I thought that you might be swamped with other reviews as we have lots of things moving thess days.

2023-05-10 11:27 UTC, cristipaval commented
> Yes, as @aimane-chnaif mentioned, it's currently broken for simulators running iOS 16.4. I've stopped investigation for a while since I'm currently focusing on other issues.

ah, ok, I'll tets on my physical device then

2023-05-10 12:36 UTC, cristipaval approved these changes
Tests well on physical iOS devices.

2023-05-10 12:37 UTC, merged

2023-05-10 12:45 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-05-11 02:43 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/4942948914) to staging by https://github.com/cristipaval in version: 1.3.13-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅