Update Details Page for Threads
Expensify/App pull request #18772
Opened 2023-05-11 11:15 UTC by grgia

### Details

<img width="1204" alt="image" src="https://github.com/Expensify/App/assets/38015950/9d647eb9-0f99-4d19-81f7-a472c2d3f36f">

### Fixed Issues

$ https://github.com/Expensify/App/issues/18757

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mob [...]

2023-05-11 11:16 UTC, grgia commented on src/languages/es.js
> +        leaveThread: 'Salir del hilo',
Need to check this !

2023-05-11 11:18 UTC, grgia commented on src/pages/ReportDetailsPage.js
> +        if (this.props.report.parentReportActionID) {
once https://github.com/Expensify/App/pull/18522 is merged we can replace with `ReportUtils.isThread(report)` for readibility.

2023-05-11 11:28 UTC, grgia commented on src/languages/es.js
> +        leaveThread: 'Salir del hilo',
https://expensify.slack.com/archives/C21FRDWCV/p1683804474846109

2023-05-11 14:12 UTC, grgia commented on src/languages/es.js
> +        leaveThread: 'Salir del hilo',
Confirmed!

2023-05-11 14:14 UTC, grgia commented
@chiragsalian @stitesExpensify could you help to define the QA for leaving threads?

2023-05-16 09:49 UTC, grgia commented
Also ready for review!

2023-05-16 18:49 UTC, stitesExpensify approved these changes, later dismissed

2023-05-16 18:51 UTC, grgia commented
@fedirjh potentially may be fixed with this PR? https://github.com/Expensify/App/pull/19056

2023-05-16 19:01 UTC, chiragsalian requested changes
Mentioned some bugs 1:1 to georgia to tackle.

2023-05-16 19:09 UTC, grgia commented
@fedirjh I confirmed that bug is happening on main when you leave a public room

2023-05-16 19:12 UTC, chiragsalian commented
Bugs to tackle,
- We should show settings button since controlling notifications is important
- In details tab -> settings, for a thread report don't show reportName (or make it non editable, whichever is easier)
- LeaveRoom does not work for non-policy chats. I think the backend does not allow for it. So my suggestion is to remove it completely here until the backend can be updated to work properly for this flow.

2023-05-16 19:34 UTC, grgia commented
> 
> Sure, 
> For EC3.
> - i think the threads feature is fine as is. Nothing more needs to done wrt details page as a priority imo.
> 
> For v1/post EC3.
> - All threads should show settings tab since its important to set their notifications over there.
> - All threads should have the option to leave thread
> 
> 
> My suggestion, to tackle this in phases, i.e., work on what you can get out the door
> 1. The details tab looks great visually. I would say have one PR having share code, members and settings. In settings hide room name if its a thread for now. Remove leave room if its a thread because i think its better to get the feature out working completely vs not working properly in some places which could get confusing to users.
> 2. Then once backend updates LeaveRoom then add it to the details page via another newDot PR.

> So should we remove all the leaveRoom stuff from this PR and only have share code / members
>  it should also have settings and room name should be hidden if its a thread.

cc @chiragsalian posting this here for easy reference

2023-05-16 23:52 UTC, chiragsalian commented
I've added CP to staging label since it would be nice if we can get this to staging early tomorrow, then later in the day it would go to production via regular App deploy. This is because i just realized we are doing DBSEC3 and may not deploy on thursday-friday. So if we get this out the door tomorrow it would be really nice. We can also ping QA to test.

2023-05-16 23:53 UTC, chiragsalian commented
I edited out my comment about leaveRoom [here](https://github.com/Expensify/App/pull/18772#issuecomment-1550217586) since we made the backend change and its live.

2023-05-17 07:56 UTC, grgia commented
Adding a comment to track while I'm currently updating this PR:

We will also be updating the QR details as part of this 
<img width="374" alt="image" src="https://github.com/Expensify/App/assets/38015950/4d6809fe-1f82-493c-97ad-a9259a57d4eb">

2023-05-17 08:38 UTC, grgia commented
| Chat DM Thread | Workspace Room Thread |
| ----- | ----- |
| <img width="1198" alt="image" src="https://github.com/Expensify/App/assets/38015950/30874eca-1c9f-4810-b4fb-b201ddf836f0"> | <img width="1198" alt="image" src="https://github.com/Expensify/App/assets/38015950/d438f907-66f4-454d-b338-733dfe9e3c37">|
| <img width="1198" alt="image" src="https://github.com/Expensify/App/assets/38015950/63bfb34a-4077-424e-b59c-b2611c95e4dd"> | <img width="1198" alt="image" src="https://github.com/Expensify/App/assets/38015950/17d74765-7bea-4d10-93af-5cfefda04219"> |
| <img width="1198" alt="image" src="https://github.com/Expensify/App/assets/38015950/d8a3282e-6392-4b82-aeb8-7a974157307a"> | <img width="1198" alt="image" src="https://github.com/Expensify/App/assets/38015950/ae48c0d4-485d-4b91-864f-331c373f3133"> |
| <img width="1198" alt="image" src="https://github.com/Expensify/App/assets/38015950/7f1f8af2-e1fb-4700-b80b-bf255b51896f"> | <img width="1198" alt="image" src="https://github.com/Expensify/App/assets/38015950/8efa1b04-ce42-45db-85df-9bdeda2dd825"> |

2023-05-17 08:40 UTC, grgia commented
@fedirjh open for review!

2023-05-17 14:06 UTC, stitesExpensify submitted a review, later dismissed
LGTM!

2023-05-17 16:30 UTC, fedirjh reviewed
Looks good , Just noticed when the thread is initially created , the members menu item is not displayed, It get displayed after the second user open the thread.

<img width="746" alt="Screenshot 2023-05-17 at 5 29 19 PM" src="https://github.com/Expensify/App/assets/36869046/2cc31fab-2b0f-4b65-94e4-026308b0e3b7">

2023-05-17 16:40 UTC, grgia commented
@fedirjh done! Also, I think that bug has to do with our optimistic data more so than the details page, so I think we should fix it separately

2023-05-17 18:34 UTC, chiragsalian commented
Also members page header says "Details", it should instead say "Members"

2023-05-17 19:14 UTC, grgia commented
@fedirjh @chiragsalian addressed those bugs

2023-05-17 19:50 UTC, stitesExpensify approved these changes

2023-05-17 20:24 UTC, chiragsalian approved these changes
LGTM and it seems to work well for me

2023-05-17 20:26 UTC, grgia commented
@fedirjh that's a known bug https://expensify.slack.com/archives/C049HHMV9SM/p1684222206427449

2023-05-17 20:30 UTC, fedirjh approved these changes
Thanks @grgia . Looks good to me and tests well

2023-05-17 23:25 UTC, merged

2023-05-18 01:01 UTC, OSBotify commented
🚀 [Cherry-picked](https://github.com/Expensify/App/actions/runs/5008927317) to staging by https://github.com/mountiny in version: 1.3.15-10 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

@Expensify/applauseleads please QA this PR and check it off on the [deploy checklist](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3AStagingDeployCash) if it passes.

2023-05-18 06:49 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5011154080) to production by https://github.com/yuwenmemon in version: 1.3.15-12 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-06-15 01:28 UTC, OSBotify commented
🚀 [Cherry-picked](https://github.com/Expensify/App/actions/runs/5273496004) to staging by https://github.com/AndrewGable in version: 1.3.28-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

@Expensify/applauseleads please QA this PR and check it off on the [deploy checklist](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3AStagingDeployCash) if it passes.

2023-06-16 18:46 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5293001429) to production by https://github.com/AndrewGable in version: 1.3.28-5 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-07-13 17:37 UTC, Santhosh-Sellavel commented
I feel we could have captured this [regression](https://github.com/Expensify/App/issues/20197) here, not an easy one though. Refer [here](https://github.com/Expensify/App/issues/20197#issuecomment-1577829745), I know the code was not added here, but we could've caught this thanks!