Fix: Backtick Bug
Expensify/App pull request #19218
Opened 2023-05-18 21:41 UTC by AngelNBazan

### Details

Fixed backticks (\`) display in the comment/description sections of actions such as Send Money, Request Money, and Split Bill by removing the HTML parser that processed the comment text. This change ensures that backticks are correctly displayed (\`) instead of being converted into their HTML representation '&#x60'."
### Fixed Issues

$ https://github.com/Expensify/App/issues/17798
PROPOSAL: https://github.com/Expensify/App/issues/17798#issuecomment-1522519111

### Tests

1.Create an action(Request money, Send money, Split bill)
2. In comment/description section and add backticks(`) to text
3. Verify the correct amount of backticks are displayed, all text in between backticks is present, and backticks are displayed properly and not as html representation('&#x60')

### Offline tests

N/a
### QA Steps

1.Create an action(Request money, Send money, Split bill)
2. In comment/description section and add backticks(`) to text
3. Verify the correct amount of backticks are displayed, all text in between backticks is present, and backticks are displayed properly and not as html representation('&#x60')
- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `A [...]

2023-05-19 14:15 UTC, mollfpr commented
@AngelNBazan Could you complete the screenshots for all platforms? Thanks!

2023-05-19 14:31 UTC, mollfpr commented
@AngelNBazan I also notice that the older IOU that already saves the markdown for description still displays the issue in LHN and the expense report thread. Could we at least display the same comment within the comment in `IOUPreview`?

![Screenshot 2023-05-19 at 21 28 17](https://github.com/Expensify/App/assets/25520267/ff3b2a3f-6e01-422f-84e0-03a4fa72aba5)

![Screenshot 2023-05-19 at 21 30 40](https://github.com/Expensify/App/assets/25520267/d4787146-e76e-45cc-8dc0-918e897c82c2)

2023-05-22 11:33 UTC, mollfpr commented
@AngelNBazan Could you address this issue?


<img width="720" alt="Screenshot 2023-05-22 at 18 32 20" src="https://github.com/Expensify/App/assets/25520267/0576af44-168c-4244-ad4e-f941e5ef2df2">

2023-05-22 17:37 UTC, AngelNBazan commented
@mollfpr I have attached some screenshots that show this PR, fixing this issue(https://github.com/Expensify/App/pull/19218#issuecomment-1557057304). The reason that the older IOU displays backticks properly and the IOU preview doesn't is that we are still sending/saving improperly parsed text to the backend. And, in this PR we remove the parsing logic and save/send the plain text to the backend which is why in the screenshots below it displays properly.
https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/src/libs/ReportUtils.js#L1394
https://github.com/Expensify/App/blob/23e5de4a3281a99b1e3e31b2916d5a6bf1d8059a/src/libs/ReportUtils.js#LL1427C20-L1427C20

<img width="1093" alt="Screenshot 2023-05-22 at 10 22 04 AM" src="https://github.com/Expensify/App/assets/78933484/8fda20b1-2703-4485-9875-bab7a656a30c">
<img width="1089" alt="Screenshot 2023-05-22 at 10 22 47 AM" src="https://github.com/Expensify/App/assets/78933484/6dcaca73-8a35-4245-8dab-12d5d767994a">

2023-05-22 17:43 UTC, mollfpr commented
@AngelNBazan So can we fix that? Or we only able to fix the issue in new IOU?

2023-05-22 17:52 UTC, AngelNBazan commented
@mollfpr Sorry, I'm a bit confused about what you mean by "Or we only able to fix the issue in new IOU", this PR would remove the parsing logic. Removing the parsing logic is how we fix this issue https://github.com/Expensify/App/pull/19218#issuecomment-1557057304, as it saves the correct text across everything. So, whenever anything uses the comments/descriptions it accesses the correct text.

2023-05-22 17:59 UTC, AngelNBazan commented
@mollfpr Oh, sorry, I think I understand now. Yes, this PR would only apply to IOUs from now on. Therefore, old IOUs would still display incorrectly. I'm not sure on how we could fix old IOUs as those have already been saved to the backend.

2023-05-23 17:28 UTC, mollfpr commented
@AngelNBazan Is it possible to display the exact text on the sidebar and the IOU preview comment?

2023-05-23 17:40 UTC, AngelNBazan commented
@mollfpr Yes, here are screenshots of that.
<img width="1469" alt="Screenshot 2023-05-23 at 10 38 39 AM" src="https://github.com/Expensify/App/assets/78933484/e4403a0a-c8d8-4d04-8a17-a407ba3c0736">
<img width="1470" alt="Screenshot 2023-05-23 at 10 37 56 AM" src="https://github.com/Expensify/App/assets/78933484/4824bd7a-124a-47a9-8ec7-1dbbca076897">

2023-05-23 18:03 UTC, AngelNBazan commented
@mollfpr Alright, that sounds good to me. I believe my PR is now ready for review. Could you please take a look at it? Thank you!

2023-05-23 18:09 UTC, mollfpr commented
@AngelNBazan I think there's a misunderstanding here. I'm asking for the older IOU since. 😅

2023-05-23 18:18 UTC, AngelNBazan commented
@mollfpr Sorry for the confusion 😅. Could you please provide more clarification on what you mean by the 'older IOU'? I want to make sure I understand your request correctly. Thank you!

2023-05-23 18:34 UTC, mollfpr commented
The screenshot [here](https://github.com/Expensify/App/pull/19218#issuecomment-1554682854) is has request money before this PR created. In LHN it's and description display `&#x60;&#x60;` but it's show '' in the IOU preview.

So I'm thinking we could fix the incorrect text for old IOUs too, because it's fix in the IOU preview component.

2023-05-24 17:36 UTC, mollfpr commented
>So to summarize, this PR will only fix new IOUs and will have LHN and descriptions display the correct text https://github.com/Expensify/App/pull/19218#issuecomment-1559880320. These https://github.com/Expensify/App/pull/19218#issuecomment-1559880320 were taken of me testing the PR with new IOUs, not old ones.

@alex-mechler Are we okay with this? We could decode the text in LHN for the last message or the display name, but if the user tries to leave a comment with &amp; , &copy; , etc, it will be decoded, and I'm afraid someone will see that as a bug.

2023-05-25 16:56 UTC, alex-mechler commented
> if the user tries to leave a comment with & , © , etc, it will be decoded, and I'm afraid someone will see that as a bug.

Can you elaborate on this? With this PR in place, if you comment with `&`, what will the user see?

For the scope of this issue, we can ignore pre-existing IOUs, and only worry about ones going forward

2023-05-25 17:18 UTC, mollfpr commented
@AngelNBazan Do we still need this parsed?

https://github.com/Expensify/App/blob/63f314c054d82ad0ee5e59ec5349d9b35d656bea/src/libs/ReportUtils.js#L1398

2023-05-25 17:47 UTC, AngelNBazan commented
@mollfpr No, you're right this does not need to parsed I have just updated the PR.

2023-05-29 18:37 UTC, mollfpr commented
@AngelNBazan Could you resolve the conflicts? I'll complete the review afterward.

2023-05-30 02:12 UTC, AngelNBazan commented
Sure, @mollfpr! I have just resolved the conflicts. Let me know if there's anything else I can help with.

2023-05-30 11:19 UTC, mollfpr requested changes
Sorry for the delay! Just need to revert unnecessary changes on `IOUPreview`.

2023-05-30 11:19 UTC, mollfpr commented on src/components/ReportActionItem/IOUPreview.js
> +    const requestComment = moneyRequestAction.comment.trim();
@AngelNBazan I think we can do nothing for the requested amount and the currency since `isIOUAction` is removed. Just need to update the comment.

2023-05-30 11:39 UTC, mollfpr commented
While testing this PR, I reported a bug in the Split bill details page [here](https://expensify.slack.com/archives/C049HHMV9SM/p1685446595440839).

2023-05-30 11:43 UTC, mollfpr commented on src/components/ReportActionItem/IOUPreview.js
> +    const requestComment = moneyRequestAction.comment.trim();
Ok, we should revert the above change. The currency should be IDR not USD.

![Screenshot 2023-05-30 at 18 40 38](https://github.com/Expensify/App/assets/25520267/edb3cfad-3b33-447a-acd6-8ea570b37d7e)

2023-05-30 16:42 UTC, mollfpr commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

<!-- add screenshots or videos here -->

https://github.com/Expensify/App/assets/25520267/451ab825-bf02-425e-a115-1e8cfa261da7


</details>

<details>
<summary>Mobile Web - Chrome</summary>

<!-- add screenshots or videos here -->

https://github.com/Expensify/App/assets/25520267/e997019e-d245-4750-b205-c8cdfc2f1696


</details>

<details>
<summary>Mobile Web - Safari</summary>

<!-- add screenshots or videos here -->

https://github.com/Expensify/App/assets/25520267/43ca230a-eee7-4bec-bb46-465cdba83e49



</details>

<details>
<summary>Desktop</summary>

<!-- add screenshots or videos here -->

https://github.com/Expensify/App/assets/25520267/bcf5caca-2ccb-44d2-8252-8ecbd6249ae [...]

2023-05-30 16:43 UTC, mollfpr approved these changes
LGTM and tests well 👍

All yours @alex-mechler

2023-05-30 19:19 UTC, alex-mechler commented
@AngelNBazan Code LGTM, and tests well, but you still have unsigned commits here. You need to make this PR have only signed commits before travis will pass

2023-05-30 23:25 UTC, closed without merging

2023-05-30 23:52 UTC, AngelNBazan commented
@mollfpr @alex-mechler, apologies for the inconvenience. I had to recreate the repo to sign all the commits. Here's the new PR: https://github.com/Expensify/App/pull/19868.

2023-05-31 00:01 UTC, alex-mechler commented
Thanks!