Create FlagCommentPage
Expensify/App pull request #19412
Opened 2023-05-22 20:40 UTC by dangrous

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/18508

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>

</details>

<details>
<summary>iOS</summary>

 [...]

2023-05-26 17:58 UTC, thienlnam reviewed
Nice - looks solid! Just a NAB

2023-05-26 17:58 UTC, thienlnam commented on src/pages/FlagCommentPage.js
> +            severity: 'spam',
NAB: constants

2023-05-26 19:14 UTC, dangrous commented on src/pages/FlagCommentPage.js
> +            severity: 'spam',
oops yep forgot to update those

2023-05-30 11:16 UTC, eVoloshchak commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Mobile Web - Chrome</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Mobile Web - Safari</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Desktop</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>iOS</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Android</summary>

<!-- add screenshots or videos here -->

</details>

2023-05-30 11:42 UTC, eVoloshchak requested changes
Found a couple of issues:

1. Navigate to a conversation
2. Right-click on someone elses message
3. Select "Reply in thread"
4. Right click on the message in thread
5. Select "Flag as offensive"
6. Press on any severity option
7. Notice nothing is happening and there's error in console


https://github.com/Expensify/App/assets/9059945/caee1797-5a0d-43e7-a610-d01306e0ae61


On mWeb/iOS/Android or web with `isSmallScreenWidth = true`
1. Select "Flag as offensive" on any message
2. Press on any severity option
3. Notice that you're navigated back twice (to the list with chats) instead of to the current chat 


https://github.com/Expensify/App/assets/9059945/ee63e3bd-9a33-4ac4-9b49-4282be69aa5a

2023-05-30 17:15 UTC, dangrous commented
@eVoloshchak I think I handled both of your comments; if you want to test functionality you are welcome to! I think based on a convo in slack the visual design will be changing slightly so stay tuned

2023-05-30 19:29 UTC, dangrous commented
Okay this is ready for review again! Maybe one last copy change coming in but everything else is good to go.

We're trying to get this merged today so @youssef-lr and @eVoloshchak speed is appreciated - thank you!

2023-05-31 13:58 UTC, eVoloshchak requested changes

2023-05-31 14:08 UTC, dangrous commented
Free to merge - copy is updated!

2023-05-31 14:09 UTC, eVoloshchak commented
Bug:

1. Flag message as Spam
2. Flag the same message as Bullying, the message becomes hidden
3. Right-click on the message, select "Reply in thread"
4. Notice there is no way to reveal the message, the button disappears
5. Go back to the conversation
6. Notice the message isn't hidden anymore (while it should be)

 

https://github.com/Expensify/App/assets/9059945/a7d05470-843b-4f3d-8a30-e07aef597f57

2023-05-31 14:10 UTC, dangrous commented
blergh. looking into it

2023-05-31 14:19 UTC, eVoloshchak commented
I think this is related to the same issue as video above:

1. Have a comment marked with high severity (so it's hidden)
2. Mark it as Spam
3. Notice `Reveal` button disappear for a second

This happens both in chats and in threads

https://github.com/Expensify/App/assets/9059945/3cf3d6c7-02b2-45ba-bc91-de166a861487

2023-05-31 14:25 UTC, eVoloshchak commented
@dangrous, if I flag the same message with `Spam` (or any other option) twice, it gets hidden. Is this the intended behavior?

2023-05-31 14:45 UTC, dangrous commented
yeah its a bit of an issue with how we handle the messages in the UI. I think I've figured it out... let me test a couple more things.

Re attachments @youssef-lr , I think we were focusing on text for v1. We might be able to use the same logic? I can see what happens without that check

2023-05-31 14:55 UTC, dangrous commented
okay i think i fixed the bugs you found @eVoloshchak.

@youssef-lr I am also sometimes getting that issue; doesn't seem like it's related to this, but we can look into it in PHP

2023-05-31 14:58 UTC, youssef-lr commented
@dangrous it's weird though that it's only happening with whispers? as regular messages updates work properly.

2023-05-31 14:59 UTC, eVoloshchak commented on src/pages/FlagCommentPage.js
> +        let reportID = props.route.params.reportID;
@dangrous, I think we can use `getReportID` here

2023-05-31 15:04 UTC, youssef-lr approved these changes, later dismissed
LGTM! The bug I found should be fixed in the backend I think.

2023-05-31 15:11 UTC, eVoloshchak commented
Found one more edge case where the reveal button is hidden for a second
1. Flag message as Spam
2. Flag message as Bullying
3. Go to 'Reply in thread"
4. Go back to chat
5. Mark the same message as Spam



https://github.com/Expensify/App/assets/9059945/fc5bf2e7-37bd-4ea9-99d0-eeaf8be1b167

2023-05-31 15:24 UTC, dangrous commented
should be fixed now

2023-05-31 15:24 UTC, eVoloshchak commented
![Simulator Screen Shot - iPhone 14 - 2023-05-31 at 18 23 04](https://github.com/Expensify/App/assets/9059945/5c8f5bb7-8bc9-4c26-82da-942d9a44ddd8)

Also I think this highlight should take up full width with paddings inside it

2023-05-31 15:44 UTC, eVoloshchak approved these changes
LGTM

2023-05-31 16:27 UTC, youssef-lr approved these changes

2023-05-31 16:28 UTC, merged

2023-05-31 18:11 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5135743267) to staging by https://github.com/youssef-lr in version: 1.3.21-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-06-01 03:03 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5139699591) to production by https://github.com/AndrewGable in version: 1.3.21-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-06-16 18:17 UTC, dangrous commented on src/pages/home/report/ContextMenu/ContextMenuActions.js
> +            !ReportUtils.isConciergeChatReport(reportID) &&
I think that's right! Shouldn't be a need for that. cc @thienlnam in case you see anything wrong with that.

2023-06-16 18:50 UTC, thienlnam commented on src/pages/home/report/ContextMenu/ContextMenuActions.js
> +            !ReportUtils.isConciergeChatReport(reportID) &&
Yeah sounds good to me, as long as you don't see flag messages in a Concierge chat the problem is solved

2023-07-11 20:36 UTC, dangrous commented on src/pages/FlagCommentPage.js
> +        <ScreenWrapper includeSafeAreaPaddingBottom={false}>
ahhhh nice catch, thank you for calling it out!