Show assigned user as mention in the task preview
Expensify/App pull request #19990
Opened 2023-06-01 17:46 UTC by dukenv0307

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/19089
PROPOSAL: https://github.com/Expensify/App/issues/19089#issuecomment-1550654651

$ https://github.com/Expensify/App/issues/19959 
$ https://github.com/Expensify/App/issues/19967

### Tests for https://github.com/Expensify/App/issues/19089

1. Login with Expensifail account
2. Go to FAB > Assign task
3. Enter title, description and click on next button
4. Click on assignee  and select any user or enter an email or phone number to select a new user if don't have any user
5. Click on confirm button to create a new task
6. Verify that the assigned user displays as metion in the task preview
7. Edit the title of this task
8. Logout and login again
9. Verify that the assigned users still displays as mention in the task preview as well

### Tests for https://github.com/Expensify/App/issues/19959
1. Go to App and Click on + icon
2. Select Assign task option
3. Create a new task
4. Go to settings > logout
5. Login again
6. Verify that the task name is created in above display

### Tests for https://github.com/Expensify/App/issues/19967
1. Go to any chat
2. Click on + icon and select Assign task option
3. Enter title and description
4. Click on Next button
5. Click on confirm task button
6. click on title
8. Edit task title
10. Go back to previous report screen
11. Verify that Task title is updated

- [x] Verify that no errors appear in the JS console

### Offline tests

Same above
### QA Steps

Same above
- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sendin [...]

2023-06-02 06:24 UTC, sobitneupane commented
@dukenv0307 Can you please include the test steps from https://github.com/Expensify/App/issues/19959 and https://github.com/Expensify/App/issues/19967 issues and verify that they are no longer reproducible. This PR is expected to solve those issues as well as mentioned by @thienlnam [here](https://github.com/Expensify/App/issues/19089#issuecomment-1572795863).

2023-06-02 17:05 UTC, thienlnam commented on src/components/ReportActionItem/TaskPreview.js
> +    const htmlForTaskPreview = taskAssignee === '' ? `<comment>${taskTitle}</comment>` : `<comment><mention-user>@${taskAssignee}</mention-user> ${taskTitle}</comment>`;
htmlForTaskPreview = taskAssignee  ? `<comment><mention-user>@${taskAssignee}</mention-user> ${taskTitle}</comment>` : `<comment>${taskTitle}</comment>`;

2023-06-05 06:57 UTC, sobitneupane reviewed
@dukenv0307 When I logout and login again, task assignee goes missing from task preview.


https://github.com/Expensify/App/assets/25876548/eafc3f3e-705b-4afd-b50b-791ebd055f42

2023-06-05 07:17 UTC, sobitneupane commented
@dukenv0307

Looks like when I edit the task report title, the task assignee is removed. Might not be related to this PR.

2023-06-05 08:03 UTC, sobitneupane reviewed
### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/25876548/05ff28ba-7550-42c1-b8a1-ae34625fb9e7

https://github.com/Expensify/App/assets/25876548/6ce44f25-a934-4082-84e6-2a1f370e0e74

<img width="1438" alt="Screenshot 2023-06-05 at 13 05 40" src="https://github.com/Expensify/App/assets/25876548/1b5e6dc1-f3d8-401a-aae5-a59b6a459fdf">

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/25876548/ee13ead4-2971-4f4c-809e-152d0addb447


</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/25876548/d6f2c99a-0d23-4aaf-afc6-01708f37506d

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/25876548/0ca53a54-0bac-454c-aa2e-ae66b650e747

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/25876548/b84ab7ff-af95-4627-b5e5-d58b014d4860


</details>

2023-06-05 08:10 UTC, sobitneupane commented
Found few issues. Most of them are not related to this PR. Few issues close to this PR:

- @thienlnam Do we want to show taskAssignee in LHN lastMessageText as well?
<img width="1017" alt="Screenshot 2023-06-05 at 13 51 00" src="https://github.com/Expensify/App/assets/25876548/3e930a2c-f19f-4797-8872-442ff2e3a776">

- @thienlnam Even after the task title is edited, LHN lastMessageText is not updated and shows the old task title. Do we want  to address the issue in this PR?
<img width="1017" alt="Screenshot 2023-06-05 at 13 53 30" src="https://github.com/Expensify/App/assets/25876548/14da4573-cb8d-4307-a2bb-3ea340c5cda5">

2023-06-05 13:50 UTC, thienlnam commented
> Looks like when I edit the task report title, the task assignee is removed. Might not be related to this PR.

Oh interesting, I'll look into this. Does this happen on main?

> @thienlnam Do we want to show taskAssignee in LHN lastMessageText as well?

No need to show the task assignee in the LHN for now

> @thienlnam Even after the task title is edited, LHN lastMessageText is not updated and shows the old task title. Do we want to address the issue in this PR?

I'm not sure if that can be fixed in the front-end, that probably also requires a BE change

2023-06-05 14:19 UTC, sobitneupane submitted a review, later dismissed
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

2023-06-05 14:27 UTC, thienlnam commented
> Yes, It happens in main as well.

Actually, I bet it happens on main because we changed what is returned via the API.
When you edit a task, you always have to provide all information on a task (title, description, assignee) otherwise it will default to null. Can we double check here that when we edit a task we're passing the correct fields to EditTask? I'm guessing this is happening because taskAssignee is null/empty somewhere in the params hence it is getting set to empty

2023-06-05 16:29 UTC, bondydaa submitted a review, later dismissed
Nothing stands out to me as problematic, 👍

2023-06-05 16:38 UTC, bondydaa commented
I'll leave this to @thienlnam to merge once the remaining questions are figured out.

2023-06-05 17:20 UTC, thienlnam commented
Yup, great find - could you please make those changes in this PR? This PR handles realigning the use of assignee to managerEmail

2023-06-05 17:40 UTC, thienlnam submitted a review, later dismissed
Looks great, thanks!

2023-06-05 18:10 UTC, thienlnam requested changes
One last thing I noticed as I pulled down your branch, you will have to update these 

    reportAction.reportAction.taskTitle = taskTitle;
    reportAction.reportAction.taskAssignee = taskAssignee;

to use 
childReportName and childManagerEmail

2023-06-05 19:14 UTC, thienlnam approved these changes
Lovely, thank you!

2023-06-05 19:20 UTC, merged

2023-06-05 19:26 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-06-06 19:50 UTC, OSBotify commented
🚀 [Cherry-picked](https://github.com/Expensify/App/actions/runs/5192443792) to staging by https://github.com/thienlnam in version: 1.3.24-5 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

@Expensify/applauseleads please QA this PR and check it off on the [deploy checklist](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3AStagingDeployCash) if it passes.

2023-06-07 03:28 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5193485581) to production by https://github.com/roryabraham in version: 1.3.24-5 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|failure ❌
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2023-06-07 13:19 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5193485581) to production by https://github.com/roryabraham in version: 1.3.24-5 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|cancelled 🔪
🍎 iOS 🍎|cancelled 🔪 
🕸 web 🕸|success ✅