migrate CopyTextToClipboard to functional component
Expensify/App pull request #20107
Opened 2023-06-02 22:43 UTC by nhminhduc

### Details

### Fixed Issues
$ https://github.com/Expensify/App/issues/16132
PROPOSAL: https://github.com/Expensify/App/issues/16132#issuecomment-1574224846

### Tests

1. Log in
2. Enter the chat with somebody
3. Copy message by message control button (hold for App, hover for Web)
4. Paste message
5. Check if message is in clipboard

### Offline tests
Same as online
### QA Steps
- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [X] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github [...]

2023-06-02 22:45 UTC, nhminhduc commented
I have read the CLA Document and I hereby sign the CLA

2023-06-02 22:46 UTC, nhminhduc commented
recheck

2023-06-02 23:03 UTC, PauloGasparSv commented
Re-opening this, I think it was closed by mistake : )

2023-06-02 23:42 UTC, nhminhduc commented
@PauloGasparSv  Tried to close+open to see if the check will go through :D

2023-06-05 15:06 UTC, mollfpr commented
@nhminhduc Could you resolve the lint issues? Thanks!

2023-06-05 15:36 UTC, mollfpr requested changes
Need to resolve the lint issue and other style problem. @nhminhduc If you using vscode, you can try the command "Format Document With..." > "Prettier - Code formatter".

2023-06-05 15:57 UTC, mollfpr commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

<!-- add screenshots or videos here -->

https://github.com/Expensify/App/assets/25520267/677de86e-02b4-4bd7-add9-625ef5abeda0


</details>

<details>
<summary>Mobile Web - Chrome</summary>

<!-- add screenshots or videos here -->

https://github.com/Expensify/App/assets/25520267/32e46402-feb1-4c0e-bc88-e65e11ee640a


</details>

<details>
<summary>Mobile Web - Safari</summary>

<!-- add screenshots or videos here -->

https://github.com/Expensify/App/assets/25520267/8f267434-8a84-447b-9f68-ee6306a25642


</details>

<details>
<summary>Desktop</summary>

<!-- add screenshots or videos here -->

https://github.com/Expensify/App/assets/25520267/c917be75-4b74-4a68-bb25-d9b8e1720c46 [...]

2023-06-05 20:18 UTC, nhminhduc commented on src/components/CopyTextToClipboard.js
> +import withDelayToggleButtonState, { withDelayToggleButtonStatePropTypes } from './withDelayToggleButtonState';
Done

2023-06-05 20:18 UTC, nhminhduc commented on src/components/CopyTextToClipboard.js
> +                    {({ hovered, pressed }) => (
Done

2023-06-05 20:18 UTC, nhminhduc commented on src/components/CopyTextToClipboard.js
>      textStyles: PropTypes.arrayOf(PropTypes.object),
Not really, it doesn't alert on my pc. But I added it again just in case.

2023-06-05 20:18 UTC, nhminhduc commented on src/components/CopyTextToClipboard.js
> +const CopyTextToClipboard = ({ text, textStyles, translate, isDelayButtonStateComplete, toggleDelayButtonState }) => {
Fixed, using props instead.

2023-06-05 20:32 UTC, nhminhduc commented
Updated to keep up with main branch:
Using PressableWithDelayToggle component.

2023-06-06 16:22 UTC, mollfpr commented
@nhminhduc Could you resolve the lint issue?

2023-06-06 16:25 UTC, mollfpr commented on src/components/CopyTextToClipboard.js
> +        Clipboard.setString(props.text);
@nhminhduc @PauloGasparSv Do you guys agree if we wrap this with `useCallback` since it has dependencies of `props.text`?

2023-06-06 21:23 UTC, nhminhduc commented
Added useCallback, displayName and fixed lint.

2023-06-07 02:33 UTC, mollfpr approved these changes
![giphy (1)](https://github.com/Expensify/App/assets/25520267/e5bdf47c-a3eb-424f-8c55-001d88fb5ec5)

Thanks @nhminhduc 👍

All yours @PauloGasparSv

2023-06-07 07:24 UTC, nhminhduc commented
> ![giphy (1)](https://user-images.githubusercontent.com/25520267/243892316-e5bdf47c-a3eb-424f-8c55-001d88fb5ec5.gif)
> 
> Thanks @nhminhduc 👍
> 
> All yours @PauloGasparSv

Thank you for your time 🙇

2023-06-07 12:31 UTC, PauloGasparSv commented
Hi @nhminhduc, can you please fix the linter errors here? (I think running `npx prettier --write .` is enough)

2023-06-07 13:24 UTC, PauloGasparSv submitted a review, later dismissed
LGTM!

Tested `main` and the copy icon doesn't show in the Contact Methods page there either.

Waiting on the linter fix to merge this

2023-06-07 19:07 UTC, nhminhduc commented
Run prettier 👍

2023-06-07 22:08 UTC, PauloGasparSv commented
> I think on android the icon is showing, just the color is quite off. Not sure why.

@nhminhduc do you mind updating the QA steps to use the Copy icon from somewhere else then? I think this will be reported as a problem if we don't explain in the QA section : )

2023-06-07 22:09 UTC, PauloGasparSv approved these changes

2023-06-07 22:09 UTC, merged

2023-06-07 22:13 UTC, nhminhduc commented
> > I think on android the icon is showing, just the color is quite off. Not sure why.
> 
> @nhminhduc do you mind updating the QA steps to use the Copy icon from somewhere else then? I think this will be reported as a problem if we don't explain in the QA section : )

I will update it tomorrow.

2023-06-07 22:15 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-06-08 10:27 UTC, nhminhduc commented
![Screenshot 2023-06-08 at 13 23 34](https://github.com/Expensify/App/assets/9055310/b67c22b4-b4be-47e0-8748-a12a8a3317a1)

<img width="1191" alt="Screenshot 2023-06-08 at 13 24 02" src="https://github.com/Expensify/App/assets/9055310/f4cb7079-bc98-4781-8b07-38e49d73e695">

@PauloGasparSv @mollfpr Hi, the icon in Android is indeed missing and it is a bug. But I do not think it is from this PR.
You can see above image, when I add `PressableWithDelayToggle` component with icon, it shows correctly in web, but not in android. This `CopyTextToClipboard` component are using the `PressableWithDelayToggle`, therefore it inherits this issue.
Should I create a bug ticket?

2023-06-08 14:21 UTC, PauloGasparSv commented
> Should I create a bug ticket?

I think that would be awesome @nhminhduc! So that's why, thks so much for explaining it too!

2023-06-09 13:54 UTC, isagoico commented
This PR QA is blocked on Android because of this issue https://github.com/Expensify/App/issues/17368. Rest of the platforms is a pass.

2023-06-13 00:22 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5249654407) to production by https://github.com/AndrewGable in version: 1.3.26-4 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅