17046 — migrate PressableWithotFocus to GenericPressable
Expensify/App pull request #20202
Opened 2023-06-05 20:08 UTC by robertKozik

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/17046
PROPOSAL: https://github.com/Expensify/App/issues/17046

### Tests

The PressableWithoutFocus is used inside two screens: DetailsPage, Image Renderer
1. DetailsPage
    - Log in
    - Open chat with different user
    - click the user avatar on the top of the screen to open RHN with user details
    - verify that user avatar styling is unchanged and press action can be triggered correctly
2. Image Renderer
    - Log in
    - Open chat
    - Upload an image
    - verify that uploaded image is clickable and styling is unchanged

- [X] Verify that no errors appear in the JS console

### Offline tests

Same as test steps
### QA Steps

Same as test steps

- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added t [...]

2023-06-06 12:59 UTC, parasharrajat requested changes

2023-06-06 21:43 UTC, robertKozik commented on src/components/PressableWithoutFocus.js
> +            <GenericPressable
I'm not sure. I've get there additionally GenericPresable proptypes

2023-06-07 00:53 UTC, parasharrajat requested changes
I noticed a few things on the Pressable itself. A few of the props are not defined. 
1. WrapperStyle
2. Style. 

Let's add and define those as well.

2023-06-12 10:00 UTC, robertKozik commented
@parasharrajat All changed according to your comments. I saw that lint is failing here, but locally it's not throwing any problems. It looks like it refers to the old directory of PressableWithoutFocus, so it's maybe cache issue.

2023-06-12 10:00 UTC, robertKozik commented on src/pages/DetailsPage.js
>                                                  style={styles.noOutline}
changed to style 👌🏼

2023-06-12 10:36 UTC, Nikhil-Vats commented
@parasharrajat FYI, while I was working on https://github.com/Expensify/App/pull/20577 as per your feedback on https://github.com/Expensify/App/pull/19545#discussion_r1226263871. There is 1 more file that uses `PressableWithoutFocus` -

https://github.com/Expensify/App/blob/6035b3e205f737180e9eeb6ab84b3fa984aa2744/src/pages/ProfilePage.js#L150

2023-06-12 10:50 UTC, robertKozik commented
@Nikhil-Vats Oh, I see now - I wasn't merged with main. Thanks!

2023-06-12 14:21 UTC, Nikhil-Vats commented on src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
> +                            style={styles.noOutline}
should be `style={[styles.noOutline]}`

2023-06-12 14:44 UTC, Nikhil-Vats commented on src/pages/ProfilePage.js
> +import PressableWithoutFocus from '../components/Pressable/PressableWithoutFocus';
I can't comment on the lines here since they were not changed but basically we are also using `PressableWithoutFocus` here with the wrong props.

2023-06-12 14:46 UTC, Nikhil-Vats commented on src/pages/ProfilePage.js
> +import PressableWithoutFocus from '../components/Pressable/PressableWithoutFocus';
and do we need to use the accessibility props here too like we have in `ImageRenderer` and `DetailsPage` -

```javascript
accessibilityRole="button"
accessibilityLabel={SOME_LABEL}
```

2023-06-12 14:55 UTC, Nikhil-Vats commented on src/pages/ProfilePage.js
> +import PressableWithoutFocus from '../components/Pressable/PressableWithoutFocus';
Yes I was not able to link the respective code line maybe because it is not part of change diff.

2023-06-12 15:20 UTC, Nikhil-Vats commented on src/pages/ProfilePage.js
> +import PressableWithoutFocus from '../components/Pressable/PressableWithoutFocus';
This is the relevant code -
https://github.com/Expensify/App/blob/6e47178b1c08df8ad2bb83a45a52bc6c3a5a5f09/src/pages/ProfilePage.js#L150-L153

2023-06-12 16:19 UTC, robertKozik commented on src/pages/ProfilePage.js
> +import PressableWithoutFocus from '../components/Pressable/PressableWithoutFocus';
Yeah, you're right. Thanks for pointing it out

2023-06-12 16:26 UTC, robertKozik commented
@parasharrajat alright, all conversations resolved

2023-06-13 11:20 UTC, Nikhil-Vats commented
Hey @parasharrajat 👋, did you get some time to test this? I am closing my related PR.

2023-06-14 12:22 UTC, robertKozik commented on src/components/HTMLEngineProvider/HTMLRenderers/ImageRenderer.js
> +                            accessibilityLabel={props.translate('common.attachment')}
I think we would need the translation for it then, as I cannot find `view the attachment` in already existing ones.

2023-06-15 21:55 UTC, parasharrajat approved these changes
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

cc: @cristipaval 

:ribbon: :eyes: :ribbon:  C+ reviewed

2023-06-15 21:59 UTC, cristipaval submitted a review, later dismissed

2023-06-16 19:49 UTC, cristipaval approved these changes

2023-06-16 19:50 UTC, merged

2023-06-21 02:27 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5329214929) to staging by https://github.com/cristipaval in version: 1.3.30-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-06-22 16:55 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5348093925) to production by https://github.com/luacmartins in version: 1.3.30-5 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-06-30 10:34 UTC, MonilBhavsar commented on src/pages/DetailsPage.js
Sorry If I am wrong, but It seems like we forgot to pass style prop in correct format here and it is causing warnings https://github.com/Expensify/App/issues/21556.

```
<PressableWithoutFocus
    style={[styles.noOutline]}
```

2023-06-30 10:47 UTC, MonilBhavsar commented on src/pages/DetailsPage.js
Thanks Rajat! @robertKozik If you agree, could you please make a follow up PR to fix https://github.com/Expensify/App/issues/21556

2023-07-04 11:27 UTC, MonilBhavsar commented on src/pages/DetailsPage.js
@robertKozik 👋

2023-07-08 09:31 UTC, robertKozik commented on src/pages/DetailsPage.js
Sorry, I missed the notifications about this one. I'll make the follow up to change the prop type of style ASAP

2023-07-10 07:23 UTC, robertKozik commented on src/pages/DetailsPage.js
@parasharrajat I've created the followup, but the but itself was already patched on main. I've unified the style type though. Let me know if it's worth a follow-up PR https://github.com/Expensify/App/pull/22539