fix: Going back after pressing sign in on public room
Expensify/App pull request #20733
Opened 2023-06-14 01:27 UTC by daordonez11

### Details
This is a border case, only anonymous users can go through this flow. I created a library called BackButtonUtils which only has Android and website implementations, when the anon user visited a public room and goes to login if the user presses the back button on Android or on the browser then the user is taken to the room again. More of a feature than an issue.
PS: Left it as backButtonHandler because it validates if should send to a report or close, so naming the method might complicate it
### Fixed Issues

$ https://github.com/Expensify/App/issues/20558
PROPOSAL: https://github.com/Expensify/App/issues/20558#issuecomment-1585445290

### Tests

1. Open a public room as unauthenticated user (i.e. https://staging.new.expensify.com/r/8813851443373010)
2. Click on sign-in
3. Click on the back button, should see the public room instead of closing the app
Tested in Browser, mobile browser and Android native

### Offline tests
N/A anonymous users only work online

### QA Steps
Same as test steps

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storyboo [...]

2023-06-14 01:29 UTC, daordonez11 commented
I have read the CLA Document and I hereby sign the CLA

2023-06-14 01:36 UTC, daordonez11 commented
@marcochavezf  did you guys rollback the migration of signinpage from function component to class component? The conflicts are a bit weird because of this.

Also, shall we review that behavior I explained in the video no this same PR or handle it as a different issue? (Opening report as a deeplink opens the main view with menu opened instead of the public room). If there is any other way of opening the public room let me know is just changing two lines.

2023-06-14 01:44 UTC, daordonez11 commented
yeah just saw @mountiny did the rollback. @marcochavezf let me know if I should update the PR to support class component or wait for that commit to enter main branch again.

2023-06-14 02:53 UTC, marcochavezf commented
Hi @daordonez11, there's an [existing issue](https://github.com/Expensify/App/issues/20412) related to the deep link problem, so I think that will be addressed there.

2023-06-14 03:00 UTC, marcochavezf commented
Regarding updating the PR to support the class, it's hard to tell since it will depend on when the [new changes](https://github.com/Expensify/App/issues/20676#issuecomment-1589449185) will be integrated. You could update the PR to adapt the changes, but there could also be the risk of updating the PR again if the new changes are merged to main first.

2023-06-14 03:02 UTC, marcochavezf commented
Ah also you might want to run `npm run lint` and `npm run prettier` to fix some styling issues (there's GH action to check that automatically but for some reason is not running, maybe because of the conflict).

2023-06-14 03:20 UTC, daordonez11 commented
For sure! Ran lint but not prettier, in terms of variable and function naming looks good?

2023-06-14 04:31 UTC, daordonez11 commented
Got it @marcochavezf  and actually with that merge of main the deeplink error is already fixed! Ran prettier, everything is up to date

2023-06-14 05:21 UTC, daordonez11 commented
Also @marcochavezf  I was testing and found a specific issue, the second time I press "Sign in" the "componenDidMount" of AuthScreens is called so you are automatically sent to the room, and you get no chance of sign in, I know pressing it twice does not sound like a general user flow but wanted to point it out: video of the error. 
[New Recording - 13_6_2023, 23_50_04.webm](https://github.com/Expensify/App/assets/13544910/d51bd180-e736-42a4-baf9-26171ee0caf9)

I'm not sure if it counts as a regression since before my implementation you cannot press it twice, it happens in browser web and mobile. In native it works fine

2023-06-14 05:56 UTC, daordonez11 commented
@marcochavezf  with this in line 125 of AuthScreens.js the autoredirect is fixed but the error of seeing the whole OptionsList reappears, still the origin is this [issue](https://github.com/Expensify/App/issues/20586) We can add my proposed line, avoid the regression and wait for [this](https://github.com/Expensify/App/issues/20412) solution
```javascript
if (this.props.lastOpenedPublicRoomID && !Session.isAnonymousUser()) {
            // Re-open the last opened public room if the user logged in from a public room link
            Report.openLastOpenedPublicRoom(this.props.lastOpenedPublicRoomID);
        }
```

2023-06-14 10:30 UTC, mountiny requested changes
This is a big change from the navigation perspective and we just rolled out a refactor, we should be very careful of introducing some one purpose code.

I will ask software mansion engineers to give a review of this PR and issue

2023-06-14 11:30 UTC, mollfpr commented on src/pages/signin/SignInPage.js
> +        BackButtonUtils.removeBackButtonListener(BackButtonUtils.backButtonHandler);
I'm not sure what the purpose of passing `backButtonHandler` separately here instead of calling it directly in the libs file is.

2023-06-14 11:57 UTC, daordonez11 commented on src/pages/signin/SignInPage.js
> +        BackButtonUtils.removeBackButtonListener(BackButtonUtils.backButtonHandler);
Yeah maybe just due to the original POC code I left it like that. I can definitely move it to the lib

2023-06-14 12:59 UTC, WoLewicki commented
Will it work after some more navigation happens? Also, is it the only case when such flow happens? Is it a generic enough behavior so it could be applied to other cases? Also, is there no option to just save the previous route somewhere in the `AppNavigator`. It seems rather like a bug with the implementation at our side, but I may be missing something.

2023-06-14 13:01 UTC, daordonez11 commented
Hey @mountiny we discussed a bit about this in the issue with Marco, basically AuthScreens and PublicScreens are in different navigation roots, I began last week so I'm not sure what was the scope of the navigation refactor but if we want to tackle this from the root we would have to join everything in a single Navigation root and use [protected views](https://reactnavigation.org/docs/auth-flow) only with groups and screens. Actually my original proposal was just to navigate if the lastRoomKey exists but this navigation is not possible between different Roots

2023-06-14 13:16 UTC, daordonez11 commented
Hi @WoLewicki I think when [Appnavigator](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/index.js) was created the anonymous user flow was no taken into account , AuthScreens and PublicScreens are created with different RootStacks instead of having protected views in a single stack, I'm not sure how much impact joining both would have but that is the root of why I implemented pop state listener. I would try to propose something additional but it is a bit out of my league for my first bug in expensify😅

2023-06-14 13:28 UTC, mountiny commented
@daordonez11 you are doing great job for your first bug for sure, thanks for your patience. 

I would probably prefer a proper discussion and research of options we have here to fix such bug and not rush this solution. I think what the bug itself is not minor but also not that critical to rush solution right now.

2023-06-14 13:40 UTC, daordonez11 commented
Totally agree playing with navigation is tricky! Maybe I can try a POC of joining both RootStacks or focus in a more specific bug while you guys decide. Also watch out for the line I mentioned in AuthScrens, that might be a possible regression in the PR of navigating to last room ( @marcochavezf )

2023-06-14 14:48 UTC, WoLewicki commented
Yeah, would be nice to have a POC to test for sure :rocket:

2023-06-14 21:14 UTC, daordonez11 commented
Had to force push because forgot to sign the merge :/ will work tonight on change requested by @mollfpr and the POC of joining the RootStack

2023-06-15 15:41 UTC, daordonez11 commented
Quick update after the Slack discussion: Probably this PR will be discarded, the scope of the issue changed a bit and the idea would be to move the sign-in page to the RHN modal, I will discuss with @marcochavezf  to make sure the new scope is clear for a new PR to be developed.

2023-06-15 17:02 UTC, mountiny commented
@danieldoglas yes lets start a new clean PR

2023-06-15 21:10 UTC, danieldoglas commented
@mountiny wrong daniel, I think?

2023-06-15 21:30 UTC, daordonez11 commented
@mountiny @marcochavezf @WoLewicki Here you can find a branch with the POC https://github.com/daordonez11/DanielExpensify/tree/poc-shared-root 
Left this message in slack:
I just did a mini POC of joining all in AuthScreens, its kinda feasible and actually the back button in the browser works :laughing:  but the thing is that Sidebar and Signin both share "Screens.Home" as the path, we need to register a new path e.g. "Signin" for them to work, it does work easily buuut everywhere sign in is called now it should do something like: Navigation.navigate(SCREENS.SIGNIN); in the poc I just included it in SignInRedirect.js you can find a working branch [HERE](https://github.com/daordonez11/DanielExpensify/tree/poc-shared-root). hehe I just wanted to check how hard it was but I don't have enough knowledge for a deep testing for testing viability. https://github.com/daordonez11/DanielExpensify/tree/poc-shared-root
Based on this I think testing might be huge due to the routes that are impacted. I think we can focus on 
[@Thiago Brezinski](https://expensify.slack.com/team/U052NTB4U0P)
’s PR and handle it as a modal in RHN to avoid testing impact (Although I have to admit joining everything does seem clearer and we can remove some classes and code, navigating to "SignIn" is more readable than going home in a different root)

2023-06-15 23:50 UTC, closed without merging

2023-06-15 23:51 UTC, daordonez11 commented
Closed after discussions, creating this one purpose code should be avoided, we will focus in the two alternatives of using a modal on RHN and merging the whole navigation in a single RootStack.