feat: support Spanish emojis
Expensify/App pull request #20828
Opened 2023-06-15 14:00 UTC by s-alves10

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/16086
PROPOSAL: https://github.com/Expensify/App/issues/16086#issuecomment-1545263685

### Tests
1. Open NewDot and go to any chat
2. Hovering any message shows reaction bar. Hover any emoji on the reaction bar and verify that emoji shortcode is translated
3. Hover any emoji reactions under the message and verify that the tooltip shows translated emoji short code. On mobile long press any emoji reactions and verify
4. Clicking the emoji+ button shows the emoji picker popup.
5. In this popup, verify that
    - search by Spanish keyword works
    - hovering category icons shows translated category names
    - skintone selection works for emojis supporting skintone
    - selecting emoji toggles emoji reaction
6. In the composer, verify that emoji suggestion and replacing works
7. Clicking the emoji button in the composer shows the emoji picker popup. Verify all items in step 5

- [x] Verify that no errors appear in the JS console

### Offline tests
1. Open NewDot and go to any chat
2. Hovering any message shows reaction bar. Hover any emoji on the reaction bar and verify that emoji shortcode is translated
3. Hover any emoji reactions under the message and verify that the tooltip shows translated emoji short code. On mobile long press any emoji reactions and verify
4. Clicking the emoji+ button shows the emoji picker popup.
5. In this popup, verify that
    - search by Spanish keyword works
    - hovering category icons shows translated category names
    - skintone selection works for emojis supporting skintone
    - selecting emoji toggles emoji reaction
6. In the composer, verify that emoji suggestion and replacing works
7. Clicking the emoji button in the composer shows the emoji picker popup. Verify all items in step 5

### QA Steps
1. Open NewDot and go to any chat
2. Hovering any message shows reaction bar. Hover any emoji on the reaction bar and verify that emoji shortcode is translated
3. Hover any emoji reactions under the message and verify that the tooltip shows translated emoji short code. On mobile long press any emoji reactions and verify
4. Clicking the emoji+ button shows the emoji picker popup.
5. In this popup, verify that
    - search by Spanish keyword works
    - hovering category icons shows translated category names
    - skintone selection works for emojis supporting skintone
    - selecting emoji toggles emoji reaction
6. In the composer, verify that emoji suggestion and replacing works
7. Clicking the emoji button in the composer shows the emoji picker popup. Verify all items in step 5

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there [...]

2023-06-16 17:15 UTC, s-alves10 commented on src/CONST.js
> +            shortcode: {en: '+1', es: '+1'},
This is for clarity. They are not names of emojis, just short codes of them. I mentioned this in issue before

2023-06-16 17:19 UTC, s-alves10 commented on src/components/EmojiPicker/CategoryShortcutBar.js
> +            name: PropTypes.string.isRequired,
Headers has no code unlike emojis. It has only name and icon. I wanted to add meanings to the properties

2023-06-16 17:49 UTC, 0xmiroslav reviewed
Your updated structure of name -> shortcode, header code -> name can be follow-up if needed.
In this PR, let's reduce code diff as much as possible and try to keep original structure but just add localization.

2023-06-16 18:16 UTC, s-alves10 commented on src/components/EmojiPicker/CategoryShortcutBar.js
> +            name: PropTypes.string.isRequired,
I'll change the headers back to original Spanish.
But let's keep the current emoji data structure as is. We have all Spanish emojis in its own structure, and we treat headers as emojis as well. Why don't we translate headers in the same place? I don't understand why headers should be in en/es.js. We can safely remove all emojis from en/es.js. This is more clear and reasonable, I think.

2023-06-16 18:20 UTC, s-alves10 commented on src/components/EmojiPicker/CategoryShortcutBar.js
> +            name: PropTypes.string.isRequired,
I think we should think about extension of supported languages, not about original structure.

2023-06-16 19:07 UTC, stitesExpensify requested changes
I'm a bit confused about some of these changes. I was under the impression that we were just adding spanish keywords to the file, and creating a spanish Trie. If you could clarify why other changes were necessary that would be great @s-alves10

2023-06-16 19:07 UTC, stitesExpensify commented on src/components/EmojiPicker/CategoryShortcutBar.js
> +            name: PropTypes.string.isRequired,
I'm confused @s-alves10 what is the benefit of this change? In the future we're going to add other files like `de.js` which with have german translations etc. for the whole app, so it seems like keeping the current structure makes more sense than changing it

2023-06-16 19:24 UTC, s-alves10 commented
@stitesExpensify @0xmiroslav 

Thank you for your feedback
Let me explain.

Emojis have its own data structure supporting multiple languages.
1. In order to storing all translations regarding emojis with the same structure, I changed quick emojis as well. Those have the same structure as normal emojis.
2. The order of skintones is different from what we see in the ND. It makes me confused and would make other developers as well. That's why I changed its order in the code
3. Supporting more languages isn't a problem in our current structure. All emoji translations would be removed under languages folder and we can care only other translations. The resource I used supports many other languages. Separating emojis and others in translation isn't more convenient?
4. Changing emoji data structure leads to a little more changes in the project but those are required in order to keep our emojis data consistently over the entire project.

2023-06-16 21:49 UTC, stitesExpensify commented
I agree. I don't think that we need to make such big changes in this PR. All we really want from this PR is for typing `:sonrisa:` to come up with 😄 and everything else to stay the same

2023-06-17 13:19 UTC, s-alves10 commented on src/CONST.js
> +            types: ['👍🏻', '👍🏼', '👍🏽', '👍🏾', '👍🏿'],
As you can see below, skintone numbering is weird. I think this change is reasonable.

https://github.com/s-alves10/App/blob/83ab0160a3b5c385fd26fffe20bdbccabf9249c0/assets/emojis.js#L56-L81

2023-06-18 15:57 UTC, s-alves10 commented
@0xmiroslav @stitesExpensify 

I changed the emoji data structure back to original. Now name property is object instead of string. Only necessary changes were left. Please check

2023-06-18 17:05 UTC, s-alves10 commented
> @s-alves10 just to confirm: you implemented [this suggestion](https://github.com/Expensify/App/issues/16086#issuecomment-1595369534) or not?

I was waiting for your suggestion. Do you want this feature to be implemented?

2023-06-18 17:30 UTC, 0xmiroslav reviewed
This is edge case but I am not sure if this can be bug or not (I don't think bug) but at least worth to consider:

(when switch language in another device)

https://github.com/Expensify/App/assets/97473779/2e7b0030-2dc7-4c99-b19d-b7755f639215

2023-06-18 17:39 UTC, s-alves10 commented on src/CONST.js
> +            types: ['👍🏻', '👍🏼', '👍🏽', '👍🏾', '👍🏿'],
Yeah. I'm sure

2023-06-18 17:41 UTC, s-alves10 commented
> This is edge case but I am not sure if this can be bug or not (I don't think bug) but at least worth to consider:
> 
> (when switch language in another device)
> 
>  Screen.Recording.2023-06-18.at.7.28.25.PM.mov

I think this is the expected behavior.

2023-06-18 18:24 UTC, s-alves10 commented
> Some emoji orders don't match with current version:

@0xmiroslav 

We're now using different database and the order is so important?

There are 1812 emojis in the old database and now 1811 emojis(except headers).
`🧑‍🎄` is missing in our current database because its Spanish version is missing.

2023-06-18 19:50 UTC, s-alves10 commented
> > 🧑‍🎄 is missing in our current database because its Spanish version is missing.
> 
> I don't want anyone to report this as regression. Let's imagine react with this emoji in old app and not see in new app. Actually crashes. If missing, why can't we add Spanish name and keywords manually? (at least fill Spanish values with English ones if hard to find Spanish copies)
> 
> <img alt="Screenshot 2023-06-18 at 8 29 42 PM" width="1680" src="https://user-images.githubusercontent.com/97473779/246683486-34bd45b7-d47f-4b9f-9967-91d16ae0b426.png">

Good idea. I'll do it

2023-06-18 20:16 UTC, s-alves10 commented on src/components/Reactions/ReportActionItemReactions.js
> +                const emoji = _.find(emojis, (e) => _.get(e, ['name', 'en'], '') === reaction.emoji);
Done

2023-06-18 20:16 UTC, s-alves10 commented on src/libs/EmojiUtils.js
> +const getLocalizedEmojiName = (enName, lang) => _.get(localizedEmojiNames, [enName, lang], '');
Done

2023-06-18 20:21 UTC, s-alves10 commented
@0xmiroslav 

PR was updated
1. Missing emoji added with same name and keywords for both English and Spanish
2. `getEmojiName` function created in `EmojiUtils.js`
3. `getLocalizedEmojiName` optimzed
4. Use CONST.LOCALES.DEFAULT

2023-06-18 21:12 UTC, s-alves10 commented
That comment is for extracting the old emoji database, I think. Is that needed for new database?

2023-06-18 21:20 UTC, s-alves10 commented
I extracted the new database in several steps. Manual operations are even needed. We can specify like "This database is extracted from `URL`" but cannot add the whole extraction process. What can I do?

2023-06-18 21:32 UTC, s-alves10 commented
> Above database concerns should have been discussed earlier in proposal stage.

https://github.com/Expensify/App/issues/16086#issuecomment-1580123722
https://github.com/Expensify/App/issues/16086#issuecomment-1587803766

2023-06-18 21:37 UTC, s-alves10 commented
I think we don't need to concern about keywords so much as long as we support all emojis in the old database.
You can see `smile` keyword doesn't match grinning in Slack.

2023-06-18 21:44 UTC, s-alves10 commented
> Different keywords are fine but not about name. We should make it compatible with old version. It affects all users who already reacted emojis with different names before this PR.

What do you suggest in this case?

2023-06-18 21:50 UTC, s-alves10 commented
I have a suggestion
Let's create the emoji name like
```
{
  en: 'xxx',
  es: 'yyy',
  old: 'zzz',
}
```

And handle emojis with old names

2023-06-18 22:01 UTC, s-alves10 commented
We can use old names for English, new names for Spanish.

2023-06-18 22:08 UTC, s-alves10 commented
What do you mean Spanish old names?

2023-06-18 22:23 UTC, s-alves10 commented
Name is added to keywords automatically in Trie. You can test it

2023-06-19 19:46 UTC, stitesExpensify commented
Okay, it looks like there has been a lot going on here and I think that we need to take a step back to set expectations and decide how to proceed. This conversation probably should have happened in the issue, but I think that this conversation is necessary right now.

Expectations:
1. You can search for emojis in the language you have chosen, as well as english
    - This should be extensible so that when we add more languages we don't need a lot of changes
2. The current structure of emoji.js with regards to `name` and `code` should not change
3. The english names of emojis should not be changed because we already have them saved in the DB
4. Skintone order should not be changed because users who have reacted with a certain skin tone will now have reacted with a different skin tone
5. All reactions should be sent to the server using the english name

Decisions:
1. Should we add more keywords to emoji.js, or create separate `emoijs/common.js` (for skintones), `en.emojis.js`, `es.emojis.js`?
    - Personally I am in favor of creating separate files so that we mirror `en.js` and `es.js`. This has the added benefit of not changing the existing emoji names which are already in the database.
2. How should we display the usages of the emojis? (Show it in chosen language always, or show in english + language, or whatever language was used
    - I think that chosen language makes the most sense


Are there any other decisions that need to be made here? cc @0xmiroslav

2023-06-19 23:02 UTC, s-alves10 commented
> We can use current names/keywords for English, new names/keywords for Spanish.

@0xmiroslav 

I think https://github.com/Expensify/App/pull/20828#issuecomment-1597677913 includes this.

2023-06-19 23:09 UTC, stitesExpensify commented
> We can use current names/keywords for English, new names/keywords for Spanish.

Everything should be referenced / stored in the DB using the english name. 
For display on the front end we should be translating `english name` -> `code` -> `<language> name`

2023-06-20 16:33 UTC, s-alves10 commented
@0xmiroslav 

skintones, headers, types are the same for all locales. I think these should be stored in common.js

2023-06-20 19:19 UTC, s-alves10 commented
@0xmiroslav @stitesExpensify 

https://github.com/Expensify/App/pull/20828#issuecomment-1598235677 were all implemented
Please review

2023-06-21 00:14 UTC, stitesExpensify commented
> just to confirm that this was your concern?

Yes, that is what I had in mind. The only potential issue is that when rendering we need the headers in the same list, so headers might actually have to be duplicated.

2023-06-21 00:15 UTC, stitesExpensify commented
FYI I will be OOO until 6/27 so the reviews of this PR will be on hold for the next few days. If you think that this PR needs to be completed faster than that, feel free to reach out in #expensify-open-source for a new reviewer, or post on the issue and the BugZero team member can help out!

2023-06-21 04:56 UTC, s-alves10 commented
@0xmiroslav 

Please check the updated PR

2023-06-28 15:38 UTC, stitesExpensify commented
Feel free to start testing when you get a chance @0xmiroslav, I'm going to do the same right now.

2023-06-28 15:44 UTC, stitesExpensify commented
@iwiznia would you mind giving this a test to please since you actually use the product in Spanish? I just want to make sure that we are creating the expected UI, especially when doing `:colon-codes:`

2023-06-28 15:54 UTC, stitesExpensify commented
@s-alves10 can you add to the QA steps that we should be testing this for:
1. Both english and spanish
2. Switching between the languages updates the tooltips
3. When set to spanish you can search in english, but not vice-versa

2023-06-28 16:09 UTC, s-alves10 commented
> @s-alves10 can you add to the QA steps that we should be testing this for:
> 
> 1. Both english and spanish
> 2. Switching between the languages updates the tooltips
> 3. When set to spanish you can search in english, but not vice-versa

I've updated the PR

2023-06-28 21:23 UTC, OSBotify commented
Use the links below to test this build in android and iOS. Happy testing!

2023-06-28 21:23 UTC, OSBotify commented
:test_tube::test_tube: Use the links below to test this build in android and iOS. Happy testing! :test_tube::test_tube:
| android :robot:  | iOS :apple: |
| ------------- | ------------- |
| https://ad-hoc-expensify-cash.s3.amazonaws.com/android/20828/index.html  | https://ad-hoc-expensify-cash.s3.amazonaws.com/ios/20828/index.html  |
| ![Android](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://ad-hoc-expensify-cash.s3.amazonaws.com/android/20828/index.html)  | ![iOS](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://ad-hoc-expensify-cash.s3.amazonaws.com/ios/20828/index.html)  |
| desktop :computer: | web :spider_web: |
| https://ad-hoc-expensify-cash.s3.amazonaws.com/desktop/20828/NewExpensify.dmg  | https://20828.pr-testing.expensify.com  |
| ![Desktop](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://ad-hoc-expensify-cash.s3.amazonaws.com/desktop/20828/NewExpensify.dmg)  | ![Web](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://20828.pr-testing.expensify.com)  |

2023-06-28 22:57 UTC, stitesExpensify commented
cc @JmillsExpensify in case you want to give it a shot :)

2023-06-30 21:38 UTC, 0xmiroslav reviewed
Console error when type in emoji picker in android but not a blocker as already happening on production

<img width="338" alt="console" src="https://github.com/Expensify/App/assets/97473779/98440bff-5046-4c16-868f-57fac9fb0eec">

2023-06-30 21:38 UTC, 0xmiroslav approved these changes
LGTM.
@stitesExpensify all yours!

2023-07-03 06:19 UTC, 0xmiroslav requested changes

2023-07-03 06:31 UTC, s-alves10 commented on src/components/Reactions/QuickEmojiReactions/BaseQuickEmojiReactions.js
> +                    text={`:${EmojiUtils.getLocalizedEmojiName(emoji.name, props.preferredLocale)}:`}
Fixed

2023-07-03 06:37 UTC, 0xmiroslav approved these changes

2023-07-03 06:45 UTC, 0xmiroslav approved these changes

2023-07-04 19:38 UTC, s-alves10 commented
@stitesExpensify 

Will you take a look at the PR again?

2023-07-05 15:16 UTC, stitesExpensify commented
Hi there! Taking a look!

2023-07-05 16:04 UTC, stitesExpensify requested changes
Code is looking great! Just a couple of small questions before I approve

2023-07-05 16:55 UTC, s-alves10 commented on src/libs/EmojiTrie.js
>  Timing.end(CONST.TIMING.TRIE_INITIALIZATION);
In dev mode, these operations take about 500ms. In production would be far shorter.
These operations are based on the old function. Almost same.

2023-07-05 17:26 UTC, s-alves10 commented
@stitesExpensify 

Please take a look at the changes. Thank you

2023-07-07 22:13 UTC, stitesExpensify approved these changes

2023-07-07 22:18 UTC, merged

2023-07-07 22:22 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-07-11 00:20 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5514102677) to staging by https://github.com/stitesExpensify in version: 1.3.39-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-07-13 01:44 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5538073623) to production by https://github.com/francoisl in version: 1.3.39-11 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-09-14 15:44 UTC, jjcoffee commented
Just coming from [this issue](https://github.com/Expensify/App/issues/25735) that fixed a bug that this PR introduced that caused duplicate suggestions to appear. Since we add the English Trie node with the suggestion's name in English, this won't match the equivalent Spanish emoji name, so it gets added as a separate match here:

https://github.com/Expensify/App/blob/3f9f1e6e2ce91468a536755f8d5830a2f77d7eaa/src/libs/EmojiUtils.js#L381