Add authToken to Image requests to allow attachments to load
Expensify/App pull request #218
Opened 2020-08-17 18:41 UTC by AndrewGable

Fixes broken images, you can test by going to a report on dev uploading the image, then clearing your cookies and going to chat and verify you can see the image (on all platforms)

2020-08-17 20:59 UTC, Jag96 reviewed
Should we update the readme for this for web? Without that diff set images don't show up for me on web, so I assume this will happen to everybody else.

2020-08-18 03:38 UTC, Jag96 reviewed
It looks like this is working on iOS, but on Android and web I still can't load chat-attachments images:

| Android | Web |
|---|----|
| ![image](https://user-images.githubusercontent.com/3981102/90466387-83f15880-e0c6-11ea-97db-52c1daa4780e.png) | ![image](https://user-images.githubusercontent.com/3981102/90467616-7ab5bb00-e0c9-11ea-8bb0-43afb2ff2293.png) |

Confirmed there's CORB issues in the console as well, same on master
![image](https://user-images.githubusercontent.com/3981102/90467670-9faa2e00-e0c9-11ea-9034-88aee5bd62ae.png)

2020-08-18 21:00 UTC, tgolen requested changes

2020-08-18 21:06 UTC, tgolen approved these changes

2020-08-18 21:06 UTC, merged