Money request header scrollable
Expensify/App pull request #21918
Opened 2023-06-29 23:39 UTC by ShogunFire

### Details

We are dividing the header in two part and one part is going to be in the list, we put it as the footer even if we want it to act like a header because the list in inverted. We are doing this change because the header was taking too much space on little screens. 

### Fixed Issues

$ https://github.com/Expensify/App/issues/19389
PROPOSAL: https://github.com/Expensify/App/issues/19389#issuecomment-1582516671

### Tests

- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [] I have checked off every checkbox in the P [...]

2023-06-30 02:36 UTC, ShogunFire commented
Hello @aimane-chnaif, it looks like there is a lint problem unrelated to my code, I ran npm run lint on my computer and fixed some errors even if I think there are still some syntax errors that they don't tell me, I also changed the name of the files as MaciejSWM suggested. 

The biggest change from the initial branch is the android version of InvertedList, I did it because Lint asked me to validate the props, I copied the way it was done in index.js I hope it's good. 

Maybe you can start the review until they fix the lint error, thanks

2023-06-30 14:57 UTC, AndrewGable requested changes, later dismissed

2023-06-30 14:57 UTC, AndrewGable commented on .github/actionlint.yaml
> +    - ubuntu-20.04-64core
Please revert this change

2023-06-30 18:59 UTC, AndrewGable commented
Looks like lint is passing now 👍 

<img width="268" alt="Screenshot 2023-06-30 at 12 59 03 PM" src="https://github.com/Expensify/App/assets/2838819/adf0fd88-25ad-48e5-9a99-8e14fab1e3ca">

2023-06-30 19:00 UTC, AndrewGable reviewed
Looks like lint is passing now 👍 

<img width="268" alt="Screenshot 2023-06-30 at 12 59 03 PM" src="https://github.com/Expensify/App/assets/2838819/adf0fd88-25ad-48e5-9a99-8e14fab1e3ca">

2023-06-30 19:04 UTC, ShogunFire commented
Yes... Weird... Thank you @AndrewGable

2023-07-03 21:57 UTC, ShogunFire commented
Hello @aimane-chnaif I have trouble degugging on android so I don't see the error in the console but I made a change on prop type. Can you check if it works now or can you send me the error ?

I also merged.

I have a weird bug on android, when I open the money request, sometimes it doesn't show the list, maybe it's related to this error that you have:

https://github.com/Expensify/App/assets/19537677/e9da63e7-df1e-4562-a6b5-e5637c759112

2023-07-03 22:39 UTC, ShogunFire commented
I changed it thanks, I just tested on main and it's also happening

One last thing, I don't really understand the code in InvertedList android and maybe there is a way to simplify like this, it seems to work and it is hat we have in the normal (not inverted) FlatList for android: 

![image](https://github.com/Expensify/App/assets/19537677/fb2cf3f6-9c30-41c6-8529-0bb4e27eec05)

What do you think ?

2023-07-04 12:53 UTC, aimane-chnaif approved these changes
LGTM 🎉 

@madmax330 @shawnborton all yours!

2023-07-05 13:21 UTC, shawnborton commented
Hmm @JmillsExpensify @trjExpensify how are we handling all of the money request/IOU changes?

For example, somethings that stand out to me:
- the top header part should basically just look like all other chat headers now. We also want to put the pay button up there.
- we removed the "To" field
- there would be just a wide Total line that sits directly above chat content

2023-07-05 13:21 UTC, shawnborton commented
But if we're just breaking the changes out into chunks, I suppose this is fine?

2023-07-05 14:58 UTC, trjExpensify commented
Here's [the main issue](https://github.com/Expensify/App/issues/20486) we were going from, I don't think this PR has come from it, and the changes to avatars and headers were being taken care of by @chiragsalian and @grgia. It does seem a bit unclear though, but I'll take that to the main issue and not in this PR.

2023-07-06 09:37 UTC, madmax330 commented
@trjExpensify so are we good to go with this PR or are we holding it for something?

2023-07-06 13:37 UTC, trjExpensify commented
>@trjExpensify so are we good to go with this PR or are we holding it for something?

Yup, consensus in the main issue was that there isn't a conflict 👍

2023-07-10 10:13 UTC, madmax330 approved these changes

2023-07-10 10:14 UTC, merged

2023-07-10 10:43 UTC, Julesssss commented
There was an outstanding lint issue here, maybe a new check was added recently?

2023-07-10 11:45 UTC, Julesssss commented
It's likely we recently added/updated a check on main. So the issue wouldn't have been seen until the changes were merged with main (or main merged to the branch). Anyway, solve now 👍

2023-07-11 00:20 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5514102677) to staging by https://github.com/madmax330 in version: 1.3.39-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-07-11 03:01 UTC, mvtglobally commented
@ShogunFire @aimane-chnaif @madmax330 @AndrewGable No QA needed here?

2023-07-11 03:04 UTC, ShogunFire commented
@mvtglobally Oups, looks like I forgot to add test steps sorry, I am doing this now

2023-07-11 03:19 UTC, ShogunFire commented
@mvtglobally I have added the steps

2023-07-11 03:22 UTC, ShogunFire commented
And I guess I should be follow the PR steps better next time because I just found a bug, when we are offline the scrollable header is not greyed out

2023-07-11 13:37 UTC, ShogunFire commented
@aimane-chnaif @grgia Are you sure we can just ignore it ? It is now a deploy blocker :(

2023-07-11 13:58 UTC, madmax330 commented
@ShogunFire Go ahead and create your PR and we'll review

2023-07-13 01:44 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5538073623) to production by https://github.com/francoisl in version: 1.3.39-11 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅