[No QA] Remove the ReportActionContextMenu beta
Expensify/App pull request #2234
Opened 2021-04-05 23:15 UTC by roryabraham

### Details
<Explanation of the change or anything fishy that is going on>

### Fixed Issues
Coming from [this Slack thread](https://expensify.slack.com/archives/C03U7DCU4/p1617641264155600)

### Tests (Web/Desktop)
1. Run the app
2. Hover a message, make sure that the `reportActionContextMenu` appears (it's just one lonely clipboard icon) now 😭

![image](https://user-images.githubusercontent.com/47436092/113637472-84286f00-9629-11eb-9e4f-8302e3759d4c.png)

3. Right-click a message, make sure that the menu appears:

![image](https://user-images.githubusercontent.com/47436092/113637520-a28e6a80-9629-11eb-8fa7-7ee07b79e7af.png)

### Tests (iOS/Android/mWeb)
1. Run the app
2. Long-press a message, make sure that the menu appears:

![image](https://user-images.githubusercontent.com/47436092/113637616-e5e8d900-9629-11eb-8173-62fb03ecea69.png)

### QA Steps
The "Copy Comment" functionality is covered by regression testing, so we shouldn't need any extra QA here.

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web
![image](https://user-images.githubusercontent.com/47436092/113637472-84286f00-9629-11eb-9e4f-8302e3759d4c.png)
![image](https://user-images.githubusercontent.com/47436092/113637520-a28e6a80-9629-11eb-8fa7-7ee07b79e7af.png)

#### Mobile Web
![image](https://user-images.githubusercontent.com/47436092/113637616-e5e8d900-9629-11eb-8173-62fb03ecea69.png)

#### Desktop

#### iOS

#### Android

2021-04-05 23:58 UTC, Jag96 requested changes
When running this on web I get an error, looks like there's still 2 usages of `isInReportActionContextMenuBeta`
```
ReportActionItem.js:101 Uncaught TypeError: _this2.isInReportActionContextMenuBeta is not a function
```

2021-04-05 23:58 UTC, Jag96 commented on src/pages/home/report/ReportActionItem.js
> -        return _.contains(this.props.betas, CONST.BETAS.REPORT_ACTION_CONTEXT_MENU)
Do we still need this beta constant? It looks like its unused now

2021-04-06 00:08 UTC, roryabraham commented
Updated!

2021-04-06 01:29 UTC, yuwenmemon approved these changes

2021-04-06 17:10 UTC, Jag96 approved these changes

2021-04-06 17:10 UTC, merged