fix inline code blocks for native platforms
Expensify/App pull request #2307
Opened 2021-04-08 21:24 UTC by parasharrajat

Please review @sketchydroide.

### Details

#### Problem

We (Including other contributors) tried using a combination of Text & View tag to achieve the above UI but there are a couple of issues as follows:
 1. Text is rendered as a block box but we want inline text.
 2. In Another way, we can get the inline text but border and border-radius are not being rendered.

#### How I fixed it?
I had an idea of tokenizing the text. Then apply the style selectively. This is working well. I have made a small snap here.

1. we create one wrapper component which divides the text into tokens(words) divided based on word break. This component put the text tokens inline into a view and renders it.
2. We can then pass styles selectively to tokens and manage the border-radius for the first and last tokens.

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes #986

### Tests / QA Steps

- Type a sentence with code block formatting (single ticks) in the middle, like this:
   This is a test to see `how code renders in the middle` of a sentence on mobile.
- Notice that it should render inline like normal text.

### Issue(Not blocker)
1. ~Inline Rendered code block is not vertically center with respect to the text.~ :heavy_check_mark: *Fixed*

### Tested On

- [x] iOS
- [x] Android
- [x] Web
- [x] Desktop

### Screenshots

#### Web / Desktop

![localhost_8080_r_68438375](https://user-images.githubusercontent.com/24370807/115467018-7cceab80-a24e-11eb-8469-c5493ca823d0.png)

#### Android

<img width="300" src="https://user-images.githubusercontent.com/24370807/115466438-beab2200-a24d-11eb-8d61-56db7956a563.jpg" >

#### IOS
I don't have an IOS device thus I mimicked the logic [here](https://snack.expo.io/@rajat_parashar/text-wrapping) and which can be seen working well.

![image](https://user-images.githubusercontent.com/24370807/115466577-e8644900-a24d-11eb-9199-55b9afb7cf31.png)

2021-04-08 22:10 UTC, parasharrajat commented
@shawnborton I hope this style matches the desired one.

2021-04-08 22:46 UTC, Luke9389 commented
Hey @parasharrajat, I'm noticing that this gets a bit clunky when there are longer words in the text. Here's what I'm talkin' about: 
<img width="641" alt="Screen Shot 2021-04-08 at 3 44 23 PM" src="https://user-images.githubusercontent.com/49007721/114105416-8f75d780-9881-11eb-9c9a-a0fd2b6b4fd4.png">

Think there's any way for us to fill in the white space with the code text style?

2021-04-08 22:55 UTC, shawnborton commented
So if all of our message text is at 15px text size but with 20px line height, that means a normal looking piece of text should be 20px tall. I wonder if we could make our inline code (and code blocks for that matter) use a text size of 13px and a line height of 18px? This way the text feels more balanced, and when code wraps two lines, we get a small gap (2px) between the lines:
![image](https://user-images.githubusercontent.com/2319350/114106013-c1d40480-9882-11eb-8617-4fc94f5c01e4.png)

2021-04-08 23:19 UTC, parasharrajat commented
@Luke9389. I not sure how to tackle this issue. In this solution, each worked is wrapped into a separate view, and then these are being flex wrapped in the next line. but if a single word would be very big it will wrap to the next line. So far I have no idea of how to break that word into child views.

2021-04-08 23:50 UTC, parasharrajat commented
Updated @shawnborton. Let me know if that works.

2021-04-09 14:33 UTC, shawnborton commented
@parasharrajat did you update the screenshots as well?

2021-04-09 14:34 UTC, parasharrajat commented
Oh no. I will update them.

2021-04-09 18:07 UTC, parasharrajat commented
@shawnborton I have updated the screens. Just I don't have IOS so I have put the image from [snap](https://snack.expo.io/@rajat_parashar/text-wrapping).

2021-04-09 19:46 UTC, shawnborton commented
Hmm it looks like there is a larger gap between lines that have regular text + inline code, versus lines that are all inline code:
![image](https://user-images.githubusercontent.com/2319350/114233070-a2e07b80-9931-11eb-9def-a32a502b6607.png)

2021-04-09 20:35 UTC, parasharrajat commented
@shawnborton I tried a lot of ways for this. **On IOS, the gap is equal** but on Android, the inline code is vertically top relative to the text so I have to push the inline code towards the bottom to Keep it centered which Increases the gap where inline code comes on the same line with the text.

After many trials, I found this solution to add border and border-radius to the inline code which has **this drawback on Android**. we(including other proposals) were only able to achieve the background-color for the inline code so far. I am open to suggestions if someone can look at the code and help me improve it.

2021-04-12 15:15 UTC, shawnborton commented
Going to tag my pal @marcaaron for thoughts on this from a technical perspective, as I know we've gone through this one a few times now. 

It seems like we're getting close to the solution though. Is there any way you can make it so that both the normal text and inline code have a height of 20? If we can get the 20px tall containers to line up correctly, we hopefully can control the styles inside of them.

2021-04-12 15:57 UTC, parasharrajat commented
I see that we set the line height of the whole text message then we can reach to almost equal gap but that text is not controlled by the inline code block and I don't think we don't want to change the line height for all messages. But let me see what I can do here.

2021-04-12 16:49 UTC, shawnborton commented
Hmm I don't think I am quite following your comment. But I am pretty sure the line height for a default message is 20 right?

So my thinking is that if a block of text has a height/line height of 20, and then an inline code block is wrapped with a height of 20, those two elements should vertically align. Inside of the inline code block wrapper, we can make the code appear to be 18 tall with a margin top of 1 and a margin bottom of 1. Let me know if that makes sense.

2021-04-12 18:26 UTC, marcaaron commented
Coming in a bit late to this PR and the overall direction and I'm curious... did we ever consider applying a solution like this in `react-native-render-html`?  IIRC we had a conversation going with a maintainer where they suggested a similar approach cc @AndrewGable 

As for styling advice, let's keep trying to achieve what we want for a bit. I don't have time to look into this today, but if we are still stuck down the line I'll jump in and see what I can do.

2021-04-14 21:01 UTC, parasharrajat commented
@shawnborton So This is how it is rendered initially 
![image](https://user-images.githubusercontent.com/24370807/114777817-bc4e5100-9d91-11eb-8c74-e946903ef91d.png)

Now to make the text inline I have to move the boxes some px downwards which works fine for the box which has normal inline text such as line 2 but when we have a whole line of code block then the negative margin which we gave to pull it down is not necessary and thus as a side effect it unnecessarily pull the whole line downwards and reducing the gap between this and next line.

2021-04-15 15:32 UTC, shawnborton commented
Hmm okay. Are all of your changes pushed to your branch? Maybe I can pull it down and test on my end and let you know what I find.

2021-04-15 15:44 UTC, parasharrajat commented
@shawnborton That would be really great. yeah its pushed.

2021-04-19 21:22 UTC, shawnborton commented
I tried playing around with this but I am stumped. I added some helper background colors to see where things were breaking down:
![image](https://user-images.githubusercontent.com/2319350/115304653-0b8ddc00-a11a-11eb-8dda-9806a4e6decf.png)


It seems like when the message is only inline code, we can make it behave correctly in terms of making everything 20px tall, but the inner code staying at 18px with the 1px gap around it within the 20px container. Notice the nice 2px gaps when this goes multi line:
![image](https://user-images.githubusercontent.com/2319350/115304752-2ceec800-a11a-11eb-972e-25db4126a299.png)

When we compare a message that is text-only and is two lines versus a message that is inline-code-only and two lines, the size is pretty similar, though it looks like the inline code is shifted upwards of about 2px:
![image](https://user-images.githubusercontent.com/2319350/115304938-6a535580-a11a-11eb-8aef-77170b14d0e4.png)

But the biggest thing that seems to be breaking is when we have a combination of text and inline code that flows to multiple lines:
![image](https://user-images.githubusercontent.com/2319350/115304978-793a0800-a11a-11eb-8543-95cd9bc7cd77.png)

Notice how there is a big gap between the two red blocks? Ideally that entire block should be 40px tall but it's actually 48px tall... so somehow there is a mystery 8px being added, and my eyes are telling me that it's an extra 4px being added to the bottom of each line. 

Anyways, I hope that is helpful in getting us closer, but I'm not entirely sure how to fix that mystery gap problem.

2021-04-20 21:29 UTC, parasharrajat commented
@shawnborton @Luke9389. Breakthrough here. I have managed the gap. :partying_face: :partying_face: 
![1618954137890](https://user-images.githubusercontent.com/24370807/115466350-958a9180-a24d-11eb-9095-c47ba44cab30.jpg)

2021-04-20 21:31 UTC, shawnborton commented
Whoa, amazing Rajat!!

2021-04-20 21:32 UTC, shawnborton commented
I think this is the behavior we want on all platforms, not just native. Is it possible to implement this everywhere?

2021-04-20 21:34 UTC, parasharrajat commented
@shawnborton Yup. 
here is web/ Desktop
![localhost_8080_r_68438375](https://user-images.githubusercontent.com/24370807/115466894-5446b180-a24e-11eb-9adc-0d74bf06e003.png)

2021-04-20 21:36 UTC, shawnborton commented
Awesome, design-wise this looks great to me.

2021-04-20 23:02 UTC, Luke9389 requested changes
Hey Rajat, this looks awesome, nice job. 
I put some knit-picky whitespace reviews in, but otherwise this looks great!

2021-04-20 23:26 UTC, parasharrajat commented
@Luke9389  Updated. Thanks

2021-04-20 23:51 UTC, Luke9389 approved these changes
Nailed it Rajat, way to go!

2021-04-20 23:51 UTC, merged

2021-04-21 00:22 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/768916423) to staging 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-04-21 20:48 UTC, isagoico commented
## Chat - Sent code blocks are not properly centered

## Expected Result
Sent message and code blocks are vertically centered/alligned

## Actual Result
Code block is not centered vertically

## Action Performed
1. Open staging.expensify.cash and login
2. Open any conversation
3. Send any message within ` , to make them code blocks

## Platform 

iOS ✔️ 

**Build** 1.0.28-0

**Notes/Images/Video**

![image](https://user-images.githubusercontent.com/44479856/115618652-ff904e80-a2c0-11eb-83c8-3f1297ca1ebc.png)

2021-04-23 00:56 UTC, roryabraham commented
Since this is a deploy blocker, the fix for which is still in review, I'm going to revert this PR. @parasharrajat what this means for you is that you'll need to resubmit a new PR that's a combination of this PR (#2307) and the fix for the deploy blocker (#2527).

That way, we can hopefully move forward with a production deploy as soon as possible. Let me know if you have any questions.

2021-04-23 01:02 UTC, parasharrajat commented
Sure

2021-05-08 01:43 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/822089210) to production in version: 1.0.39-5🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-11-11 21:19 UTC, s77rt commented on src/styles/styles.js
> +            fontSize: 13,
The inline code block font size was being inherited. But after explicitly setting it to 13px, it's always rendered at 13px even if the parent is a `H1` where the font size is expected to be a little bigger. (Coming from https://github.com/Expensify/App/issues/30203)