Fix: cannot change assignee after task created
Expensify/App pull request #23530
Opened 2023-07-25 07:57 UTC by dukenv0307

### Details
We should use props.report and reportID from route instead of props.task.report
 
### Fixed Issues

$ https://github.com/Expensify/App/issues/23556
PROPOSAL: https://github.com/Expensify/App/issues/23556#issuecomment-1650231285

### Tests

1. Go to any task report
2. Click + on composer > Assign task
3. Click back button to close modal
4. Click Assignee field
5. Select a contact you have a chat with already.
6. Verify that selecting new contact successful without error
7. Repeat the process but this time when selecting a new contact, select someone you never talked to via chat.

- [x] Verify that no errors appear in the JS console

### Offline tests

Same above

### QA Steps

1. Go to any task report
2. Click + on composer > Assign task
3. Click back button to close modal
4. Click Assignee field
5. Select a contact you have a chat with already.
6. Verify that selecting new contact successful without error
7. Repeat the process but this time when selecting a new contact, select someone you never talked to via chat.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not  [...]

2023-08-02 21:07 UTC, situchan commented on src/pages/tasks/TaskAssigneeSelectorModal.js
> +                            props.route.params.reportID && lodashGet(props.reports, `report_${props.route.params.reportID}`, undefined)
This code is duplicated. Please make common function for this

2023-08-02 21:09 UTC, situchan commented on src/pages/tasks/TaskAssigneeSelectorModal.js
> +                            props.route.params.reportID && lodashGet(props.reports, `report_${props.route.params.reportID}`, undefined)
Also use `${ONYXKEYS.COLLECTION.REPORT}${props.route.params.reportID}` instead of `report_${props.route.params.reportID}`

2023-08-02 21:40 UTC, situchan commented
@dukenv0307 this is what I suggest. does it make sense?

```diff
+   const report = useMemo(() => {
+       if (!props.route.params || !props.route.params.reportID) {
+           return null;
+       }
+       return props.reports[`${ONYXKEYS.COLLECTION.REPORT}${props.route.params.reportID}`];
+   }, [props.reports, props.route.params]);

...

        // Check to see if we're editing a task and if so, update the assignee
-       if (props.route.params.reportID && props.task.report.reportID === props.route.params.reportID) {
+       if (report) {
            // There was an issue where sometimes a new assignee didn't have a DM thread
            // This would cause the app to crash, so we need to make sure we have a DM thread
-           Task.setAssigneeValue(option.login, option.accountID, props.task.shareDestination, OptionsListUtils.isCurrentUser(option));
+           Task.setAssigneeValue(option.login, option.accountID, props.route.params.reportID, OptionsListUtils.isCurrentUser(option));

            // Pass through the selected assignee
-           Task.editTaskAndNavigate(props.task.report, props.session.accountID, {
+           Task.editTaskAndNavigate(report, props.session.accountID, {
                assignee: option.login,
                assigneeAccountID: option.accountID,
            });
        }
    };

    return (
        <ScreenWrapper includeSafeAreaPaddingBottom={false}>
            {({didScreenTransitionEnd, safeAreaPaddingBottomStyle}) => (
                <>
                    <HeaderWithBackButton
                        title={props.translate('task.assignee')}
-                       onBackButtonPress={() => (lodashGet(props.task.report, 'isExistingTaskReport') ? Navigation.dismissModal() : Navigation.goBack(ROUTES.NEW_TASK))}
+                       onBackButtonPress={() => (report ? Navigation.dismissModal() : Navigation.goBack(ROUTES.NEW_TASK))}
                    />
```

2023-08-03 09:35 UTC, situchan commented
@dukenv0307 please pull main

2023-08-03 09:52 UTC, situchan commented on src/pages/tasks/TaskAssigneeSelectorModal.js
> +        return lodashGet(props.reports, `${ONYXKEYS.COLLECTION.REPORT}${props.route.params.reportID}`, undefined);
I don't think `lodashGet` is necessary here as `props.reports` and `props.route.params` always exist

2023-08-03 15:58 UTC, situchan approved these changes
LGTM
@pecanoro all yours

2023-08-07 17:31 UTC, pecanoro requested changes
Can you pull main? We just merged this one https://github.com/Expensify/App/pull/24055 and I think we can simply use the reportID instead of having to get the whole report

2023-08-07 17:43 UTC, situchan commented
> I think we can simply use the reportID instead of having to get the whole report

`Task.editTaskAndNavigate` requires whole report as first param.
But agree in `onBackButtonPress` only reportID can be used while fixing conflict.

2023-08-08 02:34 UTC, situchan approved these changes

2023-08-08 12:39 UTC, pecanoro commented
@dukenv0307 @situchan So I tested it again and it's not working when assigning someone to the existing task after closing the new task, I am getting an error in the console as well:

![image](https://github.com/Expensify/App/assets/6474442/1b4cd007-6fa0-44e1-9104-f1da8fb79b52)

2023-08-08 12:51 UTC, situchan commented
I just tested again and no issue for me.
Are you sure that you tested this branch, not main?

2023-08-08 12:57 UTC, pecanoro commented
Hmm, I am on the branch for sure, let me test again

2023-08-08 13:12 UTC, pecanoro commented
Ok, it happens when you assign someone you have never talked to, if you assign someone for which you already have a report, it works fine:


https://github.com/Expensify/App/assets/6474442/6b0ca9ca-6e04-4301-a428-c621382d4f8c

2023-08-08 13:29 UTC, situchan commented
ok, reproduced. Seems like different root cause which also happens on main.

On this line:
https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/libs/actions/Task.js#L422

2023-08-08 14:42 UTC, pecanoro approved these changes
LGTM and it's working well now!

2023-08-08 14:46 UTC, merged

2023-08-08 14:51 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-08-09 09:11 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5806699766) to staging by https://github.com/pecanoro in version: 1.3.52-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|failure ❌
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-08-09 09:50 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5806699766) to staging by https://github.com/pecanoro in version: 1.3.52-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-08-10 20:08 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5825482823) to production by https://github.com/puneetlath in version: 1.3.52-5 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅