feat: task view with offline with feedback
Expensify/App pull request #23705
Opened 2023-07-27 01:47 UTC by allroundexperts

### Details

This PR adds `OfflineWithFeedback` component to the `TaskView` when the title / description or the assignee is changed. This PR does not cover the offline completion of the report.

### Fixed Issues

$ https://github.com/Expensify/App/issues/23200
PROPOSAL: https://github.com/Expensify/App/issues/23200#issuecomment-1642782587

### Tests

1. Go to any Task report
2. Turn off network
3. Update task title/description/assignee
4. Verify that the updated fields are greyed out
5. Turn on the network and verify that fields are not greyed out
6. Turn off the network again and verify that fields are not greyed out

- [x] Verify that no errors appear in the JS console

### Offline tests

N/A

### QA Steps

1. Go to any Task report
2. Turn off network
3. Update task title/description/assignee
4. Verify that the updated fields are greyed out
5. Turn on the network and verify that fields are not greyed out
6. Turn off the network again and verify that fields are not greyed out

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` br [...]

2023-07-27 10:58 UTC, mollfpr commented on src/libs/actions/Task.js
> +                    ...(assigneeAccountID && {managerID: null}),
@allroundexperts Should we reset the `pendingFields` for the failure data too?

2023-07-27 13:09 UTC, mollfpr approved these changes
![g75csv9111x41](https://github.com/Expensify/App/assets/25520267/444b5b03-88d7-4fdb-8490-09dbefa951f5)

LGTM and tests well 🚀

2023-07-27 17:34 UTC, neil-marcellini requested changes
Looking pretty good, but I want to make sure we handle the error case well too. Please feel free to DM me on NewDot if you have questions.

2023-07-27 17:34 UTC, neil-marcellini commented on src/libs/actions/Task.js
> +            },
I think it's better to show the user a RBR error message when editing fails, and to dismiss the pending fields when the error message is dismissed.

Let's remove this and implement that.

2023-07-27 17:34 UTC, neil-marcellini commented on src/components/ReportActionItem/TaskView.js
> +                            <OfflineWithFeedback pendingAction={lodashGet(props, 'report.pendingFields.reportName', null)}>
Let's add pendingFields to the reportPropTypes, like this
https://github.com/Expensify/App/blob/f8bb2b116439ab5210c80eb807a1b843ef37307d/src/pages/settings/Profile/Contacts/NewContactMethodPage.js#L42-L43

2023-07-27 17:34 UTC, neil-marcellini commented on src/components/ReportActionItem/TaskView.js
> +                            <OfflineWithFeedback pendingAction={lodashGet(props, 'report.pendingFields.reportName', null)}>
Also I don't think we need to pass `null` as the default value, since `undefined` is the default and should trigger the default prop to kick in.

2023-07-27 17:34 UTC, neil-marcellini commented on src/components/ReportActionItem/TaskView.js
> -                            <>
Let's wrap the top level view in OfflineWithFeedback and pass to it only the errors prop coming from `report.errorFields.editTask`, and an onClose callback to clear the error message and pendingFields. That way if there's an unexpected error on the back end the user will see an error message which they can dismiss.

I can help test this.

https://github.com/Expensify/App/blob/0965cb31f3fd4ff5534b5bcefa11d974b2dd4c81/src/components/ReportActionItem/TaskView.js#L56-L57

2023-07-28 15:50 UTC, mollfpr commented
@allroundexperts Should the updated field be reverted after dismissing the RBR? I see in your video above the title is not reverted.

2023-07-28 16:15 UTC, mollfpr approved these changes

2023-07-28 21:26 UTC, neil-marcellini commented on src/libs/actions/Task.js
> +function clearEditTaskErrors(report) {
NAB: Let's pass only what we need, which is the reportID.

2023-07-28 21:26 UTC, neil-marcellini commented on src/libs/actions/Task.js
> +            },
Nice thanks. I see that we're reverting the edited fields here too. I though we didn't want to do that, but I was wrong. `editReportComment` does the same so all good 👍

2023-07-28 21:35 UTC, neil-marcellini requested changes
Looking great. The only thing is that I think we should move the error above the line separating the task from the comments. I'll get some design feedback too.

2023-07-28 21:35 UTC, neil-marcellini commented on src/libs/actions/Task.js
> + * Clears any possible stored errors for a specific field on a task report
NAB: More simply; "Clear errors from editing a task".

Actually, we don't need a description at all. It's quite simple.

https://github.com/Expensify/App/blob/a30f5499f1703dfecaa6fd8258b3628c922ffb15/contributingGuides/STYLE.md#L170

2023-07-28 21:38 UTC, neil-marcellini commented
![image](https://github.com/Expensify/App/assets/26260477/c75606a1-ac02-4196-8236-6a0e51eefd79)

I prefer this option for displaying the error that Sibtain showed. @shawnborton do you agree?

2023-07-31 12:18 UTC, shawnborton commented
Works for me!

2023-08-02 14:46 UTC, neil-marcellini requested changes

2023-08-02 14:46 UTC, neil-marcellini commented on src/components/ReportActionItem/TaskView.js
> +                errors={lodashGet(props, 'report.errorFields')}
The current code causes a console error. We need to get the errors from `report.errorFields.editTask`, which is an object of error messages keyed by microtime. For example:
```
Onyx.merge('report_7333847874765172', {
    errorFields: {
        editTask: {
            123423: "Unexpected error",
        },
    },
});
```

2023-08-02 14:50 UTC, neil-marcellini reviewed
Other than that the code looks good

2023-08-03 16:33 UTC, neil-marcellini approved these changes
Looks good!

2023-08-03 16:34 UTC, merged

2023-08-03 16:38 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-08-03 17:40 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5753598018) to staging by https://github.com/neil-marcellini in version: 1.3.50-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-08-04 15:11 UTC, neil-marcellini commented on src/components/ReportActionItem/TaskView.js
> +                            <OfflineWithFeedback pendingAction={lodashGet(props, 'report.pendingFields.reportName', null)}>
Ah yes pendingFields is an object of strings. My bad for missing that. The `errorFields` structure is correct; it's different from `pendingFields`, which is admittedly a bit confusing.

2023-08-07 18:29 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5788505065) to production by https://github.com/puneetlath in version: 1.3.50-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-08-07 18:56 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5788511088) to staging by https://github.com/neil-marcellini in version: 1.3.51-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-08-09 08:45 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/5806686683) to production by https://github.com/Julesssss in version: 1.3.51-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅