Set lineHeight for the report action compose box to 25px
Expensify/App pull request #2511
Opened 2021-04-21 09:01 UTC by jasperhuangg

### Details
For whatever reason, emojis have a line height of 25px, in contrast to the line-height of 20px that plain text has. This means that the check happening [here](https://github.com/Expensify/Expensify.cash/blob/9efcc63e4eb9dd27fac35d7bfc92b3400554be0c/src/components/TextInputFocusable/index.js#L150-L152) thinks that we need two rows to display the emoji when we only actually need 1.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2490

### Tests
Typed emojis into the report action compose box and verified that they displayed in the correct number of rows.

### QA Steps
1. Navigate to any chat
2. Type emojis in the report action compose box. Verify that they display in the correct number of rows, aren't cutoff, and don't have any extra vertical space.

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web
<img width="1792" alt="Screen Shot 2021-04-21 at 4 52 55 PM" src="https://user-images.githubusercontent.com/31285285/115526191-5ea29300-a2c2-11eb-9c5f-70eacd30b569.png">

#### Mobile Web
![simulator_screenshot_8D6C4E11-CB1D-401B-999C-B43F21E8B817](https://user-images.githubusercontent.com/31285285/115526097-4468b500-a2c2-11eb-9caa-ffbaa586dde7.png)

#### Desktop
<img width="1200" alt="Screen Shot 2021-04-21 at 4 56 26 PM" src="https://user-images.githubusercontent.com/31285285/115526368-872a8d00-a2c2-11eb-9f1c-15372634ef6d.png">

#### iOS
![simulator_screenshot_D18875E9-981E-475D-8F2C-A53C99F5F223](https://user-images.githubusercontent.com/31285285/115526509-b0e3b400-a2c2-11eb-81e1-129a249e3f92.png)

#### Android
![Screenshot_1618995607](https://user-images.githubusercontent.com/31285285/115526913-1afc5900-a2c3-11eb-963a-635c8f6c8b3e.png)

2021-04-21 14:29 UTC, shawnborton commented
Hey Jasper - I don't think this is the correct approach for this. Can you show me an example of where we have a large paragraph of text? With this quick fix, we know compromise the text style and we'll have a mismatch between how text appears in the compose box versus how text appears as chat messages. 

I know @stitesExpensify has been working on emoji-related items, and I think with this particular item we should address the emoji line height when we address making them larger as well. I think ideally the emoji objects get wrapped in something that specifically has a lineHeight of 20 so that it balances out with the rest of the text.

2021-04-22 02:43 UTC, jasperhuangg commented
@shawnborton Looks like you're absolutely correct that there is a mismatch between the comments and the compose box, thanks for catching this! Do you mind linking the issue that @stitesExpensify is working on?

<img width="1792" alt="Screen Shot 2021-04-22 at 10 12 35 AM" src="https://user-images.githubusercontent.com/31285285/115645982-ebe1f800-a353-11eb-9bdc-dcbc3075d8a5.png">

> I think ideally the emoji objects get wrapped in something that specifically has a lineHeight of 20 so that it balances out with the rest of the text.

Although I agree this is the correct way to move forward with things, one problem is that our current implementation of the report action compose box uses a `textarea` internally. This means that we won't be able to render JSX inside of it. One option is to change up the implementation of the report action compose box to use a [content-editable div](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content), which functions the same as a `textarea`. The problem is, these aren't supported natively in React Native (only on React web), meaning we'll have either have to find a third-party implementation of one or write one up ourselves (which shouldn't be very difficult at all). 

Personally, I think this is a valuable thing to spend time on in case we want to implement things like real-time markdown rendering and other special inline elements that wouldn't otherwise be possible with a plain `textarea`. What are your thoughts?

2021-04-22 18:02 UTC, stitesExpensify commented
So this is something I've been looking into for the comments themselves, but not inside of the compose bar. I agree with you that it's definitely something worth spending time on and investigating given that we will probably want a bunch of live markdown in the future.

That said I don't think that using `content-editable div` is the way to go, we will definitely want a natively supported React Native component

2021-04-23 01:23 UTC, jasperhuangg commented
> That said I don't think that using `content-editable div` is the way to go, we will definitely want a natively supported React Native component

After doing a good amount of research it doesn't seem like there are any React Native `TextInputs` (and any React Native community libraries) that support rendering JSX and HTML inside of them. Besides using the `WebView`, we'd have to develop our own content editable div natively, which poses a number of challenges but could potentially be cool to open source (since one doesn't seem to exist). What are your thoughts, and would you potentially be down to work on something like this in the near future?

@stitesExpensify

2021-04-23 19:20 UTC, NikkiWines commented
Looks like there's still some discussion going on here - I'm gonna be OOO for some of next week so gonna let @stitesExpensify take over reviewing this. If it's not merged when I'm back I'm happy to review!

2021-04-27 01:39 UTC, roryabraham requested changes
I think you'll also want to apply this `lineHeight` style [in here](https://github.com/Expensify/Expensify.cash/blob/957815e5539a76de62da4568a6727d7f8c956467/src/components/Text.js#L53) as well 🙂 ... That way the issue will be fixed both in the compose box and in the report history.

2021-04-27 01:54 UTC, shawnborton approved these changes

2021-04-28 04:48 UTC, jasperhuangg commented
@roryabraham Good catch! I just checked the link you sent me and it seems like `lineHeight: 20` is already being applied there. If it looks good to you then I should be ready for another review, thanks!

2021-04-28 14:24 UTC, TomatoToaster approved these changes

2021-04-28 20:44 UTC, roryabraham approved these changes

2021-04-28 20:44 UTC, merged

2021-04-28 20:45 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-04-29 03:36 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/794727234) to staging in version: 1.0.33-1🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-05-08 01:43 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/822089210) to production in version: 1.0.39-5🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅