Add instruction on setting up Mapbox credentials
Expensify/App pull request #25454
Opened 2023-08-18 03:45 UTC by hayata-suenaga

### Details

We added a new library that uses native iOS and Android Mapbox SDKs. Mapbox is the service that offers, well, maps along with other map-related services. One caveat of using their SDKs is that they're closed-sourced, and you need a token to download them.

We created scripts `setup-mapbox-sdks` and `setup-mapbox-sdks-walkthrough` for streamline the process of obtaining the token and saving the token in the local environment. These scripts are invoked when running `npm run configure-mapbox`.

However, this script might not work for everyone, especially those developing on Windows computers. This PR adds instructions on manually obtaining and saving tokens.

### Fixed Issues

$ https://github.com/Expensify/App/issues/25452
PROPOSAL: N/A

### Test

This is a change in a documentation. No test or QA is needed.

2023-08-18 13:14 UTC, abdulrahuman5196 commented
@hayata-suenaga I have been assigned the auto C+ here? What should we do as C+ here?

2023-08-18 13:16 UTC, allroundexperts approved these changes

2023-08-18 18:00 UTC, neil-marcellini requested changes
Look thanks, some small things

2023-08-18 18:01 UTC, neil-marcellini commented
Also merge conflicts

2023-08-18 20:00 UTC, hayata-suenaga commented on README.md
> +* Before installing iOS dependencies, make sure that you have setup Mapbox SDK credentials. Please refer to [Setting up Mapbox SDK Credentials](#setting-up-mapbox-sdk-credentials).
thank you for thorough review 🙇

2023-08-18 20:01 UTC, hayata-suenaga commented on README.md
> +* Before installing iOS dependencies, make sure that you have setup Mapbox SDK credentials. Please refer to [Setting up Mapbox SDK Credentials](#setting-up-mapbox-sdk-credentials).
I changed iOS -> CocoaPods and Android -> Gradle

2023-08-18 22:16 UTC, deetergp submitted a review, later dismissed

2023-08-18 22:18 UTC, deetergp commented
You've got more conflicts, I'm afraid.

2023-08-20 21:32 UTC, hayata-suenaga commented
I have to change the instruction in README because of this [issue](https://github.com/Expensify/Expensify/issues/309451). I added HOLD so that this PR cannot be merged.

2023-10-06 12:44 UTC, abdulrahuman5196 commented
@hayata-suenaga Is this PR still needed?

2023-10-06 13:10 UTC, hayata-suenaga commented
yes this PR is still needed but we're holding this issue until the end of this month as this touches a build system (and there are new features merged evertyday until a big conference at the end of this month

2023-10-06 13:25 UTC, abdulrahuman5196 commented
Thank you for confirming. I am just checking through my K2 for pending items.

2023-11-01 00:37 UTC, hayata-suenaga commented
Closing the PR as we're not deploying Mapbox script PR

2023-11-01 00:37 UTC, closed without merging