Try naming VERSION to something else to not conflict
Expensify/App pull request #2558
Opened 2021-04-23 17:34 UTC by AndrewGable

### Details
Trying to fix a broken workflow, I think having an `env` variable named `VERSION` and a `with:` variable named `VERSION` might be causing this issue, but this is a guess.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2557

### Tests
1. Merge this PR
2. Verify that a version is included in the deploy message when it goes out

2021-04-23 17:47 UTC, roryabraham requested changes
Update the input in `markPullRequestsAsDeployed/action.yml` too?

2021-04-23 17:51 UTC, AndrewGable commented
Ah yes, I forgot, good call.

2021-04-23 17:58 UTC, roryabraham approved these changes
Okay, let's do this thang.

2021-04-23 17:58 UTC, merged

2021-05-08 01:43 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/822089210) to production in version: 1.0.39-5🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅