Add IOU Menu Options
Expensify/App pull request #2612
Opened 2021-04-28 17:46 UTC by marcaaron

### Details
cc @Julesssss @iwiznia adds the menu options behind beta

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/161984

### Tests
### QA Steps
1. Login and tap the FAB menu +
2. Verify that the two new options appear
<img width="379" alt="Screen Shot 2021-04-28 at 7 43 35 AM" src="https://user-images.githubusercontent.com/32969087/116449146-91361980-a7f5-11eb-9ee6-94e0603495ce.png">
3. Verify that clicking each one will bring you to the associated view
4. Select a chat with a single participant
5. Tap the `+` menu next to the comment compose area
6. Verify there is an option to `Request Money`
7. Tap and verify the request money screen appears and the participant is already selected
8. Select a chat with multiple participants
9. Tap the `+` menu next to the comment compose area
10. Verify there is an option to `Split Bill`
11. Tap and verify the split bill screen appears and all participants are already selected on the next screen

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-04-28 17:47 UTC, marcaaron commented
Will add screenshots and test on all platforms in a bit but wanted to get this into review sooner than later.

2021-04-28 20:50 UTC, francoisl commented
Code looks good but when I create a split bill from a convo with multiple people and click the `Split Bill` option, the panel doesn't populate with anything other than the currency, and the Next button is disabled. Nothing in the JS console or logs, any idea?

<img src="https://user-images.githubusercontent.com/2229301/116470748-ad9f7980-a828-11eb-9b81-62d81d49f801.png" width="200" />

2021-04-28 21:05 UTC, marcaaron commented
>Code looks good but when I create a split bill from a convo with multiple people and click the Split Bill option, the panel doesn't populate with anything other than the currency, and the Next button is disabled. Nothing in the JS console or logs, any idea?

This PR shouldn't really have any effects on the way things are working there. But I think if you click to the right of the USD then you can enter a number and should be able to "Next" after that. I found this a little confusing myself as the view doesn't really look like an input of any kind so it's unclear what we can do on desktop.

2021-04-28 21:25 UTC, francoisl commented
Oh derp, got it... I was expecting the view would directly show the bill participants.

2021-04-28 21:25 UTC, francoisl approved these changes, later dismissed

2021-04-29 11:32 UTC, Julesssss commented on src/pages/home/report/ReportActionCompose.js
> +                                                    ] : []),
Interesting way to add additional items without needing logic defined outside of the prop. Nice!

2021-04-29 11:42 UTC, Julesssss requested changes
The issue tests well. 

One request, would you mind removing the other 'Hiding menu options'[ comment here](https://github.com/Expensify/Expensify.cash/blob/72a113f89265e8873a4ece0cf6a46e3a96d43a07/src/pages/home/report/ReportActionCompose.js#L370-L380), as this PR makes it irrelevant. 

Also, could you add a test case for confirming that the IOU beta flag is working as expected in the description? (I was able to test this locally by removing the `all` beta flag, but for QA we should probably use accounts with/without the flag to verify)

2021-04-29 17:54 UTC, marcaaron commented
Thanks for spotting that @Julesssss! I have made that requested change and added a test step to verify the new options do not appear for non beta users.

2021-04-29 18:12 UTC, francoisl approved these changes

2021-04-29 18:28 UTC, trjExpensify commented
Are we good to go here without @Julesssss re-review so we can get testing, as I think he's out for the evening now?

2021-04-29 18:35 UTC, Julesssss approved these changes
Yeah, this change will not invalidate the tests I ran earlier. Merging

2021-04-29 18:40 UTC, Julesssss commented
I can't find the merge button on the GitHub app, but we're good to go. Feel free to merge

2021-04-29 18:45 UTC, merged

2021-04-29 18:46 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-04-29 23:55 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/797771259) to staging in version: 1.0.34-1🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅