feat(26270): Add Skeleton UI for Money Requests
Expensify/App pull request #26613
Opened 2023-09-03 18:25 UTC by mananjadhav

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/26270
PROPOSAL: 

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` step [...]

2023-09-03 19:01 UTC, hayata-suenaga commented
@mananjadhav Is it possible that you can push the rest of the changes soon? I think we want to fix this as soon as possible 🙇 (i.e. we want to deploy this to production)

2023-09-03 19:03 UTC, mananjadhav commented
I am just working on the checklist.

2023-09-03 19:32 UTC, mananjadhav commented
@hayata-suenaga @mountiny @shawnborton @fedirjh The PR is ready.

2023-09-03 19:37 UTC, parasharrajat requested changes

2023-09-03 19:37 UTC, mountiny commented
niiice, videos looking good!

2023-09-03 19:45 UTC, mananjadhav commented on src/components/MoneyRequestSkeletonView.js
> +    shouldAnimate: PropTypes.bool,
Don't need any of these props.

2023-09-03 19:47 UTC, mananjadhav commented
@parasharrajat I've fixed the comments. Should've raised a PR fresh in the morning to avoid silly changes. Thanks for catching those.

2023-09-03 19:47 UTC, mananjadhav commented on src/components/ReportActionItem/MoneyRequestPreview.js
>  import _ from 'underscore';
Fixed.

2023-09-03 19:47 UTC, mananjadhav commented on src/components/MoneyRequestSkeletonView.js
> +                width={styles.w100.width}
I had issues with the skeleton UI overflowing, but I fixed with fixed values. Can be removed.

2023-09-03 19:47 UTC, mananjadhav commented on src/components/MoneyRequestSkeletonView.js
> +export default compose(withWindowDimensions, withLocalize)(MoneyRequestSkeletonView);
Removed.

2023-09-03 19:48 UTC, mananjadhav commented on src/components/MoneyRequestSkeletonView.js
> +MoneyRequestSkeletonView.displayName = 'IOUSkeletonView';
yeah missed this one.

2023-09-03 19:48 UTC, mananjadhav commented on src/components/MoneyRequestSkeletonView.js
> +    shouldAnimate: PropTypes.bool,
Removed all the props.

2023-09-03 20:31 UTC, mananjadhav commented
@parasharrajat I've updated the description so that `Web` attachments show up.

> We can work on it in the IST zone in the morning to if there are more requests.

Sure that'll be great!

2023-09-04 02:21 UTC, mananjadhav commented
Yeah I thought so too. I am only replacing with the skeleton view, the behavior exists for other wise IOU requests too. I don't have the message context too that I can replace the message with any other skeleton view.


https://github.com/Expensify/App/assets/3069065/125e76d2-4bba-4f12-ace6-ee0b1f2af881

2023-09-04 05:24 UTC, mountiny commented
Yeah I think the last thing is fine

2023-09-04 07:17 UTC, mananjadhav commented
I thought earlier it was DistanceRequest. But then I also couldn’t figure out how and when it is rendered? 

I had DMed @hayata-suenaga too for distance request.

2023-09-04 08:04 UTC, rezkiy37 commented
Hi, guys! I was invited by Vit to test the PR as well 🙂

2023-09-04 08:44 UTC, mountiny commented
@parasharrajat what slack thread exactly, are you still waiting on some information confirmation?

2023-09-04 09:21 UTC, mananjadhav commented on src/components/MoneyRequestSkeletonView.js
> +                    x="15"
@rezkiy37 Good eye. Corrected.

2023-09-04 10:24 UTC, rezkiy37 commented
> I didn't understand the issue. What is the problem here?

Take a look at the entire message background color and money request background. They are the same, no contrast.

<img width="759" alt="Screenshot 2023-09-04 at 12 24 02" src="https://github.com/Expensify/App/assets/57314631/d34f0c55-664f-4772-bffc-e168c67419fb">

2023-09-04 10:59 UTC, mountiny commented
@rezkiy37 good find, Manan is now afk but he will be back in an hour. Could you make a suggestion in code which should fix it to make his work faster once he comes back?

I think that in whisper it should look like when hovered and when hovered, no style change as we had in another case

2023-09-04 12:32 UTC, shawnborton commented
I reported some design weirdness not related to the skeleton [here](https://expensify.slack.com/archives/C057F53HR40/p1693830657441109).

In terms of the skeleton itself, can we make sure it has the same pulsing effect as other skeleton loaders throughout the app too? 

Also just cc @dannymcclain on this issue since I think he worked on the mockups :)

2023-09-04 13:17 UTC, mananjadhav commented on src/components/ReportActionItem/MoneyRequestPreview.js
> -                    <View style={styles.moneyRequestPreviewBoxText}>
No nothing is changed. Why?

2023-09-04 13:30 UTC, mountiny commented
@parasharrajat @mananjadhav on eis the same with the whisper

the other one is the bacground colour border
<img width="891" alt="image" src="https://github.com/Expensify/App/assets/36083550/c9b7bd89-d343-4ba7-abd1-675d1ce34281">

2023-09-04 13:32 UTC, mananjadhav commented
The shimmer (pulsing) effect is showing when I add a certain width to it.

https://github.com/Expensify/App/assets/3069065/12889e86-e4f6-4e55-94dc-ed318df989f1

2023-09-04 13:32 UTC, rezkiy37 commented
> @rezkiy37 good find, Manan is now afk but he will be back in an hour. Could you make a suggestion in code which should fix it to make his work faster once he comes back?
> 
> I think that in whisper it should look like when hovered and when hovered, no style change as we had in another case

That's the commit how I fixed it - https://github.com/Expensify/App/pull/26603/commits/8bcad7cde66b3e074ec3d2189d8eba891ccf7b64.

2023-09-04 13:34 UTC, mountiny commented
Lets address those and the whisper hover and we can ship it

2023-09-04 14:04 UTC, rezkiy37 commented
> @rezkiy37 Thanks for reporting the issue, but for some reason I am not able to reproduce this issue at my end. Can you tell me the reproduction steps?
> 
>  web-whisper-hover-style.mov

Yeah, I see. Let try one more time, maybe someone has fixed it right now 😅

2023-09-04 14:06 UTC, rezkiy37 commented
Hah, I was fixed in another [PR](https://github.com/Expensify/App/pull/26603) that was merged 3 hours ago. No bug anymore 🙂

2023-09-04 14:08 UTC, mountiny commented
`vit-26503theft` to the rescue

2023-09-04 14:12 UTC, mananjadhav commented
@mountiny @parasharrajat @rezkiy37 do we have any more outstanding comments?

2023-09-04 14:13 UTC, rezkiy37 commented
> @mountiny @parasharrajat @rezkiy37 do we have any more outstanding comments?

From my side, LGTM!

2023-09-04 14:14 UTC, rezkiy37 approved these changes

2023-09-04 15:15 UTC, parasharrajat approved these changes
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.


:ribbon: :eyes: :ribbon:  C+ reviewed

2023-09-04 15:22 UTC, mountiny approved these changes
Thanks for all the hard work!

2023-09-04 15:42 UTC, merged

2023-09-04 15:51 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-09-04 16:49 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6075679511) to staging by https://github.com/mountiny in version: 1.3.63-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-09-05 18:41 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6088410008) to production by https://github.com/mountiny in version: 1.3.63-2 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-09-05 19:12 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6088420139) to staging by https://github.com/mountiny in version: 1.3.64-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-09-06 18:54 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6101008907) to production by https://github.com/mountiny in version: 1.3.64-2 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-11-29 06:26 UTC, rushatgabhane commented on src/components/ReportActionItem/MoneyRequestPreview.js
> +                                                additionalStyles={[styles.mr1, styles.ml1]}
Coming from [Dot separator in the report preview component appears bottom aligned](https://github.com/Expensify/App/issues/29543#top)
#29543

`styles.mb1` isn't passed to `Icon`.