Resync data when the app reconnects
Expensify/App pull request #275
Opened 2020-08-20 21:56 UTC by tgolen

Fixes https://github.com/Expensify/ReactNativeChat/issues/253

# Tests
1. Load the app
1. Go offline (either turn off wifi or set the browser to offline mode)
1. Post a comment
1. In another browser, go to expensify.com and go to the same report that is open for the chat just commented on
1. Post a comment on the report page
1. Now switch back to the chat app and turn it back to online mode
1. Verify that you see the comment from `5` show up

2020-08-20 22:33 UTC, marcaaron requested changes
I just thought of something and I'd like to get your thoughts before we commit to this solution. We don't really need to add a "connect" listener to `Network` or an extra `callback` property to the `Ion` mapping because:

1. There is only one situation where we must refetch keys (`isOffline` going from `false` > `true`)
1. Ion already knows when we are going online or offline because it is responsible for watching these changes.
1. We should just tell `Ion` which actions it needs to fetch and have `Network` only worry about updating `isOffline`.

2020-08-21 00:30 UTC, cead22 requested changes

2020-08-21 01:46 UTC, marcaaron submitted a review, later dismissed
LGTM but I can't actually get these test steps to work because when I go offline in Chrome Dev Tools web sockets still work 🤣

2020-08-21 16:16 UTC, marcaaron approved these changes
Looks great to me!

2020-08-24 15:58 UTC, cead22 approved these changes

2020-08-24 15:59 UTC, merged