Add ability to get the current operating system, display subset of emojis if on Windows
Expensify/App pull request #2787
Opened 2021-05-11 07:04 UTC by jasperhuangg

### Details
Windows doesn't support flag emojis (and just displays country codes instead), so let's prevent those emojis from displaying in the emoji picker if we're on Windows.

To do this, I added a function `getOperatingSystem` that reads the current operating system.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2761

### Tests
For the `getOperatingSystem` function, I logged its results for all operating systems and verified that they were correct.

I then verified that flag emojis don't appear in the emoji picker on Windows.

### QA Steps
1. On a Windows laptop, sign in, and navigate to any chat.
2. Open the emoji picker. Scroll down to the bottom and verify that there is no "Flags" category.

### Tested On

- [x] Web

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-05-11 18:53 UTC, stitesExpensify approved these changes
Looks great, thanks!

2021-05-11 18:56 UTC, stitesExpensify requested changes
Changing my review until we chat about splitting the lib

2021-05-12 05:03 UTC, jasperhuangg commented on src/libs/getOperatingSystem.js
> +    // When running on a native device
That's a great point, I'll work on that 👍👍

2021-05-12 05:05 UTC, jasperhuangg commented on src/libs/getOperatingSystem.js
> +    // When running on a native device
I think that's a great idea. Looks like we're doing that for other library functions like `openURLInNewTab` or `fileDownload`, so I think this should be the same 👍

2021-05-12 05:18 UTC, jasperhuangg commented
@stitesExpensify Replied your comment, I decided it's better to split it into two files to keep things more consistent with other library functions that have web and native counterparts. We should be good for another review!

2021-05-12 22:56 UTC, stitesExpensify approved these changes
Thanks for making those changes, looks great!

2021-05-12 22:56 UTC, merged

2021-05-12 23:29 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/837140536) to staging in version: 1.0.42-8🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-05-13 01:54 UTC, isagoico commented
![image](https://user-images.githubusercontent.com/44479856/118066382-a0c46f00-b36c-11eb-8ed2-fd386228cb3c.png)

It's a pass! no flag category.

2021-05-13 16:07 UTC, marcaaron commented on src/libs/getOperatingSystem/index.native.js
> +    switch (Platform.OS) {
We usually split stuff like this into an `index.android.js` and `index.ios.js` files instead of use `Platform` + `index.native.js`.

2021-05-13 16:07 UTC, marcaaron commented on src/libs/getOperatingSystem/index.js
> +    const iosPlatforms = ['iPhone', 'iPad', 'iPod'];
NAB, if we only needed to know that we're on windows we could have created an `isUsingWindows` helper instead.

2021-05-13 23:05 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/840432904) to production in version: 1.0.44-0🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅