feat: arrow navigation in context menu
Expensify/App pull request #27877
Opened 2023-09-20 18:07 UTC by samh-nl

### Details

Navigating the report actions context menu with arrows was not previously possible.

### Fixed Issues

$ https://github.com/Expensify/App/issues/23280
PROPOSAL: https://github.com/Expensify/App/issues/23280#issuecomment-1644162724

### Tests

**Web/desktop**
1. Go to any report that has a message
2. Right-click the message
3. Verify the context menu opens
4. Press the down arrow once
5. Verify the first menu item ('Reply in thread') is selected
6. Verify that you can navigate through the entire menu by pressing the up and down arrows
7. Use the arrows to go to the first menu item
8. Press Enter
9. Verify the page navigates to a thread and the context menu closes

**Mobile**
1. Go to any report that has a message
2. Long-press the message
3. Verify that the context menu opens

- [X] Verify that no errors appear in the JS console

### Offline tests

**Web/desktop**
1. Go to any report that has a message
2. Right-click the message
3. Verify the context menu opens
4. Press the down arrow once
5. Verify the first menu item ('Reply in thread') is selected
6. Verify that you can navigate through the entire menu by pressing the up and down arrows
7. Use the arrows to go to the first menu item
8. Press Enter
9. Verify the page navigates to a thread and the context menu closes

**Mobile**
1. Go to any report that has a message
2. Long-press the message
3. Verify that the context menu opens

### QA Steps

**Web/desktop**
1. Go to any report that has a message
2. Right-click the message
3. Verify the context menu opens
4. Press the down arrow once
5. Verify the first menu item ('Reply in thread') is selected
6. Verify that you can navigate through the entire menu by pressing the up and down arrows
7. Use the arrows to go to the first menu item
8. Press Enter
9. Verify the page navigates to a thread and the context menu closes

**Mobile**
1. Go to any report that has a message
2. Long-press the message
3. Verify that the context menu opens

- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpo [...]

2023-09-21 12:28 UTC, situchan commented on src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js
> +                {_.map(_.filter(ContextMenuActions, shouldShowFilter), (contextAction, index) => {
```suggestion
                {_.map(filteredContextMenuActions, (contextAction, index) => {
```

2023-09-21 12:28 UTC, situchan commented on src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js
> +    const menuItemRefs = useRef([]);
```suggestion
    const menuItemRefs = useRef({});
```

2023-09-21 13:08 UTC, situchan commented
Also, please pull main

2023-09-21 13:19 UTC, situchan commented
unit test failing

Also, found the case of arrows not working on LHN context menu while focusing on composer

https://github.com/Expensify/App/assets/108292595/b12a1b0f-2458-41b0-8fa0-bfe29a391185

2023-09-21 14:14 UTC, situchan commented
I was about to say it's out of scope. There's already GH to blur composer when any popover is open - #25485

2023-09-21 14:15 UTC, situchan commented
Please investigate why unit test is failing

2023-09-21 14:27 UTC, situchan reviewed
triggering actions

2023-09-21 14:28 UTC, situchan commented
@samh-nl please revert full code and see it still happens

2023-09-21 14:51 UTC, situchan commented
yes, let's try. Hope that "luck" won't happen

2023-09-21 15:24 UTC, situchan commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>


https://github.com/Expensify/App/assets/108292595/dbbcd926-cd0b-4577-8131-c8bb591d274c



</details>

<details>
<summary>Mobile Web - Chrome</summary>



</details>

<details>
<summary>Mobile Web - Safari</summary>


https://github.com/Expensify/App/assets/108292595/0f97bb3e-282b-4acc-bf0d-a06a8bbeecd0



</details>

<details>
<summary>Desktop</summary>


https://github.com/Expensify/App/assets/108292595/cd70ec00-60c7-41dd-b8fe-d7556306b77e



</details>

<details>
<summary>iOS [...]

2023-09-21 21:14 UTC, situchan commented
ok, that looks good. Thanks for the research

2023-09-22 00:16 UTC, situchan approved these changes
:shipit: 

@francoisl all yours

2023-09-22 00:38 UTC, francoisl requested changes
LGTM, minor small change request

2023-09-22 00:38 UTC, francoisl commented on src/components/ContextMenuItem.js
> +    focused: PropTypes.bool,
Let's rename this to `isFocused` for consistency, since it's a boolean

```suggestion
    isFocused: PropTypes.bool,
```

2023-09-22 00:41 UTC, situchan commented on src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js
> +                            focused={focusedIndex === index}
I also thought `isFocused` name is better but didn't request change because `focused` prop name already exists here 😄

2023-09-22 00:42 UTC, situchan commented on src/components/ContextMenuItem.js
> +            focused={focused}
Same here

2023-09-22 00:43 UTC, situchan commented on src/components/ContextMenuItem.js
> +            focused={focused}
I also thought `isFocused` name is better but didn't request change because `focused` prop name already exists here 😄

2023-09-22 07:22 UTC, situchan commented on src/components/ContextMenuItem.js
> +            focused={focused}
I think that's fine as we didn't touch `MenuItem` component here.
If anyone is adding/changing props on that component in the future, they might be responsible.
cc: @francoisl

2023-09-22 08:37 UTC, francoisl approved these changes
👍

2023-09-22 08:40 UTC, merged

2023-09-22 08:46 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-09-22 08:54 UTC, situchan commented
There's 2 hrs delay from bonus timeline but it would be much appreciated if it's still eligible unless any regression found.
The delay was just from minor prop name change and @samh-nl was sleeping at that moment.
cc: @francoisl

2023-09-22 13:58 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6274759566) to staging by https://github.com/francoisl in version: 1.3.73-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-09-25 09:33 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6297348186) to production by https://github.com/mountiny in version: 1.3.73-1 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅

2023-09-25 10:05 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6297355879) to staging by https://github.com/francoisl in version: 1.3.74-0 🚀

platform | result
---|---
🤖 android 🤖|failure ❌
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-09-28 18:47 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6342870850) to production by https://github.com/chiragsalian in version: 1.3.74-3 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅