Rory functional composition
Expensify/App pull request #281
Opened 2020-08-21 17:44 UTC by roryabraham

@tgolen @AndrewGable @marcaaron Would you please review this?

### Details

- Refactor to use functional composition when dealing with multiple HOCs
- Also, rename `WithIon` -> `withIon`, to follow naming convention for HOCs

### Fixes
$ https://github.com/Expensify/ReactNativeChat/issues/279

2020-08-21 17:56 UTC, marcaaron submitted a review, later dismissed
Seems like a pretty reasonable change to me.

2020-08-21 21:03 UTC, tgolen requested changes
Cool, this is nice! Thanks

2020-08-26 17:28 UTC, tgolen requested changes

2020-08-26 19:07 UTC, tgolen approved these changes

2020-08-26 19:07 UTC, merged