Add a chat switcher to the LHN
Expensify/App pull request #282
Opened 2020-08-21 21:14 UTC by tgolen

Fixes https://github.com/Expensify/ReactNativeChat/issues/269

- Refactors the sidebar component to break it up into smaller and more focused pieces
- Adds a chat switcher
- Adds a Command+K keyboard shortcut to access the chat switcher

# Tests
1. Press Command+K and verify the chat switcher gets focused
1. Begin typing names or emails and see the list of people appear
1. Use the arrow keys to highlight different options
1. Press the enter key to select an option (or click on an option)

### Things left to do
- [ ] style it (@shawnborton )
- [ ] hook up a method to get the reportID and redirect the user to that report

2020-08-21 23:41 UTC, marcaaron reviewed
Looks good so far! Just left some initial comments mostly around the `ChatSwitcher` which I'm guessing has some copy/paste stuff going on

2020-08-24 04:42 UTC, roryabraham requested changes
High-level, I have three main comments here:

- It's not compatible with desktop, but fixing those issues to get React Native to play nice with Electron might be challenging, and probably warrants its own issue/PR. That being said, I do think it's doable: there's an [early-stage npm project](https://www.npmjs.com/package/react-native-electron) addressing some of the challenging pieces, such as hotkeys, links, dialogs/alerts, and clipboard. While it doesn't offer stability yet, it's [open-source](https://github.com/PaulLeCam/react-native-electron#readme) I'm sure the developer would welcome PR's. If we don't like that idea, maybe we could also just work-around it by having separate files when we need to use some Electron-specific code for desktop (i.e: `index.desktop.js`)
- Beyond the actual functionality, the download links need to detect the current platform to show the other three.
- There were a handful of instances where you used underscore functions for which there is a native-javascript equivalent, and I think it might be best to stick with plain JS whenever convenient. In some cases I think it's more performant too, i.e: not extending an object with all the underscore methods like `_(myObject)`, just to use one function.

2020-08-24 20:31 UTC, roryabraham requested changes
- Let's actually rename the custom PropTypes object to `SafeAreaInsetPropTypes`, just so it's clear we're talking about the safe area edges on the side of a phone, and not some internal padding or something.
- Also, this really isn't specific to the sidebar module, and could conceivably be used anywhere in the app, so I would suggest moving it to `src/types/SafeAreaInsetPropTypes.js`. Or maybe it would only conceivably be used at the page level, so it could be in `src/page/SafeAreaInsetPropTypes.js`

2020-08-26 19:21 UTC, marcaaron requested changes
Ok looking good I had a few unresolved comments that were not addressed and a handful of new comments that are not major blocker.

2020-08-26 20:39 UTC, roryabraham approved these changes
Looks great, just the one PropTypes concern!

2020-08-26 20:40 UTC, roryabraham requested changes
oops, meant to request the small typechecking change

2020-08-26 21:20 UTC, roryabraham submitted a review, later dismissed
Changing to NAB

2020-08-27 22:37 UTC, marcaaron approved these changes

2020-08-27 22:38 UTC, merged