Activate draft Icon for active report
Expensify/App pull request #2823
Opened 2021-05-12 16:56 UTC by parasharrajat

Please review

### Details

### Fixed Issues

Fixes #2807

### Tests / QA Steps

  1. Select a chat
  2. Begin writing a comment
  3. Look at the LHN and there ~won't~ should be a pencil icon
  4. Switch to another chat
  5. Look at the LHN and you'll see the pencil icon for the previous chat you were in

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

https://user-images.githubusercontent.com/24370807/118014636-0d416d00-b371-11eb-9026-37cdef5a7a97.mp4

Its a minor change that will reflect on all platforms.

2021-05-12 21:18 UTC, NikkiWines reviewed
Code looks good, could we please get screenshots/videos across all platforms? Thanks

cc: @Julesssss since you approved the proposal

2021-05-13 09:37 UTC, Julesssss approved these changes

2021-05-13 09:57 UTC, Julesssss commented
Still missing screenshots, please add them next time.

2021-05-13 10:00 UTC, Julesssss requested changes
It tested well for me on each platform except mobile Web (iOS 12).

Notice that the icon will not display when leaving a chat, it is only when you tap into a chat again that the icon updates.


https://user-images.githubusercontent.com/10736861/118112378-d608a580-b3dc-11eb-9ce9-36a64b8b377c.mov

2021-05-13 10:05 UTC, parasharrajat commented
@Julesssss Let me check that part. I sure that is the default implementation.

2021-05-13 17:42 UTC, parasharrajat commented
@Julesssss I was going to upload all videos after some time. 

> It tested well for me on each platform except mobile Web (iOS 12).

I am not facing any issues. I tested it on both IOS-web and android-web but it works fine (Video linked in description). Also, most importantly it can either work on all or none.

2021-05-14 11:21 UTC, Julesssss approved these changes
Tested again and this time around it worked as expected, not sure what happened yesterday 🤷‍♂️

> Also, most importantly it can either work on all or none.

Yeah, it seemed like a separate issue if anything -- but it was worth raising anyway.

2021-05-14 16:08 UTC, parasharrajat commented
@NikkiWines All yours and screens updated. Thanks.

2021-05-14 17:24 UTC, NikkiWines approved these changes
Looks good 👍

2021-05-14 17:24 UTC, merged

2021-05-14 17:25 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-05-14 23:55 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/843695847) to staging in version: 1.0.46-1🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅