fix: ignore other actions if navigation in progress in menu Items
Expensify/App pull request #28338
Opened 2023-09-27 18:07 UTC by ishpaul777

…ting options

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/27384
PROPOSAL: https://github.com/Expensify/App/issues/27384#issuecomment-1718121484

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I t [...]

2023-10-10 16:38 UTC, robertKozik commented on src/pages/settings/InitialSettingsPage.js
> +                            onPress={singleExecution(openProfileSettings)}
Great, thanks for fixing that

2023-10-10 16:39 UTC, robertKozik commented on src/pages/workspace/WorkspaceInitialPage.js
>                                      />
OK, got it. Please add the comment why you didn't use the `MenuItemList.js`

2023-10-10 16:47 UTC, robertKozik requested changes
The diff is really messy due to import shuffle from your commits - please do something with it. Apart from that few suggestions, mainly use `useMemo` for option mappings

2023-10-10 16:47 UTC, robertKozik commented on src/pages/settings/InitialSettingsPage.js
>  import * as ReimbursementAccountProps from '../ReimbursementAccount/reimbursementAccountPropTypes';
Why every file has the imports shuffled after your commits?

2023-10-10 16:47 UTC, robertKozik commented on src/components/MenuItemList.js
> +                    key={menuItemProps.key || menuItemProps.title}
Why we are adding `menuItemProps.key` ? Isn't `menuItemProps.title` sufficient?

2023-10-10 16:47 UTC, robertKozik commented on src/pages/settings/AboutPage/AboutPage.js
> +                                }))}
Move `menuItems` mapping to separate `useMemo` variable. There is no need to recalculate it every rerender

2023-10-10 16:47 UTC, robertKozik commented on src/pages/settings/AboutPage/AboutPage.js
> +    isShortcutsModalOpen: false,
Why we need `isShortcutsModalOpen`? It wasn't the part of the proposal

2023-10-10 16:47 UTC, robertKozik commented on src/pages/settings/InitialSettingsPage.js
> +                        onPress={singleExecution(openProfileSettings)}
its OK 👌🏼

2023-10-10 16:47 UTC, robertKozik commented on src/pages/settings/Security/SecuritySettingsPage.js
> +                        }))}
Same as above - move to memo

2023-10-10 20:12 UTC, robertKozik commented
I'm OOO for today - will review early tomorrow

2023-10-17 10:45 UTC, robertKozik requested changes
The last one I think. You've removed passing onyx state about the modal, but there is still used inside the memo. I'll start filling reviewer checklist

2023-10-17 10:45 UTC, robertKozik commented on src/pages/settings/AboutPage/AboutPage.js
> +    const {translate, isShortcutsModalOpen} = props;
We got rid of the `isShortcutsModalOpen` as per [your comment](https://github.com/Expensify/App/pull/28338#discussion_r1357458217). Can we remove this leftover?

2023-10-17 10:45 UTC, robertKozik commented on src/pages/settings/AboutPage/AboutPage.js
> +            disabled: isShortcutsModalOpen,
here as well
```suggestion
```

2023-10-17 10:45 UTC, robertKozik commented on src/pages/settings/AboutPage/AboutPage.js
> +    }, [isShortcutsModalOpen, translate, waitForNavigate]);
And here
```suggestion
    }, [translate, waitForNavigate]);
```

2023-10-17 10:46 UTC, robertKozik commented
Also could you fill in your (authors) checklist, provide test steps and resolve conflicts @ishpaul777 ?

2023-10-17 14:11 UTC, robertKozik commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [X] I verified the correct issue is linked in the `### Fixed Issues` section above
- [X] I verified testing steps are clear and they cover the changes made in this PR
    - [X] I verified the steps for local testing are in the `Tests` section
    - [X] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [X] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [X] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I verified tests pass on **all platforms** & I tested again on:
    - [X] Android: Native
    - [X] Android: mWeb Chrome
    - [X] iOS: Native
    - [X] iOS: mWeb Safari
    - [X] MacOS: Chrome / Safari
    - [X] MacOS: Desktop
- [X] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [X] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>


https://github.com/Expensify/App/assets/61146594/956a0e94-eca4-4557-ad06-878de08af36b



</details>

<details>
<summary>Mobile Web - Chrome</summary>


https://github.com/Expensify/App/assets/61146594/2bbeaf18-3750-46f0-8df3-2f4b9ce09d1f



</details>

<details>
<summary>Mobile Web - Safari</summary>


https://github.com/Expensify/App/assets/61146594/cad4723c-454a-46c1-b408-8983cacd45b9



</details>

<details>
<summary>Desktop</summary>


https://github.com/Expensify/App/a [...]

2023-10-17 14:11 UTC, robertKozik commented
@ishpaul777 you missed one checkbox on your list

2023-10-17 14:14 UTC, robertKozik approved these changes
LGTM

2023-10-17 18:24 UTC, MonilBhavsar reviewed
Few suggestions and/or comments. Looks good overall

2023-10-17 18:24 UTC, MonilBhavsar commented on src/components/MenuItemList.js
> +    /** Whether or not to use the single execution hook */
```suggestion

    /** Whether or not to use the single execution hook */
```

2023-10-17 18:24 UTC, MonilBhavsar commented on src/pages/workspace/WorkspaceInitialPage.js
> +                                    Ideally we should use MenuList component for MenuItems with singleExecution/Navigation Actions.
```suggestion
                                    Ideally we should use MenuList component for MenuItems with singleExecution/Navigation actions.
```

2023-10-17 18:24 UTC, MonilBhavsar commented on src/pages/workspace/WorkspaceInitialPage.js
> +                                        disabled={hasPolicyCreationError || isExecuting || isCurrencyModalOpen}
Why we're adding isCurrencyModalOpen?

2023-10-17 18:24 UTC, MonilBhavsar commented on src/pages/workspace/WorkspaceInitialPage.js
> +                                    But Here we need to have a `isExecuting` for profile details click actions also so we are directly mapping menuItems.
I didn't get this comment. Could you please explain

2023-10-17 18:24 UTC, MonilBhavsar commented on src/components/HeaderWithBackButton/headerWithBackButtonPropTypes.js
> +    /** Single execution function to wrap the action in */
May be this is better
```suggestion
    /** Single execution function to prevent concurrent navigation actions */
```

2023-10-17 18:24 UTC, MonilBhavsar commented on src/pages/workspace/WorkspaceInitialPage.js
> +                    ? waitForNavigate(() => ReimbursementAccount.navigateToBankAccountRoute(policy.id, Navigation.getActiveRoute().replace(/\?.*/, '', waitForNavigate)))()
Why we're passing `waitForNavigate` arg here

2023-10-18 07:08 UTC, MonilBhavsar commented on src/pages/workspace/WorkspaceInitialPage.js
> +                                        disabled={hasPolicyCreationError || isExecuting || isCurrencyModalOpen}
I see, thanks for clarifying. I think we should have a more general solution here - 
We can do what you implemented, but in a generalized way. Like disable list when modal is open in foreground. But adding this condition to every modal on the page does not sound like a good option as it is easy to miss and understand the context, and will eventually lead to blink bug every time a modal is added. Thoughts?

2023-10-18 10:14 UTC, MonilBhavsar commented on src/pages/workspace/WorkspaceInitialPage.js
> +                                    But Here we need to have a `isExecuting` for profile details click actions also so we are directly mapping menuItems.
Okay thanks, we can rephrase the comment then.

2023-10-18 10:14 UTC, MonilBhavsar commented on src/pages/workspace/WorkspaceInitialPage.js
> +                                    But Here we need to have a `isExecuting` for profile details click actions also so we are directly mapping menuItems.
```suggestion
                                    In this case where user can click on workspace avatar or menu items, we need to have a check for `isExecuting`. So, we are directly mapping menuItems.
```

2023-10-18 10:31 UTC, MonilBhavsar commented on src/pages/workspace/WorkspaceInitialPage.js
> +                                        disabled={hasPolicyCreationError || isExecuting || isCurrencyModalOpen}
The `modal` onyx key! cc @robertKozik

2023-10-20 09:58 UTC, MonilBhavsar commented
There are conflicts to resolve.
Since there were major updates, it needs to be re reviewed and re tested by C+. @robertKozik could you please help to review and test.

2023-10-20 10:45 UTC, robertKozik commented
Sureee, I'm on it 👀

2023-10-25 09:48 UTC, robertKozik approved these changes
retested - works well.
CC. @MonilBhavsar

2023-10-25 12:02 UTC, MonilBhavsar approved these changes
Thanks! Looks good and works well 🚀

2023-10-25 12:03 UTC, merged

2023-10-25 12:10 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-10-25 16:59 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6643281628) to staging by https://github.com/MonilBhavsar in version: 1.3.91-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-10-26 22:41 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6660462685) to production by https://github.com/marcaaron in version: 1.3.91-8 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-11-29 08:12 UTC, mollfpr commented on src/components/HeaderWithBackButton/index.js
> +    const waitForNavigate = useWaitForNavigation();
👋 coming from https://github.com/Expensify/App/issues/30636

The hooks here cause an error in the storybook for component `HeaderWithBackButton`.

2024-01-11 14:58 UTC, abdulrahuman5196 commented on src/pages/settings/AboutPage/AboutPage.js
> +                },
link for github url is missed here during refractor