feat: enable next button
Expensify/App pull request #29125
Opened 2023-10-09 20:36 UTC by BhuvaneshPatil

### Details

Currently we don't have next button for distance request enabled by default, this PR will enable the distance request and display the error in case there is an error.

### Fixed Issues

$ https://github.com/Expensify/App/issues/27045
PROPOSAL: https://github.com/Expensify/App/issues/27045#issuecomment-1711984411

### Tests

#### Test 1
1. Empty waypoints
2. Click next
3. Verify an error appears asking you to enter waypoints

#### Test 2
1. Start waypoint A
2. empty waypoint
3. Finish waypoint B
4. Click next
5. Verify that you are navigated without errors

#### Test 3
1. start waypoint A
2. finish waypoint A
3. Click next
4. Verify an error appears about duplicate waypoints

#### Test 4
1. start waypoint A
2. stop waypoint A
3. finish waypoint B
4. Click next
5. Verify that you are navigated without errors

#### Test 5
1. start waypoint A
2. stop waypoint B
3. stop waypoint B
4. finish waypoint A
5. Click next
6. Verify that you are navigated without error

- [X] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android: Native
    - [X] Android: mWeb Chrome
    - [X] iOS: Native
    - [X] iOS: mWeb Safari
    - [X] MacOS: Chrome / Safari
    - [X] MacOS: Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message: https://expensify.slack.com/archives/C01GTK53T8Q/p1696910414908269
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and it [...]

2023-10-10 14:53 UTC, shawnborton commented
Looking good, thanks!

2023-10-12 05:21 UTC, allroundexperts approved these changes
Looks good!

2023-10-12 13:01 UTC, shawnborton commented
Yup, lgtm too

2023-10-12 14:29 UTC, tgolen requested changes

2023-10-12 14:29 UTC, tgolen commented on src/components/DistanceRequest/index.js
> +        return () => {
NAB: Thanks for commenting on the reason you added this. Next time, please add that as a code comment to give context into _why_ that logic is here.

2023-10-12 14:29 UTC, tgolen commented on src/components/DistanceRequest/index.js
> +    useEffect(() => {
OK, here is another one. At this point, I'm going to request that you add these contextual comments to the code.

2023-10-12 14:29 UTC, tgolen commented on src/components/DistanceRequest/index.js
> +        // get route error if available else show the invalid number of waypoints error
Comments should start with a capital letter and end with a period (it should be a normal sentence). Please update this and the comment below as well.

2023-10-12 14:29 UTC, tgolen commented on src/components/DistanceRequest/index.js
> +            // initially, both waypoints will be null, and if we give fallback value as emmpty string that will result in true condition, that's why different default values
```suggestion
            // initially, both waypoints will be null, and if we give fallback value as empty string that will result in true condition, that's why different default values
```
typo

2023-10-12 14:29 UTC, tgolen commented on src/components/DistanceRequest/index.js
> +        if (_.size(validatedWaypoints) < 2) {
It's confusing here that this is mixing `validatedWaypoints` and `waypoints` inside the `if` statement. Can you please clarify why both variables are used for this error?

2023-10-12 14:29 UTC, tgolen commented on src/components/DistanceRequest/index.js
> +                        }
Could you please move this logic inside of `onSubmit`?

2023-10-12 14:29 UTC, tgolen commented on src/languages/en.ts
> +            duplicateWaypointsErrorMessage: 'There are duplicate waypoints',
Shouldn't this message be more like "Please remove duplicate waypoints"?

2023-10-12 14:29 UTC, tgolen commented on src/components/DistanceRequest/index.js
> +    const [userTriedSubmitting, setUserTriedSubmitting] = useState(false);
I agree with your first instinct @allroundexperts and I don't like this being tied to a user action. I'd rather prefer that it is tied to an error state. Maybe something like `hasError, setHasError`.

2023-10-12 16:36 UTC, tgolen commented on src/components/DistanceRequest/index.js
> +                        }
Ah, I didn't realize that `onSubmit()` was from props. OK, then the proper thing to do is to move this to a function that is defined above the `return`, add a `useCallback()` and pass the function here as a reference.

2023-10-12 16:38 UTC, tgolen commented on src/components/DistanceRequest/index.js
> +        if (_.size(validatedWaypoints) < 2) {
OK, but why check `validatedWaypoints` at all then?

2023-10-12 18:46 UTC, tgolen commented on src/components/DistanceRequest/index.js
> +        if (_.size(validatedWaypoints) < 2) {
Ah, yes that makes more sense!

2023-10-12 19:06 UTC, tgolen requested changes
Looks good, just this one last thing.

2023-10-12 19:06 UTC, tgolen commented on src/components/DistanceRequest/index.js
> +    const onPress = useCallback(() => {
Please rename this to what the function does like `submitWaypoints()`

2023-10-12 19:30 UTC, tgolen approved these changes

2023-10-12 20:51 UTC, tgolen commented
I was just waiting for the tests to pass. Not sure why it was taking the lint test so long.

2023-10-12 20:51 UTC, merged

2023-10-12 20:57 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-10-13 21:11 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6512805365) to staging by https://github.com/tgolen in version: 1.3.84-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-10-16 21:12 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6539292081) to production by https://github.com/francoisl in version: 1.3.84-10 🚀

platform | result
---|---
🤖 android 🤖|skipped 🚫
🖥 desktop 🖥|skipped 🚫
🍎 iOS 🍎|skipped 🚫
🕸 web 🕸|skipped 🚫

2023-10-16 21:48 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6539526963) to production by https://github.com/francoisl in version: 1.3.84-10 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅

2023-10-16 21:51 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6539299520) to staging by https://github.com/tgolen in version: 1.3.85-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-10-17 23:16 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6553786410) to production by https://github.com/francoisl in version: 1.3.85-4 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅

2024-01-07 20:11 UTC, allroundexperts commented on src/components/DistanceRequest/index.js
> +        if (_.size(validatedWaypoints) < 2 || hasRouteError || isLoadingRoute || isLoading) {
This condition should have taken into account if the user was offline or not. This later caused https://github.com/Expensify/App/issues/32397

2024-04-01 19:16 UTC, alitoshmatov commented on src/components/DistanceRequest/index.js
> +    const getError = () => {
Duplicate waypoint is not showing error when rearranged, ref: https://github.com/Expensify/App/pull/35910