Try to refactor the logic regarding refocusing when the modal is closed
Expensify/App pull request #29199
Opened 2023-10-10 15:15 UTC by ntdiary

So far, the `Modal` components under our control can be categorized into three types: `BaseModal`, `PopoverWithoutOverlay`, and `RHP` (Right Hand Panel).

This PR will simulate the iOS native Modal refocusing behavior: If there is a focused input field before opening the `Modal`, our app will attempt to restore that focus after the `Modal` is dismissed. If there is no focus before opening, no restore after the `Modal` is dismissed.

Additionally, this PR will introduce a `restoreFocusType` prop, here are possible values:
1. `default`, this will follow the default behavior mentioned above.
2. `preserve`, this will leave the focus in the manager and no longer restore focus, applicable for consecutive modal scenarios.
3. `delete`, this will delete the focus and no longer restore focus, the caller can decide in its own business logic whether to focus a specific element. 

The specific business Modals that have been tested:
1. context menu (long press / right click a message to open this modal)
2. three dots menu (click the three dot button in the top right corner of the app to open this modal)
3. confirm modal (some `delete` actions will show this modal)
4. attachment preview modal (click an image message to open this modal)
5. emoji picker modal (click the emoji button in a composer)
6. the main composer attachment modal (click the plus button in the main composer to open this modal)
7. RHP (click the username in a message to open the profile page, or use shortcuts to open some RHP pages)

Once the POC is approved by most people, we'll refine the code, clean things up, and then repush it.

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/29011
$ https://github.com/Expensify/App/issues/24452
PROPOSAL: https://github.com/Expensify/App/issues/24452#issuecomment-1712021524

### Tests

#### context menu modal

<details><summary>case 1 (cancel action)</summary>
<p>

1. Open a report.
2. Focus the main composer.
3. Send a regular text message.
4. Long press this message to open the context menu modal (or right click the message for web/desktop platforms).
5. Click the backdrop or blank area to close the context menu modal.
6. Verify the main composer will gain focus again.
7. Make the main composer lose focus.
8. Repeat step 4 & 5.
9. Verify the main composer won't gain focus again.

- [x] android native
- [x] android chrome
- [x] ios native
- [x] ios web
- [x] web
- [x] desktop

</p>
</details>

<details><summary>case 2 (add reaction + cancel action)</summary>
<p>

1. Open a report.
2. Focus the main composer.
3. Long press a text message to open the context menu modal.
4. Click the `Add reaction`to open the emoji modal.
5. Verify that there is no focus/keyboard flickering during the transition.
6. Click the backdrop or blank area to close the emoji modal.
7. Verify the main composer will gain focus again.
8. Make the main composer lose focus.
9. Repeat step 3, 4, 5, and 6.
10. Verify the main composer won't gain focus again.

- [x] android native
- [x] android chrome
- [x] ios native
- [x] ios web
- [x] web
- [x] desktop

</p>
</details> 

<details><summary>case 3 (edit coment)</summary>
<p>

1. Open a report.
2. Focus the main composer.
3. Long press a text message to open the context menu modal.
4. Select the `Edit comment`.
5. Verify the edit composer will gain focus.

- [x] android native
- [x] android chrome
- [x] ios native
- [x] ios web
- [x] web
- [x] desktop

</p>
</details>

<details><summary>case 4 (delete comment)</summary>
<p>

1. Open a report.
2. Focus the main composer.
3. Long press the text message to open the context menu modal.
4. Select the `Delete comment` to open the `Confirm` modal.
5. Verify that there is no focus/keyboard flickering during the transition.
6. Click the backdrop / `Delete` button / `Cancel` button to close the `Confirm` modal.
7. Verify the main composer will gain focus again.
8. Make the main composer lose focus.
9. Repeat step 3, 4, 5, and 6.
10. Verify the main composer won't gain focus again.

- [x] android native
- [x] android chrome
- [x] ios native
- [x] ios web
- [x] web
- [x] desktop

</p>
</details> 

<hr />

#### emoji modal
<details><summary>case 1 (cancel action)</summary>
<p>

1. Open any report.
2. Focus the main composer.
3. Click the emoji button to open the emoji modal.
4. Click the backdrop or blank area to close the emoji modal.
5. Verify the main composer will gain focus again.
6. Make the main composer lose focus.
7. Repeat step 3 & 4.
8. Verify the main composer won't gain focus again.

- [x] android native
- [x] android chrome
- [x] ios native
- [x] ios web
- [x] web
- [x] desktop

</p>
</details> 

<details><summary>case 2 (cancel action)</summary>
<p>

1. Open any report.
2. Edit a text message.
3. Click the emoji button in the edit composer to open the emoji modal.
4. Click the backdrop or blank area to close the emoji modal.
5. Verify the edit composer will gain focus again.
6. Make the edit composer lose focus.
7. Repeat step 3 & 4.
8. Verify the edit composer won't gain focus again.

- [x] android native
- [x] android chrome
- [x] ios native
- [x] ios web
- [x] web
- [x] desktop

</p>
</details>

<details><summary>case 3 (cancel action)</summary>
<p>

1. Open any report.
2. Edit a text message.
3. Focus the main composer.
4. Click the emoji button in the edit composer to open the emoji modal.
5. Click the backdrop or blank area to close the emoji modal.
6. Verify the main composer will gain focus again.

- [x] android native
- [x] android chrome
- [ ] ~~ios native~~
      main focus didn't show
- [x] ios web
- [x] web
- [x] desktop

</p>
</details>

<hr />

#### Right Hand Panel

<details><summary>case 1 (test by mouse)</summary>
<p>

1. Open a report.
2. Focus the main composer.
3. Click the top avatar to open the detail page.
4. Click the backdrop to close the detail page. 
5. Verify the main composer will gain focus again.
6. Make the main composer lose focus.
7. Repeat step 3 & 4.
8. Verify the main composer won't gain focus again.

- [x] android native
- [x] android chrome
- [x] ios native
- [x] ios web
- [x] web
- [x] desktop

</p>
</details>

<details><summary>case 2 (test by keyboard shortcuts)</summary>
<p>

1. Open a 1:1 report.
2. Focus the main composer.
3. Press `CMD + J` to open the keyboard shortcuts page.
4. Click the backdrop to close the shortcuts page. 
5. Verify the main composer will gain focus again.
6. Make the main composer lose focus.
7. Repeat step 3 & 4.
8. Verify the main composer won't gain focus again.

- [x] android native
- [x] android chrome
- [x] ios native
- [x] ios web
- [x] web
- [x] desktop

</p>
</details>

<hr />

#### attachment modal
<details><summary>case 1 (cancel action)</summary>
<p>

1. Open a report.
2. Focus the main composer.
3. Click the plus button in the main composer to open the first attachment modal.
4. Click the backdrop or blank area to close the first attachment modal. 
5. Verify the main composer will gain focus again.
6. Make the main composer lose focus.
7. Repeat step 3 & 4.
8. Verify the main composer won't gain focus again.

- [x] android native
- [x] android chrome
- [x] ios native
- [x] ios web
- [x] web
- [x] desktop

</p>
</details> 

<details><summary>case 2 (first attachment modal + RHP)</summary>
<p>

1. Open a report.
2. Focus the main composer.
3. Click the plus button to open the first attachment modal.
4. Select the `Request money` / `Send money` / `Assign task`.
5. Verify that there is no focus/keyboard flickering during the transition.
6. Click the top-left back button.
7. Verify the main composer will gain focus again.
8. Make the main composer lose focus.
9. Repeat step 3, 4, 5, and 6.
10. Verify the main composer won't gain focus again.

- [x] android native
- [x] android chrome
- [x] ios native
- [x] ios web
      it seems that the viewport api is not stable.
- [x] web
- [x] desktop

</p>
</details> 

<details><summary>case 3 (all mobile platforms: cancel action for the second modal [...]

2023-12-01 16:22 UTC, parasharrajat requested changes

2023-12-21 10:24 UTC, Julesssss commented
Hey both, just checking the progress here. It looks like there have been a decent amount of updates since the last review, but I see lint errors. @ntdiary is this ready for a second C+ review?

2023-12-21 13:43 UTC, Julesssss commented
Great, I'm going to be out until early January, so there's no huge rush @parasharrajat

2024-01-03 10:21 UTC, trjExpensify commented
👋 @ntdiary can you address the conflicts, please? Thanks!

2024-01-12 00:13 UTC, trjExpensify commented
Doh, looks like we have conflicts again!

2024-01-22 11:17 UTC, Julesssss commented
Hey @ntdiary, looks like a lot more progress has been made. Anything we can help with in the meantime?

2024-01-23 09:48 UTC, Julesssss commented
Hey @ntdiary, that is totally fine. Thanks for keeping on top of other issues. 

I have requested that you get removed from assignments temporarily, please just let me or another Expensify employee know in the C+ Slack channel when you would like to rejoin.

2024-01-30 09:47 UTC, Julesssss reviewed
Hey @ntdiary, I didn't realise this would require so many test cases. Lets talk in the issue about increasing the bounty 👍

2024-02-21 14:34 UTC, Julesssss commented
Hey @parasharrajat, bumping the review here now your back

2024-03-28 22:42 UTC, mallenexpensify commented
@ntdiary can you provide an update on where we're at here? 
Asking cuz the below is held on this PR
- https://github.com/Expensify/App/issues/32970

2024-04-30 16:42 UTC, Julesssss commented
Ah another new problem introduced by the new architecture 😅

2024-06-17 08:24 UTC, Julesssss commented
Hey @ntdiary. Can we close this outdated PR?

2024-06-17 12:12 UTC, closed without merging