added enable wallet state
Expensify/App pull request #29430
Opened 2023-10-12 12:11 UTC by techievivek

### Details

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/324579
PROPOSAL: 

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the  [...]

2023-10-18 11:16 UTC, MariaHCD reviewed
Looks good so far! Some minor comments.

@fedirjh, we'd appreciate a code review from you as well. This one is critical for an upcoming conference.

I can handle testing on all platforms since this requires a Gold wallet.

2023-10-18 11:16 UTC, MariaHCD commented on src/languages/en.ts
> +        waitingOnEnableWallet: ({submitterDisplayName}: WaitingOnBankAccountParams) => `Started settling up, payment is held until ${submitterDisplayName} enables their Wallet`,
```suggestion
        waitingOnEnabledWallet: ({submitterDisplayName}: WaitingOnBankAccountParams) => `Started settling up, payment is held until ${submitterDisplayName} enables their Wallet`,
```

2023-10-18 11:16 UTC, MariaHCD commented on src/pages/home/report/ReportActionItem.js
> +                ReportUtils.isCurrentUserSubmitter(props.report.reportID) && paymentType === CONST.IOU.PAYMENT_TYPE.EXPENSIFY && !ReportUtils.isSettled(props.report.reportID);
I think we can DRY this up a little:

```js
const isSubmitterOfUnsettledReport = ReportUtils.isCurrentUserSubmitter(props.report.reportID) && !ReportUtils.isSettled(props.report.reportID);

const shouldShowAddCreditBankAccountButton = isSubmitterOfUnsettledReport && paymentType !== CONST.IOU.PAYMENT_TYPE.EXPENSIFY;

const shouldShowEnableWalletButton =  iisSubmitterOfUnsettledReport && paymentType === CONST.IOU.PAYMENT_TYPE.EXPENSIFY;
```

2023-10-18 11:52 UTC, fedirjh reviewed
The code looks good, but it still should be tested. Is there a beta for the gold wallet?

2023-10-18 11:55 UTC, MariaHCD commented
@techievivek can you also merge main into this branch?

2023-10-18 11:56 UTC, MariaHCD commented
> but it still should be tested. Is there a beta for the gold wallet?

I'm testing now. Everyone is on the wallet beta (with a silver wallet) but we do not have the ability to create test gold wallets at the moment.

2023-10-18 12:00 UTC, MariaHCD commented
@techievivek I notice that the send money flow keeps redirecting the payer to the KYC flow even if the payer's wallet is activated:

https://github.com/Expensify/App/assets/12268372/677eb533-fc1a-4113-92b9-9c378a61fb03

2023-10-18 12:36 UTC, MariaHCD requested changes
Noticed a few things:
1. We need to direct the user to add a PBA first if they don't have one, this logic is handled by the KYCWall component, I think we should be able to use it here.
2. I'm seeing the report action twice and with incorrect messaging:

Payer with gold wallet sees this:

![Screenshot 2023-10-18 at 4 35 44 PM](https://github.com/Expensify/App/assets/12268372/d8977529-045d-4619-9717-eb07a952f98b)


Payee with silver wallet sees this:

![Screenshot 2023-10-18 at 4 35 56 PM](https://github.com/Expensify/App/assets/12268372/2fc65353-b642-44a3-8864-e1519ab5e129)

2023-10-18 12:36 UTC, MariaHCD commented on src/pages/home/report/ReportActionItem.js
> +                            onPress={() => Navigation.navigate(ROUTES.ENABLE_PAYMENTS)}
If the user does not have a personal bank account set up, we should redirect them to the Personal Bank account page first.

Can we use the [KYCWall](https://github.com/Expensify/App/blob/a24e6a09b86f703f8ccf2e8f4bb29a4aabd6c761/src/components/SettlementButton.js#L201-L224) here?

2023-10-18 13:03 UTC, MariaHCD commented
In the interest of saving time, I've DRY'd some code and added the use of the KYCWall

2023-10-18 13:04 UTC, MariaHCD commented
We still need to:
1. Figure out why the queued action is being displayed twice
2. Why a payer can't get past the KYC flow when sending money

2023-10-18 13:33 UTC, techievivek commented
Taking a look, thanks for pushing this through while I was away.

2023-10-18 13:37 UTC, techievivek commented
```
started settling up, payment is held until ${submitterDisplayName} adds a bank account
```
This message seems to be shown because we are adding the property `isWaitingOnBankAccount` to the report.

2023-10-18 13:38 UTC, techievivek commented
We can add a check to not show this if the paymentType is wallet.

2023-10-18 14:26 UTC, techievivek commented
I am only seeing a single action here. Also, I am not sure why we would see two actions there. The other action
```
started settling up, payment is held until ${submitterDisplayName} adds a bank account
```
would also fall under the same if block of `else if (props.action.actionName === CONST.REPORT.ACTIONS.TYPE.REIMBURSEMENTQUEUED) {`

2023-10-18 17:27 UTC, fedirjh reviewed
The code looks good. I just tested some hardcoded values and it seems to be working fine


https://github.com/Expensify/App/assets/36869046/92ce335c-2c56-42f5-bf1b-7f957ea8143e

2023-10-19 05:49 UTC, techievivek commented on src/pages/home/report/ReportActionItem.js
> +                        <KYCWall
Testing it, thanks.

2023-10-19 05:52 UTC, techievivek commented on src/pages/home/report/ReportActionItem.js
> +                        <KYCWall
That worked 🎉, but I am curious to learn how it fixed that error? Because there is just a single element right? `KYCWall`?

2023-10-19 08:10 UTC, MariaHCD submitted a review, later dismissed

2023-10-19 08:10 UTC, MariaHCD commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Mobile Web - Chrome</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Mobile Web - Safari</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Desktop</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>iOS</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Android</summary>

<!-- [...]

2023-10-19 08:54 UTC, MariaHCD commented
LGTM, we're going to address polish items in follow up PRs. Please final review, @fedirjh 🙏🏼

2023-10-19 12:55 UTC, fedirjh reviewed
Looks good to me, just one little change and should be ready to get merged.

2023-10-19 13:02 UTC, techievivek commented on src/pages/home/report/ReportActionItem.js
> +                        <KYCWall
Interesting, but by just wrapping the KycWall in a fragment it looks like the error is gone, how does that work? Any idea?

2023-10-19 13:04 UTC, techievivek commented on src/pages/home/report/ReportActionItem.js
> +                        <KYCWall
Ah no, the user is only on the gold wallet that's why this condition is not being called.

2023-10-19 13:05 UTC, techievivek commented on src/pages/home/report/ReportActionItem.js
> +                        <KYCWall
The error is still there. What you explained make sense now. Thanks 👍

2023-10-19 13:13 UTC, MariaHCD approved these changes

2023-10-19 13:19 UTC, fedirjh approved these changes
Looks good to me.

2023-10-19 13:21 UTC, merged

2023-10-19 13:27 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-10-20 21:38 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6592629328) to staging by https://github.com/MariaHCD in version: 1.3.88-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-10-23 04:51 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6608779761) to production by https://github.com/chiragsalian in version: 1.3.88-11 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅

2023-10-24 18:19 UTC, cead22 commented on src/languages/es.ts
> +        waitingOnEnabledWallet: ({submitterDisplayName}: WaitingOnBankAccountParams) => `nicio el pago, pero no se procesará hasta que ${submitterDisplayName} active su Billetera`,
@techievivek this should be `Inició` or `inició`, can you submit a PR to update please?