Update request money header title
Expensify/App pull request #29936
Opened 2023-10-19 04:18 UTC by DylanDylann

### Details

1. App displays 'Split' in title on back from scan request money
2. App displays 'Split' in title on back from manual request money

### Fixed Issues

### Tests

1. Open the app
2. Click on plus and click request money->scan
3. Select any file
4. Observe now it displays 'Scan' in header, select any user
5. Click on back and verify that now it displays 'Scan' in header
6. Click manual tap, enter amount and select any user
7. Verify that header is unchanged when click back button in split and manual

- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

1. Open the app
2. Click on plus and click request money->scan
3. Select any file
4. Observe now it displays 'Scan' in header, select any user
5. Click on back and verify that now it displays 'Scan' in header
6. Click manual tap, enter amount and select any user
7. Verify that header is unchanged when click back button in split and manual

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component  [...]

2023-10-20 03:47 UTC, DylanDylann commented
@fedirjh Could you help to take a look at this PR? Thanks

2023-10-25 02:26 UTC, DylanDylann commented
@fedirjh Could you help to check this comment? https://github.com/Expensify/App/pull/29936#discussion_r1368774468

2023-10-25 14:27 UTC, DylanDylann commented
@fedirjh I am trying your suggestion, i will give some response asap

2023-10-25 16:58 UTC, DylanDylann commented
@fedirjh I just updated code according to your logic, please check again

2023-10-25 17:04 UTC, fedirjh reviewed
Let's simplify the code a bit.

2023-10-25 17:30 UTC, DylanDylann commented on src/libs/actions/IOU.js
> +}
@fedirjh Thank you for your comment, please check again

2023-10-25 17:39 UTC, DylanDylann commented on src/libs/actions/IOU.js
> +    Onyx.merge(ONYXKEYS.IOU, {isSplitRequest});
@fedirjh Quickly updated

2023-10-26 02:55 UTC, DylanDylann commented
> @DylanDylann We should reset the `isSplitRequest` to `false` inside `IOU.resetMoneyRequestInfo` to fix [this issue](https://github.com/Expensify/App/pull/29936#discussion_r1372170952).

Thanks for your suggestion, I updated

2023-10-26 02:56 UTC, DylanDylann commented on src/libs/actions/IOU.js
> +    Onyx.merge(ONYXKEYS.IOU, {isSplitRequest});
> cc @DylanDylann I think there is one more change needed, let's pass an empty array when `iou.isSplitRequest` is `false`.

@fedirjh  I think it is unnecessary, currently as code change we have 2 cases `iou.isSplitRequest = false`
1. In function `addSingleParticipant` (manual case) we must pass participants param
2. In function `addParticipantToSelection`, `isSplitRequest = false` when `newSelectedOptions.length === 0` which means `newSelectedOptions` is empty

2023-10-26 11:26 UTC, fedirjh requested changes
@DylanDylann Please address this bug, https://github.com/Expensify/App/pull/29936#discussion_r1373001768

2023-10-27 02:54 UTC, DylanDylann commented
@fedirjh Thanks for your suggestion, I updated. Please check again

2023-10-27 15:23 UTC, fedirjh approved these changes
Looks good to me.

2023-10-27 15:41 UTC, amyevans approved these changes

2023-10-27 15:42 UTC, merged

2023-10-27 15:47 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-10-30 08:02 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6689615729) to staging by https://github.com/amyevans in version: 1.3.93-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-10-31 21:35 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6712612023) to production by https://github.com/Beamanator in version: 1.3.93-1 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-10-31 22:02 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6712617804) to staging by https://github.com/amyevans in version: 1.3.94-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅

2023-11-01 08:54 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6712617804) to staging by https://github.com/amyevans in version: 1.3.94-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅

2023-11-02 10:17 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6730922807) to production by https://github.com/Beamanator in version: 1.3.94-2 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅