Fix: Missing translation for server errors
Expensify/App pull request #30073
Opened 2023-10-20 12:35 UTC by tienifr

### Details

Server errors are already translated so App can't find the translation key and displays `Missing translation` for `@expensify.com` emails. This PR modifes to pass translation key directly to `errorText`  and add `isTranslated: true` to already translated texts.

### Fixed Issues

$ https://github.com/Expensify/App/issues/29712
PROPOSAL: https://github.com/Expensify/App/issues/29712#issuecomment-1765525048

### Tests

**For every error message below, try to switch language from another device and verify the message changes accordingly.**

1. Go to Settings >> Profile >> Contact method
2. Add a new contact method
3. Press Verify in validate code page without typing anything
4. Verify `Please enter your magic code` error appears
5. Type in one digit only >> Verify
6. Verify `Incorrect magic code` error appears
7. Type in an arbitrary magic code >> Verify
8. Verify `Incorrect or invalid magic code. Please try again or request a new code.` error appears
9. Delete one digit
10. Verify the error disappears

#### `AddressForm`

1. Go to Settings >> Profile >> Personal details >> Address
2. Verify the hint under `Zip / Postcode` shows the correct Zip example for your locale

#### `AvatarWithImagePicker`

1. Go to Settings
2. Press avatar >> Upload photo
3. Upload an invalid extension file (e.g. `pdf`)
4. Verify error shows `Profile picture must be one of the following types: jpg, jpeg, png, gif, bmp, svg.`
5. Upload a very large image in size (> 6MB)
6. Verify error shows `The selected image exceeds the maximum upload size of 6MB.`
7. Upload a very large image in resolution (> 4096x4096px)
8. Verify error shows `Please upload an image larger than 80x80 pixels and smaller than 4096x4096 pixels.`

#### `DistanceRequest` & `IOURequestStepDistance`

1. Create a distance request with duplicated waypoints
2. Verify error shows `Please enter at least two different addresses`
3. Edit a distance request with new duplicated waypoints
4. Verify step 2

#### `MoneyRequestConfirmationList` & `MoneyTemporaryForRefactorRequestConfirmationList`

1. Update the rate for a workspace (Workspace >> Settings >> Reimbursements >> Track distance) to very high (e.g., 90000000)
2. Create a distance request for that workspace
5. Verify error shows `Invalid amount`
6. Create a manual request without merchant
7. Verify error shows `Please enter a correct merchant.`

#### `BaseOptionsSelector`

1. Press FAB >> Start chat >> Chat
2. In search input, type text with more than 500 letters
3. Verify error shows `Character limit exceeded (515/500)`
4. Remove some letters to reach 500
5. Verify error disappears

#### `PDFPasswordForm`

1. Send a protected PDF
2. Open that file >> Press enter the password
3. Do not type >> Confirm
4. Verify error shows `Please enter a password`
5. Type an incorrect password >> Confirm
8. Verify error shows `Incorrect password. Please try again.`

#### `TimePicker` & `StatusClearAfterPage`

1. Go to Settings >> Profile >> Status >> Clear after >> Custom >> Time
2. Select a time in the past >> Save
3. Verify error shows `Please choose a time at least one minute ahead.`

#### `NewChatPage` & `SearchPage` & `MoneyTemporaryForRefactorRequestParticipantsSelector`

1. Toggle on Offline mode
2. Press FAB >> Start chat
3. Verify message shows `You appear to be offline. Search results are limited.`
4. Press Search bar
5. Verify step 3
6. Create a manual money request
9. Verify step 3 in participant selector step

#### `CompanyStep`

1. Go to any Workspace settings >> Card >> Connect bank account >> Connect manually
2. Go to Company information step
3. Verify message under Company address field shows `PO boxes and mail drop addresses are not allowed`
4. Type an emoji in Legal business name
5. Verify error shows `Please enter a valid legal business name`
10. Type an invalid Zip code
11. Verify error shows `Incorrect zip code format. Acceptable format: 12345, 12345-1234, 12345 1234`
12. Manually modify [here](https://github.com/Expensify/App/blob/9f37d3e2c1264420773c886ae6171748e5d512b8/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L252) to `REQUESTOR` step
13. Type text in Last 4 digits of SSN
14. Verify error shows `Please enter valid last 4 digits of SSN`

#### `MoneyRequestAmountForm`

1. Create a money request with amount 0
2. Verify error shows `Please enter a valid amount before continuing.`

#### `TwoFactorAuthForm`

1. Go to Settings >> Security >> Two-factor authentication
2. Without copy or download recovery code, press Next
3. Verify error shows `Please copy or download codes before continuing.`
4. Copy the code then press Next
5. Without filling 2FA code, press Next
6. Verfiy error shows `Please enter your two-factor authentication code`
7. Fill incorrect 2FA code
8. Verify error shows `Invalid Two Factor Authentication code. Please re-enter the code from your authentication app.`

#### `SignIn`

1. Logout
2. Type an invalid email in Phone or email
3. Verify error shows `The email entered is invalid. Please fix the format and try again.`
4. Sign in with invalid magic code
5. Verify error shows `Incorrect magic code. Please try again or request a new code.`
6. Close an account
7. Verify message with green dot shows `Account closed successfully`

#### `Task`

1. Toggle on offline mode
2. Press FAB >> Assign task
3. Without filling anything, press Next
4. Verify error shows `Please enter a title`
5. Fill in a title >> Next
6. Do not select assignee
7. Verify error shows `Please select with whom you want to share.`
8. Press Share somewhere
9. Verify message shows `You appear to be offline. Search results are limited.`

#### `WorkspaceMembersPage`

Read here: https://github.com/Expensify/App/pull/23702#issue-1823427326.

#### `ExpensifyCardPage`

1. Mock data set in console:

```javascript
Onyx.set(`cardList`, {
    '2': {
        cardID: 234523452345,
        state: 3,
        bank: 'Expensify',
        availableSpend:10000,
        domainName: 'Expensify',
        lastFourPAN: '',
        isVirtual: true,
        cardholderFirstName: "Test",
        cardholderLastName: "Test",
    },
    '3': {
        cardID: 234523452345,
        state: 3,
        bank: '1000',
        availableSpend:10000,
        domainName: 'Expensify',
        lastFourPAN: '2345',
        isVirtual: false,
    },
});
```
15. Go to `/settings/wallet/card/Expensify`
16. Press Reveal details
17. Verify error shows `An error occurred while loading the card details. Please check your internet connection and try again.`
18. Mock fraud card

```javascript
Onyx.merge(`cardList`, {
    '2': {
        fraud: 'domain',
    },
});
```
19. Verify error shows `Your card is temporarily locked while our team reviews your company's account.`

#### `ReportCardLostPage`

20. Press Report physical card lost / damaged
21. Do not choose a reason >> Next
22. Verify error shows `Reason is required`

#### `TransferBalancePage`

23. Mock Onyx data:

<details>

```javascript
Onyx.merge("bankAccountList", {
  '1': {
      "title": `Generic bank Checking`,
      "description": "Account ending in 5087",
      "methodID": '1',
      "key": `bankAccount-1`,
      "accountType": "bankAccount",
      "accountData": {
          "accountNumber": "XXXXX5087",
          "additionalData": {
              "bankName": `Generic bank`,
          },
          "state": "OPEN",
          "type": "BUSINESS"
      },
      "isDefault": false
  },
  '2': {
      "title": `Generic bank Checking 2`,
      "description": "Account ending in 5123",
      "methodID": '2',
      "key": `bankAccount-2`,
      "accountType": "bankAccount",
      "accountData": {
          "accountNumber": "XXXXX5087",
          "additionalData": {
              "bankName": `Generic bank`,
          },
          "state": "OPEN",
          "type": "BUSINESS"
      },
      "isDefault": false
  }
});

Onyx.merge('fundList', {
  "4": {
      "title": "Test card",
      "description": "Card ending in 4242",
      "methodID": 4,
      "key": "ca [...]

2023-10-24 23:59 UTC, mountiny commented
Also got this when trying to send money and it failed, lets make sure these are covered too
<img width="209" alt="image" src="https://github.com/Expensify/App/assets/36083550/8b290d43-1dde-479f-b0f6-76fdee0a81ec">

2023-11-22 18:15 UTC, marcaaron commented
What's the status on this one? Are we close?

2023-11-22 23:26 UTC, 0xmiroslav requested changes
Console errors:

<img width="625" alt="Screenshot 2023-11-23 at 12 26 00 am" src="https://github.com/Expensify/App/assets/97473779/f2f1e30b-b3f2-46c9-afa4-6791508810ff">
<img width="625" alt="Screenshot 2023-11-23 at 12 26 08 am" src="https://github.com/Expensify/App/assets/97473779/51f5c850-d66b-4f2e-b8ce-2aa170b71ab4">

2023-12-20 00:53 UTC, mallenexpensify commented
What's status here? I see 
> yes close. Just waiting for last conflict to be fixed

but that was from a month ago.

2023-12-20 00:56 UTC, mallenexpensify commented
> But not fixed yet

@0xmiroslav , what is not fixed yet, the bug and this PR? If so, what's the holdup?

2023-12-20 01:05 UTC, mallenexpensify commented
Thanks @0xmiroslav , @tienifr can you please provide and update and prioritize this since it's been a while?

2023-12-26 16:47 UTC, iwiznia commented
Is this PR abandoned? If so, we will reassign it to someone else.

2024-01-04 02:35 UTC, marcaaron commented
Looks like there are some conflicts. @tienifr can you fix those? @0xmiroslav can you prioritize a review as soon as the PR is ready for review next?

2024-01-10 02:18 UTC, marcaaron commented
There are conflicts again @tienifr. 

Can we please start the review with the conflicts? We don't _need_ to wait until the conflicts are fixed to review the PR.

2024-01-18 20:09 UTC, mountiny commented
@tienifr merge conflicts

2024-01-22 18:43 UTC, marcaaron commented
@0xmiroslav Is the expectation that we will keep this PR perpetually open until all of the MISSING_TRANSLATION are cleared?

Or are we expecting to have follow up PRs to address these missing translations as they pop up?

@tienifr if you are fixing the issue mentioned in the last comment can you give us an ETA?

2024-01-23 03:45 UTC, marcaaron commented
Hm I would like to get this PR merged actually - it's been open for 3 months and has had many revisions :/ 

Maybe I am not understanding the intention of the `MISSING_TRANSLATION` stuff. But if someone changes something on the server or adds some new feature new cases will keep popping up as bug reports? Or is it possible to address them in a single PR? If not - then let's take some steps to get this merged.

2024-01-24 03:45 UTC, marcaaron commented
That's great! Thanks for confirming @tienifr. In that case, let's keep going.

2024-01-24 15:01 UTC, situchan commented
@tienifr please fix conflict

2024-01-26 17:29 UTC, situchan commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<d [...]

2024-01-26 22:06 UTC, marcaaron commented
@situchan Please ✅ 
![2024-01-26_12-04-49](https://github.com/Expensify/App/assets/32969087/4b5a9e2d-5873-4524-b151-608df86fdcc0)

@tienifr There's one more conflict 😢

2024-01-28 13:02 UTC, situchan commented
@tienifr please fix conflict. I will complete today (Sunday)

2024-01-28 16:52 UTC, situchan commented on src/languages/en.ts
> +            genericFailureMessage: "Private notes couldn't be saved",
Did you get confirmation on this Copy? Also Spanish?

2024-01-28 16:59 UTC, situchan commented
BUG: Crash on LHN

<img width="330" alt="Screenshot 2024-01-28 at 10 58 29 PM" src="https://github.com/Expensify/App/assets/108292595/c4fd5f02-fb06-4738-bdc0-fa6b1ccf64a7">

<img width="483" alt="Screenshot 2024-01-28 at 10 58 10 PM" src="https://github.com/Expensify/App/assets/108292595/ac261b0e-925b-4d8a-8c94-48f8de9714a0">

2024-01-28 17:25 UTC, situchan commented on tests/actions/IOUTest.js
> +                                        expect(_.values(transaction.errors)[0]).toStrictEqual(['iou.error.genericCreateFailureMessage', {isTranslated: false}]);
Any reason for using `toStrictEqual`?
I see `toEqual` in other parts (i.e. [here](https://github.com/Expensify/App/pull/30073/files#diff-a7f0b97fed238bc21653cb5b40f84a094a4fcc2d3ffcab4317bb8ca0db97e35eR1631) and [here](https://github.com/Expensify/App/pull/30073/files#diff-a7f0b97fed238bc21653cb5b40f84a094a4fcc2d3ffcab4317bb8ca0db97e35eR1845))

2024-01-28 17:31 UTC, situchan commented
Console error:

<img width="330" alt="Screenshot 2024-01-28 at 11 31 11 PM" src="https://github.com/Expensify/App/assets/108292595/5c41faac-e23b-4ddb-9db6-a3d4d87134a4">

on this page:

<img width="330" alt="15-contact-methods" src="https://github.com/Expensify/App/assets/108292595/62d9d1ec-bf38-417c-b13f-c7328043ffae">

2024-01-28 18:00 UTC, situchan commented
Please explain Tests steps for these changes:
- libs/actions/Card.ts
- pages/EnablePayments/OnfidoPrivacy.js
- pages/settings/Wallet/ExpensifyCardPage.js
- pages/settings/Wallet/ReportCardLostPage.js
- pages/settings/Wallet/TransferBalancePage.js
- pages/signin/UnlinkLoginForm.js
- pages/workspace/WorkspaceInvitePage.js

2024-01-28 18:13 UTC, situchan commented
Also add screenshots for all test cases (about 30 pages are affected by this PR)

2024-01-29 15:00 UTC, situchan commented
> BUG: Crash on LHN for non-expensify email domain, `[MISSING TRNSLATION]` for expensify domain `[Attachment]` is the expected string
> 
> <img alt="Screenshot 2024-01-28 at 10 58 29 PM" width="330" src="https://private-user-images.githubusercontent.com/108292595/300279731-c4fd5f02-fb06-4738-bdc0-fa6b1ccf64a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDA2OTYsIm5iZiI6MTcwNjU0MDM5NiwicGF0aCI6Ii8xMDgyOTI1OTUvMzAwMjc5NzMxLWM0ZmQ1ZjAyLWZiMDYtNDczOC1iZGMwLWZhNmIxY2NmNjRhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxNDU5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2VkNzAzMTQyM2JlOGRjY2Q0OTJjODE0OTI2MTUzMDEwNzBjMWU1MTE3MGYyYzIyNTM4YzI5OGI3NjU0YzU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TMRFcCUgyMPul25wT2Ro6_D5YSZu7qNYNgEGCSGuuSg"> <img alt="Screenshot 2024-01-28 at 10 58 10 PM" width="483" src="https://private-user-images.githubusercontent.com/108292595/300279725-ac261b0e-925b-4d8a-8c94-48f8de9714a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDA2OTYsIm5iZiI6MTcwNjU0MDM5NiwicGF0aCI6Ii8xMDgyOTI1OTUvMzAwMjc5NzI1LWFjMjYxYjBlLTkyNWItNGQ4YS04Yzk0LTQ4ZjhkZTk3MTRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxNDU5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTFhNmIxNTFmZDU1OGRmOWEyMTlkNDI4MmFmMjY5NGQzOTQ3OTk1ZjIzNzU2YTE5OGM3Zjg1Y2E4OGNhM2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.axI_nMlkeP4nPXmOm-nf2CQey_Ok5B35Gbq10-qNXvQ"> <img alt="Screenshot 2024-01-28 at 11 01 08 PM" width="323" src="https://private-user-images.githubusercontent.com/108292595/300279955-5fd76157-50ed-46af-9a77-4089594a96ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDA2OTYsIm5iZiI6MTcwNjU0MDM5NiwicGF0aCI6Ii8xMDgyOTI1OTUvMzAwMjc5OTU1LTVmZDc2MTU3LTUwZWQtNDZhZi05YTc3LTQwODk1OTRhOTZhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxNDU5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmUxNGJmMDVjMGM1NGU5YmIzOGM4YjVkNGE5MDM5YTkxMjEwZmUwMzY2MmQ2MDU5NmIyMWViZDIyYjA1NmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7uTD9q6rX9vHHlhWKHrLwpquySUslfcVQe3Tz_5pOgg">
> What I did: send pwd protected pdf attachment on any chat

This is now fixed on main. Please sync. There's conflict

2024-01-29 18:06 UTC, mallenexpensify commented
Thanks for prioritizing getting this wrapped up @situchan and @tienifr

2024-01-29 21:34 UTC, marcaaron commented
It feels like we are so close here! Let's get this one over the finish line 🙏

2024-02-02 20:32 UTC, iwiznia commented
Just found this PR... 
Is this PR going to fix all issues of missing translation?
Also, did you see [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1702316632335369) (and more about it in https://expensify.slack.com/archives/C01GTK53T8Q/p1705512051876189?thread_ts=1705511331.469849&cid=C01GTK53T8Q)? And do you agree that we should get rid of the method `translateIfPhraseKey`?

2024-02-02 22:15 UTC, marcaaron commented
>Is this PR going to fix all issues of missing translation

I am interpreting this question as - we should stop showing `MISSING_TRANSLATION` entirely?

If so, I agree with that 100% and I am very confused about why we ever did this in the first place. But assuming for now that the purpose of this PR is to fix whatever ones are showing up as broken in staging.

I asked a similar question [here](https://github.com/Expensify/App/pull/30073#issuecomment-1905242718)

And this was the response: https://github.com/Expensify/App/pull/30073#issuecomment-1905244757

Which makes it sound like this PR _will_ fix it so that we won't show `MISSING_TRANSLATION` for any server errors moving forward. But maybe @tienifr can confirm.

2024-02-02 23:54 UTC, marcaaron commented
Looking at @iwiznia's comment and how much of a struggle this PR has been. Should we maybe pause?

If we can get rid of the `isTranslated` requirement then maybe we would end up with far fewer changes (and probably less conflicts... which seems to be at least one contributing factor to the delays here).

It sounds like we implemented a very convoluted solution to handle translated server error messages (I thought we decided to _not_ translate those for now - but unsure when that changed).

I really did not anticipate these changes would touch so many files or take this long to fix 😄

So, maybe we should cut our losses on this one and raise a PR that does this instead:

- Remove the `translateIfPhraseKey()` method
- Use `translate()` directly
- In `translate()` if we do not find the phrase key then:
- Log an ensure bugbot alert if on staging or production
- Assume the phrase is not supposed to be translated and show whatever we sent the user
- Throw error on dev (so we can avoid this ever getting to staging)

?

@blazejkustra @mountiny since you all implemented the `MISSING_TRANSLATION` stuff as part of [this issue](https://github.com/Expensify/App/issues/27759) can you help us understand what would it take to unwind all this complexity? Can someone either validate the above proposal or create a new one to get this back on the right track?

2024-02-05 10:01 UTC, mountiny commented
@marcaaron The proposed plan sounds good to me. 

> It sounds like we implemented a very convoluted solution to handle translated server error messages (I thought we decided to not translate those for now - but unsure when that changed).

The core idea behind this was mainly stemming from going through the Violations doc, where we wanted to also translate the violations in the production. We **never** wanted to translate in server, just to be clear. But this could raise a problem where we are sending the translation key from the server for some violation and it might not exist in the app.

Then showing the MISSING TRANSLATION would allow us internally catch any of these issues way earlier.

However, what we did not expect is that there was already a myriad of places where the translate method has been used wrong (passing a full error message to translate method where we expect a key for example) so instead of this showing rarely such that we can address each instance easily, this ended up showing to internal users in many cases leading to confusion. 

____

So I would say your proposed solution to Log an issue is good and we should also try to translate anything we can at its "root". So we are always passing already translated string (if it can be translated) and no component then has to guess if the incoming string is key for translation or already translated phrase.

2024-02-05 19:22 UTC, marcaaron commented
Thanks for the feedback here (@blazejkustra sorry for that distraction 😄). 

Let's proceed as originally planned for now then. @tienifr Can you fix the conflicts? Let's get this one merged and do a follow up to see the best way to remove `translateIfPhraseKey()`? Sound good?

2024-02-07 17:11 UTC, mallenexpensify commented
What's the next step to get this merged?

2024-02-07 17:13 UTC, situchan commented
@tienifr still many cases are missing in Tests step. What I pointed out was just hard to test. Please also add remaining what I didn't mention.

2024-02-08 05:07 UTC, situchan commented
@tienifr please check [slack discussion](https://expensify.slack.com/archives/C06HA3SG76K/p1707333402414459) in case you missed.

2024-02-08 18:50 UTC, marcaaron commented
>though I don't think that's neccessary because those changes are not platfomr-dependent

Sorry, that's not what the checklist is asking for. We expect everyone to test on all platforms unless the change _is_ platform-dependent e.g. something that only affects Android is an exception and can be tested on Android exclusively.

2024-02-08 19:23 UTC, marcaaron approved these changes

2024-02-08 19:30 UTC, situchan commented
### Test Result

<img width="335" alt="1-zip-hint" src="https://github.com/Expensify/App/assets/108292595/c224c2e4-8a4c-47c9-8a69-e2439b1cc4d0">
<img width="335" alt="2-avatar-upload" src="https://github.com/Expensify/App/assets/108292595/ed35446e-e3ff-4b77-ad97-e8f05315dd9c">
<img width="335" alt="3-distance-dup" src="https://github.com/Expensify/App/assets/108292595/0666161f-0c19-4a91-844c-14e1e1c00f74">
<img width="335" alt="4-receipt-upload" src="https://github.com/Expensify/App/assets/108292595/c00a4379-11da-415a-8fe1-aa58af64e44e">
<img width="330" alt="5-request-confirm" src="https://github.com/Expensify/App/assets/108292595/2b73a41f-9677-4e82-a356-78c2d3a0ff65">
<img width="330" alt="6-offline-feedback" src="https://github.com/Expensify/App/assets/108292595/742db455-f0c9-4591-8e19-b8224a320bbf">
<img width="330" alt="7-search-exceed" src="https://github.com/Expensify/App/assets/108292595/7e2dfeb0-aaec-474b-8df0-8653b78486df">
<img width="330" alt="8-pdf-password" src="https://github.com/Expensify/App/assets/108292595/76f43920-92b8-4a79-bb4a-f6b85c2b18ae">
<img width="330" alt="9-time-picker" src="https://github.com/Expensify/App/assets/108292595/ec8f4cc0-67a4-4fc5-99b0-47b9b1d6f60f">
<img width="330" alt="10-search-offline" src="https://github.com/Expensify/App/assets/108292595/e3fd4475-e967-4e10-bc73-872d2fa2ec8c">
<img width="330" alt="11-vba1" src="https://github.com/Expensify/App/assets/108292595/52f544da-a3c0-49c0-b80d-b62a32f594f5">
<img width="330" alt="12-vba2" src="https://github.com/Expensify/App/assets/108292595/224b1db1-d8df-4a94-aa28-23db9902937d">
<img width="330" alt="13-amount-input" src="https://github.com/Expensify/App/assets/108292595/53c3d49b-840b-4b0f-af0a-86067419afea">
<img width="330" alt="14-participant-selector" src="https://github.com/Expensify/App/assets/108292595/5a1da695-fe10-4211-9d7b-ee7daf32d295">
<img width="330" alt="15-contact-methods" src="https://github.com/Expensify/App/assets/108292595/80ad77da-b492-436c-aa96-4862fddd09d0">
<img width="330" alt="16-status-clear" src="https://github.com/Expensify/App/assets/108292595/f4f84f31-f2e7-4bc0-871a-a3c65d8474f6">
<img width="330" alt="17-tfa-code" src="https://github.com/Expensify/App/assets/108292595/19154d5e-f538-4be3-a5e6-34ea74db7873">
<img width="330" alt="18-debit-card" src="https://github.com/Expensify/App/assets/108292595/dfe769ca-0647-44e6-aedb-d9b21e4d1515">
<img width="330" alt="19-new-task" src="https://github.com/Expensify/App/assets/108292595/aebb12d0-712a-413e-bfc8-1f4f34658850">
<img width="330" alt="20-task-share" src="https://github.com/Expensify/App/assets/108292595/23ce4c9e-ac0b-4b41-b6bb-b82dcb052ad6">
<img width="330" alt="21-members-primary" src="https://github.com/Expensify/App/assets/108292595/02983361-0241-4a75-99fd-d21336e13085">

2024-02-08 19:33 UTC, NikkiWines commented
> What would this error look like? Could you give an example?

There are a number of different errors that could be returned but here's an example of one: 

![image](https://github.com/Expensify/App/assets/16747822/c1559153-481d-4ce0-9b5c-c178961cea51)

2024-02-08 19:49 UTC, merged

2024-02-08 19:53 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-02-12 14:19 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7872745855) to staging by https://github.com/marcaaron in version: 1.4.40-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|failure ❌

2024-02-13 18:25 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7890953833) to production by https://github.com/mountiny in version: 1.4.40-5 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|failure ❌