Reopened/Fix: User experienced big delay when posting the messages
Expensify/App pull request #30605
Opened 2023-10-30 19:19 UTC by waterim

### Details

This PR is about to add a skew to Onyx dates for actions
### Fixed Issues

$ https://github.com/Expensify/App/issues/21490
PROPOSAL: $ https://github.com/Expensify/App/issues/21490#issuecomment-1697412148

### Tests

Test steps for Web and mobile platforms, this change doesn't affect desktop
1. Change local time to be 30 seconds behind
2. Login to the app
3. Go to some report
4. Try to type 2-3 messages in a row
5. Messages must be in correct order

- [x] Verify that no errors appear in the JS console

### Offline tests

N/A automated tests

### QA Steps

Same as tests

- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [x] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable [...]

2023-11-02 10:57 UTC, situchan commented
I applied changes from this PR locally. I will see if there's any unexpected behavior for next few days.

2023-11-02 11:18 UTC, situchan commented
Also, I have ever reproduced [this weird bug](https://github.com/Expensify/App/issues/28656#issuecomment-1743998927) but not found clear repro step yet.


<img width="517" alt="Screenshot 2023-11-02 at 5 17 09 PM" src="https://github.com/Expensify/App/assets/108292595/649aac47-9f5b-45bd-b482-db0e0962d390">

2023-11-02 11:26 UTC, situchan commented
So far I am not able to reproduce any of issues above.
@waterim if same to you, I will ask internally to generate QR build and perform regression test.
Please let me know.

2023-11-02 12:33 UTC, waterim commented
I tried, but Im not able to reproduce them.. :(

2023-11-02 12:34 UTC, situchan commented
@mountiny can you please generate QR build?

2023-11-02 12:34 UTC, situchan commented
@waterim please pull main

2023-11-02 13:01 UTC, mountiny commented
running

2023-11-02 13:28 UTC, OSBotify commented
:test_tube::test_tube: Use the links below to test this adhoc build on Android, iOS, Desktop, and Web. Happy testing! :test_tube::test_tube:
| Android :robot:  | iOS :apple: |
| ------------- | ------------- |
| https://ad-hoc-expensify-cash.s3.amazonaws.com/android/30605/index.html  | https://ad-hoc-expensify-cash.s3.amazonaws.com/ios/30605/index.html  |
| ![Android](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://ad-hoc-expensify-cash.s3.amazonaws.com/android/30605/index.html)  | ![iOS](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://ad-hoc-expensify-cash.s3.amazonaws.com/ios/30605/index.html)  |
| Desktop :computer: | Web :spider_web: |
| https://ad-hoc-expensify-cash.s3.amazonaws.com/desktop/30605/NewExpensify.dmg  | https://30605.pr-testing.expensify.com  |
| ![Desktop](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://ad-hoc-expensify-cash.s3.amazonaws.com/desktop/30605/NewExpensify.dmg)  | ![Web](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://30605.pr-testing.expensify.com)  |

2023-11-02 14:02 UTC, situchan commented
@mountiny can you please test this branch and confirm https://github.com/Expensify/App/issues/28649 is still reproducible? As it was reported by you.

2023-11-02 14:34 UTC, mountiny commented
Unfortunately I am still seeing delays
https://github.com/Expensify/App/assets/36083550/fcf1db94-97d3-4162-a95a-d95efed039d5

2023-11-02 14:35 UTC, waterim commented
Super weird

2023-11-02 14:37 UTC, situchan commented
Might be related to local time. @mountiny are you currently synced with internet time? (no 1ms diff)

2023-11-02 14:40 UTC, mountiny commented
> are you currently synced with internet time? (no 1ms diff)

Idk but I dont think this should be something we should expect from our customers, we should accommodate for that

2023-11-02 14:42 UTC, waterim commented
After merging main to this PR Im getting this error when trying to "npm run web' 
<img width="1045" alt="image" src="https://github.com/Expensify/App/assets/39777589/edf44220-ad91-46c8-b1ce-e49836793b7e">
@situchan @mountiny  Do you know how to fix it? (same on main as well)

2023-11-02 14:45 UTC, situchan commented
@waterim no issue on `npm run web`. Did you `npm i`?

2023-11-02 14:45 UTC, waterim commented
yes, did install, tried on older branches, works fine, but main doesnt work for some reason, will try to remove node.modules

2023-11-02 15:08 UTC, waterim commented
@mountiny Can you please try to redeploy this PR?
(locally we can't reproduce this issue)

2023-11-02 15:16 UTC, mountiny commented
Triggered again

2023-11-02 15:40 UTC, waterim commented
Wow, it fixed  :D
@mountiny @situchan

2023-11-02 15:43 UTC, situchan commented
> Wow, it fixed :D @mountiny @situchan

@waterim so you reproduced before https://github.com/Expensify/App/pull/30605/commits/fbe9c2836315fc74b4170c345c32efe66a8d03bd and not reproduced after https://github.com/Expensify/App/pull/30605/commits/fbe9c2836315fc74b4170c345c32efe66a8d03bd?

2023-11-02 15:44 UTC, OSBotify commented
:test_tube::test_tube: Use the links below to test this adhoc build on Android, iOS, Desktop, and Web. Happy testing! :test_tube::test_tube:
| Android :robot:  | iOS :apple: |
| ------------- | ------------- |
| https://ad-hoc-expensify-cash.s3.amazonaws.com/android/30605/index.html  | https://ad-hoc-expensify-cash.s3.amazonaws.com/ios/30605/index.html  |
| ![Android](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://ad-hoc-expensify-cash.s3.amazonaws.com/android/30605/index.html)  | ![iOS](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://ad-hoc-expensify-cash.s3.amazonaws.com/ios/30605/index.html)  |
| Desktop :computer: | Web :spider_web: |
| https://ad-hoc-expensify-cash.s3.amazonaws.com/desktop/30605/NewExpensify.dmg  | https://30605.pr-testing.expensify.com  |
| ![Desktop](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://ad-hoc-expensify-cash.s3.amazonaws.com/desktop/30605/NewExpensify.dmg)  | ![Web](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://30605.pr-testing.expensify.com)  |

2023-11-03 13:39 UTC, waterim commented
@situchan I was able to reproduce on the first PR deploy and after my fix I can't reproduce it on the deploy.
@mountiny Can you please check it too?

2023-11-06 11:44 UTC, waterim commented
@mountiny @situchan 
Friendly bump

2023-11-06 11:46 UTC, situchan commented
Still not able to reproduce issues mentioned in https://github.com/Expensify/App/pull/30605#issuecomment-1790532477.
But still we cannot merge this without confirming fixes.
Shall we ask QA team to do regression test?

2023-11-06 12:15 UTC, waterim commented
@mountiny Do you able to reproduce this one?
After my fix I can't reproduce it on the newest PR deploy

2023-11-07 14:54 UTC, mountiny commented
I cannot repro now

@waterim can you merge in main? seems like the reassure tests are failing

2023-11-07 14:55 UTC, waterim commented
@mountiny Nice to hear!
Out of office now, will merge in 1-2 hours, thank you!

2023-11-07 14:58 UTC, situchan commented
We're not happy yet as still [another 2 potential regressions](https://github.com/Expensify/App/pull/30605#issuecomment-1790532477) which were not reproducible by us

2023-11-07 19:36 UTC, waterim commented
@mountiny Merged

2023-11-07 21:47 UTC, OSBotify commented
:test_tube::test_tube: Use the links below to test this adhoc build on Android, iOS, Desktop, and Web. Happy testing! :test_tube::test_tube:
| Android :robot:  | iOS :apple: |
| ------------- | ------------- |
| https://ad-hoc-expensify-cash.s3.amazonaws.com/android/30605/index.html  | https://ad-hoc-expensify-cash.s3.amazonaws.com/ios/30605/index.html  |
| ![Android](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://ad-hoc-expensify-cash.s3.amazonaws.com/android/30605/index.html)  | ![iOS](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://ad-hoc-expensify-cash.s3.amazonaws.com/ios/30605/index.html)  |
| Desktop :computer: | Web :spider_web: |
| ❌ FAILED ❌  | https://30605.pr-testing.expensify.com  |
| The QR code can't be generated, because the Desktop build failed  | ![Web](https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://30605.pr-testing.expensify.com)  |

2023-11-08 15:34 UTC, mountiny commented
Asked QA to test

2023-11-08 16:37 UTC, mountiny commented
they could not reproduce so I think we are good to go then!

2023-11-08 16:39 UTC, mountiny approved these changes, later dismissed
one NAB @situchan could you please complete the checklist

2023-11-08 16:39 UTC, mountiny commented on src/libs/HttpUtils.js
> +const regex = /[?&]command=([^&]+)/;
Lets use a bit more specific name for this regex

2023-11-08 16:39 UTC, mountiny commented on src/libs/HttpUtils.js
> +const regex = /[?&]command=([^&]+)/;
```suggestion
const APICommandRegex = /[?&]command=([^&]+)/;
```

2023-11-08 16:56 UTC, mountiny commented
@waterim @situchan could you check this one out if its specific for this PR, feel like it should not

2023-11-08 16:56 UTC, mountiny commented
@waterim @situchan could you check this one out if its specific for this PR, feel like it should nothttps://github.com/Expensify/App/issues/28656#issuecomment-1802273863

2023-11-08 16:59 UTC, situchan commented
I am not able to reproduce on this branch merged with latest main locally

https://github.com/Expensify/App/assets/108292595/4431a9ef-e822-411c-9e91-e4c93a3cd5e4

2023-11-08 17:06 UTC, situchan commented
This is expected, right? I adjusted time 1 hr behind


https://github.com/Expensify/App/assets/108292595/953e4104-27c8-4a96-88c4-b329c0081cf2

2023-11-09 14:28 UTC, situchan commented
@waterim bump on https://github.com/Expensify/App/pull/30605#issuecomment-1802307261.
So what I am concerned is app should be aware of dynamic time change without refresh

2023-11-13 17:06 UTC, situchan commented
> @waterim bump on [#30605 (comment)](https://github.com/Expensify/App/pull/30605#issuecomment-1802307261). So what I am concerned is app should be aware of dynamic time change without refresh.


So you meant no need to care about this, right?

2023-11-13 17:07 UTC, situchan commented
Let's fix job1 failure. And will do checklist

2023-11-13 17:08 UTC, waterim commented
@situchan I think so, this solution was an idea from David Barett

2023-11-13 17:33 UTC, waterim commented
@situchan fixed

2023-11-15 14:06 UTC, waterim commented
@situchan friendly bump :)

2023-11-15 16:17 UTC, situchan commented
@waterim I managed reproduce on desktop app. Other platforms work fine.


https://github.com/Expensify/App/assets/108292595/61f29dab-7054-4bea-a454-2f4e25ade6fe


https://github.com/Expensify/App/assets/108292595/e4ba4472-033a-41f9-9461-e6db6a2027a3

2023-11-17 14:59 UTC, waterim commented
Hello guys, I will be OOO on Monday and Thuesday. 
Will continue working on Wednesday!

2023-11-29 14:10 UTC, waterim commented
@situchan I found an issue
Web is returning those headers:
<img width="244" alt="image" src="https://github.com/Expensify/App/assets/39777589/f7652e62-2a53-4512-a749-53e75b3ea95e">
While desktop only these:
<img width="313" alt="image" src="https://github.com/Expensify/App/assets/39777589/cf0f3236-7d2a-41c1-bbbe-2eb8d078a02b">
And it doesnt have any date inside

2023-11-29 14:48 UTC, waterim commented
Okay, yes, the main issue here is that electron fetch probably is not returning all headers and thats why I don't have an access to them at all :(

2023-11-29 14:51 UTC, waterim commented
Can we try to test it on a deploy? @situchan

2023-11-29 14:55 UTC, situchan commented
> Can we try to test it on a deploy? @situchan

It header isn't returning date, at least it should not break anything on main when user local time is correct

2023-11-29 14:58 UTC, waterim commented
@situchan Yes, I added a verification to check if it exists or not

2023-11-29 15:00 UTC, situchan commented
@waterim did you also test on QR release build?

2023-11-30 14:11 UTC, mountiny commented
I am running a test build where we can see it on desktop hopefully, the bug is not really acceptable at least from what I can see from the video

2023-12-01 14:02 UTC, waterim commented
@mountiny Access denied for desktop one :(

2023-12-04 15:47 UTC, mountiny commented
@waterim we are expereincing issue with the build, I think we can wait for that to be resolved

2024-01-08 16:43 UTC, waterim commented
@situchan @mountiny Pushed latest changes

2024-01-09 00:33 UTC, mountiny commented
Running the build, I am still kinda confused if we need this change

2024-01-09 12:50 UTC, waterim commented
Okay, looks like delay appears on the desktop app with changed time, but works fine with default auto-time. With all other platforms it works good. 
Don't know exactly why electron fetch doesn't have all headers to be honest.

What do you think guys regarding this?
The only issue is on desktop with disabled auto datetime, thats 0.0001% of users

2024-01-09 12:57 UTC, situchan commented
> The only issue is on desktop with disabled auto datetime, thats 0.0001% of users

Also, this is not a regression but production behavior. So desktop isn't affected by this PR.

In summary:
desktop: doesn't fix https://github.com/Expensify/App/issues/21490 but same as production
web: fix https://github.com/Expensify/App/issues/21490

As long as this PR doesn't cause regression, I am fine to proceed. Also there's possibility that production desktop app might work fine.

2024-01-09 21:10 UTC, mountiny commented
@situchan to confirm, no new regression, issue fixed on web and whatever the issue is on desktop that is already in production?

If so could you approve this PR please?

@waterim could you update the test steps to clearly state what platform should be tested for this?

2024-01-09 21:11 UTC, situchan approved these changes
> @situchan to confirm, no new regression, issue fixed on web and whatever the issue is on desktop that is already in production?

right

> If so could you approve this PR please?

2024-01-09 21:16 UTC, mountiny commented
Oh wow I am not even assigned to the linked issue 😂 

look at that

2024-01-09 21:17 UTC, situchan commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<d [...]

2024-01-09 21:18 UTC, mountiny requested changes

2024-01-09 21:18 UTC, mountiny commented on src/libs/HttpUtils.ts
> +        })
I think it would be great to leave a comment @waterim about why we are even doing this

2024-01-09 21:20 UTC, situchan commented
> Oh wow I am not even assigned to the linked issue 😂
> 
> look at that

Ah, the reason why I tagged you first time is that you reported https://github.com/Expensify/App/issues/28649 which was not reproducible by us

2024-01-10 17:37 UTC, waterim commented
Updated everything @mountiny

2024-01-10 18:17 UTC, mountiny approved these changes
Alright, thanks! All yours @nkuoch

2024-01-11 10:11 UTC, nkuoch approved these changes

2024-01-11 10:13 UTC, merged

2024-01-11 10:18 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-01-15 11:56 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7528228168) to staging by https://github.com/nkuoch in version: 1.4.25-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅

2024-01-17 01:14 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7549592426) to production by https://github.com/mountiny in version: 1.4.25-10 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅