fix: correctly pass transactions to LHN
Expensify/App pull request #31007
Opened 2023-11-07 15:40 UTC by TMisiukiewicz

### Details

### Fixed Issues

$ 
PROPOSAL: 

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbo [...]

2023-11-07 19:27 UTC, situchan commented on src/components/LHNOptionsList/OptionRowLHNData.js
> +    transaction,
`transaction` is missing propTypes and defaultProps

2023-11-07 19:33 UTC, situchan requested changes

2023-11-07 19:33 UTC, situchan commented on src/components/LHNOptionsList/LHNOptionsList.js
> +    transactions: transactionPropTypes,
This is not correct. `transactions` is object

2023-11-07 19:33 UTC, situchan commented on src/components/LHNOptionsList/LHNOptionsList.js
> +    reportActions: PropTypes.shape(reportActionPropTypes),
This is not correct. `reportActions` is object.

2023-11-07 19:36 UTC, situchan commented
Also, pull main when ready for review

2023-11-07 20:18 UTC, mountiny commented on src/components/LHNOptionsList/LHNOptionsList.js
> +            const itemTransactions = lodashGet(itemParentReportActions, [itemFullReport.parentReportActionID, 'originalMessage', 'IOUTransactionID'], '');
This is always just a single transaction linked to the report action
```suggestion
            const itemTransaction = lodashGet(itemParentReportAction, [itemFullReport.parentReportActionID, 'originalMessage', 'IOUTransactionID'], '');
```

2023-11-07 20:18 UTC, mountiny commented on src/components/LHNOptionsList/LHNOptionsList.js
> +            const itemParentReportActions = reportActions[`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${itemFullReport.parentReportID}`] || {};
This is always just a single report action
```suggestion
            const itemParentReportAction = reportActions[`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${itemFullReport.parentReportID}`] || {};
```

2023-11-07 20:18 UTC, mountiny commented on src/components/LHNOptionsList/LHNOptionsList.js
> +            const transactionsList = itemTransactions ? transactions[`${ONYXKEYS.COLLECTION.TRANSACTION}${itemTransactions}`] : transactions;
I am not sure if we want to pass the entire collection of transactions in this case if itemTransaction would not be found
```suggestion
            const transactionsList = itemTransaction ? transactions[`${ONYXKEYS.COLLECTION.TRANSACTION}${itemTransaction}`] : transactions;
```

2023-11-08 08:57 UTC, TMisiukiewicz commented
@situchan @mountiny thanks for your reviews. I addressed all the comments

2023-11-08 10:50 UTC, situchan commented on src/components/LHNOptionsList/LHNOptionsList.js
> +                    parentReportActions={itemParentReportAction}
`parentReportActions` should also be changed in OptionRowLHNData

2023-11-08 10:51 UTC, situchan commented on src/components/LHNOptionsList/LHNOptionsList.js
> +                    parentReportActions={itemParentReportAction}
So remove this line and directly use `parentReportAction` from prop

https://github.com/Expensify/App/blob/4f9210729a368e16be965d1607a63559189a7e8c/src/components/LHNOptionsList/OptionRowLHNData.js#L78

2023-11-08 11:24 UTC, TMisiukiewicz commented
@situchan thank you, could you re-review please when you have a moment?

2023-11-08 11:29 UTC, situchan commented on src/components/LHNOptionsList/OptionRowLHNData.js
>      /** The actions from the parent report */
```suggestion
    /** The action from the parent report */
```

2023-11-08 11:39 UTC, TMisiukiewicz commented on src/components/LHNOptionsList/OptionRowLHNData.js
>      /** The actions from the parent report */
good eye! done ✅

2023-11-08 11:47 UTC, situchan requested changes

2023-11-08 11:47 UTC, situchan commented on src/components/LHNOptionsList/LHNOptionsList.js
> +            const transactionID = lodashGet(itemParentReportAction, [itemFullReport.parentReportActionID, 'originalMessage', 'IOUTransactionID'], '');
```suggestion
            const transactionID = lodashGet(itemParentReportAction, ['originalMessage', 'IOUTransactionID'], '');
```

Had to watch this with 🦅's eye 😄

2023-11-08 11:50 UTC, situchan commented
Do you think `transactionID` is enough to satisfy this comment? I am concerned about removing `transaction` from dependency

<img width="957" alt="Screenshot 2023-11-08" src="https://github.com/Expensify/App/assets/108292595/cbcaf247-f05f-409f-8dcc-626bf87a85a8">

2023-11-08 12:02 UTC, TMisiukiewicz commented on src/components/LHNOptionsList/LHNOptionsList.js
> +            const transactionID = lodashGet(itemParentReportAction, [itemFullReport.parentReportActionID, 'originalMessage', 'IOUTransactionID'], '');
oh wow, the 🦅 eye indeed 🤯

2023-11-08 12:21 UTC, TMisiukiewicz commented
@situchan good point, I'd say it's safer to bring back whole transaction as a dependency. I reverted changes to use `transaction`.

2023-11-08 12:36 UTC, situchan commented
ok scan transaction title is updated in LHN

https://github.com/Expensify/App/assets/108292595/38a6071b-5d7a-4e66-ae31-8e7388cc64db

2023-11-08 12:47 UTC, situchan commented
Console errors from bad Onyx data. Not sure if it's coming from backend or Onyx but out of scope anyway

![Simulator Screenshot](https://github.com/Expensify/App/assets/108292595/e31ef073-b9b2-41a8-846d-6765bd06bc73)


![Simulator Screenshot](https://github.com/Expensify/App/assets/108292595/e58fa38f-77c4-4a47-9e57-8e9d4bda37fe)

2023-11-08 12:58 UTC, situchan approved these changes

2023-11-08 14:29 UTC, mountiny approved these changes
Thanks for the fix

2023-11-08 14:31 UTC, merged

2023-11-08 14:32 UTC, mountiny commented
The failing reasssure test was because of different changes in main, none of the changes in this PR influence the ReportScreens performance

2023-11-08 14:36 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-11-08 15:20 UTC, OSBotify commented
🚀 [Cherry-picked](https://github.com/Expensify/App/actions/runs/6799861129) to staging by https://github.com/mountiny in version: 1.3.96-7 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

@Expensify/applauseleads please QA this PR and check it off on the [deploy checklist](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3AStagingDeployCash) if it passes.

2023-11-09 22:45 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6818231417) to production by https://github.com/puneetlath in version: 1.3.96-15 🚀

platform | result
---|---
🤖 android 🤖|failure ❌
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-11-10 16:01 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6826740157) to staging by https://github.com/mountiny in version: 1.3.98-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-11-14 21:54 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6869834824) to production by https://github.com/roryabraham in version: 1.3.98-5 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅