[TS migration] Migrate 'Tooltip' component to TypeScript
Expensify/App pull request #31544
Opened 2023-11-20 12:13 UTC by kosmydel

### Details

### Fixed Issues

$ 
PROPOSAL: 

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2023-11-21 11:13 UTC, kosmydel commented on src/components/Tooltip/BaseTooltip.tsx
> +                    shiftVertical={shiftVertical}
We have to add a new `result` function which returns a number instead of a string.

2023-11-23 15:24 UTC, blazejkustra requested changes

2023-11-23 15:24 UTC, blazejkustra commented on src/components/DisplayNames/DisplayNamesTooltipItem.tsx
> +    const tooltipIndexBridge = useMemo(() => getTooltipShiftX(index), [getTooltipShiftX, index]);
Why was it changed to useMemo?

2023-11-23 15:24 UTC, blazejkustra commented on src/components/Pressable/PressableWithDelayToggle.tsx
> +                    // containerStyles={[styles.flexRow]}
Any clue if it's necessary?

2023-11-23 15:24 UTC, blazejkustra commented on src/components/Tooltip/BaseTooltip.native.tsx
> +}
```suggestion
import ChildrenProps from '@src/types/utils/ChildrenProps';

function Tooltip({children}: ChildrenProps) {
    return children;
}
```

2023-11-23 15:24 UTC, blazejkustra commented on src/components/Tooltip/BaseTooltip.tsx
> +import _ from 'lodash';
Let's get rid of lodash

2023-11-23 15:24 UTC, blazejkustra commented on src/components/Tooltip/BaseTooltip.tsx
>      for (let i = 0; i < bbs.length; i++) {
Did you try to use for of here?

2023-11-23 15:24 UTC, blazejkustra commented on src/components/Tooltip/types.ts
> +export type {TooltipProps, TooltipExtendedProps};
```suggestion
export default TooltipProps;
export type {TooltipExtendedProps};
```

2023-11-23 15:24 UTC, blazejkustra commented on src/components/Tooltip/types.ts
> +    tooltipRef?: RefObject<BoundsObserver> | null;
Let's remove `tooltipRef` and instead use `forwardedRef` (second argument in a component).

2023-11-23 15:24 UTC, blazejkustra commented on src/components/Tooltip/types.ts
> +    children: ReactElement;
It should be `ReactNode`, or better use `ChildrenProps`:
```ts
import ChildrenProps from '@src/types/utils/ChildrenProps';
```

2023-11-23 15:24 UTC, blazejkustra commented on src/types/utils/callOrReturn.ts
> +}
```suggestion
function callOrReturn<TValue>(value: TValue | (() => TValue)): TValue {
    if (typeof value === 'function') {
        return (value as () => TValue)();
    }

    return value;
}
```

2023-11-23 15:24 UTC, blazejkustra commented on src/styles/getTooltipStyles.ts
> +    let scale = new Animated.Value(1);
Please test it @kosmydel 😄

2023-11-23 15:24 UTC, blazejkustra commented on src/components/Tooltip/BaseTooltip.tsx
> +    renderTooltipContent = undefined,
```suggestion
    renderTooltipContent,
```

2023-11-23 15:24 UTC, blazejkustra commented on src/components/Tooltip/TooltipRenderedOnPageBody.tsx
> +    renderTooltipContent = undefined,
```suggestion
    renderTooltipContent,
```

2023-11-24 09:14 UTC, BartoszGrajdek commented on src/components/Tooltip/PopoverAnchorTooltip.tsx
> +        const tooltipNode = tooltipRef.current ? tooltipRef.current['_childNode'] : null;
Maybe let's do it like this? You need to check if the logic is the same though
```suggestion
        const tooltipNode = tooltipRef.current?.['_childNode'] ?? null;
```

2023-11-24 09:14 UTC, BartoszGrajdek commented on src/components/Tooltip/BaseTooltip.tsx
> +                    key={[text, ...renderTooltipContentKey, preferredLocale].join('-')}
Why has this changed?

2023-11-24 09:14 UTC, BartoszGrajdek commented on src/components/Tooltip/BaseTooltip.tsx
>          initialMousePosition.current = {x: e.clientX, y: e.clientY};
Can we do this? You should test it first though
```suggestion
    const updateTargetAndMousePosition = useCallback((e: MouseEvent) => {
        if (e.currentTarget instanceof HTMLElement) {
            target.current = e.currentTarget;
            initialMousePosition.current = {x: e.clientX, y: e.clientY};
        }
```

2023-11-27 11:38 UTC, blazejkustra approved these changes

2023-11-27 11:38 UTC, blazejkustra commented on src/components/Tooltip/TooltipRenderedOnPageBody.tsx
> +    shiftHorizontal: number;
Should be required?

2023-11-27 11:38 UTC, blazejkustra commented on src/components/Tooltip/TooltipRenderedOnPageBody.tsx
> +    shiftVertical: number;
Should it be required?

2023-11-27 12:30 UTC, BartoszGrajdek reviewed
Let's also move BaseTooltip files into a separate folder `src/components/Tooltip/BaseTooltip/....`

2023-11-27 16:07 UTC, blazejkustra approved these changes

2023-11-27 18:14 UTC, BartoszGrajdek approved these changes
LGTM!

2023-12-01 13:09 UTC, blazejkustra commented on src/components/Pressable/PressableWithDelayToggle.tsx
> -                    containerStyles={[styles.flexRow]}
https://github.com/Expensify/App/pull/31544#discussion_r1405891178

2023-12-04 08:59 UTC, kosmydel commented on src/components/Tooltip/BaseTooltip/index.tsx
> +    const target = useRef<HTMLElement | null>(null);
Without it, there is this type of error:

<img width="789" alt="Screenshot 2023-12-04 at 09 58 10" src="https://github.com/Expensify/App/assets/104823336/3ba29969-9d05-4c54-91f9-dd194119e632">

2023-12-04 09:02 UTC, kosmydel commented on src/components/Tooltip/BaseTooltip/index.tsx
> +                    shiftVertical={callOrReturn(shiftVertical)}
`Str.result` is only for strings, while `callOrReturn` is generic.

2023-12-04 10:59 UTC, blazejkustra approved these changes

2023-12-04 11:09 UTC, fabioh8010 approved these changes

2023-12-05 17:01 UTC, Santhosh-Sellavel commented
Requested for new C+ plus, @allroundexperts will take over this.

2023-12-05 17:15 UTC, blazejkustra commented
@kosmydel Please resolve conflicts 😄

2023-12-05 17:21 UTC, blazejkustra commented
@allroundexperts is already responsible for two quite big TS migration PRs:
- [Report](https://github.com/Expensify/App/pull/28730)
- [AppNavigator](https://github.com/Expensify/App/pull/29157#issuecomment-1840852914)

(+ and this one)

Please take this into consideration before tackling all these at once 😅

2023-12-05 17:22 UTC, allroundexperts commented
Have you listed these priority wise?

2023-12-05 19:04 UTC, blazejkustra commented
@allroundexperts priority-wise:
1. AppNavigator
2. Tooltip
3. Report

2023-12-06 00:04 UTC, allroundexperts commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->
https://github.com/Expensify/App/assets/30054992/72cbbdd2-5d32-4822-9c48-bf66c863fb8f

</details>

<details>
<summary>Android: mWeb Chrome</summary>

<!-- add screenshots or videos here -->
https://github.com/Expensify/App/assets/30054992/494a71de-d1bf-4f2b-be40-aa6f60a3c30c

</details>

<details>
<summary>iOS: Native</summary>

<!-- add screenshots or videos here -->
https://github.com/Expensify/App/assets/30054992/45826261-fef3 [...]

2023-12-06 00:05 UTC, allroundexperts commented
Testing well. Waiting for the conflicts to be resolved before final approval.

2023-12-06 09:44 UTC, kosmydel commented
Hey, I pulled the main, resolved conflicts, and had to make [fix warning on native](https://github.com/Expensify/App/pull/31544/commits/203cd81b0dd64b1d81661590c4058d4ff66b8c8c) on native, as there was a warning during runtime (related to `forwardRef`, web version used is while native didn't).

cc @blazejkustra, @allroundexperts

2023-12-06 10:20 UTC, blazejkustra approved these changes

2023-12-06 18:39 UTC, allroundexperts approved these changes
Approving since this is catching conflicts so fast. This is testing well and should be good to merge!

2023-12-07 08:32 UTC, kosmydel commented
I've resolved conflicts, so it is ready to proceed.

2023-12-07 08:51 UTC, allroundexperts commented
🎀 👀 🎀

2023-12-07 08:52 UTC, allroundexperts approved these changes

2023-12-07 08:53 UTC, allroundexperts approved these changes
Got an internal engineer!

2023-12-08 11:29 UTC, kosmydel commented
I've resolved conflicts once again. cc @blazejkustra @allroundexperts

2023-12-08 11:33 UTC, blazejkustra approved these changes

2023-12-08 11:35 UTC, allroundexperts approved these changes

2023-12-08 11:41 UTC, mountiny commented
Gonna take it over here as its component with lots of conflicts to get it over the finish line

2023-12-08 11:45 UTC, mountiny approved these changes
Ok lets go, thank you for patience @kosmydel and testing thoroughly @allroundexperts

2023-12-08 11:45 UTC, mountiny commented on src/components/Tooltip/types.ts
> +    /** passes this down to Hoverable component to decide whether to handle the scroll behaviour to show hover once the scroll ends */
NAB
```suggestion
    /** Passes this down to Hoverable component to decide whether to handle the scroll behaviour to show hover once the scroll ends */
```

2023-12-08 11:46 UTC, merged

2023-12-08 11:50 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-12-13 11:09 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7194233901) to production by https://github.com/Julesssss in version: 1.4.11-25 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅