feat: HTML to Markdown parser integration
Expensify/App pull request #3229
Opened 2021-05-29 16:20 UTC by pranshuchittora

TODO merge this https://github.com/Expensify/expensify-common/pull/381 and then edit commit hash
### Details

A small step towards migration to markdown and deprecation of `text`

### Fixed Issues

Fixes #2847 

### Tests

### QA Steps

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-06-22 19:35 UTC, pranshuchittora commented
https://user-images.githubusercontent.com/32242596/122986338-f2750600-d3bc-11eb-8f84-99b182a2de1b.mov

2021-06-22 19:46 UTC, pranshuchittora commented
@roryabraham this PR is ready for review

2021-06-22 23:35 UTC, roryabraham reviewed
Thanks for this! Not much to review here, so looks good 👍 

However, before we can approve/merge, please update the description of this PR and include screen recordings for _all_ platforms.

2021-06-22 23:35 UTC, roryabraham commented on src/pages/home/report/ReportActionContextMenu.js
>      getActionText() {
Let's change the method description here to:

```
Gets the markdown version of the message in an action.
```

2021-06-22 23:49 UTC, roryabraham requested changes
Actually, I think we should make this change in `ReportActionItemMessageEdit` instead of `ReportActionContextMenu`, because this doesn't work in the case where you edit the previous message using the `Up` arrow key:

1. Send a multiline message
1. Press the `Up` arrow key
1. Observe that the draft message in the `ReportActionItemMessageEdit` does not appear in multiple lines.

2021-06-23 17:16 UTC, pranshuchittora commented
Hi @roryabraham I have updated the PR. Is this the correct approach, let me know for any changes.
Uploading Peek 2021-06-23 22-44.mp4…

2021-06-23 20:42 UTC, roryabraham requested changes
Not exactly correct – right now we're saving the draft message using the plain-text version of the message (i.e: `reportAction.message.text`). See the `getAction` function in `ReportActionContextMenu` [here](https://github.com/Expensify/Expensify.cash/blob/43bf806751d7643f8f9a005f19d0c77b73aba0fc/src/pages/home/report/ReportActionContextMenu.js#L122). Instead, I think we'll want to start passing the `reportAction.message.html` to `saveReportActionDraft`.

Once you've done that, the `draftMessage` prop of `ReportActionItemMessageEdit` will be html instead of text, and we shouldn't need the `reportAction` prop there. Then the only other change should be that we perform the HTML -> MD transform on the `draftMessage` prop of `ReportActionItemMessageEdit` in the constructor.

2021-06-24 15:03 UTC, pranshuchittora commented
I have updated the PR

2021-06-24 21:59 UTC, roryabraham requested changes

2021-06-24 21:59 UTC, roryabraham commented on src/libs/reportUtils.js
> +        && !isReportMessageAttachment(lodashGet(reportAction, ['message', 0, 'html'], ''));
Everything else looks good, but I don't think we need this change. When a reportAction is an image attachment, its `html` will contain an image tag. However, its `text` will just be `[Attachment]`.

2021-06-25 17:01 UTC, pranshuchittora commented
@roryabraham  I have updated all the required screen recordings

2021-06-25 20:42 UTC, roryabraham requested changes
Sorry, still have the one comment about making the comment correct.

2021-06-25 20:42 UTC, roryabraham commented on src/pages/home/report/ReportActionContextMenu.js
>      getActionText() {
Bump – this method doc is no longer accurate

2021-06-28 19:13 UTC, roryabraham approved these changes
Thanks, LGTM 👍

2021-07-01 16:19 UTC, pranshuchittora commented
@roryabraham can we merge this soon to avoid any merge conflicts.

2021-07-01 19:53 UTC, merged

2021-07-01 19:54 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-07-09 00:28 UTC, roryabraham commented
Unfortunately the deploy comments are not working right now. This was deployed to staging yesteday.