Fix inconsistent workspace tooltip
Expensify/App pull request #32325
Opened 2023-12-01 01:50 UTC by chie2727

### Details

Fix for archived workspace name in tooltip showing up as 'Unavailable workspace' while the workspace name in the header banner shows correctly

### Fixed Issues

$ https://github.com/Expensify/App/issues/31894
PROPOSAL: https://github.com/Expensify/App/issues/31894#issuecomment-1827540848

### Tests

1. Create a new workspace
2. In the new workspace send a message
3. Click 'Request money' and make a request
4. Delete the workspace
5. In the now archived workspace, go to the message sent earlier and click 'Reply in thread'
6. In the thread verify that the tooltip shows the correct workspace name

- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

1. Create a new workspace
2. In the new workspace send a message
3. Click 'Request money' and make a request
4. Delete the workspace
5. In the now archived workspace, go to the message sent earlier and click 'Reply in thread'
6. In the thread verify that the tooltip shows the correct workspace name
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://g [...]

2023-12-01 09:08 UTC, chie2727 commented
I have read the CLA Document and I hereby sign the CLA

2023-12-01 11:45 UTC, cubuspl42 commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/2590174/b1fc2293-6937-4af3-95cd-68e23feae217

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/2590174/173cad83-fbc8-42a2-a8e8-52b3febbab77

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/2590174/887544a6-1c1b-4e28-99f7-bab8124609cc

</details>

<details>
<summary>Desktop</summary>

<!-- add screenshots or videos here -->

</details> [...]

2023-12-01 11:45 UTC, jakub-trzebiatowski approved these changes
Looks good 👍

2023-12-01 15:52 UTC, nkuoch approved these changes, later dismissed

2023-12-12 10:45 UTC, cubuspl42 commented
@chie2727 Please fix the "Lint code" check

2023-12-12 10:50 UTC, cubuspl42 commented
I'm sorry for this situation.

C+s and internal engineers have multiple assignments. Issues sometimes fall out of the radar. Feel free to ping C+ every day during the C+ review phase, and during the internal engineer review phase (now) you can also directly ping the assigned internal engineer every two days or so.

Of course, ideally, this would never be necessary, and quite often it isn't.

2023-12-13 16:47 UTC, nkuoch commented
@chie2727 Please fix the "Lint code" check

2023-12-20 00:36 UTC, chie2727 commented
@nkuoch I've fixed the Lint Code check by moving getRootParentReport() up in the script. (I also moved up getParentReport() for ease of findability.)

2023-12-20 10:46 UTC, cubuspl42 commented
@chie2727 Please pay attention to the checks section and iterate as long as needed.

![image](https://github.com/Expensify/App/assets/2590174/dd687e7d-70cf-453f-ae09-d8967df48510)

2023-12-20 13:53 UTC, nkuoch commented
<img width="954" alt="image" src="https://github.com/Expensify/App/assets/2463975/768f7d4a-f50d-4350-8a28-fa8339bebdc4">

2023-12-21 00:42 UTC, chie2727 commented
@nkuoch @cubuspl42 
I've moved up the getReport() function as well. This should fix the second Lint Code check.

2023-12-21 11:36 UTC, cubuspl42 commented
@chie2727 

 The "PR Author Checklist" checklist is failing. Is it possible that the checklist template has changed in the meantime?

2023-12-26 00:25 UTC, chie2727 commented
@cubuspl42
That seems to have been the case..! I've updated the checklist now and the PR Author check is passing.

2023-12-27 10:28 UTC, cubuspl42 requested changes

2023-12-27 10:28 UTC, cubuspl42 commented on src/libs/ReportUtils.ts
> +     */
This comment is not placed above the lines it refers to

2023-12-27 10:28 UTC, cubuspl42 commented on src/libs/ReportUtils.ts
> +     * Using typical string concatenation here due to performance issues
Have you observed these performance issues?

2023-12-27 10:28 UTC, cubuspl42 commented on src/libs/ReportUtils.ts
> +    return allReports?.[`${ONYXKEYS.COLLECTION.REPORT}${report.parentReportID}`] ?? {};
Isn't this the `getReport` function, inlined?

2023-12-27 10:28 UTC, cubuspl42 commented on src/libs/ReportUtils.ts
> + * Uses recursion to iterate any depth of nested reports.
Function doc comments should not describe implementation details

2023-12-27 10:28 UTC, cubuspl42 commented on src/libs/ReportUtils.ts
> +function getRootParentReport(report: OnyxEntry<Report> | undefined | EmptyObject): OnyxEntry<Report> | EmptyObject {
Wouldn't `getRootAncestorReport` be a more appropriate name? "Parent" is always the _direct_ ancestor, so "root parent" is somewhat contradictive.

2023-12-27 10:28 UTC, cubuspl42 commented on src/libs/ReportUtils.ts
> + * Returns the root parentReport if the given report is nested.
I would suggest this description:

```
Returns the root ancestor of the given report, i.e. the parent of the parent of the parent (and so on...), which itself is parentless. If a report has no parent, it is its own root ancestor.
```

2023-12-27 10:28 UTC, cubuspl42 commented on src/libs/ReportUtils.ts
> +    // Returns the current report as the root report, because it does not have a parentReportID
I would nuke this comment, it is close to describing the code literally

2023-12-27 10:28 UTC, cubuspl42 commented on src/libs/ReportUtils.ts
> +    // Runs recursion to iterate a parent report
Again, this comment describes the code literally. It doesn't provide any insight, rationale, or context. I would remove it.

2023-12-28 03:48 UTC, chie2727 commented
@cubuspl42 
All of the in-code comments were not made by me - I simply moved the existing functions up the script in order to solve the previously occurring Lint Code checks.

2023-12-28 10:05 UTC, cubuspl42 commented
@chie2727 I'm sorry. I went through my queue and started commenting without noticing that you moved this stuff to satisfy the linter. We always handle multiple issues simultaneously and sometimes become victims of context switching. Also, I could be tired.

2023-12-28 12:39 UTC, cubuspl42 commented
@chie2727 I think you forgot to preserve the videos when you updated the checklist. You might find the links in the commit edit history.

2023-12-28 12:42 UTC, cubuspl42 commented
@chie2727 Next time, please fill in the "Screenshots/Videos" section. Please don't check off checkboxes without reading them.

2023-12-28 12:44 UTC, cubuspl42 commented
@chie2727 Please merge `main`

2023-12-28 12:48 UTC, cubuspl42 commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos

<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/2590174/e2802cd2-53dd-4bbc-a973-d9b787fb6656

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/2590174/173cad83-fbc8-42a2-a8e8-52b3febbab77

</details>

<details>
<summary>Mobile Web - Safa [...]

2023-12-28 12:49 UTC, cubuspl42 requested changes
@chie2727 Please merge `main`

2023-12-29 00:07 UTC, chie2727 commented
@cubuspl42 
I've just updated the Screenshots/Videos section. Will remember to do this early on next time!

The "PR Reviewer Checklist" seems to be failing due to missing checkboxes. I believe after it's been updated I'll be able to merge.

2023-12-29 08:59 UTC, cubuspl42 commented
@chie2727 Have you merged `main`? ([as per this request](https://github.com/Expensify/App/pull/32325#pullrequestreview-1798020378))

Merging `main` ensures that all lints are passing on the newest version of the code and reduces the risk of "breaking `main`".

2023-12-29 09:03 UTC, cubuspl42 commented
> The "PR Reviewer Checklist" seems to be failing due to missing checkboxes.

I think it just needs to re-run. I think it still processed the old checklist comment before I deleted it.

2023-12-29 09:15 UTC, chie2727 commented
@cubuspl42 
You mean merging this PR into main, yes?
I'm unable to make any merge until the PR Reviewer Check runs again and goes through.

<img width="972" alt="スクリーンショット 2023-12-29 18 13 31" src="https://github.com/Expensify/App/assets/72862115/aadbd21d-475e-46d1-b368-8e0321b7bbc2">

2023-12-29 09:37 UTC, cubuspl42 commented
> You mean merging this PR into main, yes?

No, I mean merging the upstream `main`. This is a common practice, and if the PR diverges too much from `main` (let's say above 500 commits), `main` should be merged in.

This is what this checkbox is talking about:

```
 If the main branch was merged into this PR after a review, [...]
```

It can be done with these commands (when the feature branch is checked out):

```
git fetch upstream
git merge upstream/main
```

...assuming the `Expensify/App` remote is named `upstream`.

2024-01-02 23:58 UTC, chie2727 commented
I see! Sorry for the confusion. I've merged main now!

2024-01-03 10:21 UTC, jakub-trzebiatowski approved these changes

2024-01-03 12:39 UTC, nkuoch approved these changes

2024-01-03 13:20 UTC, merged

2024-01-03 13:25 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-01-04 19:02 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7413337939) to staging by https://github.com/nkuoch in version: 1.4.22-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|cancelled 🔪
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-01-04 20:10 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7413337939) to staging by https://github.com/nkuoch in version: 1.4.22-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-01-09 05:19 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7456919171) to production by https://github.com/thienlnam in version: 1.4.22-6 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅