[Wave 6: Referral Program] Promote referral program messaging in NewDot Redesign the Referral page
Expensify/App pull request #32362
Opened 2023-12-01 16:07 UTC by rezkiy37

### Details

The PR redesigns a page for Referral Program. Currently, it has 5 variants. For 2 (_refer a friend, share code_) of them, we changed content.

### Fixed Issues

$ https://github.com/Expensify/App/issues/32187
PROPOSAL: N/A

### Tests

#### Money request
1. Click on the **FAB**.
3. Click on **"Request money"**
4. Enter any amount.
5. Click on **"Next"**.
6. Click on **"Request money, get $250."**.
7. Verify that the page looks correctly.

#### Start chat
1. Click on the **FAB**.
2. Click on **"Start a chat"**
5. Click on **"Start a chat, get $250.**.
6. Verify that the page looks correctly.

#### Send money
1. Click on the **FAB**.
2. Click on **"Send money"**
3. Enter any amount.
4. Click on **"Next"**.
5. Click on **"Send money, get $250."**.
6. Verify that the page looks correctly.

#### Refer a friend
1. Click on the **Search**.
2. Click on **"Refer a friend, get $250."**.
3. Verify that the page looks correctly.
4. Click on **"Copy referral link"**.
5. Verify that the button label has been changed to "**Copied!**" ("**¡Copiado!**") for a moment.
6. Verify that you actually copied a link - `https://join.my.expensify.com/?thanks=<YOUR_LOGIN>`.

#### Share code
1. Go to **Settings**.
2. Click on **"Share code"**
3. Click on **"Get $250"**.
5. Verify that the page looks correctly.
6. Click on **"Copy referral link"**.
8. Verify that the button label has been changed to "**Copied!**" ("**¡Copiado!**") for a moment.
9. Verify that you actually copied a link - `https://join.my.expensify.com/?thanks=<YOUR_LOGIN>`.

#### Same for all cases:

##### "**Learn more**" click
1. Click on "**Learn more**" button on a page.
2. Verify that it redirects you to `https://help.expensify.com/articles/new-expensify/billing-and-plan-types/Referral-Program`.

##### "**Learn more**" long press/right-click with mouse
1. Long press (_on mobile devices_) / right-click with mouse (_on PC_) on "**Learn more**" button on a page.
2. Verify that a context menu with the link appears.

- [X] Verify that no errors appear in the JS console

### Offline tests

Same as "**Tests**".

### QA Steps

Same as "**Tests**".

- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android: Native
    - [X] Android: mWeb Chrome
    - [X] iOS: Native
    - [X] iOS: mWeb Safari
    - [X] MacOS: Chrome / Safari
    - [X] MacOS: Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing S [...]

2023-12-02 14:47 UTC, rezkiy37 commented
@jamesdeanexpensify, please verify that everything looks good and content is correct. 

<details><summary>Share code</summary>

<img width="380" alt="Screenshot 2023-12-02 at 15 43 41" src="https://github.com/Expensify/App/assets/57314631/37cf4f8e-7995-4cc5-aaba-1b5f1b3dc820">

</details> 

<details><summary>Refer a friend</summary>

<img width="380" alt="Screenshot 2023-12-02 at 15 43 44" src="https://github.com/Expensify/App/assets/57314631/6614a860-e7e9-4568-a70d-980ff6994ad7">

</details> 

<details><summary>Request money</summary>

<img width="380" alt="Screenshot 2023-12-02 at 15 43 47" src="https://github.com/Expensify/App/assets/57314631/fa93e1f0-2782-4b5e-98e8-61487e81ebc9">

</details> 


<details><summary>Start a chat</summary>

<img width="380" alt="Screenshot 2023-12-02 at 15 43 50" src="https://github.com/Expensify/App/assets/57314631/645d68db-9680-43fa-b4ec-6d2c4299635d">

</details> 

<details><summary>Send money</summary>

<img width="380" alt="Screenshot 2023-12-02 at 15 43 52" src="https://github.com/Expensify/App/assets/57314631/01cce1e2-5559-4115-87fd-2d1f88019ea2">

</details>

2023-12-04 17:47 UTC, jamesdeanexpensify commented
I'm going to share these internally today for any final feedback in case we're missing anything. Will be back soon, thanks!

2023-12-07 14:38 UTC, parasharrajat requested changes

2023-12-07 18:15 UTC, rezkiy37 commented on src/pages/ReferralDetailsPage.js
> +            <Text style={[styles.textHeadline, styles.textAlignCenter, styles.mb3, styles.mt8, styles.ph4]}>{contentHeader}</Text>
So, it is already has bottom margins. Why do we need paddings?

2023-12-07 18:15 UTC, rezkiy37 commented on src/pages/ReferralDetailsPage.js
> +            backgroundColor={theme.PAGE_THEMES[SCREENS.SETTINGS.WORKSPACES].backgroundColor}
Done - 0d31230.

2023-12-07 18:22 UTC, rezkiy37 commented
Fixed UI bugs.

<img width="425" alt="Screenshot 2023-12-07 at 19 21 52" src="https://github.com/Expensify/App/assets/57314631/b6d5dfac-60a9-4bd9-8267-47cc159c4e28">

2023-12-07 18:37 UTC, rezkiy37 commented on src/pages/ReferralDetailsPage.js
> +            <Text style={[styles.textHeadline, styles.textAlignCenter, styles.mb3, styles.mt8, styles.ph4]}>{contentHeader}</Text>
Done - 3870b4d.

<img width="590" alt="Screenshot 2023-12-07 at 19 37 29" src="https://github.com/Expensify/App/assets/57314631/fd17642f-bd81-4b13-8acd-48d254e30f57">

2023-12-07 20:55 UTC, jamesdeanexpensify commented
We're still making the button "Copy invite link" right? Thanks!

2023-12-07 21:29 UTC, grgia commented
@parasharrajat it should be 32px

2023-12-08 09:59 UTC, rezkiy37 commented
1. Changed title of the copy button.
2. Updated spacing between the top block and content.

<img width="410" alt="Screenshot 2023-12-08 at 10 56 28" src="https://github.com/Expensify/App/assets/57314631/09492546-7e0a-4e0c-b6a1-cb7a752263fb">

<img width="406" alt="Screenshot 2023-12-08 at 10 57 55" src="https://github.com/Expensify/App/assets/57314631/a4f1a68b-eda2-465e-bbc2-26630849cbcd">

2023-12-08 14:54 UTC, parasharrajat approved these changes
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

:ribbon: :eyes: :ribbon:  C+ reviewed

2023-12-08 17:09 UTC, rezkiy37 commented on src/languages/es.ts
>          copyReferralLink: 'Copiar enlace de invitación',
@parasharrajat, yes, it is.

2023-12-08 19:31 UTC, hayata-suenaga commented on src/pages/ReferralDetailsPage.js
> +            <MenuItem
yep I agree with @rezkiy37 👍

2023-12-08 19:33 UTC, hayata-suenaga submitted a review, later dismissed
LGTM

2023-12-11 09:54 UTC, rezkiy37 commented
The conflicts were resolved.

2023-12-11 19:36 UTC, hayata-suenaga submitted a review, later dismissed
good work! LGTM!

2023-12-11 19:36 UTC, hayata-suenaga commented
there are conflicts 😢

2023-12-12 09:33 UTC, rezkiy37 commented
@hayata-suenaga, resolved.

2023-12-12 09:37 UTC, rezkiy37 commented
A bug was found. Investigating...
<img width="1473" alt="Screenshot 2023-12-12 at 10 36 53" src="https://github.com/Expensify/App/assets/57314631/49283311-0bfd-4f3c-8e9c-4daeeac1b11a">

2023-12-12 09:40 UTC, rezkiy37 commented
Fixed.
<img width="1716" alt="Screenshot 2023-12-12 at 10 40 19" src="https://github.com/Expensify/App/assets/57314631/1f6c6b14-ced0-4445-b8b2-2c890c10b832">

2023-12-12 18:53 UTC, hayata-suenaga approved these changes
thanks for fixing the merge conflicts 👍

2023-12-12 18:53 UTC, merged

2023-12-12 18:57 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2023-12-13 11:29 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7194238476) to staging by https://github.com/hayata-suenaga in version: 1.4.12-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|cancelled 🔪
🍎 iOS 🍎|cancelled 🔪
🕸 web 🕸|success ✅

2023-12-13 11:50 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7194238476) to staging by https://github.com/hayata-suenaga in version: 1.4.12-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|cancelled 🔪
🕸 web 🕸|success ✅

2023-12-13 12:17 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7194238476) to staging by https://github.com/hayata-suenaga in version: 1.4.12-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-12-14 15:24 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7210852007) to production by https://github.com/Julesssss in version: 1.4.12-2 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2023-12-14 16:41 UTC, jamesdeanexpensify commented
Actually, just kidding. It works! Sorry bout that.