[HOLD Auth 5613] [IOU] Pay with Expensify option
Expensify/App pull request #3256
Opened 2021-06-01 04:35 UTC by jasperhuangg

### Details
Added the option to pay with Expensify in the IOU Details modal if the report has USD set as its currency. See the issue for more context.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/159572

### Tests
1. Created 3 users (A, B, and C) with Gold Expensify Wallets (via [this SO](https://stackoverflow.com/c/expensify/questions/9868/9869#9869))
2. Used A to submit an IOU Request to B and C.
3. Used the Pay with Expensify option to pay for B and C.
4. Verified that the payments were added in the reimbursements table:
```SQL
SELECT * from reimbursements WHERE reportID=[reportID];
```  

### QA Steps
Same as the above tests.

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web
<img width="1249" alt="Screen Shot 2021-05-27 at 9 57 13 AM" src="https://user-images.githubusercontent.com/31285285/119755440-9f4e8700-bed4-11eb-8380-a42e718d1571.png">

#### Mobile Web
![Simulator Screen Shot - iPhone 11 - 2021-05-27 at 10 04 49](https://user-images.githubusercontent.com/31285285/119755463-a9708580-bed4-11eb-96bb-2ac1cbc51dc2.png)
![Simulator Screen Shot - iPhone 11 - 2021-05-27 at 10 04 55](https://user-images.githubusercontent.com/31285285/119755468-ab3a4900-bed4-11eb-9645-2851c889f734.png)

#### Desktop
<img width="1792" alt="Screen Shot 2021-05-27 at 9 59 10 AM" src="https://user-images.githubusercontent.com/31285285/119755478-b0979380-bed4-11eb-8183-040a4c651038.png">

#### iOS
![Simulator Screen Shot - iPhone 11 - 2021-05-27 at 10 02 43](https://user-images.githubusercontent.com/31285285/119755507-b9886500-bed4-11eb-8020-5acea6655311.png)
![Simulator Screen Shot - iPhone 11 - 2021-05-27 at 10 02 46](https://user-images.githubusercontent.com/31285285/119755513-bab99200-bed4-11eb-9fab-7329c93f3ead.png)

#### Android
![171622081774_ pic](https://user-images.githubusercontent.com/31285285/119755560-cad17180-bed4-11eb-8863-9ed2b02dcbf1.jpg)
![181622081775_ pic](https://user-images.githubusercontent.com/31285285/119755565-cc9b3500-bed4-11eb-82a5-622ebb789fe7.jpg)

2021-06-02 09:50 UTC, Julesssss commented on src/pages/iou/IOUDetailsModal.js
> +     * Checks to see if we can use Expensify.
> Checks to see if we can use Expensify.

Could you expand on this a bit? 'use Expensify' without the pay-with-expensify context is a bit vague IMO.

2021-06-02 14:36 UTC, jasperhuangg commented
Hey @Julesssss! My bad! Forgot to update the testing instructions. You also need to run `./script/clitools.sh generator:bankaccount` to generate a deposit bank account for the payer.

It's because the PayWithWallet command was recently updated to [require either a default bank account or debit card fund for the payer](https://github.com/Expensify/Auth/blob/e93624679ec767f0014ec8df5bdb25a8f3356851/auth/command/PayWithWallet.cpp#L58-L66). I think it's so we can support Bancorp personal payments?

2021-06-02 14:59 UTC, Julesssss requested changes
Thanks, I was able to settle the IOU!

The next problem is that the reports are updated but the message doesn't appear for either user. This is because a Pusher/Push notification is not being sent for this specific IOU event. Notice that any other 'event' (create IOU, send message, cancel IOU, pay IOU) will trigger the following debug message in the other clients console: 

![Screenshot 2021-06-02 at 15 54 50](https://user-images.githubusercontent.com/10736861/120503493-42af0880-c3bb-11eb-9474-74309d177433.png)

This is how we trigger updates to report comments (and therefore IOU actions), so we'll need to ensure that users are notified as part of the pay-with-expensify flow.

2021-06-03 05:22 UTC, jasperhuangg commented
@Julesssss I opened up a Web-E PR that should fix our pusher notification problem. It updates PayWithWallet in the PHP layer to check if the report that was just paid for in Auth is an IOU report, and sends a pusher notification if that's the case. I requested you for review!

https://github.com/Expensify/Web-Expensify/pull/31113

2021-06-03 14:07 UTC, Julesssss approved these changes
Tested well for me. All yours @tylerkaraszewski 

<img width="1033" alt="Screenshot 2021-06-03 at 14 25 03" src="https://user-images.githubusercontent.com/10736861/120652310-92530a00-c477-11eb-8e73-99beac69f747.png">

2021-06-03 19:38 UTC, tylerkaraszewski approved these changes

2021-06-04 03:51 UTC, merged

2021-06-04 04:30 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/905041081) to staging in version: 1.0.62-2🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-06-08 00:14 UTC, roryabraham commented
I think that @kevinksullivan and I were able to successfully QA this on Friday last week. Let me confirm.

2021-06-08 00:26 UTC, roryabraham commented
Verified that the front-end is working for me on iOS, Mobile Safari, Chrome, Desktop. Just need someone, I think from @ring1, to confirm that the reimbursements are added to the `reimbursements` table by running this query:

```sql
SELECT * FROM reimbursements WHERE reportID=71125175;
```

2021-06-08 00:35 UTC, roryabraham commented
Looks like this _may_ have been a QA-fail, but I'll let @jasperhuangg retest and confirm. I used `Pay With Expensify` for several IOUs on Expensify.cash staging in that report, but [the reimbursements table was empty](https://expensify.slack.com/archives/C03TQ48KC/p1623112168372800).

Nonetheless, since `payWithExpensify` is hidden behind a beta this does not need to be a deploy blocker.

2021-06-08 01:00 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/916738164) to production in version: 1.0.64-0🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅