Add focus trap to the RHP (v3)
Expensify/App pull request #32800
Opened 2023-12-11 11:41 UTC by kosmydel

### Details

### Fixed Issues

$
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2023-12-18 10:35 UTC, kosmydel commented
I ran the tests on all platforms but Android, as it crashes on main. Will test it, when it works.

Can we do the QA tests after the C+ approves and before merging? 
Since focus trap changes affect almost every screen in the App, there is a high risk of regression. So it might be a good idea, especially since it was reverted two times. 

cc @fedirjh, @roryabraham, @luacmartins

2023-12-21 14:08 UTC, kosmydel commented
Hey, sorry for the delay. The android was crashing, and then I had a busy week. This is ready for a review.

Can we run QA here before merging it into the main? cc @roryabraham

2024-01-02 09:19 UTC, kosmydel commented
I've resolved conflicts and retested. 
Friendly bump @fedirjh :)

2024-01-09 21:54 UTC, fedirjh reviewed
Left minor feedback about the code.

2024-01-10 14:55 UTC, kosmydel commented on src/components/ScreenWrapper.tsx
> +    shouldDisableFocusTrap?: boolean;
Right, great idea! I'm not sure why I was fixed with that approach.

2024-01-10 15:00 UTC, kosmydel commented
I've addressed the review and quickly tested it. cc @fedirjh

2024-01-11 08:17 UTC, fedirjh approved these changes
Looks good to me and tests well

2024-01-11 09:00 UTC, kosmydel commented
Thanks @fedirjh!

Can we please do the QA before merging? Those changes got reverted two times, so it would be safer this way. cc @roryabraham

2024-01-14 05:17 UTC, roryabraham commented
Kicked off an AdHoc build, requested regression run [here](https://expensify.slack.com/archives/C9YU7BX5M/p1705209423974619)

2024-01-18 11:34 UTC, kosmydel commented
I've pulled the main and resolved conflicts.
cc @fedirjh for another look, to be safe

2024-01-22 13:46 UTC, kosmydel commented
> Kicked off an AdHoc build, requested regression run [here](https://expensify.slack.com/archives/C9YU7BX5M/p1705209423974619)

Hey @roryabraham, do we have any results of the regression test?

2024-01-24 08:40 UTC, roryabraham commented
Good question @kosmydel, sorry I didn't follow up. I didn't hear back from Applause after my initial request, so I just pinged them again for confirmation. Will let you know.

2024-01-24 20:30 UTC, mvtglobally commented
Regression is completed. No issues

2024-01-25 12:08 UTC, kosmydel commented
> Regression is completed. No issues

Great! Thanks!

I'm unsure if I can merge conflicts and test it this week.

2024-01-30 10:40 UTC, kosmydel commented
I've resolved conflicts again. 

---

However, there is an issue (both on main and staging) related to navigation using the tab in the manual request flow.

Steps:
1. FAB -> Request money -> Manual
2. Type any amount, press next
3. Try using tab

---

Anyway, could you have a final look, as after the regression test I resolved conflicts three times? cc @fedirjh

2024-01-31 22:59 UTC, fedirjh approved these changes
Looks good. 

cc @roryabraham Let's get this merged once @kosmydel resolves the conflicts

2024-02-01 20:20 UTC, roryabraham requested changes
otherwise LGTM, ready to merge after conflicts are resolved and this one comment is addressed

2024-02-01 20:20 UTC, roryabraham commented on src/components/FocusTrapView/index.tsx
> +                fallbackFocus: () => ref.current!,
Let's avoid disabling this lint rule

2024-02-02 10:26 UTC, kosmydel commented
The ideal nav has been merged and it affected the FocusTrap behavior. The reported issue is solved. 

If we want to change anything in terms of the navigation using the Tab button, please let me know.

cc @roryabraham, @fedirjh

2024-02-02 17:14 UTC, roryabraham commented
> The reported issue is solved.

Great, sounds like we can just close this then?

2024-02-26 20:58 UTC, roryabraham commented
@kosmydel can we close this and create a new PR in association with https://github.com/Expensify/App/issues/36476? I also think that we have a new process for adding new external libs to the codebase that we would want to follow if we are going to proceed with adding `react-focus-trap`

2024-02-27 09:37 UTC, closed without merging