Add Spanish locales
Expensify/App pull request #3360
Opened 2021-06-03 23:49 UTC by iwiznia

Please, let's not focus too much on the translations themselves, we can iterate on them later.

### Fixed Issues

Fixes https://github.com/Expensify/Expensify/issues/152156

### Tests
- Go to the JS console > Application > Local Storage and set a new key `preferredLocale` to `"es-ES"` (including the quotes)
- Play around the app and check texts are correctly translated to spanish
- Delete the preferredLocale if you don't want e.cash to remain in spanish forever

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web
![image](https://user-images.githubusercontent.com/521248/120724597-729dff00-c4d4-11eb-8e9b-f7a5c53479b1.png)
![image](https://user-images.githubusercontent.com/521248/120724600-7467c280-c4d4-11eb-8ab0-b48b90a2d0a5.png)
![image](https://user-images.githubusercontent.com/521248/120724608-76318600-c4d4-11eb-9cd9-1f3dd284508f.png)
![image](https://user-images.githubusercontent.com/521248/120724614-77fb4980-c4d4-11eb-90b0-b76f2de53fe3.png)

2021-06-04 18:02 UTC, shawnborton commented
For this one:

![image](https://user-images.githubusercontent.com/2319350/120844527-5cb82a80-c524-11eb-9ce5-9b4168b6f9eb.png)

Could we either add a word or remove a word so that we don't have the hanging orphan on the second line?

2021-06-07 18:28 UTC, iwiznia commented
> Could we either add a word or remove a word so that we don't have the hanging orphan on the second line?

I don't think we should, mainly because these are not final copy, it's just a test so that we can see the whole I18n project works... also it is possible that in some languages the copy will be hard to fit in one line, so we need to learn to live with it... it does not look that bad to me.

2021-06-07 19:10 UTC, pecanoro commented
For that one maybe we can simply change it to "¡Cuéntanos algo sobre tí, nos encantaría conocerte!"

2021-06-07 19:13 UTC, iwiznia commented
Alright changed it

2021-06-07 20:10 UTC, pecanoro requested changes

2021-06-07 20:10 UTC, pecanoro commented on src/languages/es.js
> +        phrase1: 'Al ingresar, estas aceptando los',
```suggestion
        phrase1: 'Al usar Expensify.cash, estás aceptando los',
```

2021-06-07 20:10 UTC, pecanoro commented on src/languages/es.js
> +        forgot: 'Te has olvidado?',
```suggestion
        forgot: '¿Te has olvidado?',
```

2021-06-07 20:10 UTC, pecanoro commented on src/languages/es.js
> +        twoFactorCode: 'Autenticación de 2 factores',
`Autentificación` sounds better than `Autenticación`, but maybe it's just me

2021-06-07 20:10 UTC, pecanoro commented on src/languages/es.js
> +        pleaseEnterEmailOrPhoneNumber: 'Por favor escribe un email o número de teleéfono',
```suggestion
        pleaseEnterEmailOrPhoneNumber: 'Por favor escribe un email o número de teléfono',
```

2021-06-07 20:10 UTC, pecanoro commented on src/languages/es.js
> +        phoneOrEmail: 'Teleéfono o Email',
```suggestion
        phoneOrEmail: 'Número de Teléfono o Email',
```

2021-06-07 20:10 UTC, pecanoro commented on src/languages/es.js
> +        enterYourPhoneOrEmail: 'Escribe tu teleéfono o email:',
```suggestion
        enterYourPhoneOrEmail: 'Escribe tu número de teléfono o email:',
```

2021-06-07 20:10 UTC, pecanoro commented on src/languages/es.js
> +        weSentYouMagicSignInLink: 'Te hemos enviado un enlace - simplemente haz click en él para conectarte!',
```suggestion
        weSentYouMagicSignInLink: '¡Te hemos enviado un enlace - simplemente haz click en él para conectarte!',
```

2021-06-07 20:10 UTC, pecanoro commented on src/languages/es.js
> +        addBankAccount: 'Agregar una cuenta de banco',
```suggestion
        addBankAccount: 'Agregar una cuenta bancaria',
```

2021-06-07 20:10 UTC, pecanoro commented on src/languages/es.js
> +        heHimHis: 'El',
```suggestion
        heHimHis: 'Él',
```

2021-06-07 20:10 UTC, pecanoro commented on src/languages/es.js
> +        offlineMessage: 'Parece que no estás conectado a internet. Comprueba to conexión e inténtalo de nuevo?',
```suggestion
        offlineMessage: 'Parece que no estás conectado a internet. Comprueba tu conexión e inténtalo de nuevo.',
```

2021-06-07 20:46 UTC, iwiznia commented on src/languages/es.js
> +        allCurrencies: 'TODAS LAS MONEDAS',
Moneda is more common IMO

2021-06-07 20:47 UTC, iwiznia commented on src/languages/es.js
> +        requestMoney: 'Pedir Dinero',
Solicitar importe no me dice mucho...

2021-06-07 20:49 UTC, iwiznia commented
Updated

2021-06-07 21:49 UTC, pecanoro commented on src/languages/es.js
> +        requestMoney: 'Pedir Dinero',
`Pedir dinero` sounds like begging money to me 😂

2021-06-07 21:53 UTC, pecanoro commented on src/languages/es.js
> +        requiredWhen2FAEnabled: 'Obligatorio cuando A2F esta habilitado',
```suggestion
        requiredWhen2FAEnabled: 'Obligatorio cuando A2F está habilitado',
```

2021-06-07 21:54 UTC, iwiznia commented on src/languages/es.js
> +        requestMoney: 'Pedir Dinero',
🤷 we can change this later

2021-06-07 21:54 UTC, iwiznia commented
Updated

2021-06-07 21:56 UTC, pecanoro approved these changes

2021-06-07 22:30 UTC, merged

2021-06-07 22:30 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-06-08 01:11 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/916741429) to staging in version: 1.0.64-1🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-06-08 23:36 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/919961677) to production in version: 1.0.65-0🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅