[WIP] Menu auto close
Expensify/App pull request #3363
Opened 2021-06-04 03:43 UTC by parasharrajat

### Details

### Fixed Issues

Fixes GH_LINK

### Tests

### QA Steps

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-06-07 17:33 UTC, NikkiWines requested changes
This looks good. I know this issue only occurred on web/desktop app, but can you add videos for mWeb and iOS, as well as the remaining one for web or desktop (not sure which platform the current video is for since they're under the same heading)

2021-06-07 17:33 UTC, NikkiWines commented on src/pages/home/report/ReportActionContextMenu.js
> +    hidePopover(delay) {
This should probably be called something like `hasDelay` or `shouldDelay` since it's a boolean.

2021-06-07 19:44 UTC, parasharrajat commented
@NikkiWines Updated. Thanks

2021-06-07 22:16 UTC, NikkiWines requested changes
Looks great, with only a couple of very minor comments.

2021-06-07 22:16 UTC, NikkiWines commented on src/pages/home/report/ReportActionContextMenu.js
> +     * @param {Boolean} shouldDelay whether the meanu should close after a delay
typo: `meanu`

2021-06-07 22:16 UTC, NikkiWines commented on src/pages/home/report/ReportActionContextMenu.js
> +     * Hide the Menu
NAB: `Hides the popover menu with an optional delay`

2021-06-08 01:54 UTC, parasharrajat commented
@NikkiWines Updated. Thanks

2021-06-08 02:10 UTC, NikkiWines approved these changes
👍  Looks good

2021-06-08 15:54 UTC, parasharrajat commented
:shipit: .

2021-06-08 16:08 UTC, merged

2021-06-08 16:49 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/918949862) to staging in version: 1.0.64-5🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅