New room visibility format refactor
Expensify/App pull request #33717
Opened 2023-12-28 17:35 UTC by esh-g

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/32614
PROPOSAL: https://github.com/Expensify/App/issues/32614#issuecomment-1851610628

### Tests

1. Click on '+' FAB.
2. Click on 'Start chat'
3. Select the '#Room' tab
4. Enter any name
5. Hover over the visibility menu item
6. Make sure the bottom line of additional text is a part of the menu item. ('People in your workspace can find this room')
7. Click on the visibility.
8. Make sure the titles of all options are bold.
9. Make sure changing an option also changes the additional text of the menu item.

- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

1. Click on '+' FAB.
2. Click on 'Start chat'
3. Select the '#Room' tab
4. Enter any name
5. Hover over the visibility menu item
6. Make sure the bottom line of additional text is a part of the menu item. ('People in your workspace can find this room')
7. Click on the visibility.
8. Make sure the titles of all options are bold.
9. Make sure changing an option also changes the additional text of the menu item.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</s [...]

2023-12-28 18:20 UTC, s77rt requested changes

2023-12-28 18:20 UTC, s77rt commented on src/components/MenuItem.tsx
> +                                                {furtherDetailsIcon && (
```suggestion
                                                {!!furtherDetailsIcon && (
```

The conditions here should always be boolean

2023-12-28 18:22 UTC, s77rt commented
Font size does not match the mock up

<img width="377" alt="Screenshot 2023-12-28 at 7 21 04 PM" src="https://github.com/Expensify/App/assets/16493223/160ba318-c55b-4c30-9f4e-558f9b845e72">



Spacing does not match the mock up

<img width="378" alt="Screenshot 2023-12-28 at 7 21 21 PM" src="https://github.com/Expensify/App/assets/16493223/0f1a39b6-4e19-43bc-a6f5-a3df540719c9">

2023-12-29 05:38 UTC, esh-g commented
@s77rt As for the font-size in the menu item, it is the same style being used in the violations tab:
<img width="375" alt="Screenshot 2023-12-29 at 11 05 00 AM" src="https://github.com/Expensify/App/assets/77237602/1bf24570-dd62-4a02-97ec-1937ac515d43">

So, changing this would mean changes to this tab as well, it is possible to have the style props passed from the parent as separate but I think we should be consistent with how we handle all `furtherDetails` text in `MenuItem`. So, keeping all that in mind, should we change the `styles.furtherDetailsText`?

And does the spacing look fine now?

<img width="375" alt="Screenshot 2023-12-29 at 11 03 53 AM" src="https://github.com/Expensify/App/assets/77237602/f9e587c3-a4d8-4349-9cf1-e165f5108a59">

2023-12-29 13:21 UTC, s77rt commented
@esh-g I think we make the changes to be global

2023-12-29 13:34 UTC, s77rt commented
@shawnborton Need some help here:
1. Figma design for the selection list https://github.com/Expensify/App/issues/32614#issuecomment-1850797464

2023-12-29 13:34 UTC, s77rt commented
@esh-g Yes, let's work on it then apply any necessary changes later

2023-12-29 13:37 UTC, esh-g commented
> Yes, let's work on it then apply any necessary changes later
@s77rt So, right now we should wait for design approval before making any change or should I increase the text size now and then wait for design approval later?

2023-12-29 14:30 UTC, s77rt commented
Let's increase the size first, I think the correct font size here is `variables.fontSizeLabel`

2023-12-29 14:36 UTC, esh-g commented
Made the change, this is how it looks in violations:

<img width="375" alt="Screenshot 2023-12-29 at 8 04 48 PM" src="https://github.com/Expensify/App/assets/77237602/d401bca7-9dfb-4ea6-8e10-e700657cdfcc">

2023-12-30 23:47 UTC, quinthar commented
I'm sorry for my confusion here, can you catch me up?  So far as I can tell:

1. Is the question whether to change the global font size?  If so, I do *not* think we want to change any global fonts.  This is a very tiny, local change, let's follow the global styling, not change it.

2. Given that we're going to follow global stying, can you show what this looks like next to what the mockup asked for, side by side?  I suspect following global styling is just fine, but I'd like to see it.

Thanks!

2023-12-31 00:05 UTC, s77rt commented
Mockup vs PR

![289656893-9af14df1-e86a-4618-95ef-92598f047f18](https://github.com/Expensify/App/assets/16493223/5e150a16-5f6b-4077-802d-98289a58c1af)

![289656893-9af14df1-e86a-4618-95ef-92598f047f18 copy](https://github.com/Expensify/App/assets/16493223/09f769d1-c02e-4959-b3dc-02eca50833d6)



___

The "People in this workspace can find your room message" message shares the same stye with "Message hidden from channel, plus anonymous warning and message is reported for review" so you can see we had to increase the font size in order to match with the mockup. Do you think that increase in size is okay or we should keep that one untouched? 

<img width="375" alt="293314302-1bf24570-dd62-4a02-97ec-1937ac515d43" src="https://github.com/Expensify/App/assets/16493223/3debe250-257f-4c8b-9eff-4dc750e61ed7">
<img width="375" alt="293381691-d401bca7-9dfb-4ea6-8e10-e700657cdfcc" src="https://github.com/Expensify/App/assets/16493223/d8210445-4d90-4cea-a6ba-190202330a6e">

2023-12-31 00:06 UTC, quinthar commented
Please leave the abuse screen untouched.  The PR looks fine to me; let's stick with the global styling.

2023-12-31 00:56 UTC, s77rt commented
@quinthar I have opened a new PR for urgency (@esh-g does not seem online atm). https://github.com/Expensify/App/pull/33808 Can you merge it?

2023-12-31 02:14 UTC, quinthar commented
Ah I will defer to others to merge.  Thanks for the hustle, though!

2023-12-31 02:40 UTC, esh-g commented
@s77rt I am online now... should I just reverse the font change and merge this?

2023-12-31 03:57 UTC, quinthar commented
Works for me!

On Sat, Dec 30, 2023 at 6:40 PM Esh Tanya Gupta ***@***.***>
wrote:

> @s77rt <https://github.com/s77rt> I am online now... should I just
> reverse the font change and merge this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Expensify/App/pull/33717#issuecomment-1872653312>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEMNUQ3IWCEKKNNELINTYTYMDGAVAVCNFSM6AAAAABBFXUVMGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZSGY2TGMZRGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-31 09:34 UTC, s77rt commented
@esh-g No. I have created another PR https://github.com/Expensify/App/pull/33808 to keep the flag page untouched. Can you please close this one?

2024-01-04 12:39 UTC, closed without merging