Set default currency for IOUBadge
Expensify/App pull request #3382
Opened 2021-06-04 18:59 UTC by Jag96

@roryabraham will you please review this

### Details
This PR fixes an issue that I found while testing https://github.com/Expensify/react-native-onyx/pull/76#pullrequestreview-676561010. Currency does not have a default value, so if the IOUReport isn't done fetching before we try to display the IOUBadge, we can get a white screen on Web and Desktop. We also have default values for the other iouReport props in the IOUBadge, so we should add one for currency anyway.

### Tests/QA
1. Sign into an account with an IOU
2. Confirm the chats load normally and there isn't a white screen

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots
N/A

2021-06-04 19:02 UTC, roryabraham requested changes

2021-06-04 19:02 UTC, roryabraham commented on src/components/IOUBadge.js
> +        currency: CONST.CURRENCY.USD,
This should be documented in the `PropTypes.shape` above too

2021-06-04 19:13 UTC, Jag96 commented
@roryabraham updated

2021-06-04 19:20 UTC, roryabraham approved these changes

2021-06-04 21:23 UTC, merged

2021-06-04 21:24 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-06-07 09:55 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/914229979) to staging in version: 1.0.63-1🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-06-08 00:59 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/916738164) to production in version: 1.0.64-0🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅