Set the focus on Edit Box after edit action.
Expensify/App pull request #3441
Opened 2021-06-08 17:42 UTC by parasharrajat

### Details
1. Remove modal visibility status from the Context Menu. which is needed to make the edited comment as a prime actor for focus.
2. Delayed the edit action after the Context menu is completely hidden which let us handle the focus. It removes the need of the SetTimeout hack.

### Fixed Issues

Fixes #3017

### Tests | QA Steps (Web|Desktop)
• Sign in to the e.chat staging web app
• Right-click text and choose Edit Comment
• Textbox should automatically get focused.
* Click Edit comment from Hover menu. Edit box should automatically get focused.

### Tests | QA Steps(mWeb|Android|IOS)
• Sign in to the e.chat staging web app
• Hold press any text message sent by you and choose Edit Comment
• Textbox should automatically get focused.

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-06-09 14:50 UTC, parasharrajat commented
Ready to roll. Thanks.

2021-06-09 16:14 UTC, roryabraham commented
@parasharrajat Looks like lint is failing

2021-06-09 16:20 UTC, parasharrajat commented
@roryabraham this is due to https://github.com/Expensify/Expensify.cash/pull/3401. And the fix is being made here https://github.com/Expensify/Expensify.cash/pull/3481. So I suggest we merge it quickly.

2021-06-09 17:41 UTC, roryabraham commented
Lint error resolved, please merge `main` into this branch

2021-06-09 17:43 UTC, roryabraham commented
Also @parasharrajat will this also fix [this deploy blocker](https://github.com/Expensify/Expensify.cash/pull/3434)?

2021-06-09 17:59 UTC, roryabraham commented
> Also @parasharrajat will this also fix this deploy blocker?

Confirmed on iOS safari that it does.

2021-06-09 18:13 UTC, roryabraham requested changes
Also, I must be going crazy because I can't find where the `isFocused` prop of the `ReportActionCompose` comes from, because it isn't coming from [here](https://github.com/Expensify/Expensify.cash/blob/37465dbd07da1feab8347835d82ed3d2302cde4c/src/pages/home/report/ReportView.js#L37). Are we sure that this is ever being actually set? Can we safely get rid of it? We also have `isFocused` in the `ReportActionCompose` state.

2021-06-09 18:19 UTC, parasharrajat commented on src/pages/home/report/ReportActionContextMenu.js
>                      );
Yes

2021-06-09 18:20 UTC, parasharrajat commented
`IsFocused` prop is coming from withNavigation HOC. It's the most important prop.  Removing it is not an option. :smile:

2021-06-09 18:30 UTC, parasharrajat commented
Updated. Thanks.

2021-06-10 16:41 UTC, parasharrajat commented
@deetergp @roryabraham Awaiting your feedback. Thanks.

2021-06-10 17:26 UTC, deetergp commented
## Testing
### Web
Editing via the context menu always puts focus to the edit text box, but the right-click > edit only does it on the first edit after a page load. In subsequent right-click > edits, the focus stays at the bottom, in the main text editor.

### Desktop
Context menu Edit works like it should, but I couldn't get right-click > edit to focus in the edit text box, it always went down to the main text box.

### mWeb
Works as intended 👍 

### iOS
Works as intended, though it's weird that you only get the long-press context menu if you click on your own avatar. That's probably unrelated.

2021-06-10 18:18 UTC, parasharrajat commented
@deetergp Thanks for letting me know. I changed the prop name but forgot to update it in the Component. `shouldSetModalVisibility` was the prop. Just fixed it. You can check now. Thanks.

2021-06-10 18:39 UTC, deetergp commented
That fix did it, thanks @parasharrajat 👍

2021-06-10 18:39 UTC, deetergp approved these changes
Code looks good and tests pass.

2021-06-10 19:42 UTC, parasharrajat commented
:shipit:

2021-06-11 16:42 UTC, parasharrajat commented
@roryabraham Any feedback here? I think this PR is waiting to be merged by you. :sweat_smile:

2021-06-11 22:10 UTC, roryabraham approved these changes
This looks good to me. Sorry to have been a bottleneck here @parasharrajat – been a crazy couple days.

2021-06-11 22:10 UTC, merged

2021-06-11 22:11 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-06-15 17:14 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/940035625) to staging in version: 1.0.68-5🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-06-15 22:38 UTC, kavimuru commented
## iPhone - Safari -  Cursor focus not gained for edit comment field
## Expected Result: 
Textbox should automatically get focused.
## Actual Result:
Focus not gained in edit box
## Actions Performed:
1. Launch the URL and login
2. Hold press any text message sent by you and choose Edit Comment
## Platform:
iOS 
mWeb ✔️
Android 
## Build:
1.0.69-0

## Notes/Images/Video:

https://user-images.githubusercontent.com/43996225/122132148-50777b80-ce08-11eb-9be8-9bd8735cbc6f.mp4

2021-06-15 23:01 UTC, parasharrajat commented
No worries I will test it on safari M-web

2021-06-17 16:45 UTC, roryabraham commented
I am unable to reproduce on iOS 14.5 Safari. @isagoico @kavimuru can we please retest this in the latest staging version and see if it has been resolved?

2021-06-17 17:00 UTC, parasharrajat commented
Same here issue is not reproducible on M-web safari iPhone 12 - 14.4.

2021-06-18 13:37 UTC, isagoico commented
Retested and it was a pass in mWeb! Checking it off.

2021-06-25 18:32 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/972294561) to production in version: 1.0.73-3🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅