[WIP] Cancel Payment command (again and again)
Expensify/App pull request #34719
Opened 2024-01-18 11:31 UTC by Gonals

### Details

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/327308
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-01-31 14:37 UTC, Gonals commented
@sobitneupane, this is on HOLD for the paid workspaces. You probably can't test that part anyways, so feel free to go ahead and start on this for free workspaces

2024-02-01 14:47 UTC, Gonals commented
Removing HOLD for now, as you cn start testing with free plans @sobitneupane

2024-02-05 07:17 UTC, sobitneupane commented
I could not pay the amount from account A.
<img width="354" alt="Screenshot 2024-02-05 at 12 59 13" src="https://github.com/Expensify/App/assets/25876548/7ba608c8-a30d-472e-ac88-5cb6cb6a8f92">

https://github.com/Expensify/App/assets/25876548/530e22b3-803c-4fd1-9f52-952476a36978

2024-02-05 11:40 UTC, Gonals commented
> I could not pay the amount from account A. <img alt="Screenshot 2024-02-05 at 12 59 13" width="354" src="https://private-user-images.githubusercontent.com/25876548/302204213-7ba608c8-a30d-472e-ac88-5cb6cb6a8f92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzM0NzgsIm5iZiI6MTcwNzEzMzE3OCwicGF0aCI6Ii8yNTg3NjU0OC8zMDIyMDQyMTMtN2JhNjA4YzgtYTMwZC00NzJlLWFjODgtNWNiNmNiNmE4ZjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDExMzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YTEzODViMmQ4MTM1M2I1MjFiMWE5ZDU4YjQ4NThhYjVmMGVhNzllZGJmMTU1ZGVhZTNjOGEyYjg3MGQ4ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ecvKfem5dQwVWLjnJ4Tkac01BLnv7-UEgbAKcR0aDD0">
> 
>  Untitled.mov 
> I managed to pay from the Workspace Report Page, but I couldn't cancel the payment with following console error.
> 
> <img alt="Screenshot 2024-02-05 at 13 07 54" width="276" src="https://private-user-images.githubusercontent.com/25876548/302206133-ba29c31c-8a3e-4886-8339-97f4a79874ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzM0NzgsIm5iZiI6MTcwNzEzMzE3OCwicGF0aCI6Ii8yNTg3NjU0OC8zMDIyMDYxMzMtYmEyOWMzMWMtOGEzZS00ODg2LTgzMzktOTdmNGE3OTg3NGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDExMzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ODg5ZGZmZmExMmQwZjlmMzQyOWE3ZWM0NjBkZWUxNjMyYzY1OGZiNTEzODBmZDIwN2ZkMjY4NWFkNzlhMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FGK2Nf_sjPmHigkK3_1ONopQbTh8uABDG5bBSGRDH0M">
>  Screen.Recording.2024-02-05.at.13.04.56.mov

Ah, likely something changed after merging main. Taking a look

2024-02-05 12:02 UTC, Gonals commented
@sobitneupane, I can't seem to reproduce the issue. I merged main again, can you give it another shot?

2024-02-05 12:58 UTC, sobitneupane commented
Thanks for the update @Gonals. I cannot reproduce the issue any longer.

I was able to reproduce [this issue](https://github.com/Expensify/App/issues/34685).

https://github.com/Expensify/App/assets/25876548/38c500de-5151-4259-bacb-909f14376a54

I was also able to reproduce [this issue](https://github.com/Expensify/App/issues/34681) and [this issue](https://github.com/Expensify/App/issues/34676).

https://github.com/Expensify/App/assets/25876548/164d84bc-2ccd-466f-9546-786bc36a3549

2024-02-05 12:59 UTC, sobitneupane commented
Is cancel payment only limited to workspace? I could not cancel payment for transaction between two users.
<img width="1440" alt="Screenshot 2024-02-05 at 18 43 50" src="https://github.com/Expensify/App/assets/25876548/9be5efdb-f3b7-4691-aa3c-22f39f14fb1b">

2024-02-07 12:55 UTC, Gonals commented
Ok! Issues fixed!
- Negative amount issue fixed
- We shouldn't even be displaying the "Marked as reimbursed" message, so removing it.
- Due to non-related changes, we now display the Report's title on unsettled reports, so we should no longer see the cancelled/owes change

2024-02-08 11:53 UTC, sobitneupane commented
@Gonals I can still reproduce [this issue](https://github.com/Expensify/App/issues/34681). 
<img width="1440" alt="Screenshot 2024-02-08 at 17 29 10" src="https://github.com/Expensify/App/assets/25876548/98986a6b-c436-46d7-9785-389aefddca58">

It first shows following message in LHN.
<img width="293" alt="Screenshot 2024-02-08 at 17 29 38" src="https://github.com/Expensify/App/assets/25876548/1ef4c4d9-b924-4db5-a0bc-cbc23903fd5e">

which changes to following message after refreshing.
<img width="293" alt="Screenshot 2024-02-08 at 17 30 10" src="https://github.com/Expensify/App/assets/25876548/30a6a78d-5b0d-408c-a084-e32e5face2be">

2024-02-08 12:14 UTC, sobitneupane commented
I found another weird issue. I requested $100 from a workspace(with NPR as default currency) as a member. Then I change the default currency to USD. I paid the amount. Now the message should be either paid $100 or NPR (something) but it is paid NPR 100.0.

Steps to reproduce:
1. [Member]Go to an workspace(with default currency other than USD) as a member
2. [Member] Actions> Request money > change the currency to USD and add amount > Next > Request
3. [Admin] Change the default currency of the workspace to USD
4. [Admin] Pay the amount
5. Notice that the amount is in one currency with the symbol of another currency (for example:- NPR100 expected: $100 or NPR (something))

https://github.com/Expensify/App/assets/25876548/195c36f1-3de8-4b25-a3b2-9736a2d341a1

2024-02-08 12:31 UTC, Gonals commented
> @Gonals I can still reproduce [this issue](https://github.com/Expensify/App/issues/34681). <img alt="Screenshot 2024-02-08 at 17 29 10" width="1440" src="https://private-user-images.githubusercontent.com/25876548/303314763-98986a6b-c436-46d7-9785-389aefddca58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTQxNTgsIm5iZiI6MTcwNzM5Mzg1OCwicGF0aCI6Ii8yNTg3NjU0OC8zMDMzMTQ3NjMtOTg5ODZhNmItYzQzNi00NmQ3LTk3ODUtMzg5YWVmZGRjYTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEyMDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMWY4MTAwM2M2ZDM5MmJkYjE2ZDIxZWFlNzUyNjY2MWEwZWUwOGZiY2ZiZGFkYWE5NmE1YjY3MTYzOTA4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AbziCNUcFhX2LrVKsQfY0eMzg334GbZ2zVhwDQhkhCg">
> 
> It first shows following message in LHN. <img alt="Screenshot 2024-02-08 at 17 29 38" width="293" src="https://private-user-images.githubusercontent.com/25876548/303314899-1ef4c4d9-b924-4db5-a0bc-cbc23903fd5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTQxNTgsIm5iZiI6MTcwNzM5Mzg1OCwicGF0aCI6Ii8yNTg3NjU0OC8zMDMzMTQ4OTktMWVmNGM0ZDktYjkyNC00ZGI1LWEwYmMtY2JjMjM5MDNmZDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEyMDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMmVjY2I1Y2QwNjgzMzQwMGE3N2YwM2I0ODY2MGEzOGMxODE2Y2Q4YmEyM2QxYjYyMTFjMjI2ZjBjMDQ3N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QqFzxPJ-19zQ8rG2qUc4QTHF0_9hWHKFtctX6VWZrUI">
> 
> which changes to following message after refreshing. <img alt="Screenshot 2024-02-08 at 17 30 10" width="293" src="https://private-user-images.githubusercontent.com/25876548/303315019-30a6a78d-5b0d-408c-a084-e32e5face2be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTQxNTgsIm5iZiI6MTcwNzM5Mzg1OCwicGF0aCI6Ii8yNTg3NjU0OC8zMDMzMTUwMTktMzBhNmE3OGQtNWIwZC00MDhjLWEwODQtZTMyZTVmYWNlMmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEyMDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZTA5OGRmN2NkZTkyMjk0YWMwNzkzZWE3NTc4MDk3OWU1YmUyZGUzNzA5NzU5MGUxYzgxY2EyYjIyODMxOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H5dVvlxW-YFWEwrHxmasLY7a2gyS0SpAy6kHSpI3wGI">

Taking another look! I wasn't able to see it happen, but it is likely due to me being in the `canUseReportFields` beta, which changes this behavior

2024-02-08 14:44 UTC, Gonals commented
> I found another weird issue. I requested $100 from a workspace(with NPR as default currency) as a member. Then I change the default currency to USD. I paid the amount. Now the message should be either paid $100 or NPR (something) but it is paid NPR 100.0.
> 
> Steps to reproduce:
> 
> 1. [Member]Go to an workspace(with default currency other than USD) as a member
> 2. [Member] Actions> Request money > change the currency to USD and add amount > Next > Request
> 3. [Admin] Change the default currency of the workspace to USD
> 4. [Admin] Pay the amount
> 5. Notice that the amount is in one currency with the symbol of another currency (for example:- NPR100 expected: $100 or NPR (something))
> 
>  Screen.Recording.2024-02-08.at.17.53.37.mov

I'd say this is unrelated to this PR. This PR may have made this issue visible, as we were using the wrong function to display these messages before (I'm surprised no one fixed that earlier), but it is not really causing the issue

2024-02-08 15:29 UTC, Gonals commented
> > @Gonals I can still reproduce [this issue](https://github.com/Expensify/App/issues/34681). <img alt="Screenshot 2024-02-08 at 17 29 10" width="1440" src="https://private-user-images.githubusercontent.com/25876548/303314763-98986a6b-c436-46d7-9785-389aefddca58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTQxNTgsIm5iZiI6MTcwNzM5Mzg1OCwicGF0aCI6Ii8yNTg3NjU0OC8zMDMzMTQ3NjMtOTg5ODZhNmItYzQzNi00NmQ3LTk3ODUtMzg5YWVmZGRjYTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEyMDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMWY4MTAwM2M2ZDM5MmJkYjE2ZDIxZWFlNzUyNjY2MWEwZWUwOGZiY2ZiZGFkYWE5NmE1YjY3MTYzOTA4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AbziCNUcFhX2LrVKsQfY0eMzg334GbZ2zVhwDQhkhCg">
> > It first shows following message in LHN. <img alt="Screenshot 2024-02-08 at 17 29 38" width="293" src="https://private-user-images.githubusercontent.com/25876548/303314899-1ef4c4d9-b924-4db5-a0bc-cbc23903fd5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTQxNTgsIm5iZiI6MTcwNzM5Mzg1OCwicGF0aCI6Ii8yNTg3NjU0OC8zMDMzMTQ4OTktMWVmNGM0ZDktYjkyNC00ZGI1LWEwYmMtY2JjMjM5MDNmZDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEyMDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMmVjY2I1Y2QwNjgzMzQwMGE3N2YwM2I0ODY2MGEzOGMxODE2Y2Q4YmEyM2QxYjYyMTFjMjI2ZjBjMDQ3N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QqFzxPJ-19zQ8rG2qUc4QTHF0_9hWHKFtctX6VWZrUI">
> > which changes to following message after refreshing. <img alt="Screenshot 2024-02-08 at 17 30 10" width="293" src="https://private-user-images.githubusercontent.com/25876548/303315019-30a6a78d-5b0d-408c-a084-e32e5face2be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTQxNTgsIm5iZiI6MTcwNzM5Mzg1OCwicGF0aCI6Ii8yNTg3NjU0OC8zMDMzMTUwMTktMzBhNmE3OGQtNWIwZC00MDhjLWEwODQtZTMyZTVmYWNlMmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEyMDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZTA5OGRmN2NkZTkyMjk0YWMwNzkzZWE3NTc4MDk3OWU1YmUyZGUzNzA5NzU5MGUxYzgxY2EyYjIyODMxOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H5dVvlxW-YFWEwrHxmasLY7a2gyS0SpAy6kHSpI3wGI">
> 
> Taking another look! I wasn't able to see it happen, but it is likely due to me being in the `canUseReportFields` beta, which changes this behavior

I think this is fixed now. I wasn't able to reproduce it consistently before, but I've tried a few rounds and it seems to work fine now.

2024-02-12 15:30 UTC, sobitneupane commented
Thanks for the update @Gonals . I can no longer reproduce [this issue](https://github.com/Expensify/App/pull/34719#issuecomment-1933957332). I will perform more extensive tests and will update.

https://github.com/Expensify/App/assets/25876548/f5003701-eac3-4093-a703-d7a7780576ec

2024-02-13 08:52 UTC, sobitneupane reviewed
### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->

https://github.com/Expensify/App/assets/25876548/e0b5a1ad-0e2e-4f43-8deb-7fa7ea019c96


</details>

<details>
<summary>Android: mWeb Chrome</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>iOS: Native</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/25876548/a6169d47-1d0f-4d51-9ee9-15a3f283c69c


<!-- add screenshots or videos here -->

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/25876548/1387d45b-59fa-41a8-91bd-02e33f5a20d0


https://github.com/Expensify/App/assets/25876548/eb4a1f64-b801-4f13-907d-a13be07c86a9



</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/25876548/d578c459-3c99-4403-a0ee-b9e2cd8fcef6



</details>

2024-02-13 08:53 UTC, sobitneupane approved these changes
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

2024-02-13 18:27 UTC, blimpich requested changes

2024-02-13 18:27 UTC, blimpich commented on src/components/MoneyReportHeader.tsx
> +        // @ts-expect-error TODO: Remove this once IOU (https://github.com/Expensify/App/issues/24926) is migrated to TypeScript.
I think this has happened, see https://github.com/Expensify/App/pull/34092. Is it possible to get rid of this?

2024-02-14 18:41 UTC, blimpich approved these changes

2024-02-14 18:42 UTC, merged

2024-02-14 18:47 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-02-15 05:35 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7911420306) to staging by https://github.com/blimpich in version: 1.4.42-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-02-19 23:33 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7966217051) to production by https://github.com/chiragsalian in version: 1.4.42-5 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅