fix: Inconsistency of flashlight/torch behavior in Scan tab
Expensify/App pull request #34782
Opened 2024-01-19 04:48 UTC by tienifr

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/34457
PROPOSAL: https://github.com/Expensify/App/issues/34457#issuecomment-1890362015

### Tests

1. Login to native/mweb App
2. Tap FAB button
3. Tap Request money
4. Tap on flashlight icon to enable
5. Verify that the button should turn into a pressed state (highlighted), but the flash is not turned on yet
6. Tap on green circle to take a shoot with camera
7. Verify that the flash is turned on and the photo is taken in the flashlight effect

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as above

### QA Steps

1. Login to native/mweb App
2. Tap FAB button
3. Tap Request money
4. Tap on flashlight icon to enable
5. Verify that the button should turn into a pressed state (highlighted), but the flash is not turned on yet
6. Tap on green circle to take a shoot with camera
7. Verify that the flash is turned on and the photo is taken in the flashlight effect

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
        - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ [...]

2024-01-20 09:02 UTC, s77rt commented
I can't test this either. My phone does not seem to support the web camera feature neither the simulator. Will ask for someone to take over this PR review/test

2024-01-20 14:33 UTC, mananjadhav commented
@s77rt @tienifr I tested the adhoc builds on the Android and iOS Physical devices. Attached are the videos.

The expected result works fine on native iOS and Android app. mWeb Safari no flash light icon (expected result). mWeb Chrome turning on the flashlight has not impact on the camera flash.


Video for iOS native app.

https://github.com/Expensify/App/assets/3069065/cb0a4088-e554-49fe-8619-18e5dbaa81b1


Video for mWeb Safari.

https://github.com/Expensify/App/assets/3069065/0de9d365-0cc4-424e-a213-878bc2db29a5


Video for Android native app:

https://github.com/Expensify/App/assets/3069065/4f7c22f1-a7e3-4fa3-98ab-d7565fa96204

Video for mWeb Chrome.

https://github.com/Expensify/App/assets/3069065/504b1449-4de9-418d-afc7-d939caf1795b

2024-01-22 14:44 UTC, s77rt commented
@tienifr The use of setTimeout is discouraged. Can we instead implement a `Promise` for the get screenshot method?

2024-01-24 15:26 UTC, mananjadhav commented
Sure can we trigger the adhoc build? That would be the fastest to test.

2024-01-24 15:35 UTC, s77rt commented
@mountiny Can you please trigger adhoc build

2024-01-24 20:16 UTC, mountiny commented
https://github.com/Expensify/App/actions/runs/7645656648

2024-01-25 22:02 UTC, s77rt commented
@tienifr Why it's not working in this case? Shouldn't the `applyConstraints` promise guarantee that the flash in on?

2024-01-29 16:38 UTC, s77rt commented
The example on MDN https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/applyConstraints#examples shows like what we are doing should be possible. Maybe there is a problem with `getScreenshot`. Try to log a message after the promise resolves see if it's logged while the flash is on or not

2024-02-05 14:24 UTC, s77rt commented
That still does not make much sense. How is it possible that the flash is on and still get a photo with no flash? We shouldn't use setTimeout unless it's necessary. At this point I think we still need to know why this is failing

2024-02-11 20:26 UTC, s77rt commented
@tienifr Any updates here?

2024-02-22 19:20 UTC, s77rt commented
@tienifr Are you still working on this? Any updates on the investigation?

2024-02-23 14:40 UTC, s77rt commented
I think it may be better to bring this back to the drawing board (gh issue) and close this PR

2024-02-25 14:23 UTC, s77rt commented
> But at the time we call `getScreenshot`, the video stream doesn't have the torch effect yet

Why is that? If anything we should wait for the video stream to update. Using `setTimeout` is still a hacky solution here.

2024-02-27 11:01 UTC, s77rt requested changes

2024-02-27 11:01 UTC, s77rt commented on src/pages/iou/request/step/IOURequestStepScan/index.js
> +                    }, 2000);
I think we need to clear the timeout on unmount, otherwise we'd be trying access undefined values

2024-02-28 04:32 UTC, s77rt requested changes

2024-02-28 04:32 UTC, s77rt commented on src/pages/iou/request/step/IOURequestStepScan/index.js
> +        }
Move to `getScreenshot`

2024-02-28 04:32 UTC, s77rt commented on src/pages/iou/request/step/IOURequestStepScan/index.js
> +    }, [cameraRef, isFlashLightOn, getScreenshot]);
```suggestion
    }, [isFlashLightOn, getScreenshot]);
```

ref does not change

2024-02-28 04:32 UTC, s77rt commented on src/pages/iou/request/step/IOURequestStepScan/index.js
> +    const handleOnUserMedia = (stream) => {
Rename to what the function does instead of when it's called

2024-02-28 04:32 UTC, s77rt commented on src/pages/iou/request/step/IOURequestStepScan/index.js
> +                });
Race condition: What if the promise resolves after the page is unmounted?

2024-02-28 15:51 UTC, s77rt requested changes

2024-02-28 15:51 UTC, s77rt commented on src/pages/iou/request/step/IOURequestStepScan/index.js
> +        if (!cameraRef.current || !cameraRef.current.getScreenshot) {
```suggestion
        if (!cameraRef.current) {
```

Is there a case where `cameraRef.current` would be set and `cameraRef.current.getScreenshot` not?

2024-02-28 20:54 UTC, s77rt commented
@mountiny Can you please trigger an adhoc build?

2024-03-18 14:40 UTC, s77rt commented
@ishpaul777 Did the flash work as expected? I'm not sure I can tell a diff, try in a dark area

2024-03-18 14:45 UTC, s77rt commented
@ishpaul777 Please do same test on mWeb, it should have similar feel as in iOS

2024-03-18 15:07 UTC, s77rt commented
@ishpaul777 What's your device?

2024-03-18 16:46 UTC, s77rt commented
## Reviewer Checklist

- [X] I have verified the author checklist is complete (all boxes are checked off).
- [X] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [X] I verified the steps for local testing are in the `Tests` section
    - [X] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [X] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [X] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I verified tests pass on **all platforms** & I tested again on:
    - [X] Android: Native
    - [X] Android: mWeb Chrome
    - [X] iOS: Native
    - [X] iOS: mWeb Safari
    - [X] MacOS: Chrome / Safari
    - [X] MacOS: Desktop
- [X] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [X] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [X] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [X] I verified that all the inputs inside a form are aligned with each other.
    - [X] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->

https://github.com/ [...]

2024-03-18 16:48 UTC, s77rt commented
@tienifr Can you please clear up / remove duplicated testing steps and just specify that the flash should be turned on after pressing the shutter button

2024-03-18 16:49 UTC, s77rt commented
> Tap on flashlight icon to enable (verify nothing happens)

This may be confusing, the button should turn into a pressed state (highlighted). Instead specify that the flash is not turned on yet

2024-03-19 04:16 UTC, s77rt approved these changes

2024-03-19 17:48 UTC, luacmartins commented
@tienifr we have conflicts

2024-03-19 17:59 UTC, luacmartins approved these changes, later dismissed

2024-03-20 12:47 UTC, luacmartins approved these changes

2024-03-20 12:47 UTC, merged

2024-03-20 12:53 UTC, luacmartins commented
Tests were passing

2024-03-20 12:53 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-03-22 16:19 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8393044290) to staging by https://github.com/luacmartins in version: 1.4.56-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-03-27 04:48 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8446744500) to production by https://github.com/yuwenmemon in version: 1.4.56-8 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅