fix login background image moving down
Expensify/App pull request #34958
Opened 2024-01-23 10:59 UTC by shahinyan11

### Details

### Fixed Issues

$
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-01-24 16:36 UTC, hayata-suenaga commented
asked a contributor plus to review this PR first. Someone will come and review this soon

2024-01-25 17:18 UTC, shahinyan11 commented
@aimane-chnaif @hayata-suenaga  Please do not did any job on this PR I just added it for my proposal to show what change I suggest . Sorry if i did something wrong

2024-01-26 08:53 UTC, shahinyan11 commented
@aimane-chnaif How to crate draft PR and  Don't mark as ready .

2024-01-30 17:21 UTC, hayata-suenaga commented
is this draft or ready for review?

2024-01-30 17:58 UTC, s77rt requested changes

2024-01-30 17:58 UTC, s77rt commented on src/pages/signin/SignInPageLayout/BackgroundImage/index.ios.js
Revert. Do not wrap the component itself. Instead wrap it's instance on the SignInPageLayout

2024-01-30 17:58 UTC, s77rt commented on src/pages/signin/SignInPageLayout/index.js
Revert

2024-01-30 17:58 UTC, s77rt commented on src/styles/index.ts
Revert

2024-01-30 18:38 UTC, shahinyan11 commented on src/styles/index.ts
My proposal causes regression on the small screens of the Web. And so I made additional changes to avoid this regression. The latest changes are made to ensure that all changes work only for IOS

2024-01-30 18:45 UTC, shahinyan11 commented on src/pages/signin/SignInPageLayout/BackgroundImage/index.ios.js
We have bug on the small screens of the Web. And so I made additional changes to avoid this regression. The latest changes are made to ensure that all changes work only for IOS . And since the changes should be affect only on IOS wrap its instance on the SignInPageLayout will not work too

2024-01-31 09:03 UTC, shahinyan11 commented on src/pages/signin/SignInPageLayout/index.js
Our previous changes caused an error on the small screen of Web, So I made some changes. please check them and approve

2024-01-31 09:05 UTC, shahinyan11 commented on src/styles/index.ts
The same as [above](https://github.com/Expensify/App/pull/34958#discussion_r1472504600)

2024-01-31 09:08 UTC, shahinyan11 commented
@s77rt We have had a bug on the small screens of web.I made some changes, please review and approve them if everything is ok

2024-01-31 09:31 UTC, shahinyan11 commented on src/pages/signin/SignInPageLayout/BackgroundImage/index.ios.js
I will cause  bugs for other platforms

2024-01-31 12:21 UTC, shahinyan11 commented
@s77rt I made some new changes to preserve the current UI on other platforms because they changed a bit after our changes. Please check them and approve  if everything is ok

2024-01-31 12:36 UTC, s77rt commented
@shahinyan11 Please apply the requested changes and explain the bug you are referring to. This PR should only effect one file.

2024-01-31 13:27 UTC, shahinyan11 commented
@s77rt  Now We have such error on Web small screens 

![Screenshot 2024-01-31 at 17 17 37](https://github.com/Expensify/App/assets/46921547/d9254385-85b7-4166-868b-37e984de6f5d)

This is because we updated the styles and now [here](https://github.com/Expensify/App/blob/9d4c634a87890ccbdcc2efe353ae9d929aa5530b/src/pages/signin/SignInPageLayout/BackgroundImage/index.js#L23C20-L23C43) should be used  `styles.signInBackgroundImage` instead `styles.signInBackground`.

2024-01-31 13:34 UTC, s77rt commented
@shahinyan11 We shouldn't be changing any style here. There should be only one change which is to add a wrapping view in SignInPageLayout

2024-01-31 13:38 UTC, shahinyan11 commented
@s77rt Adding wrapping view demands changing style of his child

2024-01-31 13:45 UTC, s77rt commented
The wrapping view shouldn't have the same style as the child. Keep the style of the child untouched.

The wrapping view should be something like that:
```js

                      <View
                            style={[
                                styles.pAbsolute,
                                styles.w100,
                                StyleUtils.getHeight(Math.max(variables.signInContentMinHeight, containerHeight)),
                                StyleUtils.getBackgroundColorStyle(theme.highlightBG),
                            ]}
                        >
                            <BackgroundImage />
                        </View>

```

2024-01-31 13:48 UTC, shahinyan11 commented
> The wrapping view shouldn't have the same style as the child. Keep the style of the child untouched.

@s77rt  we took the absolute style from the шьфпу and gave it to wrapping view. There is no point in leaving absolute style for the child ( image )

2024-02-01 16:22 UTC, s77rt requested changes

2024-02-01 16:22 UTC, s77rt commented on src/pages/signin/SignInPageLayout/index.js
> +                            {backgroundColor: theme.signInPage},
```suggestion
                            StyleUtils.getBackgroundColorStyle(theme.signInPage),
```

No inline styles

2024-02-01 16:22 UTC, s77rt commented on src/pages/signin/SignInPageLayout/index.js
> +                            StyleUtils.getMinimumHeight(Math.max(variables.signInContentMinHeight, containerHeight)),
Define `Math.max(variables.signInContentMinHeight, containerHeight)` as `backgroundImageHeight`

2024-02-01 16:27 UTC, s77rt commented
@shahinyan11 Please change the PR title to something more explanatory (what's being changed in the PR) also fix the checklist (the part `I linked the correct issue `)

2024-02-01 16:45 UTC, shahinyan11 commented
@s77rt  And what about my comment above related with android bug ?

2024-02-01 16:54 UTC, s77rt commented
@shahinyan11 Can you please clarify which bug? Is there still a reproducible bug here?

2024-02-01 17:02 UTC, shahinyan11 commented
We should set `{backgroundColor: theme.signInPage}` only for IOS to avoid below bug on Android. Android uses another image as the background and the bottom color of that image is different from the bottom color of the image that IOS uses.

![Screenshot 2024-01-31 at 17 59 47](https://github.com/Expensify/App/assets/46921547/5c146018-d65c-4527-9076-88c1ff055109)

@s77rt What do you think about using
StyleUtils.getBackgroundColorStyle(isIOSNative ? theme.signInPage : null)

2024-02-02 19:38 UTC, s77rt commented
@shahinyan11 This seems like a different bug as I can see the three color layers on main. Also, is there a real case where this is reproducible? (besides hard coding a long error)

<img width="489" alt="Screenshot 2024-02-02 at 8 25 19 PM" src="https://github.com/Expensify/App/assets/16493223/61468b31-3b41-4bec-81a4-14b416ca286e">

2024-02-03 08:27 UTC, shahinyan11 commented
@s77rt 

https://github.com/Expensify/App/assets/46921547/282070d6-6756-4606-a2d2-787bad70ed39

2024-02-03 09:11 UTC, shahinyan11 commented
@s77rt Yes I am agree with you that there is another error too. Actually, there are several bottlenecks 
1. What is the point of using different images for IOS and Android ?
2. Why use [gradient layer](https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/signin/SignInPageLayout/Footer.js#L157C1-L164C26) for a smooth color transition instead LinearGrading ?
3. The [gradient layer](https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/signin/SignInPageLayout/Footer.js#L157C1-L164C26) does not work for IOS at all and on Android it works bad ( not smoothly )

2024-02-04 12:41 UTC, s77rt commented
Write a util style function (something like `codeStyles`) to return the correct platform-dependent background.

2024-02-04 23:51 UTC, s77rt commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->
https://github.com/Expensify/App/assets/16493223/12d4e130-fac8-4d28-a67e-883689e2c868



</details>

<details>
<summary>Android: mWeb Chrome</summary>

<!-- add screenshots or videos here -->
https://github.com/Expensify/App/assets [...]

2024-02-05 00:11 UTC, s77rt requested changes

2024-02-05 00:11 UTC, s77rt commented on src/styles/utils/signInPageStyles/index.ts
NAB. Rename folder to getSignInBgStyles

2024-02-05 00:11 UTC, s77rt commented on src/styles/utils/signInPageStyles/index.ios.ts
Don't we need to do this for web as well? Not that it makes any diff as on web the height is limited but I think android is the platform that is different than the rest not ios.

index.ts returns theme.signInPage as bg color
index.android.ts returns no specifc bg color

2024-02-06 22:49 UTC, s77rt commented
@shahinyan11 Any updates here?

2024-02-07 07:16 UTC, shahinyan11 commented on src/styles/utils/signInPageStyles/index.ios.ts
No. Only IOS need specified background color. Other platforms use a background image whose bottom color is different from the bottom color of the background image that iOS uses.

2024-02-07 14:57 UTC, s77rt approved these changes

2024-02-07 14:59 UTC, s77rt commented
@shahinyan11 Try merge main see if it fixes the failing perf test

2024-02-08 19:06 UTC, rlinoz approved these changes

2024-02-08 19:07 UTC, merged

2024-02-08 19:11 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-02-12 14:20 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7872745855) to staging by https://github.com/rlinoz in version: 1.4.40-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|failure ❌

2024-02-13 18:25 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/7890953833) to production by https://github.com/mountiny in version: 1.4.40-5 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|failure ❌