show recents in participants page based on action type
Expensify/App pull request #35431
Opened 2024-01-30 19:21 UTC by rojiphil

@eVoloshchak @mountiny

### Details

TODO

### Fixed Issues
$ https://github.com/Expensify/App/issues/34227
PROPOSAL: https://github.com/Expensify/App/issues/34227#issuecomment-1908444762

### Tests

**Steps**
TODO

- [ ] Verify that no errors appear in the JS console

### Offline tests

Same as the Steps in Tests Section.

### QA Steps

Same as the Steps in Tests Section.

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
        - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR author ch [...]

2024-01-31 14:45 UTC, mountiny commented
thanks! thats your eta to get this ready for a review?

2024-01-31 22:15 UTC, rojiphil commented
Sorry. Unfortunately, I could not complete this today. 
And, I think I may need more time as this is complex enough to easily cause regressions.
Since it’s late night here, I will have a look into this tomorrow and arrive at a proper ETA.

2024-02-01 17:38 UTC, rojiphil commented
@eVoloshchak @mountiny

The PR is ready for review. 

I have documented the implementation details in `Details` section of the checklist.
Also, I have tested with web safari environment and works well too. 

Post review, I will complete testing for the remaining environments too.

Thanks for your patience.

2024-02-01 17:43 UTC, eVoloshchak commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Android: mWeb Chrome</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>iOS: Native</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary> [...]

2024-02-01 19:46 UTC, eVoloshchak requested changes

2024-02-01 19:46 UTC, eVoloshchak commented on src/libs/OptionsListUtils.ts
> +    actionTypeForParticipants?: string;
`type ActionType = ValueOf<typeof CONST.REPORT.TYPE | typeof CONST.IOU.TYPE | typeof CONST.IOU.REQUEST_TYPE>;`
```suggestion
    actionTypeForParticipants?: ActionType;
```

2024-02-01 19:46 UTC, eVoloshchak commented on src/libs/OptionsListUtils.ts
> +    const isMoneyRequestActionTypeForParticipants =
If `isTaskActionTypeForParticipants=true`, `isMoneyRequestActionTypeForParticipants` will be false, we don't have to check it in this case
```js
const isMoneyRequestActionTypeForParticipants = !isTaskActionTypeForParticipants && (
        actionTypeForParticipants === CONST.IOU.REQUEST_TYPE.MANUAL ||
        actionTypeForParticipants === CONST.IOU.REQUEST_TYPE.SCAN ||
        actionTypeForParticipants === CONST.IOU.REQUEST_TYPE.DISTANCE ||
        actionTypeForParticipants === CONST.IOU.TYPE.SPLIT);

2024-02-01 19:46 UTC, eVoloshchak commented on src/libs/TransactionUtils.ts
> +                    transaction != null && (actionType === CONST.IOU.TYPE.SPLIT ? isSplitRequest(transaction) : getRequestType(transaction) === actionType),
This is a little bit hard to read, I think a helper method (something like `getTransactionActionType`, essentially a combination of `isSplitRequest` and `getRequestType`) would be useful here

2024-02-01 19:52 UTC, eVoloshchak commented
Bug:

1. Click Global FAB -> Request Money -> Manual tab
2. Enter an amount
3. Click Next, select a user (`userA`) from the Participants list
4. Click Request
5. Click Global FAB -> Request Money -> Manual tab 
6. Enter an amount, click Next
7. Verify that recents list shows `userA`as the first one
8. Click Global FAB -> Request Money -> Scan tab
9. Upload a receipt file
10. Select a different user (`userB`) from the Participants list
11. Click Request
12. Click Global FAB -> Request Money -> Manual tab
13. Enter an amount, click Next
14. The first user in recents list is `userB`, while it should be `userA`, since this is a manual tab


https://github.com/Expensify/App/assets/9059945/a82fdd6f-3e8f-4f45-a6f6-65d0f76b8407

2024-02-02 13:55 UTC, rojiphil commented
> 14\. The first user in recents list is `userB`, while it should be `userA`, since this is a manual tab

In your test video, I notice that User `copyreading+099@gmail.com` had two existing requests present when the `scan` receipt was generated. 
Can you please check if one of the other two requests is `manual`? 

And if there is a `manual` request, I think it is expected to show `copyreading+099@gmail.com` at the top for this new `manual` request because this is the most recent report which had changes and which also has a `manual` request in it.  
Does this make sense?

2024-02-02 18:48 UTC, rojiphil commented
@eVoloshchak 
Thanks for your feedback. I have integrated your feedback comments. Tests well too.
Please review.

2024-02-03 10:19 UTC, rojiphil commented
@mountiny @eVoloshchak 
I just added a section `Points to note` in the PR details description [here](https://github.com/Expensify/App/pull/35431#issue-2108589328) with some open points.
What are your thoughts on these?

2024-02-03 17:10 UTC, eVoloshchak commented
https://github.com/Expensify/App/assets/9059945/df4b1eb8-7ae6-4626-b4bc-5f3f42251334

Blocked by this issue (also present on `main`), endless skeleton view after logging in

2024-02-05 10:40 UTC, mountiny commented
@eVoloshchak can you run `npm ci` please?

2024-02-05 16:44 UTC, eVoloshchak commented
@mountiny, that did the trick, thank you!

2024-02-05 16:44 UTC, eVoloshchak commented
> Since we depend on transactions and task reports to find the most recent chat reports, it is possible that we do not find the most recent chat report just because the dependant transactions and task reports are not available locally in Onyx even though the chat report is locally available. This scenario would most likely occur when the remote user generates a transaction/task that is not yet accessed locally by the local user or during a fresh sign-in.

This is a valid point. Especially if you consider the case where the user is logged in on multiple devices, the transactions won't be available locally
@mountiny, is this something we'd like to resolve (also that would require quite a few changes on the back end)?

> The existing implementation considers recent changes only within chat reports while showing the recent list of participants’ page. This means that changes in transaction reports, task reports, money request reports, and thread reports would not be considered while showing the recent list on the participants’ page.

_I think_ it should include all of the available transactions (not only from chat reports). @mountiny, do you agree?

> It may be possible that the transaction/task report and the parent chat report are locally present but the intermediate reports are not present locally. Such chat reports will be missing from the recent list as they could not be traced back from the transaction/task report.

This is similar to the first point, it would require changes to the back end (not sure how feasible it is, we can't load ALL of the transactions. We could load only the recent ones, since it's all we need)

2024-02-05 19:00 UTC, mountiny commented
> is this something we'd like to resolve (also that would require quite a few changes on the back end)?

Lets just use this when its available for now any backend changes would have to be planned more

> I think it should include all of the available transactions (not only from chat reports)

Not sure what this means exactly, when you request money its on the expense reports, tasks can be anywhere

> This is similar to the first point, it would require changes to the back end (not sure how feasible it is, we can't load ALL of the transactions. We could load only the recent ones, since it's all we need)

again, if not available default to the classic behaviour

2024-02-06 19:49 UTC, rojiphil commented
@mountiny

Thanks for your feedback. 
So, that means two queries got clarified, and only one more is left. Here are some more details about this query.

> Not sure what this means exactly, when you request money its on the expense reports, tasks can be anywhere

Let’s take the example of a money request. 
When we generate a money request (say Manual), there are three reports representing this `manual` request. A) Chat Report B) Expense/IOU Report C) Transaction Details Report. Currently, we only look at the Chat Report to see if that has changed to qualify for a berth in the recent list. The question here is this:
Do we also have to look at the changes in the expense/iou report and transaction detail report for adding the participant to the recent list is the question here?

Also, a similar question arises for tasks as well. While the parent chat report of the task may not have changed, the task report itself may have a new comment added recently. 
Does that mean the participant will be added to the recent list because of the new comment in the task report?

2024-02-08 20:51 UTC, mountiny commented
@rojiphil for requests, we care about the highest context - so the DMs or the workspace chat

for tasks we care about the particular page, so if I created a task in some report with reportID = 123 I want to add it there

2024-02-09 19:22 UTC, rojiphil commented
Thanks for bringing clarity on these. 

> for requests, we care about the highest context - so the DMs or the workspace chat

Ok. So, the current implementation is good enough here.

> for tasks we care about the particular page, so if I created a task in some report with reportID = 123 I want to add it there

Ok. So, here we care only about the parent report of the task report via `parentReportID`. 
Currently, the implementation cares about the top-most report. 
I will change this to consider only the parent report and resend it for review again.

2024-02-12 19:20 UTC, rojiphil commented
Update:
The work is still in progress on the PR here. The changes look good and testing is in progress.
I will be able to send it across for review tomorrow my day.

2024-02-13 20:09 UTC, rojiphil commented
@eVoloshchak 
I have updated the PR checklist with additional details + screenshots for 4 platforms.
As the PR looks good in testing, please review the recent changes and let me know if any changes are required.
Meanwhile, I will complete the testing on the remaining 2 platforms (i.e. android & mweb chrome) tomorrow.

2024-02-14 07:54 UTC, rojiphil commented
@eVoloshchak 
The remaining platforms are also tested and works well. 
The PR checklist is also done.
All yours for review.

2024-02-15 19:34 UTC, eVoloshchak commented
https://github.com/Expensify/App/assets/9059945/a4660162-b4a3-41e0-b4b2-36241592f60d

There's a bug when performing a manual request. It works correctly when requesting money from a user you haven't interacted with, but an existing user with already existing IOU requests is not at the top of recents list
cc: @rojiphil

2024-02-16 04:15 UTC, rojiphil commented
> There's a bug when performing a manual request. It works correctly when requesting money from a user you haven't interacted with, but an existing user with already existing IOU requests is not at the top of recents list

@eVoloshchak 
Exactly. That’s what I meant in the following note to QA in PR description.

>	1	While testing money request steps, if there is an existing Report Preview due to open money requests, the Report Preview timestamp does not update. Because of this, adding a new money request when there are previous open money requests will not bring this report in the top of the recent list. So, for testing this PR, please ensure that there are no previous open money requests. This means that all the previous money requests must be paid.

This looks like a regression introduced recently in the latest main. 
Attaching a test video to demonstrate this:
Or is this intentionally added recently? 
What do you think?
cc @mountiny 


https://github.com/Expensify/App/assets/3004659/aa4861a1-1804-4ad5-b100-bd669b958ba7

2024-02-16 12:44 UTC, mountiny commented
@rojiphil @eVoloshchak I think my main concern with this change is the impact on performance. Its quite a big change to the already tight getOptions method. 

Could you time the difference the getOptions take on main vs this branch for the same high-traffic account?

2024-02-19 03:29 UTC, rojiphil commented
> I think my main concern with this change is the impact on performance. Its quite a big change to the already tight getOptions method.
> 
> Could you time the difference the getOptions take on main vs this branch for the same high-traffic account?

I think I get your concern. Looking into this today.

2024-02-19 18:10 UTC, rojiphil commented
> I think my main concern with this change is the impact on performance. Its quite a big change to the already tight getOptions method.
> Could you time the difference the getOptions take on main vs this branch for the same high-traffic account?

While experimenting with `Timing.start` and `Timing.end` within `getFilteredOptions` [here](https://github.com/rojiphil/App/blob/a485edd68c3164477393175570c185e455a57bea/src/libs/OptionsListUtils.ts#L1844C1-L1887C2) on my HT account, I could not notice any significant difference between the latest main and feature branch. For money requests, the timings remain around 100ms whereas for tasks it comes to around 50ms.  Maybe we need to do more tests here.  @eVoloshchak Can you also please check on your HT account if there is a noticeable timing difference?

Here are the results:
![Screenshot 2024-02-19 at 11 35 26 PM](https://github.com/Expensify/App/assets/3004659/23d7d446-402a-4eeb-a0a2-39f8ab2bb4ef)

And, here are the test videos for reference:
<details>
<summary>Main Branch</summary>

https://github.com/Expensify/App/assets/3004659/ec928b7a-1ecc-4c92-bcfd-b239506ddff6

</details>

<details>
<summary>Feature Branch</summary>

https://github.com/Expensify/App/assets/3004659/cd26f15d-01ce-4ad8-931c-446a6a60ab16

</details>

2024-02-19 18:15 UTC, rojiphil commented
>  I think you could use the transactions created for that too

Currently, I am looking into this to see how we can use transactions `created` and get this done optimally. I will provide an update on this tomorrow my day.

2024-02-19 20:02 UTC, mountiny commented
@rojiphil can you merge main? I will try to create a build and then we can test on those with large accounts from internal employees

2024-02-20 03:01 UTC, rojiphil commented
> can you merge main? I will try to create a build and then we can test on those with large accounts from internal employees

@mountiny I just merged. But, I am new to this `Ready to Build` state. So, not sure if you want the merge to be done just before generating the build. Anyway, I will make myself available during your day so that we can take this forward.

2024-02-20 03:17 UTC, rojiphil commented
> and then we can test on those with large accounts from internal employees

I love this idea. Along with the performance check, I think this will also help us get feedback on the feature logic itself if any.

2024-02-20 19:13 UTC, mountiny commented
I have triggered the build

2024-02-20 23:45 UTC, mountiny commented
@kacper-mikolajczak @adhorodyski also curious what you think of the changes in the PR and if you can see there woul dbe potential impact on performance

2024-02-22 03:58 UTC, rojiphil commented
I just merged again to resolve a merge conflict

2024-02-22 04:26 UTC, rojiphil commented
> I've measured `getFilteredOptions` taking ~30% more time compared to `main`
> On a HT account the time fluctuates around 100-150ms, no noticeable difference compared to `main` when using the app

I think you are referring to the fluctuations when you mentioned ~30%. Is this correct?

2024-02-22 04:28 UTC, rojiphil commented
Also, I just re-reviewed the changes we made in this PR. While I can think of `getTransactionsByActionType` [here](https://github.com/rojiphil/App/blob/2bfaf542dc8e5c9ccb88d5c7fa31ae96c3d19f8f/src/libs/OptionsListUtils.ts#L1569) that can take some time when there are lots of transactions, we have neatly called this only for recent list fetch of money requests. Further, we have also ordered the transactions so that the most recent ones will be at the top for a quick search. Also, we return early after finding out the most recent `n` reports. On the other side, if no transactions are found at all, the default flow remains pretty much the same.  So, purely from the code perspective, while I agree that there will be additional computations I do not know what can cause a major hit on performance. 
Curious to know your thoughts as well on any suspicious code that can impact performance. 

One of the alternatives we can consider is relying only on transactions to arrive at the recent list. But this would mean that we have to agree on not supporting the `Test 6` case. And I am not sure if we want to go this way. Also, I do not see any significant advantage here as we return early after identifying the most recent `n` reports.

2024-02-25 23:08 UTC, eVoloshchak commented
> I think you are referring to the fluctuations when you mentioned ~30%. Is this correct?

@rojiphil, I meant that with this change calling `getFilteredOptions` takes 30% more time on average (very roughly)
In practical terms, it means these changes are adding 30-50 ms, which given that the HT account has hundreds of contacts, doesn't seem like a problem

2024-03-03 19:29 UTC, mountiny commented
30% sounds quite a lot to be fair this can go out of hands with heavy accounts (much larger than high traffic - its closer to what admins of large policies can experience)

2024-03-04 17:36 UTC, rojiphil commented
> 30% sounds quite a lot to be fair this can go out of hands with heavy accounts (much larger than high traffic - its closer to what admins of large policies can experience)

I am still not sure of the 30% impact on performance. But I also agree that having that kind of impact would not be good. Not feeling quite well today. I will have a fresh look at this tomorrow and provide an update.

2024-03-05 12:10 UTC, rojiphil commented
I just checked again. And surprisingly, my HT account gives better performance for this PR implementation than the earlier (default) implementation. But I don't think the PR implementation has optimized the earlier implementation. Looks like for `manual` action type, the reports for the recent transactions were already on the top of `allReportOptions`. Also attaching the summary screenshot and test videos for reference.

For now, I have committed some code changes for timing logs. While the code can be tested as it is for the new logic, the earlier default logic can be tested by just replacing `actionTypeForParticipants` [here](https://github.com/rojiphil/App/blob/5a5d986eb9474acfc77c17dea07365d05b8c0cac/src/pages/iou/request/MoneyTemporaryForRefactorRequestParticipantsSelector.js#L142) with an empty string. Additionally, we can uncomment [here](https://github.com/rojiphil/App/blob/5a5d986eb9474acfc77c17dea07365d05b8c0cac/src/libs/OptionsListUtils.ts#L1685C1-L1689C9) to know the current action type used. And the timing log is already available [here](https://github.com/rojiphil/App/blob/5a5d986eb9474acfc77c17dea07365d05b8c0cac/src/libs/actions/Timing.ts#L55).  
Please try this out on your HT account. Curious to know how the timing logs turn up for you. 
 
Regarding the implementation logic itself, I think the only implementation that can add significant time complexity is the fetching of transactions. For this, I have shared my comment [here](https://github.com/Expensify/App/pull/35431#issuecomment-1958679077). What do you think about this? 

cc @mountiny @eVoloshchak 

<details>
<summary>Recent Reports By Action Type</summary>

https://github.com/Expensify/App/assets/3004659/6fb0e33c-7498-41f2-850c-0ce981e88736

</details>

<details>
<summary>Recent Reports By Default</summary>

https://github.com/Expensify/App/assets/3004659/96912925-fc1e-4eff-84aa-f86535b312a2

</details>

![Screenshot 2024-03-05 at 3 30 39 PM](https://github.com/Expensify/App/assets/3004659/04600c52-3da7-4302-b05b-633722f64266)

2024-03-10 16:31 UTC, rojiphil commented
Looks like we are stuck on the issue of 30% impact on performance which honestly I am not able to quantify. Even in the `main` branch without any of our PR changes, I see a similar behavior as mentioned [here](https://github.com/Expensify/App/pull/35431#issuecomment-1978621619). So, not sure of the way ahead.
@eVoloshchak @mountiny What do you think we could do to take this forward from here?

2024-03-11 13:24 UTC, mountiny commented
@rojiphil I have asked for some other eyes on this PR but yeah I guess we will have to try this out. @rojiphil could you sync up with main please?

2024-03-11 14:27 UTC, hurali97 commented on src/libs/TransactionUtils.ts
> +            .reverse()
Why do we need to sort and then reverse? By the looks of it, we can achieve the same if we just flip the condition while sorting:

```suggestion
            .sort((transactionA, transactionB) => (transactionA?.created && transactionB?.created && transactionA?.created < transactionB?.created ? 1 : -1))
```

2024-03-11 15:39 UTC, rojiphil commented on src/libs/OptionsListUtils.ts
> +    // }
This code was temporarily added to assist in testing for C+ as mentioned [here](https://github.com/Expensify/App/pull/35431#issuecomment-1978621619). Let me remove the code as it was temporary code anyway.

2024-03-11 16:17 UTC, rojiphil commented on src/libs/OptionsListUtils.ts
> +    // }
Committed changes after removing code related to timing logs.

2024-03-11 18:49 UTC, rojiphil commented
Thanks @hurali97 for your review comments. I have integrated your feedback and committed the code changes. 
Please let me know if any other review feedback changes need to be made.

2024-03-12 23:10 UTC, mountiny commented
@rojiphil just to give us more confidence @OlimpiaZurek is implementing reassure tests for getOptions method which will hopefully give us more peace in mind for this change if all goes well https://github.com/Expensify/App/issues/38165

2024-03-20 19:09 UTC, mountiny commented
@rojiphil The new reassure test is merged so can you sync up with main please to we can see if there will be any diff shown? https://github.com/Expensify/App/pull/38387

2024-03-21 16:58 UTC, rojiphil commented
@mountiny Merged. Regarding reassure test, I am not aware of the internals of the reassure performance but I searched for `getFilteredOptions` in logs and this is what I got. Hopefully, I am looking at the right place.

![Screenshot 2024-03-21 at 10 13 26 PM](https://github.com/Expensify/App/assets/3004659/001231a2-7335-408e-991b-0d4f24b53dd0)

This seems ok to me. Also, if we are moving ahead, I will need to test this once more as quite some time has passed since we implemented this.

2024-03-31 20:09 UTC, mountiny commented
@rojiphil yeah that is what we are looking for, however I agree that to properly capture the impact we might need more complex scenario here. 

Can you please resolve the conflicts and retest?

2024-04-03 11:25 UTC, mountiny commented
@rojiphil more conflicts

2024-04-05 18:48 UTC, rojiphil commented
> more conflicts

Sorry. I was not able to spend time on resolving conflicts. I will prioritize my day tomorrow on resolving them and retesting.

2024-04-08 10:18 UTC, rojiphil commented
> Can you please resolve the conflicts and retest?

Resolved the conflicts and retested too. It needed minor fixes but the core logic remains the same. The reassure performance tests also passed well. LGTM.

2024-04-08 19:45 UTC, rojiphil commented
> Test 1: Task Creation is failing for me

@eVoloshchak That’s an interesting observation. I was not able to get this problem as I was not that quick in coming back to the task creation to check if the assignee participants page is updated. For some weird reason, here it looks like the reports do not immediately include the newly created task report which is why the assignee participants page is not updated. However, this is only observed for a short period of time. It may be that the API response/pusher updates will later populate the reports with the newly created report and the assignee participants page will show the updated participants. Although I think we should fix this I also think this falls outside the scope of our current work here. Also, as it is momentary in nature it may also quality as a super-edge case. Anyway, I am making a note of this in the PR description. Does this make sense?


https://github.com/Expensify/App/assets/3004659/c14222e3-bc2f-477b-b210-df6a0a6fcd90

2024-04-10 11:28 UTC, eVoloshchak commented
> It may be that the API response/pusher updates will later populate the reports with the newly created report and the assignee participants page will show the updated participants. Although I think we should fix this I also think this falls outside the scope of our current work here. Also, as it is momentary in nature it may also qualify as a super-edge case

Can confirm it does work after some time (or a page refresh). 
My main concern is that also means this feature won't work while offline, since we need to wait for the API response
How hard would it be to use pending actions in addition to recent actions to fix this?
On a side note, could you merge main please?

2024-04-15 14:13 UTC, eVoloshchak commented
> My main concern is that also means this feature won't work while offline, since we need to wait for the API response
How hard would it be to use pending actions in addition to recent actions to fix this?

@rojiphil, gentle bump on this question

2024-04-19 02:17 UTC, rojiphil commented
It looks like the option list is not getting updated for the intermediate reports and gets updated only for the last updated report when there are multiple reports updated at the same time. In our use case here, we update two reports at the same time i.e. `Assignee Report` and `Parent Report`. The attached screenshot for logs how the assignee report does not get considered for option list updation but the parent report does [here](https://github.com/Expensify/App/blob/9d7ebf2866a144d823081bf78022096f3f8f4b65/src/components/OptionListContextProvider.tsx#L65). We consider only the `lastUpdatedReport` [here](https://github.com/Expensify/App/blob/e0ebfd683136519e231146302b62c75157bd80a2/src/components/OptionListContextProvider.tsx#L59). This is the reason for the problem mentioned [here](https://github.com/Expensify/App/pull/35431#issuecomment-2043291681). To be able to consistently reproduce the problem, we can test this in offline scenarios. A recent PR [here](https://github.com/Expensify/App/pull/38207) for caching search options introduced these changes.  

@eVoloshchak  Can you please confirm if you share a similar understanding here?

![Screenshot 2024-04-18 at 4 45 15 PM](https://github.com/Expensify/App/assets/3004659/e780de92-eb6d-40aa-a358-8cfc818571d4)

2024-04-24 16:30 UTC, eVoloshchak commented
> It looks like the option list is not getting updated for the intermediate reports and gets updated only for the last updated report when there are multiple reports updated at the same time. In our use case here, we update two reports at the same time i.e. Assignee Report and Parent Report. The attached screenshot for logs how the assignee report does not get considered for option list updation but the parent report does [here](https://github.com/Expensify/App/blob/9d7ebf2866a144d823081bf78022096f3f8f4b65/src/components/OptionListContextProvider.tsx#L65). We consider only the lastUpdatedReport [here](https://github.com/Expensify/App/blob/e0ebfd683136519e231146302b62c75157bd80a2/src/components/OptionListContextProvider.tsx#L59). This is the reason for the problem mentioned https://github.com/Expensify/App/pull/35431#issuecomment-2043291681.

@rojiphil, thank you for the thorough explanation!
It is my understanding that we don't need a `lastUpdatedReport` variable, is that correct?
> It looks like the option list is not getting updated for the intermediate reports and gets updated only for the last updated report when there are multiple reports updated at the same time. In our use case here, we update two reports at the same time i.e. Assignee Report and Parent Report. 

This is the actual bug we need to fix. Was it introduced by https://github.com/Expensify/App/pull/38207?

2024-04-27 20:14 UTC, rojiphil commented
> This is the actual bug we need to fix. Was it introduced by #38207?

@eVoloshchak Yes. That's correct. The performance improvement via caching search options caused this.

2024-08-24 17:46 UTC, closed without merging