[No QA] fix menu placement is broken on mobile
Expensify/App pull request #3635
Opened 2021-06-17 13:52 UTC by parasharrajat

### Details
Reverted accidentally deleted file. and refactor Code for IOS.

### Fixed Issues

Fixes #3633

### Tests | QA Steps
1. Open any chat on Mobile.
2. open context menu on any message.
3. It should open correctly from bottom to top.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-06-17 13:53 UTC, parasharrajat commented
It's a little urgent and I believe needs to go to Production.

2021-06-17 16:48 UTC, roryabraham commented
@parasharrajat Please provide screenshots for this PR

2021-06-17 16:52 UTC, parasharrajat commented
Uploading

2021-06-17 21:46 UTC, parasharrajat commented
@roryabraham Updated.

2021-06-17 23:28 UTC, roryabraham requested changes

2021-06-17 23:28 UTC, roryabraham commented on src/components/Popover/index.native.js
> +export default withWindowDimensions(Popover);
Can we safely get rid of `withWindowDimensions` here? Seems unnecessary.

2021-06-17 23:30 UTC, Luke9389 submitted a review, later dismissed
I was the one who deleted the `.native` index file, but now I see that we need both because of the `ReactDOM.createPortal` usage. I think it was just bad timing that we did this at the same time.

2021-06-18 07:01 UTC, parasharrajat commented
Updated. Let's merge this quickly

2021-06-18 16:53 UTC, parasharrajat commented
Let's merge this @roryabraham It's fixing deploy blockers.

2021-06-18 18:01 UTC, roryabraham approved these changes

2021-06-18 18:01 UTC, merged

2021-06-18 18:01 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-06-18 19:00 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/950720545) to staging in version: 1.0.71-1🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-06-18 19:24 UTC, roryabraham commented
Heads up I think this may have caused a regression where the global create menu is sliding in right-to-left

2021-06-18 19:26 UTC, parasharrajat commented
Oh. Sending another PR. Didn't notice that part.

2021-06-18 20:43 UTC, parasharrajat commented
Follow-up PR is ready here #3684.  Thanks

2021-06-25 18:29 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/972294561) to production in version: 1.0.73-3🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅