Fix client side tag violations and Improve function signatures
Expensify/App pull request #36821
Opened 2024-02-20 00:56 UTC by cead22

### Details

- This started as a follow up to this PR https://github.com/Expensify/App/pull/33969 to address comments we didn't get to address before the end of last week when Infinite Red finished working with us on violations. Namely, updating the method signatures of TransactionUtils.hasViolation, TransactionUtils.getTransactionViolations, and ReportUtils.isSettled
- I was getting `Malformed currency code` when testing ([see slack thread in expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1708384127377139)), so I added a fix to this PR
- I also noticed the missing tag violation wasn't working and dug into it, and added a fix as well (I believe it was broken here https://github.com/Expensify/App/pull/34983)

### Fixed Issues

- Followup to https://github.com/Expensify/App/pull/33969
- PROPOSAL: N/A

### Tests
> [!important]
> You must be on the **violations** beta and have policy expense chats enabled on the workspace you're using to test ([SO](https://stackoverflowteams.com/c/expensify/questions/17518/17519#17519))

- Configure a workspace in old dot with
    - Max expense amount set to $5
    - Tags required, and 2 enabled tags
    - Categories required and 2 enabled categories
- 

- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Sc [...]

2024-02-20 03:50 UTC, allroundexperts commented
@cead22 Am I supposed to review this? This one seems to be a WIP.

2024-02-20 16:40 UTC, cead22 commented
@allroundexperts no, or not yet at least, I assigned you and Yuwen as reviewers cause you had context on the deploy blocker. I could've just cc'ed you, but if you want to be the C+ to review this PR, that works

2024-02-20 23:13 UTC, s77rt commented
@cead22 

> Tap the Request $X.XX button
> Verify the report preview in the workspace chat has an RBR

We shouldn't let the user proceed with creating the request if the required fields are missing

2024-02-20 23:18 UTC, cead22 commented
> We shouldn't let the user proceed with creating the request if the required fields are missing

No that's not true, users should be able to create money requests without entering category and tag even if they're required. And for merchant, we already prevent it

2024-02-20 23:19 UTC, s77rt commented
@cead22 So they are required in the term that they cannot be submitted?

2024-02-20 23:20 UTC, cead22 commented
They can also be submitted, approved, and paid. They're used to highlight violations to users submitting the requests, and those approving them as well

2024-02-21 00:24 UTC, s77rt commented
Choosing a tag for multi-level tags does not clear the error

https://github.com/Expensify/App/assets/16493223/ea2eff27-0beb-4de4-be43-e2dcff2760e2

2024-02-21 00:39 UTC, s77rt commented
Setting a category value clears the error right away, while the tag error takes a while (waits for BE)



https://github.com/Expensify/App/assets/16493223/359f5a12-df96-44fa-afbc-44ef77b88919

2024-02-21 01:00 UTC, s77rt commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [X] I verified the correct issue is linked in the `### Fixed Issues` section above
- [X] I verified testing steps are clear and they cover the changes made in this PR
    - [X] I verified the steps for local testing are in the `Tests` section
    - [X] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [X] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [X] Android: Native
    - [X] Android: mWeb Chrome
    - [X] iOS: Native
    - [X] iOS: mWeb Safari
    - [X] MacOS: Chrome / Safari
    - [X] MacOS: Desktop
- [X] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [X] If the PR modifies the form input styles:
    - [X] I verified that all the inputs inside a form are aligned with each other.
    - [X] I added `Design` label so the design team can review the changes.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->

https://github.com/Expensify/App/assets/16493223/0cdad8ed-d89a-43f1-8b97-1f13f5a6ff89


</details>

<details>
<summary>Android: mWeb Chrome</summary>

<!-- add screenshots or videos here -->

https://github.com/Expensify/App/asset [...]

2024-02-22 01:13 UTC, cead22 commented
@rlinoz @s77rt please hold on reviewing. Fixing the tag violations for the multi-tag case is trickier than I thought

2024-02-22 20:11 UTC, cead22 commented
@rlinoz @s77rt this is ready for review. Please note that I remove code for violations for multi-level tags to avoid bloating the scope of this PR, and I'll follow up with another PR to add violation support for multi tags

2024-02-22 22:07 UTC, rlinoz commented
CategoryPicker is broken for me
`Uncaught TypeError: Cannot read properties of undefined (reading 'enabled')`, but it is also happening on main.

I will try to understand what is happening tomorrow.

2024-02-23 00:55 UTC, cead22 commented
@rlinoz I'm pretty sure this is known and happening for the tags as well, which is being fixed here https://github.com/Expensify/App/pull/36994/files

2024-02-23 04:46 UTC, s77rt commented
For multi level tags still seeing RBR in the money request preview - Do you want to handle this in the follow up as well?


https://github.com/Expensify/App/assets/16493223/decb2260-4ff3-43b2-999f-df9d81636fc1

2024-02-23 04:47 UTC, s77rt commented
For single tag, the tag selection works as expected but cannot test category due to other bugs

2024-02-23 04:47 UTC, s77rt commented
@cead22 Can you please merge main and resolve the conflicts?

2024-02-23 18:09 UTC, cead22 commented
@s77rt merged main

> For multi level tags still seeing RBR in the money request preview - Do you want to handle this in the follow up as well?

Yes

2024-02-23 19:07 UTC, s77rt requested changes

2024-02-23 19:07 UTC, s77rt commented on src/libs/Violations/ViolationsUtils.ts
> +                const hasMissingTagViolation = transactionViolations.some((violation) => violation.name === 'missingTag');
```suggestion
                const hasTagOutOfPolicyViolation = transactionViolations.some((violation) => violation.name === CONST.VIOLATIONS.TAG_OUT_OF_POLICY);
                const hasMissingTagViolation = transactionViolations.some((violation) => violation.name === CONST.VIOLATIONS.MISSING_TAG);
```

2024-02-23 19:10 UTC, cead22 commented on src/hooks/useViolations.ts
> -            }
I created an issue to follow up to implement violations for multi level tags https://github.com/Expensify/App/issues/37117

2024-02-23 19:11 UTC, cead22 commented
@s77rt I committed your suggestions

2024-02-23 19:22 UTC, cead22 commented
Yeah that change was intentional. I created an issue to follow up to implement violations for multi level tags https://github.com/Expensify/App/issues/37117

2024-02-23 19:26 UTC, s77rt commented
That removed condition is for empty tags list, does not seem related to the multi tags.

2024-02-23 19:50 UTC, cead22 commented
Is there a specific case you're worried about not working? I tested again and things seem to work fine. There's a couple of non-obvious things at play here
1. The removed condition is checking for empty tag lists on a workspace, and I don't think that can ever happen. You may have a workspace with a single tag list with no tags enabled, but there will still be a tag list
2. Even if the workspace had no tag lists, the workspace's "requires tag" property/logic should return false. Similarly for the case of a single tag lists that has tags in it, but where all the tags are disabled, the workspace "requires tag" property/logic should return false

So for the case where there is only 1 tag list, with no tags enabled, and the money request has a tag selected (that is disabled), we don't go into the `if (policyRequiresTags) {`

I say `"requires tag" property/logic should return false` because that may not be the case on the new dot client, but it is the case in our php logic, which looks like the code below

```php
    public function requiresTag()
    {
...
        if (!$this->hasEnabledTags()) {
            return false;
        }
...
    public function hasEnabledTags()
    {
...
        // If the policy has independent tags, ensure we check each tag list to see if there are any required tags
        if ($this->hasIndependentTags()) {
            return ArrayUtils::some($this->getTagListsArray(), function (array $tagList, int $i): bool {
                $tagCollection = $this->getIndependentTags($i);
                return $tagCollection->hasEnabledTags();
            });
        }
```

2024-02-23 19:56 UTC, s77rt approved these changes

2024-02-23 19:59 UTC, cead22 commented
@neil-marcellini not sure why you were added here, but a review from either you or @rlinoz works for me :)

2024-02-23 20:00 UTC, rlinoz approved these changes
Code looks good and tests well, thanks!

2024-02-23 20:01 UTC, cead22 commented
Thank you! Scratch my previous request @neil-marcellini

2024-02-23 20:01 UTC, merged

2024-02-23 20:07 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-02-26 21:09 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8055342505) to staging by https://github.com/cead22 in version: 1.4.44-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-02-28 23:57 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8088632252) to production by https://github.com/puneetlath in version: 1.4.44-13 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅