Localization consts for Request Call Page
Expensify/App pull request #3696
Opened 2021-06-21 01:49 UTC by jasperhuangg

This PR adds some translations for text that'll be needed when implementing the Request Call Page.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/167900

### Tests
N/A

### QA Steps
N/A

### Tested On
N/A

2021-06-21 02:30 UTC, jasperhuangg commented
@HorusGoul requesting you for review specifically for a quick double-check on the Spanish translations, thanks!

2021-06-21 09:55 UTC, HorusGoul commented on src/languages/es.js
> +        availabilityText: '*Nuestros guías están disponibles de domingo desde las 17.00 CT a viernes hasta las 17.00 CT. Si solicitas una llamada fuera de este horario, te llamaremos de lunes a viern
I would change the last part to look like this:
```suggestion
        availabilityText: '*Nuestros guías están disponibles de domingo desde las 17.00 CT a viernes hasta las 17.00 CT. Si solicitas una llamada fuera de este horario, te llamaremos de lunes a viernes de 9.00 a 17.00 en tu hora local. El orden de llamada corresponde con el orden de solicitud.',
```

2021-06-21 11:17 UTC, jasperhuangg commented
@HorusGoul Thanks for the fix! Should be good for another review, feel free to merge if you think everything checks out, thanks!!

2021-06-21 11:30 UTC, HorusGoul requested changes
I missed a lot of stuff on my first review. These are all the things I'd change:

2021-06-21 11:30 UTC, HorusGoul commented on src/languages/es.js
> +        description: 'Necesitas ayuda configurando tu cuenta? Nuestro equipo de guías te pueden ayudar.',
```suggestion
        description: '¿Necesitas ayuda configurando tu cuenta? Nuestro equipo de guías puede ayudarte.',
```

2021-06-21 11:30 UTC, HorusGoul commented on src/languages/es.js
> +        growlMessageOnSave: 'Llamada perdida.',
```suggestion
        growlMessageOnSave: 'Llamada solicitada.',
```

2021-06-21 11:30 UTC, HorusGoul commented on src/languages/es.js
> +        growlMessageInvalidPhone: 'El teléfono no es valido. Intenta nuevamente agregando el código de país. Eg: +15005550006',
```suggestion
        growlMessageInvalidPhone: 'El teléfono no es valido. Intentalo de nuevo agregando el código de país. P. ej.: +15005550006',
```

2021-06-22 08:54 UTC, jasperhuangg commented
@HorusGoul Thanks again! Should be good for another review 👍

2021-06-22 09:05 UTC, HorusGoul approved these changes
LGTM!

2021-06-22 14:05 UTC, merged

2021-06-22 14:06 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-06-25 18:48 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/972300794) to staging in version: 1.0.73-4🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-06-29 18:59 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/983780492) to production in version: 1.0.74-0🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅