Make OpenApp a write command
Expensify/App pull request #37062
Opened 2024-02-22 02:33 UTC by youssef-lr

cc @iwiznia @tgolen @roryabraham @marcochavezf 

### Details

This PR makes OpenApp a write command so that for anonymous users we make sure to process `OpenApp` first before any requests that are made after it.

Summary of my findings from this [thread](https://expensify.slack.com/archives/C066HJM2CAZ/p1708134160129379)

> 1. The first request an anonymous user makes is OpenReport of the parent room, OpenReport is processed first and does not return a lastUpdateID
> 2. The app then makes a call to OpenApp as usual, but its response is not processed immediately as it’s a read command, the sequential queue must process write commands first, and in this case it’s still processing OpenReport
> 3. Anon clicks quickly on a thread and triggers another call to OpenReport which we will process before OpenApp ’s response
> 4. Once we [attempt](https://github.com/Expensify/App/blob/5b265f38d97972f0118ef4e3f08e620499b54580/src/libs/Middleware/SaveResponseInOnyx.ts#L45) to save the response of the 2ndOpenReport , the sequential queue finds out we don’t have a lastUpdateID set [here](https://github.com/Expensify/App/blob/5b265f38d97972f0118ef4e3f08e620499b54580/src/libs/actions/OnyxUpdateManager.ts#L71) and calls ReconnectApp
> 5. The sequential queue is paused until we process ReconnectApp which comes back with a lastUpdateID equal to OpenReport ’s
> 6. We unpause the queue to apply the update from OpenReport but since it has the same update ID we now have in the client we don’t apply its response and we end up with the component not having a report set.
> 
> So in conclusion, I think this is due to navigating to the thread quickly before OpenApp has finished, so if we make it a write, it’ll be processed first before we process  OpenReport when opening the thread 

### Fixed Issues

$
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

1. To reproduce locally add a `sleep(3)` to `openApp` [here](https://github.com/Expensify/Web-Expensify/blob/f8dc0034d2ab28d5efe4cdc91b139b71107178b3/lib/AppInit.php#L431), as to reproduce this bug `OpenReport` needs to finish before `OpenApp`.
2. Create a workspace room with visibility set to public, create a thread inside the room.
3. Open the room as an anonymous user in an incognito window, and click on the thread as fast as you can.
4. Make sure it loads properly.

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not  [...]

2024-02-22 03:47 UTC, marcochavezf commented
Seems we'd need to update the unit test cases and types too

2024-02-22 03:49 UTC, youssef-lr commented
Yeah I'm looking into it now

2024-02-22 14:17 UTC, iwiznia submitted a review, later dismissed

2024-02-22 14:35 UTC, tgolen submitted a review, later dismissed
In theory, I am not a fan of this change. I think it blurs the lines between why something is a read/write in the first place. If something is being made a read/write only to have some kind of effect in the UI, and it is not based on the command actually "reading or writing" to the database, then I think it's an indication that we are doing something wrong.

Since it sounds like the real intention is to have OpenApp go into the synchronous blocking queue, I'd be much more in favor of us opening up an option for that so that we can be explicit that this is still a READ command, but the request needs to go into the synchronous queue for X reason.

2024-02-22 15:24 UTC, youssef-lr commented
@tgolen I agree and I thought about that, but `OpenApp` can actually be a write command as it creates a chat report [here](https://github.com/Expensify/Auth/blob/c1dee68835e9d5b26eba6de149a3e8301f6b8f4f/auth/command/OpenApp.cpp#L125) as @marcochavezf pointed out in the thread. Also, in Web-E `openApp` eventually calls `reconnectApp`, which is a write command, so I'm not really sure why we're having it as a read command.

2024-02-22 15:55 UTC, tgolen commented
OK, thanks! That's great if it results in WRITEs being done.

2024-02-22 19:34 UTC, iwiznia commented
>  Web-E openApp eventually calls reconnectApp, which is a write command

reconnectApp is a write command??? What does it write?

2024-02-22 20:08 UTC, youssef-lr commented
>reconnectApp is a write command??? What does it write?

I'm not sure, if it doesn't actually write anything, it seems like we made it solely to have it block the queue? cc @tgolen I can see it was added [here](https://github.com/Expensify/App/pull/23516)

2024-02-22 21:45 UTC, tgolen commented
The design doc said:

"It will call `API.write` (doing this so that it blocks all other calls)"

So yeah, I think your assumption is correct. No wonder why I didn't like
manipulating read/write like that!

On Thu, Feb 22, 2024 at 1:08 PM Youssef Lourayad ***@***.***>
wrote:

> reconnectApp is a write command??? What does it write?
>
> I'm not sure, if it doesn't actually write anything, it seems like we made
> it solely to have it block the queue? cc @tgolen
> <https://github.com/tgolen> I can see it was added here
> <https://github.com/Expensify/App/pull/23516>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Expensify/App/pull/37062#issuecomment-1960207408>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJMAB2ECJFK2PIMR3WPSCDYU6QTLAVCNFSM6AAAAABDUEGEPWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRQGIYDONBQHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-25 04:24 UTC, youssef-lr commented on tests/unit/NetworkTest.js
> +                PersonalDetails.openPersonalDetails();
I had to use a READ command here to make the test pass. It seems like this behaves differently when we call a write command.

2024-02-25 04:48 UTC, youssef-lr commented on tests/unit/NetworkTest.js
> +                PersonalDetails.openPersonalDetails();
I tested this scenario though of a write command with an expired authToken and I was re-authenticated properly.

2024-02-26 16:02 UTC, iwiznia approved these changes, later dismissed

2024-02-26 17:15 UTC, tgolen requested changes

2024-02-27 01:37 UTC, youssef-lr commented on tests/unit/NetworkTest.js
> +                PersonalDetails.openPersonalDetails();
On it.

2024-02-27 01:38 UTC, youssef-lr commented
cc'ing @marcaaron as well

2024-02-27 02:00 UTC, marcaaron approved these changes
These changes seem fine as far as I understand them. The "skew" stuff I am not sure about tbh still need to catch up on why we added that.

2024-02-27 08:33 UTC, youssef-lr commented
Looks like we just need a checklist, since this is hard to reproduce on mobile, I think we can just do web screenshots.

2024-02-27 15:49 UTC, tgolen approved these changes

2024-02-27 19:11 UTC, iwiznia approved these changes

2024-02-27 23:19 UTC, marcochavezf approved these changes

2024-02-27 23:45 UTC, merged

2024-02-27 23:50 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-02-29 00:07 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8088635796) to staging by https://github.com/marcochavezf in version: 1.4.45-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-02-29 23:31 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8103968899) to production by https://github.com/puneetlath in version: 1.4.45-6 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅