Feature: Send image with text via composer
Expensify/App pull request #3708
Opened 2021-06-21 17:17 UTC by parasharrajat

### Details

### Fixed Issues

Fixes #2258

### Tests | QA Steps
1. Open E.cash.
2. Open any conversation.
3. Type any message in the composer but don't send it.
4. Add an attachment from the plus menu.
5. Button should say send and After clicking send text should be posted followed by that image.
6. Repeat all the above steps in each platform.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

https://user-images.githubusercontent.com/24370807/122802126-9dfd5800-d2e2-11eb-9a94-ad43b555c4b0.mp4

#### Mobile Web

Upcoming
#### Desktop

https://user-images.githubusercontent.com/24370807/122802143-a190df00-d2e2-11eb-81a9-c3d48076df26.mp4

#### iOS

upcoming
#### Android

https://user-images.githubusercontent.com/24370807/122802148-a48bcf80-d2e2-11eb-9b4c-3591c6ad0428.mp4

2021-06-22 02:03 UTC, Jag96 requested changes
Tested and works well! Just a couple of requests for the language files

2021-06-22 02:03 UTC, Jag96 commented on src/components/AttachmentModal.js
> +                            text={this.props.translate('common.send')}
Can you remove the old `upload` const value if it is unused now?

2021-06-22 02:03 UTC, Jag96 commented on src/languages/en.js
> +        send: 'Send',
Can you also make sure these updates are included in the `es.js` file? You can just google translate to Spanish for now

2021-06-22 06:33 UTC, parasharrajat commented
@Jag96 Updated.

2021-06-22 23:03 UTC, parasharrajat commented
Ready for review

2021-06-22 23:46 UTC, Jag96 approved these changes
LGTM

2021-06-22 23:46 UTC, merged

2021-06-22 23:47 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-06-25 18:47 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/972300794) to staging in version: 1.0.73-4🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-06-29 18:58 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/983780492) to production in version: 1.0.74-0🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅