Ideal nav v2 workspaces
Expensify/App pull request #37421
Opened 2024-02-28 13:22 UTC by WojtekBoman

### Details

### Fixed Issues

$
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-02-28 22:24 UTC, hayata-suenaga commented
thank you for the draft PR @WojtekBoman. please mark the PR ready for review once it's ready 🙇

2024-02-29 09:11 UTC, kosmydel commented on src/pages/home/sidebar/PressableAvatarWithIndicator.js
> +    const buttonStyle = isSelected ? {borderWidth: 2, borderRadius: 30, borderColor: theme.splashBG} : {};
We have to add it to `styles`.

2024-02-29 09:11 UTC, kosmydel commented on src/pages/home/sidebar/PressableAvatarWithIndicator.js
> +                <View style={[styles.p1, buttonStyle]}>
```suggestion
                <View style={[styles.p1, isSelected && styles.buttonStyle]}>
```

2024-02-29 09:11 UTC, kosmydel commented on src/pages/home/sidebar/AvatarWithOptionalStatus.js
> +    isSelected: PropTypes.bool,
Please add comment

2024-02-29 09:11 UTC, kosmydel commented on src/libs/Navigation/types.ts
> +// };
```suggestion
```

2024-02-29 12:48 UTC, shawnborton commented
Let us know when this has some screenshots or a test build to review, thanks! cc @Expensify/design

2024-02-29 13:29 UTC, WojtekBoman commented on src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
> +            // bottomTabRoute?.name === SCREENS.WORKSPACE.INITIAL ||
I've asked about it [here](https://github.com/Expensify/App/issues/36656#issuecomment-1971133064)

2024-02-29 16:34 UTC, WojtekBoman commented
> Let us know when this has some screenshots or a test build to review, thanks! cc @Expensify/design

I've made it ready for review :) I'm waiting for your comments 👀

2024-02-29 17:40 UTC, hayata-suenaga commented
that's a good point

[building right now](https://github.com/Expensify/App/actions/runs/8100282059)

2024-03-01 08:43 UTC, WojtekBoman commented
@Expensify/design -> it's ready to test

2024-03-01 14:09 UTC, dannymcclain commented
Generally this is feeling pretty sweet! I want to let the other designers review it too but I think it's looking really good so far.

A couple things:
- @Expensify/design do we want the status to display in the avatar tab like it's currently doing in this build? I don't know that we ever talked about/specified that.
- I stumbled onto some weird behavior where if I go to a workspace's settings, goof around a bit, and then click "back", it drops me on the chat tab with the workspace page from the avatar tab in the main view (screenshot+video attached).

![CleanShot 2024-03-01 at 08 07 09@2x](https://github.com/Expensify/App/assets/7516624/1a74e5bb-e0a4-4bf2-bd40-b0bb624f286e)

https://github.com/Expensify/App/assets/7516624/8ab80ed5-e149-4ee0-a2b8-d3c11e2a2fb2

Basically all I do to reproduce this is navigate to avatar tab > click on workspaces > go into a workspace's settings > click on description (or anything really), close the RHP > click the top left back arrow.

2024-03-01 17:02 UTC, WojtekBoman commented
@dannymcclain Thanks for noticing [that](https://github.com/Expensify/App/pull/37421#issuecomment-1973272942)! I've added some fixes and I now it should works. You can check it when the new build is ready :)

2024-03-01 19:29 UTC, hayata-suenaga commented
thank you Danny for reporting the issue 😄

2024-03-04 14:11 UTC, shawnborton commented
Gonna fire up a new test build and then I'll also take it for a spin! But so far this is looking great!

2024-03-04 16:32 UTC, WojtekBoman commented
@mkhutornyi Could you take a look at it when you have time? :)

2024-03-04 16:34 UTC, shawnborton commented
Are we able to use a higher quality image for the avatar photo? It's pretty blurry:
![CleanShot 2024-03-04 at 11 34 42@2x](https://github.com/Expensify/App/assets/2319350/315971b7-8580-44aa-a8c9-ff620ebd6342)

2024-03-04 16:40 UTC, shawnborton commented
I think we should add 12px padding below the left side's header here, so that the first active item in the list lines up perfectly with the top of the card in the right content view:
![CleanShot 2024-03-04 at 11 39 54@2x](https://github.com/Expensify/App/assets/2319350/d75e3005-d41a-43d3-b833-8601cc3bb97e)

2024-03-04 16:42 UTC, shawnborton commented
Not sure if this was changed here, but I think we want the "Switch to Expensify Classic" to be at the top of Settings and not use an arrow icon. I think we're handling this elsewhere, just wanted to call it out though. We might just need to pull main.
![CleanShot 2024-03-04 at 11 41 51@2x](https://github.com/Expensify/App/assets/2319350/b73aa97c-2db0-47ed-82ab-6eb9c2625277)

2024-03-04 16:44 UTC, shawnborton commented
> @Expensify/design do we want the status to display in the avatar tab like it's currently doing in this build? I don't know that we ever talked about/specified that.

@dannymcclain I think I kinda like it there? I don't feel too strongly though... I can see where it makes things a little busy. What do you think?

2024-03-04 16:45 UTC, shawnborton commented
For the bottom tabs, I think in Figma we have them at 72px tall, but they are 80px in this PR:
![CleanShot 2024-03-04 at 11 43 50@2x](https://github.com/Expensify/App/assets/2319350/92bed063-d64e-4682-a709-f36597ef7706)

Should we use this as an opportunity to slim them down slightly? We just need to shave 4px off of the top padding and bottom padding. We'd still have the safeSpace below them on the mobile devices.

2024-03-04 16:46 UTC, shawnborton commented
Okay I think that's really all I got - looking good to me so far!

2024-03-04 17:17 UTC, dannymcclain commented
>I think we should add 12px padding below the left side's header here, so that the first active item in the list lines up perfectly with the top of the card in the right content view:

Stupid detail: let's add that 12px to the top of the nav items list. That's the way we do it in the center pane (12px top padding on the "content" container)

>do we want the status to display in the avatar tab like it's currently doing in this build? I don't know that we ever talked about/specified that.
>
>@dannymcclain I think I kinda like it there? I don't feel too strongly though... I can see where it makes things a little busy. What do you think?

I kinda do too haha. On desktop it makes it SUPER fast to get to your status which I loooooove. On mobile it will likely never be practical to actually tap it, but that's probably ok. But you're right, it is fairly busy... So I can see us going either way.

>Should we use this as an opportunity to slim them down slightly? We just need to shave 4px off of the top padding and bottom padding. We'd still have the safeSpace below them on the mobile devices.

I definitely think we should. Our bottom tabs are pretty big compared to basically all other apps on my phone. I assume they are all using native iOS tabs—so I'm not saying they need to match, just calling out how much bigger ours are (and in this comparison I have ours at 72px).
![image](https://github.com/Expensify/App/assets/7516624/87a4aa70-c47e-4462-957a-2a3c7a0dd90e)

2024-03-04 17:20 UTC, shawnborton commented
> On desktop it makes it SUPER fast to get to your status which I loooooove. On mobile it will likely never be practical to actually tap it, but that's probably ok. But you're right, it is fairly busy... So I can see us going either way.

Regardless of what we decide, I think I would make it so that tapping this part of the bottom tab just always takes you to Settings. I don't think we should ever block on the user getting taken to the parent level of Settings on based on exactly where they tap on this tab. So I'd be cool to keep it, but always navigate to Settings. From here you will see the status in the top right for easy access. 

Curious what Judge Jon thinks though of course!

2024-03-04 17:21 UTC, shawnborton commented
And nice, let's get these tabs down to 72px then and see how it feels from there. Thanks for that comparison btw!

2024-03-04 17:24 UTC, dannymcclain commented
>Regardless of what we decide, I think I would make it so that tapping this part of the bottom tab just always takes you to Settings. I don't think we should ever block on the user getting taken to the parent level of Settings on based on exactly where they tap on this tab. So I'd be cool to keep it, but always navigate to Settings. From here you will see the status in the top right for easy access.
>
>Curious what Judge Jon thinks though of course!

Now that you say that, I'm down with this approach and agree with you. If we keep it, it should basically just be a little visual indicator instead of an interactive element. Knowing Jon, I have a feeling he will agree with you 😁 but I can't wait to find out!

2024-03-05 09:43 UTC, WojtekBoman commented
> I think we should add 12px padding below the left side's header here, so that the first active item in the list lines up perfectly with the top of the card in the right content view: ![CleanShot 2024-03-04 at 11 39 54@2x](https://private-user-images.githubusercontent.com/2319350/309831561-d75e3005-d41a-43d3-b833-8601cc3bb97e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NzA3NTAsIm5iZiI6MTcwOTU3MDQ1MCwicGF0aCI6Ii8yMzE5MzUwLzMwOTgzMTU2MS1kNzVlMzAwNS1kNDFhLTQzZDMtYjgzMy04NjAxY2MzYmI5N2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTY0MDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDgxYmRjZWVkMmUzOTk0Y2FiMjFhMmIyNjkwMzk4YjdlODMwZGQ0Nzk0MGQ3NmY0OGE2NTNlMjc3ZTU1MTBhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L1iTcYZcTO_6uxtwR5aOwHDzxO5GD6yKnZHj5oB2-Nk)

I've checked it, and to set it at the same line, padding should be 8px. This is how it looks after the refactor: 
<img width="1117" alt="image" src="https://github.com/Expensify/App/assets/47774969/3a7b9aa4-2602-4fc5-bfd2-c39cdd4805f3">
Is it ok for you?

2024-03-05 14:08 UTC, shawnborton commented
Ah sorry, I don't mean that we should change the padding of the nav item itself. But rather, the space between the left header area and the first item needed a gap of 12px. The right side should also have the 12px gap.

2024-03-05 14:10 UTC, shawnborton commented
So both the left header and the right header should be 80px tall:
![CleanShot 2024-03-05 at 09 09 27@2x](https://github.com/Expensify/App/assets/2319350/cda16333-16d1-4a92-a420-9254e19b381f)

With 12px padding below:
![CleanShot 2024-03-05 at 09 10 06@2x](https://github.com/Expensify/App/assets/2319350/af12f77e-e8c0-425f-a7f3-e51b2b23d22c)

![CleanShot 2024-03-05 at 09 10 20@2x](https://github.com/Expensify/App/assets/2319350/22a25f06-beaf-4103-a9a3-523648093cc3)

2024-03-05 20:16 UTC, shawnborton commented
Looks like the border color on the outline of the pencil button is the wrong color:
![CleanShot 2024-03-05 at 15 15 47@2x](https://github.com/Expensify/App/assets/2319350/44203930-3a51-47ca-968a-257ddb97e6f5)

2024-03-06 13:26 UTC, shawnborton commented
It looks like the wordmark is not aligned with the "Chats" label, likely because of the adhoc label?
![CleanShot 2024-03-06 at 08 26 02@2x](https://github.com/Expensify/App/assets/2319350/6ddbc8ba-90c3-4889-89ca-f8b0e58772bc)

2024-03-06 14:44 UTC, WojtekBoman commented
> It looks like the wordmark is not aligned with the "Chats" label, likely because of the adhoc label? ![CleanShot 2024-03-06 at 08 26 02@2x](https://private-user-images.githubusercontent.com/2319350/310514727-6ddbc8ba-90c3-4889-89ca-f8b0e58772bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzE4OTYsIm5iZiI6MTcwOTczMTU5NiwicGF0aCI6Ii8yMzE5MzUwLzMxMDUxNDcyNy02ZGRiYzhiYS05MGMzLTQ4ODktODljYS1mOGIwZTU4NzcyYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMTMyNjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGI0M2EwZWEyYzljMmExNTRjNzQ3ZDdmMmUxZTM2YTFmNjQzYTUxYjIyMjBkYWQxNmRiYjRiMDZkZGYxYTM4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mzqjKFSJjk_j6ke9new0ASEoVJFGl-EDSyOO58uavsc)

![Simulator Screenshot - iPhone 15 Plus - 2024-03-06 at 15 43 23](https://github.com/Expensify/App/assets/47774969/df3f214e-7ced-4d1b-9463-7fa2df3acae6)

I think it's a problem that occurs also on the main branch:

2024-03-07 13:59 UTC, mountiny commented
@mkhutornyi ready for testing, creating a new build https://github.com/Expensify/App/actions/runs/8189318520

2024-03-07 16:16 UTC, shawnborton commented
This is feeling pretty solid to me! cc @Expensify/design in case ya'll wanna giver a testy run too.

2024-03-07 16:18 UTC, shawnborton commented
I mentioned this before but it still feels like the big avatar here is low resolution:
![CleanShot 2024-03-07 at 11 17 49@2x](https://github.com/Expensify/App/assets/2319350/3b4d7009-9e02-4e4e-9a05-cca8754ab156)

Can we fix that here or do we need a follow up?

2024-03-07 16:27 UTC, dannymcclain commented
Feeling good to me too! 🚀 

One thing I wanted to call out that I know Shawn has mentioned before: currently the status icon in the bottom tab is a separate interactive element from the tab itself—do we want that? I know Shawn has mentioned that the we should keep that whole thing as a single interactive tab and not have a direct link to the status in the tab bar. Is that something we should deal with in this PR or as a follow up?

![CleanShot 2024-03-07 at 10 24 34](https://github.com/Expensify/App/assets/7516624/5765a5c7-2854-4716-bf34-75ce6f2af71a)

2024-03-07 16:30 UTC, WojtekBoman commented
> I mentioned this before but it still feels like the big avatar here is low resolution: ![CleanShot 2024-03-07 at 11 17 49@2x](https://private-user-images.githubusercontent.com/2319350/310957423-3b4d7009-9e02-4e4e-9a05-cca8754ab156.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4Mjg1OTQsIm5iZiI6MTcwOTgyODI5NCwicGF0aCI6Ii8yMzE5MzUwLzMxMDk1NzQyMy0zYjRkNzAwOS05ZTAyLTRlNGUtOWEwNS1jY2E4NzU0YWIxNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMTYxODE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjRmZWQzZTg4ZGI1ZjEyM2U5YWUzOTAwOGIzYzY2ZTFhNzhhZjhiYWNjOTkxZGViNmU3ZjUxYTQyYzkzYjliMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V7yHQ7Yx3-gXIwu1wdt4gg2PlhsrxE6ZckxnjjdvfRk)
> 
> Can we fix that here or do we need a follow up?

This issue is also present on the main, so maybe we can create the follow up

2024-03-07 16:30 UTC, shawnborton commented
Ah good shout - we should solve that here, and I agree we should just make that entire tab always navigate you to settings

2024-03-07 16:43 UTC, dannymcclain commented
>Profile tab tooltip position is inconsistent with others. Expected?

I think they should all be the same. @Expensify/design?

2024-03-07 16:45 UTC, WojtekBoman commented
@dannymcclain @shawnborton 

https://github.com/Expensify/App/assets/47774969/76619eb6-facb-4431-8ee4-702f56eb4e20

Will it be ok? I can also remove a tooltip from the status icon, what do you think?

2024-03-07 16:57 UTC, shawnborton commented
I agree, we should remove the tooltip in that case

2024-03-08 14:27 UTC, dannymcclain commented
>Will it be ok? I can also remove a tooltip from the status icon, what do you think?

@WojtekBoman I think we need to remove the tooltip from status and make sure all the tab tooltips are positioned the same.

2024-03-08 14:58 UTC, WojtekBoman commented
> > Will it be ok? I can also remove a tooltip from the status icon, what do you think?
> 
> @WojtekBoman I think we need to remove the tooltip from status and make sure all the tab tooltips are positioned the same.

I've already added the fix :) Now it works this way: 

https://github.com/Expensify/App/assets/47774969/34f76d12-b0f2-41b1-bebc-f238be934da3

2024-03-08 15:07 UTC, dannymcclain commented
Fantastic—looks great!

Quick question for @Expensify/design: does it make more sense for the tooltips to be anchored to the icon (as shown in [this video](https://github.com/Expensify/App/pull/37421#issuecomment-1985847120)) or anchored to the top of the _tab_?

2024-03-08 18:56 UTC, mountiny commented
Making a new build https://github.com/Expensify/App/actions/runs/8207749469

2024-03-08 19:47 UTC, mountiny requested changes
Great job so far

2024-03-08 19:47 UTC, mountiny commented on src/components/AvatarSkeleton.tsx
> +
```suggestion
```

2024-03-08 19:47 UTC, mountiny commented on src/libs/Navigation/AppNavigator/createCustomFullScreenNavigator/CustomFullScreenRouter.tsx
>      // - SETINGS.ROOT to cover left pane.
Right? Or how should this comment be updated?
```suggestion
    // - WORKSPACE.INITIAL to cover left pane.
```

2024-03-08 19:47 UTC, mountiny commented on src/pages/home/sidebar/AvatarWithOptionalStatus.js
> +    onPress: PropTypes.func,
Please add a comment here just to follow the style guide

2024-03-08 19:47 UTC, mountiny commented on src/pages/home/sidebar/BottomTabAvatar.js
> +    isSelected: PropTypes.bool,
Pleaase add a comment

2024-03-08 19:47 UTC, mountiny commented on src/pages/home/sidebar/BottomTabAvatar.js
> +/* eslint-disable rulesdir/onyx-props-must-have-default */
This is a new file, can you write it in TS?

2024-03-08 19:47 UTC, mountiny commented on src/pages/home/sidebar/PressableAvatarWithIndicator.js
> +    onPress: PropTypes.func,
Please add a comment

2024-03-11 10:46 UTC, mkhutornyi reviewed
Bug1:  No left pane on workspace profile page


https://github.com/Expensify/App/assets/97676131/c34ee239-97a1-4abc-a83f-89316f1a10ba

----

Bug2: navigate to wrong chat (Concierge) after creating new room


https://github.com/Expensify/App/assets/97676131/18b8a53e-8dcf-4171-8b4a-244b165448e0

----

Bug3: anonymous user is able to navigate to Profile tab

<img width="1063" alt="bug3" src="https://github.com/Expensify/App/assets/97676131/3692f0c6-8083-47dd-a27d-f692e33b9b10">

----

Bug4: breadcrumb **root** is always "Expensify" even after selecting workspace


https://github.com/Expensify/App/assets/97676131/99ada3ed-e289-46ac-ac09-1275d6f23450

----

Bug5: [mobile] wrong navigation animation when go back from workspace profile


https://github.com/Expensify/App/assets/97676131/8188afce-23bd-4325-831f-1e916f3b4eef

2024-03-11 10:58 UTC, WojtekBoman commented
> Bug1: No left pane on workspace profile page
> 
>  bug1.mov 

Try reinstalling node_modules. It should help, because in this PR has been introduced changes in the patch file responsible for displaying left pane in FullScreenNavigator and you need reinstall packages to apply these changes

2024-03-11 11:05 UTC, mountiny commented
@mkhutornyi the adhoc builds should be accessible now

2024-03-11 13:03 UTC, WojtekBoman commented
> Bug2: navigate to wrong chat (Concierge) after creating new room

https://github.com/Expensify/App/assets/47774969/c33ba3ac-1d94-4cb3-a518-a624acffb437

I can't reproduce this one. Are there any other steps I need to take to reproduce this?

2024-03-11 16:11 UTC, mountiny commented
@mkhutornyi thanks for initial reports. hopefully you can complete the first round today 🙇

2024-03-11 17:10 UTC, mountiny commented
@mkhutornyi can you repro on staging too?

2024-03-11 18:30 UTC, WojtekBoman commented on src/components/Indicator.tsx
> +    const cleanAllPolicyMembers = Object.fromEntries(Object.entries(allPolicyMembers ?? {}).filter(([, policyMembers]) => !!policyMembers));
It's logic copied from the `hasGlobalWorkspaceSettingsRBR` method of `WorkspacesSettingsUtils.ts`. I added this in another PR. In policies we also sometimes store (when trying to open a non-existent policy) invalid policies that are not displayed on the list, so we don't want to show an indicator for them

2024-03-11 18:33 UTC, WojtekBoman commented
@mountiny @mkhutornyi I've solved bugs reported in the comments that aren't present on the main branch :)

2024-03-12 06:23 UTC, WojtekBoman commented
@mkhutornyi Conflicts have been solved. Please ping me, if they appear again :)

2024-03-12 06:37 UTC, WojtekBoman commented
@mkhutornyi Conflicts have been resolved :) Ping me, if they appear again :)

2024-03-12 11:30 UTC, trjExpensify commented
> Anonymous user is still able to access profile page via deep link. This also happens on staging. Is this bug or expected? If bug, can we create new GH for this?
> 
>  Screen.Recording.2024-03-12.at.1.06.47.pm.mov

@mkhutornyi that isn't expected, but unrelated to this PR, right? Looks like @DylanDylann helped fixed it once [here](https://github.com/Expensify/App/issues/28925). My suspicion is that the TS migration might have caused the regression. Couple of questions: 

- Is it staging and prod, or staging only? 
- What are the steps you're taking? Are they: 

1. Sign-out of any instance of Expensify you have on the device
2. Click a public room URL as an anonymous user like: https://staging.new.expensify.com/r/868417741568295
3. Enter https://staging.new.expensify.com/settings/profile in the browser
4. Observe you land on the profile page 

- Is it just the profile page once you're on the profile page, or can you access other pages in settings without being prompted to sign-in (or via deep link to the others)?

2024-03-12 16:39 UTC, WojtekBoman commented
![image](https://github.com/Expensify/App/assets/47774969/f4dc34d1-d617-4811-a647-9fa498913d64)
This issue with wrong display of the avatar in the bottom tab doesn't occur for me, I've increased borderRadius of the view that is a wrapper for the avatar, so maybe it will help. [This one](https://github.com/Expensify/App/pull/37421#issuecomment-1991524309) should work now.

2024-03-12 17:05 UTC, WojtekBoman commented
![IMG_7372](https://github.com/Expensify/App/assets/47774969/fbe0717a-6d56-4297-b8ee-0cf94780db49)
 On a physcial device it also works for me, I don't know what can be a reason of this issue

2024-03-12 17:33 UTC, WojtekBoman commented
@mkhutornyi Conflicts solved :)

2024-03-12 18:08 UTC, mountiny commented
New build is running

2024-03-12 19:39 UTC, WojtekBoman commented on src/pages/workspace/WorkspaceInitialPage.tsx
> +                onLinkPress={Navigation.resetToHome}
Ok, I can change it, but in some cases, for example when you open a link in your browser to the non-existing workspace, it won't navigate you to the home page but will open the list of workspaces. Is it ok?

2024-03-12 19:51 UTC, WojtekBoman commented on src/pages/workspace/WorkspaceInitialPage.tsx
> +                onLinkPress={Navigation.resetToHome}
I think it can be a problem with builds on staging, is it occurs also on your local build?

2024-03-12 19:53 UTC, WojtekBoman commented on src/pages/workspace/WorkspaceInitialPage.tsx
> +                onLinkPress={Navigation.resetToHome}
@mountiny As far as I know, we had a problem with builds that not-found page appears when we open the app, am I right?

2024-03-12 20:26 UTC, WojtekBoman commented on src/pages/workspace/WorkspaceInitialPage.tsx
> +                onLinkPress={Navigation.resetToHome}
I believe this problem with builds causes this issue. It seems to work fine locally

https://github.com/Expensify/App/assets/47774969/2b3cfb38-21f8-45b8-96a2-79d57ae74ca5

2024-03-12 21:03 UTC, mkhutornyi approved these changes
Given that no blocker issues, I am going to approve.
Since this is big refactor, we might have missed edge cases which should be handled as follow-up.

2024-03-12 21:06 UTC, mountiny commented on src/pages/workspace/WorkspaceInitialPage.tsx
> +                onLinkPress={Navigation.resetToHome}
Yep this seems like issue with adhoc builds

2024-03-12 21:12 UTC, mountiny approved these changes
Changes look good to me too @Expensify/design I believe this one has been checked by design already, but anything else to check for before we merge?

2024-03-12 21:15 UTC, mountiny requested changes
<img width="1460" alt="image" src="https://github.com/Expensify/App/assets/36083550/8aac41fe-d18f-49a9-9c54-78be65f21024">

in desktop view I am not seeing the workspace settings options

2024-03-12 21:17 UTC, shawnborton commented
Not sure how we keep getting this regression, but the border color on the edit workspace profile pic button is incorrect:
![CleanShot 2024-03-12 at 17 16 30@2x](https://github.com/Expensify/App/assets/2319350/ac0156b8-3c6e-413c-a9f5-d491c13ac236)


Could have sworn that @narefyev91 fixed that - maybe we just need to pull main?

2024-03-12 21:29 UTC, mountiny commented
@mkhutornyi I see thanks!

2024-03-12 23:01 UTC, mountiny commented
Seems to e fixed for me 
<img width="1532" alt="image" src="https://github.com/Expensify/App/assets/36083550/5fbe82f8-a9c4-4e2a-a848-36c42d112fa7">

2024-03-12 23:04 UTC, mountiny approved these changes
Ok this works well for me now, I will go ahead and merge this before there is more conflicts

2024-03-12 23:04 UTC, merged

2024-03-12 23:11 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-03-13 12:52 UTC, shawnborton commented
@mountiny in your screenshot, the border color is still borked:
![CleanShot 2024-03-13 at 08 52 00@2x](https://github.com/Expensify/App/assets/2319350/70ab3427-3a28-460f-81a1-334e5c1f6495)


Can we please follow up and fix this?

2024-03-13 19:59 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8270538134) to staging by https://github.com/mountiny in version: 1.4.52-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-03-13 21:23 UTC, shawnborton commented
Anyone else seeing this small gap on the top of the Settings view?

![CleanShot 2024-03-13 at 17 22 47@2x](https://github.com/Expensify/App/assets/2319350/cc3cb592-37da-4054-a267-7133fff121b7)

2024-03-14 07:57 UTC, kosmydel commented
> @kosmydel should be a quick one for you to follow up on tomorrow

I've prepared [a PR](https://github.com/Expensify/App/pull/38274) with a fix.

2024-03-15 10:15 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8294512236) to production by https://github.com/Beamanator in version: 1.4.52-6 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-03-17 07:42 UTC, godofoutcasts94 commented
This PR has caused this [issue](https://github.com/Expensify/App/issues/38436#issuecomment-2002332908)

2024-03-20 18:31 UTC, akinwale commented
This PR caused a [regression](https://github.com/Expensify/App/issues/38296#issuecomment-1997605199).

2024-03-25 10:32 UTC, jjcoffee commented
This caused a regression in https://github.com/Expensify/App/issues/38277. When deleting a policy, we needed to add a check if the policy selected in the switcher is the one being deleted, so that we can reset the switcher to `All workspaces`. More details [here](https://github.com/Expensify/App/issues/38277#issuecomment-1998522263).

2024-08-19 05:42 UTC, c3024 commented on src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts
> +            const isRHPScreenOpenedFromLHN = topmostNestedRHPRoute?.name && RHP_SCREENS_OPENED_FROM_LHN.includes(topmostNestedRHPRoute?.name as RHPScreenOpenedFromLHN);
`Track expense` adds self DM as matching route and it should be added in the RHPScreensOpenedFromLHN. Fixed with #46848 . Issue here #46674.

2025-06-20 04:49 UTC, eh2077 commented on src/pages/workspace/WorkspaceInitialPage.tsx
> +                onLinkPress={Navigation.resetToHome}
> Ok, I can change it, but in some cases, for example when you open a link in your browser to the non-existing workspace, it won't navigate you to the home page but will open the list of workspaces. Is it ok?

We should navigate back the list of workspace, which is reported here https://github.com/Expensify/App/issues/61485