New: Added drafts in GSD / #focus mode
Expensify/App pull request #3793
Opened 2021-06-29 17:11 UTC by parasharrajat

### Details

### Fixed Issues

$ #3782

### Tests

### QA Steps

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-07-01 03:31 UTC, Jag96 requested changes
Looks good, 2 minor comments but this works well!

2021-07-01 03:31 UTC, Jag96 commented on src/libs/OptionsListUtils.js
> +        const shouldShowReportIfhasDraft = showReportsWithDrafts && hasDraftComment;
```suggestion
        const shouldShowReportIfHasDraft = showReportsWithDrafts && hasDraftComment;
```

2021-07-01 03:37 UTC, parasharrajat commented
@Jag96 Updated.

2021-07-01 03:46 UTC, Jag96 approved these changes
LGTM

2021-07-01 04:10 UTC, merged

2021-07-01 04:11 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-07-09 00:31 UTC, roryabraham commented
Unfortunately the deploy comments are not working right now. This was deployed to staging yesterday.