Update welcome note
Expensify/App pull request #38023
Opened 2024-03-10 15:35 UTC by dukenv0307

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/37152
PROPOSAL: https://github.com/Expensify/App/issues/37152#issuecomment-1964336610

### Tests

1. Go to WS settings
2. Click button 'Invite member'
3. Choose a contact and click button Next
4. Verify that: Welcome message has a new format.
 
- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

1. Go to WS settings
2. Click button 'Invite member'
3. Choose a contact and click button Next
4. Verify that: Welcome message has a new format.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/129500732/1c275282-9440-44a9-b3a5-0a5cbebc297a

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/129500732/30c4fd3a-4e57-40da-aacc-60aafc623121

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/129500732/a21598c8-bcbc-43b8-a88e-9d179f260313

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/129500732/da9dff7c-f71e-4a5f-9cfc-95ef184ca5ac

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/129500732/ [...]

2024-03-11 23:38 UTC, trjExpensify commented
@situchan can you give us an ETA on reviewing this PR please?

2024-03-12 16:46 UTC, situchan commented
> @situchan can you give us an ETA on reviewing this PR please?

ETA end of day

2024-03-12 16:56 UTC, situchan commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->

</details>

<detail [...]

2024-03-12 16:59 UTC, situchan requested changes
@dukenv0307 Spanish copy is missing. Please request on slack

2024-03-12 17:00 UTC, situchan commented
And at least one platform screenshot with Spanish tested. And also screenshot of invite email

2024-03-13 00:56 UTC, danielrvidal commented
@situchan we don't actually need for the welcome messages if they are being sent from Concierge/a guide, etc. 

@dukenv0307 if you need other screens translated, you can ask me and I'll get them.

2024-03-13 18:31 UTC, trjExpensify commented
Sorry @dukenv0307, I think you might have misunderstood Daniel. Messages in the product that come from "Expensify" in a support capacity like Concierge, an account manager or a setup specialist etc are **not translated** into Spanish because we don't provide support in Spanish.

2024-03-13 19:00 UTC, situchan commented
@trjExpensify we have Spanish message in production. So now this should be unlocalized?
https://github.com/Expensify/App/blob/0cb701c34ccb45a10227f8d2e34cecab5b80cfc4/src/languages/es.ts#L2003-L2004

2024-03-13 19:26 UTC, trjExpensify commented
Cool, chatted to some peeps internally [here](https://expensify.slack.com/archives/C21FRDWCV/p1710357143581579?thread_ts=1710290471.543179&cid=C21FRDWCV) (ref for Expensifiers) and we'd like to remove that translation on the welcomeNote message, please. CC: @iwiznia

2024-03-13 23:23 UTC, danielrvidal commented
@dukenv0307 do you mind showing what the email looks like when:
- The workspace description is: This is the workspace description.
- The invite message is: This is the invite message. 

This screenshot looks to be incorrect, but I think it's because you are inputting information into the invite message: 
![image](https://github.com/Expensify/App/assets/2364487/f8496a44-48d5-4be1-ae6a-3903d19ebb4d)


This is what the email should be:
```
Subject: [First Name] [Last Name] ([email@user.com]) invited you to Expensify

Hi there -

To join "[workspace name]", [click here](link) to start tracking your expenses!

They also added the message:
[Input invitationmessage]

Additionally, here is the workspace description:
[Input workspace description]
```

And the bottom two lines (for invitation/workspace description) are dependent on 1) if they are present and 2) what the text of those inputs are. 

If you don't mind showing a mock-up/video up what it looks like with the suggestions above I can definitively tell you if there is an issue in the coding or if it was just because of what was input in the invitation message.

2024-03-14 00:08 UTC, danielrvidal commented
Mabve to add a bit more information, here is what I would expect the message to look like and then I have defined what is driving some of the pieces. Please let me know if there is any questions. 
![image](https://github.com/Expensify/App/assets/2364487/e01923c1-d802-4b18-9f3f-43268766f7a4)


- Daniel Vidal in the subject line is my First/Last name
- Bob's Donut's is the workspace name. 
- click here is linked to the workspace chat they were invited to (the URL for which is unique as every member gets a workspace chat created on invite to a workspace).
- "This is the invite message" is the invite message they input when inviting the user to the workspace. 
- "This is the workspace description" is the workspace description.

2024-03-14 12:07 UTC, situchan commented
> @situchan @trjExpensify If we decide to remove welcomeNote, should we remove all welcomeNotes from the en and es files and then move welcomeNote to the const file?

I don't mind putting this directly in view component like copy on onboarding modal
https://github.com/Expensify/App/blob/0a512c9f3cf1b207668ab93f3d79866c80345f88/src/pages/OnboardEngagement/PurposeForUsingExpensifyPage.tsx#L25

Maybe it would be good to group concierge messages all together but out of scope

2024-03-14 17:33 UTC, danielrvidal commented
@dukenv0307 here is an example of a workspace chat link: https://new.expensify.com/r/4656517140007919

It would just direct me to my workspace chat:
<img width="1276" alt="image" src="https://github.com/Expensify/App/assets/2364487/1c3479bc-14c0-445c-ae32-6f3ab2b1a185">

Obviously for a new user, theirs would not be populated with any requests yet but it would drop them into their workspace chat.

2024-03-18 17:53 UTC, danielrvidal commented
@situchan @dukenv0307 any update on this one? Let me know if you need anything else.

2024-03-18 17:59 UTC, danielrvidal commented
> subject mail in here, I think BE will fix it? 

Sorry, what is BE in this reference? I'll be sure to get it answered asap.

2024-03-18 20:15 UTC, trjExpensify commented
@danielrvidal I think @dukenv0307 is asking if we're getting the intended subject line for this message from the backend or not? 

`#[senders display name] ([senders login]) invited you to Expensify`

2024-03-19 01:10 UTC, danielrvidal commented
@dukenv0307 just for reference, I'm looking into the backend changes[ in here](https://github.com/Expensify/Web-Expensify/pull/41052). It looks like something might not be working with the updated message. @Gonals should give us some more info tomorrow.

2024-03-20 11:30 UTC, Gonals commented
> @dukenv0307 just for reference, I'm looking into the backend changes[ in here](https://github.com/Expensify/Web-Expensify/pull/41052). It looks like something might not be working with the updated message. @Gonals should give us some more info tomorrow.

It shouldn't affect this PR at all 😁

2024-03-21 04:00 UTC, danielrvidal commented
@dukenv0307 we're still working figuring out the subject line/invite updates. I'll get back to you asap.

2024-03-25 23:16 UTC, danielrvidal commented
@dukenv0307 I have an update for you. Sorry for the delay. Here are the new updates we need to make. Can you let me know:
1. Does the below all make sense? If not, please let me know precisely what you need help with. @Gonals @tgolen and I can help.
2. If it does make sense, can we prioritize this as it is blocking a high-priority project? 
3. Can you let us know what the ETA might be? 

Here is what the invite should be on New Expensify:

```
Subject: # [inviterFirstName] [inviterLastName] invited you to [workspaceName]

Body:
[welcomeNote]

Footer: Head over to new.expensify.com to respond on Expensify, or reply here.

```

- This should trigger a whisper message for the invited in the workspaceChat from the inviter. 
- The whisper message will use the custom subject line syntax (so the subject line is bigger/bolded in the chat UI) and thus trigger an invite email/SMS. 
- If the inviter does not have a [inviterFirstName] [inviterLastName], it would be their email/SMS in place of those.
- In the footer, new.expensify.com should link to the workspace chat. 
- The footer is not shown in the whisper, only in email/SMS. 

If you would like to see the updates that @Gonals is making on Expensify Classic, you [can here](https://github.com/Expensify/App/issues/38963). 

Let us know what we can do to help!

2024-03-26 18:44 UTC, danielrvidal commented
Hey @dukenv0307 please find the follow-ups below:
1. In the video you linked, the text box will be the workspaceDescription by default. If the user ends up changing the text in the text box, then you would send whatever they input as the body of the welcomeNote. I've highlighted where that goes here:
![image](https://github.com/Expensify/App/assets/2364487/0e297d77-1f9d-48a7-859e-180125a296be)

2. If we invite many members at one time, you would need to change the new.expensify.com link to be the workspace Chat that is specific to each invited member. Thus, each invite will have the same text but have different links linked in the new.expensify.com 

Let me know if that does not make sense.

2024-03-27 21:29 UTC, danielrvidal commented
>If the user changes the input, it will be This is invite message https://github.com/Expensify/App/pull/38023#issuecomment-1996163665 or it's all body of the email

Sorry, but I think what you are linking to is not correct. We would want the body to be what is in the welcomeNote and only that except for the footer which we'll always send in email/SMS. It is not the message you linked to. Please let me know if that does not make sense. 

>Actually, when AddMemberToWorkspace API is called, we send the welcomeNote to backend and it will be used as the body of the email for all users, so if we want to do that we need to config the workspaceLink from backend

@tgolen @Gonals for workspace invites, I'm wondering if the footer should be sent via the back end because it is always going to be the same thing when being sent to a user on NewDot. Can you advise what we should do here? 

> Reply to this message or respond at [new.expensify.com](http://new.expensify.com/)

And new.expensify.com links to the workspace chat that applies to them. I think this would fix what @dukenv0307 is talking about. Note: This is a slightly updated from the footer I had above as someone pointed out we want a footer with the link at the end so it will look good in SMS too.

2024-03-28 16:50 UTC, danielrvidal commented
I think you are looking at the old format, but we updated it to be the following. I have tried to outline what it will be in both cases so let me know if it does not make sense. 

```
Subject: # [inviterFirstName] [inviterLastName] invited you to [workspaceName]

Body:
[Input invitationmessage]

Footer: Reply to this message or respond at new.expensify.com

```

So if they have an invitation message that says "This is my invitation message" it would be:
```
Subject: # [inviterFirstName] [inviterLastName] invited you to [workspaceName]

This is my invitation message

Reply to this message or respond at new.expensify.com
```



If they removed the invitation message, it would just be:
```
Subject: # [inviterFirstName] [inviterLastName] invited you to [workspaceName]

Reply to this message or respond at new.expensify.com
```

2024-03-28 16:51 UTC, danielrvidal commented
One other note that @Gonals added. For the footer, the new.expensify.com would be the validation link for a brand new user, and then when validated send the user to the workspace chat. Then after that, the link should just be the workspace chat.

2024-03-29 18:03 UTC, danielrvidal commented
@dukenv0307 did that all make sense? We'd like to get this done asap as we're now creating Collect workspaces on NewDot so need this to be done relatively quickly.

2024-04-01 23:53 UTC, danielrvidal commented
Unfortunately, your examples do not look correct. Can you please review [the text in this](https://github.com/Expensify/App/pull/38023#issuecomment-2025676184)? 

In the examples you gave:
- You have the workspace name as the subject line. 
- "[inviterFirstName] [inviterLastName] invited you to [workspaceName]" you have this in the body, when it should be the subject line. 
- The footer should be "Reply to this message or respond at new.expensify.com" and new.expensify.com should be linked to validate the account/go to the workspace chat. 

I believe you are still trying to use the old format but the formatting/text in[ these examples ](https://github.com/Expensify/App/pull/38023#issuecomment-2025676184)are what they should be.

2024-04-02 20:15 UTC, tgolen commented
Hey @dukenv0307 I'll see if I can try and help. Let's zero in on the subject line for now since that's the most important. 

I believe the invite that comes from NewDot should be using what we call the "custom subject line" format in order to specify the subject of the notification email. In order to achieve this, I believe you need to update the welcome note to include the custom subject line:

```
            welcomeNote: ({inviterDisplayName, workspaceName}: WelcomeNoteParams) =>
                `# ${inviterDisplayName} invited you to ${workspaceName || 'Aaworkspace'}

You have been invited to ${workspaceName || 'a workspace'}! Download the Expensify mobile app at use.expensify.com/download to start tracking your expenses.`,
```

Custom subject lines begin with `#` and are followed by an empty line. These are then parsed out on the backend and used as the notification subject.

2024-04-02 21:52 UTC, danielrvidal commented
@dukenv0307 in regards to the footer, good call. I'll get that updated via the backend on a separate issue now. So the expected behavior would be for the footer to be "To respond, head over to new.expensify.com or reply directly to this message."

Sorry for the confusion.

2024-04-03 10:56 UTC, Gonals commented
> @tgolen I tried to add the subject line in `welcomeNote` like this video and the email still doesn't update the subject line as expected. Correct me if I missed something?
> 
>  Screen.Recording.2024-04-03.at.13.53.37.mov

Hey @dukenv0307! I don't think your message is going through `Expensimark.js`, as it is not an actual comment. `Expensimark` is in charge of converting our markdown language (the #, in this case) into HTML.

I don't see your new changes here, so I'm unsure of how your code looks, but you'd have to either run your message through the Expensimark parser or simply surrounf the subject with <h1></h1> instead of using the `#` notation.

2024-04-04 18:06 UTC, danielrvidal commented
@dukenv0307, @Gonals updated the [customer subject line](https://github.com/Expensify/Web-Expensify/pull/41547) functionality. This should be released on Monday so then we can test again on Tuesday. Let us know if you have any questions in the meantime. 

@Gonals can you please answer any questions for @dukenv0307 while I'm OOO next week.

2024-04-08 22:05 UTC, trjExpensify commented
@dukenv0307, @Gonals put a [PR up](https://github.com/Expensify/Web-Expensify/pull/41547) on Friday that hit staging today (that link won't work for you), so perhaps you can try to test your changes tomorrow when it hits prod? 

@situchan is now out of the office, so we need another C+ to review this PR. I'll ask for a volunteer in the channel.

2024-04-08 22:10 UTC, trjExpensify commented
@rayane-djouah is going to take on the review. I can't remove situ for some reason, but there we go!

2024-04-09 14:35 UTC, rayane-d requested changes

2024-04-09 15:07 UTC, rayane-d requested changes
Let's use two separate `const` with clear names: `welcomeNoteSubject` and `welcomeNoteDefaultBody`.

2024-04-09 20:13 UTC, trjExpensify commented
@dukenv0307, @Gonals' PR is now on production. Please can you confirm you can address these comments today? Excited to retest and get this one closed out. :)

2024-04-10 14:29 UTC, Gonals commented
> @trjExpensify When I send the invite with the `welcomeNote` that contains `h1` tag, I don't receive the invite email.
> 
>  v1-1.mov 
> If I remove this tag, I receive this email
> 
>  v2-1.mov 
> cc @danielrvidal @Gonals

Your code seems to work fine for me. I receive the email with no issues:
<img width="699" alt="Screenshot 2024-04-10 at 4 27 21 PM" src="https://github.com/Expensify/App/assets/19366280/4818a8c6-7ada-4120-afe5-628dcb5e9730">

2024-04-10 20:50 UTC, trjExpensify commented
@dukenv0307, what's the diff here then? Did you invite a new user that doesn't have an account or an existing one?

2024-04-11 01:12 UTC, trjExpensify commented
Haha, I'm so confused. @Gonals can you list your numbered steps to successfully achieve [this](https://github.com/Expensify/App/pull/38023#issuecomment-2047712574) using Duke's code?

2024-04-12 07:22 UTC, Gonals commented
> * The existing user is receiving this email (which doesn't meet the needed format):

Yep, that is the email expected for existing users.

It is really weird you are not getting the email for new users, though, as I seem to get it without any issues. You are not getting it regardless of the contents of the message and/or name of the workspace? I'm trying to figure out if any special characters may be causing issues

2024-04-12 07:24 UTC, Gonals commented
> Haha, I'm so confused. @Gonals can you list your numbered steps to successfully achieve [this](https://github.com/Expensify/App/pull/38023#issuecomment-2047712574) using Duke's code? 

Sure, but there's nothing special 😅 :
1. Log into NewDot
2. Create a new workspace
3. Go to Members
4. Invite an email address that does NOT have an Expensify account
5. That's it

2024-04-12 09:25 UTC, trjExpensify commented
@dukenv0307 @rayane-djouah can you follow those steps exactly, please? Let's get videos of going through that whole flow to verify that's we're all on the same page. Thanks!

2024-04-12 13:35 UTC, Gonals commented
@dukenv0307, after a bunch of testing, we have seen some inconsistent behavior on the staging backend when sending custom subject emails. I got them fine, Tom got them in some domains, and not in others...

At this point, we are unsure of the cause, but it is unrelated to this issue, so we can move ahead with it, as it tests well for me. 

@situchan, can you check if it works for you too/approve and we go ahead and merge this?

Alternatively, if you have access to emails in other domains, you can try inviting those 🤷

2024-04-15 12:07 UTC, Gonals commented
> > @dukenv0307, after a bunch of testing, we have seen some inconsistent behavior on the staging backend when sending custom subject emails. I got them fine, Tom got them in some domains, and not in others...
> > At this point, we are unsure of the cause, but it is unrelated to this issue, so we can move ahead with it, as it tests well for me.
> > @situchan, can you check if it works for you too/approve and we go ahead and merge this?
> > Alternatively, if you have access to emails in other domains, you can try inviting those 🤷
> 
> @Gonals, the code is LGTM, but I'm not able to test it. LMK if I should skip testing and approve anyway. in this case, we should add [No QA] to skip QA testing also.

Let's just go ahead and approve this. I can QA it, so no need for the [No QA] label

2024-04-15 13:25 UTC, rayane-d approved these changes

2024-04-15 15:43 UTC, Gonals commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->

</details>

<detail [...]

2024-04-15 15:58 UTC, Gonals approved these changes

2024-04-15 15:58 UTC, merged

2024-04-15 16:06 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-04-18 04:54 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8732363773) to staging by https://github.com/Gonals in version: 1.4.63-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-04-18 14:02 UTC, lanitochka17 commented
This PR is failing because of issue https://github.com/Expensify/App/issues/40445

The issue is reproducible in: all environments


https://github.com/Expensify/App/assets/78819774/ccfde1e9-0922-4e94-9b7c-f564b1f1725d

2024-04-22 14:55 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8786104763) to production by https://github.com/mountiny in version: 1.4.63-21 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-04-22 21:00 UTC, danielrvidal commented
@Gonals @dukenv0307 I tried to generate invite emails in the new format and couldn't get them to work. Are you able to get it to work? 
1. Created a workspace as a new user danrvidal+onboardtest8@gmail.com
2. Invited danrvidal+onboardtest9@gmail.com
3. I never got an invite message 

Could we diagnose what is happening ASAP? If we're not sending invite emails for anyone being added, that is not great, and we should prioritize a fix ASAP. 

Here is a video of my flow:
https://github.com/Expensify/App/assets/2364487/a38dc470-7e39-4cb5-9120-28c29d9abd91

2024-04-24 15:19 UTC, danielrvidal commented
Hey @dukenv0307, it looks like me not getting the email was from another issue, so this is all good. Thank you!