Scroll highlight feature for workspace member page
Expensify/App pull request #38036
Opened 2024-03-11 11:42 UTC by shubham1206agra

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/35717

### Tests

1. Open Workspace where you want to add members.
2. Add new members using Invite Members flow.
3. Observe that it scrolls to the first new added member, and it highlights new members for some time.

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as Tests

### QA Steps

Same as Tests

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/58412969/42d367f0-6080-41f5-8b89-8f075af16327

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/58412969/af8bfe87-9e65-48fd-90c5-868bfb4d6a12

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/58412969/711a0ed9-a980-421a-bfb7-804251371731

https://github.com/Expensify/App/assets/58412969/35751c58-9afc-4f41-806c-764596acfd4d

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/58412969/e5ee8bd8-4e24-4a44-8606-97a273687425

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/58412969/5aa1f582-28b9-40b9-8861-41477aafb739

</details>

2024-03-11 12:46 UTC, mountiny commented on src/pages/workspace/WorkspaceMembersPage.tsx
> +        selectionListRef.current?.scrollAndHighlightItem?.(invitedEmails, 1500);
@Expensify/design How long should the highlight be there for?

2024-03-11 12:47 UTC, mountiny commented
> it is very hard to implement due to multiple extra re-renders which I am unable to control.

Could you define this problem a bit more specifically and bring it to slack, possible #newdot-performance and we could brainstorm with agency workers how to achieve this

2024-03-11 12:54 UTC, mountiny reviewed
@ishpaul777 @shubham1206agra Given this is bigger change to the BaseSelectionList component, can you please add tests for other places where the SelectionList component is used? Also make sure Tab+Enter navigation is working as expected there etc. 

Thanks

2024-03-11 12:54 UTC, mountiny commented on src/pages/workspace/WorkspaceMembersPage.tsx
> +        Policy.setWorkspaceInviteMembersDraft(route.params.policyID, {});
Shy did you move it here from the action itself?

2024-03-11 12:54 UTC, mountiny commented on src/components/SelectionList/BaseSelectionList.tsx
> +    const scrollAndHighlightItem = useCallback(
Could you add a plain english explanation to a doc comment of what is being done in this method?

2024-03-11 14:32 UTC, shawnborton commented on src/pages/workspace/WorkspaceMembersPage.tsx
> +        selectionListRef.current?.scrollAndHighlightItem?.(invitedEmails, 1500);
Got it, so just to clarify, we are not doing the original idea where it stays highlighted until another action is taken? The highlight will always be ephemeral? 

If that's the case I don't have strong feelings on an exact time... somewhere between 1.5-3 seconds seems fine to me?

2024-03-11 14:51 UTC, shawnborton commented on src/pages/workspace/WorkspaceMembersPage.tsx
> +        selectionListRef.current?.scrollAndHighlightItem?.(invitedEmails, 1500);
Cool, no strong feelings in terms of time then - perhaps let's see some screen recordings of a few different options?

2024-03-11 15:15 UTC, shawnborton commented on src/pages/workspace/WorkspaceMembersPage.tsx
> +        selectionListRef.current?.scrollAndHighlightItem?.(invitedEmails, 1500);
That feels pretty good, but can we have the background color fade out instead of just change at the end?

2024-03-11 16:13 UTC, mountiny commented
Cool ok, I think we can leave the fade for later and explore if the highlight approach is doable

2024-03-11 18:16 UTC, ishpaul777 approved these changes

2024-03-11 23:57 UTC, luacmartins requested changes

2024-03-11 23:57 UTC, luacmartins commented on src/components/SelectionList/BaseSelectionList.tsx
> +    const [itemToHighlight, setItemToHighlight] = useState<Set<string> | null>(null);
This can be a list of items, right?
```suggestion
    const [itemsToHighlight, setItemsToHighlight] = useState<Set<string> | null>(null);
```

2024-03-11 23:57 UTC, luacmartins commented on src/components/SelectionList/BaseSelectionList.tsx
> +        const isItemFocused = !isDisabled && (focusedIndex === normalizedIndex || itemToHighlight?.has(item.keyForList));
TS is failing here, I think we need a default in the case `itemToHighlight` is `null`

2024-03-11 23:57 UTC, luacmartins commented on src/components/SelectionList/BaseSelectionList.tsx
> +            const index = flattenedSections.allOptions.findIndex((option) => newItemsToHighlight.has(option.keyForList));
same here, TS is failing

2024-03-11 23:57 UTC, luacmartins commented on src/components/SelectionList/BaseSelectionList.tsx
> +    );
Did this happen on mWeb only? Do we need to add an offset with the item height?

2024-03-11 23:57 UTC, luacmartins commented on src/pages/workspace/WorkspaceInviteMessagePage.tsx
> -        Policy.setWorkspaceInviteMembersDraft(route.params.policyID, {});
I think we still want to clear this list, no?

2024-03-12 05:17 UTC, luacmartins submitted a review, later dismissed

2024-03-12 05:17 UTC, luacmartins commented
LGTM we can look at this issue in the follow up - https://github.com/Expensify/App/pull/38036#discussion_r1520114589

2024-03-12 22:33 UTC, mountiny commented
Waiting for conflicts resolution

2024-03-13 02:43 UTC, luacmartins approved these changes

2024-03-13 03:12 UTC, merged

2024-03-13 03:17 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-03-13 19:59 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8270538134) to staging by https://github.com/luacmartins in version: 1.4.52-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-03-15 10:16 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8294512236) to production by https://github.com/Beamanator in version: 1.4.52-6 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-03-15 17:54 UTC, rushatgabhane commented on src/pages/workspace/WorkspaceMembersPage.tsx
> +        selectionListRef.current?.scrollAndHighlightItem?.(invitedEmails, 1500);
smallll nitpick: 1500 should have been in CONST file