Add delete option to attachments
Expensify/App pull request #3804
Opened 2021-06-29 19:51 UTC by rdjuric

### Details

We change our `shouldShow` condition for the delete option to be a new function `canDeleteReportAction`. It is similar to our canEditReportAction, but don't check if the message is an attachment.

### Fixed Issues

#3775 

### Tests

1. Open any chat
2. Send an attachment 
3. The delete option shows on the menu
4. Clicking on the delete option correctly deletes the attachment
### QA Steps

1. Open any chat
2. Send an attachment 
3. The delete option shows on the menu
4. Clicking on the delete option correctly deletes the attachment

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

https://user-images.githubusercontent.com/53711423/123856564-a283cb00-d8f7-11eb-9f73-f0e918e59b64.mov

#### Mobile Web

https://user-images.githubusercontent.com/53711423/123856665-bdeed600-d8f7-11eb-9d5a-7e11a9e050a7.mp4

#### Desktop

https://user-images.githubusercontent.com/53711423/123856726-cf37e280-d8f7-11eb-9764-1da0b528d5d2.mov

#### iOS

https://user-images.githubusercontent.com/53711423/123856813-e971c080-d8f7-11eb-9fa5-a29d8cb4a85a.mp4

#### Android

https://user-images.githubusercontent.com/53711423/123858297-b8928b00-d8f9-11eb-8085-cf9bf950215d.mp4

2021-06-29 19:55 UTC, rdjuric commented
Just a note: while #3767 isn't fixed, we have to use the context menu from the side of the message to test this on the web/desktop.

2021-06-29 22:40 UTC, luacmartins requested changes
Great work! Only minor NAB changes.

2021-06-29 22:40 UTC, luacmartins commented on src/libs/reportUtils.js
> + * Can only edit if it's a ADDCOMMENT that is not an attachment,
```suggestion
 * Can only edit if it's an ADDCOMMENT that is not an attachment,
```

2021-06-29 22:40 UTC, luacmartins commented on src/libs/reportUtils.js
> + * the author is this user and it's not a optimistic response.
```suggestion
 * the author is this user and it's not an optimistic response.
```

2021-06-29 22:40 UTC, luacmartins commented on src/libs/reportUtils.js
> + * Can only delete if it's a ADDCOMMENT, the author is this user and it's not a optimistic response.
```suggestion
 * Can only delete if it's an ADDCOMMENT, the author is this user and it's not an optimistic response.
```

2021-06-29 22:53 UTC, rdjuric commented
Done! Thanks for the corrections @luacmartins

2021-06-29 23:18 UTC, luacmartins approved these changes

2021-06-29 23:18 UTC, merged

2021-06-29 23:19 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-07-09 00:32 UTC, roryabraham commented
Unfortunately the deploy comments are not working right now. This was deployed to staging yesterday.