Fix: Hold request style and visibility
Expensify/App pull request #38471
Opened 2024-03-18 13:30 UTC by dragnoir

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/37536
PROPOSAL: https://github.com/Expensify/App/issues/37536#issuecomment-1973464572

The winning proposals are:
- Not displaying hold on 3 dots menu when scanning https://github.com/Expensify/App/issues/37536#issuecomment-1979995972
- Having the same style for hold status https://github.com/Expensify/App/issues/37536#issuecomment-1973464572

### Tests

1. Go to staging.new.expensify.com
2. Go to 1:1 DM
3. Create a scan request
4. Go to request details page
5. Click 3-dot menu
6. Verify that there's no option to Hold from the 3 dots menu when the scanning status is displayed
7. Wait until the scan finish
8. Click 3-dot menu > Hold request
9. Add a reason and save it
10. Verify that the Hold status has the same style as the scanning status except with a red background for the badge

- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

1. Go to staging.new.expensify.com
2. Go to 1:1 DM
3. Create a scan request
4. Go to request details page
5. Click 3-dot menu
6. Verify that there's no option to Hold from the 3 dots menu when the scanning status is displayed
7. Go back online to allow the scan to finish
8. Wait until the scan finish
9. Go offline again
10. Click 3-dot menu > Hold request
11. Add a reason and save it
12. Verify that the Hold status has the same style as the scanning status except with a red background for the badge

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/desi [...]

2024-03-18 13:43 UTC, shawnborton commented
Can you share a couple of still screenshots of the scanning state and the hold state? I just want to double check that the banner styles look the same. Thanks!

2024-03-18 13:50 UTC, shawnborton commented
Awesome. Can you try making the "Hold" text use the same text color as our danger/red buttons? 

Also cc @Expensify/design for vis... I think some of this stuff will eventually change when we update the next steps, but for now, I think this is worth getting alignment on. 

We could also consider updating both of these badges to use our new badge style that's in the app too?

2024-03-25 18:27 UTC, Santhosh-Sellavel commented on src/styles/index.ts
> -            backgroundColor: theme.border,
We could've easily over-written with `spread` operator. Instead of deleting this, as this could affect styles in other places where its used.

2024-03-25 18:32 UTC, Santhosh-Sellavel requested changes

2024-03-25 18:32 UTC, Santhosh-Sellavel commented on src/components/MoneyRequestHeaderStatusBar.tsx
> +    const badgeTextColorStyle = badgeColorStyle ? styles.textMicroBoldDangerColor : styles.textMicroBoldColor;
Why `badgeColorStyle` is used like a boolean here. 
Why if `badgeColorStyle`color exists text style should be styles.`textMicroBoldDangerColor`?

As `badgeColorStyle` could be anything.

Can you please refactor this properly?

2024-03-27 10:17 UTC, Santhosh-Sellavel commented
@neonbhai Can you help here by reviewing this one. Complete the Reviewer checklist.

2024-03-29 08:07 UTC, shawnborton commented
Also, where did we land with regards to this screen here:
![image](https://github.com/Expensify/App/assets/2319350/a3042e17-307b-4d5f-8621-a46ce6da81cb)

I thought the idea was that we would not show two banners at once?

2024-03-29 08:08 UTC, shawnborton commented
From @JmillsExpensify in the original issue:

> Yeah you shouldn't be able to hold a scanning request. That feels like the solution in my opinion.

cc @danielrvidal since you commented about this in Slack

2024-03-29 16:06 UTC, Santhosh-Sellavel commented
Yeah, we should not show two labels at the same time!

2024-04-01 05:26 UTC, shawnborton commented
> it's just a screenshot for you to check how it looks. I played with the code to display both.

Sounds good, thanks for confirming. Let us know when there are updated screenshots to check out and we can review from there.

2024-04-01 12:33 UTC, shawnborton commented
Cool, looks good to me - thanks!

2024-04-01 12:38 UTC, shawnborton commented
Actually @dragnoir I'm super sorry for the late feedback, but one thing we could do is normalize these badges with our actual official badge style from our design system. It's not much different, but it looks like this:
![CleanShot 2024-04-01 at 14 37 45@2x](https://github.com/Expensify/App/assets/2319350/f32ddeb0-fd16-4cd1-982a-d5bcb9af174a)

Curious what you think about that. We already have an existing badge component, so this would be extending it to have a Success and Danger prop which just changes the border color to success green or danger red. 

cc @Expensify/design for thoughts too.

2024-04-01 12:39 UTC, shawnborton commented
So as it relates to this PR, the "Scanning" badge would look like our normal badge component, and the "Hold" badge would use the danger badge component.

2024-04-01 13:37 UTC, dannymcclain commented
That sounds good to me. Good shout Shawn!

2024-04-02 15:51 UTC, shawnborton commented
> Would you prefer these changes to be implemented in the current pull request or in a separate one for enhanced testing, code review, and integration with Storybook?

I don't feel too strongly if we do it here or in another PR. I am fine doing it here personally, but let's see what @francoisl and @Santhosh-Sellavel think.

2024-04-02 16:16 UTC, Santhosh-Sellavel commented
I think that can be done in a separate PR and test throughly.

2024-04-02 16:17 UTC, Santhosh-Sellavel commented
@neonbhai Any update on the checklist?

2024-04-02 17:57 UTC, neonbhai requested changes

2024-04-08 07:36 UTC, shawnborton commented
How are we doing with this one?

2024-04-10 07:43 UTC, shawnborton commented
If you are using our standard variables for:
- border: the default border color for badges, this should exist already
- text: the color of text inside of the badge, this should exist already
- success: the color we would use for the border and icon of the badge in the success case
- danger: the color we would use for the border and icon of the badge in the danger case

Then these colors will automatically flip for you when changing from dark to light themes.

2024-04-22 12:35 UTC, shawnborton commented
Looks like that PR is still open?

2024-04-24 12:04 UTC, shawnborton commented
Can we please try to push this one over the finish line today? cc @dragnoir

2024-04-25 11:22 UTC, shawnborton commented
> Also updated the education header 

What updates were needed for this out of curiosity? 

> we will not need the component HoldBanner anymore. How to proceed?

Can you elaborate some more - why is this not needed anymore?

2024-04-25 11:54 UTC, shawnborton commented
> We use the same component for the 3 type of messages. The HOLD one, was using a the component HoldBanner. After we updated using badges, we don't need it, because it was for UI HOLD badge

> this one here https://github.com/Expensify/App/pull/38471#issuecomment-2069287799

Cool, thanks for confirming!

2024-04-25 22:45 UTC, neonbhai commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->

</details>

<detail [...]

2024-04-25 23:34 UTC, neonbhai requested changes
looks good! just some small changes

2024-04-29 13:46 UTC, shawnborton commented
Friendly bump, let's please get this reviewed ASAP. I have a feeling this one is going to conflict with the updates @grgia is making to the pending/scanning requests though, right?

2024-04-29 15:37 UTC, neonbhai approved these changes
Looks good to me! 🚀

2024-04-29 17:01 UTC, trjExpensify commented
👋 @NikkiWines any chance you could take the secondary internal review on this PR?

2024-04-29 19:00 UTC, NikkiWines commented
Sure, I'll review this today!

2024-04-29 19:13 UTC, Santhosh-Sellavel approved these changes
LGTM, tests well, thanks everyone!

2024-04-30 06:52 UTC, NikkiWines approved these changes
👍 looks good!

2024-04-30 06:53 UTC, merged

2024-05-01 03:01 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8904499086) to staging by https://github.com/NikkiWines in version: 1.4.69-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-05-02 13:04 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8924174545) to production by https://github.com/Beamanator in version: 1.4.69-2 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅