fixed spaces collapsing in Messages
Expensify/App pull request #3869
Opened 2021-07-02 18:25 UTC by parasharrajat

### Details

### Fixed Issues

$ GH_LINK

### Tests | QA Steps

 1. Log in to e.cash and navigate to a conversation
 2. Send the following text
```
0 space
 1 spaces
  2 spaces
   3 spaces
    4 spaces
```
3. Output should contain the same amount of spacing as added.

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-07-06 02:12 UTC, jasperhuangg commented on src/components/RenderHTML/BaseRenderHTML.js
> + * @param {number} tagName - tagname
Can we provide a better description for this parameter?

2021-07-06 02:17 UTC, jasperhuangg requested changes
Left a comment about some JSDoc stuff. Also, tested it and it doesn't seem to work, am I missing something? This doesn't seem to happen on main. Were there any changes in expensify-common that I'm missing?

https://user-images.githubusercontent.com/31285285/124532430-259aa900-de43-11eb-8bb9-04708b8da818.mp4

2021-07-06 02:36 UTC, parasharrajat commented
did you do 'npm install'?

2021-07-07 04:25 UTC, jasperhuangg commented
@parasharrajat Ah forgot, make sure you include that in your testing instructions if there were changes to `expensify-common`.

2021-07-08 23:24 UTC, parasharrajat commented
@jasperhuangg  Please, let me know if you are facing some issues while testing.

2021-07-09 00:42 UTC, jasperhuangg commented
@parasharrajat Still waiting on you to look into [this](https://github.com/Expensify/Expensify.cash/pull/3869/files#r664190613).

2021-07-09 01:08 UTC, parasharrajat commented
Sorry @jasperhuangg, I thought you are still facing the issue so I waiting to get a response over it.
Anyways, I have updated it. Thanks.

2021-07-09 12:15 UTC, jasperhuangg commented on src/components/RenderHTML/BaseRenderHTML.js
> + * @param {number} tagName - tagname of the Element whose maxWidth is need to be set
```suggestion
 * @param {number} tagName - tagname of the Element whose maxWidth needs to be set
```

2021-07-09 12:15 UTC, jasperhuangg approved these changes, later dismissed
@parasharrajat Looks good! One small grammatical fix.

2021-07-09 12:26 UTC, parasharrajat commented
@jasperhuangg Done. Thanks.

2021-07-10 01:11 UTC, jasperhuangg approved these changes
Awesome, thanks for your patience!

2021-07-10 01:11 UTC, merged

2021-07-10 01:12 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-07-10 01:14 UTC, jasperhuangg commented
Ah crap, didn't see the HOLD on this. I opened up a revert https://github.com/Expensify/Expensify.cash/pull/3969. Sorry for any inconvenience @parasharrajat!

2021-07-14 19:53 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/1031434935) to staging         in version: 1.0.77-6🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2021-07-15 03:16 UTC, kavimuru commented
## Chat - Spaces are not displayed after sending the message
## Expected Result: 
Spaces should be displayed in the message after it's sent
## Actual Result:
No spaces are displayed in the conversation after sending the message
## Actions Performed:
1. Log in to e.cash and navigate to a conversation
2. Send the following text
0 space
 1 spaces
  2 spaces
   3 spaces
    4 spaces
## Platform:
iOS ✔️
mWeb ✔️
Android ✔️
Web ✔️
## Build:
1.0.78-0
## Notes/Images/Video:
![Bug5152224_IMG_6279](https://user-images.githubusercontent.com/43996225/125723617-2d41336b-39ae-4d7d-ac40-d923b42c1f08.png)

https://user-images.githubusercontent.com/43996225/125723624-51227edb-b65c-46e0-9284-59c9d7cfcec9.mp4

2021-07-15 04:18 UTC, parasharrajat commented
This PR is reverted. So the original issue still exists.

2021-07-15 18:19 UTC, isagoico commented
@jasperhuangg We're good to check off this PR from the list if the PR was reverted right? CC @roryabraham

2021-07-23 21:15 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1060984705) to production         in version: 1.0.79-4🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅