fix: picker an arrow navigation
Expensify/App pull request #3871
Opened 2021-07-02 21:05 UTC by parasharrajat

### Details

1. https://github.com/Expensify/Expensify.cash/issues/3858#issuecomment-873079314
2. https://github.com/Expensify/Expensify.cash/issues/3858#issuecomment-873122883

### Fixed Issues

$ Fixes #3858

### Tests | QA Steps

1. Navigate to e.cash
2. Navigate to a conversation
3. Click on the emoji icon
4. Type something in the search box
5. Press down the arrow key to navigate through the options.
6. when at the top of the emoji list, press the Up arrow to focus the search Input.

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-07-07 19:28 UTC, roryabraham requested changes
Code looks good, but a few other feature notes:

1. When search is refocused, we should highlight the string so that the old search will be replaced by anything new you type.
1. When you start typing again (any key other than arrow or enter), then the search should refocus.

This one is more of a nice-to-have, but if you:

1. Hover over an emoji to highlight it.
1. Use the down-arrow to focus the emoji,
1. Then the focus will go to the one that you have hovered, which feels a bit weird to me. I think it should just highlight the first emoji in the first row.

2021-07-07 19:28 UTC, roryabraham commented on src/pages/home/report/EmojiPickerMenu/index.js
> +            // Keyboard events are not bubbling in RN-Web
This comment isn't super helpful in it's current state – if you include it I think it's better to explain _why_ bubbling in this case is necessary for this feature to work.

2021-07-07 21:33 UTC, parasharrajat commented
> Then the focus will go to the one that you have hovered, which feels a bit weird to me. I think it should just highlight the first emoji in the first row.

@jasperhuangg Any input for this as you originally created the Picker.

2021-07-07 21:38 UTC, roryabraham commented
I believe @stitesExpensify originally created the emoji picker. That last item I feel less strongly about too, so if you disagree let's just start with the first two.

2021-07-07 21:38 UTC, roryabraham commented
My bad ... didn't mean to close this at all.

2021-07-07 22:14 UTC, parasharrajat commented
@roryabraham 1, 2 is implemented and PR is updated. Thanks.

2021-07-08 00:20 UTC, jasperhuangg commented
> > Then the focus will go to the one that you have hovered, which feels a bit weird to me. I think it should just highlight the first emoji in the first row.
> 
> @jasperhuangg Any input for this as you originally created the Picker.

So I actually implemented something that disables mouseover input for the `EmojiPickerMenu` when an arrow key is pressed, and reenables it again when the user moves their mouse. This should prevent the issue that @roryabraham is describing here.

2021-07-08 17:54 UTC, roryabraham requested changes
Looks good and tests well. Just want to clean up the comment one more time before we merge.

2021-07-08 17:54 UTC, roryabraham commented on src/pages/home/report/EmojiPickerMenu/index.js
> +            // event is attached to document. To fix this attach event in Capture phase.
```suggestion
            // event handler attached to document root. To fix this, trigger event handler in Capture phase.
```

2021-07-08 22:33 UTC, parasharrajat commented
Updated.

2021-07-09 17:04 UTC, parasharrajat commented
@roryabraham Gentle bump. Thanks

2021-07-09 17:15 UTC, roryabraham approved these changes

2021-07-09 17:15 UTC, merged

2021-07-09 17:16 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-07-14 19:32 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/1031429034) to production         in version: 1.0.77-5🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅