feature: Add validation flow to bank account set up
Expensify/App pull request #38726
Opened 2024-03-21 04:32 UTC by dukenv0307

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/33035
PROPOSAL: https://github.com/Expensify/App/issues/33035#issuecomment-1855394934

### Tests

1. Create an unvalidated account on New Expensify by logging into expensify.com with an account on a public domain
2. Create a workspace for that account
3. Navigate to your Workspace >
4. Select either Connect Online With Plaid or Connect Manually
5. Verify that: User should see a page with a view to validate their account and receive a notification to validate their bank account.
6. Pressing the < should take them back to the Connect Bank Account with the two options mentioned in step 4.
7. Once the user verifies their account they should be able to continue with the standard bank account setup flow
  - It is expected that at this time the user will be logged out shortly after validating their account through this flow. 
- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

1. Create an unvalidated account on New Expensify by logging into expensify.com with an account on a public domain
2. Create a workspace for that account
3. Navigate to your Workspace >
4. Select either Connect Online With Plaid or Connect Manually
5. Verify that: User should see a page with a view to validate their account and receive a notification to validate their bank account.
6. Pressing the < should take them back to the Connect Bank Account with the two options mentioned in step 4.
7. Once the user verifies their account they should be able to continue with the standard bank account setup flow

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [...]

2024-05-23 11:56 UTC, allroundexperts commented
**BUG**

On going back after verification, you get logged out automatically.

https://github.com/Expensify/App/assets/30054992/a0ed2b14-9404-4aa5-9499-a9316e12788f

2024-05-27 16:21 UTC, allroundexperts commented
This seems connected to me. To make things faster, maybe we can request a bounty increase instead of creating a separate issue.

2024-05-29 09:33 UTC, allroundexperts commented
@NikkiWines Can you check if [this](https://github.com/Expensify/App/pull/38726#issuecomment-2134742812) can be fixed from the backend?

2024-05-29 16:25 UTC, NikkiWines commented
Yep, I'll take a look today!

2024-05-30 17:22 UTC, allroundexperts approved these changes
Looks good other than the logout issue which seems to be related to the backend. @NikkiWines is investigating that.

2024-05-31 07:46 UTC, NikkiWines commented
Coincidentally, it looks like we have an open PR to resolve this bug as part of a [different issue](https://github.com/Expensify/App/issues/34595) - https://github.com/Expensify/App/pull/35791 

@hayata-suenaga do you have an ETA for that PR by any chance?

2024-06-01 18:27 UTC, allroundexperts commented
I think we can merge this since the bug is un-related to this PR.

2024-06-03 14:48 UTC, hayata-suenaga commented
That PS was in my backlog. Seems like this PR is not related to my PR 😄

2024-06-06 05:03 UTC, NikkiWines commented
@hayata-suenaga it is related to your PR (though unbeknownst to you until now) as the functionality you added in https://github.com/Expensify/Web-Expensify/pull/41180 is being utilized as part of this new feature. 

However, agreed with @allroundexperts that we can merge this PR as is since the sign-out issue is already known will presumably be fixed with https://github.com/Expensify/App/pull/35791.

2024-06-06 05:20 UTC, NikkiWines requested changes
Looks good though clicking on the `verify the account` link the first time fails to redirect the user appropriately.

After that it works fine though 👍

https://github.com/Expensify/App/assets/16747822/6c64e25d-a70d-4d9c-83c1-e52f062aee57

2024-06-06 05:20 UTC, NikkiWines commented on src/languages/en.ts
> +            phrase4: 'verify the account here',
Let's change this to `verify your account here` (and also update the Spanish copy accordingly)

2024-06-07 01:36 UTC, NikkiWines approved these changes
Works great aside from the aforementioned log out issue.

2024-06-07 01:37 UTC, merged

2024-06-07 01:45 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-06-11 23:31 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/9474095450) to production by https://github.com/luacmartins in version: 1.4.81-11 🚀

platform | result
---|---
🤖 android 🤖|failure ❌
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-07-03 14:46 UTC, etCoderDysto commented
Hi @dukenv0307, I am working on extracting the component you have built here and use it on 2FA page when user is not validated. I am facing this [navigation issue](https://github.com/Expensify/App/pull/44635#issuecomment-2202515219) while trying to use the component on [CodeStep](https://github.com/Expensify/App/pull/44635/files#diff-81199675c77cf1e53cc7391b74f6444b7fa7ca0e8ef635f10b7fdf5d71dd77aa) of 2FA page. For the past few days, I have been trying to investigate the issue to no avail. Could you please help me understand the issue? Thank you!