Feature: Show local time for User in 1:1 chat
Expensify/App pull request #3883
Opened 2021-07-05 17:12 UTC by parasharrajat

### Details

### Fixed Issues

$ GH_LINK

### Tests | QA Steps
1. Open Any conversation on E.cash.
2. Other user's Local Time should be visible over the composer.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-07-07 13:13 UTC, Beamanator requested changes
I see the app crashing when I log out / log in, here's some screenshots:

![Screen Shot 2021-07-07 at 7 12 07 AM](https://user-images.githubusercontent.com/3885503/124764950-bc726e80-def2-11eb-9071-a2824bef7606.png)
![Screen Shot 2021-07-07 at 7 12 59 AM](https://user-images.githubusercontent.com/3885503/124764997-c98f5d80-def2-11eb-80cc-156202ca723b.png)

2021-07-07 13:19 UTC, parasharrajat commented
Oh Damn. Let me check. thanks for testing it.

2021-07-07 13:34 UTC, parasharrajat commented
@Beamanator Just fixed. Thanks.

2021-07-07 18:35 UTC, Beamanator requested changes
Overall looks pretty slick! One more thing I found - when we have the timezone text showing in a report, it looks like `ReportActionCompose` drops down a bit, and when you're on a report which doesn't show timezone, `ReportActionCompose` shifts back up a bit. Can we fix this?

https://user-images.githubusercontent.com/3885503/124811486-c2cb0f80-df1f-11eb-95ea-a01672e97c26.mov

2021-07-07 18:35 UTC, Beamanator commented on src/pages/home/report/ParticipantLocalTime.js
> +                        )}
NAB; I think it could be nicer to pull this out of the JSX, like under `const isReportRecipientLocalTimeReady = ...`

2021-07-07 21:23 UTC, parasharrajat commented
@Beamanator Updated. Please test now. I didn't find any jump but I think height is causing that so I have fixed it.

2021-07-08 15:12 UTC, Beamanator approved these changes
Tested on web, mweb & iOS - looks great! 👍  LGTM

2021-07-08 15:12 UTC, merged

2021-07-08 15:13 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-07-09 00:36 UTC, roryabraham commented
Unfortunately the deploy comments are not working right now. This was deployed to staging yesterday.

2021-07-09 00:41 UTC, rdjuric commented
@parasharrajat @Beamanator, I noticed a small issue with this feature. The name is disappearing if the string is bigger than the flex container. Here's a vid to help

https://user-images.githubusercontent.com/53711423/125006683-154a2000-e035-11eb-8c9b-a0d009c9a2f7.mov

2021-07-09 00:54 UTC, parasharrajat commented
Good to know. @rdjuric It just `flex:nowrap`. I will patch it up.

2021-07-09 17:33 UTC, isagoico commented
@parasharrajat Mmmm I'm still unable to see the new feature on my side, can you guys confirm this is on staging? (I'm checking on build 1.0.76-2)
![image](https://user-images.githubusercontent.com/44479856/125116033-6406c100-e0ec-11eb-92a6-fd1a2fe24d43.png)

2021-07-09 17:35 UTC, parasharrajat commented
I think its yet to be https://github.com/Expensify/Expensify.cash/issues/3905.

2021-07-09 18:57 UTC, roryabraham commented
Sorry @parasharrajat @isagoico, my [above comment](https://github.com/Expensify/Expensify.cash/pull/3883#issuecomment-876829716) was incorrect. It was added to the deploy checklist in error – this is not on staging yet. Going to check it off the deploy checklist for now. We'll want to be careful to make sure it gets tested in the next checklist.

2021-07-14 19:33 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/1031429034) to production         in version: 1.0.77-5🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅