Only provide a default lineHeight when the fontSize is default
Expensify/App pull request #3966
Opened 2021-07-10 00:01 UTC by roryabraham

### Details
Our custom `Text` component provided a default line height. However, for larger fonts, that caused the text to appear cut off. To fix, we only provide a default line height when the font size is the default.

### Fixed Issues
$ https://github.com/Expensify/Expensify.cash/issues/3964

### Tests / QA Steps
1. Open the app
1. Create a new bill split
1. Verify that the currency/amount is fully visible.

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots
#### Web
![image](https://user-images.githubusercontent.com/47436092/125145733-5bf05680-e0d7-11eb-87f0-49386af1f387.png)

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-07-10 00:02 UTC, OSBotify commented
:warning: :warning: **Heads up! This pull request has the `CP Staging` label.** :warning: :warning:
Merging it will cause it to be immediately deployed to staging, _even if the [open `StagingDeployCash` deploy checklist](https://github.com/Expensify/Expensify.cash/issues?q=is%3Aopen+is%3Aissue+label%3AStagingDeployCash) is locked._

2021-07-12 15:02 UTC, Dal-Papa approved these changes

2021-07-12 17:48 UTC, deetergp requested changes, later dismissed
Considering the initial issue was logged on Android, it is espcially important that it be tested on Android. Disagree?

2021-07-12 18:03 UTC, roryabraham commented
> Considering the initial issue was logged on Android, it is espcially important that it be tested on Android

Agree! I was having emulator issues before I ran out of time EOD on Friday when I created this PR, but I will work on getting the Android testing done here.

2021-07-12 18:26 UTC, roryabraham commented
Sorry about that @deetergp, G2G now 👍

2021-07-12 22:45 UTC, roryabraham commented
@deetergp Friendly bump because this resolves an hourly deploy blocker

2021-07-12 23:58 UTC, thienlnam approved these changes

2021-07-13 00:00 UTC, thienlnam commented
Hmm looks like it still needs an approval from @deetergp (Since this is an hourly deploy blocker and Scott's comment was addressed going to see if I can unassign to merge)

2021-07-13 00:01 UTC, mountiny commented
@thienlnam You need to Dismiss his review

2021-07-13 00:02 UTC, merged

2021-07-13 00:02 UTC, thienlnam commented
@mountiny Thanks!

2021-07-13 00:50 UTC, OSBotify commented
🚀 [Cherry-picked](https://github.com/Expensify/Expensify.cash/actions/runs/1024725033) to staging         in version: 1.0.77-2🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-07-14 19:32 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/1031429034) to production         in version: 1.0.77-5🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-07-14 19:53 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/1031434935) to staging         in version: 1.0.77-6🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2021-07-23 21:15 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1060984705) to production         in version: 1.0.79-4🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅