[Mentions v2] Parse <mention-report> when displaying reportAction
Expensify/App pull request #39906
Opened 2024-04-09 09:20 UTC by war-in

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/39545
PROPOSAL:

### Tests

To check the functionality paste the code in `src/pages/home/report/ReportActionsView.tsx` under the `PopoverReactionList` (line 533)
```
<RenderHTML html="<comment><mention-report>#admins</mention-report></comment>" />
<RenderHTML html='<comment><mention-report reportID="3088255940953979" /></comment>' />
<RenderHTML html="<comment><mention-report>#non-existent-room</mention-report></comment>" />
<RenderHTML html='<comment><mention-report reportID="111111" /></comment>' />        
```

1. Go to a chat
2. There should be some tags
![image](https://github.com/Expensify/App/assets/61014013/715322a3-116c-4b24-8e5d-4187f8c99870)
3. The first one is clickable and redirects to the `#admins` room
4. The second one is clickable and redirects to the chat of id `3088255940953979` (you probably would need to change the id to one existing on your account)
5. Last two should not redirect because there are no such rooms

### Offline tests

### QA Steps

To check the functionality paste the code in `src/pages/home/report/ReportActionsView.tsx` under the `PopoverReactionList` (line 533)
```
<RenderHTML html="<comment><mention-report>#admins</mention-report></comment>" />
<RenderHTML html='<comment><mention-report reportID="3088255940953979" /></comment>' />
<RenderHTML html="<comment><mention-report>#non-existent-room</mention-report></comment>" />
<RenderHTML html='<comment><mention-report reportID="111111" /></comment>' />        
```

1. Go to a chat
2. There should be some tags
![image](https://github.com/Expensify/App/assets/61014013/715322a3-116c-4b24-8e5d-4187f8c99870)
3. The first one is clickable and redirects to the `#admins` room
4. The second one is clickable and redirects to the chat of id `3088255940953979` (you probably would need to change the id to one existing on your account)
5. Last two should not redirect because there are no such rooms

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can  [...]

2024-04-09 11:34 UTC, robertKozik commented on src/components/HTMLEngineProvider/HTMLRenderers/MentionRoomRenderer.tsx
> +    const removeLeadingLTRAndHash = (value: string) => value.replace(CONST.UNICODE.LTR, '').slice(1);
get it outside the component

2024-04-09 11:35 UTC, robertKozik commented on src/components/HTMLEngineProvider/HTMLRenderers/MentionRoomRenderer.tsx
> +    }
extract to separate function

2024-04-09 11:39 UTC, robertKozik commented on src/components/HTMLEngineProvider/HTMLRenderers/MentionRoomRenderer.tsx
> +        reportID = report?.reportID ? parseInt(report.reportID, 10) : undefined;
remove `parseInt`

2024-04-09 11:51 UTC, robertKozik commented on src/components/HTMLEngineProvider/HTMLRenderers/MentionRoomRenderer.tsx
> +    },
limit reports to only to used values

2024-04-10 09:30 UTC, robertKozik commented
Hi! We were in the internal review process, but the PR is already available for review 🚀

2024-04-10 15:11 UTC, puneetlath commented
I think we should call the renderer `MentionReport` instead of `MentionRoom` since the tag is `<mention-report>`

2024-04-10 19:20 UTC, robertKozik commented
> Linking to another room only seems to work from rooms, not from a normal chat. `navigationRoute` seems to be undefined when attempting to navigate from a normal chat:

Actually @rlinoz @puneetlath When user types by hand room mention (auto complete is disabled for chats which are not in group policy) we will parse it and send to backend (parser is not aware of chat type). Will backend filtered this tag out?

2024-04-10 19:22 UTC, robertKozik commented
> I think we should call the renderer `MentionReport` instead of `MentionRoom` since the tag is `<mention-report>`

Changed 👌🏼

2024-04-10 19:44 UTC, robertKozik commented
So if we have only optimistic version of the report action the expected behaviour would be to check if mentions are allowed in current report and if not just return null and not render it at all?

2024-04-10 20:08 UTC, rlinoz commented
I think we should strip out the tag and render as plain text if the mention is happening in a report that is not allowed.

2024-04-11 21:30 UTC, rlinoz commented
> I think we should strip out the tag and render as plain text if the mention is happening in a report that is not allowed.

Just to be sure, we are going to do that in this PR right?

2024-04-11 22:34 UTC, robertKozik commented
Yeah @war-in will take care of it tommorow

2024-04-12 09:13 UTC, robertKozik commented on src/components/HTMLEngineProvider/HTMLRenderers/MentionReportRenderer.tsx
> +        const report = reports?.['report_'.concat(htmlAttributeReportID)];
```suggestion
        const report = getReport(htmlAttributeReportID)
```

2024-04-12 09:14 UTC, robertKozik commented on src/components/HTMLEngineProvider/HTMLRenderers/MentionReportRenderer.tsx
> +    const currentReportID = useCurrentReportID();
You can destructure here
```suggestion
    const {currentReportID} = useCurrentReportID();
```

2024-04-12 11:10 UTC, war-in commented
@Ollyws fixed! Now, linking from the chat is disabled as @rlinoz requested

2024-04-12 13:30 UTC, Ollyws approved these changes
LGTM.

2024-04-12 13:57 UTC, rlinoz requested changes

2024-04-12 13:57 UTC, rlinoz commented on src/components/HTMLEngineProvider/HTMLRenderers/MentionReportRenderer.tsx
> +                    #{mentionDisplayText}
I think this is duplicating the `#` for `reportID` mentions.
<img width="339" alt="image" src="https://github.com/Expensify/App/assets/5201282/823676e7-c71d-4afa-b595-e3e3e287a2cb">

2024-04-12 13:57 UTC, rlinoz commented on src/components/HTMLEngineProvider/HTMLRenderers/MentionReportRenderer.tsx
> +    // get mention details based on reportID from tag attribute
```suggestion
    // Get mention details based on reportID from tag attribute
```

2024-04-12 13:57 UTC, rlinoz commented on src/components/HTMLEngineProvider/HTMLRenderers/MentionReportRenderer.tsx
> +        // get mention details from name inside tnode
```suggestion
        // Get mention details from name inside tnode
```

2024-04-12 14:53 UTC, war-in commented
@rlinoz fixed 😌

2024-04-12 15:52 UTC, puneetlath approved these changes

2024-04-12 15:55 UTC, rlinoz approved these changes
Thanks!

2024-04-12 15:56 UTC, merged

2024-04-18 04:57 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/8732363773) to staging by https://github.com/rlinoz in version: 1.4.63-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-04-18 05:53 UTC, kbecciv commented
@war-in Can you verify internally, not sure if QA team can paste the code in src/pages/home/report/ReportActionsView.tsx under the PopoverReactionList (line 533)?

2024-04-18 10:37 UTC, robertKozik commented
As I saw that other PR's related to mentions are deployed as well, you should be able to just type the mention inside composer - sent message should contain the mention and be styled properly.