Fix wrong active report on LHN
Expensify/App pull request #4004
Opened 2021-07-13 14:40 UTC by rdjuric

### Details

The componentDidMount lifecycle isn't fired when we navigate to a ReportScreen from the Search/FAB. So we need to call our `storeCurrentlyViewedReport` method in the componentDidUpdate lifecycle (after checking for a report change).

### Fixed Issues

$ https://github.com/Expensify/Expensify.cash/issues/3982

### Tests

**Chat switcher scenario:**
1. Open chat switcher via CMD + K or in windows use the search function
2. Search for an user
3. Select any user
4. LHN should show the selected user as the active chat

**Request Money scenario:**
1. Click on FAB
2. Click on request money
3. Set an amount
4. Search for any user
5. Finish the request money flow
6. LHN should show the selected user as the active chat

### QA Steps

Same as above.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-07-13 16:42 UTC, pecanoro requested changes

2021-07-13 16:42 UTC, pecanoro commented on src/pages/home/ReportScreen.js
> +
```suggestion
```

2021-07-13 16:57 UTC, rdjuric commented
Updated @pecanoro

2021-07-13 20:45 UTC, pecanoro approved these changes

2021-07-13 20:45 UTC, merged

2021-07-13 20:45 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-07-14 19:52 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/1031434935) to staging         in version: 1.0.77-6🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2021-07-23 21:15 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1060984705) to production         in version: 1.0.79-4🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅