[Feature] Support to html pasting on web
Expensify/App pull request #4009
Opened 2021-07-13 17:49 UTC by parasharrajat

### Details

### Fixed Issues

$ Fixes #3790

### Tests | QA Steps

    1. Copy the following text:

 *Bold text*
_italic text_
~Strikethrough text~

 2. Paste the text in e.cash

### Tested On

- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-07-14 02:12 UTC, Jag96 requested changes
A couple of nitpicks but it's working well!

2021-07-14 02:14 UTC, parasharrajat commented on src/components/TextInputFocusable/index.js
> +        const pastedHTML = event.clipboardData.getData(TEXT_HTML);
Yes. Thanks

2021-07-14 02:14 UTC, parasharrajat commented on src/components/TextInputFocusable/index.js
> +            const embededImages = domparser.parseFromString(pastedHTML, TEXT_HTML).images;
Yup. It was already there but I will update.

2021-07-14 02:21 UTC, parasharrajat commented
@Jag96 While handling all this I found a couple of issues.
1. If we edited the formatted text I see MD syntax but clicking save does not show formatting anymore.
![image](https://user-images.githubusercontent.com/24370807/125550202-79e126ce-2d62-4155-8b91-4a6f1e95f45b.png)
2. There is an extra Line Break added on paste. I debugged the main cause and found we are getting newlines via HTMLparser.
3. When I copy the existing sent message which is formatted and pastes it. it does not convert to formatted MD strings. The main issue here is that we don't use HTML semantic tags for rendering Every type of element is made with div and styling rules. Which we can't really interpret ATM.

2021-07-14 02:48 UTC, parasharrajat commented
Updated.

2021-07-14 02:51 UTC, Jag96 commented
Good finds!

- `1` sounds like a regression to me, so I think that would be a blocker in this case and something we should look into.
- For `2`, I tested on Firefox and Chrome and it looks like Firefox has extra line breaks in the HTML whereas Chrome doesn't. Could that be the issue there? If our code is adding unnecessary line breaks I think that'd be a blocker, but if it's just the way the HTML is copied from the browser I don't think that should block this PR. Looking into this a bit more, I do see that there are `<br>` tags in the HTML when pasting on chrome (using the same text in the [issue description](https://github.com/Expensify/Expensify.cash/issues/3790)), so perhaps there is an issue w/ the newline regex causing it to fail in this case?
- For `3` that sounds like a different issue and something to discuss in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) since I think that will be a bit more involved, so I wouldn't block this PR on that.

Thoughts?

2021-07-14 02:55 UTC, parasharrajat commented
Ok. I agree. Should I add those fixes in this PR?

2021-07-14 02:57 UTC, Jag96 commented
I think fixes for 1 and 2 should be added to this PR, assuming 2 requires a fix.

2021-07-14 03:26 UTC, parasharrajat commented
@Jag96 Just opened a new PR for `2`. https://github.com/Expensify/expensify-common/pull/393. Could be merged quickly and we can move forward here.

2021-07-14 03:41 UTC, parasharrajat commented
Okay, I have updated the E-common here. and `1` & `2` is fixed

2021-07-14 04:09 UTC, parasharrajat commented
Please let me know if anything else is needed here.

2021-07-14 04:30 UTC, Jag96 commented
1 looks good, for 2 it looks like when I copy HTML that contains a `<br>` tag it doesn't add the line breaks if the `<br>` tag has styles. For example, copying the following from https://github.com/Expensify/Expensify.cash/issues/3790:

![image](https://user-images.githubusercontent.com/3981102/125560311-669d9425-d9e5-42bd-a17e-7d79e89a1c79.png)

Results in the following `html` value inside `handlePastedHTML`
```
"<meta charset='utf-8'><strong style=\"box-sizing: border-box; font-weight: 600; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\">Bold text</strong><br style=\"box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><em style=\"box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\">italic text</em><br style=\"box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><del style=\"box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);\">Strikethrough text</del>"
```

Before this PR, pasting the content would include these line breaks, but now it strips them:

| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/3981102/125560790-373dd3d4-f53d-47af-ba50-73a1d7fe2af0.png) | ![image](https://user-images.githubusercontent.com/3981102/125560806-81512d58-b062-4530-b195-2e400a7c3995.png) |

However, this just looks like a bug in the regex and isn't really tied to the core of this PR, so I won't block on it and I'll open a new issue for this.

2021-07-14 04:30 UTC, Jag96 approved these changes

2021-07-14 04:31 UTC, merged

2021-07-14 04:31 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-07-14 05:17 UTC, parasharrajat commented
Yeah @Jag96  Do you want me to correct the Br tag regex

2021-07-14 19:52 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash/actions/runs/1031434935) to staging         in version: 1.0.77-6🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2021-07-14 22:04 UTC, Jag96 commented
@parasharrajat sounds good, feel free to leave a comment on https://github.com/Expensify/Expensify.cash/issues/4052 so I can assign you, I'll invite you to the Upwork job in the meantime

2021-07-16 11:22 UTC, isagoico commented
@Jag96 Since this PR is failing because of the [issue](https://github.com/Expensify/Expensify.cash/issues/4052) above, should we block prod deploy on this? or can we check it off the PR list and test this again when the fix is merged?

2021-07-16 17:00 UTC, Jag96 commented
No worries! Now that https://github.com/Expensify/Expensify.cash/pull/4067 is on staging that'll be the latest fix

2021-07-23 21:14 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1060984705) to production         in version: 1.0.79-4🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-02-02 01:07 UTC, sonialiap commented
An error was identified that was linked to this PR - https://github.com/Expensify/App/issues/9505