React native 0.74 upgrade
Expensify/App pull request #40548
Opened 2024-04-19 10:15 UTC by MrRefactor

### Details

### Fixed Issues

$
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-04-22 16:39 UTC, roryabraham requested changes
Two things:

1. For any new patches, please include a link to the upstream PR in this PR description. This is _critical_ for us because when upgrade the dependency in the future we need a clear record of what the patch is and does to understand how or if it needs to be migrated to the new version of the dependency. We should only be adding patches where there is an existing PR upstream. The ideal path is to get those upstream PRs merged and to upgrade the dependency rather than introducing a patch.
2. Let's try to find ways to incrementally land portions of this PR to reduce the diff and decrease the likelihood of regressions. There appear to be a number of changes that we could introduce in separate PRs and merge sooner. Most notably, all the dependency upgrades (onfido, mapbox, reanimated, webview, safe-area-context, eslint + jest). Please try to work with your coworkers to create several separate upgrade PRs so we can land those upgrades in production ASAP.

2024-06-05 12:35 UTC, mountiny commented
Adding @shubham1206agra this is ready for a review

2024-06-05 12:41 UTC, MrRefactor commented
> @MrRefactor The size of Android APK got way too big (278.06 MB vs current 116 MB). Can you please check this?

I will check that

2024-06-05 13:44 UTC, MrRefactor commented
> @MrRefactor The size of Android APK got way too big (278.06 MB vs current 116 MB). Can you please check this?

I have just fix the APK size, it should look better with next build

2024-06-07 09:14 UTC, MrRefactor commented
> Unable to switch back from offline to online (using troubleshoot settings).
> 
> 1. Go to Troubleshoot Page.
> 2. Switch Force Offline twice.

Fixed

2024-06-07 09:14 UTC, MrRefactor commented
> 
> 2FA page getting weird.

Fixed

2024-06-10 07:58 UTC, mountiny commented
@MrRefactor Can you sync with main?

2024-06-10 10:18 UTC, MrRefactor commented
> @MrRefactor Can you sync with main?


Synced

2024-06-10 13:45 UTC, MrRefactor commented
> @MrRefactor The size is still huge.

Im trying to find out why as my local builds are not exceeding 175MB

2024-06-11 13:29 UTC, kubabutkiewicz commented
@shubham1206agra can you give more details? Which platform? What are the actual steps to reproduce? Is this is happening after clicking Submit Expense from FAB or something else?

2024-06-12 03:58 UTC, MrRefactor commented
> > > Unable to switch back from offline to online (using troubleshoot settings).
> > > 
> > > 1. Go to Troubleshoot Page.
> > > 2. Switch Force Offline twice.
> > 
> > 
> > issue from main, fixed after merging new changes
> 
> This is still not fixed for me.

Reproduced the issue on main - it takes around 20s for me after toggling "Force offline" off for "You appear to be offline" message to disappear.

2024-06-17 13:35 UTC, mountiny commented
kicked off a new build https://github.com/Expensify/App/actions/runs/9548698293

2024-06-18 11:30 UTC, MrRefactor commented
@mountiny Please run ad hoc builds and remove cache for pod's for iOS pipeline as its breaking on pod install step. Also desktop build crashed, I believe its caused by worker error.

2024-06-19 07:25 UTC, MrRefactor commented
> 
> @MrRefactor The Track Expense modal is not working correctly. Go to FAB > Track Expense to reproduce.

There is an issue with displaying `FeatureTrainingModal` looking into it.

2024-06-19 13:56 UTC, kubabutkiewicz commented
Hi @tomekzaw @j-piasecki this issue https://github.com/Expensify/App/pull/40548#issuecomment-2176118940 was caused by `GestureHandlerRootView` when it was inside `Modal` component, I was able to fix it by moving it out of `Modal` buy just wanted to let you know that its causing issue.

2024-06-19 14:42 UTC, j-piasecki commented
> Hi @tomekzaw @j-piasecki this issue https://github.com/Expensify/App/pull/40548#issuecomment-2176118940 was caused by GestureHandlerRootView when it was inside Modal component, I was able to fix it by moving it out of Modal buy just wanted to let you know that its causing issue.

Thanks for the ping! Just FYI: moving root view outside of modal will prevent gestures inside the modal from working on Android. Have you tried moving it deeper into the view hierarchy instead (assuming there are any gestures there)?

2024-06-20 09:18 UTC, koko57 commented
@shubham1206agra are you able to reproduce it consistently? I'm not able to reproduce it. Isn't it because you have copied this address earlier and you have it in your clipboard?

2024-06-20 09:46 UTC, kubabutkiewicz commented
@shubham1206agra can you elaborate more whats wrong with the emojis? I am not able to reproduce it

https://github.com/Expensify/App/assets/25230417/f906a30d-acf2-4b90-930e-2b094930b016

2024-06-20 10:15 UTC, MrRefactor commented on Gemfile
> +gem 'cocoapods', '>= 1.13', '< 1.15'
@shubham1206agra @roryabraham we dont need to revert this change, `cocoapods` 15.2.0 already have the fix for breaking builds.

2024-06-20 10:36 UTC, MrRefactor commented on Gemfile
> +gem 'cocoapods', '>= 1.13', '< 1.15'
I will remove it while merging changes from main

2024-06-25 17:00 UTC, roryabraham requested changes
Its _CRITICAL_ that for every added patch, we include in the PR description a link to the upstream commit, PR and/or issue, along with a comment explaining why the patch was added, ideally in the form of reproduction steps in the form of `Actions Taken` / `Expected Result` / `Actual Result`

2024-06-26 11:23 UTC, mountiny commented
@shubham1206agra How is the testing going? How far are we from some stable form where we could ask Applause for testing?

2024-06-26 11:45 UTC, MrRefactor commented
@mountiny could you please run ad hoc builds so @shubham1206agra can verify attachments?

2024-06-26 15:04 UTC, shawnborton commented
I can run the test builds quickly...

2024-06-27 08:57 UTC, MrRefactor commented
> Its _CRITICAL_ that for every added patch, we include in the PR description a link to the upstream commit, PR and/or issue, along with a comment explaining why the patch was added, ideally in the form of reproduction steps in the form of `Actions Taken` / `Expected Result` / `Actual Result`

@roryabraham @mountiny updated PR description with list of patches

2024-06-27 09:27 UTC, MrRefactor commented on package.json
> +    "expo": "51.0.0",
done

2024-06-28 08:31 UTC, kubabutkiewicz commented
@shubham1206agra I don't see that crash on local and on ad hoc build, did you run `npm ci` ?

2024-06-28 13:19 UTC, kubabutkiewicz commented
@shubham1206agra actually there was a problem with web crash , I pushed a fix

2024-07-01 16:57 UTC, lanitochka17 commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  Android - Composer - Previous text is cut off after creating next line

**Version Number:**  9.0.1-0 adhoc
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal Team


## Action Performed:
1. Launch New Expensify app
2. Go to any chat
3. Type anything
4. Hit Enter to create a new line (do not type anything on the new line)

## Expected Result:
The previous line will be fully visible in the composer

## Actual Result:
The previous line is cut off in the composer when the next line is created and empty

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?

- [x] Android


## Screenshots/Videos


https://github.com/Expensify/App/assets/78819774/7ee86fb0-5d35-4158-95b1-b669c05396b0



</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-01 17:01 UTC, lanitochka17 commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  Android - Composer - Pasted multiline message is displayed in one line

**Version Number:**  9.0.1-0 adhoc
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal Team


## Action Performed:
1. Launch New Expensify app
2. Go to any chat
3. Send a multiline message
4. Long tap on the message > Copy to clipboard
5. Paste the content in the composer
6. Scroll the pasted content

## Expected Result:
The pasted multlline message will be displayed completely

## Actual Result:
The pasted multlline message is displayed in one line, while the composer is expanded

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?

- [x] Android


## Screenshots/Videos

</details> 

https://github.com/Expensify/App/assets/78819774/6fc9230a-97bd-4c3b-bf8a-9a3a9f5d045c


[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-01 17:05 UTC, lanitochka17 commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  Android - Composer - The suggestion list appears with spacing above the composer

**Version Number:**  9.0.1-0 adhoc
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal Team


## Action Performed:
1. Launch New Expensify app.
2. Go to any chat.
3. Type :sm to open emoji suggestion list.

## Expected Result:
The suggestion list will appear above the text/composer

## Actual Result:
The suggestion list appears with spacing above the composer

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?

- [x] Android


## Screenshots/Videos

</details> 

https://github.com/Expensify/App/assets/78819774/54ebca60-61cc-4901-984a-3938e579ee5a


[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-01 17:30 UTC, kbecciv commented
@MrRefactor @mountiny @roryabraham 
Is it okay to test on build v9.0.1-0?
![image (5)](https://github.com/Expensify/App/assets/93399543/9b05e27d-2b7b-4d28-8f8c-68d792a28c70)

2024-07-01 19:50 UTC, lanitochka17 commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  Task – Hidden assignee appears in LHN when assign task without assignee to yourself

**Version Number:**  9.0.1-0 adhoc
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal Team


## Action Performed:
1. Go to https://40548.pr-testing.expensify.com/
2. Log in as user A
3. Open room chat where user B is a member
4. Create a task without assignee
5. As user B open task details and assign it to yourself
6. Find task in LHN

## Expected Result:
Assignee name appears in LHN

## Actual Result:
Hidden assignee appears in LHN

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?

- [x] Web/Chrome



## Screenshots/Videos

</details> 


https://github.com/Expensify/App/assets/78819774/22eb3ab1-7cc7-4736-adea-eeab5bbf4023

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-01 20:10 UTC, lanitochka17 commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  Android - Chat - Green background flickers when dismissing the + modal

**Version Number:**  9.0.1-0 adhoc
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal Team


## Action Performed:
1. Launch New Expensify app
2. Go to any chat
3. Tap +
4. Dismiss the modal by tapping outside the modal

## Expected Result:
The green background will not flicker when dismissing the + modal

## Actual Result:
The green background flickers when dismissing the + modal

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?

- [x] Android



## Screenshots/Videos

</details> 

https://github.com/Expensify/App/assets/78819774/d00321bd-3999-494a-96cd-65fae6ee5c53

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-01 21:21 UTC, lanitochka17 commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  IOS - Image preview before sending is not displayed for images from the gallery

**Version Number:**  9.0.1-0 adhoc
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal Team


## Action Performed:
1. Go to any chat
2. Tap on the "+" button
3. Select Add attachment and Choose from the gallery
4. Select any photo from the gallery
5. Verify an infinite loading spinner is displayed

## Expected Result:
The photo preview should be displayed

## Actual Result:
An infinite loading spinner is displayed

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?

- [x] IOS


## Screenshots/Videos

</details> 


https://github.com/Expensify/App/assets/78819774/05b91323-1c22-403c-82cb-6754f594807d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-01 21:35 UTC, lanitochka17 commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  iOS - Track expense - App crashes after selecting track expense

**Version Number:**  9.0.1-0 adhoc
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal Team


## Action Performed:
1. Open the app and log in with a new account
2. Tap FAB > Track expense

## Expected Result:
The BNP and educational modal with video are opened

## Actual Result:
The app crashes

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?

- [x] IOS


## Screenshots/Videos

</details> 


https://github.com/Expensify/App/assets/78819774/684baea7-9a42-4a6a-9bc7-29691ec345bc

[logs (2).txt](https://github.com/user-attachments/files/16059221/logs.2.txt)


[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-01 21:43 UTC, lanitochka17 commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##   iOS - App crashes after selecting a video as the attachment to send

**Version Number:**  9.0.1-0 adhoc
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal Team


## Action Performed:
1. Go to any chat.
2. Tap on the "+" button.
3. Select Add attachment.
3. Try to send any video from any option (Choose from gallery or Choose file).

## Expected Result:
A video preview before sending the file should be displayed

## Actual Result:
The app crashes after selecting a video as a file to send

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?

- [x] IOS


## Screenshots/Videos

</details> 

https://github.com/Expensify/App/assets/78819774/e8a7883e-08bd-4bd4-badd-74c6e5a50eed


[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-01 21:46 UTC, lanitochka17 commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  IOS-Distance rate-Keyboard not open/disappear smoothly when selecting default category

**Version Number:**  9.0.1-0 adhoc
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal Team


## Action Performed:
1. Open the app and log in
2. Create a workspace
3. Navigate to workspace settings > More features
4. Enable Distance rates
5. Open Distance rates > Settings
6. Select "Default category"
7. Tap somewhere to dismiss the keyboard

## Expected Result:
The keyboard opens/disappears smoothly

## Actual Result:
The keyboard opens/disappears with some flickering

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?

- [x] IOS


## Screenshots/Videos

</details> 


https://github.com/Expensify/App/assets/78819774/d6ab5a5a-acb2-4e9d-8a3b-64594445aed9




[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-02 09:16 UTC, izarutskaya commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  Android - Expense - Cursor positions behind the currency when editing amount

**Version Number:**  v1.4.85-0  adhoc
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal Team


## Action Performed:
1. Launch New Expensify app.
2. Go to FAB > Submit expense > Manual.
3. Submit a manual expense to any user.
4. Immediately go to transaction thread.
5. Tap Amount.

## Expected Result:
The cursor positions after the currency.

## Actual Result:
The cursor positions behind the currency.

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?

- [x] Android


## Screenshots/Videos

</details> 


https://github.com/Expensify/App/assets/115492554/37d230d3-ecc9-46e4-a27b-fa9f4ff0f238



[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-02 09:39 UTC, izarutskaya commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  iOS - No image preview on confirmation screen when creating scan request

**Version Number:**  v1.4.85-0  adhoc
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal Team


## Action Performed:
1. Tap on the FAB button.
2. Select Submit expense.
3. On the scan tab, take a photo.
4. Select any user/workspace to send the request.
5. Verify no photo preview is displayed on the confirmation screen.

## Expected Result:
A photo preview should be displayed on the confirmation screen.

## Actual Result:
No photo preview is displayed on the confirmation screen.

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?

- [x] iOS


## Screenshots/Videos

</details> 






[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-02 10:04 UTC, MrRefactor commented
Hey @tomekzaw 
Could you please take a look if these issues are `react-native-libe-markdown` related?
https://github.com/Expensify/App/pull/40548#issuecomment-2200629563
https://github.com/Expensify/App/pull/40548#issuecomment-2200637317
https://github.com/Expensify/App/pull/40548#issuecomment-2200643475

2024-07-02 10:15 UTC, tomekzaw commented
@MrRefactor I'm quite packed this week; could you please replace `RNMarkdownTextInput` with `RNTextInput` and confirm if these bugs are indeed caused by `react-native-live-markdown`? If yes, please report them to `react-native-live-markdown` repo and we'll fix them on our side.

2024-07-02 10:26 UTC, MrRefactor commented
> @MrRefactor I'm quite packed this week; could you please replace `RNMarkdownTextInput` with `RNTextInput` and confirm if these bugs are indeed caused by `react-native-live-markdown`? If yes, please report them to `react-native-live-markdown` repo and we'll fix them on our side.

checking

2024-07-02 14:20 UTC, kacper-mikolajczak commented
> ## Task – Hidden assignee appears in LHN when assign task without assignee to yourself
> **Version Number:** 9.0.1-0 adhoc **Reproducible in staging?:** N **Reproducible in production?:** N **Issue reported by:** Applause-Internal Team
> 
> ## Action Performed:
> 1. Go to https://40548.pr-testing.expensify.com/
> 2. Log in as user A
> 3. Open room chat where user B is a member
> 4. Create a task without assignee
> 5. As user B open task details and assign it to yourself
> 6. Find task in LHN
> 
> ## Expected Result:
> Assignee name appears in LHN
> 
> ## Actual Result:
> Hidden assignee appears in LHN

Hi @lanitochka17 👋 I am responsible for the regression and I would like to help. 

I went through repro steps on:
- adhoc build 
- the latest PR commit 

For the **adhoc build** I confirm the issue exists, however it does not seem to persist on **latest commit**.

Here is a recording showing comparison process between two environments. 

https://github.com/Expensify/App/assets/62747088/5584d1ac-66b7-4de8-af54-f1cb8b383603

Let me know if I properly tried to reproduce the bug and let me know how can I help further with the issue or shall we treat it as resolved. Thank you!

2024-07-02 14:26 UTC, kacper-mikolajczak commented
[IOU - Same results appear twice when search email on submit expense modal](https://github.com/Expensify/App/pull/40548#issuecomment-2200896495)


Hi @lanitochka17 once again 😄  I am responsible for the regression and I would like to help. 

I went through repro steps on:
- adhoc build 
- the latest PR commit 

For the **adhoc build** I confirm the issue exists, however it does not seem to persist on **latest commit**.

Here is a recording showing comparison process between two environments. 

https://github.com/Expensify/App/assets/62747088/c31e13b0-ff56-46eb-bc1e-8bb67a48ed73

As before, please let me know if I properly tried to reproduce the bug and let me know how can I help further with the issue or shall we treat it as resolved. Thank you!

PS

Just to be sure, I have ran the test after cleaning app entirely on dev and there was no regression found. Here is a recording after removing app data.

https://github.com/Expensify/App/assets/62747088/2bc86571-bd37-45e7-a9b5-9bbeec10a327

2024-07-02 15:10 UTC, lanitochka17 commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  Android - Workspace chat avatar preview is not displayed

**Version Number:**  1.4.85-0  adhoc
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal Team


## Action Performed:
1. Create Workspace
2. Invite User B to the Workspace
3. Navigate to individual workspace chat with User B
4. Tap on User's B avatar to open detail page
5. Tap on Avatar


## Expected Result:
Avatar should be displayed

## Actual Result:
Avatar is not displayed until tap on the page

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?

- [x] Android


## Screenshots/Videos

</details> 

https://github.com/Expensify/App/assets/78819774/693b7b39-167e-4011-ba3c-b3be07dee3b6


[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-02 15:57 UTC, lanitochka17 commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  Android - Expense - App flickers when opening and closing year picker repeatedly

**Version Number:**  1.4.85-0  adhoc
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Issue reported by:** Applause-Internal Team


## Action Performed:
1. Launch New Expensify app
2. Go to any chat
3. Go to + > Submit expense > Manual
4. Proceed to confirmation page
5. Tap Show more > Date
6. Tap Year
7. Open and close year picker repeatedly


## Expected Result:
App will not flicker

## Actual Result:
App flickers when opening and closing year picker repeatedly

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?

- [x] Android


## Screenshots/Videos

</details> 


https://github.com/Expensify/App/assets/78819774/9c287b6b-4366-4065-9e0a-20e58d3bfb01


[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-09 20:21 UTC, mountiny commented
@MrRefactor Let me know when you think we should create a new build

2024-07-11 13:09 UTC, MrRefactor commented
hey @mountiny I think we can run builds to finish iOS testing.

Also while working on suggestion box issue -> [link](https://github.com/Expensify/App/pull/40548#issuecomment-2200643475) -  @perunt I noticed that you implemented functionality for calculating suggestionBox position, could you take a look on that and help me resolve the issue? 
there are some values I gathered while testing on both platforms:

Android, keyboard opened:
```
windowHeight: 783.2727272727273,
y: 387.6363525390625,
cursorCoordinates.y: 4.363636493682861,
scrollValue: 0,
keyboardHeight: 274.9090881347656,
bottomInset: 0
```
Android, keyboard closed:
```
windowHeight: 783.2727272727273,
y: 662.54541015625,
cursorCoordinates.y: 4.363636493682861,
scrollValue: 0,
keyboardHeight: 0,
bottomInset: 0
```
iOS, keyboard opened:
```
windowHeight: 932,
y: 513,
cursorCoordinates.y: 20.666666666666668,
scrollValue: 0,
keyboardHeight: 274.9090881347656,
bottomInset: 23.799999999999997
```
iOS, keyboard closed:
```
windowHeight: 932,
y: 835.3333129882812,
cursorCoordinates.y: 20.666666666666668,
scrollValue: 0,
keyboardHeight: 0,
bottomInset: 23.799999999999997
```

2024-07-12 09:54 UTC, perunt commented
@MrRefactor, can you check out the latest changes from the main branch? This issue might be potentially fixed there as the position calculation method was changed

2024-07-12 10:01 UTC, MrRefactor commented
> @MrRefactor, can you check out the latest changes from the main branch? This issue might be potentially fixed there as the position calculation method was changed

sure, pulling latest main

2024-07-12 12:33 UTC, MrRefactor commented
@perunt the issue is still here after applying changes from latest main
![Screenshot 2024-07-12 at 14 32 25](https://github.com/user-attachments/assets/73b7c51d-30d3-4b4d-ad00-2da7e8fa35e2)

2024-07-19 07:24 UTC, MrRefactor commented
> @MrRefactor Can you update description please? 
already done

2024-07-19 17:23 UTC, MrRefactor commented
any idea why is this test failing? Locally its passing 
![Screenshot 2024-07-19 at 10 05 21](https://github.com/user-attachments/assets/a1cee415-c19c-453a-9b36-6ed07460f730)

2024-07-19 21:25 UTC, kubabutkiewicz commented
@MrRefactor I saw a thread about it in slack https://expensify.slack.com/archives/C01GTK53T8Q/p1721375022329119

2024-07-19 21:32 UTC, mountiny commented
I have cleared the caches and ran a new build https://github.com/Expensify/App/actions/runs/10014592690

2024-07-19 21:49 UTC, MrRefactor commented
> I have cleared the caches and ran a new build https://github.com/Expensify/App/actions/runs/10014592690

Looks like caches for pods haven't cleared properly :(

2024-07-19 23:27 UTC, mountiny commented
Cleared lots of cache again and started it now https://github.com/Expensify/App/actions/runs/10015565519

2024-07-20 00:09 UTC, mountiny commented
Would you look at that

2024-07-29 09:19 UTC, izarutskaya commented
## Chat - Emoji suggestion box displayed slightly extra above the compose box.


If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4770519
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team


## Action Performed:
1. Launch app
2. Tap on a group chat
3. Enter :+1

## Expected Result:
Emoji suggestion box must not be displayed slightly extra above the compose box.

## Actual Result:
Emoji suggestion box is displayed slightly extra above the compose box.

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] iOS: Native


## Screenshots/Videos

![Bug6555668_1722212073958!Screenshot_2024-07-29-05-38-19-319_com expensify chat adhoc](https://github.com/user-attachments/assets/ae65dabb-3586-40d5-8f88-923016067fb9)


</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-29 10:00 UTC, izarutskaya commented
## Attachment - Opening attachments takes you back to the first attachment


If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4770512
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team


## Action Performed:
1. Go to any chat
2. Send a couple of attachments in the chat
3. Click on any attachment other than the first attachment
Notice that you are taken to the first attachment

## Expected Result:
Clicking on an attachment opens the clicked attachment

## Actual Result:
Clicking on an attachment opens the first attachment

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] iOS: Native


## Screenshots/Videos


https://github.com/user-attachments/assets/c310f6ba-ed49-4115-86c6-d2c71ef35318




</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-29 19:55 UTC, izarutskaya commented
## Chat - Keyboard is not shown when a Chat is opened or user focuses on text field


If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13.0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4770469
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team


## Action Performed:
1. Launch New Expensify
2. Open any chat from LHN
3. Tap on the text field

Note: this issue specific for Pixel phones (Android 14)

## Expected Result:
Keyboard appears when entering the chat

## Actual Result:
Keyboard only appears after tapping on the emoji icon and then dismissed

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] iOS: Native


## Screenshots/Videos



https://github.com/user-attachments/assets/bd6abbb6-44e5-4f4b-afe9-b67ecf135946


</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-29 20:02 UTC, izarutskaya commented
## Sign In - User not redirected back when tapped on "Go back" link


If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13.0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4770453&group_by=cases:section_id&group_id=229043&group_order=asc
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team


## Action Performed:
1. Open app
2. Write any email which is already registered
3. Tap on Continue button
4. Tap on 'Go back" link

Note: this issue specific only for Pixel phones (Android 14)

## Expected Result:
User should be navigated back on email page

## Actual Result:
Nothing happened. The "Go back" link is inactive"

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] iOS: Native


## Screenshots/Videos


https://github.com/user-attachments/assets/036f9794-49d4-460e-ad2a-f8ef443daf24


</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-30 09:58 UTC, MrRefactor commented
> ## Sign In - User not redirected back when tapped on "Go back" link
> If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
> 
> **Version Number:** 9.0.13.0 **Reproducible in staging?:** N **Reproducible in production?:** N **If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4770453&group_by=cases:section_id&group_id=229043&group_order=asc **Logs:** https://stackoverflow.com/c/expensify/questions/4856 **Issue reported by:** Applause-Internal team
> 
> ## Action Performed:
> 1. Open app
> 2. Write any email which is already registered
> 3. Tap on Continue button
> 4. Tap on 'Go back" link
> 
> Note: this issue specific only for Pixel phones (Android 14)
> 
> ## Expected Result:
> User should be navigated back on email page
> 
> ## Actual Result:
> Nothing happened. The "Go back" link is inactive"
> 
> ## Workaround:
> Unknown
> 
> ## Platforms:
> Which of our officially supported platforms is this issue occurring on?
> 
> * [x]  Android: Native
> * [ ]  iOS: Native
> 
> ## Screenshots/Videos
>  Bug6555704_1722216957400.screen-20240729-043510.mp4 
> [View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

cannot reproduce on dev build

2024-07-30 09:58 UTC, MrRefactor commented
> ## Chat - Keyboard is not shown when a Chat is opened or user focuses on text field
> If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
> 
> **Version Number:** 9.0.13.0 **Reproducible in staging?:** N **Reproducible in production?:** N **If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4770469 **Logs:** https://stackoverflow.com/c/expensify/questions/4856 **Issue reported by:** Applause-Internal team
> 
> ## Action Performed:
> 1. Launch New Expensify
> 2. Open any chat from LHN
> 3. Tap on the text field
> 
> Note: this issue specific for Pixel phones (Android 14)
> 
> ## Expected Result:
> Keyboard appears when entering the chat
> 
> ## Actual Result:
> Keyboard only appears after tapping on the emoji icon and then dismissed
> 
> ## Workaround:
> Unknown
> 
> ## Platforms:
> Which of our officially supported platforms is this issue occurring on?
> 
> * [x]  Android: Native
> * [ ]  iOS: Native
> 
> ## Screenshots/Videos
>  Bug6555609_1722203295179.az_recorder_20240729_004218.mp4 
> [View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

cannot reproduce on dev build

2024-07-30 10:39 UTC, izarutskaya commented
## Taxes - Keyboard flickers when opening the "Name" menu in "Add rate" taxes


If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13.0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4770256
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team


## Action Performed:
1. Open New Expensify Ad-Hoc app
2. Log in under HT account
3. Create a new WS
4. Navigate to the "More features" menu in the WS settings
5. Turn on "Taxes"
6. Navigate to the "Taxes" menu
7. Tap on "Add rare"
8. Tap on the "Name" menu


## Expected Result:
The keyboard should appear without flickering

## Actual Result:
Keyboard flickers when opening the "Name" menu in "Add rate" taxes

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] iOS: Native


## Screenshots/Videos


https://github.com/user-attachments/assets/cc5efc15-a208-44de-b8bd-7d6583bd029b


</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-30 10:44 UTC, izarutskaya commented
## Expense - Incorrect currency is displayed when creating an Expense Request in WS


If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13.0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4770343
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team


## Action Performed:
Precondition:
Workspace currency is different from local currency.
1. Open New Expensify Ad-Hoc app
2. Go to workspace chat.
3. Go to + Menu > Submit expense > Manual
4. Create an Expense Request

The same behaviour is observed in Distance rates -> Settings -> Default category

## Expected Result:
When creating an Expense Request in a WS, the currency selected by default in the WS settings should be displayed

## Actual Result:
Incorrect currency is displayed when creating an Expense Request in WS

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] iOS: Native


## Screenshots/Videos

https://github.com/user-attachments/assets/addc3786-899c-4778-945e-76bbd885e51a


</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-30 10:53 UTC, izarutskaya commented
## Members - Application crashes when scrolling through the "Invite new members" list in WS


If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13.0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4770052
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team


## Action Performed:
1. Open New Expensify Ad-Hoc app
2. Log in under HT account
3. Create a new WS
4. Navigate to the "Members" menu in the WS settings
5. Click on "+Invite member"
6. Scroll down the list of members all the way to the bottom

## Expected Result:
The application should not crash when scrolling through the "Invite new members" list in WS

## Actual Result:
Application crashes when scrolling through the "Invite new members" list in WS

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] iOS: Native


## Screenshots/Videos



https://github.com/user-attachments/assets/6b560562-c1a8-45a3-854f-a8a7c86a4cba

[Bug6556416_1722288629230!logs-2024-07-29_21_29_10.695.txt](https://github.com/user-attachments/files/16426498/Bug6556416_1722288629230.logs-2024-07-29_21_29_10.695.txt)

[Bug6556416_1722288629248!onyx-state.txt](https://github.com/user-attachments/files/16426499/Bug6556416_1722288629248.onyx-state.txt)



</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-07-30 18:59 UTC, MrRefactor commented
hey @izarutskaya could you check if the crash on add members page is also reproducible on this build? https://github.com/Expensify/App/pull/40548#issuecomment-2180481263

2024-07-31 08:48 UTC, perunt commented
> Chat - Emoji suggestion box displayed slightly extra above the compose box.

I'm currently exploring this.
It looks like a different value came from `measureInWindow` on the composer component's root view. I will investigate it further.

2024-07-31 09:24 UTC, MrRefactor commented
> > Chat - Emoji suggestion box displayed slightly extra above the compose box.
> 
> I'm currently exploring this. It looks like a different value came from `measureInWindow` on the composer component's root view. I will investigate it further.

Whats interesting, on 0.75 upgrade its working fine

2024-07-31 09:39 UTC, perunt commented
> Whats interesting, on 0.75 upgrade its working fine

Something has gone wrong with the layout itself. I also encountered some random bugs related to measuring another component. Let me test it in version 75. If it works there, it might make sense to skip it, as it appears to be a bug under the hood, wdyt?

2024-07-31 09:44 UTC, MrRefactor commented
> > Whats interesting, on 0.75 upgrade its working fine
> 
> Something has gone wrong with the layout itself. I also encountered some random bugs related to measuring another component. Let me test it in version 75. If it works there, it might make sense to skip it, as it appears to be a bug under the hood, wdyt?

@mountiny @roryabraham

2024-07-31 09:45 UTC, MrRefactor commented
> ## Members - Application crashes when scrolling through the "Invite new members" list in WS
> If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
> 
> **Version Number:** 9.0.13.0 **Reproducible in staging?:** N **Reproducible in production?:** N **If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4770052 **Logs:** https://stackoverflow.com/c/expensify/questions/4856 **Issue reported by:** Applause-Internal team
> 
> ## Action Performed:
> 1. Open New Expensify Ad-Hoc app
> 2. Log in under HT account
> 3. Create a new WS
> 4. Navigate to the "Members" menu in the WS settings
> 5. Click on "+Invite member"
> 6. Scroll down the list of members all the way to the bottom
> 
> ## Expected Result:
> The application should not crash when scrolling through the "Invite new members" list in WS
> 
> ## Actual Result:
> Application crashes when scrolling through the "Invite new members" list in WS
> 
> ## Workaround:
> Unknown
> 
> ## Platforms:
> Which of our officially supported platforms is this issue occurring on?
> 
> * [ ]  Android: Native
> * [x]  iOS: Native
> 
> ## Screenshots/Videos
>  Bug6556416_1722270424497.RPReplay_Final1722269790.mp4 
> [Bug6556416_1722288629230!logs-2024-07-29_21_29_10.695.txt](https://github.com/user-attachments/files/16426498/Bug6556416_1722288629230.logs-2024-07-29_21_29_10.695.txt)
> 
> [Bug6556416_1722288629248!onyx-state.txt](https://github.com/user-attachments/files/16426499/Bug6556416_1722288629248.onyx-state.txt)
> 
> [View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

fixed

2024-07-31 09:45 UTC, MrRefactor commented
> ## Taxes - Keyboard flickers when opening the "Name" menu in "Add rate" taxes
> If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
> 
> **Version Number:** 9.0.13.0 **Reproducible in staging?:** N **Reproducible in production?:** N **If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4770256 **Logs:** https://stackoverflow.com/c/expensify/questions/4856 **Issue reported by:** Applause-Internal team
> 
> ## Action Performed:
> 1. Open New Expensify Ad-Hoc app
> 2. Log in under HT account
> 3. Create a new WS
> 4. Navigate to the "More features" menu in the WS settings
> 5. Turn on "Taxes"
> 6. Navigate to the "Taxes" menu
> 7. Tap on "Add rare"
> 8. Tap on the "Name" menu
> 
> The same behaviour is observed in Distance rates -> Settings -> Default category
> 
> ## Expected Result:
> The keyboard should appear without flickering
> 
> ## Actual Result:
> Keyboard flickers when opening the "Name" menu in "Add rate" taxes
> 
> ## Workaround:
> Unknown
> 
> ## Platforms:
> Which of our officially supported platforms is this issue occurring on?
> 
> * [ ]  Android: Native
> * [x]  iOS: Native
> 
> ## Screenshots/Videos
>  Bug6556060_1722252168368.RPReplay_Final1722251466.mp4 
> [View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

cant reproduce, to be validated on next build

2024-07-31 10:22 UTC, MrRefactor commented
> ## Expense - Incorrect currency is displayed when creating an Expense Request in WS
> If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email [contributors@expensify.com](mailto:contributors@expensify.com) to request to join our Slack channel!
> 
> **Version Number:** 9.0.13.0 **Reproducible in staging?:** N **Reproducible in production?:** N **If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4770343 **Logs:** https://stackoverflow.com/c/expensify/questions/4856 **Issue reported by:** Applause-Internal team
> 
> ## Action Performed:
> Precondition: Workspace currency is different from local currency.
> 
> 1. Open New Expensify Ad-Hoc app
> 2. Go to workspace chat.
> 3. Go to + Menu > Submit expense > Manual
> 4. Create an Expense Request
> 
> ## Expected Result:
> When creating an Expense Request in a WS, the currency selected by default in the WS settings should be displayed
> 
> ## Actual Result:
> Incorrect currency is displayed when creating an Expense Request in WS
> 
> ## Workaround:
> Unknown
> 
> ## Platforms:
> Which of our officially supported platforms is this issue occurring on?
> 
> * [ ]  Android: Native
> * [x]  iOS: Native
> 
> ## Screenshots/Videos
>  Bug6556380_1722268373917.RPReplay_Final1722267297.mp4 
> [View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

cannot reproduce after merging latest main

2024-08-01 06:02 UTC, MrRefactor commented
> > Whats interesting, on 0.75 upgrade its working fine
> 
> Something has gone wrong with the layout itself. I also encountered some random bugs related to measuring another component. Let me test it in version 75. If it works there, it might make sense to skip it, as it appears to be a bug under the hood, wdyt?

after talking with @roryabraham,  the suggestion list bug may be treated as a blocker so we would like to fix it before merging

2024-08-05 09:05 UTC, kubabutkiewicz commented
Hi @perunt, I was investigating this issue with Suggestions box and here is my finding 
in file `node_modules/react-native/ReactCommon/react/renderer/core/LayoutableShadowNode.cpp`
we have this line 
```
    if (!shouldCalculateTransformedFrames && i != 0 &&
        policy.includeTransform) {
      resultFrame.origin += currentShadowNode->getContentOriginOffset() * currentShadowNode->getTransform();
    }
   ```
and when you will remove `* currentShadowNode->getTransform()` the suggestions box will appear right above Composer so that means `getTransform` method is calculating wrong translate. Hope that will help

2024-08-05 12:24 UTC, staszekscp commented
Hello @MrRefactor! I've noticed that you've removed the following patches:

[patches/expo+50.0.4.patch](https://github.com/Expensify/App/pull/40548/files#diff-7fde50669d6d0e8c383803f3e2ed872bd3e69f32f76302324d08bc323996fc4d)
[patches/expo-av+13.10.4.patch](https://github.com/Expensify/App/pull/40548/files#diff-d1042e6c6e6c126558d0770f54ce54acec21e658a0155996510c87c3a83227a1)
[patches/expo-modules-autolinking+1.10.2.patch](https://github.com/Expensify/App/pull/40548/files#diff-a9d55a096766d6027bb31f80f6f07b7995b54bc9360d45248a1e795e979532c2)
[patches/expo-modules-core+1.11.8+001+initial.patch](https://github.com/Expensify/App/pull/40548/files#diff-ce4f292fce243eb8e615cf69ba59ceec4cb095a9dc7dc7dd0df3a96cc56416b5)

These patches are necessary for the HybridApp to work, and without testing they shouldn't be removed. Was there a special reason why you've decided to delete them? 😄 

Since HybridApp is being rolled out at this moment, I think that when the PR is ready we should test if everything compiles correctly :) cc: @AndrewGable

2024-08-05 12:26 UTC, MrRefactor commented
> Hello @MrRefactor! I've noticed that you've removed the following patches:
> 
> [patches/expo+50.0.4.patch](https://github.com/Expensify/App/pull/40548/files#diff-7fde50669d6d0e8c383803f3e2ed872bd3e69f32f76302324d08bc323996fc4d) [patches/expo-av+13.10.4.patch](https://github.com/Expensify/App/pull/40548/files#diff-d1042e6c6e6c126558d0770f54ce54acec21e658a0155996510c87c3a83227a1) [patches/expo-modules-autolinking+1.10.2.patch](https://github.com/Expensify/App/pull/40548/files#diff-a9d55a096766d6027bb31f80f6f07b7995b54bc9360d45248a1e795e979532c2) [patches/expo-modules-core+1.11.8+001+initial.patch](https://github.com/Expensify/App/pull/40548/files#diff-ce4f292fce243eb8e615cf69ba59ceec4cb095a9dc7dc7dd0df3a96cc56416b5)
> 
> These patches are necessary for the HybridApp to work, and without testing they shouldn't be removed. Was there a special reason why you've decided to delete them? 😄
> 
> Since HybridApp is being rolled out at this moment, I think that when the PR is ready we should test if everything compiles correctly :) cc: @AndrewGable

Let me doublecheck on that, and I will bring those back

2024-08-05 13:42 UTC, MrRefactor commented
@staszekscp I have updated all of the expo patches you mentioned, please take a look if everything seems fine

2024-08-05 13:46 UTC, staszekscp commented
Thanks @MrRefactor! Is the app buildable from this PR at the moment? If so, tomorrow I will try to build HybridApp from this PR

2024-08-05 13:51 UTC, MrRefactor commented
> Thanks @MrRefactor! Is the app buildable from this PR at the moment? If so, tomorrow I will try to build HybridApp from this PR

Yes, it is

2024-08-06 18:10 UTC, perunt commented
Can you try this workaround? It should work. It is not the ideal solution, but it will be removed in RN75. https://github.com/MrRefactor/App/pull/1

2024-08-07 06:34 UTC, staszekscp commented
So, I've managed to have a go, and tried to build the HybridApp from this PR - there are some build errors, though. 😢 However _I think_ they shouldn't be very difficult to resolve. A couple of patches and tweaks in `build.gradle`/`Podfile` should do the trick. 😄 

It may take me like a day or two to resolve everything, but I won't be able to jump in at this moment. That's why I don't want the HybridApp to be a blocker of this PR. However, when it gets merged HybridApp may be broken for some time cc: @AndrewGable

2024-08-07 06:54 UTC, MrRefactor commented
> So, I've managed to have a go, and tried to build the HybridApp from this PR - there are some build errors, though. 😢 However _I think_ they shouldn't be very difficult to resolve. A couple of patches and tweaks in `build.gradle`/`Podfile` should do the trick. 😄
> 
> It may take me like a day or two to resolve everything, but I won't be able to jump in at this moment. That's why I don't want the HybridApp to be a blocker of this PR. However, when it gets merged HybridApp may be broken for some time
> 
> cc: @AndrewGable

Thanks for checking that @staszekscp , after talking to @AndrewGable on Monday I was told that next HybridApp release is planned around 8/14, so we cannot merge PR until the release. Please let me know when you will be able to work on adjusting `build.gradle/Podfile`

2024-08-19 09:26 UTC, perunt commented
@MrRefactor, how is it going here? Do we have any plans/estimates for this?

2024-08-19 09:28 UTC, chrispader commented
> > So, I've managed to have a go, and tried to build the HybridApp from this PR - there are some build errors, though. 😢 However _I think_ they shouldn't be very difficult to resolve. A couple of patches and tweaks in `build.gradle`/`Podfile` should do the trick. 😄
> > It may take me like a day or two to resolve everything, but I won't be able to jump in at this moment. That's why I don't want the HybridApp to be a blocker of this PR. However, when it gets merged HybridApp may be broken for some time
> > cc: @AndrewGable
> 
> ... I was told that next HybridApp release is planned around 8/14, so we cannot merge PR until the release.

Was there a new HybridApp release and can we continue working on this PR? It would be awesome if we could push this PR through, since there are some other major PRs that are on HOLD for this:

https://github.com/Expensify/App/pull/37891
https://github.com/Expensify/App/pull/42143

2024-08-20 16:44 UTC, roryabraham commented
Closing this in favor of the 0.75 upgrade

2024-08-20 16:44 UTC, closed without merging

2024-08-25 21:11 UTC, IuliiaHerets commented
## Tasks - App crashes when assigning someone to a task without assignees

**Version Number:** 9.0.17-1
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4843131
**Email or phone of affected tester (no customers):** gatantm+86@gmail.com
**Issue reported by:** Applause Internal Team


## Action Performed:
1. Launch new Expensify
2. Navigate to any chat with a task not yet assigned (or create one)
3. Tap on the chat > assign > select any assignee

## Expected Result:
The selected assignee is added without issues

## Actual Result:
The app crashes. An already assigned task can change assignees without issues. Issue is reproducible only on tasks without any assignees

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos


https://github.com/user-attachments/assets/2636bd84-1526-48f0-90e9-28d33bb72cd2



</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2024-08-26 06:42 UTC, MrRefactor commented
hey @IuliiaHerets this PR is closed, and shouldnt be tested anymore, did that issue occur on builds from 0.75 upgrade as well?