Fix padding for edit composer suggestions
Expensify/App pull request #41071
Opened 2024-04-26 09:20 UTC by dukenv0307

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/34442
https://github.com/Expensify/App/issues/40861
https://github.com/Expensify/App/issues/40864
https://github.com/Expensify/App/issues/40856
https://github.com/Expensify/App/issues/40854
PROPOSAL: https://github.com/Expensify/App/issues/34442#issuecomment-1891334360

### Tests

1. Open any report
2. Send some messages
3. Edit a message
4. Type `@` and verify that the mention suggestion list appears with spacing between composer is `8px`
5. Type `:sm` and verify that the emoji suggestion list appears with spacing between composer is `8px`
- [x] Verify that no errors appear in the JS console

### Offline tests

Same as above
### QA Steps

1. Open any report
2. Send some messages
3. Edit a message
4. Type `@` and verify that the mention suggestion list appears with spacing between composer is `8px`
5. Type `:sm` and verify that the emoji suggestion list appears with spacing between composer is `8px`
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/9611dfba-cddf-4235-a88d-f6bc9b41a7e9

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/9a99e137-4448-4d27-8173-72b018fd0487

</details>

<details>
<summary>iOS: Native [...]

2024-05-22 11:43 UTC, eVoloshchak requested changes

2024-05-22 11:43 UTC, eVoloshchak commented on src/styles/utils/getAutoCompleteSuggestionContainerStyle/index.ts
Why are styles different for web and native? 
The only part that differs is `top` style, but shouldn't it be the same on both platforms to look the same?

2024-05-22 11:43 UTC, eVoloshchak commented on src/styles/utils/getAutoCompleteSuggestionContainerStyle/index.ts
If this is necessary, we can still de-duplicate this a bit. The only style that is different is `top`, so all of the other logic can be moved to a single file

2024-05-22 11:43 UTC, eVoloshchak commented on src/styles/utils/getAutoCompleteSuggestionContainerStyle/index.native.ts
The folder should be called `getAutoCompleteSuggestionContainerStyles` to be consistent with the rest

2024-05-22 11:43 UTC, eVoloshchak commented on src/pages/home/report/ReportActionItemMessageEdit.tsx
> +            // Reopen the suggestion after scroll has end
```suggestion
            // Reopen the suggestion after scroll has ended
```

2024-05-22 11:43 UTC, eVoloshchak commented on src/libs/SuggestionUtils.ts
> +const measureHeightOfSuggestionsContainer = (numRows: number, isSuggestionsPickerLarge: boolean): number => {
```suggestion
const measureSuggestionsContainerHeight = (numRows: number, isSuggestionsPickerLarge: boolean): number => {
```

2024-05-22 11:43 UTC, eVoloshchak commented on src/CONST.ts
> +        EDIT_SUGGESTER_PADDING: 8,
This should be in `styles/variables`

2024-05-22 11:43 UTC, eVoloshchak commented on src/styles/utils/getAutoCompleteSuggestionContainerStyle/index.ts
> +    const borderWidth = 2;
We could also move this to `styles/variables`, which would allow us to use it in `src/libs/SuggestionUtils.ts` instead of a hardcoded number

2024-05-22 11:43 UTC, eVoloshchak commented on src/styles/utils/getAutoCompleteSuggestionContainerStyle/index.ts
> +    const height = itemsHeight + 2 * CONST.AUTO_COMPLETE_SUGGESTER.SUGGESTER_INNER_PADDING + (shouldPreventScroll ? borderWidth : 0);
What is `+2` in this case? Is it `borderWidth`?

2024-05-22 11:43 UTC, eVoloshchak commented on src/pages/home/report/ReportActionCompose/ComposerWithSuggestionsEdit/ComposerWithSuggestionsEdit.tsx
> +                maxLines={maxLines} // This is the same that slack has
```suggestion
                maxLines={maxLines}
```

2024-05-22 11:43 UTC, eVoloshchak commented on src/pages/home/report/ReportActionCompose/ComposerWithSuggestionsEdit/ComposerWithSuggestionsEdit.tsx
> +                onChangeText={onChangeText} // Debounced saveDraftComment
```suggestion
                onChangeText={onChangeText}
```

2024-05-22 11:43 UTC, eVoloshchak commented on src/pages/home/report/ReportActionCompose/ComposerWithSuggestionsEdit/ComposerWithSuggestionsEdit.tsx
> +                // Input
```suggestion
```

2024-05-22 11:43 UTC, eVoloshchak commented on src/pages/home/report/ReportActionCompose/ComposerWithSuggestionsEdit/ComposerWithSuggestionsEdit.tsx
> +    selection: Selection;
`ComposerProps` type already has `value`, `selection` and `isGroupPolicyReport` properties

2024-05-24 08:45 UTC, eVoloshchak requested changes

2024-05-24 08:45 UTC, eVoloshchak commented on src/pages/home/report/ReportActionItem.tsx
> +                            // Avoid defining within component due to an existing Onyx bug
Could you please expand on what the bug is?

2024-05-24 08:45 UTC, eVoloshchak commented on src/styles/utils/getAutoCompleteSuggestionContainerStyle/index.ts
@dukenv0307, thanks 
Then we can still de-duplicate this as I've described in https://github.com/Expensify/App/pull/41071/files/a92552d7d9c53933a95f4a458d4aab931f23f6e8#r1609783905

In addition to that, we can define `borderWidth` in `CONST.AUTO_COMPLETE_SUGGESTER..`, and use it here and in `src/libs/SuggestionUtils`

2024-05-29 20:33 UTC, eVoloshchak requested changes

2024-05-29 20:33 UTC, eVoloshchak commented on src/libs/SuggestionUtils.ts
> +    const borderAndPadding = CONST.AUTO_COMPLETE_SUGGESTER.SUGGESTER_INNER_PADDING + 2;
```suggestion
    const borderAndPadding = CONST.AUTO_COMPLETE_SUGGESTER.SUGGESTER_INNER_PADDING + CONST.AUTO_COMPLETE_SUGGESTER.BORDER_WIDTH;
```

2024-05-29 20:33 UTC, eVoloshchak commented on src/pages/home/report/ReportActionCompose/ComposerWithSuggestionsEdit/ComposerWithSuggestionsEdit.tsx
> +        maxLines = -1,
Are we supposed to use `-1` here?

2024-05-29 20:33 UTC, eVoloshchak commented on src/styles/utils/getAutoCompleteSuggestionContainerPosition/index.ts
> +        top: -(height + (shouldBeDisplayedBelowParentContainer ? -2 : 1) * (suggestionsPadding + (shouldPreventScroll ? 0 : borderWidth))),
```suggestion
        top: -(height + (shouldBeDisplayedBelowParentContainer ? -CONST.AUTO_COMPLETE_SUGGESTER.BORDER_WIDTH : 1) * (suggestionsPadding + (shouldPreventScroll ? 0 : borderWidth))),
```

2024-06-11 12:35 UTC, eVoloshchak reviewed
On iOS, the following error pops up when suggestions or emoji list is opened (I suspect this might be resolved by merging main)


https://github.com/Expensify/App/assets/9059945/257b5d07-3590-4ac7-886d-e3abc3a82723

2024-06-18 15:16 UTC, eVoloshchak commented
@dukenv0307, I'm still encountering the same [error](https://github.com/Expensify/App/pull/41071#pullrequestreview-2110331763)
 

https://github.com/Expensify/App/assets/9059945/5b666fbb-8836-4907-aadd-eab68a61bd85

Verified this doesn't exist on `main`. Could you double-check if this is working for you on iOS?

2024-06-25 20:31 UTC, eVoloshchak reviewed
Suggestions and emoji list are displayed on top of the composer, this doesn't look right, can we remove it to the top?
![Simulator Screenshot - iPhone 15 Pro - 2024-06-25 at 22 24 58](https://github.com/Expensify/App/assets/9059945/402636ba-680a-4552-bb71-3f7e87331e04)
![Simulator Screenshot - iPhone 15 Pro - 2024-06-25 at 22 24 27](https://github.com/Expensify/App/assets/9059945/4123448b-f172-441e-ae97-c72be6af943e)

It looks correctly on mWeb

![Simulator Screenshot - iPhone 15 Pro - 2024-06-25 at 22 26 50](https://github.com/Expensify/App/assets/9059945/1f9f8b36-a2ba-421c-bc94-5aa819572da9)

2024-06-25 20:46 UTC, shawnborton commented
We recently changed the top/bottom padding of our popovers to be 16px instead of 12px, so I wonder if we need to update the offset by 8px to correct that.

2024-06-26 14:33 UTC, dannymcclain commented
>We recently changed the top/bottom padding of our popovers to be 16px instead of 12px, so I wonder if we need to update the offset by 8px to correct that.

Oh good call Shawn, I bet that's why we're getting this little overlap with the composer.

2024-07-08 10:21 UTC, eVoloshchak reviewed
@dukenv0307, it is reproducible on Web and mWeb


https://github.com/Expensify/App/assets/9059945/9bd87acb-d257-4271-baf4-1526e502b76b

It's also reproducible for the regular composer (not the edit one) on staging, we don't need to fix that in this PR, but I suspect it will be fixed for both with [a single fix](https://github.com/Expensify/App/pull/41071#issuecomment-2189938469) (@dukenv0307, could you please check if this does the trick?)

2024-07-24 06:27 UTC, eVoloshchak reviewed
> So we want to add a space between the suggestion and the composer, right?

@dukenv0307, yes, it should have the same padding as the emoji modal for default composer

<img width="1128" alt="Screenshot 2024-07-24 at 08 24 03" src="https://github.com/user-attachments/assets/e7ac61f6-764f-4b62-815f-91b78cc1c6e8">

Currently, it overlaps with the edit composer

<img width="1128" alt="Screenshot 2024-07-24 at 08 24 32" src="https://github.com/user-attachments/assets/82394300-efb7-4b46-bb6c-2a16c4d707f8">

2024-07-31 19:45 UTC, eVoloshchak reviewed
Looking good now! (noting the same problem exists for the emoji modal, but that exists on staging and unrelated to this PR)

@dukenv0307, I'm a bit late, apologies for that, could you resolve the conflicts and I'll give this the last round of testing?

2024-08-05 09:41 UTC, eVoloshchak commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->

</details>

<detail [...]

2024-08-05 10:07 UTC, eVoloshchak commented
@dukenv0307, when testing this I noticed that emoji suggestions have already been implemented for the edit composer

https://github.com/user-attachments/assets/3dd6f3e9-6c0a-4380-8943-3c706d2efc52

Am I missing something? Looks like the previous PR was reverted, was this added by another PR?

2024-08-05 13:08 UTC, eVoloshchak commented
> It was added here,

Could you point me to a PR that added this? https://github.com/Expensify/App/pull/35226 was reverted by https://github.com/Expensify/App/pull/40865

2024-08-16 13:31 UTC, shawnborton commented
What's the latest on this one? Looks like progress slowed down.

2024-08-16 13:55 UTC, eVoloshchak commented
@shawnborton, this feature was added by another PR (https://github.com/Expensify/App/pull/44720) already

The only thing that's left is a small UI issue (https://github.com/Expensify/App/pull/41071#pullrequestreview-2195746266), I think we can implement it here
@dukenv0307, could you update the PR please? The only change that is needed is a fix for https://github.com/Expensify/App/pull/41071#pullrequestreview-2195746266

2024-08-21 19:30 UTC, eVoloshchak commented
@dukenv0307, we don't need any other changes besides different padding (fix for https://github.com/Expensify/App/pull/41071#pullrequestreview-2195746266). Treat this like a new PR (or go ahead and create a new PR, your choice)

2024-08-27 13:02 UTC, eVoloshchak reviewed
- **Bug 1**

suggestions list doesn't open when typing "@", emoji suggestions list doesn't open when starting to type an emoji name (this doesn't happen 100% of the times, but pretty consistently)


https://github.com/user-attachments/assets/c3acfbfa-4ba7-4d39-a403-0ff13f6b4d4e

- **Bug 2 (Android)**

Both lists overlap with the keyboard/UI (padding calculation is not correct)

<img width="335" alt="Screenshot 2024-08-27 at 14 59 58" src="https://github.com/user-attachments/assets/71b78644-f3bd-4590-87eb-6e3ffe3e8d5c">

https://github.com/user-attachments/assets/23924b9b-eb74-428d-9197-94fa0d49d6a9

- In addition to that, could you please update the testing steps, retest this on all of the platforms and update the Screenshots/Videos section please?

2024-09-04 15:03 UTC, eVoloshchak commented
> Is this bug reproducible on the latest main

Confirmed this is reproducible on staging

> I can't reproduce this bug.

I can reliably reproduce it on native Android


https://github.com/user-attachments/assets/af8170d5-1f6a-4c94-95e6-61bd96d043f4

2024-09-12 11:01 UTC, eVoloshchak commented
Turns out this is working correctly on a physical device, must be a problem with an emulator
@dukenv0307, could you pull the latest main please?

2024-09-15 08:25 UTC, eVoloshchak reviewed
Still doesn't look right on mWeb Safari. This isn't a simulator issue, current staging works fine in a simulator

https://github.com/user-attachments/assets/932e0d3f-14e3-4adf-9469-57699b8a8f6e

2024-10-07 11:49 UTC, eVoloshchak approved these changes
LGTM!

2024-10-07 21:48 UTC, stitesExpensify approved these changes

2024-10-07 21:49 UTC, merged

2024-10-08 08:32 UTC, IuliiaHerets commented
This PR is failing for Android app because of issue #50377