[No QA] Add Performance issue template
Expensify/App pull request #4128
Opened 2021-07-17 00:26 UTC by marcaaron

### Details

- Adding a Performance issue template here to make it easier for contributors to report performance improvements.
- The only existing option is to use the standard issue template and it doesn't capture the information we need to evaluate these types of conversations and issues.

### Fixed Issues
None

### Tests
### QA Steps
None

2021-07-19 16:15 UTC, tgolen requested changes

2021-07-19 16:15 UTC, tgolen commented on .github/ISSUE_TEMPLATE/Performance.md
> + Mobile Web
Maybe make these checkboxes for ease of use.

2021-07-19 16:15 UTC, tgolen commented on .github/ISSUE_TEMPLATE/Performance.md
> +## Is there a specific app feature that will be improved by solving this problem?
To go along with this, what do you think about adding a question like:

> What is the impact of this on end-users?

2021-07-19 18:34 UTC, marcaaron commented
Added checklists and incorporated that suggestion, thanks! I think it's a bit clearer now.

2021-07-20 20:39 UTC, tgolen approved these changes

2021-07-20 20:39 UTC, merged

2021-07-20 20:40 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-07-23 21:35 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1060992044) to staging         in version: 1.0.79-5🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-07-28 21:08 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1076320151) to production         in version: 1.0.80-2🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅