Fixes styling for hidden element
Expensify/App pull request #4158
Opened 2021-07-21 00:54 UTC by rdjuric

### Details

1. Changes the styling of our `hiddenElementOutsideOfWindow` to be cross-platform. 
2. Takes our hidden `Text` out of the `View` that wraps `TextInputAutoWidth` so that our `position: absolute` is in relation to the parent component.

### Fixed Issues

$ https://github.com/Expensify/App/issues/3296
$ https://github.com/Expensify/App/issues/3355

### Tests

### QA Steps

1. Open the app on an iPad Pro in Landscape mode
2. Start the IOU flow (request money or split bill)
3. You should be able to type an amount

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [x] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

https://user-images.githubusercontent.com/53711423/126413515-a9680051-85ab-491c-8c94-c3a45217a727.mp4

#### Android

2021-07-21 15:14 UTC, luacmartins requested changes
Code LGTM. Can we add screenshots/videos for all platforms to make sure there is no regression?

2021-07-22 15:30 UTC, rdjuric commented
Updated the PR with videos for all platforms @luacmartins

2021-07-22 16:40 UTC, luacmartins approved these changes

2021-07-22 16:40 UTC, merged

2021-07-22 16:42 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-07-23 21:34 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1060992044) to staging         in version: 1.0.79-5🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-07-28 21:08 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1076320151) to production         in version: 1.0.80-2🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅