Xero export bank account new
Expensify/App pull request #41916
Opened 2024-05-09 13:59 UTC by mananjadhav

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/39745
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-05-09 14:38 UTC, lakchote commented
@pecanoro could we please have the spanish translation for this:

```
xeroBankAccountDescription: 'Select the bank account expenses will be posted to as bank transactions.',
```

Link to the line in the PR: https://github.com/Expensify/App/pull/41916/files#diff-472528060691374654a2e2e866547d385eec3849efddca38cbfca1e5b3ba47d5R2079

2024-05-09 15:27 UTC, mananjadhav commented
@ishpaul777 You'll need to enable the `Accounting` and `Xero` beta for this. You can check the steps [here](https://github.com/Expensify/App/pull/40277#issue-2245622576).

2024-05-09 20:25 UTC, pecanoro requested changes

2024-05-09 20:25 UTC, pecanoro commented on src/languages/es.ts
> +            xeroBankAccountDescription: 'Select the bank account expenses will be posted to as bank transactions.',
```suggestion
            xeroBankAccountDescription: 'Selecciona la cuenta bancaria en la que se aparecerán los gastos como transacciones bancarias.',
```

2024-05-10 10:24 UTC, mananjadhav commented
@ishpaul777 Did you get the access working? Need to move this faster along.

2024-05-10 10:27 UTC, mananjadhav commented on src/languages/es.ts
> +            xeroBankAccountDescription: 'Select the bank account expenses will be posted to as bank transactions.',
I'll update this in an hour.

2024-05-10 10:47 UTC, mananjadhav commented
@pecanoro The Spanish translation is updated (screenshot added to the PR body as well).

<img width="1512" alt="web-xero-bank-account-select-es" src="https://github.com/Expensify/App/assets/3069065/9e9bf60f-30a7-44bb-9ca5-ee8c69631d36">

2024-05-10 10:48 UTC, mananjadhav commented on src/languages/es.ts
> +            xeroBankAccountDescription: 'Select the bank account expenses will be posted to as bank transactions.',
Done.

2024-05-10 10:53 UTC, mananjadhav commented
Asking @hungvu193 to review as per [this](https://expensify.slack.com/archives/C036QM0SLJK/p1715338321218469?thread_ts=1715336564.073279&cid=C036QM0SLJK). Need this for the Xero adhoc build.

2024-05-10 10:55 UTC, mananjadhav commented
> Hey @mananjadhav, Sorry for delay, I was not able to priortize yesterday, will try the steps now let you know if i am able to setup in few minutes 🙇

Thanks for responding. Just asked @hungvu193. They already have the setup as well as the context.

2024-05-10 11:32 UTC, mananjadhav commented
No. Means a Xero account with Bank names.

2024-05-10 11:52 UTC, mananjadhav commented on src/pages/workspace/accounting/xero/export/XeroBankAccountSelectPage.tsx
> +    );
@lakchote Can confirm this. We didn't add it in other screens so I've kept it as is.

2024-05-10 14:50 UTC, hungvu193 requested changes
Looking good. Only 2 small comments 👍

2024-05-10 14:50 UTC, hungvu193 commented on src/pages/workspace/accounting/xero/export/XeroBankAccountSelectPage.tsx
> +    const updateMode = useCallback(
We probably need a more understandable function name 😄 
```suggestion
    const updateBankAccount = useCallback(
```

2024-05-10 14:50 UTC, hungvu193 commented on src/pages/workspace/accounting/xero/export/XeroBankAccountSelectPage.tsx
> +            Navigation.goBack(ROUTES.POLICY_ACCOUNTING_XERO_ADVANCED.getRoute(policyID));
```suggestion
            Navigation.goBack(ROUTES.POLICY_ACCOUNTING_XERO_EXPORT.getRoute(policyID));
```

2024-05-10 18:30 UTC, mananjadhav commented
Thanks for the important redirect bug. I had my commits messed up, could've easily missed this one.

2024-05-11 01:38 UTC, hungvu193 approved these changes
LGTM 😄

2024-05-11 06:59 UTC, mananjadhav commented
@hungvu193 @ishpaul777 Can one of you please complete the checklist for this one?

2024-05-11 08:37 UTC, ishpaul777 approved these changes

2024-05-12 14:31 UTC, pecanoro approved these changes

2024-05-13 07:55 UTC, lakchote commented
@mananjadhav there are conflicts that need to be solved

2024-05-13 09:31 UTC, lakchote approved these changes

2024-05-13 09:41 UTC, mananjadhav commented
Running prettier diff.

2024-05-13 09:43 UTC, mananjadhav commented
Fixed lint issues. All checks should pass now.

2024-05-13 10:01 UTC, merged

2024-05-23 00:00 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/9199894178) to production by https://github.com/chiragsalian in version: 1.4.74-6 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅