Feat/dupe detection confirmation
Expensify/App pull request #42571
Opened 2024-05-24 07:20 UTC by kubabutkiewicz

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/39810

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-07-05 19:07 UTC, JmillsExpensify commented
@kubabutkiewicz when you're back on Monday, please make this PR your top focus. We're aiming to get this final PR for dupe detection merged by early next week!

2024-07-08 16:38 UTC, pecanoro requested changes

2024-07-08 16:38 UTC, pecanoro commented on src/languages/es.ts
> +        hold: 'Bloqueada',
```suggestion
        confirmDetails: 'Confirma los detalles que conserva',
        confirmDuplicatesInfo: 'Los duplicados que no conserve se guardarán para que el usuario los elimine',
        hold: 'Bloqueado',
```

2024-07-08 16:59 UTC, parasharrajat requested changes

2024-07-09 06:05 UTC, kubabutkiewicz commented on src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
> +                    }}
@pecanoro I remember that we were talking about that on the slack, can we add it to doc?

2024-07-09 07:54 UTC, kubabutkiewicz commented on src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
> +                    }}
here: https://callstack-hq.slack.com/archives/C036QM0SLJK/p1715717883275529?thread_ts=1712851453.066999&cid=C036QM0SLJK

2024-07-09 07:54 UTC, kubabutkiewicz commented on src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
> +                    }}
here: https://callstack-hq.slack.com/archives/C036QM0SLJK/p1715717883275529?thread_ts=1712851453.066999&cid=C036QM0SLJK

2024-07-09 08:13 UTC, kubabutkiewicz commented on src/libs/actions/IOU.ts
> +    failureData.push(failureTransactionData, ...failureTransactionDuplicatesData, ...failureTransactionViolations);
this was the original solution but its produces TS error

2024-07-09 14:40 UTC, pecanoro commented on src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx
> +                    }}
Yeah, sounds good

2024-07-09 14:44 UTC, parasharrajat requested changes

2024-07-10 12:31 UTC, kubabutkiewicz commented
@parasharrajat this is ready to be check again

2024-07-15 18:05 UTC, pecanoro commented
Is it ready for another review?

2024-07-17 16:30 UTC, JmillsExpensify commented
What account are you using?

2024-07-17 16:41 UTC, JmillsExpensify commented
Please reach out to me in Slack so that we can resolve your issue live. I'm hopeful that we can get this merged today. We only have one more day to get this in the deploy cycle ahead of our deadline.

2024-07-17 16:44 UTC, pecanoro commented
> I am seeing Restricted add payment method page while making new requests. I currently have active free trial. Is there a way to bypass this? @pecanoro

Do you see the same in oldDot? The error message there might be clearer to see if there is an owed account or something

2024-07-17 16:44 UTC, pecanoro commented
Also if you let me know the account, I can check the free trial date on my end and update it

2024-07-17 16:45 UTC, pecanoro commented
I am also going to test the PR in the meantime

2024-07-17 17:24 UTC, pecanoro commented
While testing, I noticed we still have the arrows/carrots on the confirmation page. Since they cannot be modified, we should remove them.

![image](https://github.com/user-attachments/assets/0fd5d122-ba08-449b-b7d6-a6ef2787381f)

2024-07-17 18:04 UTC, pecanoro commented
> While I agree, mock up does have arrows.

Ah yes, we were talking about it, I think originally we thought about being able to modify each field separately but I don't think we have time for that right now so we can handle that later as polish if we decide to add that functionality.

2024-07-17 18:31 UTC, pecanoro commented
@JmillsExpensify noticed it is possible to add reactions to this screen. Can we remove that?

https://files.slack.com/files-pri/T047TPA624F-F07CZ355YNQ/cleanshot_2024-07-17_at_12.25.21_2x.png

2024-07-17 18:32 UTC, pecanoro commented
Forget my previous comment, we can do that in a follow-up PR

2024-07-17 19:05 UTC, pecanoro commented
> I reproduced this issue https://github.com/Expensify/App/pull/42571#issuecomment-2233853607 a few times now. @pecanoro Should this be fixed before we merge this PR?

Ah yes, that seems like an important one to fix

2024-07-17 19:26 UTC, kubabutkiewicz commented
Yes, I will check it first thing in the morning

2024-07-17 19:27 UTC, kubabutkiewicz commented
Also about arrows, I left them because it was like that in the design doc last time I check, should I remove them from a confirm page?

2024-07-17 21:04 UTC, kubabutkiewicz commented
Just fyi I noticed that there is a problem with calculating tax amount but its also happening on main.
<img width="378" alt="image" src="https://github.com/user-attachments/assets/73dc1cf7-4bc4-441a-b71d-bffd702da705">

2024-07-17 21:10 UTC, kubabutkiewicz commented
@parasharrajat Are you able to send to me a receipt which you used, when the bug with not found page occurred?

2024-07-17 21:47 UTC, JmillsExpensify commented
@kubabutkiewicz no need to remove the arrows, since as you note, they are in the design doc.

2024-07-18 08:45 UTC, kubabutkiewicz commented
Hey @parasharrajat, I pushed a fix for this redirect to not found page

2024-07-18 16:32 UTC, JmillsExpensify commented
@parasharrajat @pecanoro Can you make reviewing this issue a priority today? We need to find a path for getting this merged in order to make our deadline.

2024-07-18 16:54 UTC, pecanoro commented
Yes, I am doing another test run right now!

2024-07-18 19:34 UTC, pecanoro commented
@parasharrajat How is it going?

2024-07-18 20:29 UTC, pecanoro commented
The only bug I found is that after resolving/merging the duplicates, the report doesn't have the right total, it just shows as $0:

![image](https://github.com/user-attachments/assets/ee7a97f5-0778-4290-9ece-0805ed995f8d)

2024-07-18 21:01 UTC, kubabutkiewicz commented
@pecanoro this seems to be a backend issue, I check the response for `OpenReport` command after resolving duplicates and there is something like that 
<img width="530" alt="image" src="https://github.com/user-attachments/assets/d243c4c8-5d87-4322-8dcc-bc8b2ca2b282">

2024-07-18 21:10 UTC, pecanoro commented
Oh wow, that is super odd indeed, I will create an issue to fix it internally then, thank you for looking into it! Waiting on @parasharrajat then to finish the whole review

2024-07-18 21:27 UTC, kubabutkiewicz commented
@pecanoro I recheck what is sent to backend from frontend and I noticed that when there is no receipt amount in paramters for `MergeTransactions` is sent as 0 and that cause a problem pushing a fix for that

2024-07-18 21:33 UTC, JmillsExpensify commented
Thanks for the quick work and responsiveness!

2024-07-19 00:31 UTC, pecanoro commented
@parasharrajat Please prioritize the PR when you get online next! 🙏

2024-07-19 00:41 UTC, pecanoro approved these changes, later dismissed
The comments that I left are pretty minor and can be addressed at some other PR

2024-07-19 00:41 UTC, pecanoro commented on src/languages/es.ts
> +        confirmDuplicatesInfo: 'Los duplicados que no conserve se guardarán para que el usuario los elimine',
```suggestion
        confirmDetails: 'Confirma los detalles que conservas',
        confirmDuplicatesInfo: 'Los duplicados que no conserves se guardarán para que el usuario los elimine',
```

2024-07-19 00:41 UTC, pecanoro commented on src/ROUTES.ts
> +
I don't want to block on this, but once we do any other polish issues, we should remove this extra line

```suggestion
```

2024-07-19 00:41 UTC, pecanoro commented on src/libs/actions/IOU.ts
> +function mergeDuplicates(params: TransactionMergeParams) {
```suggestion
/** Merge several transactions into one by updating the fields of the one we want to keep and deleting the rest */
function mergeDuplicates(params: TransactionMergeParams) {
```

2024-07-19 00:41 UTC, pecanoro commented on src/libs/actions/IOU.ts
> +
```suggestion
```

2024-07-19 00:41 UTC, pecanoro commented on src/libs/actions/IOU.ts
> +
```suggestion
```

2024-07-19 00:41 UTC, pecanoro commented on src/pages/TransactionDuplicate/ReviewBillable.tsx
> +            <ReviewFields<'billable'>
Nothing to address, today I just learned that you can do this for the name of the component 😄

2024-07-19 00:41 UTC, pecanoro commented on src/pages/TransactionDuplicate/ReviewTaxCode.tsx
> +    const onSelectRow = useCallback(
This should say what it does not what it handles, but just ignore it for now since it's too many changes 😄

2024-07-19 00:43 UTC, pecanoro commented
@kubabutkiewicz If you get online and this PR is not merged, feel free to commit my suggestions. If it's merged, no worries; we can handle them in some other Polish PR since we need to fix some minor stuff.

2024-07-19 02:42 UTC, JmillsExpensify commented
@parasharrajat Just confirming that you are still reviewing/testing this PR?

2024-07-19 08:00 UTC, kubabutkiewicz commented
@pecanoro I applied your suggestions

2024-07-19 10:16 UTC, kubabutkiewicz commented
Trying to reproduce that but no luck yet

2024-07-19 10:29 UTC, kubabutkiewicz commented
Checking it... but this seems to be a backend issue because I see in the response from `OpenReport` I see that there is a currency taken from a Workspace but I see I am sending a currency from a original transaction, but double checking

2024-07-19 10:30 UTC, kubabutkiewicz commented
<img width="488" alt="SCR-20240719-lcgl" src="https://github.com/user-attachments/assets/2ce712ba-02c8-40ba-9014-94cf642a1a06">

2024-07-19 10:54 UTC, kubabutkiewicz commented
<img width="421" alt="image" src="https://github.com/user-attachments/assets/162d7d66-d992-465c-ad30-0a914be9f488">

2024-07-19 13:47 UTC, JmillsExpensify commented
Nice, @pecanoro we're getting really close. QA only has 1% to go. Can we get this merged in the next hour?

2024-07-19 14:05 UTC, pecanoro approved these changes

2024-07-19 14:07 UTC, pecanoro commented
I am merging so it goes into the deploy but just a note that I didn't retest the PR after the most recent commits. Hopefully it doesn't cause any issues, I will test on staging later today.

2024-07-19 14:07 UTC, pecanoro commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->

</details>

<detail [...]

2024-07-19 14:08 UTC, pecanoro commented
Also as a note, due to the urgency, I am copying and pasting the checklist but I didn't go through each item one by one

2024-07-19 14:11 UTC, merged

2024-07-19 14:12 UTC, pecanoro commented
@parasharrajat It would have been great to have had that the checklist completed either way even though you found that small bug so it was ready to be merged this morning

2024-07-19 14:21 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-07-19 20:13 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10013421048) to staging by https://github.com/pecanoro in version: 9.0.10-2 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-07-22 13:35 UTC, OSBotify commented
🚀 [Cherry-picked](https://github.com/Expensify/App/actions/runs/10041305614) to staging by https://github.com/mountiny in version: 9.0.10-3 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅

@Expensify/applauseleads please QA this PR and check it off on the [deploy checklist](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3AStagingDeployCash) if it passes.

2024-07-23 08:02 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10054903341) to production by https://github.com/mountiny in version: 9.0.10-7 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅

2024-07-25 03:13 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10087411925) to production by https://github.com/francoisl in version: 9.0.11-5 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-08-01 12:04 UTC, jayeshmangwani commented
Coming from this issue https://github.com/Expensify/App/issues/45814, It seems we missed disabling the ReceiptEmptyState on confirmation screen



https://github.com/Expensify/App/blob/864c69f61e03669c20f2e0fcddd99f0291fb2240/src/components/ReportActionItem/MoneyRequestView.tsx#L477-L478

2024-10-24 20:35 UTC, rojiphil commented on src/pages/TransactionDuplicate/Confirmation.tsx
> +                    <MoneyRequestView
`MoneyRequestView` should have known that the view is displayed for dupe detection as the display of transaction receipt image depends on money request report id but the transaction itself may not belong to the same report. This caused the transaction receipt image to shown a not found image in #50107

2024-12-10 20:26 UTC, alitoshmatov commented on src/libs/TransactionUtils.ts
> +        comment: {comment: reviewDuplicateTransaction?.description},
Omitting other `reviewDuplicateTransaction.comment` properties caused an issue where if default tax is selected, `Default` label is not shown next to tax name

2025-03-28 16:22 UTC, jjcoffee commented on src/pages/TransactionDuplicate/Confirmation.tsx
> +        Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(reportAction?.childReportID ?? '-1'));
Coming from https://github.com/Expensify/App/issues/58497. The resolve duplicates screen was still in the stack when tapping the back button after confirming duplicates. We should've used `dismissModal` before navigating here to resolve this.