Disable the submit button if required form fields are not filled out
Expensify/App pull request #4272
Opened 2021-07-28 16:18 UTC by jasperhuangg

### Details
See issue for more context.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/171673

### Tests/QA
1. Navigate to the company step in the VBA flow: `<baseURL>/bank-account/company`.
2. These are the fields that need to be filled out in order for the submit button to be enabled. Verify that it is disabled if any of these fields aren't filled out. You don't need to input a valid value, any value will suffice as long as it isn't empty:
    - Legal Business Name
    - Company Address
    - City (for company address)
    - State (for company address)
    - Zip Code (for company address)
    - Company Website
    - Tax ID Number
    - Incorporation Date
    - Industry Classification Code
    - Expensify Password

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [ ] Android

### Screenshots
N/A

2021-07-29 14:21 UTC, madmax330 requested changes

2021-07-29 14:21 UTC, madmax330 commented on src/pages/ReimbursementAccount/CompanyStep.js
> -        if (!this.state.password.trim()) {
Should we leave these in?
B/c the button will be disabled, but what if someone hits return or  "Done" on mobile or whatever, won't that still submit the form and bypass the button being disabled?

2021-07-29 14:22 UTC, madmax330 commented on src/pages/ReimbursementAccount/CompanyStep.js
> -        if (!this.state.password.trim()) {
Basically I don't think we should rely on the button being enabled/disabled as a sign that the input is valid or not.

2021-07-30 02:07 UTC, jasperhuangg commented
@madmax330 Thanks so much for the review! I reverted the commit that removed the duplicate checks, should be good for another look!

2021-07-30 10:00 UTC, madmax330 approved these changes

2021-07-30 10:00 UTC, merged

2021-07-30 10:01 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-07-30 20:09 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1083388541) to staging         in version: 1.0.81-5🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2021-08-06 02:43 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1103640379) to production         in version: 1.0.82-7🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅