[TS Migration] Remove `EmptyObject` type
Expensify/App pull request #42851
Opened 2024-05-30 17:08 UTC by tienifr

### Details

This PR investigates and removes usages of `EmptyObject` type.

### Fixed Issues

$ https://github.com/Expensify/App/issues/39124
PROPOSAL:

### Tests

1. Verify basic flows: IOU, chat, map, mention, task work properly

- [x] Verify that no errors appear in the JS console

### Offline tests

NA

### QA Steps

1. Verify basic flows: IOU, chat, map, mention, task work properly

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/113963320/eb95d9d8-ad3b-4292-8ebd-3b83e8140724

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/113963320/02be86ac-368b-44de-8580-93695a498516

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/113963320/c464d505-5eaa-451c-9251-f0461f7ed0e9

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/113963320/0f015b44-482f-42ad-b74a-49eca2b67736

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/113963320/4d58c89 [...]

2024-06-03 16:40 UTC, blazejkustra requested changes
Looks very promising! 🚀 

How about EmptyObject usage in `src/components/PopoverProvider/types.ts` and `src/hooks/useKeyboardShortcut.ts`?

2024-06-04 11:50 UTC, VickyStash commented on src/libs/actions/IOU.ts
> +                (reportAction as ReportAction & OriginalMessageReportPreview).originalMessage.linkedReportID === iouReportID,
Why do we need assertion here? I think the type is narrowed down by the check of `actionName` above
```suggestion
                reportAction.originalMessage.linkedReportID === iouReportID,
```

2024-06-04 11:50 UTC, VickyStash commented on src/libs/actions/Report.ts
> +    openReport(report?.reportID ?? '', '', userLogins, newChat ?? {}, undefined, undefined, undefined, avatarFile);
Same question, why empty object is used here?

2024-06-04 11:50 UTC, VickyStash commented on src/libs/migrations/CheckForPreviousReportActionID.ts
> +        return Onyx.multiSet(onyxData as Record<`${typeof ONYXKEYS.COLLECTION.REPORT_ACTIONS}`, EmptyObject>);
```suggestion
        return Onyx.multiSet(onyxData as ReportActionsCollectionDataSet);
```

2024-06-04 11:50 UTC, VickyStash commented on src/libs/OptionsListUtils.ts
> +        accountID: personalDetail?.accountID ?? 0,
I think we usually use -1 as a fallback value for `accountID`
```suggestion
        accountID: personalDetail?.accountID ?? -1,
```

2024-06-04 11:50 UTC, VickyStash commented on src/libs/actions/Policy/Policy.ts
> +                              reimbursementChoice: policy?.reimbursementChoice ?? null,
```suggestion
                              approvalMode: policy?.approvalMode,
                              autoReporting: policy?.autoReporting,
                              harvesting: policy?.harvesting,
                              reimbursementChoice: policy?.reimbursementChoice,
```

2024-06-04 11:52 UTC, VickyStash commented
@tienifr Could you please explain why [`receipt` typing](https://github.com/Expensify/App/pull/42851/commits/bbc5694ba41f722dc309547f729f99559f6d8d03) updates where done? Also, why do you sometimes use `OnyxEntry<Receipt>` and sometimes just `Receipt | null` during that updates?

2024-06-05 11:17 UTC, fabioh8010 commented
@tienifr bump, and we have conflicts now

2024-06-07 02:19 UTC, mkhutornyi reviewed
Conflicts again

2024-06-07 17:17 UTC, fabioh8010 commented
@tienifr kindly bump, could we try to prioritize this PR to get it moving faster? Thanks!

2024-06-13 14:42 UTC, blazejkustra commented
@tienifr Any updates on the PR?

2024-06-14 15:33 UTC, blazejkustra commented
@tienifr I think you need to use `undefined` instead of `null` for most cases, let me know if it works

2024-06-14 16:53 UTC, mountiny commented
I have started a thread in here for y'all to align on what is needed https://expensify.slack.com/archives/C01GTK53T8Q/p1718383194236479

@tienifr can you have this ready on Monday?

2024-06-17 13:55 UTC, blazejkustra requested changes
Small remarks, looks very promising!

2024-06-17 13:55 UTC, blazejkustra commented on src/components/AddPaymentMethodMenu.tsx
> +    const isIOUReport = ReportUtils.isIOUReport(iouReport ?? null);
```suggestion
    const isIOUReport = ReportUtils.isIOUReport(iouReport);
```

2024-06-17 13:55 UTC, blazejkustra commented on src/components/AddPaymentMethodMenu.tsx
> +        ReportUtils.isExpenseReport(iouReport ?? null) || (isIOUReport && !ReportActionsUtils.hasRequestFromCurrentAccount(iouReport?.reportID ?? '-1', session?.accountID ?? -1));
```suggestion
        ReportUtils.isExpenseReport(iouReport) || (isIOUReport && !ReportActionsUtils.hasRequestFromCurrentAccount(iouReport?.reportID ?? '-1', session?.accountID ?? -1));
```

2024-06-17 13:55 UTC, blazejkustra commented on src/libs/actions/MapboxToken.ts
> +        API.read(READ_COMMANDS.GET_MAPBOX_ACCESS_TOKEN, null, {});
Let's verify that API commands work well with `null` passed here

2024-06-17 13:55 UTC, blazejkustra commented on src/pages/home/report/ReportActionsList.tsx
> +    const lastReportAction: OnyxTypes.ReportAction | null = useMemo(() => sortedReportActions.at(-1) ?? null, [sortedReportActions]);
Let's use `undefined` here instead of `null`

2024-06-17 13:55 UTC, blazejkustra commented on src/types/onyx/OriginalMessage.ts
> +    originalMessage: undefined | null; // No data is sent with this action
Can we use only undefined here?
```suggestion
    originalMessage: undefined; // No data is sent with this action
```

2024-06-18 09:30 UTC, blazejkustra approved these changes
Looks good to me! 🚀

2024-06-18 09:31 UTC, blazejkustra commented
@VickyStash @mkhutornyi Yours now 👍

2024-06-18 09:44 UTC, VickyStash approved these changes

2024-06-19 10:07 UTC, blazejkustra commented
@mkhutornyi Please prioritize as this can get daily conflicts 🙏

2024-06-21 18:03 UTC, srikarparsi commented
Looks like there are more conflicts already @tienifr

2024-06-24 08:41 UTC, srikarparsi commented
@mkhutornyi please let me know after you review so that we can merge before there's conflicts again

2024-06-24 19:10 UTC, srikarparsi commented
Looks like there's a conflict but @mkhutornyi please review/add screenshots anyway. The conflicts look relatively small and I will also review them before merging after @tienifr fixes.

2024-06-25 01:42 UTC, srikarparsi commented
@mkhutornyi is there any update here?

2024-06-26 04:50 UTC, mkhutornyi approved these changes
Looks good except conflict

2024-06-26 04:57 UTC, srikarparsi commented
Thanks @mkhutornyi, I know screenshots/videos are a little difficult for this one but if you could add some type of screenshots that would just help check off the requirement for this.

@tienifr, I'm reviewing now but if you could fix the conflict whenever you have a chance that would be great. It looks like just replacing the {} with null.

2024-06-26 06:31 UTC, srikarparsi submitted a review, later dismissed
This looks good to me as well apart from the conflict. Thanks everyone! @tienifr please let me know once you get around to resolving the conflict and I can re-approve and merge. There seems to be a couple more now.

2024-06-26 12:34 UTC, srikarparsi approved these changes
Great thanks!

2024-06-26 12:35 UTC, merged

2024-06-26 12:45 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-07-03 19:37 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/9783702010) to production by https://github.com/jasperhuangg in version: 9.0.3-7 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-07-10 10:54 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/9872741083) to production by https://github.com/Julesssss in version: 9.0.5-13 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅