[ESM] Localize system messages
Expensify/App pull request #43079
Opened 2024-06-04 22:30 UTC by BrtqKr

### Details

### Fixed Issues

$
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-06-21 15:17 UTC, deetergp approved these changes
Overall looks pretty good to me. Thanks! I had a couple comments inline. Let's address those, get testing steps added, and complete the checklist.

2024-06-21 17:34 UTC, deetergp requested changes
I Meant to hit "Request changes" not "Approve."

2024-06-24 17:16 UTC, deetergp commented
@BrtqKr You should be able to at least test the Export to CSV part of this by creating a collect workspace with two users, submitting an expense from one user to the other, approving the report in OldDot, and exporting it to CSV.

2024-06-24 17:20 UTC, deetergp commented
There's one thing you'll need to fix in order for it to work:
```diff
diff --git a/src/libs/ReportActionsUtils.ts b/src/libs/ReportActionsUtils.ts
index 204fec860a..a4de4c544d 100644
--- a/src/libs/ReportActionsUtils.ts
+++ b/src/libs/ReportActionsUtils.ts
@@ -192,6 +192,10 @@ function getWhisperedTo(reportAction: OnyxInputOrEntry<ReportAction>): number[]
     const originalMessage = getOriginalMessage(reportAction);
     const message = reportAction?.message;

+    if (originalMessage == '[]') {
+        return [];
+    }
+
     if (!(originalMessage && 'whisperedTo' in originalMessage) && !(message && 'whisperedTo' in message)) {
         return [];
     }
```

2024-06-24 17:22 UTC, deetergp commented
https://github.com/Expensify/App/assets/766197/f42eec13-ce64-42ff-9386-30e993764c67

2024-06-24 20:49 UTC, trjExpensify commented
@parasharrajat just a heads up this is an important one to jump on reviewing ASAP for #wave-collect. Thanks!

2024-06-25 09:19 UTC, BrtqKr commented
@deetergp Is this condition meant for other messages? I've included the change, but export to CSV seems to be working even without that. Anyway, it seems to be working as expected

<img width="406" alt="image" src="https://github.com/Expensify/App/assets/45288762/7a4afb40-385c-4ef7-81ee-78557894d5fb">

<img width="422" alt="image" src="https://github.com/Expensify/App/assets/45288762/f7e28bd2-a337-4566-931e-f91a951dd94a">

2024-06-25 14:52 UTC, deetergp commented
@BrtqKr It turns out the issue with Export CSV was because of [a regression](https://github.com/Expensify/App/pull/40168) that another contributor introduced. If you never updated to that version or have updated since (it has been fixed) then it should not be necessary.

2024-06-25 14:52 UTC, deetergp commented on src/CONST.ts
> +                DELETED_ACCOUNT: 'DELETEDACCOUNT', // Deprecated OldDot Action
Let's leave that one be for now

2024-06-25 21:07 UTC, deetergp commented on src/libs/ReportActionsUtils.ts
> -    }
That is a valid point. Nice catch @parasharrajat. 

@BrtqKr let's add these back. The back end changes I spoke of earlier will prevent new ones from being created, but it won't prevent old ones from being shown, which is what this code did.

2024-06-26 16:17 UTC, BrtqKr commented on src/libs/ReportActionsUtils.ts
> +function getMessageOfOldDotReportAction({originalMessage, actionName}: OldDotOriginalMessage): string {
Let's just use message the old way based on the predefined array, the rest of them are defined based on the key. I've already adjusted the types and the conditions

2024-06-26 19:06 UTC, deetergp commented
@parasharrajat There a lot of flows here but another one you can try is:
1. On a workspace with Workflows and Add Approvals enabled, submit an expense from a submitter to an approver to the workspace chat
2. Navigate to the Concierge chat (or any other chat that isn't workspace or the expense report)
3. In an incognito browser, log in as the approver and approve the expense and wait a moment
4. Go back to the submitter's browser window
    - [ ] Verify that the expense chat doesn't show up in the LHN as unread
 5. Navigate to the expense chat
     - [ ] Verify that there is a already message saying the approver approved the amount
  6. In Settings, change the language
     - [ ] Verify that the message text is translated to whichever language you switched to

2024-06-26 19:15 UTC, deetergp commented
I haven't tested this one yet, but it should work…
Given a workspace with an owner and an admin
1. Log into NewDot as the admin & verify you see an `#admins room`. If it is bolded/unread mark it unread, then navigate to a different chat.
3. Log into OldDot as the owner and navigate to the workspace settings.
4. Click Reports and add a named field and save it.
5. Then change the field name and save it.
6. Switch back to the admin in NewDot and wait a moment.
    - [ ] Verify that the #admins room does not go unread
7. Click into the `#admins` room
    - [ ] Verify that there is a message there showing that the field was changed
8. Change the admin's langage in Preferences
    - [ ] Verify that the message is translated

2024-06-26 19:16 UTC, deetergp commented
Those ought to be enough prove that this works.

2024-06-27 14:09 UTC, BrtqKr commented
@parasharrajat looks like it might be because of this thing https://github.com/Expensify/App/pull/43079#issuecomment-2188400627. [@deetergp  mentioned that it's already been fixed](https://github.com/Expensify/App/pull/43079#issuecomment-2189176386), so I assume this might still be relevant.

2024-06-27 15:03 UTC, deetergp commented
@parasharrajat If you haven't pulled `main` into your testing branch recently, give that as shot. The bug that introduce that _should_ be resolved now.

2024-06-27 18:21 UTC, deetergp commented
@BrtqKr I think you've got merge conflicts with the current `main`.

2024-06-27 18:47 UTC, deetergp commented
@parasharrajat My apologies, that is on me. I was working on that flow for a different PR. Neither `APPROVED` nor `SUBMITTED` are a part of this PR, so it is expected that neither of those would pass. Let me get you a different test case.

2024-06-27 19:14 UTC, deetergp commented
0. Have a Workflows + Approvals enabled workspace with a submitter and an approver
1. In OldDot, as the admin/approver go to Settings -> Workspaces -> your workspace -> Reports and add a field
2. In NewDot, as the submitter, submit an expense to the workspace chat
3. In OldDot, view the report and a value to the field
4. Pause a moment
5. In NewDot, view the expense report
    - [ ] Verify that a message is there saying the field was changed from something to something else
    - [ ] Verify that the message changes to Spanish when the language pref is changed

<img width="1728" alt="Screenshot 2024-06-27 at 12 14 00 PM" src="https://github.com/Expensify/App/assets/766197/2d7ace9c-b245-49f9-bcfc-261a9b1569c6">
<img width="855" alt="Screenshot 2024-06-27 at 12 14 16 PM" src="https://github.com/Expensify/App/assets/766197/5d059a86-c8fb-4c27-86f2-74d2ccceccda">

2024-06-28 07:30 UTC, parasharrajat requested changes
More conflicts @BrtqKr

2024-06-28 09:41 UTC, trjExpensify commented on src/languages/en.ts
> +                integrationsMessage: ({errorMessage}: IntegrationsMessageParams) => `failed to export this report to NetSuite. ${errorMessage}`,
Just checking but `NetSuite` here doesn't seem to be variable depending on what accounting solution is connected? I.e they could be exporting to Xero, not NetSuite, for example.

2024-06-28 10:34 UTC, BrtqKr commented
@trjExpensify I've added a template label as in `exportedToIntegration`

@parasharrajat I've added a conditional case for that 

`changeFieldEmpty: ({newValue, fieldName}: ChangeFieldParams) => `changed ${fieldName} to ${newValue}`,` 

@deetergp is it possible that `policy` or `type` could be empty in some kind of scenario?

2024-06-28 11:25 UTC, parasharrajat approved these changes
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

:ribbon: :eyes: :ribbon:  C+ reviewed

2024-06-28 15:34 UTC, deetergp approved these changes
PR Looks good to me too 👍

2024-06-28 15:34 UTC, deetergp commented
> @deetergp is it possible that policy or type could be empty in some kind of scenario?

No, I don't think that is possible.

2024-06-28 16:06 UTC, deetergp requested changes
@BrtqKr The perf-tests are failing consistently due to `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` and I believe it is related to the changes in tests/utils/collections/reportActions.ts. We ran into a similar issue in an [earlier PR](https://github.com/Expensify/App/pull/42811/files) and those changes are what resolved it. Can you undo those changes?

2024-06-30 21:25 UTC, BrtqKr commented
@deetergp I've merged main and reverted tests it seems to be passing the check

2024-07-01 07:34 UTC, deetergp approved these changes
Looks good! Thanks for the changes 👍

2024-07-01 07:36 UTC, merged

2024-07-01 07:43 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-07-03 20:00 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/9783702773) to staging by https://github.com/deetergp in version: 9.0.4-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-07-04 22:12 UTC, OSBotify commented
🚀 [Cherry-picked](https://github.com/Expensify/App/actions/runs/9800117961) to staging by https://github.com/tgolen in version: 9.0.4-5 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

@Expensify/applauseleads please QA this PR and check it off on the [deploy checklist](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3AStagingDeployCash) if it passes.

2024-07-10 10:55 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/9872741083) to production by https://github.com/Julesssss in version: 9.0.5-13 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-07-15 20:18 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/9945901401) to production by https://github.com/thienlnam in version: 9.0.6-8 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅