Different throw for Missing partnerUserSecret
Expensify/App pull request #4313
Opened 2021-07-29 21:04 UTC by joelbettner

@Expensify/pullerbear will you please review?

### Details
This PR allows us to display the correct error message when a password of less than 4 characters is entered.

### Fixed Issues
$ https://github.com/Expensify/App/issues/4292

### Tests
1. Entered a password that was less than 4 characters long and confirmed I got the correct error message:
![image](https://user-images.githubusercontent.com/13264774/127565402-f2cf5dec-28ca-4fb1-9327-d7e799dd964e.png)

### QA
1. Repeat the steps from the above test on Web, iOS and Android

2021-07-29 21:08 UTC, tylerkaraszewski approved these changes

2021-07-29 21:08 UTC, tylerkaraszewski requested changes
Oops, wrong quotation marks.

2021-07-29 21:27 UTC, tylerkaraszewski approved these changes

2021-07-29 23:30 UTC, yuwenmemon approved these changes

2021-07-29 23:30 UTC, merged

2021-07-29 23:30 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-07-30 20:09 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1083388541) to staging         in version: 1.0.81-5🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2021-08-06 02:43 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1103640379) to production         in version: 1.0.82-7🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅