Remove unused propType for CollapsibleSection
Expensify/App pull request #4386
Opened 2021-08-02 22:51 UTC by Jag96

@marcaaron will you please review this?

### Details
This PR removes an unused propType from the CollapsibleSection component. This is a follow-up to https://github.com/Expensify/App/pull/3879#pullrequestreview-720419096.

### Fixed Issues
Follow up to https://github.com/Expensify/App/pull/3879#pullrequestreview-720419096

### Tests
The easiest way to get to the Terms Page without going through the entire OnFido flow is to update the following lines locally:

1. Undo [this change](https://github.com/Expensify/App/pull/3879/commits/a1b6d5b4690057cbe786aa68fe416062d931318d#diff-239d10d81e0cd799a3aa5ae1c9f951c5cc10c75d1924e1efe3473f97dd09e93fR35) which makes the default step the terms page
2. Undo [this change](https://github.com/Expensify/App/pull/3879/commits/a1b6d5b4690057cbe786aa68fe416062d931318d#diff-9b9fee594bc95324fa21caa02ac4d6d9692ce460c56587ff9aea35893fb3dde2R117) which will let you navigate to the terms page by tapping on the `+` button and selecting `New Chat`
3. Confirm you can open and close the `All Expensify Payments account fees` dropdown, and that it's initial state is closed

Note, there is an issue where the enable-payments page only shows up the first time you view it until you sign out ([slack post](https://expensify.slack.com/archives/C01GTK53T8Q/p1627944072091400))

### QA Steps
N/A

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

2021-08-02 22:54 UTC, marcaaron approved these changes, later dismissed
LGTM!

2021-08-03 19:16 UTC, tgolen requested changes

2021-08-03 19:16 UTC, tgolen commented on src/components/CollapsibleSection/index.js
> +import propTypes from './CollapsibleSectionPropTypes';
I can't find where these are used in any other file. Can you please just move them into this component to clean it up a little further?

2021-08-05 17:59 UTC, Jag96 commented
@tgolen updated!

2021-08-11 21:37 UTC, tgolen approved these changes

2021-08-11 21:38 UTC, merged

2021-08-11 21:38 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-08-17 18:53 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1140319573) to staging by @tgolen in version: 1.0.85-10 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅