Fix broken two touch zoom for Attachment Images
Expensify/App pull request #4440
Opened 2021-08-06 01:23 UTC by Jag96

@marcaaron will you please review this?

### Details
This PR fixes a regression where zooming with two fingers on an attachment was broken.

### Fixed Issues

$ https://github.com/Expensify/App/issues/2499

### Tests/QA
1. Sign into an account and send an image attachment
2. After the attachment uploads, tap on it, confirm an attachment modal shows
3. Double tap on the image, confirm it zooms
4. Double-tap again, confirm it zooms out
5. Use two fingers to zoom in, confirm the image zooms in
6. While zoomed in, swipe down and right and confirm the modal doesn't close, and that the viewport pans around the zoomed image
7. Double-tap again then swipe down or right, confirm the modal dismisses
8. Confirm that there are no regressions on web
    1. Confirm attachments still show up on web
    2. Confirm the modal attachment closes normally on web

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

<img src='http://g.recordit.co/6V36awfawm.gif' width='400'/>

2021-08-06 15:46 UTC, yuwenmemon approved these changes, later dismissed

2021-08-09 19:39 UTC, marcaaron requested changes
Looks good there's just a small style guide rule we should fix up

2021-08-09 19:39 UTC, marcaaron commented on src/components/ImageView/index.native.js
> +    handleOnStartShouldSetPanResponder(e, gestureState) {
Style guide rule about this [here](https://github.com/Expensify/App/blob/main/STYLE.md#naming-conventions)

2021-08-09 19:39 UTC, marcaaron commented on src/components/ImageView/index.native.js
> +                        const touches = this.amountOfTouches;
NAB, don't really need to declare `touches` variable

2021-08-09 19:39 UTC, marcaaron commented on src/components/ImageView/index.native.js
> +                     */}
Whoa, nice workaround

2021-08-09 22:35 UTC, Jag96 commented
Updated!

2021-08-09 22:51 UTC, marcaaron approved these changes
LGTM 🤘

2021-08-10 01:34 UTC, merged

2021-08-10 01:35 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-08-11 22:19 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1120800158) to staging by @Jag96 in version: 1.0.83-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|failure ❌
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-08-17 18:19 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1140313603) to production by @isagoico in version: 1.0.85-9 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅