fix: Design updates to Search rows on mobile
Expensify/App pull request #44677
Opened 2024-07-01 11:37 UTC by dominictb

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/44563
PROPOSAL: https://github.com/Expensify/App/issues/44563#issuecomment-2195878728

### Tests

#### Small screen device:
1. Open app
2. Go to /search/all?sortBy=date&sortOrder=desc
3. Verify these below behavior:
 
- There is no tag from the bottom line under the merchant, and only show a Category if one is available
- There is no Fold icon in front of Category
- If no category exists, the Merchant line is vertically centered in the available space
- If no Merchant exists, the description is displayed.

#### Large screen device:
1. Open app
2. Go to /search/all?sortBy=date&sortOrder=desc
3. Verify it works as it is
- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/165644294/e87fcea9-fab1-4363-ad7c-74443cdbb3e9

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/165644294/2e70a913-733c-481d-9a21-b324235eb896

</details>

<deta [...]

2024-07-01 16:44 UTC, shawnborton commented
The category should still be styled in the same gray text that it was before, looks like it's dark from the screenshots:
![CleanShot 2024-07-01 at 18 43 39@2x](https://github.com/Expensify/App/assets/2319350/51452bf7-d187-4d0e-9fcb-1f4dc33857f7)

2024-07-01 21:54 UTC, shawnborton commented
I think we need to make sure we are truncating Merchants/Descriptions after 1 line, looks like the descriptions can get quite long here:
![CleanShot 2024-07-01 at 23 54 28@2x](https://github.com/Expensify/App/assets/2319350/656ae8c3-5960-4d8c-9717-065e2eb09ab0)

2024-07-02 19:19 UTC, luacmartins requested changes

2024-07-02 19:19 UTC, luacmartins commented on src/components/SelectionList/Search/TransactionListItemRow.tsx
> +                        isLargeScreenWidth={isLargeScreenWidth}
yes, in this case it's always `false` since we're still inside the if block

2024-07-04 07:25 UTC, shawnborton commented
Looking really great! 

One small thing: I still see multiple lines for a super long description where I am purposely using line breaks to test... 
![CleanShot 2024-07-04 at 09 24 45@2x](https://github.com/Expensify/App/assets/2319350/8186a98b-9fa4-4b75-8a61-6eafccac87d2)

![CleanShot 2024-07-04 at 09 25 25@2x](https://github.com/Expensify/App/assets/2319350/1211e647-fc85-4f5e-9075-50849320a9b8)

Can you make sure that truncates after 1 line as well?

2024-07-04 10:13 UTC, shawnborton commented
Oh and another thing we chatted about - the idea that the "View" buttons on mobile felt quite superfluous and we could just omit them entirely. It would look something more like this:
![CleanShot 2024-07-04 at 12 12 11@2x](https://github.com/Expensify/App/assets/2319350/df576495-b8e5-4324-975c-38fe9b84a440)

Thoughts @Expensify/design @luacmartins? Feels like we could make that change in this same PR while we are here.

2024-07-04 13:31 UTC, dannymcclain commented
>Oh and another thing we chatted about - the idea that the "View" buttons on mobile felt quite superfluous and we could just omit them entirely.

I could honestly go either way on this one. I don't _hate_ the view buttons on mobile, but I also totally understand why we'd get rid of them. Curious for others' thoughts because I really don't have any strong feelings about this one.

2024-07-04 16:16 UTC, luacmartins commented
I'm down to removing the button on mobile since they dont really do much and less components on screen means higher performance.

2024-07-04 18:12 UTC, shawnborton commented
Works for me - let's see if @dubielzyk-expensify has any strong feelings too, though I do tend to agree that it will make the page feel a bit lighter.

2024-07-04 22:53 UTC, dubielzyk-expensify commented
I like it 👍

2024-07-05 07:36 UTC, shawnborton commented
Okay, let's remove the View button from mobile expenses then. @dominictb can you handle that one too please? Thanks!

2024-07-05 12:08 UTC, shawnborton commented
Lovely! Will also spin up a test build here, but we should be ready for final review. Thanks!

2024-07-05 15:06 UTC, shawnborton commented
Looks great, let's get it into final review!

2024-07-08 03:52 UTC, dukenv0307 approved these changes

2024-07-08 15:37 UTC, luacmartins approved these changes
LGTM

2024-07-08 15:37 UTC, merged

2024-07-08 15:47 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-07-10 11:20 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/9872743303) to staging by https://github.com/luacmartins in version: 9.0.6-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|failure ❌
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-07-10 11:37 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/9872743303) to staging by https://github.com/luacmartins in version: 9.0.6-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-07-11 07:16 UTC, shawnborton commented
Hmm not sure what's going on but I just tested this on our latest TestFlight app and it looks like the View button still shows for all mobile rows. Any idea what happened there? 

It also looks like the "Paid" button isn't aligned to the right edge of the top header area of the row either:
![CleanShot 2024-07-11 at 09 16 08@2x](https://github.com/Expensify/App/assets/2319350/0b7e9018-eb56-4553-b470-466262c4bb6c)

Can we do a quick follow up to address those issues? Thanks!

2024-07-11 09:37 UTC, shawnborton commented
Perfect, thanks!

2024-07-11 10:17 UTC, OSBotify commented
🚀 [Cherry-picked](https://github.com/Expensify/App/actions/runs/9889170505) to staging by https://github.com/Julesssss in version: 9.0.6-1 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|failure ❌
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

@Expensify/applauseleads please QA this PR and check it off on the [deploy checklist](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3AStagingDeployCash) if it passes.

2024-07-11 10:37 UTC, OSBotify commented
🚀 [Cherry-picked](https://github.com/Expensify/App/actions/runs/9889170505) to staging by https://github.com/Julesssss in version: 9.0.6-1 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

@Expensify/applauseleads please QA this PR and check it off on the [deploy checklist](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3AStagingDeployCash) if it passes.

2024-07-15 20:23 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/9945901401) to production by https://github.com/thienlnam in version: 9.0.6-8 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-07-16 15:30 UTC, luacmartins commented on src/components/SelectionList/Search/TransactionListItemRow.tsx
> +                        {item.category && (
Oh nice catch @Kicu. I can fix it now since it might lead to a crash on native. PR [here](https://github.com/Expensify/App/pull/45490)

2024-07-17 00:19 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/9965822856) to production by https://github.com/thienlnam in version: 9.0.7-8 🚀

platform | result
---|---
🤖 android 🤖|failure ❌
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅