Fix: Use different fallback receipt icon when displaying a Search row that has no receipt and isn't editable
Expensify/App pull request #44742
Opened 2024-07-02 18:43 UTC by neonbhai

### Details

### Fixed Issues
$ https://github.com/Expensify/App/issues/44240
PROPOSAL: https://github.com/Expensify/App/issues/44240#issuecomment-2186596927

### Tests
1. Open Expensify App
2. Go to Search
3. Verify the slashed receipt is visible if a report is settled

- [x] Verify that no errors appear in the JS console

### Offline tests
Same as Tests step

### QA Steps
Same as Tests step

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-07-11 03:50 UTC, neonbhai commented
My mac stopped working a few days ago, just got it back from repair. Working on Finalizing this PR! Sorry for the delay! 🙇

2024-07-15 04:37 UTC, neonbhai commented
@s77rt PR is ready for your review!

Noting one thing, The pay someone flow in app seems to have a problem on main where the request is marked Submitted instead of Reimbursed, making `isSettled` calculation false


<details><Summary>Image</Summary>
<img width="1089" alt="Screenshot 2024-07-14 at 6 14 34 AM" src="https://github.com/user-attachments/assets/1c26f5b9-c91e-44a8-83f7-fed11f1f47b2">
</details>


I've been trying to debug the root cause and the optimistic data is fine. The bug seems to be with how Onyx is managing the BE responses. @bernhardoj also observed the same thing when debugging a similar issue (with connected root cause) [here](https://github.com/Expensify/App/issues/44914#issuecomment-2211753381)

2024-07-15 15:23 UTC, s77rt requested changes

2024-07-15 15:23 UTC, s77rt commented on src/components/SelectionList/Search/TransactionListItemRow.tsx
> +    const canModifyReceipt = !ReportUtils.isReportApproved(transactionItem.reportID) && !ReportUtils.isSettled(transactionItem.reportID);
Closed reports can't have their receipt changed https://github.com/Expensify/App/issues/44240#issuecomment-2187287469

2024-07-15 19:34 UTC, neonbhai commented on src/components/SelectionList/Search/TransactionListItemRow.tsx
> +    const canModifyReceipt = !ReportUtils.isReportApproved(transactionItem.reportID) && !ReportUtils.isSettled(transactionItem.reportID);
Ah right, updated!

2024-07-15 20:30 UTC, s77rt requested changes

2024-07-15 20:30 UTC, s77rt commented on src/components/SelectionList/Search/TransactionListItemRow.tsx
> +    const canModifyReceipt = !ReportUtils.isReportApproved(transactionItem.reportID) && !ReportUtils.isSettled(transactionItem.reportID) && !ReportUtils.isClosedReport(transactionItem.reportID);
Instead of checking if the report is not eligible we should check if the report is eligible i.e. canModifyReceipt = isOpen || isSubmitted

2024-07-15 20:31 UTC, s77rt requested changes

2024-07-23 20:29 UTC, luacmartins commented
What's the status on this one @neonbhai ?

2024-07-31 16:15 UTC, s77rt commented
@neonbhai Any updates on this?

2024-07-31 19:58 UTC, neonbhai commented
Apologies for the delay 🙇 bought and setup a new pc

PR is ready for review!

Noting that when using a high traffic account not all reports are loaded in Onyx, this makes the `report` status checks incorrect (as it is null)



https://github.com/user-attachments/assets/59133eaf-09d5-4caa-882e-c8ce184f8c84



The icon updates after we click on it and the report is loaded. Simultaneously `allReports` length increases as a new report is loaded



To fix this I have added an extra check for Paid and Done actions, since these transactions cannot be modified

cc: @s77rt

2024-07-31 20:41 UTC, s77rt commented
@neonbhai Can you please merge `main`? I'm having a problem testing this

2024-07-31 21:39 UTC, neonbhai commented
Merged main!

2024-08-01 07:22 UTC, s77rt commented
@neonbhai Still seeing reports with the wrong icon


https://github.com/user-attachments/assets/3a6b3519-e0af-44fd-8505-7b4bd55bcc9e

2024-08-01 15:46 UTC, neonbhai commented
Looks like this is still caused by the issue that not all report objects shown in search are loaded in Onyx 😥
This makes the status checks on the `report` objects `null` [here](https://github.com/Expensify/App/pull/44742/files#diff-577fcc5f3a5e4930916ff310e61c38edfa093792fe3ab55b9a30d2aecd8811dbR878)

Possible Solutions: 
- Call openReport when a report is not found in Onyx.
  wondering if the decision to not load all this was done as part of the performance improvements in App, since there are prod accounts with 15K reports. Calling openReport on search page will affect performance for high traffic accounts

- Since we show Receipt thumbnail for every transactionItem on the search page, suggesting we have `canModifyReceipt` as part of the `transactionItem` data coming from BE (as BE would have access to the reports connected to transaction data it is sending). This would save the frontend client from loading full reports. 
I would recommend this.

cc: @s77rt

2024-08-01 17:07 UTC, s77rt commented
@neonbhai Can we use the existing fields: **action**, **canDelete** and **canHold**?

2024-08-02 15:25 UTC, neonbhai commented
We might be able to use canDelete, but I see a bug in app:

When setting up a flow, where an Employee submits to an Approver -> Which then goes to the Admin
(Submit Frequency is Manual)

The Approver and Requestor can see the receipt empty state, but cannot click on it to add a receipt:




https://github.com/user-attachments/assets/bc9dd753-ebce-449c-84d6-d6ae5f6775da

Admin's POV for a submitted Expense. The empty state is not clickable (cannot edit receipt)

2024-08-02 15:30 UTC, neonbhai commented
Here is the current behaviour of app:

Flow: Employee submits to an Approver -> Which then goes to the Admin
(Submit Frequency is Manual)

#### The expenses were made (not submitted yet)
- Requestor - can Edit Receipt
- Approver - cannot Edit Receipt - sees empty state
- Admin - cannot Edit Receipt - sees empty state 

#### The expenses were submitted
- Requestor - can Edit Receipt
- Approver - cannot Edit Receipt - sees empty state
- Admin - cannot Edit Receipt - sees empty state

#### The expenses were approved
- Requestor - cannot Edit Receipt
- Approver - cannot Edit Receipt
- Admin - cannot Edit Receipt

#### The expenses were paid
- Requestor - cannot Edit Receipt
- Approver - cannot Edit Receipt
- Admin - cannot Edit Receipt

---
Is the behavior of the Approver and Admin not being able to edit the receipt in any step correct? 

And if a role cannot edit an expense, should they be seeing the receipt empty state?


cc: @s77rt @luacmartins

2024-08-03 11:06 UTC, s77rt commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->
<img width="480" alt [...]

2024-08-03 11:06 UTC, s77rt requested changes

2024-08-03 11:06 UTC, s77rt commented on src/libs/ReportUtils.ts
Revert

2024-08-03 11:07 UTC, s77rt commented
@neonbhai If the user (no matter their role) cannot add a receipt they should not see the "add the receipt" icon

2024-08-03 18:00 UTC, neonbhai commented on src/libs/ReportUtils.ts
ah right, reverted!

2024-08-04 16:33 UTC, s77rt commented
@neonbhai 

> Verify the slashed receipt is visible if a report is settled

This is not clear. Please change to:
- In the receipt column, verify that:
    - If the report has a receipt, the receipt preview is shown
    - If the report has no receipt and is open/submitted then the "Receipt Plus" icon is shown
    - If the report has no receipt and is settled then the "Receipt Slash" icon is shown 

Tag me once done

2024-08-04 16:37 UTC, neonbhai commented
Makes sense, updated!

cc: @s77rt

2024-08-04 16:52 UTC, s77rt approved these changes
Thank you!

2024-08-05 07:51 UTC, luacmartins approved these changes

2024-08-05 07:51 UTC, merged

2024-08-05 08:02 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-08-06 04:27 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10259951896) to staging by https://github.com/luacmartins in version: 9.0.17-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-08-07 22:03 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10292258172) to production by https://github.com/marcaaron in version: 9.0.17-2 🚀

platform | result
---|---
🤖 android 🤖|failure ❌
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-08-08 04:52 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10292258172) to production by https://github.com/marcaaron in version: 9.0.17-2 🚀

platform | result
---|---
🤖 android 🤖|failure ❌
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-08-08 20:04 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10292258172) to production by https://github.com/marcaaron in version: 9.0.17-2 🚀

platform | result
---|---
🤖 android 🤖|failure ❌
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅