Show Avatar image for Workspace List Item in Sidebar
Expensify/App pull request #4512
Opened 2021-08-09 19:32 UTC by mananjadhav

### Details
Updated the `MenuItem` component to allow Avatar support and accordingly updated the Workspace List Item icon param.

### Fixed Issues

$ #4434 

### Tests
1. Added Avatar Image and checked the sidebar list item
2. Tested removing Avatar image should rollback to show a default icon
3. Default Icon to be the building icon

### QA Steps

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web
https://user-images.githubusercontent.com/3069065/128763484-28ad0b1b-2afe-4c10-b5f0-fe578d1a6d5b.mp4

#### Mobile Web
![wkspace-sbar-icon-mweb](https://user-images.githubusercontent.com/3069065/128763139-61b4301f-d620-49ff-8e58-c555c057346c.png)

#### Desktop
![wkspace-sbar-icon-desktop](https://user-images.githubusercontent.com/3069065/128763154-af2df7bf-0c7b-4185-ae15-cbadbedfea9e.png)

#### iOS
![wkspace-sbar-icon-ios](https://user-images.githubusercontent.com/3069065/128763190-64d27a98-b51b-442e-bcb5-c841b1fe3d83.png)

#### Android
![wkspace-sbar-icon-android](https://user-images.githubusercontent.com/3069065/128763218-b554c844-5137-4f80-a226-5df21482654c.png)

2021-08-10 17:14 UTC, nickmurray47 commented on src/components/MenuItem.js
> +    iconType: PropTypes.oneOf(['avatar', 'icon']),
Missing comment here

2021-08-10 17:15 UTC, nickmurray47 commented
Looks pretty good to me, just need to add one comment there and this looks ready to go!

2021-08-10 17:21 UTC, mananjadhav commented on src/components/MenuItem.js
> +    iconType: PropTypes.oneOf(['avatar', 'icon']),
Added

2021-08-10 17:21 UTC, mananjadhav commented
PR Updated

2021-08-10 18:20 UTC, MonilBhavsar submitted a review, later dismissed

2021-08-10 20:26 UTC, mananjadhav commented
@nickmurray47 Can you check the PR again and merge this? Monil has approved the changes.

2021-08-10 21:38 UTC, nickmurray47 requested changes
Last thing @mananjadhav but can you replace any references to the strings 'avatar' or 'icon' with new variables added to the `CONST.js` file please, i.e. `'avatar'` becomes `CONST.AVATAR`?

2021-08-11 04:17 UTC, mananjadhav commented
@nickmurray47 Done. Thanks for pointing it out. I should've done it in the first place.

2021-08-11 04:20 UTC, nickmurray47 commented on src/components/MenuItem.js
> +                    {(icon && iconType === 'icon') && (
here and below
```suggestion
                    {(icon && iconType === 'CONST.ICON_TYPE_AVATAR') && (
```

2021-08-11 04:23 UTC, mananjadhav commented on src/components/MenuItem.js
> +                    {(icon && iconType === 'icon') && (
Good eye.  Fixed.

2021-08-11 20:08 UTC, nickmurray47 approved these changes
👍

2021-08-11 20:08 UTC, merged

2021-08-11 20:08 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-08-17 18:54 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1140319573) to staging by @nickmurray47 in version: 1.0.85-10 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-08-30 17:21 UTC, botify commented
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-06.  :confetti_ball: