When uploading, automatically reduce the size of receipt image
Expensify/App pull request #45448
Opened 2024-07-16 03:01 UTC by nkdengineer

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/44084
PROPOSAL: https://github.com/Expensify/App/issues/44084#issuecomment-2188022852

### Tests

- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-07-23 16:00 UTC, luacmartins requested changes
I haven't tested but code LGTM. Left a small suggestion to simplify the resizing code

2024-07-23 16:00 UTC, luacmartins commented on src/libs/fileDownload/FileUtils.ts
> +        }
We can simplify this a bit

```suggestion
        const scaleFactor = CONST.MAX_IMAGE_DIMENSION / (width < height ? height : width);
        const newWidth = width * scaleFactor;
        const newHeight = height * scaleFactor;
```

2024-07-24 03:04 UTC, nkdengineer commented on src/libs/fileDownload/FileUtils.ts
> +        }
Thanks your suggestion

2024-07-24 14:43 UTC, luacmartins commented
@shubham1206agra I think any image over 2MB should do it

2024-07-24 17:26 UTC, luacmartins submitted a review, later dismissed

2024-07-26 15:03 UTC, luacmartins commented
@shubham1206agra bump for review

2024-07-29 07:24 UTC, nkdengineer commented on src/libs/fileDownload/FileUtils.ts
> +    if (!file || !Str.isImage(file.name ?? '') || (file?.size ?? 0) <= CONST.API_ATTACHMENT_VALIDATIONS.MAX_SIZE) {
@shubham1206agra you can download the large image [here](https://drive.google.com/file/d/1dcW-YtWnT4MjVuaF6ojj3zClRldQjxvc/view?usp=sharing)

2024-07-29 18:58 UTC, luacmartins commented
I'm running an adhoc build since the attachment flow can be a bit weird on the simulator.

2024-07-30 03:35 UTC, nkdengineer commented
Checking this now.

2024-07-30 03:50 UTC, nkdengineer commented
> 
 Screen.Recording.2024-07-29.at.9.50.30.PM.mov 
@nkdengineer This is giving weird result here.


I can reproduce this, checking to find the reason.

2024-07-30 05:13 UTC, nkdengineer commented
@shubham1206agra @luacmartins This bug only happens on Safari and I think this warning may be why. I'm finding a solution to fix this.

> Canvas area exceeds the maximum limit (width * height > 16777216).

<img width="996" alt="Screenshot 2024-07-30 at 12 11 30" src="https://github.com/user-attachments/assets/52080b6a-90b3-4da1-ad92-70812ff6355c">

2024-07-30 08:19 UTC, nkdengineer commented
@shubham1206agra What do you think if we only do this on safari mWeb?

2024-07-30 09:07 UTC, nkdengineer commented
@shubham1206agra What do you think about this message

cc @luacmartins 

<img width="363" alt="Screenshot 2024-07-30 at 16 05 03" src="https://github.com/user-attachments/assets/9a64bc7c-e5af-4467-b7dd-8be13208ef18">

2024-07-30 10:59 UTC, nkdengineer commented
@shubham1206agra I'm investigating to find a fix for this case.

2024-07-30 15:34 UTC, nkdengineer commented
@shubham1206agra The context is [here](https://pqina.nl/blog/canvas-area-exceeds-the-maximum-limit/). Because the canvas area limit on IOS Safari is `4096 * 4096` and `manipulateAsync` function uses the original width and height to create the canvas of the original image, this canvas becomes invalid and then the black image appears after resizing.

```
canvas.width = imageSource.naturalWidth;
canvas.height = imageSource.naturalHeight;
```

<img width="1205" alt="Screenshot 2024-07-30 at 22 32 53" src="https://github.com/user-attachments/assets/81f54362-766b-4955-80f5-83b1475297a0">


1. If we want to fix this, we need to implement it in `expo-image-manipulator` lib to divide the image into small canvases, get image data from the small canvases, and combine them into image data of the original image before resizing.

2. Display a warning as this comment https://github.com/Expensify/App/pull/45448#issuecomment-2257856584



cc @luacmartins

2024-07-30 16:32 UTC, luacmartins commented
Asked in [Slack](https://expensify.slack.com/archives/C04878MDF34/p1722357131043479) for someone familiar with `expo-image-manipulator` to comment here.

2024-08-01 14:42 UTC, BrtqKr commented
@luacmartins @nkdengineer 
Ok, so the diagnosis regarding the issue was correct - the files exceeding the limit were corrupted (the format signatures were correct tho), but...

It looks like [enforcing the canvas size within the limits before performing the operations](https://github.com/software-mansion-labs/expensify-app-fork/commit/c167b92de09130f7f52c225477ced98224fd0ec5) (on the image manipulator level) seems to be fixing the problem. It's a bit weird, because with those assumptions the canvas is smaller than the image being processed (for a brief moment), but the end result should be fulfilling our expectations. 

On the other hand, what should not be fulfilling our expectations is the processing time - I'd suggest at least adding the indicator that the image is being processed. Uploading images of that size is probably not a common case, but this might be slightly confusing. 

I'll try to send a PR during the week-end and discuss it in the image-manipulator repository directly, but for now that should be sufficient. 


https://github.com/user-attachments/assets/fff9ac11-f6cc-484d-bdfd-18c5ee2b062a

2024-08-01 19:11 UTC, luacmartins commented
Nice! Thanks for the investigation @BrtqKr! Looking forward to the PR!

2024-08-02 09:45 UTC, BrtqKr commented
@nkdengineer if you could apply this, it would be amazing. Let me know if you find anything related to this patch. If this gets merged before I discuss it with expo and the library gets released, I'll clean this patch and bump the version in a separate PR.

2024-08-02 09:47 UTC, nkdengineer commented
@BrtqKr I will add the patch in this PR soon.

2024-08-05 03:32 UTC, nkdengineer commented
@shubham1206agra Updated the patch for the resizing solution, I tested and it works well. Please help to test again, thanks.

2024-08-05 06:30 UTC, nkdengineer commented
@shubham1206agra I updated, I missed re-installing the lib before creating the patch.

2024-08-05 10:20 UTC, shubham1206agra approved these changes

2024-08-05 11:41 UTC, luacmartins approved these changes
LGTM

2024-08-05 11:42 UTC, merged

2024-08-05 11:55 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-08-06 04:27 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10259951896) to staging by https://github.com/luacmartins in version: 9.0.17-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-08-07 22:03 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10292258172) to production by https://github.com/marcaaron in version: 9.0.17-2 🚀

platform | result
---|---
🤖 android 🤖|failure ❌
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-08-08 04:53 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10292258172) to production by https://github.com/marcaaron in version: 9.0.17-2 🚀

platform | result
---|---
🤖 android 🤖|failure ❌
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-08-08 20:04 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10292258172) to production by https://github.com/marcaaron in version: 9.0.17-2 🚀

platform | result
---|---
🤖 android 🤖|failure ❌
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅