Fixing comment edits when cursor is in the middle
Expensify/App pull request #458
Opened 2020-09-10 22:44 UTC by chiragsalian

# Fixes
https://github.com/Expensify/ReactNativeChat/issues/457

# Tests
1. Write up a message. Click in the middle of the message. Type out something and confirm the cursor doesn't automatically move to the end.
1. Type out a really long message such that the input box handles multiple lines. Refresh and confirm the message remains and its multiline
1. Type out a message really fast and click send. Confirm it gets sent just fine and the input box is empty.
1. On the mobile app type out a message and confirm you can type quickly.
1. On the mobile app center your cursor in the middle of the text and type out and confirm its working normally.

2020-09-11 03:27 UTC, marcaaron requested changes

2020-09-11 23:58 UTC, AndrewGable submitted a review, later dismissed
Looks good and tests well!

2020-09-12 00:17 UTC, marcaaron submitted a review, later dismissed
LGTM!

2020-09-12 01:00 UTC, marcaaron approved these changes

2020-09-14 17:59 UTC, AndrewGable approved these changes

2020-09-14 17:59 UTC, merged