update copy for login
Expensify/App pull request #4644
Opened 2021-08-13 07:57 UTC by aman-atg

cc: @MonilBhavsar 
### Details
https://github.com/Expensify/App/issues/4111#issuecomment-884817325
https://github.com/Expensify/App/issues/4111#issuecomment-886869858

### Fixed Issues

$ #4111

### Tests || QA Steps
1. Go to newDot
2. Enter your email/phone : `{login}`
3. Press "Continue"
4. You will see `Not {login}? Go back.` below the button.
   - `Go back.` Will be on the next line if the `{login}` is too long
5. You will see "We've sent a magic sign in link to your email/phone number." above the button if you don't have an account already.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Android
- Please test on these two
- [ ] Desktop
- [ ] iOS

### Screenshots

#### Web

https://user-images.githubusercontent.com/28243942/129036130-7e7252ab-69f3-465a-8c42-b225c69fb76f.mp4

#### Mobile Web

https://user-images.githubusercontent.com/28243942/129036141-9122a4e9-d925-457d-a9be-159ce4b6de5f.mp4

#### Desktop

#### iOS

#### Android

https://user-images.githubusercontent.com/28243942/129036194-8820470b-0c47-44af-b322-77d8ddc73301.mp4

2021-08-19 23:26 UTC, NikkiWines requested changes
@aman-atg sorry for the delayed review here. One minor comment otherwise looks great + works well

2021-08-19 23:26 UTC, NikkiWines commented on src/pages/signin/ResendValidationForm.js
> +    credentials: PropTypes.shape({
Can you add `/** The credentials of the logged in person */` above so it matches the format in `src/pages/signin/ChangeExpensifyLoginLink.js`

2021-08-20 09:54 UTC, aman-atg commented
@NikkiWines, PR updated!

2021-08-23 11:08 UTC, aman-atg commented
Bump @NikkiWines

2021-08-23 17:56 UTC, NikkiWines approved these changes
👍

2021-08-23 17:56 UTC, merged

2021-08-23 17:57 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-08-30 17:38 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1183075988) to production by @roryabraham in version: 1.0.88-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2021-09-01 01:26 UTC, botify commented
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-08.  :confetti_ball: