Added tooltips to all Icon buttons
Expensify/App pull request #4661
Opened 2021-08-14 10:01 UTC by mananjadhav

@iwiznia Can you please review this?

### Details
Wrapped all TouchableOpacity + Icon components with Tooltip.

### Fixed Issues

$ 4499

### Tests
1. Verified tooltips for IOUModal, Search, ReportActionCompose, AttachmentView, VideoChat.
2. Verified Tooltips for Web and Desktop
3. Tested for no impact on Mobile Web, iOS and Android

### QA Steps

### Tested On

- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

<img width="165" alt="tooltip-icon-close-download png" src="https://user-images.githubusercontent.com/3069065/129442148-f7125e17-4960-407b-9710-f984289250ab.png">
<img width="122" alt="tooltip-icon-close-web" src="https://user-images.githubusercontent.com/3069065/129442151-dfaa2a42-0075-4e58-bdaa-fcb86061baed.png">
<img width="203" alt="tooltip-icon-emoji-web" src="https://user-images.githubusercontent.com/3069065/129442152-bd2aac77-a50d-4d15-94d7-92e964e27fee.png">
<img width="128" alt="tooltip-icon-pin-web" src="https://user-images.githubusercontent.com/3069065/129442153-1de688a7-a63c-446d-a5a6-d54cc82dc57b.png">
<img width="369" alt="tooltip-icon-search-web" src="https://user-images.githubusercontent.com/3069065/129442154-73edebdb-04bb-4ade-bd9e-489d42dce658.png">
<img width="104" alt="tooltip-icon-unpin-web" src="https://user-images.githubusercontent.com/3069065/129442156-e65a7bb8-45e3-47a3-9f86-d7515e55aedc.png">
<img width="187" alt="tooltip-icon-vc-web" src="https://user-images.githubusercontent.com/3069065/129442157-9164a16f-9a1f-4c81-aae7-4dd9c14fe348.png">

#### Mobile Web
NA

#### Desktop

<img width="125" alt="tooltip-icon-close-desktop" src="https://user-images.githubusercontent.com/3069065/129442286-960ec1e9-08a7-4643-8536-e788a7e60170.png">
<img width="289" alt="tooltip-icon-download-desktop" src="https://user-images.githubusercontent.com/3069065/129442288-e8c1278c-f08a-4f07-bb62-95052ea44dd4.png">
<img width="270" alt="tooltip-icon-emoji-desktop" src="https://user-images.githubusercontent.com/3069065/129442289-f656a7ea-4085-4641-90d5-648488df3373.png">
<img width="183" alt="tooltip-icon-pin-desktop" src="https://user-images.githubusercontent.com/3069065/129442290-0b3fadb6-eb91-41ec-a742-77a0857b9977.png">
<img width="426" alt="tooltip-icon-search-desktop" src="https://user-images.githubusercontent.com/3069065/129442291-43231615-d608-4748-adf6-49f36dfeec7c.png">
<img width="298" alt="tooltip-icon-unpin-desktop" src="https://user-images.githubusercontent.com/3069065/129442294-e108b36e-15f3-4e67-88fd-1c165525ee5f.png">
<img width="170" alt="tooltip-icon-vc-desktop" src="https://user-images.githubusercontent.com/3069065/129442295-a8055129-c392-4320-a7fc-98ddbd333151.png">

#### iOS
NA

#### Android
NA

2021-08-14 10:18 UTC, mananjadhav commented
@iwiznia PR raised.

Need help:
1. to confirm coverage. I'd search all `Icon` across the codebase and updated all relevant pressable icon
2. Translations in Spanish.
3. I haven't added Tooltips to the following buttons: 
       a. Main Send button in the Chat Input Box
       b. Green FAB on the LHN
       c. + button that opens up "Add attachment" option

Let me know if you feel tooltips are required for those too.

2021-08-16 11:25 UTC, iwiznia requested changes

2021-08-16 11:25 UTC, iwiznia commented on src/languages/es.js
> +        pin: 'Alfiler',
```suggestion
        pin: 'Anclar',
```

2021-08-16 11:25 UTC, iwiznia commented on src/languages/es.js
> +        back: 'De vuelta',
```suggestion
        back: 'Volver',
```

2021-08-16 11:25 UTC, iwiznia commented on src/languages/es.js
> +        unPin: 'Desprender',
```suggestion
        unPin: 'Desanclar',
```

2021-08-16 11:25 UTC, iwiznia commented on src/languages/es.js
> +        tooltip: 'Chat de video',
```suggestion
        tooltip: 'Videollamada',
```

2021-08-16 11:25 UTC, iwiznia commented
> I haven't added Tooltips to the following buttons:

Why not?

2021-08-16 11:28 UTC, iwiznia commented
Oh, also can you make sure to test in the other platforms? Even if it is to check there are no regressions and buttons look/work properly

2021-08-16 11:58 UTC, mananjadhav commented
I'll update the translation changes.

> Why not?
One of them was a primary action. Other is a menu. I can add. Can you help with the translations for these two buttons ?
![image](https://user-images.githubusercontent.com/3069065/129559960-96e73d6c-1bef-42f5-afaf-265c6f06956a.png)


>  Oh, also can you make sure to test in the other platforms? Even if it is to check there are no regressions and buttons look/work properly
I've checked the other platforms - Mobile Web, iOS, and Android.

2021-08-16 12:09 UTC, iwiznia commented
> One of them was a primary action. Other is a menu. I can add. Can you help with the translations for these two buttons ?

Sure. Let me tag the @Expensify/marketing team so they can check the copy (all new copy is [in this file](https://github.com/Expensify/App/pull/4661/files#diff-22037c1e4dbdea8803b450b3fce06e6c475762a31ecf84b34dc264ba0e443637R39), they are the green lines) and give us copy for the tooltips of these buttons:
a. Main Send button in the Chat Input Box
b. Green FAB on the LHN
c. + button that opens up "Add attachment" option

I can then translate the new ones for you.

2021-08-16 12:39 UTC, mananjadhav commented
@iwiznia One quick question, what are your thoughts on opening the FAB menu and the + icon menu on hover? rather than adding Tooltip?

2021-08-16 12:46 UTC, iwiznia commented
I am personally not quite fond of things that open on hover. In any case that's just one opinion, you can propose and discuss changes like that one in the slack channel.

2021-08-16 13:07 UTC, mananjadhav commented
PR Updated with suggested translations and tooltip for send button.

2021-08-16 13:10 UTC, iwiznia commented
b. Green FAB on the LHN
c. + button that opens up "Add attachment" option

We are still waiting for those, right?

2021-08-16 14:02 UTC, mananjadhav commented
Yes waiting.

2021-08-16 14:41 UTC, marklouisdeshaun commented on src/languages/es.js
> +        pin: 'Anclar',
I would suggest using `Fijar`. This is the terminology used in popular apps like WhatsApp and Twitter.

2021-08-16 14:42 UTC, marklouisdeshaun commented on src/languages/es.js
> +        unPin: 'Desanclar',
I would suggest using `Desfijar`. This is the terminology used in popular apps like WhatsApp and Twitter.

2021-08-16 15:04 UTC, mananjadhav commented
@marklouisdeshaun Thanks, Mark. Will update. Can you help with the copy of the other two buttons? Floating Action Button in the sidebar and + button to open Add Attachments in the chat?

<img width="244" alt="Screenshot 2021-08-16 at 5 25 56 PM" src="https://user-images.githubusercontent.com/3069065/129585484-d52e4540-1ce2-4f7a-b54b-dd0610de1060.png">

2021-08-17 00:13 UTC, aldo-expensify reviewed
I tested this locally and seemed to work fine.
I agree with the proposed changes on the spanish translations.

2021-08-17 12:45 UTC, mananjadhav commented
@iwiznia @marklouisdeshaun Left with the copy & translation for the + action on ReportActionCompose.  Can you help with that to close it at the earliest?

2021-08-17 12:49 UTC, iwiznia submitted a review, later dismissed

2021-08-17 12:57 UTC, mananjadhav commented
I've set the labels as `Actions` and `Acción` right now.

2021-08-17 13:05 UTC, iwiznia submitted a review, later dismissed

2021-08-19 10:41 UTC, mananjadhav commented
> @iwiznia @marklouisdeshaun Left with the copy & translation for the + action on ReportActionCompose. Can you help with that to close it at the earliest?

@marklouisdeshaun Can you help me with the copy of this button? So that this can be moved to closure?

2021-08-24 14:21 UTC, iwiznia approved these changes

2021-08-24 14:21 UTC, merged

2021-08-24 14:22 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-08-30 17:37 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1183075988) to production by @roryabraham in version: 1.0.88-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2021-09-01 01:26 UTC, botify commented
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-08.  :confetti_ball:

2023-01-23 17:05 UTC, eVoloshchak commented
Leaving a note here that the PR has caused a regression: https://github.com/Expensify/App/issues/14043
The 'close' and 'download' tooltips are slightly misaligned 
<img width="250" alt="image" src="https://user-images.githubusercontent.com/9059945/214103122-d4b7244e-0dd0-42ab-bd7f-4b3942e1a76e.png">