Fix: different behavior when using app and device back button in selection mode
Expensify/App pull request #46937
Opened 2024-08-07 03:21 UTC by nkdengineer

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/45896
PROPOSAL: https://github.com/Expensify/App/issues/45896#issuecomment-2262103584

### Tests

- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-08-14 13:53 UTC, eVoloshchak commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->

</details>

<detail [...]

2024-08-14 14:41 UTC, eVoloshchak reviewed
@nkdengineer, looking good on native platforms, however, there's still a behavior mismatch on web/mWeb

- If you press hardware back button (or back button in browser), the selection isn't dismissed, you're just navigated back
`beforeRemove` should be of help here

- Android: mWeb Chrome screen recording is missing

2024-08-19 08:21 UTC, nkdengineer commented
I'll update soon

2024-08-21 03:15 UTC, nkdengineer commented
@eVoloshchak I tried with `beforeRemove` but this event doesn't trigger any time we click on the back button of the browser. Ref [here](https://reactnavigation.org/docs/preventing-going-back/#limitations). I also tried with `beforeunload` but this didn't work.

2024-08-26 04:26 UTC, nkdengineer commented
@eVoloshchak What do you think about my comment above?

2024-08-27 13:20 UTC, eVoloshchak commented
>  I tried with beforeRemove but this event doesn't trigger any time we click on the back button of the browser

@nkdengineer, it does according to my testing, but it isn't called when shouldUseNarrowLayout=true (which poses a problem on web and mWeb)


https://github.com/user-attachments/assets/c789ce4f-e5c5-4b0b-be90-ae4a82767d6d

2024-08-28 05:18 UTC, nkdengineer commented
> @nkdengineer, it does according to my testing, but it isn't called when shouldUseNarrowLayout=true (which poses a problem on web and mWeb)

@eVoloshchak Yes this is the problem.

2024-09-02 15:12 UTC, eVoloshchak commented
@nkdengineer, that means that, at the very least, we're able to make this work on desktop web (since there `beforeRemove` works as expected)
But ideally, we need to get to the bottom of "why does it not fire correctly if `shouldUseNarrowLayout` is true)

2024-09-09 02:58 UTC, nkdengineer commented
Still investigating.

2024-09-16 09:16 UTC, nkdengineer commented
Still find the RCA of the bug above.

2024-09-23 07:12 UTC, nkdengineer commented
Same as above.

2024-09-25 09:13 UTC, nkdengineer commented
@eVoloshchak I checked again and `beforeRemove` also doesn't trigger when we open the search page from the chat on large screen. It's only triggered when we refresh the search page.

https://github.com/user-attachments/assets/cdab643e-40d3-46ea-811f-f272c1ad92ad

2024-10-02 07:47 UTC, nkdengineer commented
@eVoloshchak I tried with the listener on `Search` page and it's the same behavior with you. I am investigating the RCA again.

2024-10-02 09:32 UTC, nkdengineer commented
@eVoloshchak I fixed this bug now. Please help to check again.

2024-10-07 04:14 UTC, nkdengineer commented
@eVoloshchak Friendly bump.

2024-10-10 14:44 UTC, eVoloshchak reviewed
@nkdengineer, awesome job!
However, there is still a bug: this works correctly for a hardware/browser back button for the first time, but breaks when you do the same for the second time

1. Go to Search
2. Long press on the expense
3. Select some expenses
4. Press the browser back button
5. Selectin is dismissed (correct behavior)
6. Long press on the expense once again
7. Select some expenses
8. Press the browser back button
9. Notice you're navigated back (incorrect behavior)

https://github.com/user-attachments/assets/1dbba82f-70e9-48b5-b8c2-ef441f43b548

2024-10-16 10:05 UTC, nkdengineer commented
Still investigate.

2024-10-29 17:22 UTC, nkdengineer commented
@eVoloshchak The problem is we prevented navigating to the previous page but you can see the URL was still changed to the previous page then on the second time it's going to the chrome page.

2024-10-29 17:23 UTC, nkdengineer commented
It's the default behavior of the back button browser.

2024-11-06 03:50 UTC, nkdengineer commented
@eVoloshchak any update here

2024-11-10 19:31 UTC, eVoloshchak commented
> It's the default behavior of the back button browser.

Yeah, you're right, it can observed on many other pages too 
In that case, could you resolve the conflicts please?

2024-11-11 10:55 UTC, nkdengineer commented
@eVoloshchak So we're good to remove the implementation for web, right?

2024-11-12 16:43 UTC, eVoloshchak commented
> So we're good to remove the implementation for web

@nkdengineer, that is correct

2024-11-12 16:50 UTC, nkdengineer commented
> @nkdengineer, that is correct



@eVoloshchak I updated, please help to check again.

2024-11-12 20:23 UTC, eVoloshchak commented
Testing this one more time on mWeb and native Android and it's not ideal how the behavior of back button is different

- @nkdengineer, please roll back to the implementation for web, apologies for the confusion on this one. The bug with it back button not working correctly the second time is out of scope of this PR 

- make sure that we're unsubscribing from `beforeRemove` event

2024-11-26 09:50 UTC, nkdengineer commented
@eVoloshchak Friendly bump.

2024-12-10 07:57 UTC, nkdengineer commented
@eVoloshchak Friendly bump.

2024-12-19 08:38 UTC, nkdengineer commented
> @eVoloshchak But at the first time we do that, the URL is changed to the previous page but the screen is still the search page, it is also a bug. I think the best way is do nothing in web/mweb.

@Julesssss Currently web/mweb cannot prevent the default behavior when clicking on the back button browser. Do you agree that we can only fix this bug on Native?

2024-12-20 11:52 UTC, Julesssss commented
> @Julesssss Currently web/mweb cannot prevent the default behavior when clicking on the back button browser. Do you agree that we can only fix this bug on Native?

Yeah I agree with native only. No need to worry about web matching our desired mobile behaviour here.

2024-12-23 04:52 UTC, nkdengineer commented
@eVoloshchak We're good to process now.

2024-12-29 17:46 UTC, eVoloshchak requested changes

2024-12-29 17:46 UTC, eVoloshchak commented on src/pages/Search/useHandleBackButton/index.android.ts
> +export default function useHandleBackButton(callback: UseHandleBackButtonCallback) {
Can we instead extend the logic in [src/libs/Navigation/setupCustomAndroidBackHandler](https://github.com/Expensify/App/tree/76c3a616062d0ba04c90da085a9ab598c69aaef5/src/libs/Navigation/setupCustomAndroidBackHandler)?

2024-12-29 17:46 UTC, eVoloshchak commented on src/components/Search/SearchContext.tsx
> +        .map((item) => ({reportID: item.reportID, action: item.action ?? CONST.SEARCH.ACTION_TYPES.VIEW, total: item.total ?? CONST.DEFAULT_NUMBER_ID, policyID: item.policyID ?? ''}));
Linter error

2025-01-28 20:36 UTC, eVoloshchak commented on src/libs/PolicyUtils.ts
> +function hasVBBA(policyID: string | undefined) {
This looks like an accidental change?

Tests well on all platforms otherwise

2025-02-04 08:39 UTC, eVoloshchak approved these changes
LGTM!

2025-02-04 17:04 UTC, Julesssss approved these changes
Working as expected 👍

2025-02-04 17:05 UTC, merged

2025-02-04 17:16 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2025-06-08 22:24 UTC, ahmedGaber93 commented on src/components/Search/index.tsx
> +    }, [selectedTransactions, selectionMode?.isEnabled, shouldTurnOffSelectionMode]);
Coming from https://github.com/Expensify/App/issues/61326, this `useEffect` still able to run even though "search screen" is under the stack and not focused, and we fixed it here https://github.com/Expensify/App/pull/62332