Handle if push notification doesn't have a payload
Expensify/App pull request #47123
Opened 2024-08-09 00:00 UTC by jp928

### Details
If a push notification was send without a payload, the App would crash.

### Fixed Issues
$ https://github.com/Expensify/App/issues/46820
PROPOSAL: $ https://github.com/Expensify/App/issues/46820#issuecomment-2272700910

### Tests
- [x] Verify that no errors appear in the JS console

### Offline tests
1. prepare a text with following contents:
```
{
  "Simulator Target Bundle": "com.expensify.chat.dev",
  "aps": {
    "alert": "Testing",
    "sound": "default",
    "badge": 1,
  },
}
```

2. Run the project in a simulator with `npm run ios`
3. Run the following command to see if the App still crash
```
xcrun simctl push  {simulator_uuid} com.expensify.chat.dev {path_to_the_file_in_step1}
```

### QA Steps
1. Send push notification without payload.
2. Check if the App still crashes.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [x] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summa [...]

2024-08-09 13:19 UTC, s77rt commented
@jp928 Please do not raise PRs until assigned in the issue

2024-08-22 19:40 UTC, s77rt requested changes
It seems we have a type error, `pushPayload.extras.payload` is shown to have type `JsonValue` but it's not always the case as it can be `undefined`. I think we should fix this [upstream](https://github.com/urbanairship/react-native-airship/blob/main/src/types.ts). Then we can just fix the ts errors which will prevent the crash.


This assertion is also false
```ts
const data = payload as PushNotificationData
```

2024-08-23 04:12 UTC, jp928 commented
@arosiclair @s77rt  Updated with respecting comments.

2024-08-23 04:57 UTC, s77rt requested changes

2024-08-23 04:57 UTC, s77rt commented on src/types/modules/react-native-airship.d.ts
Revert. Please raise a PR upstream fixing the ts for `JsonObject`

```ts
export type JsonObject = {
    [key: string]: JsonValue | undefined;
};
```

2024-08-23 04:57 UTC, s77rt commented on src/libs/Notification/PushNotification/shouldShowPushNotification.ts
> -    if (!data.reportID) {
Revert. This should be changed to:

```ts
const data = payload ? payload as PushNotificationData : undefined;
```

2024-08-23 10:56 UTC, s77rt commented
@jp928 Did you raise a PR? (https://github.com/Expensify/App/pull/47123#discussion_r1728355830)

2024-08-23 11:29 UTC, jp928 commented
> @jp928 Did you raise a PR? (https://github.com/Expensify/App/pull/47123#discussion_r1728355830)

Sry. PR to react-native-airship?

2024-08-23 11:53 UTC, jp928 commented
> @jp928 Did you raise a PR? ([#47123 (comment)](https://github.com/Expensify/App/pull/47123#discussion_r1728355830))

$ https://github.com/urbanairship/react-native-airship/pull/583

2024-08-23 13:24 UTC, s77rt commented
@jp928 Can you please create a patch so we can have the type corrected without waiting for the upstream PR to be merged

2024-08-23 18:24 UTC, s77rt requested changes

2024-08-23 18:24 UTC, s77rt commented on patches/@ua+react-native-airship+17.2.1.patch
> ++++ b/node_modules/@ua/react-native-airship/src/types.ts
This should be applied to `node_modules/@ua/react-native-airship/lib/typescript/types.d.ts`

2024-08-23 18:24 UTC, s77rt commented on src/libs/Notification/PushNotification/shouldShowPushNotification.ts
> +    let payload = pushPayload.extras?.payload;
Revert

2024-08-23 18:24 UTC, s77rt commented on src/libs/Notification/PushNotification/shouldShowPushNotification.ts
> +            payload = JSON.parse(payload) as string;
```suggestion
            payload = JSON.parse(payload);
```

2024-08-23 18:24 UTC, s77rt commented on src/libs/Notification/PushNotification/shouldShowPushNotification.ts
> +            payload = {};
```suggestion
            payload = undefined;
```

2024-08-23 20:07 UTC, jp928 commented on src/libs/Notification/PushNotification/shouldShowPushNotification.ts
> +            payload = JSON.parse(payload) as string;
without a cast, my editor shows error.
<img width="881" alt="Screenshot 2024-08-24 at 6 06 23 AM" src="https://github.com/user-attachments/assets/53a3a107-5970-458b-beb0-50dc2d9d7829">

2024-08-23 20:21 UTC, s77rt requested changes
Can you please apply same solution for other affected places (in editor search for: `as PushNotificationData`)

2024-08-23 20:42 UTC, jp928 commented
> Can you please apply same solution for other affected places (in editor search for: `as PushNotificationData`)

Thx. Just apply same cast as other places.

2024-08-23 20:48 UTC, arosiclair commented on patches/@ua+react-native-airship+17.2.1.patch
Is the airship package getting updated with this fix soon? If so, can we just use the new version instead of adding this patch?

2024-08-23 20:54 UTC, s77rt commented
@jp928

> Just apply same cast as other places.

This is not what I meant. Actually the new cast is the correct one. What I meant is that in other places the payload can be undefined and we are still accessing fields on undefined e.g.  

https://github.com/Expensify/App/blob/f5e63543cbdea0ffcc0e5bf201f8f2e9645582c6/src/libs/Notification/clearReportNotifications/index.native.ts#L8-L18

2024-08-23 21:29 UTC, rlepinski commented
Airship release - https://github.com/urbanairship/react-native-airship/releases/tag/19.2.1

2024-08-24 02:20 UTC, s77rt requested changes

2024-08-24 02:20 UTC, s77rt commented on src/libs/Notification/PushNotification/index.native.ts
> +            payload = JSON.parse(payload) as string;
```suggestion
            payload = JSON.parse(payload) as JsonObject;
```

do same in other places

2024-08-24 02:20 UTC, s77rt commented on src/libs/Notification/clearReportNotifications/index.native.ts
> +        reportID: String(data?.reportID),
This could return `'undefined'` (a string) which is unwanted it should be `undefined` instead.

2024-08-24 05:39 UTC, s77rt requested changes

2024-08-24 05:39 UTC, s77rt commented on src/libs/Notification/clearReportNotifications/index.native.ts
> +        reportID: data?.reportID ? String(data.reportID) : undefined,
```suggestion
        reportID: data?.reportID !== undefined ? String(data.reportID) : undefined,
```
This is needed to make it work with `reportID=0`

2024-08-24 19:10 UTC, s77rt requested changes

2024-08-24 19:10 UTC, s77rt commented on src/libs/Notification/PushNotification/shouldShowPushNotification.ts
> +    if (!data?.reportID) {
```suggestion
    if (data?.reportID === undefined) {
```
To account for `reportID=0` (same as in other places)

2024-08-24 19:12 UTC, s77rt commented
@jp928 The QA steps are not clear (sending a notification without payload). Can you instead use the steps from the reported issue?

2024-08-24 19:22 UTC, s77rt commented
@jp928 Did you find a way to send a notification to the Android Emulator?

2024-08-24 22:01 UTC, jp928 commented
> @jp928 Did you find a way to send a notification to the Android Emulator?

Unfortunately no.

2024-08-25 04:09 UTC, s77rt commented
@jp928  In QA Steps add a third step to verify that the app didn't crash

2024-08-25 17:28 UTC, s77rt commented
## Reviewer Checklist

- [X] I have verified the author checklist is complete (all boxes are checked off).
- [X] I verified the correct issue is linked in the `### Fixed Issues` section above
- [X] I verified testing steps are clear and they cover the changes made in this PR
    - [X] I verified the steps for local testing are in the `Tests` section
    - [X] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [X] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [X] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I verified tests pass on **all platforms** & I tested again on:
    - [X] Android: Native
    - [X] Android: mWeb Chrome
    - [X] iOS: Native
    - [X] iOS: mWeb Safari
    - [X] MacOS: Chrome / Safari
    - [X] MacOS: Desktop
- [X] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [X] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [X] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [X] I verified that all the inputs inside a form are aligned with each other.
    - [X] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [X] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->

</details>

<detail [...]

2024-08-25 17:29 UTC, s77rt approved these changes

2024-08-26 12:35 UTC, arosiclair requested changes

2024-08-26 12:35 UTC, arosiclair commented on src/libs/Notification/PushNotification/shouldShowPushNotification.ts
> +        }
We repeated this payload parsing logic in a few places. Can we move this to a helper function `parsePushNotificationPayload` to DRY this up? You can just put that in the [PushNotification lib](https://github.com/Expensify/App/blob/5a2602c441170093e99850e2194808218b0aa838/src/libs/Notification/PushNotification/index.native.ts) if it doesn't cause any dependency cycles.

2024-08-26 15:03 UTC, tgolen approved these changes, later dismissed
+1 to DRY up the parsing.

2024-08-26 19:46 UTC, s77rt requested changes

2024-08-26 19:46 UTC, s77rt commented on src/libs/Notification/PushNotification/shouldShowPushNotification.ts
> +    Log.info('[PushNotification] push notification resceived', false, {pushPayload});
```suggestion
    Log.info('[PushNotification] push notification received', false, {pushPayload});
```

2024-08-26 20:05 UTC, s77rt commented
@jp928 Looks we have conflicts

2024-08-26 20:47 UTC, arosiclair approved these changes

2024-08-26 20:48 UTC, merged

2024-08-26 20:52 UTC, s77rt commented
@jp928 For future PRs please avoid force-pushing, it causes review progress to be lost and can't use the "Show changes since your last review" option. Instead merge `main`.

2024-08-26 21:07 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-08-26 23:18 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10568369200) to staging by https://github.com/arosiclair in version: 9.0.25-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅

2024-08-27 00:08 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10568369200) to staging by https://github.com/arosiclair in version: 9.0.25-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌
🕸 web 🕸|success ✅