fix: optimistically build next step after resolving violation
Expensify/App pull request #47543
Opened 2024-08-16 05:42 UTC by dominictb

### Details

Build `fix the issue(s)` next step optimistically when the transaction has violations.

### Fixed Issues

$ https://github.com/Expensify/App/issues/46914
PROPOSAL: https://github.com/Expensify/App/issues/46914#issuecomment-2273874988

### Tests

1. Create a "Control" workspace
2. Set the workspace currency to USD
3. Enable expense violation on OD (Settings > Workspaces > Choose the workspace > Expenses > Enable "Expense Violations")
4. On New Dot, Go to workspace settings > Categories > Settings
5. Enable "Members must categorize all expenses"
6. Submit an expense without a category and with an amount greater than the "Receipt Required Amount"
7. You will get a "Waiting for to fix the issue(s)" report next step
8. Go offline
9. Add a category to the expense
10. Change the expense amount to a value less than the "Receipt Required Amount"
11. Verify the next step message should update from "Waiting for to fix the issue(s)" to the corresponding next step ("Waiting for to submit expense(s)" for example).
12. Go online
13. Verify the next step does not revert to "Waiting for to fix the issue(s)"

- [x] Verify that no errors appear in the JS console

### Offline tests

See Tests

### QA Steps

See Tests

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged  [...]

2024-08-23 19:08 UTC, dangrous commented
Okay so this is a bit of a nightmare from the backend side, since we build the report next step dynamically when we call `OpenReport`. We can send an onyx update with a new next step to the front end, BUT in order for it to work we'd need to check - **in EVERY command that changes a request** - if there was a violation before, and, if so, check if there isn't one now, and then build the onyx update for the next step.

I'm not actually sure what the best option for this is. Do you have any thoughts @vit?

2024-08-27 14:43 UTC, dangrous commented
> Okay so this is a bit of a nightmare from the backend side, since we build the report next step dynamically when we call `OpenReport`. We can send an onyx update with a new next step to the front end, BUT in order for it to work we'd need to check - **in EVERY command that changes a request** - if there was a violation before, and, if so, check if there isn't one now, and then build the onyx update for the next step.
> 
> I'm not actually sure what the best option for this is. Do you have any thoughts `@vit`?

Oops I mentioned the wrong person whoops! Let's try @mountiny

2024-08-27 22:23 UTC, mountiny commented
@dangrous fun, do we optimistically clear the violations? We could update the next step when there are no violations left.

Otherwise, I agree that we might have to make a change to a bunch of the API commands. We can add an optional parameter that would be true only if the local report's next steps say to fix issues. In that case, the API command would also re-compute and return the report's next steps.

2024-08-28 16:46 UTC, dangrous commented
So yeah, we're clearing the violations optimistically here. @dominictb do you want to take a shot at seeing if we can call OpenReport here, or some other way to re-pull the next steps from the backend?

That seems less intrusive than the backend solution, but I can work on that over time if we feel like it's best.

2024-08-30 15:47 UTC, dangrous commented
thanks! happy to implement something on the backend too if we feel like that's the best solution, whether that's the checking every update transaction api command (hopefully not haha) or another option!

2024-09-02 11:28 UTC, mountiny commented
I am mildly afraid the right solution is to update all the commands to recompute the next steps, but also this should wait for the auth migration @dangrous what do you think? Anything else is a hack/ workaround

2024-09-06 15:22 UTC, mountiny commented
There is also EditMoneyRequest and UpdateTransaction but those are I gues not called from the NewDot so I think it might be ok as we do not need to push these

2024-09-06 17:24 UTC, dangrous commented
see comment here - https://github.com/Expensify/App/issues/46914#issuecomment-2334507966 - putting this on hold so that the backend can be synced up before pushing this.

2024-09-17 18:15 UTC, dangrous commented
Yep confirmed! Thanks for updating the title @mountiny

2024-09-30 15:00 UTC, dangrous commented
Still in the design process, hopefully in the next week or so! Sorry for the delay

2025-02-13 19:20 UTC, dangrous commented
let me know when this is ready for a look @rayane-d - thank you!

2025-02-23 16:59 UTC, rayane-d approved these changes
LGTM and tests well 👍

2025-02-24 23:05 UTC, dangrous requested changes
Let's update that jsdoc but otherwise looks good!

2025-02-24 23:05 UTC, dangrous commented on src/libs/NextStepUtils.ts
>   */
yes please, thanks!

2025-02-26 15:58 UTC, dangrous commented
bump for adding the param to the doc, then we're good to go!

2025-02-26 20:05 UTC, rayane-d approved these changes

2025-02-27 16:27 UTC, dangrous approved these changes

2025-02-27 16:28 UTC, merged

2025-02-27 16:38 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.