Make download links cross-platform
Expensify/App pull request #476
Opened 2020-09-11 19:24 UTC by roryabraham

### Fixes
https://github.com/Expensify/ReactNativeChat/issues/287

### Tests
1. Open the app on web, and verify that you see links for Desktop, iOS, and Android in the bottom of the left-hand-nav.
2. Open the app on desktop, and verify that you see links for Web, iOS, and Android in the bottom of the left-hand-nav.
3. Open the app on iOS, and verify that you see only one link in the bottom of the left-hand-nav that says "View on web" (added a couple words to fill space when it's the only link).

2020-09-23 18:50 UTC, tgolen requested changes

2020-09-23 20:08 UTC, tgolen requested changes

2020-09-23 20:21 UTC, tgolen approved these changes
Thanks!

2020-09-24 05:30 UTC, marcaaron approved these changes

2020-09-24 05:30 UTC, merged