Refactor the componentDidUpdate method for ReportActionCompose
Expensify/App pull request #4768
Opened 2021-08-20 17:51 UTC by mountiny

### Details

To resolve a StagingDeployBlocker, we have introduced some changes which need some refactoring. How to refactor has been discussed and decided in [this thread here](https://github.com/Expensify/App/pull/4761#discussion_r693077028). Look there for more details.

### Fixed Issues

❌ 

### Tests

Just repeat the `action performed` steps from this issue https://github.com/Expensify/App/issues/4756 and make sure it all works as expected.

### QA Steps

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-08-20 18:10 UTC, mountiny commented
@marcaaron My theory based on what I have observed when testing it is that the `reportID` is fetched from `route` [here](https://github.com/Expensify/App/blob/5acd2363000993f5bc946114adf83ef099e870a0/src/pages/home/ReportScreen.js#L155) and passed down to the `ReportActionCompose`. However, the `report` which holds the comment we need is not updated at that same time as the route changes. In console I could see ~2-3 calls of `componentDidUpdate` in `ReportActionCompose` with the previous `report` while the `reportID` has already been updated.

Isn't it that the `reportID` fetched from `route` is from the `Navigation` whereas report is from Onyx which can take slightly longer to switch?

2021-08-23 18:53 UTC, marcaaron commented
>Isn't it that the reportID fetched from route is from the Navigation whereas report is from Onyx which can take slightly longer to switch?

Yes that makes sense to me. It should be like 1 tick behind because Onyx is asynchronous. Is that what you're asking?

2021-08-23 18:54 UTC, marcaaron requested changes

2021-08-23 18:54 UTC, marcaaron commented on src/pages/home/report/ReportActionCompose.js
> +        if (reportChanged) {
This should use an early return like

```js
if (!reportChanged) {
    return;
}

this.updateComment(this.props.comment);
```

2021-08-23 18:55 UTC, marcaaron commented on src/pages/home/report/ReportActionCompose.js
> +        if (reportChanged) {
Also `reportChanged` does not need a variable just put the comparison into the if case?

2021-08-25 22:09 UTC, bondydaa approved these changes

2021-08-30 19:43 UTC, marcaaron approved these changes

2021-08-30 19:43 UTC, merged

2021-08-30 19:44 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-08-31 00:26 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1184237205) to staging by @marcaaron in version: 1.0.89-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|skipped 🚫 
🖥 desktop 🖥|skipped 🚫
🍎 iOS 🍎|skipped 🚫 
🕸 web 🕸|skipped 🚫

2021-08-31 15:30 UTC, isagoico commented
@mountiny @marcaaron Are we good to check this PR off the list? (I'm guessing it's NoQA but wanted to double check)

2021-09-01 00:24 UTC, roryabraham commented
@isagoico I filled in the QA steps here. Can you please perform QA on this?

2021-09-01 00:36 UTC, isagoico commented
Just tested it and it was a pass 🎉 checking it off.

2021-09-01 01:42 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1188395063) to production by @roryabraham in version: 1.0.90-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅