Fix MarkerBadge Count
Expensify/App pull request #4773
Opened 2021-08-20 23:34 UTC by parasharrajat

### Details

### Fixed Issues

$ #4669 

### Tests QA Steps

1. Open any conversation in newDot.
2. Scroll back in the history to see the new Markerbadge when new messages are received.
3. Send a new message from another device to the correct chat from the other user.
4. See that the new Marker badge is shown.
5. Now don't yet interact with the app or marker yet.
6. Send another message from the other device.
7. Observe that count.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

https://user-images.githubusercontent.com/24370807/130302691-6a252ee1-5a08-4a43-bb82-3af9e0f1ec03.mp4

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-08-23 21:21 UTC, roryabraham requested changes

2021-08-23 21:21 UTC, roryabraham commented on src/pages/home/report/ReportActionsView.js
> +            unreadActionCount: this.props.report.unreadActionCount,
I don't think it's great that this state variable shadows the name of the prop. Instead, we should call it `localUnreadActionCount` or something. And then `updateUnreadMessageCount` would be `updateLocalUnreadActionCount`

2021-08-23 22:44 UTC, parasharrajat commented
Updated

2021-08-24 04:07 UTC, parasharrajat commented
@roryabraham I think this is ready to roll.

2021-08-24 04:09 UTC, roryabraham approved these changes
Looks good, thanks @parasharrajat 👏

2021-08-24 04:10 UTC, merged

2021-08-24 04:10 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-08-30 17:37 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1183075988) to production by @roryabraham in version: 1.0.88-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2021-09-01 01:26 UTC, botify commented
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-08.  :confetti_ball: