Remove copilot and change access level
Expensify/App pull request #47984
Opened 2024-08-26 04:32 UTC by rushatgabhane

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/46921
$ https://github.com/Expensify/App/issues/46925
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-09-23 19:08 UTC, dangrous commented
Posted on the issue too but for clarity - Backend is ready! UpdateDelegateRole now exists.

Still working on those other changes (error handling, and personal details for delegated access) but that shouldn't block this.

2024-09-24 11:23 UTC, rushatgabhane commented
thank you! let me update and test this PR

2024-09-25 15:50 UTC, dangrous commented
how are we looking on this one? Would love to get this settled in the next day or so!

2024-09-27 16:54 UTC, dangrous commented
Bumping on this - thanks! Can we get this merged on Monday? It's the last big piece we have!

2024-09-29 07:20 UTC, rushatgabhane commented
PR is ready for a review 
cc: @situchan

2024-09-30 06:16 UTC, situchan commented
> Hey @situchan , I would be reviewing this PR because it belongs to the co-pilot project, thanks :)

Sure. Can you share link to that discussion (you were assigned to this project) though?

2024-09-30 09:21 UTC, allgandalf reviewed
Overall seems good to me, only a few comments, I will begin testing now

2024-09-30 09:47 UTC, allgandalf requested changes
Functionality wise this LGTM,  Lets work on the bugs and get this one merged ASAP 🚀

2024-09-30 16:28 UTC, rushatgabhane commented on src/languages/es.ts
> +        removeCopilot: 'Eliminar copiloto',
yes

2024-09-30 16:29 UTC, rushatgabhane commented on src/libs/actions/Delegate.ts
> +    }
makes it easier. we can use optional chaining

2024-09-30 16:30 UTC, rushatgabhane commented on src/pages/settings/Security/AddDelegate/UpdateDelegateRole/ValidateCodeForm/index.android.tsx
> +import React, {forwardRef} from 'react';
yeah, android has different autocomplete prop

2024-09-30 16:32 UTC, rushatgabhane commented
> Bug: The popover icons are missing the green color

@allgandalf i think it is correct. im reusing the component so the styles are same in other popovers too.

@Expensify/design could you please confirm if this design for popover color and icon fill is correct


https://github.com/user-attachments/assets/16dc2488-555d-4c52-8e53-02d3f7ce2cbe

2024-09-30 16:38 UTC, rushatgabhane commented
@allgandalf all fixed

2024-09-30 17:04 UTC, dannymcclain commented
>could you please confirm if this design for popover color and icon fill is correct

Yup! Looks good 👍

2024-10-01 17:21 UTC, dangrous commented
Got some conflicts now, sounds like we're almost there though! Are we on track to final review/merge today or tomorrow?

2024-10-02 08:22 UTC, rushatgabhane commented
@allgandalf all yours

2024-10-07 01:58 UTC, rushatgabhane commented
hmmm, tried Modal.close but it didn't work

2024-10-08 16:25 UTC, dangrous commented
How's the investigation going/

2024-10-09 13:26 UTC, allgandalf approved these changes
Lets merge this 🚀

2024-10-10 14:53 UTC, dangrous commented
Awesome! Thanks for sussing that out

2024-10-11 09:52 UTC, allgandalf approved these changes
Tested on iOS native, works great

2024-10-11 14:35 UTC, dangrous approved these changes
Okay let's do it! I found a very edge case bug where the popover shows up in a weird place if you have changed your screen size on web since loading the page / opening it last, but we have a number of edge case bugs that exist about changing screen size so I don't think it's a blocker, not really a thing we specifically support.

Thank you both for all your hard work on this!

I'm going to merge, and let's just keep an eye out for any additional bugs

2024-10-11 14:35 UTC, merged

2024-10-11 14:46 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-12-29 20:05 UTC, alitoshmatov commented on src/pages/settings/Security/AddDelegate/UpdateDelegateRole/UpdateDelegateRolePage.tsx
> +                    setCurrentRole(option.value);
When the option is selected user is required to authenticate using magic code, which means this option is not selected yet. Thus when user just goes back without authenticating this option will be selected even though user did not complete required steps. https://github.com/Expensify/App/pull/53677/files

2025-11-19 16:25 UTC, FitseTLT commented on src/libs/actions/Delegate.ts
> +                                  pendingFields: {role: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE},
We should have cleared pending fields on `failureData` as the above code caused https://github.com/Expensify/App/issues/72381