feat: add labels to bottom tab bar
Expensify/App pull request #48003
Opened 2024-08-26 14:07 UTC by BhuvaneshPatil

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/47339
PROPOSAL: https://github.com/Expensify/App/issues/47339#issuecomment-2286559311

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-08-26 14:12 UTC, BhuvaneshPatil commented
Android Browser - 


<img width="418" alt="Screenshot 2024-08-26 at 7 30 27 PM" src="https://github.com/user-attachments/assets/739b3c45-8a99-4021-bb69-df21ecda6a8d">


<img width="393" alt="Screenshot 2024-08-26 at 7 30 21 PM" src="https://github.com/user-attachments/assets/fc5a6695-bafd-4624-bbac-c852fb247b49">


<img width="460" alt="Screenshot 2024-08-26 at 7 30 05 PM" src="https://github.com/user-attachments/assets/e3b6fcc0-70a9-4fb7-9b72-3c6de225fb43">


<img width="439" alt="Screenshot 2024-08-26 at 7 29 52 PM" src="https://github.com/user-attachments/assets/d9a49024-89c8-45a7-8f1f-9feca6f32932">

2024-08-26 14:12 UTC, BhuvaneshPatil commented
android native-
<img width="437" alt="Screenshot 2024-08-26 at 7 21 00 PM" src="https://github.com/user-attachments/assets/ab73c07a-47d7-4b0a-b473-1f9be1fe5de3">
<img width="506" alt="Screenshot 2024-08-26 at 7 20 51 PM" src="https://github.com/user-attachments/assets/a2c1640b-9dbe-4b76-a454-6609428540a5">
<img width="435" alt="Screenshot 2024-08-26 at 7 20 24 PM" src="https://github.com/user-attachments/assets/7e0ddaab-7e5f-4739-b129-aa6ab2668efd">
<img width="518" alt="Screenshot 2024-08-26 at 7 20 16 PM" src="https://github.com/user-attachments/assets/f206c0db-9924-4ff9-8ff8-59a85d1f4fcd">
<img width="801" alt="Screenshot 2024-08-19 at 7 10 01 PM" src="https://github.com/user-attachments/assets/34266f0e-a6d2-4904-8e37-94abce945adb">

2024-08-26 14:13 UTC, BhuvaneshPatil commented
IOS Native -
<img width="401" alt="Screenshot 2024-08-25 at 9 58 12 PM" src="https://github.com/user-attachments/assets/6aae0a8c-0d3f-4ceb-bfc8-e660e835af46">
<img width="399" alt="Screenshot 2024-08-25 at 9 57 55 PM" src="https://github.com/user-attachments/assets/d59a2f64-42cf-4944-ad1c-950ba1a45075">
<img width="384" alt="Screenshot 2024-08-25 at 9 57 34 PM" src="https://github.com/user-attachments/assets/dc56b839-945f-4bc9-97af-1605d9db23e1">
<img width="369" alt="Screenshot 2024-08-25 at 9 56 40 PM" src="https://github.com/user-attachments/assets/3668e11d-3bf2-45aa-aed4-ad9ba4bae844">

2024-08-26 14:16 UTC, BhuvaneshPatil commented
<img width="778" alt="Screenshot 2024-08-19 at 7 10 18 PM" src="https://github.com/user-attachments/assets/8be42c65-5e6c-4b67-8fdf-45f666e4cbd5">
<img width="801" alt="Screenshot 2024-08-19 at 7 10 01 PM" src="https://github.com/user-attachments/assets/52556b52-bbae-4fcd-8e75-ed1dc0cd309e">

2024-08-27 14:57 UTC, rushatgabhane commented
Makes sense

2024-08-27 14:58 UTC, rushatgabhane commented
@Expensify/design 

We need your feedback on the design - https://github.com/Expensify/App/pull/48003#issuecomment-2310329673

2024-08-27 15:02 UTC, shawnborton commented
So we need to adjust the gap between icon + label so that all of the labels line up perfectly. See the big difference here?
![CleanShot 2024-08-27 at 10 59 33@2x](https://github.com/user-attachments/assets/0665db2c-f364-4a9b-8e4d-4cdfe448d212)

The way to handle this is to use different gaps for the first two tabs vs the settings tab. I have it so that the first two tabs are using 6px gap, and then the Settings tab uses 2px gap:

https://github.com/user-attachments/assets/459fdc26-ce4d-4816-bcad-dfd5b56dbd19

I also tried to reduce the 2px gap between the green ring and the avatar to be just 1px so we save some space there too. cc @Expensify/design for thoughts on all of this

2024-08-27 15:05 UTC, shawnborton commented
Also, the tabs that are not active should use textSupporting for the color, not our standard text color. 
![CleanShot 2024-08-27 at 11 05 23@2x](https://github.com/user-attachments/assets/07b53d35-874f-4aa6-8b60-fab61dc7079a)

2024-08-27 15:18 UTC, dannymcclain commented
Love all those comments Shawn! Something looks weird with the 1px gap around the selected avatar though... It doesn't look even to me? (Closer on the sides than it is on the top... No idea why that would be)
![CleanShot 2024-08-27 at 10 17 37@2x](https://github.com/user-attachments/assets/3cf1d674-c2f8-4ae1-a656-f4767c86b0a3)

2024-08-27 15:21 UTC, shawnborton commented
Oh boy it was set to 33x34... good eye, my b! This is an updated version that looks even:
![CleanShot 2024-08-27 at 11 21 14@2x](https://github.com/user-attachments/assets/7cac0ec9-c7d7-46f0-a29c-f5c51830c251)

2024-09-02 01:35 UTC, rushatgabhane commented
@BhuvaneshPatil bump on the above

2024-09-02 12:27 UTC, BhuvaneshPatil commented
@rushatgabhane I modified the code for given margins that is - 6px for inbox and search and 2px for avatar. It looks good when we are on inbox or search page but when we have green ring it pushes the label down (for Settings)

2024-09-03 07:11 UTC, shawnborton commented
>  It looks good when we are on inbox or search page but when we have green ring it pushes the label down (for Settings)

Is there a way to absolutely position the green ring? That's what We have in Figma I believe.

2024-09-07 18:36 UTC, BhuvaneshPatil commented
<img width="963" alt="Screenshot 2024-09-07 at 11 55 55 PM" src="https://github.com/user-attachments/assets/92aa6ffb-7f80-40b7-8dc7-244efc69eef3">
<br/>
<img width="746" alt="Screenshot 2024-09-07 at 11 55 23 PM" src="https://github.com/user-attachments/assets/5c362efc-4085-4d33-804f-6fb43df1ea4e">
<br/>
<img width="469" alt="Screenshot 2024-09-07 at 11 54 53 PM" src="https://github.com/user-attachments/assets/843848ea-80ed-44de-b6b9-217bd06be483">
<br/>
<img width="422" alt="Screenshot 2024-09-07 at 11 54 12 PM" src="https://github.com/user-attachments/assets/145fc5a3-fcfe-4964-ae21-af0af877b66b">

2024-09-08 15:20 UTC, shawnborton commented
Looks like the alignment is still slightly off and incorrect. Can you keep adjusting please? Happy to help provide any direction if needed, just let us know. Going to spin up a test build in the meantime.

2024-09-08 16:00 UTC, shawnborton commented
Hmm the iOS app crashes when I try to open it from the test build. Any ideas?

2024-09-08 16:13 UTC, BhuvaneshPatil commented
I am able to run the app locally on the same branch.

2024-09-09 03:31 UTC, dubielzyk-expensify commented
There's some funky jumps happening:
![CleanShot 2024-09-09 at 13 30 30](https://github.com/user-attachments/assets/c856086e-0e15-492d-a8dd-6cd9c8022579)

Also, do we want the inactive label text color to be secondary color or primary @shawnborton ?

2024-09-09 05:09 UTC, shawnborton commented
Good catch, we should not see any "jumping" besides the label text becoming bold. 

And the inactive labels should use textSupporting color as you mentioned.

2024-09-09 05:10 UTC, shawnborton commented
@BhuvaneshPatil can you try running the test build on iOS from above (if you have an iPhone)? It's still crashing for me.

2024-09-09 06:44 UTC, BhuvaneshPatil commented
The jumpy behaviour is because I am adjusting top margins when we have ring or emoji status,I have done for keeping the text on same line

2024-09-09 06:52 UTC, shawnborton commented
We need to remove the jumpy behavior and make sure everything feels "fixed" in place - can you please adjust?

2024-09-09 12:56 UTC, BhuvaneshPatil commented
@shawnborton I made the border absolute, it will solve the issue for selected avatar, can you please provide design/gap numbers of margin for avatar with emoji status please

2024-09-09 14:13 UTC, shawnborton commented
@BhuvaneshPatil the emoji status should also be absolutely positioned and not change anything about how the avatar icon is placed. 

Is this ready for a new test build btw? You said you made the ring absolutely positioned but I didn't see any new commits come through.

2024-09-09 14:16 UTC, shawnborton commented
I just tried the most recent build and I am still getting the jumpiness when selecting the Settings tab.

2024-09-09 14:16 UTC, BhuvaneshPatil commented
I have changes locally, I was thinking of making all changes first then verify. Does that work?

2024-09-09 14:30 UTC, shawnborton commented
Sounds good. Please push your latest changes when you can so we can test from there. Please remember to adjust the font color like we mentioned above as well, thanks!

2024-09-10 02:41 UTC, BhuvaneshPatil commented
@shawnborton can you please provide a design like you've shared [here](https://github.com/Expensify/App/pull/48003#issuecomment-2312815088). For the case where we have emoji status and labels

https://github.com/user-attachments/assets/c3dd3138-bade-474a-9d6a-98b4f6b3cbef

<img width="858" alt="Screenshot 2024-09-10 at 8 11 13 AM" src="https://github.com/user-attachments/assets/6ee2a5c4-28f8-4ade-af7c-d0cc54084723">

2024-09-10 03:29 UTC, dubielzyk-expensify commented
I think we'll have to put the status bubble in the top right corner with this new change or add more spacing between the icon and the label. Keen to hear what @shawnborton thinks.

2024-09-10 05:23 UTC, BhuvaneshPatil commented
Issue with placing emoji status on top right corner is that we show tiny green dot if user has some action required to perform.

For example when I created new account and email is not verified we show tiny green dot.

2024-09-10 06:01 UTC, dubielzyk-expensify commented
Ah of course. My bad for forgetting. Let's see what Shawn says. We'll find a solution either way 👍

2024-09-10 08:23 UTC, dubielzyk-expensify commented
> but I can totally see moving it up and to the left by like 1-2 pixels to make a little more room for the label.

Definitely like that thinking. Tested it with inspect mode and changing it from `-4px` to `-2px` works well.

2024-09-11 11:50 UTC, shawnborton commented
Okay here's how I think we can approach this.

First, the wrapper that wraps the avatar portion needs to be 28x28. Then let's give it position relative and move it to `top: -2px` so we vertically pull it up a bit. This gives us a little extra space below but optically it looks balanced.
![CleanShot 2024-09-11 at 13 46 59@2x](https://github.com/user-attachments/assets/11b6cd22-dc8c-4fb4-b06f-3debe9c9c406)

For the emoji portion, I think that can be `-6px` from the right and bottom:
![CleanShot 2024-09-11 at 13 48 59@2x](https://github.com/user-attachments/assets/f520707d-e746-4f44-a80d-5e48631fdcd6)

Can you try that and see how it goes?

2024-09-12 08:14 UTC, shawnborton commented
We're so close! Can you give the wrapper that holds the Settings icon a style of `top: -2px` so we pull it up slightly to create a bit more separation between the icon and label? I think it still maintains optical alignment even though we're pulling it up slightly:
![CleanShot 2024-09-12 at 10 13 17@2x](https://github.com/user-attachments/assets/3b587d70-10a2-4206-9d2c-f6ad1d883e23)

2024-09-12 13:18 UTC, shawnborton commented
Hmm no idea why iOS failed, maybe you need to pull main?

2024-09-12 13:21 UTC, shawnborton commented
Otherwise this is feeling pretty good:

https://github.com/user-attachments/assets/897414f4-c40e-4401-b432-14f04f9ca56d


cc @Expensify/design to take it for a spin too!

2024-09-12 13:29 UTC, dannymcclain commented
I was just looking at it on web—overall feels pretty good to me too!

It gets a little intense/tight when you also have an emoji status saved, but that's not really this project's fault. I feel like we can noodle on that for later.

![CleanShot 2024-09-12 at 08 26 33@2x](https://github.com/user-attachments/assets/93622064-8f1b-4b16-94d2-82d1e04d2d5f)

2024-09-12 14:30 UTC, shawnborton commented
Agree - it's definitely tight but I think we finally got it to an acceptable spot at least! Triggered a new build btw.

2024-09-12 15:40 UTC, shawnborton commented
Hmm no idea why this won't build for iOS. 

Either way, I'm definitely curious for @dubielzyk-expensify to get a chance to weigh in on the styles too, but otherwise I think @rushatgabhane you can start reviewing this.

Also cc @anmurali in case you want to take this for a spin as well.

2024-09-12 16:09 UTC, BhuvaneshPatil commented
I am trying to turn developer mode on in my iphone but I don't see the option (I am on ios 18).

2024-09-13 03:03 UTC, dubielzyk-expensify commented
On web it's looking great!

On Android the icons shift a tad bit on my Pixel 7. Is it possible to avoid this?

https://github.com/user-attachments/assets/9df5ca6d-1809-4c87-af35-cce82235b386

2024-09-13 05:15 UTC, shawnborton commented
Interesting catch Jon. I wonder if we need to set a fixed height for the labels? Which would be `14` technically since I think that is the desired line height we have for the micro font size.

2024-09-13 12:54 UTC, BhuvaneshPatil commented
https://github.com/user-attachments/assets/49c5d87e-bb37-4cd8-97d6-d468e0976d90

2024-09-14 06:34 UTC, shawnborton commented
@dubielzyk-expensify @BhuvaneshPatil did those latest line height changes fix the issue Jon reported? I spun up a new test build so we can check again.

2024-09-14 06:34 UTC, shawnborton commented
In your video, it looks like the slight jump/movement is still happening. Any ideas how to fix that?

2024-09-15 21:43 UTC, rushatgabhane commented
@ design - when accessing as a copilot, this is how it looks. Let me know if it looks okay

<img width="281" alt="image" src="https://github.com/user-attachments/assets/48545ac4-4ca3-4c8a-910b-139c54ec2fe9">

2024-09-16 00:05 UTC, dubielzyk-expensify commented
> @ design - when accessing as a copilot, this is how it looks. Let me know if it looks okay

Good catch. I think this should have the same treatment as we've made to the status emoji above cause that doesn't look great at the moment :) Keen to hear if @Expensify/design has thoughts though.

2024-09-16 05:12 UTC, shawnborton commented
> when accessing as a copilot, this is how it looks. Let me know if it looks okay

Oh interesting, I could have sworn we decided not to do that in the end? If we are planning to keep that, let's just occupy the same space as the status I suppose. cc @dylanexpensify in case you have thoughts too

2024-09-16 05:50 UTC, BhuvaneshPatil commented
I have applied same styles to co-pilot avatar that appears on the place of emoji status.

Also I have given height of 16px. The root cause of moving icon hen clicked is when text gets bold it changes its height and width and that causes layout to shift. Please verify attached video looks fine.

https://github.com/user-attachments/assets/e83e7275-5040-4ab2-a4a0-8ef97b418221

2024-09-16 05:54 UTC, shawnborton commented
How are you getting this particular avatar to show up as the Copilot's avatar? It looks broken:
![CleanShot 2024-09-16 at 07 54 17@2x](https://github.com/user-attachments/assets/e367a8ee-ccb1-48f8-ba9a-a935e5ca32c9)

Size-wise the layout looks okay though, it's just the specific avatar being used that is throwing me off.

2024-09-16 05:59 UTC, BhuvaneshPatil commented
I intentionally added some random email (for testing)

2024-09-16 06:00 UTC, shawnborton commented
Sure, but is that the fallback avatar being used? It feels incorrect to me.

2024-09-16 06:06 UTC, BhuvaneshPatil commented
By looking at code - https://github.com/Expensify/App/blob/main/assets/images/avatars/fallback-avatar.svg
Is the fallback avatar that's being used.

2024-09-16 08:52 UTC, shawnborton commented
Ah but notice how much negative space is around the fallback avatar:
![CleanShot 2024-09-16 at 10 52 16@2x](https://github.com/user-attachments/assets/1ee524e2-00f4-4d4a-8537-24871ee73f05)

That same space around the shape should be maintained here as well.

2024-09-16 16:25 UTC, BhuvaneshPatil commented
I am not sure if I am getting what you are trying to say.
By looking in browser, we have given 28x28 dimensions for that. So maybe cause of that it looks tighter

2024-09-17 05:31 UTC, shawnborton commented
Something looks off though, even if we scale it down to 28x28, it should retain the slight amount of negative space around the icon. So let's take a quick look into that but I also don't want to block progress so we can get this merged.

Can you share a screenshot of what it looks like when the Copilot avatar is available for comparison to the fallback version?

2024-09-17 05:53 UTC, BhuvaneshPatil commented
sure

mac web - 
<img width="1126" alt="Screenshot 2024-09-17 at 11 22 04 AM" src="https://github.com/user-attachments/assets/c896c124-16c2-4fb5-8098-abc24249b937">

IOS native-  
<img width="415" alt="Screenshot 2024-09-17 at 11 22 19 AM" src="https://github.com/user-attachments/assets/4f130715-dbb4-4633-a26e-03c6b27da993">

2024-09-17 07:57 UTC, shawnborton commented
Okay great - see the difference? The iOS version is not the same as web. Web looks correct though:
![CleanShot 2024-09-17 at 09 56 55@2x](https://github.com/user-attachments/assets/8ae3d1f1-5202-4afb-a505-9b83438088f9)

2024-09-17 08:20 UTC, BhuvaneshPatil commented
Right, I will try to fix that in this PR itself

2024-09-18 06:18 UTC, BhuvaneshPatil commented
<img width="374" alt="android_native" src="https://github.com/user-attachments/assets/c79dda93-14d3-440f-99e2-147bb4e4cef4">
<img width="394" alt="ios_native" src="https://github.com/user-attachments/assets/0653b439-2d49-4239-8be2-e694ccabfd0a">
<img width="419" alt="iphone_web" src="https://github.com/user-attachments/assets/cf81dd21-a43f-4696-931c-d9da8d999c1f">
<img width="426" alt="android_web" src="https://github.com/user-attachments/assets/a2b9017d-74e1-4f8d-9918-1673c1213049">

2024-09-18 06:20 UTC, shawnborton commented
That seems better. I think we can start to get this into final review! cc @rushatgabhane

2024-09-18 06:45 UTC, rushatgabhane commented
@BhuvaneshPatil are you sure you pushed commits for the above?

2024-09-18 06:53 UTC, BhuvaneshPatil commented
not yet, wanted to get confirmation first

2024-09-18 09:20 UTC, BhuvaneshPatil commented
@rushatgabhane Completed checklist

2024-09-19 23:11 UTC, rushatgabhane commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->

</details>

<detail [...]

2024-09-26 17:49 UTC, BhuvaneshPatil commented
Quick bump @rushatgabhane

2024-09-30 02:28 UTC, rushatgabhane requested changes
Small change. Rest LGTM

2024-09-30 02:28 UTC, rushatgabhane commented on src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
> +                        textAlign="center"
please use `style={styles.textAlignCenter}`

2024-09-30 02:28 UTC, rushatgabhane commented on src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx
> +                        textAlign="center"
same here `styles.textAlignCenter`

2024-09-30 02:28 UTC, rushatgabhane commented on src/pages/home/sidebar/BottomTabAvatar.tsx
> +                    textAlign="center"
same here `styles.textAlignCenter`

2024-09-30 03:55 UTC, BhuvaneshPatil commented
@rushatgabhane Updated the PR

2024-10-01 03:24 UTC, rushatgabhane approved these changes

2024-10-01 21:31 UTC, marcochavezf approved these changes
LGTM

2024-10-01 21:35 UTC, merged

2024-10-01 21:46 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.