Fix copilot bugs
Expensify/App pull request #48517
Opened 2024-09-04 03:00 UTC by rushatgabhane

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/48261
https://github.com/Expensify/App/issues/48245
https://github.com/Expensify/App/issues/48246
https://github.com/Expensify/App/issues/48252
https://github.com/Expensify/App/issues/48253
https://github.com/Expensify/App/issues/48259
https://github.com/Expensify/App/issues/48292

PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-09-04 14:36 UTC, dangrous commented
I know this is a draft but wanted to call out two bugs not yet listed in the list in the PR description:

* https://github.com/Expensify/App/issues/48244
* [IOS: BUG: While offline, Alert does not show up on changing accounts.](https://github.com/Expensify/App/pull/47338#issuecomment-2313666208)

2024-09-05 02:02 UTC, rushatgabhane commented
added them to the list

2024-09-08 18:33 UTC, rushatgabhane commented
- [x] https://github.com/Expensify/App/issues/48261
- [ ] https://github.com/Expensify/App/issues/48245
- [ ] https://github.com/Expensify/App/issues/48246
- [ ] https://github.com/Expensify/App/issues/48252
- [ ] https://github.com/Expensify/App/issues/48253
- [ ] https://github.com/Expensify/App/issues/48259
- [ ] https://github.com/Expensify/App/issues/48292
- [ ] https://github.com/Expensify/App/pull/47338#issuecomment-2313666208
- [ ] https://github.com/Expensify/App/issues/48244

2024-09-08 19:57 UTC, rushatgabhane commented
cc: @dangrous

2024-09-09 02:08 UTC, rushatgabhane commented
> https://github.com/Expensify/App/pull/47338#issuecomment-2313666208

@dangrous this was fixed in the PR itself. So I've removed it from the list


https://github.com/user-attachments/assets/a400d3ce-e56b-4c49-91fc-db3517e66ca8

2024-09-09 02:13 UTC, rushatgabhane commented
All bugs here fixed - https://github.com/Expensify/App/pull/48517#issuecomment-2336781614

cc @mkhutornyi

2024-09-10 21:59 UTC, rushatgabhane commented
> Bug: app crashes while switching account. And blank account info

unrelated to copilot actually. and being fixed in another issue

2024-09-10 21:59 UTC, rushatgabhane commented on src/components/AccountSwitcher.tsx
> +                                style={[styles.textBold, styles.textLarge, styles.flexShrink1]}
@mkhutornyi you can look at the commits for that - https://github.com/Expensify/App/pull/48517/commits

2024-09-10 22:46 UTC, rushatgabhane commented on src/components/AvatarWithImagePicker.tsx
> +                                                    style={[styles.pRelative, avatarStyle]}
nice catch!

2024-09-10 22:46 UTC, rushatgabhane commented on src/components/AvatarWithImagePicker.tsx
> +                                                    style={[styles.pRelative, avatarStyle]}
i think i'll just override the style then

2024-09-12 23:56 UTC, dangrous commented
@rushatgabhane are we going to be able to add the new copilot bugs into this PR as well? I believe you're assigned to all of them currently. Thanks!

2024-09-13 01:28 UTC, rushatgabhane commented
yes will do

2024-09-14 00:05 UTC, dangrous commented
Do we think this will be ready to review on Monday? I'd love to be able to get this merged then and then see if any new bugs crop up.

2024-09-16 09:01 UTC, rushatgabhane commented on src/components/AvatarWithImagePicker.tsx
> +                                                    style={[styles.pRelative, avatarStyle]}
<img width="401" alt="image" src="https://github.com/user-attachments/assets/62fdb4f6-d543-4f0f-ae32-0894637a736d">


<img width="400" alt="image" src="https://github.com/user-attachments/assets/9fadf85f-22e4-40fd-99cf-508482decf26">

2024-09-16 09:41 UTC, rushatgabhane commented
@mkhutornyi for ease of review i added new commits with their issue number. hope that helps.

5 new issues for you to review - 

https://github.com/Expensify/App/issues/48965
https://github.com/Expensify/App/issues/48966
https://github.com/Expensify/App/issues/48967
https://github.com/Expensify/App/issues/48972

ty!

2024-09-16 09:42 UTC, rushatgabhane commented on src/components/AvatarWithImagePicker.tsx
> +                                                    style={[styles.pRelative, avatarStyle]}
fixed

2024-09-16 09:44 UTC, rushatgabhane commented
@dangrous all done here

2024-09-16 16:35 UTC, rushatgabhane commented on src/pages/settings/Subscription/SubscriptionSettingsPage.tsx
> +    }
I don't think it is worth improving this more. The subscription data is simply not in Onyx, so we have to show not found page

2024-09-16 16:36 UTC, rushatgabhane commented on src/pages/settings/Subscription/SubscriptionSettingsPage.tsx
> +    }
this is the conditon now. the most we can do is to show a loader when the app is loading.

```
    if (!subscriptionPlan && isAppLoading) {
        return <FullScreenLoadingIndicator />;
    }
    if (!subscriptionPlan) {
        return <NotFoundPage />;
    }
```

2024-09-16 16:50 UTC, rushatgabhane commented
> Is it a bug from our PR ?, the error message is not visible on iOS native:

looks like it let me see

2024-09-16 19:48 UTC, allgandalf approved these changes
## Summary of all the bugs attached to this PR ♻️ :

### Fixed:
- [x] https://github.com/Expensify/App/issues/48261
- [x] https://github.com/Expensify/App/issues/48252
- [x] https://github.com/Expensify/App/issues/48253
- [x] https://github.com/Expensify/App/issues/48259
- [x] https://github.com/Expensify/App/issues/48244 
- [x] https://github.com/Expensify/App/issues/48965 
- [x] https://github.com/Expensify/App/issues/48967
- [x] https://github.com/Expensify/App/issues/48972


### Partially Fixed:

- [ ] https://github.com/Expensify/App/issues/48246 

[Comments](https://github.com/Expensify/App/pull/48517/files#r1761479480) from @rushatgabhane :

> I don't think it is worth improving this more. The subscription data is simply not in Onyx, so we have to show not found page


I agree with this conclusion! There isn't a way that we know of to get the subscription data from `Onyx`


- [ ] https://github.com/Expensify/App/issues/48966 

This bug is more of a `BE` bug, @dangrous you can refer to @rushatgabhane 's comments [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1726505388396179?thread_ts=1726494617.816779&cid=C06ML6X0W9L).


But the above 2 shouldn't block this PR, this PR looks great and fixes a lot of bugs, had fun reviewing this one 🚀 all yours @dangrous

2024-09-18 00:41 UTC, dangrous commented
Running through this, it's all looking good so far! Commenting here when I find bugs so you might get a couple messages.

I noticed that we don't differentiate between errors on the new validate code form. I tried adding a copilot from an unvalidated account, and got a `401 Delegator account must be validated` error returned from the server, but all the form said was that it was an incorrect validation code

<img width="1087" alt="image" src="https://github.com/user-attachments/assets/96c2f5a2-7c04-4875-a648-42c16ab34838">

Although now that I'm writing it I'm realizing it might be something we should fix on the backend? Like if the verification code is correct (for all of these new flows), should that count to validate the account? cc @NikkiWines since you wrote the new code on the backend.

2024-09-18 00:46 UTC, dangrous commented
For https://github.com/Expensify/App/issues/48246 I think we might want a fallback for if the delegator account doesn't have a subscription but the delegate does, or vice versa - that is, if you're on the subscription page and swap accounts to a user who doesn't have it. Maybe not found is fine here.

2024-09-18 00:51 UTC, dangrous requested changes
Fallback icon works for now for https://github.com/Expensify/App/issues/48966, I will look into the back end fix.

Other than those commented bugs, I think we're almost there! Let me know what you think about those, and I agree that we can skip the ones @allgandalf called out

2024-09-18 00:51 UTC, dangrous commented on src/pages/settings/Subscription/SubscriptionSettingsPage.tsx
> +    }
Yeah I think that's fine for now

2024-09-18 01:11 UTC, rushatgabhane commented
> I noticed that we don't differentiate between errors on the new validate code form. I tried adding a copilot from an unvalidated account, and got a 401 Delegator account must be validated error returned from the server, but all the form said was that it was an incorrect validation code

you're right. we should fix on backend. We have to return onyx data and then frontend can show that.

2024-09-18 15:44 UTC, dangrous commented
Ready to merge this if you agree with https://github.com/Expensify/App/pull/48517#issuecomment-2357266910 - should we leave as is? Or would it be better to navigate from subscription page back to profile page or something?

2024-09-18 17:36 UTC, rushatgabhane commented
> Ready to merge this if you agree with #48517 (comment) - should we leave as is? Or would it be better to navigate from subscription page back to profile page or something?

we don't have this pattern to fallback to another route. so i think we should do nothing here 👍

2024-09-18 19:26 UTC, dangrous approved these changes
okay great! BE changes needed as noted to fix the remaining bugs but this gets 99% of them and looks great!

2024-09-18 19:26 UTC, merged

2024-09-18 19:36 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-09-18 22:53 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10930931534) to staging by https://github.com/dangrous in version: 9.0.38-0 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2024-09-19 23:33 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/10950309294) to production by https://github.com/grgia in version: 9.0.38-4 🚀

platform | result
---|---
🤖 android 🤖|success ✅
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅
🕸 web 🕸|success ✅

2025-08-26 11:27 UTC, parasharrajat commented
This PR didn't completely solve the issue https://github.com/Expensify/App/issues/48246 which we solved here https://github.com/Expensify/App/issues/66842