Update capitalization of copy to match new guidelines
Expensify/App pull request #4854
Opened 2021-08-26 15:39 UTC by iwiznia

### Fixed Issues
$https://github.com/Expensify/Expensify/issues/169061

### Tests
Click around on the site both in spanish and english and make sure the capitalization of the copy is correct. We should only capitalize names, the beginning of sentences and acronyms.

### QA Steps
Same, but please try to be on the lookout for any capitalization we missed

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [x] iOS
- [x] Android

### Screenshots
![image](https://user-images.githubusercontent.com/521248/130993031-cb4fed82-929e-4109-8f40-98c32bf339a0.png)
![image](https://user-images.githubusercontent.com/521248/130993239-ff9530f4-12d3-41e1-aadc-13fdafed28ef.png)
![image](https://user-images.githubusercontent.com/521248/130993251-c3315dfd-678a-4641-9ca8-b6121ffba582.png)

2021-08-26 16:11 UTC, MonilBhavsar submitted a review, later dismissed

2021-08-26 16:51 UTC, luacmartins requested changes
Left a few suggestions. Great work @iwiznia! My eyes are very happy now 😄

2021-08-26 18:15 UTC, luacmartins submitted a review, later dismissed
LGTM 👍

2021-08-27 12:12 UTC, luacmartins approved these changes

2021-08-27 12:24 UTC, MonilBhavsar approved these changes

2021-08-27 12:30 UTC, merged

2021-08-30 17:32 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1183084866) to staging by @MonilBhavsar in version: 1.0.88-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|cancelled 🔪 
🖥 desktop 🖥|cancelled 🔪
🍎 iOS 🍎|cancelled 🔪 
🕸 web 🕸|success ✅

2021-09-01 01:43 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1188395063) to production by @roryabraham in version: 1.0.90-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2023-03-16 19:56 UTC, puneetlath commented
FYI: we changed the `Terms of Service` back to capitalized [here](https://github.com/Expensify/App/issues/15664) because it's a title, rather than a sentence.