fix count when LHN is open on mobile
Expensify/App pull request #4865
Opened 2021-08-26 23:23 UTC by parasharrajat

### Details

1. Only increment the counter when the report is visible and in other case, we should reset the counter.

### Fixed Issues

$ https://github.com/Expensify/App/issues/4863

### Tests | QA Steps
1. Lunch the app
2. Log in with account A in device 1
3. Select user you will chat and scroll the chat to 10-30 messages to top
4. Back to LHN
5. Log in with account B in device 2
6. Send 13 messages to account A from device 2
7. Back to conversation from LHN in device 1 and check the green Marker Badge Coun

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

https://user-images.githubusercontent.com/24370807/131048311-e46c43ad-8721-4104-8448-6382826bb4b8.mp4

2021-08-27 00:22 UTC, roryabraham requested changes

2021-08-27 15:11 UTC, TomatoToaster approved these changes

2021-08-27 16:59 UTC, roryabraham approved these changes

2021-08-27 16:59 UTC, merged

2021-08-30 17:32 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1183084866) to staging by @roryabraham in version: 1.0.88-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|cancelled 🔪 
🖥 desktop 🖥|cancelled 🔪
🍎 iOS 🍎|cancelled 🔪 
🕸 web 🕸|success ✅

2021-08-30 17:36 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1183075988) to production by @roryabraham in version: 1.0.88-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2021-09-01 01:26 UTC, botify commented
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-08.  :confetti_ball:

2021-09-01 01:43 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1188395063) to production by @roryabraham in version: 1.0.90-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅