Marker not updated properly fixed
Expensify/App pull request #4887
Opened 2021-08-27 19:14 UTC by Santhosh-Sellavel

@timszot 
### Details
The issue is specifically occurs in Mobile devices & mWeb

### Fixed Issues

$ #4357 

### Tests & QA Steps
1. Open new Expensify app
2. Wait for any new message on the chat list page
3. When a new message is received open the chat
4. Should show `NEW` indicator above the new messages
5. Go back to the chat list
6. Open the same chat again, `NEW` indicator should not be shown.
7.  Now go back to the chat list, & wait until a new message from the same user
8. Open the same chat now
9. Should show `NEW` indicator above the new messages
10. Go back to chat list
11. Open the same chat again, `NEW` indicator should not be shown.

### Tested On
- [x] Mobile Web
- [x] iOS
- [x] Android

### Screenshots

#### Mobile Web
https://user-images.githubusercontent.com/85645967/132128854-5560109e-b8f8-4bff-a151-426969fc1163.mp4

#### iOS
https://user-images.githubusercontent.com/85645967/132128985-71615ca1-0ebf-46a0-806f-35048d3c53e3.mov

#### Android
https://user-images.githubusercontent.com/85645967/132129234-ddf16cb1-58d1-4f06-b343-8b4acce4fd5f.mov

2021-08-31 16:32 UTC, Santhosh-Sellavel commented
@sketchydroide can review my changes if possible. I see @timszot is OOO until sep 7.

I'll update screenshot/videos after an initial review thanks!

2021-08-31 16:48 UTC, sketchydroide commented
Is this still a WIP?

2021-08-31 16:50 UTC, Santhosh-Sellavel commented
> Is this still a WIP?
No added WIP
 - For screenshots/videos only 
 - @timszot first review

2021-08-31 17:04 UTC, sketchydroide commented
It is still a draft, that's what I meant

2021-08-31 17:12 UTC, Santhosh-Sellavel commented
> It is still a draft, that's what I meant
Yes mate

2021-09-02 23:50 UTC, deetergp commented
@Santhosh-Sellavel WIP = Work in Progress, which was how we designated draft PRs before Github has the ability to mark a PR as a draft.

2021-09-03 00:24 UTC, deetergp requested changes

2021-09-03 03:55 UTC, Santhosh-Sellavel commented on src/pages/home/report/ReportActionsView.js
> +        // If the new marker has changed places so update the component.
Sure

2021-09-03 03:55 UTC, Santhosh-Sellavel commented on src/pages/home/report/ReportActionsView.js
> +
Will do.

2021-09-05 14:00 UTC, Santhosh-Sellavel commented
cc: @sketchydroide @deetergp Ready for review

2021-09-06 11:34 UTC, sketchydroide commented on src/pages/home/report/ReportActionsView.js
> +            this.updateUnreadIndicatorPosition(this.props.report.unreadActionCount);
weird spacing here

2021-09-06 11:36 UTC, sketchydroide approved these changes

2021-09-07 18:17 UTC, deetergp approved these changes
Code looks good and tests pass 👍

2021-09-07 18:17 UTC, merged

2021-09-07 18:17 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-09-08 22:05 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1214907189) to staging by @deetergp in version: 1.0.94-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-09-09 20:41 UTC, botify commented
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-16.  :confetti_ball:

2021-09-09 21:00 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1218876549) to production by @yuwenmemon in version: 1.0.95-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅