Use SearchRouter everywhere and drop Chat finder
Expensify/App pull request #49984
Opened 2024-10-01 11:39 UTC by Kicu

### Details
 - waiting on other Search PRs to be merged
 - this PR adds the new SearchButton everywhere 
 - everything related to `ChatFinder` is removed 

### Fixed Issues
$ https://github.com/Expensify/App/issues/49123
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-10-04 13:52 UTC, Kicu commented
@luacmartins @rayane-djouah This PR enables it all: takes off the `Permission` check for isDev and turns on SearchRouter everywhere including on cmd+k shortcut. However I'm going OOO for the next week and will be back 14 October.

Meanwhile if there are problems or deploy blockers then @SzymczakJ should be able to help with those.

I understand that we might notice some more bugs since probably now it will be tested more heavily 😅

2024-10-04 13:54 UTC, Kicu commented
CC @adhorodyski if you mind taking a look at the file `tests/perf-test/SearchRouter.perf-test.tsx` in which there are old file `ChatFinder` reassure tests rewritten to new component. The tests were passing on my local dev setup, but I'd like to now if they make sense :)

2024-10-04 14:59 UTC, luacmartins commented
Nice! Really excited about this one.

2024-10-04 15:02 UTC, luacmartins requested changes
BUG: Pressing `cmd + k` with the modal open closes the modal and reopens it

1. Press `cmd + k` to open the modal
2. With the modal open, press `cmd + k` again
3. Note that the modal closes and reopens

Expected behavior: the modal should just close if it is already open

2024-10-04 15:04 UTC, luacmartins commented
@Expensify/design  I kicked off an adhoc build and would love your eyes on this one.

2024-10-04 15:05 UTC, luacmartins commented
Should the modal have the same top margin as the search bar?
![Screenshot 2024-10-04 at 9 02 59 AM](https://github.com/user-attachments/assets/e51b81b7-acc4-462e-9f37-a7556377ade9)

2024-10-04 15:10 UTC, Kicu commented
> BUG: Pressing cmd + k 

I'll push a quick fix for this

2024-10-04 15:38 UTC, Kicu commented
pushed a fix but its a bit dirty, not sure if it will hold up over review 😅 that's the best I could do for today to make it behave somewhat good.
The caveat is we will now not close other modals globally.

2024-10-07 09:54 UTC, SzymczakJ commented
I'll be finishing this PR when Mateusz is OOO. As for:

> The caveat is we will now not close other modals globally.

I fixed it and now modals will close on cmd+k
Also, could you review tests section in this PR @adhorodyski?. Your opinion would be invaluable for us 😃

2024-10-07 12:05 UTC, adhorodyski commented
On it now!

2024-10-07 13:57 UTC, adhorodyski approved these changes

2024-10-07 13:57 UTC, adhorodyski commented on tests/perf-test/SearchRouter.perf-test.tsx
> +        .then(() => measureRenders(<SearchRouterWrapperWithCachedOptions />, {scenario}));
exactly what we aimed for here 👍🏼

2024-10-07 13:57 UTC, adhorodyski commented on tests/perf-test/SearchRouter.perf-test.tsx
thanks for removing some of the mocks!

2024-10-08 04:00 UTC, dubielzyk-expensify commented
This is looking awesome. Here's a few design fixes:

- The height of the recent searches should be `52px`. In the branch it's `44px`
- The section titles ("Recent searches", "Recent chats") should have 12px padding instead of 20px
- Router should be `6px` padding from the edge, not `20px`

Below a few screens to explain further:
![CleanShot 2024-10-08 at 13 52 18@2x](https://github.com/user-attachments/assets/d5676b4c-8add-4cae-8349-6b1bb2fedb31)

![CleanShot 2024-10-08 at 13 56 29@2x](https://github.com/user-attachments/assets/e801f3bf-adf3-4190-968f-fa4d3c5e30d4)

![CleanShot 2024-10-08 at 13 58 45@2x](https://github.com/user-attachments/assets/529bba0f-b504-420f-b4bf-1b6a65eda6d0)

2024-10-08 09:04 UTC, SzymczakJ commented
> Search field should have our normal text size 16px

Did you mean 15px @dubielzyk-expensify? I see that `variables.fontSizeNormal` in our codebase are defined with `15px` size and also Figma mock has 15px text in it.

2024-10-08 09:23 UTC, SzymczakJ commented
this is ready for your review @rayane-djouah 🙏

2024-10-08 13:52 UTC, dannymcclain commented
>Did you mean 15px @dubielzyk-expensify? I see that variables.fontSizeNormal in our codebase are defined with 15px size and also Figma mock has 15px text in it.

Yes `15px` is correct 🙂

2024-10-08 23:08 UTC, dubielzyk-expensify commented
My bad for the typo. Danny is correct 🙏

2024-10-09 16:25 UTC, dannymcclain commented
>Do we need to add a margin between the search button and the "new workspace" button?
>I think we need to add a 16px gap like we did in search page

Yeah I agree.

2024-10-10 00:18 UTC, dubielzyk-expensify commented on src/components/Search/SearchRouter/SearchRouter.tsx
>      const modalWidth = isSmallScreenWidth ? styles.w100 : {width: variables.popoverWidth};
Yep. I've tested both and I recon let's do 512 as that is nicely divisible by 8 and its somewhat inbetween.

2024-10-10 00:18 UTC, dubielzyk-expensify commented
Yep agree with the gap. 

Let us know when we can re-review this :)

2024-10-10 07:57 UTC, SzymczakJ commented on src/pages/ChatFinderPage/ChatFinderPageFooter.tsx
> -    return <ReferralProgramCTA referralContentType={CONST.REFERRAL_PROGRAM.CONTENT_TYPES.REFER_FRIEND} />;
I guess we could think of another place to put `ReferralProgramCTA`. @Expensify/design should we also put this Referral Program in SearchRouter, or maybe should we add it somewhere else(as the space in SearchRouter is limited)

2024-10-10 10:33 UTC, SzymczakJ commented
fixed comments and conflicts!

2024-10-10 13:32 UTC, dannymcclain commented on src/components/Search/SearchRouter/SearchRouter.tsx
>      const modalWidth = isSmallScreenWidth ? styles.w100 : {width: variables.popoverWidth};
Beautiful! Sounds good.

2024-10-11 09:58 UTC, SzymczakJ commented
@rayane-djouah 🙏 🙏

2024-10-11 10:26 UTC, rayane-d requested changes

2024-10-11 11:38 UTC, SzymczakJ commented on src/styles/variables.ts
> +    popoverWidth: 512,
whoops, sorry for that one 😅

2024-10-11 11:43 UTC, SzymczakJ commented
> Let us know when we can re-review this :)

This should be ready @dubielzyk-expensify

2024-10-11 16:47 UTC, luacmartins commented
@Kicu @SzymczakJ we have conflicts now

2024-10-11 23:44 UTC, luacmartins commented on src/pages/ChatFinderPage/ChatFinderPageFooter.tsx
> -    return <ReferralProgramCTA referralContentType={CONST.REFERRAL_PROGRAM.CONTENT_TYPES.REFER_FRIEND} />;
I asked the product team. I'll circle back once I get an answer.

2024-10-12 06:32 UTC, JmillsExpensify commented on src/pages/ChatFinderPage/ChatFinderPageFooter.tsx
> -    return <ReferralProgramCTA referralContentType={CONST.REFERRAL_PROGRAM.CONTENT_TYPES.REFER_FRIEND} />;
Yeah let's not worry about this right now. We can find another place for referrals. Cc @jamesdeanexpensify

2024-10-14 07:31 UTC, Kicu commented on src/components/Search/SearchRouter/SearchRouter.tsx
> +        Timing.end(CONST.TIMING.SEARCH_FILTER_OPTIONS);
No this line is correct. 

There were 2 measures done in the old `ChatFinder`. What you're thinking about is still there in `onLayout` inside SearchRouterList - https://github.com/Expensify/App/pull/49984/files#diff-6d769534d8506784b70ef165d2e6883fe38e3fde4683528be637b7f8b923ff9fR185

And this one is just the timing for performing the search of chats, copied directly from here: https://github.com/Expensify/App/blob/main/src/pages/ChatFinderPage/index.tsx#L107-L109

2024-10-14 18:48 UTC, rayane-d approved these changes
LGTM and tests well 🚀

2024-10-15 15:22 UTC, luacmartins submitted a review, later dismissed
LGTM! Gonna ask the product team to test as well before we get it merged

2024-10-15 15:57 UTC, shawnborton commented
Chiming in way late here but I'm back from OOO!

When you type text into the input, can we make sure the text uses our normal text color? Right now it's in text supporting which is wrong:
![CleanShot 2024-10-15 at 17 55 21@2x](https://github.com/user-attachments/assets/b7ea9bb9-3a26-46b9-84c0-e390a9f6e75f)

Also question for the @Expensify/design team - what height should the Recent searches be? 
![CleanShot 2024-10-15 at 17 56 18@2x](https://github.com/user-attachments/assets/1ba44cdd-ef06-44f7-a42e-2ebeb308700f)

I think they are 44px tall right now, but wondering if we should make them 52px to match our button/LHN row sizes?

2024-10-15 15:58 UTC, shawnborton commented
Similar comment - when you actually have text into the input that displays above the table, we should update the text color here too:
![CleanShot 2024-10-15 at 17 57 21@2x](https://github.com/user-attachments/assets/9d3dfdb6-577e-4781-8777-afa628f9a1b6)

And when it's focused, we should use the same lighter BG that the router uses as well:
![CleanShot 2024-10-15 at 17 57 47@2x](https://github.com/user-attachments/assets/0797ed09-8def-42fb-a3eb-d7efd83812ec)

2024-10-15 23:31 UTC, dubielzyk-expensify commented
Saw that we brought this to Slack, but don't think 52px is bad at all. That being said, I think the other alignment fixes are more important than the height

2024-10-15 23:47 UTC, luacmartins commented
@Kicu @SzymczakJ we have conflicts

2024-10-16 07:27 UTC, Kicu commented
Conflicts solved.

I have a question, will be merging this PR soon or will we be holding up until autocomplete features are on?
Because if we want to wait we could keep the `Permission` code in this PR but still merge it to main, so that we avoid thounsands of merge commits in here

2024-10-16 14:49 UTC, luacmartins approved these changes

2024-10-16 14:51 UTC, merged

2024-10-17 07:56 UTC, MonilBhavsar commented
Looks like a minor regression came out of this PR. Would be great if anyone can make a quick fix https://github.com/Expensify/App/issues/50977

2024-10-17 08:00 UTC, Kicu commented
I will take a look at this @MonilBhavsar

2026-01-02 12:17 UTC, shubham1206agra commented on src/libs/Navigation/AppNavigator/AuthScreens.tsx
> +                Session.checkIfActionIsAllowed(() => {
We forgot to close the modal when the user is anonymous, which caused https://github.com/Expensify/App/issues/75498