Fix "New message" button shows when resolving an actionable mention whisper
Expensify/App pull request #50247
Opened 2024-10-04 15:04 UTC by bernhardoj

### Details

Resolving an actionable mention whisper causes the "New message" button to shows up.

### Fixed Issues

$ https://github.com/Expensify/App/issues/49824
PROPOSAL: https://github.com/Expensify/App/issues/49824#issuecomment-2378602701

### Tests

Same as QA Steps
- [x] Verify that no errors appear in the JS console

### Offline tests

Same as QA Steps
### QA Steps

1. Open a room or create a new one with at least 25 messages
2. Mention a user that is not in the room
3. After receiving the concierge whisper, close (switch) and reopen the room
4. Press "Do nothing" on the whisper
5. Verify there is no floating "New message" button shows
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/b9217ef4-1667-445a-b703-3bd1db1cf386

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/06c2dde7-5088-4fcb-a140-a2d873508d2c

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/035cdd09 [...]

2024-10-04 15:05 UTC, bernhardoj commented
Can't send message on android mweb.
https://github.com/user-attachments/assets/952553dd-25be-4b94-bb9f-5ee5c02a3eda

2024-10-04 15:06 UTC, bernhardoj commented on src/libs/ReportActionsUtils.ts
> -        !isResolvedActionTrackExpense(reportAction)
I remove checking `isResolvedActionTrackExpense` because `shouldReportActionBeVisible` already covers it with the new condition.

2024-10-04 15:07 UTC, bernhardoj commented on src/libs/OptionsListUtils.ts
> -                    !ReportActionUtils.isResolvedActionTrackExpense(reportAction),
Same as https://github.com/Expensify/App/pull/50247/files#r1787860157

2024-10-04 15:08 UTC, bernhardoj commented on src/pages/home/report/ReportActionItem.tsx
> -
Removed this workaround because the issue doesn't happen anymore after we exclude the resolved actionable whisper from the list.

2024-10-09 09:32 UTC, bernhardoj commented
I'm able to repro it by simply reopening the report. Here is what happens:
1. Send a user mention that is not part of the room
2. A whisper shows as the last action, but the report `lastVisibleActionCreated` is not updated (BE issue)
3. Close and reopen the report, the updated report `lastVisibleActionCreated` is received from OpenReport
4. Resolve the whisper, we optimistically update the `lastVisibleActionCreated` to the previous action, that is the user mention, but the last action is still the whisper, which what we are fixing here.
5. Close and reopen the report, OpenReport sends the resolved whisper `created` as the report `lastVisibleActionCreated`.

Since we don't include the whisper as the last action anymore, the new message shows.

I think BE shouldn't send the resolved whisper `created` as the report `lastVisibleActionCreated`.

----

However, if that's the expected behavior, then we shouldn't optimistically update the `lastVisibleActionCreated` to the previous action when resolving whisper (step 4).

2024-10-19 01:12 UTC, youssef-lr commented
> I'm able to repro it by simply reopening the report. Here is what happens:
> 
> 1. Send a user mention that is not part of the room
> 2. A whisper shows as the last action, but the report lastVisibleActionCreated is not updated (BE issue)
> 3. Close and reopen the report, the updated report lastVisibleActionCreated is received from OpenReport
> 4. Resolve the whisper, we optimistically update the lastVisibleActionCreated to the previous action, that is the user mention, but the last action is still the whisper, which what we are fixing here.
> 5. Close and reopen the report, OpenReport sends the resolved whisper created as the report lastVisibleActionCreated.


I'm not able to reproduce this locally, can we try again?

2024-10-19 04:29 UTC, bernhardoj commented
Still happens for me.

https://github.com/user-attachments/assets/e3abefd3-fa7b-42fe-9562-7ae024895777

The new message doesn't show because the room has less than 25 messages. I forgot to add more messages before recording.

https://github.com/Expensify/App/blob/66cf824036a51183d73dab2cc621901e43fe3196/src/pages/home/report/ReportActionsList.tsx#L637

Here is the video with the new message shows.

https://github.com/user-attachments/assets/ae42b585-3114-4ee4-b656-bf0dea66fd92

2024-10-24 02:23 UTC, bernhardoj commented
@youssef-lr just in case you missed the above comment ☝️

2024-10-30 12:41 UTC, bernhardoj commented
It's still reproducible. [Here](https://expensify.slack.com/archives/C01GTK53T8Q/p1730292050580319) is the thread.

2024-11-15 18:09 UTC, dangrous commented
hi @paultsimura! The backend changes do NOT currently cover this case - I only updated the behavior when _receiving_ the whisper, not when resolving it. I can look into that too, but I wasn't aware of it at the time

2024-11-23 08:45 UTC, bernhardoj commented
Checking

2024-11-23 08:55 UTC, bernhardoj commented
> A whisper shows as the last action, but the report lastVisibleActionCreated is not updated (BE issue)

This is resolved

> Close and reopen the report, OpenReport sends the resolved whisper created as the report lastVisibleActionCreated.

This is not.

2025-01-13 20:44 UTC, ishpaul777 approved these changes
LGTM!

2025-01-15 03:37 UTC, bernhardoj commented
done

2025-01-15 17:36 UTC, youssef-lr commented
can we fix eslint errors?

2025-01-16 08:05 UTC, bernhardoj commented
Fixed lint

2025-01-16 15:28 UTC, dangrous requested changes
ugh that new lint rule makes these very hard to review. I _think_ the actual code diff looks good! One minor change and then should be good on my end

2025-01-16 15:28 UTC, dangrous commented on src/libs/ReportActionsUtils.ts
> + * Checks whether an action is actionable track expense.
add a `@param` here

2025-01-17 01:55 UTC, bernhardoj commented on src/libs/ReportActionsUtils.ts
> + * Checks whether an action is actionable track expense.
Actually, we don't need the @param since we are no longer using JSDoc after migrating to TS. The other two above already have it.

2025-01-17 19:40 UTC, youssef-lr commented
Conflicts @bernhardoj

2025-01-18 02:21 UTC, bernhardoj commented
Fixed

2025-01-21 02:55 UTC, bernhardoj commented
@youssef-lr @ishpaul777 fixed

2025-01-21 16:19 UTC, dangrous submitted a review, later dismissed
LGTM! One Typescript question I'm curious about - not a blocker though!

2025-01-21 16:19 UTC, dangrous commented on src/libs/ReportActionsUtils.ts
> +): reportAction is ReportAction<
NAB - for this one and the ones similar to it... How does this return type work? It's just explaining that the function will return whether or not the reportAction is of those types? Is it so that other parts of the code can know that the reportAction is/isn't those types, outside of our actual logic that says that?

I think it makes sense, it's just hard to wrap my brain around the Typescript of it.

2025-01-21 16:31 UTC, bernhardoj commented on src/libs/ReportActionsUtils.ts
> +): reportAction is ReportAction<
> https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

Yes. This is used for a generic type. For example, `isActionableTrackExpense` will return a boolean whether `reportAction` is of type `ReportAction<typeof CONST.REPORT.ACTIONS.TYPE.ACTIONABLE_TRACK_EXPENSE_WHISPER>` or not. If we return `true`, then the report action inside the `if` block will have a type of `ReportAction<typeof CONST.REPORT.ACTIONS.TYPE.ACTIONABLE_TRACK_EXPENSE_WHISPER>`.

here is the ts doc for it: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

2025-01-21 16:49 UTC, dangrous commented
@ishpaul777 I think the reviewer checklist must have changed since you filled it out, mind updating with the latest so the check is happy?

2025-01-21 22:25 UTC, dangrous commented
Great. @youssef-lr all yours, though I think you may be out sick? I can merge tomorrow if you're still not around. I hope you feel better!

2025-01-22 20:45 UTC, dangrous commented
oh noooo i was coming in here to merge, but looks like we have conflicts now. @bernhardoj mind handling those?

2025-01-23 02:48 UTC, bernhardoj commented
@dangrous fixed

2025-01-23 14:23 UTC, dangrous approved these changes
LGTM!

2025-01-23 22:25 UTC, merged

2025-01-23 22:33 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2025-01-28 14:43 UTC, pecanoro commented
I think this PR caused this bug [here](https://github.com/Expensify/App/issues/55855).

2025-01-29 15:33 UTC, dangrous commented
@ishpaul777 @bernhardoj I know you partially reverted this PR to fix that bug ^ - do we need a new fix for this, or are we good?

2025-01-30 14:01 UTC, bernhardoj commented
I explained the [root cause of that issue on the PR](https://github.com/Expensify/App/pull/55895#discussion_r1933111553) and provided a proper fix without partially reverting the PR.

2025-01-30 14:46 UTC, dangrous commented
Ah okay great!