search router polish
Expensify/App pull request #50883
Opened 2024-10-16 11:27 UTC by 289Adam289

### Details

This pr fixes following problems mentioned in https://github.com/Expensify/App/issues/50250:
 - parsing error with special characters
 - amount display value in cents
 - improve performance od filter validation
### Fixed Issues

https://github.com/Expensify/App/issues/50250
$
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-10-18 08:31 UTC, SzymczakJ approved these changes
LGTM 🚀

2024-10-18 09:22 UTC, 289Adam289 commented
@rayane-djouah I am not sure why but no reviewer has been assigned to this pr. You have reviewed https://github.com/Expensify/App/pull/49838 and I think you can review this one as a follow up pr to https://github.com/Expensify/App/pull/49838.

2024-10-18 10:41 UTC, rayane-d reviewed
.

2024-10-18 15:36 UTC, luacmartins reviewed
Nice changes. Was the link dropping issue a parsing problem?

2024-10-18 15:36 UTC, luacmartins commented on src/libs/SearchUtils.ts
> +                .find((filter) => filter.operator === 'lt' && validateAmount(filter.value.toString(), 0, CONST.IOU.AMOUNT_MAX_LENGTH + 2))
Maybe we can add a comment on why we're using `CONST.IOU.AMOUNT_MAX_LENGTH + 2`

2024-10-21 08:22 UTC, 289Adam289 commented
Yes, the link dropping issue was a parsing problem. When you pasted the link parsing error occurred and router navigated to search page with the last query without error.

2024-10-21 21:07 UTC, luacmartins commented
@289Adam289 we have conflicts and some tests are failing

2024-10-21 21:37 UTC, luacmartins reviewed
@289Adam289 we have conflicts and some tests are failing

2024-10-22 15:45 UTC, luacmartins submitted a review, later dismissed
LGTM and tests well. @rayane-djouah let's prioritize reviewing this one

2024-10-22 15:45 UTC, luacmartins commented on src/libs/SearchParser/baseRules.peggy
> +_ "whitespace" = [ \t\r\n]*
NAB add empty line at end of file

2024-10-22 23:37 UTC, rayane-d requested changes

2024-10-22 23:48 UTC, luacmartins commented
We also have conflicts now

2024-10-23 09:20 UTC, 289Adam289 commented
@rayane-djouah I fixed both bugs and resolved conflicts

2024-10-23 17:52 UTC, luacmartins submitted a review, later dismissed

2024-10-23 19:09 UTC, luacmartins commented
all yours @rayane-djouah

2024-10-24 16:37 UTC, 289Adam289 commented
I gave it a try and I think it works. Unit tests pass but further testing is needed because I've heavily changed important rules. cc @rayane-djouah

2024-10-24 19:23 UTC, luacmartins approved these changes
LGTM. I did some testing on the latest grammar and it seems to be working well. All yours @rayane-djouah

2024-10-25 21:51 UTC, rayane-d approved these changes
Works well

2024-10-25 22:07 UTC, merged

2024-10-25 22:18 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-10-29 14:05 UTC, dangrous commented
Hi! I haven't confirmed yet but it seems like this is related to https://github.com/Expensify/App/issues/51661 - can you take a quick look?

2025-07-18 18:26 UTC, shubham1206agra commented on src/libs/SearchQueryUtils.ts
> +        filter.filters.sort((a, b) => localeCompare(a.value.toString(), b.value.toString()));
Mark for ref

2026-03-17 08:16 UTC, DylanDylann commented on src/libs/SearchQueryUtils.ts
> +            const backendAmount = CurrencyUtils.convertToBackendAmount(Number(filter));
This change caused https://github.com/Expensify/App/issues/79934, 


> This PR added amount-to-cents conversion (convertToBackendAmount) to the findIDFromDisplayValue function in src/libs/SearchQueryUtils.ts. The PR's intent was to fix "amount display value in cents," but this function was already being called for all search submissions from SearchRouter.tsx — including clicks on recent search items.