[Pending on design doc][Self-guided tours][V2] Add tour links to onboarding tasks
Expensify/App pull request #51153
Opened 2024-10-21 06:09 UTC by c3024

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/50926
PROPOSAL: N/A

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-10-28 01:11 UTC, rushatgabhane requested changes

2024-10-28 01:29 UTC, rushatgabhane approved these changes

2024-10-28 03:55 UTC, dubielzyk-expensify commented
Visually looks good to me 👍

2024-10-28 07:12 UTC, c3024 commented on src/CONST.ts
> +    autoCompleted: false,
We drop the user to Concierge chat after selecting onboarding choice. At that point of time, the user still has not seen the tour yet. So, this should be `false`.

2024-11-04 18:38 UTC, mountiny reviewed
@c3024 @rushatgabhane couple small comments

2024-11-04 18:38 UTC, mountiny commented on src/libs/API/types.ts
> +    [WRITE_COMMANDS.SELF_TOUR_VIEWED]: null;
This is not invoice API, can you move it to a more appropriate section please?

2024-11-04 18:38 UTC, mountiny commented on src/libs/onboardingSelectors.ts
> +    }
Given [this answer](https://expensify.slack.com/archives/C07HPDRELLD/p1730505334480879?thread_ts=1730161036.738369&cid=C07HPDRELLD), I think that if the onboarding NVP is not set yet, so old account, we still want to show them the tour option. 
```suggestion
    if (Array.isArray(onboarding)) {
        return false;
    }
```

2024-11-04 21:20 UTC, mountiny commented
@c3024 please merge main

2024-11-05 01:26 UTC, c3024 commented
@mountiny 

Merged `main` but tasks are rejected by backend when the intent selected is "Personal Spend" on `main`.



https://github.com/user-attachments/assets/f2e7526d-ac75-4e71-8170-8b4111f73fb5

2024-11-05 03:37 UTC, dubielzyk-expensify approved these changes
LGTM

2024-11-05 08:45 UTC, mountiny approved these changes
Thanks

2024-11-05 08:45 UTC, merged

2024-11-05 08:56 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-12-06 19:12 UTC, brunovjk commented
We did not include `selfGuidedTourTask` in the`combinedTrackSubmitOnboardingPersonalSpendMessage` leading to this [issue](https://github.com/Expensify/App/issues/52985).

2025-04-02 15:13 UTC, tgolen commented on src/CONST.ts
> +const selfGuidedTourTask: OnboardingTaskType = {
@c3024 @mountiny Is there a reason these objects were put in `CONST.ts`? I feel that this is not the right file for putting message templates. Would anyone mind if I open an issue to have these moved somewhere else so that we only keep `CONST`s in this file?

2025-04-02 15:21 UTC, c3024 commented on src/CONST.ts
> +const selfGuidedTourTask: OnboardingTaskType = {
Task titles and descriptions for onboarding tasks were in this file when we added this task. Extracted them to an object because this is repetitive for several onboarding intents.

>Would anyone mind if I open an issue to have these moved somewhere else so that we only keep CONSTs in this file?

Not at all, sounds like a good idea!

2025-04-03 17:34 UTC, mountiny commented on src/CONST.ts
> +const selfGuidedTourTask: OnboardingTaskType = {
Yep agreed, we can move anything dynamic out of this file to keep it purely consts