Enable/disable per diem rates
Expensify/App pull request #51232
Opened 2024-10-22 09:45 UTC by shubham1206agra

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/50862

### Tests

Pre-requisite
Make sure you are on `newDotPerDiem` beta before testing this feature.

1. Go to the workspace where you want to enable per diem feature.
2. Go to More Features.
3. Toggle the Per diem under spend to enable/disable the feature.
4. Make sure that if you are on paid workspace, it is asking you to upgrade the workspace.
5. Make sure you can go to the per diem page.

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as Tests

### QA Steps

Same as Tests

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/a22461ba-2a82-434b-b8ed-738d9e9dd03b

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/2a1ccd9c-aabb-4a2a-a127-dbf71d8ce5a4

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/94259899-d938-4c33-a2f7-bf97f5dcd326

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user- [...]

2024-10-24 02:45 UTC, c3024 commented
@shubham1206agra 

Can you please share the extract of the design doc?

2024-10-24 11:16 UTC, Gonals commented
Shared

2024-10-31 07:20 UTC, c3024 commented
Upgrade screen has a styling issue.

<img width="1440" alt="Screenshot 2024-10-31 at 12 49 16 PM" src="https://github.com/user-attachments/assets/0dc58e85-44db-4bab-9bf0-8c90e80f71ce">


Works fine on `main`

<img width="1440" alt="Screenshot 2024-10-31 at 12 48 08 PM" src="https://github.com/user-attachments/assets/89e185bd-ac2a-4582-a4b8-0a4f1e34ab9f">

2024-10-31 08:20 UTC, c3024 reviewed
Some minor comments.

2024-10-31 08:20 UTC, c3024 commented on src/languages/en.ts
> +            subtitle: 'Set per diem rates to control daily employee spend.',
Few strings like "Set per diem rates to control daily employee spend." and "Per diem" are repeated to match the UI. Wondering if it'd be easier to update later if we use one variable perhaps here in `common` and use it wherever required.

2024-10-31 08:20 UTC, c3024 commented on src/libs/actions/Policy/PerDiem.ts
> +function generateCustomUnitID(): string {
How about using the `generateCustomUnitID` function in the `PolicyUtils` instead of creating a new one here?

2024-10-31 08:20 UTC, c3024 commented on src/libs/actions/Policy/PerDiem.ts
> +    const doesCustomUnitExists = !!customUnitID;
```suggestion
    const doesCustomUnitExist = !!customUnitID;
```

2024-10-31 08:20 UTC, c3024 commented on src/pages/workspace/perDiem/WorkspacePerDiemPage.tsx
> +// import {deleteWorkspaceCategories, setWorkspaceCategoryEnabled} from '@userActions/Policy/Category';
```suggestion

```

2024-10-31 08:20 UTC, c3024 commented on src/pages/workspace/perDiem/WorkspacePerDiemPage.tsx
> +// import ROUTES from '@src/ROUTES';
```suggestion
```

2024-10-31 08:20 UTC, c3024 commented on src/pages/workspace/perDiem/WorkspacePerDiemPage.tsx
> +                    // errors: value.errors ?? undefined,
```suggestion
```

2024-10-31 08:20 UTC, c3024 commented on src/pages/workspace/perDiem/WorkspacePerDiemPage.tsx
> +        // deleteWorkspaceCategories(policyID, selectedPerDiem);
```suggestion
```

2024-10-31 08:22 UTC, c3024 commented
Looks like until the API is implemented, all we can do is visually check the page. There are no functional buttons or menus on the per diem page yet.

The code changes look fine.

I will test and update if I find anything.

2024-10-31 08:36 UTC, c3024 commented
>Can you check again since I didn't touched the upgrade pages?

Oh. Checked again. This works well now.

2024-10-31 08:54 UTC, c3024 commented
Navigating to the per diem page through deeplink shows a Not Found page.


https://github.com/user-attachments/assets/86c72db9-04d1-4006-b7f3-246b3e945f88

2024-10-31 09:25 UTC, shawnborton commented
Visually it looks pretty good to me from a design perspective, good finds on those small bugs too. I'm running a test build so I can take it for a spin as well.

2024-10-31 09:52 UTC, c3024 commented
>Can you confirm if this happens with per diem only?

Only for per diem. "Rules" page works well.

https://github.com/user-attachments/assets/19c90ff1-b34f-4176-bfb1-10a52fb240e0

2024-10-31 11:01 UTC, c3024 commented
>I am not seeing this problem. Have you enabled this feature for that workspace?

Yes. But on logging back in it gets disabled.

Does this need the beta enabled on backend?

2024-10-31 13:29 UTC, dannymcclain commented
So far it's looking good visually (web ad hoc build). Seems like testing is kind of limited at the moment since most of the stuff isn't interactive. But so far so good!

2024-10-31 16:27 UTC, shawnborton commented
Visually this is feeling good! Do we have a sample spreadsheet I can use to import some per diem rates?

2024-11-01 10:12 UTC, shawnborton commented
Ah, looks like maybe this PR is just about enabling/disabling the feature - I don't think I can actually upload anything yet. 

Anyways, I think this is all good from a design perspective at least.

2024-11-04 16:03 UTC, Gonals commented
> Ah, looks like maybe this PR is just about enabling/disabling the feature - I don't think I can actually upload anything yet.

Correct

2024-11-04 16:04 UTC, Gonals commented
> Does this need the beta enabled on backend?

There shouldn't be any beta checks in the BE

2024-11-05 06:23 UTC, c3024 commented
@shubham1206agra 

With reference to [this](https://github.com/Expensify/App/pull/51232#issuecomment-2450211922), upon logging back in, the backend responses do not include the per diem value as enabled for the policy. Is this expected for now and not a blocker for this PR? It is not related to front-end changes.



https://github.com/user-attachments/assets/f508333a-cb5f-471c-be90-32785e0751fc

2024-11-05 10:59 UTC, Gonals commented
> @Gonals The policy is not returning `arePerDiemEnabled` property. Can you fix this?

Looking into it

2024-11-05 11:02 UTC, Gonals commented
> @Gonals The policy is not returning `arePerDiemEnabled` property. Can you fix this?

They are not returning it because this is not a property Policies have.
Instead, we should create a frontEnd helper function that:
- Checks if the policy has an `International Per Diem` Custom unit
- If so, checks if the Custom Unit is enabled.

2024-11-05 11:12 UTC, Gonals commented
> > > I don't think so its a good idea. Since we always use these markers to obtain access the page, and deeplinking to any of those pages will cause problem as we need to calculate these properties.
> > 
> > 
> > I'm not sure I follow. What problems would it cause?
> 
> It will show not found page if the customUnits are not loaded yet. And we use different API to fetch these variables than customUnits.

Ok. Let me take a look and see how I can fix this from the BE

2024-11-05 12:49 UTC, c3024 commented
Uploading csv from OldDot throws an error.

```js
{
    "jsonCode": 0,
    "message": "Expensify\\Policy\\CustomUnit::setAttributes(): Argument #1 ($attributes) must be of type array, string given, called in \/var\/www\/expensify.com\/ee6c06fd6ad\/lib\/Policy\/CustomUnit.php on line 93",
    "requestID": "8ddcf0f1fb822e11-BOM"
}
```

So, while the PR has made a lot of changes, only the page enablement and the initial page can be tested now. If this is merged now, we need to make a followup PR to test these pages again once backend changes are done.

2024-11-06 14:51 UTC, Gonals commented
`arePerDiemRatesEnabled` should now be returned from the backend. The Web-E PR has yet to merge, but the Auth PR is deployed and should be enough for this flow. You might need to log out/back in.
@shubham1206agra

2024-11-06 15:32 UTC, c3024 commented
It works well now.

I will complete the checklist with testing enabling/disabling and the initial page display.

I guess we will make another PR uncommenting the pending parts of this PR after backend changes are deployed. Then I will test remaining parts in that PR.

2024-11-06 15:34 UTC, c3024 commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>Android: mWeb Chrome</summary>

<!-- add screenshots or videos here -->

</details>

<details>
<summary>iOS: Native</summary>

<!-- add sc [...]

2024-11-06 15:37 UTC, c3024 commented
@shubham1206agra 

Spanish translations are not added?

2024-11-06 15:46 UTC, Gonals commented
> It works well now.
> 
> I will complete the checklist with testing enabling/disabling and the initial page display.
> 
> I guess we will make another PR uncommenting the pending parts of this PR after backend changes are deployed. Then I will test remaining parts in that PR.

Which parts are commented out?

2024-11-06 15:52 UTC, c3024 commented
>Which parts are commented out?

Importing spreadsheet, opening settings, subrates etc. in WorkspacePerDiemPage.

2024-11-06 15:53 UTC, c3024 commented
> @c3024 Yeah. Since I didn't received them yet.

I think you can update them with Spanish translate GPT and @Gonals can confirm them.

2024-11-06 16:04 UTC, Gonals commented on src/languages/es.ts
> +            perDiem: 'Dieta',
`Per diem`

Let's keep the latin

2024-11-06 16:04 UTC, Gonals commented on src/languages/es.ts
> +            subtitle: 'Establece las tasas de dieta para controlar los gastos diarios de los empleados.',
Establece las tasas per diem para controlar los gastos diarios de los empleados.

2024-11-06 16:06 UTC, Gonals commented on src/languages/es.ts
> +                title: 'Dietas',
Per diem

2024-11-06 16:06 UTC, Gonals commented on src/languages/es.ts
> +                subtitle: 'Establece las tasas de dieta para controlar los gastos diarios de los empleados.',
Establece las tasas per diem para controlar los gastos diarios de los empleados.

2024-11-06 16:07 UTC, Gonals commented on src/languages/es.ts
> +                title: 'Dietas',
Per diem

2024-11-06 16:07 UTC, Gonals commented on src/languages/es.ts
> +                    'Las dietas (ej.: $100 por día para comidas) son una excelente forma de mantener los costos diarios predecibles y conformes con las políticas de la empresa, especialmente si tus e
Las dietas per diem (ej.: $100 por día para comidas) son una excelente forma de mantener los gastos diarios predecibles y ajustados a las políticas de la empresa, especialmente si tus empleados viajan por negocios. Disfruta de funciones como tasas personalizadas, categorías por defecto y detalles más específicos como destinos y subtasas.

2024-11-07 07:40 UTC, shawnborton commented
cc @bfitzexpensify - what's the correct help article URL for this?

2024-11-07 08:12 UTC, bfitzexpensify commented
https://help.expensify.com/articles/expensify-classic/workspaces/Enable-per-diem-expenses

2024-11-07 08:21 UTC, shawnborton commented
Do we have one ready for NewDot though? Also, where is this link shown exactly @shubham1206agra ?

2024-11-07 08:26 UTC, bfitzexpensify commented
Sorry, completely missed the ND portion, need to have my coffee. 

We don't have ND help docs up yet - opened https://github.com/Expensify/Expensify/issues/442420 to get them sorted, should take me a day or two. 

We don't need that to be a blocker for this, I can open a PR to update the link once the help docs are ready.

2024-11-07 08:32 UTC, c3024 commented
@bfitzexpensify 

>need to have my coffee.

This PR has other things apart from the link. I think this PR should not be closed.

2024-11-07 08:52 UTC, c3024 requested changes

2024-11-07 08:52 UTC, c3024 commented on src/languages/en.ts
> +                onlyAvailableOnPlan: 'Per diem are only available on the Control plan, starting at ',
```suggestion
                onlyAvailableOnPlan: 'Per diem is only available on the Control plan, starting at ',
```

NIT: Google say plural for per diem is per diems.

So, this in `onlyAvailableOnPlan` might need to be confirmed if this should be "Per diems are" or "Per diem is" or retain as it is.

2024-11-07 08:52 UTC, c3024 approved these changes
Tested the enabling/disabling and view of the per diem page. LGTM!

2024-11-07 10:28 UTC, Gonals commented
Neat! Let's merge! @shubham1206agra, send the PRs with the rest of the functionality (importing/exporting/setting default category) my way when they are ready. I'll test with the backend and deploy the backend PRs accordingly

2024-11-07 10:29 UTC, Gonals approved these changes

2024-11-07 10:31 UTC, Gonals approved these changes

2024-11-07 10:31 UTC, merged

2024-11-07 10:41 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.