Open reports at first unread action
Expensify/App pull request #51366
Opened 2024-10-23 21:40 UTC by janicduplessis

### Details

### Fixed Issues

$
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2025-01-28 16:30 UTC, janicduplessis commented
I have a UX question here, where do we want the scroll of the list to open at? Currently it opens the chat where the new message is aligned at the bottom so like this:

<img width="1015" alt="image" src="https://github.com/user-attachments/assets/c745242e-54f9-46e8-aefd-da30cfd10429" />

But it could also be aligned at the top so we see more new messages instead of old ones, like this:

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/756192ad-d15a-4739-8ba0-b8fe26f83d8f" />

2025-01-28 17:48 UTC, shawnborton commented
> But it could also be aligned at the top so we see more new messages instead of old ones, like this:

I personally like this, but I think I would prefer to let an older message slightly peak out from above so there is a little more context that you are starting from a certain point. So basically what you have but maybe push down the starting point by like 56px or 64px or something like that.

2025-01-28 23:54 UTC, dubielzyk-expensify commented
+1 to that. Always like it when we peek content to show that there's more there

2025-02-02 10:06 UTC, ikevin127 commented
@janicduplessis First of all, props for picking up this veteran difficulty level issue, doing such great work on it so far and getting it so close to completion 🚀

##

👋 Please tag me before merging this in case I don't get notified becasuse I'd like to run some tests myself to make sure this works as expected, I have 2 scenarios in mind:

- opening a report for the **first time on fresh login, with 300-500 unread new messages**
- opening a report for the **first time on fresh login where the last read message was deleted in the meantime**

**Note:** I'm one of the contributors which attempted to fix this from FE only but ultimately figured out it won't work and [suggested](https://github.com/Expensify/App/issues/35011#issuecomment-2166665657) a BE + FE implementation discussion months ago before **Rory** went on parental leave.

**How did I get here ?** Another C+ reviewer [asked](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1738418444919069) just yesterday about an issue on Slack, which will basically be fixed by this PR - that's how I remembered this 1 year old issue and decided to join the testing effort as well since I have some context on this.

**Note:** No compensation needed, just want to help 👍

2025-02-22 19:47 UTC, janicduplessis commented
This is ready for review and further testing. Sadly adjusting the scroll position so the newest message is near the top ended up very difficult with the way we handle opening the list in the middle of a chat. I think we should punt that for later since this is already taking longer than I would have liked.

2025-02-26 01:22 UTC, janicduplessis commented on src/pages/home/report/ReportActionsList.tsx
> +                viewOffset: -64,
This is actually not needed anymore, since scrolling the view like this didn't end up working. Will remove.

2025-02-26 01:38 UTC, janicduplessis commented on src/pages/home/report/ReportActionsList.tsx
> +                viewOffset: -64,
This is actually not needed anymore.

2025-02-26 05:48 UTC, ikevin127 approved these changes
♻️ **Reporting on my previous [comment](https://github.com/Expensify/App/pull/51366#issuecomment-2629327822):**
- ✅ **opening a report for the first time on fresh login, with 300-500 unread new messages**: works well, tested both with fresh login and Clear cache and reset
- ✅ **opening a report for the first time on fresh login where the last read message was deleted in the meantime**: works well, looks like the current behaviour is that when the last read message is deleted, the one underneath (right below) will become the last read 👍 

🗒️ **Notes**:
- I only tested on web-based platforms (Web / mWeb / Desktop)
- I did not fully test the manual `Mark as unread` functionality but from the test mentioned above it seems to work as expected 👍

2025-03-04 22:14 UTC, ishpaul777 commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified that the composer does not automatically focus or open the keyboard on mobile unless explicitly intended. This includes checking that returning the app from the background does not unexpectedly open the keyboard.
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] For any bug fix or new feature in this PR, I verified that sufficient [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) are included to prevent regressions in this flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expect [...]

2025-03-11 13:52 UTC, rlinoz commented
Hey @janicduplessis were you able to take a look at the 2 issues?

2025-03-11 16:19 UTC, janicduplessis commented
Hey, sorry I wasn’t available last week, I should be able to have a look soon

2025-03-15 21:10 UTC, janicduplessis commented
@rlinoz @ishpaul777 I pushed a fix, can you check if it fixes both issues?

What happens is when we load the chat list, we get the latest message of each chat. Normally we display that message while loading the rest of the chat. However now that we open at last unread, this message might not be the one we open at. What I did is stay in loading state if the chat is unread and we only have 1 message (assume it came from cache from loading the chat list).

2025-03-18 13:12 UTC, rlinoz commented
I think that should be fine, I will give it a try today.

2025-03-18 15:31 UTC, rlinoz commented
Regarding that same flow, I think I found a bug:

1. Have a new chat unread
2. Go offline
3. Open the chat
4. Go back online
5. Chat loads but can't scroll

https://github.com/user-attachments/assets/b94fac53-f2d8-45ce-80fe-0ad8153a81ea

2025-03-20 13:30 UTC, rlinoz commented
Hey @chrispader since you are working on this one now, did you get a chance to check my comment above?

2025-03-20 14:48 UTC, chrispader commented
not yet. will look into it tmrw morning!

2025-03-25 17:03 UTC, chrispader commented
> Regarding that same flow, I think I found a bug:
> 
> 1. Have a new chat unread
> 2. Go offline
> 3. Open the chat
> 4. Go back online
> 5. Chat loads but can't scroll

Hmm @rlinoz i cannot repro this. Did i miss anything here?

https://github.com/user-attachments/assets/985e56f7-f607-4bc2-a5e7-72b3d8c9d0fa

2025-03-25 17:42 UTC, rlinoz commented
Hmm your chat didn't open at the first message, do you know why?

2025-03-26 14:26 UTC, chrispader commented
> Hmm your chat didn't open at the first message, do you know why?

I think this should be fixed now. I'm not sure if i'm causing issues with something @janicduplessis had in mind about https://github.com/Expensify/App/pull/51366/commits/4442d2d86b8a344201a9bc84e7a92cab7ca8b621

@janicduplessis do we necessarily check for whether there are no or only one report action in cache? Or did you just want to check whether the chat is initially loading?

2025-03-26 14:27 UTC, chrispader commented
I'm not sure if i'm causing issues with something @janicduplessis had in mind about https://github.com/Expensify/App/pull/51366/commits/4442d2d86b8a344201a9bc84e7a92cab7ca8b621

@janicduplessis do we necessarily check for whether there are no or only one report action in cache? Or did you just want to check whether the chat is initially loading?

2025-03-27 10:11 UTC, rlinoz commented
This was his reasoning for that commit https://github.com/Expensify/App/pull/51366#issuecomment-2727001626

I think it was fixing this issue: https://github.com/Expensify/App/pull/51366#issuecomment-2698863607

2025-03-28 16:56 UTC, chrispader commented
Okay so i think we have a couple of other issues right now:

1. The report is currently marked as read once we go to the chat even when the user is offline and there (might) be newer report actions, that aren't visible yet. I'll have to look into this more tomorrow, but it seems this is not necessarily caused by this PR or might extend the scope of this issue.
2. Sometimes the chat still does not scroll to the last unread comment. I cannot repro this 100% accurately yet, but it definitely happens from time to time

Will try to get some more context on this tomorrow!

2025-04-01 13:53 UTC, rlinoz commented
Hey @chrispader did you get a chance to get to this one?

2025-04-01 21:28 UTC, chrispader commented
@rlinoz not quite! Will hopefully be able to continue working on this on thursday!

I'm at a React Native Conference tomorrow, so i won't have much time, but hopefully the day after

2025-04-09 07:00 UTC, chrispader commented
hey @rlinoz sorry, i got sick in the meantime. Will try to get this done by the end of the week, once i'm out of bed again

2025-04-09 13:11 UTC, rlinoz commented
Hope you feel better soon!

2025-04-16 13:26 UTC, chrispader commented
Looking into this now!

2025-04-16 20:25 UTC, chrispader commented
@rlinoz @janicduplessis is it the expected behaviour, that only one element is rendered initially when a report hasn't been opened yet? After that we would continue rendering the rest, and then scroll to the first unread message?

Or should all (initial) message be rendered from the beginning and or just N number of elements before/after the linked report action (`initialScrollKey`).

Currently, we would slice the `data` from the index of the linked report action (last one in the array), which means that we only render one element initially. This also messes up the jumping to the first unread action

2025-04-17 13:04 UTC, rlinoz commented
> is it the expected behaviour, that only one element is rendered initially when a report hasn't been opened yet? 

I feel like this was more of a limitation than wanted behavior, so no need to keep it.

> Or should all (initial) message be rendered from the beginning and or just N number of elements before/after the linked report action (initialScrollKey).

Are you saying if we have 100 messages and haven't read starting on the 50th, we would render the 50th message along with the 25 previous messages and the 25 next messages?

2025-04-17 20:09 UTC, chrispader commented
> I feel like this was more of a limitation than wanted behavior, so no need to keep it.

okay thanks. i'll further check with @janicduplessis so i don't mess anything up here.
 
> Are you saying if we have 100 messages and haven't read starting on the 50th, we would render the 50th message along with the 25 previous messages and the 25 next messages?

Yes, so my idea instead of just slicing the dataset from the beginning would be to initially slice the array to a size similar to the pagination size, which holds all the initially visible items.

So right now, since the selected unread message is (usually) displayed at the bottom of the screen, i would render N number of elements before that. If it were at the beginning of the screen, we would need to include elements after that. If it were in the middle of the screen, we would need both.

I'm not sure if this is too easy to implement, but the logic is definitely messed up right now with new unread reports

2025-04-20 10:18 UTC, chrispader commented
@rlinoz @janicduplessis i just pushed a fix for the issue with unread reports where the first message is unread.

Basically the problem is, that when a message within the first page is unread and is the once we want to display initially, it will still get shifted up by new messages, because the page is getting filled up by other elements due to the layout and styling of the ReportScreen. The number of elements per page depends on the window height on web, therefore we cannot really calculate easily how many items exactly are in a page, therefore i'm just using the hardcoded `CONST.PAGINATION_SIZE` for this fix.

The fix for this will basically just manually scroll to the end of the list if one of the first messages is the unread one and once more than a page of items are loaded. @janicduplessis could you maybe give this fix (latest commit) a quick review and let me know if this makes sense to you?

2025-04-22 13:10 UTC, chrispader commented
> @chrispader do you have a video of this working? I am not sure I understood how this is gonna work

i'll upload a video in a bit

2025-04-22 16:12 UTC, chrispader commented
https://github.com/user-attachments/assets/55a02ffe-b786-4c05-9370-ee5e70761430

2025-04-22 16:19 UTC, rlinoz commented
Ah nice, that behavior does look correct to me

2025-04-23 10:17 UTC, chrispader commented
> Ah nice, that behavior does look correct to me

Cool. @rlinoz can we give this PR a final review and hopefully merge it soon! :)

2025-04-23 12:58 UTC, rlinoz commented
Sure, I think there are a few failing tests/typechecks though, can you check?

I will review today, please do the same if you can @ishpaul777

2025-04-24 15:19 UTC, chrispader commented
> Sure, I think there are a few failing tests/typechecks though, can you check?
> 
> I will review today, please do the same if you can @ishpaul777

@rlinoz fixed both the typechecks and updated the test. The test assertion needed to be updated, since we're now displaying less report actions when we go to a report with unread message

2025-04-24 20:51 UTC, rlinoz commented
Hey @chrispader this is going pretty well!

Opening report while logged in ✅ 
Opening report offline ✅ 
Marking some message as unread and opening the report again ✅ 

Found this bug though:

1. [User A] Logout
2. [User B] Send messages in the report
3. [User A] Log back in
4. Not sure what happens, but can't scroll to the last message even though it shows up in the LHN.

https://github.com/user-attachments/assets/21bd45e1-8ed8-4bca-b79e-9922eab7fd50

2025-04-25 11:15 UTC, chrispader commented
> Hey @chrispader this is going pretty well!
> 
> Opening report while logged in ✅ Opening report offline ✅ Marking some message as unread and opening the report again ✅
> 
> Found this bug though:
> 
> 1. [User A] Logout
> 2. [User B] Send messages in the report
> 3. [User A] Log back in
> 4. Not sure what happens, but can't scroll to the last message even though it shows up in the LHN.
> 
>  Screen.Recording.2025-04-24.at.17.47.56.mov

Hmm, are there any additional repro steps? Did you send messages in an already existing report or a new one, that you created while user a was offline?

I cannot reproduce this atm. This is how it looks for both an existing and new report:


https://github.com/user-attachments/assets/92e53823-a48c-4209-9015-c58d6c9820bf

(scaled the video down a bit sorryyy)

2025-04-25 13:45 UTC, rlinoz commented
I think it has to have more messages, our page I think is 50 messages, so at least more than that.

Adding this to `addUtilsToWindow`
```
        window.addActions = (reportID: string) => {
            Array.from({length: 250}, (_, i) => i + 1).forEach((action) => {
                addComment(reportID, action.toString());
            });
        };
```

Run it from who is sending the comments then log in into the other account seems to do it for me, you gotta wait for the network requests to finish though.

2025-04-26 10:46 UTC, chrispader commented
> I think it has to have more messages, our page I think is 50 messages, so at least more than that.

Ahh yea i see the problem now. I'm still getting the last 50 paginated items from the backend on the initial`OpenReport`, even though the request is sent with `useLastUnreadReportAction: true` and `clientLastReadTime: <empty_string>`. Therefore, we aren't able to find the report action by the `unreadMarkerReportActionID`.

Can we check if there is an error in the backend code and/or if `clientLastReadTime` should be an empty string rather than undefined (not defined in the request payload)? Not sure if we check for that on the backend...

2025-04-28 13:34 UTC, rlinoz commented
I mean, `OpenReport` seems to be returning the previous 25 already read messages and the next 25 unread messages, is that not what you are seeing?

2025-04-28 13:53 UTC, chrispader commented
> I mean, `OpenReport` seems to be returning the previous 25 already read messages and the next 25 unread messages, is that not what you are seeing?

For new reports, that have not been read before (`clientLastReadTime: <empty_string`) i always get the last 50 items right now

2025-04-28 14:05 UTC, rlinoz commented
I think we are talking about 2 different issues, and what you found is a different bug.

Your bug comes from the fact that OpenReport is currently markign the report as read if the `clientLastReadTime

2025-04-28 15:17 UTC, rlinoz commented
It looks like that happens because we call `ReadNewestAction` before calling `OpenReport` 
<img width="529" alt="image" src="https://github.com/user-attachments/assets/30e015eb-ec48-4751-8dc9-ab7f13745e2d" />

2025-04-29 16:54 UTC, chrispader commented
> It looks like that happens because we call `ReadNewestAction` before calling `OpenReport`

i fixed this issue, but i'm still working on a better solution for the issue with opening a chat with an unread message on the first page of items. There are many edge cases with scrolling to the start of the chat, so i'll implement a better solution based on the height of the scrollable content and container height

2025-04-29 21:06 UTC, chrispader commented
I've just improved and simplified the scrolling logic in `BaseInvertedFlatList`. By default, the list will not scroll to the unread message, unless it is on the first page of rendered items (within the first 25 items in the dataset)

I think all remaining issues should be fixed now!

2025-04-29 21:15 UTC, rlinoz commented
Great, thanks for the work here! I will test again tomorrow

2025-04-30 14:37 UTC, rlinoz commented
I think I am still seeing the same issue

https://github.com/user-attachments/assets/284cf28e-c1aa-497d-ab3b-9af45f3abb89

2025-05-05 07:00 UTC, chrispader commented
Looking into it again today!

2025-05-08 16:06 UTC, chrispader commented
> I think I am still seeing the same issue

Hmm, i still cannot reproduce this 🥴

I now even used Firefox on the receiving end (User A) but still, the messages are displayed in order and the chat starts loading with the first message visible.

Might this be due to your local backend (proxy) running? It seems like your result from `OpenReport` is giving you the last 50 messages in the chat, whereas it should provide the first 25 because of the `useLastUnreadReportAction` flag.


https://github.com/user-attachments/assets/d0831654-2145-4b44-8761-0f6a9f1b70b6

2025-05-08 16:12 UTC, chrispader commented
> I think I am still seeing the same issue
> 
>  Screen.Recording.2025-04-30.at.11.35.56.mov

@rlinoz also, is there a reason why your (new) chat is immediately focused once you login with User A?

2025-05-08 16:34 UTC, rlinoz commented
> @rlinoz also, is there a reason why your (new) chat is immediately focused once you login with User A?

Not that I know of, not sure about how that logic works.

@ishpaul777 do you mind taking it for a spin and see if you can reproduce the same bug that I see?

2025-05-11 20:05 UTC, chrispader commented
> i can reproduce this but in my case it eventually show the last message after few seconds

Hmm so to me it seems the behaviour is working correctly, but the latest messages are just taking forever to load, either because of bad internet connection or because other tasks are blocking the `GetNewerActions` request.

@rlinoz but your screen recording definitely looks different than the one from @rlinoz. @ishpaul777 could you maybe try this one more time with the network tab open on the left (receiving) client and check for the `GetNewerActions` request?

2025-05-14 11:47 UTC, rlinoz commented
@chrispader if you could take a look 🙏

2025-05-20 10:29 UTC, chrispader commented
> reproduced the exact issue as @rlinoz, no call made to `GetNewerActions` till I switched report and reopen it again

@rlinoz @ishpaul777 this issue should now be fixed. The problem was, that in `useLoadReportActions` we only allowed fetching `GeNewerActions` or `GetOlderActions` once unless it was forced. This is not applicable anymore, since the chat can start at any point in the chat and therefore we will need to be able to fetch newer/older messages multiple times

2025-05-20 10:30 UTC, chrispader commented
@rlinoz how do we want to handle marking unread messages as read. When some message in the middle of the chat is marked unread, do we immediately want to mark the report as read or does the user need to scroll until the last (unread) message in the chat?

2025-05-20 14:15 UTC, rlinoz commented
> When some message in the middle of the chat is marked unread, do we immediately want to mark the report as read once the chat opens or does the user need to scroll to the last (unread) message in the chat?

That is a good question. I think we should mark it as read once you open the report, but curious for others thoughts @Expensify/design @trjExpensify

2025-05-20 16:13 UTC, shawnborton commented
I feel like we would mark it as read once you have the new comment scrolled into view? Not sure what we currently do though.

2025-05-20 16:19 UTC, trjExpensify commented
I was going to ask, what do we currently do? I think it's probably out of scope to change that here.

2025-05-20 16:19 UTC, dannymcclain commented
>When some message in the middle of the chat is marked unread, do we immediately want to mark the report as read once the chat opens or does the user need to scroll to the last (unread) message in the chat?

Wouldn't the chat open with the unread message in view? Or no? I feel like we wouldn't mark the chat as read until the "new message" was in the viewport for the user, but I'm not sure I'm fully following here.

2025-05-21 12:49 UTC, rlinoz commented
From what I understand currently we mark the report as read as soon as an unread message is visible, is that correct @chrispader?

>  I think it's probably out of scope to change that here.

That makes sense to me.

2025-05-21 15:42 UTC, chrispader commented
> From what I understand currently we mark the report as read as soon as an unread message is visible, is that correct @chrispader?

The thing is that with this PR we open the report at the _first_ unread message. Therefore, there might be lots of later unread messages.

The current implementation would mark the report as unread right after it's opened, since it will always show the last message, which also always happens to be the last unread.

It would be easiest to just mark the report unread once opened, but we could think of some more intuitive approach, where we kind of update the unread marker based on up to which message the user scrolled. If the chat is scrolled up until the end, the whole report is marked as unread

cc @rlinoz @trjExpensify @dannymcclain @shawnborton

2025-05-22 00:51 UTC, dubielzyk-expensify commented
Think I'm mostly understanding, but apologies if not.

> It would be easiest to just mark the report unread once opened, but we could think of some more intuitive approach, where we kind of update the unread marker based on up to which message the user scrolled. If the chat is scrolled up until the end, the whole report is marked as unread

I kinda like the simplicity of the end there. Just updating it as unread when the last unread message is scrolled to. I don't mind the first one, but starting to measure which of, let's say, 10 messages, and then figure out where to measure unread, seems very complicated. 

Just my 2 cents 🤷‍♀️

2025-05-22 13:37 UTC, dannymcclain commented
>Just updating it as unread when the last unread message is scrolled to.

Yeah I think I'm still having a hard time following, but this seems to make sense to me.

2025-05-23 10:49 UTC, chrispader commented
Thanks for the feedback! Yes i also think just marking the report as unread once opened initially is the easies apraoch.

When the user receives a new message while in the chat the report will still only be marked unread once the user scrolls to the bottom. Additionally, when we load the report from the start or some arbitrary message and the user has more messages to load, the report will not be marked unread until the very last message has been scrolled to

2025-05-23 11:49 UTC, chrispader commented
Everything should be fully working now. Both loadings chats with and without unread messages, on both the initial load and later loads.

https://github.com/user-attachments/assets/f5e76305-6656-458b-96e0-bbab12dbd685

Also here you can see how the reports are marked as unread once we receive a new message while in the report:


https://github.com/user-attachments/assets/af0ae2e5-6224-4f56-a76f-57919aece885

2025-05-23 20:44 UTC, chrispader commented
@rlinoz @ishpaul777 still working on addressing the last failing test. Not sure yet if this is a problem with the test itself or if there is something going wrong in the code.

The problem in the test is that the chat title should switch from bold to normal font, but it somehow doesn't (early enough)

2025-05-28 16:23 UTC, rlinoz commented
Not a fresh account, steps are:

1. Open any DM
2. Mark one of the first messages as unread
3. Clear cache and restart
4. Open the DM again

2025-06-04 16:21 UTC, chrispader commented
> Not a fresh account, steps are:
> 
> 1. Open any DM
> 2. Mark one of the first messages as unread
> 3. Clear cache and restart
> 4. Open the DM again
> 
> If you want we can schedule a call and debug together.

@rlinoz @ishpaul777 this issue on Firefox should be fixed now. Could you please verify that it works for you too? 🙌🏼

2025-06-04 16:40 UTC, rlinoz commented
YES it is fixed!! 🎉 🙌

2025-06-04 20:02 UTC, rlinoz commented
Nice, I think we should move on with this PR and get it merged. @ishpaul777 can you prioritize testing this when you get a chance?

Then as a follow up work on opening expense reports with the table view at the last unread message as well, currently they open at the top, but that is true for this PR and prod.

cc: @trjExpensify since you pointed that out here https://github.com/Expensify/App/issues/35011#issuecomment-2890598187

2025-06-04 20:20 UTC, rlinoz commented
Once the checklist is done we should probably ask Applause to run tests on adhoc builds as well

2025-06-05 19:44 UTC, ishpaul777 commented
reviewing

2025-06-05 23:12 UTC, ishpaul777 commented
bug: it scrolls to wrong unread message after clear cache and restart and there is jitter when scrolling  start

https://github.com/user-attachments/assets/0e995b9d-3e30-4c90-a0a6-39495429b798

2025-06-05 23:20 UTC, ishpaul777 commented
this [comment](https://github.com/Expensify/App/issues/35011#issuecomment-2891633560) from @trjExpensify 

> if the expense report has an unread comment, we'd scroll to the unread comment. If not, the top of the report where the transaction table is in view

seems like this is not working it always scroll to the top of the table


https://github.com/user-attachments/assets/b8959498-2303-43e5-9b86-4ddc7bc732a4

2025-06-05 23:23 UTC, ishpaul777 commented
after clear cache and restart,  in a long chat direct comment linking to first message does not scroll the chat exactly to first message

 https://github.com/user-attachments/assets/b4307c50-cfe3-4f83-9c90-7fbbbfc18df0


Edit: i can repro on staging so its not a blocker

2025-06-06 13:12 UTC, rlinoz commented
> seems like this is not working it always scroll to the top of the table

Yeah, that is how it works in prod at the moment as well and we are not using an `InvertedFlatList`, I suggest we handle that in a follow up PR

2025-06-10 13:49 UTC, rlinoz commented
@chrispader can you take a look at this one https://github.com/Expensify/App/pull/51366#issuecomment-2946824931 before we ask applause to run tests?

2025-06-11 14:20 UTC, chrispader commented
> bug: it scrolls to wrong unread message after clear cache and restart and there is jitter when scrolling start

@ishpaul777 cannot reproduce this in the latest state of the PR:


https://github.com/user-attachments/assets/4186b08a-d89d-47bb-b0ee-e6c6cd059139

2025-06-11 14:22 UTC, chrispader commented
> after clear cache and restart, in a long chat direct comment linking to first message does not scroll the chat exactly to first message
> Edit: i can repro on staging so its not a blocker

@ishpaul777 if i'm not mistaken, this is the expected behaviour. Once the report has been opened, it is marked as read and a `ReadNewestAction` API request is sent.

After clearing the cache and restarting the message will not be unread anymore and therefore it will not start at this message.

2025-06-12 13:39 UTC, rlinoz commented
bump @ishpaul777 on this one https://github.com/Expensify/App/pull/51366#issuecomment-2963035889

2025-06-12 13:43 UTC, ishpaul777 commented
testing

2025-06-12 13:54 UTC, ishpaul777 commented
> > after clear cache and restart, in a long chat direct comment linking to first message does not scroll the chat exactly to first message
> > Edit: i can repro on staging so its not a blocker
> 
> @ishpaul777 if i'm not mistaken, this is the expected behaviour. Once the report has been opened, it is marked as read and a `ReadNewestAction` API request is sent.
> 
> After clearing the cache and restarting the message will not be unread anymore and therefore it will not start at this message.

Sorry if i was not clear, here i am not trying to link to unread message, i click the link to first message(/:reportId/:reportActionId) in chat but it does not link me to the first message


https://github.com/user-attachments/assets/230f35f8-0eac-42cb-9077-ee1a4edc1473

2025-06-12 13:54 UTC, ishpaul777 commented
https://github.com/Expensify/App/pull/51366#issuecomment-2946824931 this is fixed *on web*🎉 

https://github.com/user-attachments/assets/2eb9c445-748c-4152-acd0-4d19957fdd4e

2025-06-12 13:55 UTC, ishpaul777 commented
@rlinoz can you please trigger adhoc build for native apps 🙇

2025-06-12 14:03 UTC, ishpaul777 commented
https://github.com/Expensify/App/pull/51366#issuecomment-2966855060 still happening on mweb safari

Steps:

1. on fresh sign in open a report (https://dev.new.expensify.com:8082/r/2636639376691898) with many messages

2. link to any of the top message mark any message unread

3. go back and open report again, it does not open chat to the correct unread message

https://github.com/user-attachments/assets/d3c3f60a-59ab-491a-89a8-a542d9755653

2025-06-16 09:43 UTC, chrispader commented
> after clear cache and restart, in a long chat direct comment linking to first message does not scroll the chat exactly to first message
> 
>  Screen.Recording.2025-06-06.at.4.51.31.AM.mov 
> Edit: i can repro on staging so its not a blocker

> Sorry if i was not clear, here i am not trying to link to unread message, i click the link to first message(/:reportId/:reportActionId) in chat but it does not link me to the first message

@ishpaul777 thanks for the clarification, but i still cannot reproduce this. For me it always links to the correct message


https://github.com/user-attachments/assets/11c2d8e5-9ba4-454c-ac4e-7ecbabc42704

2025-06-16 10:12 UTC, chrispader commented
> [#51366 (comment)](https://github.com/Expensify/App/pull/51366#issuecomment-2966855060) still happening on mweb safari
> 
> Steps:
> 
> 1. on fresh sign in open a report ([dev.new.expensify.com:8082/r/2636639376691898](https://dev.new.expensify.com:8082/r/2636639376691898)) with many messages
> 2. link to any of the top message mark any message unread
> 3. go back and open report again, it does not open chat to the correct unread message

@ishpaul777 i also cannot reproduce this one 🥴


https://github.com/user-attachments/assets/ed8b7fb5-bd9b-4b19-aa55-03c52090155f

2025-06-16 18:18 UTC, ishpaul777 commented
i can reproduce both issues consistently, @chrispader can you please try a new sign in and then redo steps instead clear cache and restart 🙇 

https://github.com/Expensify/App/pull/51366#issuecomment-2975942830



https://github.com/user-attachments/assets/fdb8d2d7-25c2-4311-bcc9-911132999128



https://github.com/Expensify/App/pull/51366#issuecomment-2975845760

https://github.com/user-attachments/assets/e8f230a3-1a3c-4cbe-91f2-3d4bbf8eb625

2025-06-17 19:23 UTC, chrispader commented
> i can reproduce both issues consistently, @chrispader can you please try a new sign in and then redo steps instead clear cache and restart 🙇

Thanks, @ishpaul777 i can reproduce the issue now. I just discussed this issue with @rlinoz as this is going to be a bit more complex to fix. I'll create a separate PR with some refactoring needed to fix this issue holistically.

2025-06-18 12:27 UTC, ishpaul777 commented
Thanks @chrispader!  i'll finalize checklist today then we good to merge.


@rlinoz lets send this for QA now?

2025-06-18 12:34 UTC, rlinoz commented
I think the idea is 

1. Create another PR hoisting the calculation of the unread report action to the `ReportScreen`
2. HOLD this PR on that
3. Once step 1 is merged, merge main and fix the issue you found here.

Does that sound correct? @chrispader @ishpaul777

2025-06-18 12:36 UTC, ishpaul777 commented
makes sense to me @rlinoz 👍 🚀

2025-06-25 22:48 UTC, chrispader commented
> I think the idea is
> 
> 1. Create another PR hoisting the calculation of the unread report action to the `ReportScreen`
> 2. HOLD this PR on that
> 3. Once step 1 is merged, merge main and fix the issue you found here.
> 
> Does that sound correct? @chrispader @ishpaul777

@rlinoz recently introduced a new `OpenReport` response property called `oldestUnreadReportActionID` which lets us prevent that refactor while fixing the last issue we had with this PR. I've just implemented the frontend changes and it looks like it's working fine!

There is one last issue with the `OpenReport` request in the backend, where we don't get the 25 report actions before and after the last unread report action. @rlinoz is working on fixing this! 🙌🏼

Once this is fixed, i'm going to do some final testing

cc @ishpaul777

2025-07-08 00:31 UTC, chrispader commented
@rlinoz is there an update on the backend issue?

2025-07-10 17:49 UTC, rlinoz commented
I just got back from OOO, but I am having a hard time reproing what you mentioned.


https://github.com/user-attachments/assets/3f0af3d4-01d5-4b60-89ac-5aee4d8c7a50


https://github.com/user-attachments/assets/20b40d2c-f5df-48d6-b103-af2476e101fd

2025-07-14 13:10 UTC, rlinoz commented
@chrispader ^

2025-07-15 11:39 UTC, chrispader commented
@rlinoz i'm also not to reproduce this reliably atm. I've tested the PR again with recent changes from main, and seems there are now problems with `maintainVisibleContentPosition`.

Will re-test and hopefully fix the issue tomorrow.

2025-07-15 21:00 UTC, rlinoz commented
I found out what the issue is, essentially we filter out some messages depending on who is requesting them and that logic is not part of getting the last unread reportActionID

I will make the backend PR to fix it.

2025-07-16 06:51 UTC, chrispader commented
@rlinoz ahh got it. Thanks, i'll re-test the PR once the backend fix is merged

2025-07-22 13:20 UTC, rlinoz commented
Hey @chrispader the backend is deployed, do you mind giving this a go again? It is working for me now.

2025-07-22 13:38 UTC, chrispader commented
> Hey @chrispader the backend is deployed, do you mind giving this a go again? It is working for me now.

@rlinoz i'll test this tomorrow!

2025-07-24 13:53 UTC, rlinoz commented
@chrispader bumping this one

2025-07-24 16:28 UTC, chrispader commented
@rlinoz @ishpaul777 i think all the issues are fixed!


https://github.com/user-attachments/assets/4566ad03-908e-4a1b-96e5-61b91175fb7f

2025-07-25 13:00 UTC, rlinoz commented
@ishpaul777 can you check if all your concerns are addressed?

I will also ask for QA to test the adhoc builds above.

2025-07-25 15:08 UTC, ishpaul777 commented
Sure i will try prioritize this by EOD

2025-07-25 20:43 UTC, vincdargento commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Chat - Skeleton loader is displayed when creating a chat offline

**Version Number:** v9.1.85-4 PR:51366
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://test-management.browserstack.com/projects/2148171/test-runs/TR-240/folder/12015267/39317129/806256614?sort=%2Bidentifier
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://51366.pr-testing.expensify.com/
2. Disable the internet connection in the device
3. Click on the green + button
4. Click on the "Start Chat" option
5. Search for a user with a valid email that you don't have any messages with and open the chat
6. Send some messages

## Expected Result:
The conversation is grayed out indicating is pending to be created
The preview of the conversation shows the latest message sent in the previous step

## Actual Result:
Skeleton loader is displayed when creating a chat offline and sending messages

## Workaround:
Unknown

## Platforms:
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c5227309-438e-4bc1-ad84-414ad0d25fe9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2025-07-28 20:04 UTC, ishpaul777 commented
was not able to priortize last week, will start testing now

2025-07-29 23:01 UTC, ishpaul777 commented
Overall it works well but we still have some blocking issues.

### Testing results:

✅ Open report and scrolled to  unread message in report after clearing cache.

✅ Open report and scrolled to  unread message in reportwith existing cache.

✅ Open report and scrolled to  unread message in report in fresh sign in.

✅ Comment linking, works well but on jos there is jitter it not always shows the message is user view 
video:

https://github.com/user-attachments/assets/2081a6f9-d24a-4fe2-af01-eeaa97e7b288

❌  Open report while offline - Always displays a skeleton view, even when cache exists. similar issue reported [here]
(https://github.com/Expensify/App/pull/51366#issuecomment-3120290909).

❌  "New Messages" pop-up behavior - Navigates to the end of currently loaded messages, then fetches more in batches and scrolls again. While it technically works, the behavior differs from staging, where the scroll to the bottom is smoother and immediate. 

video:

https://github.com/user-attachments/assets/e175b591-af9a-4584-a421-95c16d6e9c9f

2025-07-30 12:29 UTC, rlinoz commented
@chrispader can you take a look at the issue reported above, please?

2025-07-30 15:08 UTC, chrispader commented
> @chrispader can you take a look at the issue reported above, please?

@rlinoz yes will do in a bit!

2025-08-04 13:19 UTC, chrispader commented
> ## Chat - Skeleton loader is displayed when creating a chat offline
> **Version Number:** v9.1.85-4 PR:51366 **Reproducible in staging?:** No **Reproducible in production?:** No **If this was caught during regression testing, add the test name, ID and link from TestRail:** [test-management.browserstack.com/projects/2148171/test-runs/TR-240/folder/12015267/39317129/806256614?sort=%2Bidentifier](https://test-management.browserstack.com/projects/2148171/test-runs/TR-240/folder/12015267/39317129/806256614?sort=%2Bidentifier) **Issue reported by:** Applause Internal Team
> 
> ## Action Performed:
> 1. Navigate to [51366.pr-testing.expensify.com](https://51366.pr-testing.expensify.com/)
> 2. Disable the internet connection in the device
> 3. Click on the green + button
> 4. Click on the "Start Chat" option
> 5. Search for a user with a valid email that you don't have any messages with and open the chat
> 6. Send some messages
> 
> ## Expected Result:
> The conversation is grayed out indicating is pending to be created The preview of the conversation shows the latest message sent in the previous step
> 
> ## Actual Result:
> Skeleton loader is displayed when creating a chat offline and sending messages


@shubham1206agra fixed!

2025-08-04 13:40 UTC, shubham1206agra commented
@chrispader Why am I tagged here 🙏🏽

2025-08-04 13:47 UTC, chrispader commented
> @chrispader Why am I tagged here 🙏🏽

@shubham1206agra oh sorry, thought you were the C+ on this issue. You can ignore this

2025-08-05 14:56 UTC, chrispader commented
> ❌ "New Messages" pop-up behavior - Navigates to the end of currently loaded messages, then fetches more in batches and scrolls again. While it technically works, the behavior differs from staging, where the scroll to the bottom is smoother and immediate.

@ishpaul777 @rlinoz i'm still working on fixing this one. I cannot clearly reproduce this on native yet, this is working sometimes.

Also, as mentioned [here](https://github.com/Expensify/App/pull/51366#issuecomment-3073271629) i'm currently having trouble making `maintainVisibleContentPosition` work in general on native. Not sure whether a recent RN update has caused issues, but i experience some jumpiness on initial render:

https://github.com/user-attachments/assets/5e664c73-60cb-4a68-b89d-edfc6086a4b3

2025-08-13 07:49 UTC, chrispader commented
> Also, as mentioned [here](https://github.com/Expensify/App/pull/51366#issuecomment-3073271629) i'm currently having trouble making `maintainVisibleContentPosition` work in general on native. Not sure whether a recent RN update has caused issues, but i experience some jumpiness on initial render:
> 

@ishpaul777 @rlinoz i found the culprit for this issue and it seems to be the `ActionSheetAwareScrollView`. When this scroll component is used it will cause this jump. Currently looking for a solution for this on iOS

2025-08-13 11:27 UTC, rlinoz commented
Thanks for the update and the work on this!

2025-08-18 10:24 UTC, chrispader commented
> @ishpaul777 @rlinoz i found the culprit for this issue and it seems to be the `ActionSheetAwareScrollView`. When this scroll component is used it will cause this jump. Currently looking for a solution for this on iOS

@rlinoz @ishpaul777 i found a fix for the issue with `ActionSheetAwareScrollView`. Basically the issue was that this component would render one single element in the `ScrollView` rather than the children itself. This caused issues with `maintainVisibleContentPosition`

Edit: I'll extract these changes to a separate PR though so it is more easily testable. I'd say we hold on this other PR, do you agree @rlinoz ?

2025-08-18 10:49 UTC, chrispader commented
PR is up here: https://github.com/Expensify/App/pull/68648

2025-08-18 13:40 UTC, chrispader commented
> ❌ "New Messages" pop-up behavior - Navigates to the end of currently loaded messages, then fetches more in batches and scrolls again. While it technically works, the behavior differs from staging, where the scroll to the bottom is smoother and immediate.

@ishpaul777  this should be fixed now!

2025-08-18 13:41 UTC, chrispader commented
@ishpaul777 could you please re-test this PR with while also applying these changes from https://github.com/Expensify/App/pull/68648 to fix the issue with the `ActionSheetAwareScrollView`

@rlinoz could you please trigger new ad-hoc builds?

2025-08-18 13:59 UTC, rlinoz commented
> Edit: I'll extract these changes to a separate PR though so it is more easily testable. I'd say we hold on this other PR, do you agree @rlinoz ?

Yes, that is much easier to review, thanks!

> @rlinoz could you please trigger new ad-hoc builds?

Done!

2025-08-18 14:05 UTC, shubham1206agra commented
@chrispader I am not sure why I am being tagged here

2025-08-18 14:07 UTC, chrispader commented
> @chrispader I am not sure why I am being tagged here

sorry again, my mistake, wrong C+

2025-08-19 08:55 UTC, chrispader commented
@rlinoz the ad-hoc build for iOS failed. Could we create a new one please? 🙌🏼

(i think the failing Reassure tests is unrelated)

2025-08-22 15:00 UTC, chrispader commented
@ishpaul777 are you able to test this? :)

2025-08-22 18:56 UTC, ishpaul777 commented
hey @chrispader 👋, I was unexpectedly OOO this week but just got online. I’ll make sure to catch up on this and prioritize (over weekend or monday) 🙇

2025-08-26 10:22 UTC, ishpaul777 commented
reviewing today

2025-09-11 10:20 UTC, chrispader commented
@rlinoz @ishpaul777 we don't need to hold on https://github.com/Expensify/App/pull/69527 anymore, as this issue has been fixed on `main` already! 🥳

I just merged `main` and refactored the PR after recent introduction of `useFlatListScrollKey`. I believe the "open report"/comment linking logic can also be used in non-inverted lists, but we'd need to also test that there?

2025-09-11 11:08 UTC, chrispader commented
I've created a follow-up with low priority which re-organizes the files related to FlatList: https://github.com/Expensify/App/pull/70378

2025-09-11 18:23 UTC, ishpaul777 commented
Thanks @chrispader, i will priortize review and testing

2025-09-11 18:23 UTC, ishpaul777 commented
@rlinoz can you please start adhoc build, thanks!

2025-09-16 08:55 UTC, rlinoz commented
@chrispader do you mind fixing the conflicts, please?

@ishpaul777 did you get a chance to test the adhoc build?

2025-09-16 11:45 UTC, chrispader commented
> @chrispader do you mind fixing the conflicts, please?

done! I had to revert the changes from another PR because of [this revert](https://github.com/Expensify/App/pull/70411). I made some other improvements as part of the previous merge and refactor, which i kept in the PR.

Namely i added the following hooks:

- `useRefWithFallback`
- `useFlatListHandle`
- 
> @ishpaul777 did you get a chance to test the adhoc build?

@ishpaul777 the current ad-hoc build includes the changes from the reverted PR so please keep the issues mentioned [this revert](https://github.com/Expensify/App/pull/70411) in mind.

@rlinoz could you please trigger another ad-hoc build?

2025-09-16 22:13 UTC, ishpaul777 commented
### Testing results: (web desktop)

✅ Open report and scrolled to  unread message in report after clearing cache.

https://github.com/user-attachments/assets/2313948b-d6b1-4d22-b9cd-020167789500

✅ Open report and scrolled to  unread message in reportwith existing cache.

https://github.com/user-attachments/assets/aa86f820-04e2-46b7-84f1-9c2dc254ef64

✅ Open report and scrolled to  unread message in report in fresh sign in.

https://github.com/user-attachments/assets/f999df58-f6b9-43de-832c-f37bba52fa08

✅  Open report while offline works loads the cached message and reports loads fine when only

https://github.com/user-attachments/assets/f6c3b60a-a1d6-458b-adba-903f7f9219f8

❌ Comment linking to message seems to have issue when cache not exist 

https://github.com/user-attachments/assets/a291bc61-b8d8-49cb-8dcd-97a47d1773c6

❌  "New Messages" and "latest messages" pop-up button does nothing 

https://github.com/user-attachments/assets/98ddaadc-defe-4a2b-8089-5631529973cd


https://github.com/user-attachments/assets/6cc14417-5ea6-4ca9-9b7f-78f504b2773f


________

will run more testing on native apps and post results tomorrow

2025-09-18 11:18 UTC, chrispader commented
i'll look into these issues today!

2025-09-23 11:13 UTC, chrispader commented
Sorry for the delay, still working on fixing these issues. Will report later today!

2025-09-24 16:36 UTC, chrispader commented
Sorry again, was super busy with other PRs. Will look into this as soon as possible, probably EOD

2025-09-25 16:35 UTC, VickyStash commented
Hi there 👋 I was taking a look at this PR, as I'm work on something that can be related - I'm implementing the update to always open transaction thread at top instead of the bottom. I was experimenting with this PR and found some issues, so decided to let you know:

1. I can't scroll to the top of the transaction thread if the thread has 60+ messages and opened in the RHP:

https://github.com/user-attachments/assets/fadfc220-6716-4010-b00c-ce8dad2b0399

2. I'm not scrolled to the unread action if the report is opened in the RHP:

https://github.com/user-attachments/assets/ed8a4225-0783-48ee-9894-8c069710db2b

2025-10-02 16:14 UTC, chrispader commented
> ❌ "New Messages" and "latest messages" pop-up button does nothing

@ishpaul777 fixed!

2025-10-02 16:24 UTC, chrispader commented
> ❌ Comment linking to message seems to have issue when cache not exist

@ishpaul777 i cannot reproduce this one, but maybe my recent changes actually fixed it or sth from `main`. Could you please re-test?


https://github.com/user-attachments/assets/9dbeac42-c05f-4f46-95b0-d9a4e42d6a79

2025-10-02 16:27 UTC, chrispader commented
@rlinoz PR Author Checklist is failing at the moment, and Janic is currently not working on this issue/project, so i'd suggest to create a duplicate of the PR once all issues are resolved, so that we can keep the context for now!

2025-10-02 16:34 UTC, chrispader commented
> Hi there 👋 I was taking a look at this PR, as I'm work on something that can be related - I'm implementing the update to always open transaction thread at top instead of the bottom. I was experimenting with this PR and found some issues, so decided to let you know:
> 
> 1. I can't scroll to the top of the transaction thread if the thread has 60+ messages and opened in the RHP:
> 
>  bug1.mp4 
> 
> 2. I'm not scrolled to the unread action if the report is opened in the RHP:
> 
>  bug2.mp4

@VickyStash is this still a problem for you? I see https://github.com/Expensify/App/pull/71480 has been merged...

If so, how can reproduce this as i currently don't see a way to show the report in the RHP

2025-10-06 07:19 UTC, VickyStash commented
> @VickyStash is this still a problem for you? I see https://github.com/Expensify/App/pull/71480 has been merged...

It wasn't blocking me, it just something I've noticed while testing your PR. Have you tried to reproduce it?

2025-10-06 12:29 UTC, rlinoz commented
> PR Author Checklist is failing at the moment, and Janic is currently not working on this issue/project, so i'd suggest to create a duplicate of the PR once all issues are resolved, so that we can keep the context for now!


I think I can update the checklist so we don't have to duplicate the PR.

I was OOO last week, what are the next steps here? @ishpaul777 @chrispader

2025-10-07 11:11 UTC, chrispader commented
> > @VickyStash is this still a problem for you? I see #71480 has been merged...
> 
> It wasn't blocking me, it just something I've noticed while testing your PR. Have you tried to reproduce it?

@VickyStash yes I tried to reproduce, but wasn't able. Do you have concrete repro steps for me? :)

2025-10-07 11:12 UTC, chrispader commented
@rlinoz I fixed one issue mentioned by @ishpaul777 and could not reproduce the other one. @ishpaul777 could you let me know if you can still reproduce [this issue](https://github.com/Expensify/App/pull/51366#issuecomment-3362073047).

Other than that, everything should be ready!

2025-10-08 12:19 UTC, ishpaul777 commented
I'll try to priortize this for later today or tomorrow 🙇

2025-10-10 08:29 UTC, VickyStash commented
Hey @chrispader, when I run the app from this PR, the app crashes when I switch between reports:
<img width="2984" height="1380" alt="image" src="https://github.com/user-attachments/assets/6265b631-363d-4b87-97dd-1e08f95e607d" />

2025-10-10 09:31 UTC, chrispader commented
> Hey @chrispader, when I run the app from this PR, the app crashes when I switch between reports

@VickyStash thanks for the catch. I might have missed to push my latest changes, because I've fixed this issue already. Should be working now!

2025-10-10 11:40 UTC, rlinoz commented
@ishpaul777 any updates on tests?

2025-10-11 19:46 UTC, ishpaul777 commented
Sorry for the delay in getting back! Below are my testing results everything seems to be working. I didn’t encounter any issues during my testing. Excellent work, @chrispader 👏

### Testing results: (web / ios safari / ios Native / Android Native)

<details>
<summary>✅ Open report and scrolled to unread message in report after clearing cache</summary>

  
https://github.com/user-attachments/assets/fcaf226f-554f-44ab-87db-1fc6108f76f4  

https://github.com/user-attachments/assets/af8c7ea7-3323-424f-969c-735ebeffb7c3  

https://github.com/user-attachments/assets/8a39a6a5-362d-4d2e-a20c-e2040a1ae93a  

https://github.com/user-attachments/assets/3b015eb5-3844-4472-8ad1-f6f95c3187f0  

https://github.com/user-attachments/assets/d68099b5-f979-4a3a-8b68-57ae3df29a79  

</details>


<details>
<summary>✅ Open report and scrolled to unread message in report with existing cache</summary>

  
https://github.com/user-attachments/assets/76da5e3d-245e-477d-91dd-f77e7562a98  

https://github.com/user-attachments/assets/393225d9-ac01-4421-9701-0930e72d411f  

https://github.com/user-attachments/assets/41109c22-c721-4bc6-9d83-c48ec0991d35  

https://github.com/user-attachments/assets/ceb02cad-6f6d-4187-8712-24270b730be0  

https://github.com/user-attachments/assets/81e1ec55-3a23-4345-91bc-3dd0701ea07e  

</details>


<details>
<summary>✅ Open report and scrolled to unread message in report in fresh sign in</summary>

  
https://github.com/user-attachments/assets/0db22039-f6d8-4c94-b95e-912432af3f83  

https://github.com/user-attachments/assets/b24b782d-268e-4e94-8525-2c85ba7fbb6c  

https://github.com/user-attachments/assets/a75a3554-536e-4326-8c8e-546f424917d3  

https://github.com/user-attachments/assets/016d4349-34ab-4901-b87e-31a289ee6b9b  

https://github.com/user-attachments/assets/13a95273-9fa1-4170-a7a9-1a9a3fe00b86  

</details>


<details>
<summary>✅ Open report while offline — loads cached message and reports fine when online again</summary>

  
https://github.com/user-attachments/assets/e3ee5245-fdd4-4825-a063-dd719d58a11a  

https://github.com/user-attachments/assets/2cda5d34-bb6f-444b-8c24-90c7ebfc7fff  

https://github.com/user-attachments/assets/bce793c6-8427-4159-b223-2727d9979773  

</details>


<details>
<summary>✅ Comment linking to message and "New Messages" / "Latest messages" pop-up button works</summary>

  
https://github.com/user-attachments/assets/54785737-07ae-4ba2-9378-50cbfe7b1048  

https://github.com/user-attachments/assets/6a025290-9987-4320-aa65-123fd392ed93  

https://github.com/user-attachments/assets/5989ae65-40dd-4444-8d20-897027d5dda5  

https://github.com/user-attachments/assets/dcb8f4c1-02e8-4df2-8035-71dc302f2c0d  

https://github.com/user-attachments/assets/4225f1c8-d04d-45ff-a9e7-707e12bd53fe  

https://github.com/user-attachments/assets/74c910c3-2f37-4873-9702-7c6ad38247b9  

https://github.com/user-attachments/assets/2ccbe1b1-07c4-4bb6-99dc-55d953c19ff0  

</details>

2025-10-12 16:36 UTC, chrispader commented
@rlinoz so are we ready for merge then? 👀 Could you please update the PR author checklist then! 🙌🏼

I'll keep looking out for merge conflicts in the next days

2025-10-13 12:10 UTC, rlinoz commented
Oh this is great!

I will get another Applause test on a new adhoc build here and we can merge.

2025-10-13 13:11 UTC, rlinoz commented
Requested here https://expensify.slack.com/archives/C9YU7BX5M/p1760361073444529

2025-10-16 02:29 UTC, mitarachim commented
##  iOS - Edit composer scroll up & is out of view after selecting edit comment option in menu

**Version Number:** v 9.2.24-1 PR:51366
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exploratory when testing https://test-management.browserstack.com/projects/2219752/test-runs/TR-1260/folder/13176723/41237044/950301260
**Issue reported by:** Applause Internal Team
**Device used:** iPhone 16/iOS 18.3.1


## Action Performed:
1. Launch Hybrid app
2. Navigate to 1:1 DM which has several messages
3. Long tap on any previous message (or the message which is near to chat header)
4. Select edit comment option

## Expected Result:
Edit composer should be visible, be in view to user & displayed above the keyboard

## Actual Result:
Edit composer scroll up & get out of view after selecting edit comment option in menu.

User has to scroll the chat page to view the edit composer

## Tester login credentials - Email/Phone 
kiatest.80+ck101325@gmail.com

## Workaround:
Unknown

## Platforms:
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1e9452ac-0756-4f4c-a875-e4757904f740

2025-10-16 14:07 UTC, rlinoz commented
cc: @chrispader on the above, I guess this is the last one 🤞

2025-10-16 19:29 UTC, chrispader commented
@rlinoz last bug fixed. Latest changes shouldn't cause any other issues, since this change was very isolated and only related to `scrollToIndex` function in `BaseInvertedFlatList` component.

I think we'd just need a another quick review, but no further QA.

2025-10-17 11:49 UTC, rlinoz commented
Nice, thank you very much!

I will update the checklist and approve the PR, @ishpaul777 can you also approve it, please?

2025-10-17 11:50 UTC, rlinoz commented
ah actually jest is failing with something that seems related @chrispader

2025-10-17 12:33 UTC, chrispader commented
@rlinoz i feel like the `UnreadIndicatorsTest` is still flaky after they have been re-enabled in https://github.com/Expensify/App/pull/72385

These are my results from testing the UI tests in this PR:

> Unread Indicators › Display bold in the LHN for unread chat and new line indicator above the chat message when we navigate to it

> Unread Indicators › Displays the correct chat message preview in the LHN when a comment is added then deleted

https://github.com/user-attachments/assets/a60f9ac5-492d-4f42-92fa-0633f74aea6a


> Unread Indicators › Move the new line indicator to the next message when the unread message is deleted

2025-10-17 12:42 UTC, rlinoz commented
Oh interesting, let's re run it then!

2025-10-17 15:06 UTC, ishpaul777 commented
jest tests still failing, it passing on other PRs

2025-10-17 15:47 UTC, rlinoz commented
Yeah, I ran then like 3 or 4 times, it looks like it is straight up not passing.

2025-10-21 09:56 UTC, chrispader commented
@rlinoz @ishpaul777 the tests should be passing now. Seems we still had some changes that were supposed to work around the flaky `UnreadIndicatorsTest` before it was fixed.

2025-10-22 12:24 UTC, rlinoz commented
Looks like we are good!

@ishpaul777 can you review and approve it, please?

2025-10-22 13:23 UTC, VickyStash commented
I've noticed two issues during quick testing. @janicduplessis @chrispader Can you please verify it?

1. The chat loading indication is shown when going back to the chat using the name in the header. Steps:
- Create a workspace
- Open workspace chat
- Create an expense here
- Open the expense
- Tap on the chat name in the header to navigate back
- See the loading indication. There should be no loading

https://github.com/user-attachments/assets/7864dc1b-b400-43ca-ad01-a360154ffea5

2. Transaction thread loading indication every time I open it
- Create a workspace
- Open workspace chat
- Create 2 expenses here
- Tap on the expenses preview
- Open any transaction thread 
- See the loading indication. There should be no loading indication, the thread should be shown right away


https://github.com/user-attachments/assets/1fead23b-34db-4b3d-ae59-ac61f1bcbb03

2025-10-22 13:23 UTC, chrispader commented
> Looks like we are good!
> 
> 
> 
> @ishpaul777 can you review and approve it, please?

@ishpaul777 @rlinoz i have to test one more thing, seems something is off after the latest changes from main

2025-10-22 13:39 UTC, VickyStash reviewed
Great work! Just a couple of comments from me

2025-10-22 13:39 UTC, VickyStash commented on src/hooks/useLoadReportActions.ts
> +            });
Can you please explain a little what's happening here, why `GET_REPORT_ACTIONS_MAX_WAITING_TIME` is specifically 3000?

2025-10-22 13:39 UTC, VickyStash commented on src/hooks/useLoadReportActions.ts
> +            });
Same question here!

2025-10-22 13:39 UTC, VickyStash commented on src/libs/actions/Report.ts
> +/* eslint-disable @typescript-eslint/no-deprecated */
Why do we need it?

2025-10-22 13:39 UTC, VickyStash commented on src/libs/actions/Report.ts
> +}
Should we return earlier if the reportID is `undefined`?

2025-10-22 13:39 UTC, VickyStash commented on src/libs/ReportUtils.ts
> +/* eslint-disable @typescript-eslint/no-deprecated */
Same, why do we need it?

2025-10-22 13:52 UTC, ishpaul777 commented on src/libs/actions/Report.ts
> +    return API.paginate(
I think this violates our philosophy, is it absolute necessary


https://github.com/Expensify/App/blob/085af64559aacfab8c87aa7bfe720fb5953b1ee4/contributingGuides/philosophies/DATA-BINDING.md?plain=1#L23

2025-10-22 13:52 UTC, ishpaul777 commented on src/ONYXKEYS.ts
> +
please add comment above explaining key purpose

2025-10-22 13:52 UTC, ishpaul777 commented on src/hooks/useLoadReportActions.ts
> +                isLoadingOlderChats.current = false;
maybe we can use `.finally` instead of `.then`, using Promises is still anti pattern please add comment if its abosolute necessary

2025-10-27 12:48 UTC, rlinoz commented
Hey @chrispader can you take a look at the reviews, please?

2025-10-27 14:02 UTC, chrispader commented
> Hey @chrispader can you take a look at the reviews, please?

@rlinoz yes, sorry for the delay. Was busy with other PRs. I will work on this later today!

2025-10-29 19:38 UTC, chrispader commented
@rlinoz i didn't forget about this one, sorry again for the delay. Some other PRs came up in the meantime. I'll be able to work on the reviews tomorrow!

2025-10-31 12:12 UTC, chrispader commented on src/hooks/useLoadReportActions.ts
> +            });
Based on @ishpaul777 comment [here](https://github.com/Expensify/App/pull/51366#discussion_r2452183505), i was able to remove this. This is a relict from a previous implementation and not necessary anmyore, thanks for the catch!

2025-10-31 12:12 UTC, chrispader commented on src/hooks/useLoadReportActions.ts
> +            });
Same as above

2025-10-31 12:13 UTC, chrispader commented on src/libs/actions/Report.ts
> +/* eslint-disable @typescript-eslint/no-deprecated */
Thanks for the catch, we don't need this anymore. This was due to recent `translateLocal` deprecation.

2025-10-31 12:14 UTC, chrispader commented on src/libs/actions/Report.ts
> +}
Good catch, thanks!

2025-10-31 12:14 UTC, chrispader commented on src/libs/ReportUtils.ts
> +/* eslint-disable @typescript-eslint/no-deprecated */
Same as above, removing!

2025-10-31 12:19 UTC, chrispader commented on src/hooks/useLoadReportActions.ts
> +                isLoadingOlderChats.current = false;
Yes, thats a good suggestion. This `Promise.race` call is a relict from a previous implementation/experiment. We can remove this, it is not necessary anymore!

2025-10-31 12:54 UTC, chrispader commented
@rlinoz @ishpaul777 i've addressed all comments and re-implemented the logic in `useLoadReportActions` so that the actions are not returning a promise anymore.

@ishpaul777 could you re-test this PR, please? 🙌🏼

2025-10-31 14:44 UTC, chrispader commented on src/libs/actions/Report.ts
> +    return API.paginate(
I've refactored the logic in `useLoadReportActions` so that it does not rely on promises anymore.

2025-10-31 19:56 UTC, ishpaul777 commented
@rlinoz can you please trigger adhoc build and Ai reviewer workflow here. Thx!

2025-11-03 13:15 UTC, ishpaul777 commented
i'll try to priortize testing today, just a heads up i have joined BE contributor team and will soon be removed from C+ team so we might have reassign if this still takes long (i can still be involved and help testing if needed)

@rlinoz gentle bump on https://github.com/Expensify/App/pull/51366#issuecomment-3474698205 🙇

2025-11-03 13:31 UTC, rlinoz commented
Sorry, I was OOO on Friday, running it now.

2025-11-03 14:02 UTC, rlinoz commented
@codex review

2025-11-04 18:01 UTC, rlinoz commented
Tested today and it is working well.

@ishpaul777 can you finish the review so we can get ir merged before more conflicts, please?

2025-11-04 18:36 UTC, chrispader commented on src/hooks/useLoadReportActions.ts
> +        }
Addressed in https://github.com/Expensify/App/pull/51366/commits/d1fbb1e1da824d83af1b63ebec46705edce15387

2025-11-04 18:52 UTC, chrispader commented
> Tested today and it is working well.

Perfec!, i've addressed the comment by Codex, which was valid but probably would have been an edge-case that should not be possible.
 
> @ishpaul777 can you finish the review so we can get ir merged before more conflicts, please?

Too late, i've just resolved merge conflicts.

2025-11-05 21:52 UTC, ishpaul777 commented
Bug: loading skelaton everytime report is opened



https://github.com/user-attachments/assets/83ea7d58-3814-4265-9026-180445a73640

2025-11-06 17:34 UTC, chrispader commented
> Bug: loading skelaton everytime report is opened
> 
>  Screen.Recording.2025-11-06.at.3.20.25.AM.mov

@ishpaul777 just fixed this, thanks for the catch! This was caused because i triggered the `oldestUnreadReportActionID` check on every open, even if there are no unread report actions.

In general, when there are unread messages, we will need to delay the first render of the report until we have the result from `OpenReport` in order to prevent layout shifts and/or janky behavior. This is not a bug, but a limitation of the current implementation. In order to display an unread report immediately, we would need to add logic to pre-fetch the report actions somehow, e.g. in the background, before the report is opened. We don't have this logic at the moment though

2025-11-06 17:50 UTC, rlinoz commented
> In general, when there are unread messages, we will need to delay the first render of the report until we have the result from OpenReport in order to prevent layout shifts and/or janky behavior.

I get the reason why, but this might be problematic, at least it is just for unread chats.

Any thoughts @trjExpensify ?

2025-11-06 23:05 UTC, trjExpensify commented
Yeah, it's a good point. I think this risks making the app feel slugglish, not smarter. I'd be curious for @Expensify/design @JmillsExpensify's take as well, but I'm questioning we should wait to do something like mentioned below before we release it:

>we would need to add logic to pre-fetch the report actions somehow, e.g. in the background, before the report is opened. We don't have this logic at the moment though

2025-11-07 03:43 UTC, dubielzyk-expensify commented
Yeah I tend to agree that it makes it feel sluggish and a bit clunky. Also feels like it'll make the offline experience worse. It'd be great to avoid this.

2025-11-10 12:12 UTC, chrispader commented
@rlinoz @trjExpensify i'm checking whether i can find a simple way of removing the initial loading for unread chats in this PR. If too complex, i will propose a separate PR, which we can merge before this separately

2025-11-10 17:14 UTC, chrispader commented
Currently discussing next steps in [this Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1762783201002999)

2025-11-17 21:48 UTC, chrispader commented
@rlinoz this is testing well now for me without the loading state for unread chats.

@ishpaul777 are you able to re-test?

2025-11-18 09:48 UTC, rlinoz commented
I will run tests on this today.

2025-11-18 09:53 UTC, ishpaul777 commented
> @ishpaul777 are you able to re-test?

will retest this later today in couple hours

2025-11-21 17:18 UTC, ishpaul777 commented
This is still on radar, but I am still low on bandwidth sorry for delay everyone.

2025-11-24 21:04 UTC, ishpaul777 commented
@chrispader can you please merge main, also would be great if you can summarize and help me understand the new changes. Thanks!

_____


Also i feel like if possible can this PR be broken into smaller PRs to reduce scope per PR and possibilty of full revert incase of regressions ?

2025-11-24 21:10 UTC, ishpaul777 commented
@codex review

2025-11-25 11:06 UTC, chrispader commented
> @chrispader can you please merge main, also would be great if you can summarize and help me understand the new changes. Thanks!
> 
> Also i feel like if possible this PR should be broken into smaller PRs to reduce scope per PR and possibilty of full revert incase of regressions ?

@ishpaul777 just merged main! I will try to split this up into smaller PRs and then summarize the overall plan and each part indivudally

2025-11-26 09:26 UTC, chrispader commented
Okay @ishpaul777 & @rlinoz, so i've split this PR up into 4 separate PRs:

In the first stage, we would need to merge two PRs that change the behavior of the `useLoadReportActions` and `usePaginatedReportActions` hooks, which is needed for the comment linking of unread messages:

- https://github.com/Expensify/App/pull/76101:
  This PR adds an optional `shouldLinkToOldestUnreadReportAction` flag, which enables finding the page from store which includes the oldest unread report action, if no other `reportActionID` is provided.
- https://github.com/Expensify/App/pull/76104:
  This PR changes the behavior of `useLoadReportActions` so that `GetOlderActions` and `GetNewerActions` can be triggered multiple times. Previously, this could only be triggered once, i'm not sure if this was by design or a bug, but for comment linking this definitely has to be possible.

The above two PRs are also the most likely to cause regressions, so it's good to have them separate.

In the second stage, we can merge the actual changes to `BaseInvertedFlatList` and related components, which implement the comment linking to the unread message itself:

- **This PR**

I was not really able to split this up further, since the changes depend on each other and splitting these up would only increase complexity of the implementation...

After the main PR, i extracted some of the changes that i made during the work on this feature into a separate refactoring PR. These changes don't change any behavior, but are merely simplifications, changes for better readability and cleanups. These changes were cluttering this PR's diff quite a bit:

- https://github.com/Expensify/App/pull/76102:
  Currently this PR includes all the changes that we had previously here... Once this PR is merged, i will merge main and then we'll see the refactors

Therefore, @rlinoz could you change the title of this PR to HOLD on https://github.com/Expensify/App/pull/76101 and https://github.com/Expensify/App/pull/76104 please 🙌🏼

2025-11-26 12:10 UTC, ishpaul777 commented
Thanks for splitting this up @chrispader! i'll priortize review for each as soon as i can

2026-03-25 18:24 UTC, chrispader commented
@rlinoz we can put this off hold. I'll merge conflicts, check what's left to do here and report back in this issue.

Aside from testing what we already have, we'll have to figure out solutions for some edge cases discovered in https://github.com/Expensify/App/issues/76104

2026-03-25 18:26 UTC, rlinoz commented
Thank you! Excited for this

2026-03-26 11:24 UTC, chrispader commented
Okay, so here are a few things that we'll have to work on in here:

- [x] The current pagination logic expects the backend to deliver contiguous pages of data. When we load the report from a specific unread report action, this causes the existing pages to merge, even though there is still data to be loaded in between the stored pages.
  - I'm working on a solution where we can treat `OpenReport` calls differently, based on whether the chat has newer/older actions using `hasOlderActions`/`hasNewerActions`. If a `OpenReport` call reports that there are older/newer actions, we treat the data as _non-contiguous by default_, and therefore create a separate page that is not merged with the existing data.
- [x] When the user sends a message after going to a specific report action (unread/linked), we need to find a solution to scroll to the latest report action, even if we don't have it stored locally yet.
  - Previously i tried to just re-navigate to the report without a linked report action, which would cause the report to just load fresh from the end of the chat, but that causes issues with maintaining an open keyboard and composer focus on mWeb.
  - Simply scrolling to the end of the chat by calling `reportScrollManager.scrollToBottom()` does not work either, because we would need to load _all_ the data up until the last message

2026-03-26 12:32 UTC, rlinoz commented
could we have a mix of openreport with scroll to bottom? Like, we actually call the openreport API and then scroll to bottom

2026-04-02 12:28 UTC, rlinoz commented
@chrispader bumping this one

2026-04-03 18:48 UTC, chrispader commented
@rlinoz sorry for the delay, looking into this now!

2026-04-04 13:17 UTC, chrispader commented
> When the user sends a message after going to a specific report action (unread/linked), we need to find a solution to scroll to the latest report action, even if we don't have it stored locally yet.

@rlinoz i think i found a solution for this, but i'm not sure whether we want to add some sort of loading spinner here? You can see the loading bar on the sidebar, once the message is sent, but not sure whether we'll want to also indicate the loading state somewhere else, since a `OpenReport` call is triggered which can potentially take longer on a slow network. Also i think once the message is sent, the "Last message" pill should optimistically hide already.


https://github.com/user-attachments/assets/da2119cc-cb35-4e80-91e3-67f8e8213621

Basically what i'm doing is that we're fetching the very last messages in the chat, appending them to the list of current messages, then scroll to the bottom and then remove the mid-chat report actions page and update the list. This way, we can scroll to the last message without the need to manually reload the whole list

2026-04-10 22:41 UTC, chrispader commented
@rlinoz just resolved merge conflicts and re-tested the changes. The base functionality of linking to unread report actions works smoothly and i think we don't have any other edge-cases to cover in this PR.

Last tasks for me to do are:

- [x] Make sure that the multi-expense report view works (`tableReportView`)
  - https://github.com/Expensify/App/issues/35011#issuecomment-2890598187 
- [x] Evaluate whether we have any conflicts with changes by @aimane-chnaif and resolve them
  - https://github.com/Expensify/App/issues/35011#issuecomment-4170977329

After that, we can hopefully finally merge this beast of a PR 👀

2026-04-13 13:07 UTC, rlinoz commented
Discussing here https://github.com/Expensify/App/issues/35011#issuecomment-4236587632 before discussing this https://github.com/Expensify/App/pull/51366#issuecomment-4187105096

2026-04-13 17:28 UTC, rlinoz commented
I think if we are going to add the loading indicator we do as a follow up to this PR, so we only need to do what you mentioned here https://github.com/Expensify/App/pull/51366#issuecomment-4227179218k

2026-04-13 17:46 UTC, chrispader commented
@rlinoz both of the above points are handled. @aimane-chnaif's changes for LHN action badges should not conflict with this PR and also opening an unread report action with the multi-expense report view works smoothly. (`tableReportView` seems to not be a beta flag anymore, so i've just tested with any type of report view that we have on `main` atm)

I think this PR should be ready for a final review and merge! 🙌🏼

2026-04-13 17:49 UTC, chrispader commented
I'll coordinate with @Expensify/design on the implementation of loading states when the report is loading newer/older messages in a follow-up PR. For context, we've previously discussed this in [this Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1763145279164649?thread_ts=1762783201.002999&cid=C01GTK53T8Q).

2026-04-13 17:51 UTC, chrispader commented
@ishpaul777 or @ikevin127 could you please review this PR?

Also, @rlinoz could you please remove the `[HOLD on #51366 and #76104]` tag from the PR title? I cannot edit as this is Janic's PR originally

2026-04-13 17:58 UTC, rlinoz commented
Running an adhoc build, after we finish reviewing I will ask applause to test this as well.

2026-04-13 21:53 UTC, rlinoz commented
@ishpaul777 if you could help review this one.

2026-04-13 22:23 UTC, chrispader commented
@rlinoz sorry my bad, i forgot to push the last commit for this fix: https://github.com/Expensify/App/pull/51366#issuecomment-4187105096

Could you please re-trigger the ad-hoc builds?

2026-04-14 11:46 UTC, rlinoz commented
@chrispader can you fix the tests, typecheck and lint please?

2026-04-14 13:03 UTC, chrispader commented
@rlinoz fixed, there was an invalid import remaining from the merge conflicts...

2026-04-14 15:35 UTC, rlinoz commented
It is working pretty well, only issue I found is this one:

1. Mark message as unread
2. Reset cache
3. Open report

We are scrolling to the bottom of the chat, did we discuss this before?

https://github.com/user-attachments/assets/3fc0d6aa-d7ab-4060-bb5f-20626d522ed8

2026-04-15 16:13 UTC, chrispader commented
> It is working pretty well, only issue I found is this one:
> 
> 1. Mark message as unread
> 2. Reset cache
> 3. Open report
> 
> We are scrolling to the bottom of the chat, did we discuss this before?

@rlinoz this issue is fixed!

In this screen recording you can see, that before the actual unread message is shown, the report will render the latest two report actions first, which we have stored from `OpenApp`. Only after that, we can fetch the older report actions page and show the actual unread report action. This only happens when the user loads an unread report with no report actions in store/cache.


https://github.com/user-attachments/assets/8158414f-98da-448d-a5b5-97492f599b4d

2026-04-15 16:30 UTC, rlinoz commented
Ithink that is fine

2026-04-16 14:27 UTC, rlinoz commented
@chrispader some conflicts. 

@ishpaul777 can you help us finish this one?

2026-04-16 14:28 UTC, ishpaul777 commented
looking 👀

2026-04-16 14:30 UTC, ishpaul777 commented
@MelvinBot i am bit behind on context can i get a quick summary what are we doing here

2026-04-16 14:38 UTC, ishpaul777 commented
@MelvinBot can you please do a detailed review for the PR

2026-04-16 20:51 UTC, chrispader commented
@ishpaul777 @rlinoz the conflicts are due to the recent merge of [#85114: Migrate main chat to FlashList with inverted flag](https://github.com/Expensify/App/pull/85114) which already has some deploy blockers. I think we should hold on that until we're sure that we can continue with the FlashList migration.

Once FlashList has been established, i'll have to put some more effort into making this PR compatible with it, since there were changes around how we can achieve `maintainVisibleContentPosition` and with inverted lists in general. Maybe it's actually not hard, but i'm not sure it works 100% the same as in the previous `FlatList` implementation.

The whole conversation can be found starting from [this comment](https://github.com/Expensify/App/issues/33725#issuecomment-3729746125).

2026-04-20 15:27 UTC, chrispader commented
@rlinoz @ishpaul777 since https://github.com/Expensify/App/pull/85114 is not going to be reverted ([Slack](https://expensify.slack.com/archives/C08CZDJFJ77/p1776697097158039?thread_ts=1776337234.248689&cid=C08CZDJFJ77)), i will resolve merge conflicts today and test my changes with the new FlashList implementation.

2026-04-23 11:50 UTC, rlinoz commented
@chrispader some lint/typechek failures

2026-04-23 22:07 UTC, chrispader commented
@rlinoz i'm currently investigating whether we can achieve [this feature](https://github.com/Expensify/App/issues/88502#event-24766430559) with the new FlashList implementation. Basically, lots of the logic we needed for `FlatList` just became obsolete, because `maintainVisibleContentPostion` and `initialScrollIndex` work better with `FlashList`, so this works already.

2026-04-24 15:58 UTC, chrispader commented
> ## Detailed Code Review
> This is a large, complex PR touching pagination, scroll positioning, and mark-as-read logic across 28 files. Below are the findings organized by severity.
> 
> ### Bugs
> **1. In-place mutation of Onyx-cached array (`Pagination.ts:144-147`)** The `firstPage.shift()` call mutates the Onyx cache directly. `existingPages` is a reference from `pagesCollections[pageKey]`, and `.at(0)` returns a reference to the same array. This violates Onyx's immutability contract and can cause missed re-renders and stale state. Additionally, this is **redundant** with lines 152-153, which already strip `PAGINATION_START_ID` from all existing pages under the same `response.hasNewerActions === true` condition.

Valid comment. This is redundant and also in-place mutations are bad. Fixed this!

> **2. `oldestUnreadReportActionIndex` is in the wrong index domain (`usePaginatedReportActions.ts:95-100`)** `resourceItem.index` comes from `getContinuousChain`, which uses `sortedAllReportActions` (full, unfiltered). This index flows into `unreadMarkerReportActionIndex` and eventually reaches `useReportUnreadMessageScrollTracking.ts:115`, where it's compared against FlatList viewable item indexes. But the FlatList data source is `sortedVisibleReportActions` — a different, smaller array. The fallback path via `getUnreadMarkerReportAction` correctly uses `visibleReportActions` indices, but the new `oldestUnreadReportActionMarker` path (ReportActionsList.tsx:324) uses the wrong domain. This could cause the floating message counter to show/hide at incorrect scroll positions.

Also valid. Weird this didn't cause any issues with the rendering logic so far 🤔 Fixed!

> **3. Refs not reset on report navigation (`ReportActionsView.tsx:400`, `ReportActionsList.tsx:465`)** `isReportUnreadInitially` and `didMarkReportAsReadInitially` are `useRef`s set once and never reset when `reportID` changes. If `ReportActionsView`/`ReportActionsList` is reused for a different report (e.g., route param change without unmount), switching to an unread report won't trigger the initial mark-as-read, and the skeleton guard could behave incorrectly. Similarly, `isListInitiallyLoaded` state (line 454) is never reset.

Addressed!

> **4. `setTimeout` leak in scroll `useEffect` (`useFlatListScrollKey.ts:128-141`)** The `useEffect` calls `setTimeout` for `INITIAL_SCROLL_DELAY` but never returns a cleanup function. If the component unmounts or the effect re-fires before the 200ms elapses, the callback will still execute, potentially calling `renderQueue.start()` on a stale/cancelled queue.

Outdated, i removed this hook because it's no longer needed with FlashList

> **5. Race condition between Onyx prune and pagination anchor reset (`ReportActionsList.tsx:924`)** In `onLayoutInner` during `await_prune`, `pruneReportActionPagesToNewestWindow` writes to Onyx (async), then `setTreatAsNoPaginationAnchor(false)` fires synchronously. The next render of `usePaginatedReportActions` will use old (unread-anchored) pages because the Onyx write hasn't committed yet, potentially snapping the view back to the unread position.

I don't think this edge-case has ever happened so far. Agree that this might be a race condition, but fixing it would mean that we have to await the promise from `Onyx.set` in the action, which is disregarded as per https://github.com/Expensify/App/blob/main/contributingGuides/philosophies/DATA-BINDING.md#--action-methods-should-not-return-a-promise.

@rlinoz do you think we should handle this or simply ignore? The potential result would not be critical anyway. We can fix if this ever occurs.

> ### Concerns
> **6. Double-timeout race in `RenderTaskQueue` (`RenderTaskQueue.tsx:30-35, 50-53`)** `renderWithDelay()` does not set `isRendering = true`. So between calling `start()` (or `add()`) and the 500ms timeout firing, `isRendering` remains `false`, allowing a second `add()` or `start()` to schedule another timeout chain. This creates two concurrent render loops.

Outdated, we don't need the changes in `RenderTaskQueue` anymore.

> **7. `isUnreadMessagePageLoadingInitially` can cause permanent skeleton (`ReportActionsView.tsx:409`)** If a report is unread but `usePaginatedReportActions` cannot find any action with `created > lastReadTime` (e.g., actions deleted, or `lastReadTime` stale), `oldestUnreadReportAction` stays `undefined` forever, `shouldWaitForOpenReportResultInitially` stays `true`, and the skeleton is shown indefinitely. A fallback (e.g., release after `hasOnceLoadedReportActions` becomes `true`) is needed.

Addressed!

> **8. Live tail jump state machine has no timeout/escape hatch (`ReportActionsList.tsx:406`)** If `openReport` fails or `isLoadingInitialReportActions` never transitions, the machine stays in `open_report` forever, swallowing new-message scroll events. Additionally, `await_scroll` → `await_prune` transitions when `hasNewestReportAction` becomes true, but the scroll hasn't actually happened yet — just been requested via `setIsScrollToBottomEnabled(true)`. If `onLayoutInner` doesn't fire, the machine gets stuck.

Also going to ignore this until this really becomes a problem. Implementing an escape hatch would mean to add an alternative timeout, after which the `OpenReport` response would be disregarded, which is not very elegant either way.

> **9. `as unknown as` double-cast in `Pagination.ts:130-140`** The comment says tooling resolves `@libs/PaginationUtils` as untyped, but these functions are already properly typed generics. The `as unknown as` pattern completely bypasses TypeScript's type system. If signatures diverge, TS won't catch it. The underlying tooling issue should be fixed instead.

Addressed!

> **10. `renderQueue.setHandler()` called every render outside `useEffect` (`useFlatListScrollKey.ts:143-155`)** This is a side effect during render. The handler closure captures render-time values. Under React concurrent mode, this could behave unpredictably. Consider using `useEffectEvent` for the handler.

This needs to run during render, because it affects the initial render. Moving this to an effect wouldn't work.

> **11. `treatAsNoPaginationAnchor` silently discards `reportActionID` (`usePaginatedReportActions.ts:52-58`)** When `treatAsNoPaginationAnchor` is true, even an explicit `reportActionID` is ignored. But `linkedAction` (line 93) still uses `reportActionID`, creating an inconsistency where `linkedAction` could reference an action outside the paginated window.

Addressed!

> **12. No unit tests for new `PaginationUtils` functions** `mergePagesByIDOverlap`, `prunePagesToNewestWindow`, and `selectNewestPageWithIndex` are critical new functions with zero test coverage.

Added tests for these functions

> ### Nits
> **13. Commented-out `console.log` left in code (`ReportActionsView.tsx:413`)**
> 
> ```js
> // console.log({isLinkedMessageLoading: isLinkedMessagePageLoading, ...});
> ```
> 
> Variable names in the comment don't even match the current names — stale from a rename.

Removed.

> **14. `getFirstAndLastIndexForPage` backward loop is unnecessarily complex (`PaginationUtils.ts:215-221`)** The loop scans backwards but effectively only checks the last element. A simple `if (page.at(-1) === CONST.PAGINATION_END_ID)` would be clearer.

Addressed.

> **15. `useEffect` dependency array includes ref objects (`useFlatListScrollKey.ts:141`)** `isMessageOnFirstPage` and `listRef` are `useRef` objects — stable across renders, so they have no effect in the dependency array.

Outdated, this code has been removed.

2026-04-24 16:51 UTC, chrispader commented
@rlinoz i've detected one minor issue with recent changes that i still need to fix. Other than that, we're good to go

2026-04-24 17:10 UTC, rlinoz commented
meanwhile I will run another adhoc build to test

2026-04-24 17:32 UTC, chrispader commented
@rlinoz @ishpaul777 just note that this flicker issue has been fixed in the last commit, so it's not going to be in the ad-hoc build:


https://github.com/user-attachments/assets/600418a1-b97e-4e65-9c87-959b86013961

2026-04-27 14:11 UTC, rlinoz commented
Hey @chrispader lint and tests are failing, I can run another adhoc after they are fixed and we can try go get this merged this week.

2026-04-27 20:46 UTC, chrispader commented
@rlinoz i've now merged main and fixed tests and linting issues. There are some added warnings because of broken React compiler rules. I simplified the code a bit, but there are at least 1-2 spots where we specifically need to suppress Rules of React

2026-04-27 21:00 UTC, chrispader commented
Tests might need another look... 👀

2026-04-28 12:28 UTC, ishpaul777 commented
@MelvinBot can you please summarize the PR changes ? also update the PR description with summarized explaination of changes

2026-04-28 21:02 UTC, rlinoz commented
@ishpaul777 can you prioritze review this one, please?

2026-04-28 21:33 UTC, chrispader commented
@rlinoz there are some lint issues to to recent introduction of `eslint-seatbelt`. I'm discussing how to go forward with these errors with @roryabraham in [this Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1777368853266339?thread_ts=1777334893.637019&cid=C01GTK53T8Q) right now.

There are lots of Rules of React errors causing the check to fail, that cannot easily be fixed in this PR and are originally also not caused by my changes.

2026-04-28 21:34 UTC, chrispader commented
@rlinoz @ishpaul777 the current lint errors do not affect the functionality of the PR and the ad-hoc build though, so feel free to already test and review! 🙌🏼

@rlinoz also, Melvin updated the PR description and unchecked all of the checkboxes. Since Janic is not working on this PR anymore, could you please update the checklist once reviewed, so this mergable? Thanks!

2026-04-28 22:45 UTC, ishpaul777 requested changes
tested on desktop it works really well 🎉 only some minor issues

1. it shows a random message unread while report is loading  (there is no cache) 

https://github.com/user-attachments/assets/164b8d57-0ea6-4e70-8e1d-2328cab7c01e

2. when there is a image in chat it not exactly scroll to the unread message, i am guessing this is becuase thumbnail size is calculated after linking to unread message

https://github.com/user-attachments/assets/ce8f1749-3867-46e4-bbcf-466b93df58f5

2026-04-28 22:45 UTC, ishpaul777 commented on src/libs/PaginationUtils.ts
> +    const idToIndex = buildIDToIndexMap(sortedItems, getItemID);
mergePagesByIDOverlap already builds idToIndex at the top  we can pass this `idToIndex` as param

2026-04-28 22:45 UTC, ishpaul777 commented on src/hooks/usePaginatedReportActions.ts
> +        return undefined;
```suggestion
return sortedAllReportActions.findLast((reportAction) => reportAction.created > initialLastReadTime)?.reportActionID;
```

2026-04-28 22:45 UTC, ishpaul777 commented on src/libs/PaginationUtils.ts
NAB: now that buildIDToIndexMap exists, findFirst/LastItem could also use it

2026-04-29 14:44 UTC, chrispader commented on src/libs/PaginationUtils.ts
> +    const idToIndex = buildIDToIndexMap(sortedItems, getItemID);
True, removed the duplicate calculation

2026-04-29 14:57 UTC, chrispader commented on src/libs/PaginationUtils.ts
Addressed!

2026-04-29 16:20 UTC, chrispader commented
> tested on desktop it works really well 🎉 only some minor issues
> 
> 1. it shows a random message unread while report is loading  (there is no cache)

@ishpaul777 i think this should be either fixed or this was due to some invalid cache or local store... Could you retry?

https://github.com/user-attachments/assets/3d13b043-33bf-424e-aaae-c134122c7054

> 2. when there is a image in chat it not exactly scroll to the unread message, i am guessing this is becuase thumbnail size is calculated after linking to unread message

Yes, pretty sure that's because of the thumbnails. @rlinoz is this a blocker or do you think we can handle that in a follow-up PR?

2026-04-29 16:25 UTC, rlinoz commented
Let's address the thumbnail issue in a follow up please

2026-04-30 12:24 UTC, rlinoz commented
@ishpaul777 if we handle the thumbnail issue in a follow up are we good here from your perspective?

2026-05-01 17:00 UTC, ishpaul777 commented
hey! i will complete final checklist and mobile device testing today! and we are good to go,

2026-05-02 20:28 UTC, ishpaul777 commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified that the composer does not automatically focus or open the keyboard on mobile unless explicitly intended. This includes checking that returning the app from the background does not unexpectedly open the keyboard.
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: HybridApp
    - [x] Android: mWeb Chrome
    - [x] iOS: HybridApp
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L80)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4510fc76bbf5df699a2575bfb49a276af90f3ed7/src/components/LocaleContextProvider.tsx#L116-L123)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] For any bug fix or new feature in this PR, I verified that sufficient [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) are included to prevent regressions in this flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still exp [...]

2026-05-02 20:31 UTC, ishpaul777 commented
> it shows a random message unread while report is loading (there is no cache)
> > i think this should be either fixed or this was due to some invalid cache or local store... Could you retry?

this i can still repro, when opening unread report after fresh login

https://github.com/user-attachments/assets/355454cd-48f7-4130-85a9-45f2995fa682


Rest this looks good 👍

2026-05-04 09:10 UTC, chrispader commented
> > it shows a random message unread while report is loading (there is no cache)
> > > i think this should be either fixed or this was due to some invalid cache or local store... Could you retry?
> 
> this i can still repro, when opening unread report after fresh login

ahh yes, that makes sense. This is actually caused by no `reportActionsPages_` in store on empty cache/store, so after fresh login or clearing store from Troubleshoot menu.

@rlinoz this has the same root cause that we discussed previously in DM, where we would need a backend fix. Should we also fix this in a follow-up? This does not seem to be a blocker

2026-05-05 11:17 UTC, rlinoz commented
I will file an  issue for the two remainign things in this PR and we fix them in a follow up, which are

This: https://github.com/Expensify/App/pull/51366#issuecomment-4364662206
and this https://github.com/Expensify/App/pull/51366#issuecomment-4345546580

2026-05-05 23:12 UTC, rlinoz commented
Issues are here 

https://github.com/Expensify/App/issues/89677
https://github.com/Expensify/App/issues/89676

2026-05-05 23:34 UTC, rlinoz commented
asked for a final adhoc testing here https://expensify.slack.com/archives/C09V78U42D8/p1778024055931269

2026-05-06 19:47 UTC, lanitochka17 commented
Hello @janicduplessis @rlinoz @ishpaul777 @chrispader 
###  Chat - Unread marker is displayed in the conversation history while viewing the chat

Version Number: 9.3.66-5 PR:51366
Reproducible in staging?: N
Reproducible in production?: N
If this was caught during regression testing, add the test name, ID and link from TestRail: N/A
Issue reported by: Applause - Internal Team

Action Performed:
1. Go to https://51366.pr-testing.expensify.com/
2. Navigate to the conversation with the secondary user. Be sure to clear any unread messages if needed
3. Keep the conversation in view of the most recent message
4. As the secondary user - Send some messages to the main user

Expected Result: The unread marker is not displayed in the conversation history over the new messages

Actual result: The unread marker is displayed in the conversation history over the new messages while viewing chat


https://github.com/user-attachments/assets/27735ed4-feab-485e-8a4a-c11d184f4b4b

Is this new behavior, or is it actually a bug?

2026-05-06 19:56 UTC, rlinoz commented
@chrispader can you take a look please?

2026-05-06 21:31 UTC, lanitochka17 commented
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Split - Group chat not show split amount in the search results


**Version Number:** 9.3.66-5 PR:51366
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team


## Action Performed:
1. Launch Expensify App (Adhoc: v9.3.66-5 PR:51366)
2. Navigate to a group conversation with at least 2 users
3. Select Split expense
4. Select the Scan tab if it is not already active
5. Upload a digital receipt
6. Enter a description
7. Create the Split expense
8. Click on the preview
9. Click the search icon on the top right
10. Search for the group chat or view recent searches

## Expected Result:
The group chat shows the correct split amount in the search results

## Actual Result:
The group chat is not displayed with correct split amount in the search results
Issue is reproducible on Prod too.

## Workaround:
Unknown

## Platforms:
<!---
Check off any platforms that are affected by this issue
--->
Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos


https://github.com/user-attachments/assets/3e0a6475-0f7b-4cd3-9b97-803bcfc56165

2026-05-07 12:39 UTC, IuliiaHerets commented
@rlinoz **Regression is completed**
1 issue was logged:
[Split - Group chat not show split amount in the search results](https://github.com/Expensify/App/pull/51366#issuecomment-4392336153)

2026-05-08 11:38 UTC, chrispader commented
> ### Chat - Unread marker is displayed in the conversation history while viewing the chat
> Version Number: 9.3.66-5 PR:51366 Reproducible in staging?: N Reproducible in production?: N If this was caught during regression testing, add the test name, ID and link from TestRail: N/A Issue reported by: Applause - Internal Team
> 
> Action Performed:
> 
> 1. Go to [51366.pr-testing.expensify.com](https://51366.pr-testing.expensify.com/)
> 2. Navigate to the conversation with the secondary user. Be sure to clear any unread messages if needed
> 3. Keep the conversation in view of the most recent message
> 4. As the secondary user - Send some messages to the main user
> 
> Expected Result: The unread marker is not displayed in the conversation history over the new messages
> 
> Actual result: The unread marker is displayed in the conversation history over the new messages while viewing chat
>
> Is this new behavior, or is it actually a bug?

No this is not intended. Just fixed this!

2026-05-08 11:47 UTC, chrispader commented
> ## Split - Group chat not show split amount in the search results
> **Version Number:** 9.3.66-5 PR:51366 **Reproducible in staging?:** N **Reproducible in production?:** N **If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A **Issue reported by:** Applause - Internal Team
> 
> ## Action Performed:
> 1. Launch Expensify App (Adhoc: v9.3.66-5 PR:51366)
> 2. Navigate to a group conversation with at least 2 users
> 3. Select Split expense
> 4. Select the Scan tab if it is not already active
> 5. Upload a digital receipt
> 6. Enter a description
> 7. Create the Split expense
> 8. Click on the preview
> 9. Click the search icon on the top right
> 10. Search for the group chat or view recent searches
> 
> ## Expected Result:
> The group chat shows the correct split amount in the search results
> 
> ## Actual Result:
> The group chat is not displayed with correct split amount in the search results Issue is reproducible on Prod too.

@rlinoz just tried this flow and it works without any problems locally. Maybe this got fixed recently on main?

<img width="1172" height="904" alt="Screenshot 2026-05-08 at 12 46 21" src="https://github.com/user-attachments/assets/9efb1cb5-a2e1-4247-b7e6-ac8b6c82c7e6" />

https://github.com/user-attachments/assets/054b6b46-70b2-48bb-b85f-f083283ba471

2026-05-08 11:47 UTC, chrispader commented
@rlinoz all issues addressed!

2026-05-08 12:13 UTC, rlinoz approved these changes

2026-05-08 12:14 UTC, rlinoz commented
@ishpaul777 concerns are addressed and applause issues are fixed, let's merge this 🚀

2026-05-08 12:14 UTC, merged

2026-05-08 12:24 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2026-05-08 15:39 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/25562780535) to staging by https://github.com/rlinoz in version: 9.3.69-0 🚀

platform | result
---|---
🕸 web 🕸|success ✅
🤖 android 🤖|success ✅
🍎 iOS 🍎|success ✅

**Bundle Size Analysis (Sentry):**
- [Android](https://expensify.sentry.io/preprod/size/240732"})
- [iOS](https://expensify.sentry.io/preprod/size/240735"})

2026-05-08 16:43 UTC, mitarachim commented
Deploy Blocker https://github.com/Expensify/App/issues/90032 was identified to be related to this PR.

2026-05-08 17:43 UTC, lanitochka17 commented
Deploy Blocker #https://github.com/Expensify/App/issues/90052 was identified to be related to this PR.

2026-05-08 18:32 UTC, jponikarchuk commented
Deploy Blocker #90064 was identified to be related to this PR.

2026-05-11 23:40 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/25703615883) to production by https://github.com/Beamanator in version: 9.3.69-18 🚀

platform | result
---|---
🕸 web 🕸|success ✅
🤖 android 🤖|success ✅
🍎 iOS 🍎|success ✅

2026-05-19 21:23 UTC, mallenexpensify commented
@ikevin127 are you due payment for the review here? If so, how much? Looks like there were regressions

2026-05-19 21:30 UTC, ikevin127 commented
@mallenexpensify Nope, no payment due for me here. I only wanted to ensure that functionally, some tests are passing in the beginning of the PR as I worked on similar logic before.