fix: latest message instead of marked as unread
Expensify/App pull request #52689
Opened 2024-11-18 08:10 UTC by nkdengineer

### Explanation of Change

### Fixed Issues

$ https://github.com/Expensify/App/issues/44647
PROPOSAL: https://github.com/Expensify/App/issues/44647#issuecomment-2205862683

### Tests

- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-11-19 03:00 UTC, nkdengineer commented
@rojiphil I am a little stuck on the Native builds, will add later

2024-11-25 13:56 UTC, rojiphil reviewed
@nkdengineer Did you consider [this comment](https://github.com/Expensify/App/issues/44647#issuecomment-2451904105) during PR implementation?

2024-11-28 08:15 UTC, nkdengineer commented
@rojiphil i updated and tested well

2024-12-06 18:30 UTC, rojiphil commented
@nkdengineer Sorry for the delay here. Please merge with the latest main. I am planning to review this over the weekend. Thanks

2024-12-09 03:46 UTC, nkdengineer commented
@rojiphil i merged

2024-12-10 08:37 UTC, rojiphil commented
@nkdengineer Thanks for the merge. There is a bug when we delete the item. Can you please check? 
And here is a test video demonstrating the problem:


https://github.com/user-attachments/assets/20dcedf4-9eae-453a-ba45-4449a4e5d439

2024-12-10 08:52 UTC, rojiphil commented
@Expensify/design Currently, when we scroll to the `unread` message, we display the message towards the top of the chat report where there are lots of chat in the report. Is this fine or do we show in the middle or towards the bottom of the chat report? 
We can see the current behaviour in the initial part of the test video [here](https://github.com/Expensify/App/pull/52689#issuecomment-2530806838)

2024-12-10 08:53 UTC, rojiphil commented on src/pages/home/report/ReportActionsList.tsx
> +            reportScrollManager?.scrollToIndex(unreadReportActionIndex, undefined, 0.9);
NAB but let us add view position value as a constant in CONST file.

2024-12-10 14:11 UTC, shawnborton commented
> Is this fine or do we show in the middle or towards the bottom of the chat report?

The current behavior you are showing in the video feels totally fine to me? Curious what the rest of the @Expensify/design gang thinks though.

2024-12-10 14:17 UTC, dannymcclain commented
I agree - the position in that video looks good to me. We will be able to change the caret icon to point up or down depending on where the message is? (Sorry if this has been asked before.)

2024-12-11 03:47 UTC, dubielzyk-expensify commented
Agree that the video seems correct 👍

2024-12-11 05:24 UTC, rojiphil commented
Thanks design team for the inputs. We will go with the current behavior itself.

> We will be able to change the caret icon to point up or down depending on where the message is?

That’s a good point. @nkdengineer Let’s add that too.

2024-12-13 02:16 UTC, rojiphil commented
@nkdengineer Please update

2024-12-13 07:35 UTC, nkdengineer commented
I'm investigating, will give an update today or Monday.

2024-12-19 04:20 UTC, nkdengineer commented
I'm still finding the way to this [bug](https://github.com/Expensify/App/pull/52689#issuecomment-2530806838)

2024-12-25 08:27 UTC, nkdengineer commented
I'm investigating

2025-02-03 03:30 UTC, rojiphil commented
> I have tried many ways to do it but still no way can succeed. @rojiphil Do you have any suggestions on this?

Sorry for the delay in response here. Can you please provide details about the problems you are facing?

2025-02-03 03:31 UTC, rojiphil commented
Also, please merge with the latest as there are conflicts

2025-02-11 02:26 UTC, rojiphil commented
Oops. I missed the last comment [here](https://github.com/Expensify/App/pull/52689#issuecomment-2632784038). Will review the comment today

2025-02-11 19:27 UTC, rojiphil reviewed
@nkdengineer Before having a look at the caret icon improvement, I have a query about the recent changes. Please have a look.

The recent changes also seem to have caused the following issue on scrolling to the top and, then, clicking on `New message`

https://github.com/user-attachments/assets/fd86b58b-1f94-486e-a276-041e1beab2b9

2025-02-11 19:27 UTC, rojiphil commented on patches/react-native-web+0.19.13+007+fix-scrollable-overflown-text.patch
> ++          if (doesFrameWithTheSameIndexExist) {
Can you please explain how the last changes helps in fixing the delete issue? It seems like we have reverted to the previous code here.

2025-03-19 03:10 UTC, rojiphil commented
@nkdengineer Sorry for the delay here. I will pick this up within the next couple of days.

2025-03-28 02:51 UTC, rojiphil commented
@nkdengineer Can you please merge with the latest main? I will take a look at this today.

2025-03-30 18:50 UTC, rojiphil commented
Review in progress

2025-04-25 16:05 UTC, rojiphil commented
> friendly bump @rojiphil

@nkdengineer Extremely sorry for not being able to follow up on this. 
Looks like some recent change has broken quite a lot of things as 9 checks are failing. Can you please have a look?
And thanks for your patience, I'll be sure to pick this up on priority.

2025-04-28 05:46 UTC, rojiphil commented
> it seems like this is a bug in main and other branches have the same problem.

@nkdengineer I just checked with the latest main and `npm run clean` completes successfully. However, with our branch, it does not. On reverting the `patch` file changes though, the `npm run clean` completes successfully. Looks like something to do with our patch file. Can you please check? Thanks.

2025-05-01 14:43 UTC, rojiphil commented
@nkdengineer There is still some edge case which causes the `new message` to not display the `unread` message. I do not have a reliable steps to reproduce but I do get this once in a while. I think we need to investigate this further. While I continue to try to reproduce this consistently, please have a look at this too. 


https://github.com/user-attachments/assets/2bde88c6-377a-48ca-868d-1c78b20a8929

2025-06-18 08:49 UTC, nkdengineer commented
bump here @rojiphil

2025-07-01 09:26 UTC, nkdengineer commented
It looks like we are not prioritizing this PR, so I think we can close it @rojiphil

2025-07-02 02:37 UTC, rojiphil commented
> It looks like we are not prioritizing this PR, so I think we can close it @rojiphil

@nkdengineer I just checked and the original issue still exists with latest main as demonstrated in attached video. 
I don’t think priority is the issue here but it is just that the proposed solution is not fixing the issue completely as I already mentioned [here](https://github.com/Expensify/App/pull/52689#issuecomment-2844978268). And I think it does not make sense to merge without a proper fix. 

https://github.com/user-attachments/assets/2763d9dd-8bc0-4abf-b93f-b6f321ce73ad

2025-07-09 07:50 UTC, nkdengineer commented
@rojiphil I can't find a way to fix the other edge cases. Let's close this PR and open it up to other contributors.

2025-07-10 13:15 UTC, rojiphil commented
> I can't find a way to fix the other edge cases. Let's close this PR and open it up to other contributors.

@nkdengineer To me, it looked like we were very close to getting this done. Let me give a shot at this sometime early next week. If it is still not possible, we will proceed as per your suggestion.

2025-08-04 02:48 UTC, nkdengineer commented
friendly bump here @rojiphil

2025-09-08 05:10 UTC, nkdengineer commented
@rojiphil friendly bump again

2025-09-13 07:49 UTC, rojiphil commented
@nkdengineer Very sorry for the delay here to check that edge case. I will prioritise this early next week for sure. 
Meanwhile, I see a lot of failing checks here due to patch file version issue. Can you please resolve this too while merging with the latest main? Thanks.

2025-09-18 08:00 UTC, rojiphil commented
I still see a lot of failing checks. Is it simple to fix or do you think the PR needs a complete overhaul?

2025-09-18 18:02 UTC, nkdengineer commented
we might be having conflict with react-native-web lib, i will try to resolve this issue soon

2025-09-23 10:44 UTC, nkdengineer commented
@rojiphil i fixed

2025-09-30 08:22 UTC, nkdengineer commented
friendly bump @rojiphil

2025-10-07 06:52 UTC, rojiphil commented
I will pick it up this week.

2025-10-13 13:54 UTC, rojiphil commented
Looking into this now...

2025-10-16 02:34 UTC, rojiphil commented
Investigation still in progress on the [issue](https://github.com/Expensify/App/pull/52689#issuecomment-3026149157) here.

2025-10-20 23:20 UTC, rojiphil commented
@nkdengineer With the latest main, it looks like [this code](https://github.com/nkdengineer/App/blob/7abb48dd07f2c7a763c0b5239b20cd3bd3f6ea99/patches/react-native-web/react-native-web%2B0.20.0%2B013%2Bfix-inverted-flatlist-scroll.patch#L17C1-L30C12) needs to be executed only if `curr` does not exist. No?

2025-10-20 23:21 UTC, rojiphil commented
The issue can be consistently reproduced with the following steps:
1. User 1: Navigate to a 1:1 conversation between User 1 and User 2 that has a large history of messages.
2. User 1: Scroll the conversation a little and hover over a message from the other user and mark the message as "Unread"
3. User 1: Scroll further up the conversation such that `New Messages` floating message is displayed.
4. User 2: Login in another device as User 2 and leave a new message in 1:1 conversation between User 1 and User 2. 
5. User 1: Click on "New Messages" button
6. Verify that: User is scrolled to the message marked as unread after clicking the 'New messages' button

And I think the issue seems to be occur because the `props` and `frames` are out of sync [here](https://github.com/necolas/react-native-web/blob/a9de220ba9e65bdea540fb5322ffb1da2b0bf442/packages/react-native-web/src/vendor/react-native/VirtualizedList/index.js#L250). Because of this, the index does not match [here](https://github.com/necolas/react-native-web/blob/a9de220ba9e65bdea540fb5322ffb1da2b0bf442/packages/react-native-web/src/vendor/react-native/VirtualizedList/index.js#L1881). What do you think?

2025-10-27 08:30 UTC, nkdengineer commented
> And I think the issue seems to be occur because the props and frames are out of sync [here](https://github.com/necolas/react-native-web/blob/a9de220ba9e65bdea540fb5322ffb1da2b0bf442/packages/react-native-web/src/vendor/react-native/VirtualizedList/index.js#L250). Because of this, the index does not match [here](https://github.com/necolas/react-native-web/blob/a9de220ba9e65bdea540fb5322ffb1da2b0bf442/packages/react-native-web/src/vendor/react-native/VirtualizedList/index.js#L1881). What do you think?

@rojiphil  I have the same problem and I have tried many ways to deal with it but still can't solve it. Do you have any suggestions for this?

2025-11-07 07:55 UTC, nkdengineer commented
@rojiphil I tested again and not see the issue with these steps now. Can you check again?

2025-11-07 17:32 UTC, joekaufmanexpensify requested changes
Good from a product perspective. @nkdengineer could you please make sure to always fill out the explanation of change section so it's clear to reviewers what the change is doing?

2025-11-10 19:41 UTC, joekaufmanexpensify commented
bump @nkdengineer

2025-11-10 19:43 UTC, nkdengineer commented
I updated.

2025-11-11 16:10 UTC, joekaufmanexpensify submitted a review, later dismissed
Thanks!

2025-11-13 07:41 UTC, nkdengineer commented
@rojiphil Friendly bump.

2025-11-21 09:49 UTC, nkdengineer commented
@rojiphil Friendly bump

2026-01-07 08:52 UTC, nkdengineer commented
@rojiphil Friendly bump.

2026-01-20 16:36 UTC, joekaufmanexpensify commented
@rojiphil bump on the above

2026-01-21 15:37 UTC, rojiphil commented
> I tested again and not see the issue with these steps now. Can you check again?

Ok. Will review this soon in the next few days. If there is still no headway, we will see if any experts can help. 
Meanwhile, @nkdengineer please merge with the latest main one last time. And thanks for the patience.

2026-01-23 09:11 UTC, nkdengineer commented
@rojiphil Updated.

2026-02-17 18:25 UTC, rojiphil commented
@nkdengineer The steps for the issue mentioned [here](https://github.com/Expensify/App/pull/52689#issuecomment-3424077668) still exist. As you suggested some time back, I think we can close this and open it up for proposals again. 


https://github.com/user-attachments/assets/c9e8f8c2-ff3d-4935-969e-ea433109c632

2026-02-22 13:26 UTC, closed without merging