feat: Step 3 logic
Expensify/App pull request #52954
Opened 2024-11-22 11:01 UTC by MrMuzyk

### Explanation of Change

Implements validation, API, navigation and other logic for step 3 in global reimbursements flow

### Fixed Issues

$ https://github.com/Expensify/App/issues/50905
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2025-01-07 13:20 UTC, MrMuzyk commented
@hungvu193 Hey, I've marked it as ready for review because everything on FE is done (still need to get translations). It requires some changes on BE side that Ive mentioned before - https://github.com/Expensify/App/issues/50905#issuecomment-2557037200. Once it's done everything should start working properly without extra changes need on FE side so we can save some time by starting review now

2025-01-07 13:45 UTC, hungvu193 commented
Cool. Thanks for letting me know 😁

2025-01-09 08:16 UTC, MrMuzyk commented
@hungvu193 Hey, when can I expect the review? :)

2025-01-09 08:18 UTC, hungvu193 commented
> @hungvu193 Hey, when can I expect the review? :)

Oops I thought this was not ready because we're waiting for BE changes?

2025-01-09 08:22 UTC, MrMuzyk commented
Ye, now I realise that maybe my comment was a bit convoluted :D Well, some BE changes are needed and Max is working on them as far as I know, but FE is already done. 

At the moment data we're sending in each step is not being saved in onyx. Because of that, I dont have the `bankAccountID` created after step 2 so the final request from step 3 is not passing. However once it is fixed on BE side, final request should work without any extra changes as Im already trying to read `bankAccountID` value from onyx

2025-01-09 08:23 UTC, hungvu193 commented
All good. My bad 🥲. I'll review today

2025-01-10 06:53 UTC, hungvu193 requested changes

2025-01-10 06:53 UTC, hungvu193 commented on src/pages/ReimbursementAccount/NonUSD/BusinessInfo/substeps/PaymentVolume.tsx
> +    const policyID = reimbursementAccount?.achData?.policyID;
```suggestion
    const policyID = reimbursementAccount?.achData?.policyID ?? CONST.DEFAULT_NUMBER_ID;
```

2025-01-10 06:53 UTC, hungvu193 commented on src/pages/ReimbursementAccount/NonUSD/BusinessInfo/substeps/AverageReimbursement.tsx
> +    );
Looks like we have `SingleFieldStep` for this kind of Form. Can we reuse it instead?

2025-01-10 06:53 UTC, hungvu193 commented on src/pages/ReimbursementAccount/NonUSD/BusinessInfo/substeps/AverageReimbursement.tsx
> +    const policyID = reimbursementAccount?.achData?.policyID;
```suggestion
    const policyID = reimbursementAccount?.achData?.policyID ?? CONST.DEFAULT_NUMBER_ID;
```

2025-01-10 06:53 UTC, hungvu193 commented on src/pages/ReimbursementAccount/NonUSD/BusinessInfo/BusinessInfo.tsx
> +                taxIDEINNumber: onyxValues[INPUT_KEYS.TAX_ID_EIN_NUMBER],
I'm fine with this way but I think we can shorten it:
Here's the idea, lmk what do you think 😄 
```javascript
    const params = {};

    Objects.key(INPUT_KEYS).forEach((currentKey) => {
        params[currentKey] = onyxValues[currentKey];
    });

    BankAccounts.saveCorpayOnboardingCompanyDetails({...params, currencyNeeded: currency})

```

2025-01-10 10:21 UTC, MrMuzyk commented on src/libs/ValidationUtils.ts
> +function isValidABN(registrationNumber: string): boolean {
In the design doc we have this - https://docs.google.com/document/d/1Y4P7G9h0Easjcea7wyk52gKrNB9o1yTjpmJFYkrHDW4/edit?tab=t.0#bookmark=id.sttexatm14wb

Not sure if you have access to this doc

2025-01-10 10:21 UTC, MrMuzyk commented on src/libs/ValidationUtils.ts
> +function isValidABN(registrationNumber: string): boolean {
<img width="683" alt="image" src="https://github.com/user-attachments/assets/9e6965d7-3f17-4943-a836-63b7d53bff5a" />

2025-01-10 10:23 UTC, MrMuzyk commented on src/pages/ReimbursementAccount/NonUSD/BusinessInfo/BusinessInfo.tsx
> +    const policyID = reimbursementAccount?.achData?.policyID;
This was changed due to latest changes in linting rules. I think we just gotta leave it like that as type for policyID is `?: string`

2025-01-10 10:38 UTC, MrMuzyk commented on src/pages/ReimbursementAccount/NonUSD/BusinessInfo/substeps/AverageReimbursement.tsx
> +    );
SingleFieldStep is used for TextInput fields. Here we have a different component. Maybe in the future we will rework SingleFieldStep so its more flexible or create a different reusable component for PushRowWithModal case as we have a few of these

2025-01-10 11:51 UTC, MrMuzyk commented on src/pages/ReimbursementAccount/NonUSD/BusinessInfo/substeps/PaymentVolume.tsx
> +    const policyID = reimbursementAccount?.achData?.policyID;
https://github.com/Expensify/App/pull/52954#discussion_r1910158861

2025-01-10 11:51 UTC, MrMuzyk commented on src/pages/ReimbursementAccount/NonUSD/BusinessInfo/substeps/AverageReimbursement.tsx
> +    const policyID = reimbursementAccount?.achData?.policyID;
https://github.com/Expensify/App/pull/52954#discussion_r1910158861

2025-01-10 12:30 UTC, MrMuzyk commented
@hungvu193 Hey, I've updated the PR and responded to the comments

2025-01-10 12:32 UTC, hungvu193 commented
Thank you. I'll review it soon

2025-01-12 15:25 UTC, hungvu193 commented on src/libs/ValidationUtils.ts
> +function isValidABN(registrationNumber: string): boolean {
I can access to this docs, but I don't understand this function logic. Can you explain it? Ty
What's the weights, checksum and why it needs to be divisible by 89

2025-01-12 15:25 UTC, hungvu193 commented on src/pages/ReimbursementAccount/NonUSD/BusinessInfo/BusinessInfo.tsx
> +                taxIDEINNumber: onyxValues[INPUT_KEYS.TAX_ID_EIN_NUMBER],
I think it looks better. Let's do it 😄

2025-01-13 07:54 UTC, MrMuzyk commented on src/libs/ValidationUtils.ts
> +function isValidABN(registrationNumber: string): boolean {
For these various business numbers I did some looking and found that in few cases there is more than number of digits/letters in order to validate them.

These are the requirements for:
ABN - https://abr.business.gov.au/Help/AbnFormat
ACN - https://asic.gov.au/for-business/registering-a-company/steps-to-register-a-company/australian-company-numbers/australian-company-number-digit-check/

These pages have `gov.au` in their name so I'd assumed they're correct and tightened validation.  If this is too much I can change it to a simple length check

2025-01-13 10:27 UTC, hungvu193 commented on src/libs/ValidationUtils.ts
> +function isValidABN(registrationNumber: string): boolean {
Yeah, these websites look legit to me too. Can you leave a comment to explain that we use the logic from these websites?

2025-01-13 10:34 UTC, MrMuzyk commented on src/libs/ValidationUtils.ts
> +function isValidABN(registrationNumber: string): boolean {
Sure

2025-01-13 11:07 UTC, MrMuzyk commented on src/pages/ReimbursementAccount/NonUSD/BusinessInfo/BusinessInfo.tsx
> +                taxIDEINNumber: onyxValues[INPUT_KEYS.TAX_ID_EIN_NUMBER],
Updated

2025-01-13 11:07 UTC, MrMuzyk commented on src/libs/ValidationUtils.ts
> +function isValidABN(registrationNumber: string): boolean {
Done

2025-01-13 11:30 UTC, MrMuzyk commented
Everything is fixed. Now we're waiting for BE to test if everything works as a whole. I'll keep an eye on the PR and try to keep it up to date in the meantime

2025-01-14 01:40 UTC, hungvu193 commented
Looking good. I'll test again today 🎉

2025-01-14 08:34 UTC, MrMuzyk commented
Sure thing!

2025-01-14 08:45 UTC, MrMuzyk commented
I got it too but seems like the request passed and data got saved in onyx. Looking into cause of that crash, will let you know once it's fixed

2025-01-14 10:11 UTC, MrMuzyk commented
Ok, I know where the issue is. After we do the save, `reimbursementAccount` inside onyx is simply overwritten (at least that what it looks like) instead of being updated (merged with existing entries).

Before sending 
<img width="1920" alt="Screenshot 2025-01-14 at 11 04 19" src="https://github.com/user-attachments/assets/d4c4a8a6-ffae-49d2-9655-fe130c24c169" />

After sending
<img width="1920" alt="Screenshot 2025-01-14 at 11 05 04" src="https://github.com/user-attachments/assets/66f1a72f-c943-46a4-97bc-68f24c4684a6" />

It crashes only for AUD because displayed steps for AUD accounts are being calculated on the fly using policies currency. API call succeeds but policyID is being wiped out after onyx merge and for a split second before redirect whole form is getting updated because we start getting undefined instead of policyID
<img width="1920" alt="Screenshot 2025-01-14 at 11 10 27" src="https://github.com/user-attachments/assets/b5ee5e5f-6345-4aa2-ba0c-0d842f83c869" />

I'll let Max know

2025-01-15 03:16 UTC, hungvu193 commented
I assume that BE is ready. I got this error while trying to submit on step 3. It looks like we need more infor about the validation from BE, after that we can add more strict rules to our FE validation.

https://github.com/user-attachments/assets/a41cc10a-5de1-46b4-9ed5-c30a24c79bc9

2025-01-15 07:05 UTC, MrMuzyk commented
Looking into it

2025-01-15 07:48 UTC, MrMuzyk commented
I don't think latest BE is deployed - still no policyID after 2nd step. However I've found one small issue with `ErrorUtils` call, fixed that

2025-01-15 08:48 UTC, hungvu193 commented
I think we changed the eslint rules recently, can you address the lint? @MrMuzyk

2025-01-15 08:58 UTC, MrMuzyk commented
On it

2025-01-15 15:13 UTC, MrMuzyk commented
@hungvu193 Looks like the issue with missing policyID is fixed - AUD accounts should pass too. I've talked with Max and I've added 2 missing fields but at the moment I'm getting `"message": "500 Unhandled Exception",` Hopefully we will sort this out soon, we're close

2025-01-16 07:50 UTC, hungvu193 commented
> @hungvu193 Looks like the issue with missing policyID is fixed - AUD accounts should pass too. Eslint issues are fixed as well. I've talked with Max and I've added 2 missing fields but at the moment I'm getting `"message": "500 Unhandled Exception",` Hopefully we will sort this out soon, we're close

Yeah, I got the same `500` issue with you. Let me know when. it's resolved, I think this PR is ready to merge.

2025-01-21 09:02 UTC, MrMuzyk commented
@hungvu193 Hey, latest fix for BE made it live and now Step 3 is working correctly for me. Let's close this one today 🚀

2025-01-21 14:11 UTC, hungvu193 commented
Awesome. I'll test it today!

2025-01-21 17:00 UTC, hungvu193 commented
Nice, it's working well 🚀 

https://github.com/user-attachments/assets/010a1e14-bbab-4dc6-be5f-447a771ca79f

2025-01-21 17:41 UTC, hungvu193 commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] For any bug fix or new feature in this PR, I verified that sufficient [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) are included to prevent regressions in this flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add sc [...]

2025-01-21 18:08 UTC, hungvu193 approved these changes

2025-01-21 19:34 UTC, madmax330 reviewed
Just one small comment 😅

2025-01-21 19:34 UTC, madmax330 commented on src/ONYXKEYS.ts
> +    /** Corpay fieds to be used in the bank account creation setup */
```suggestion
    /** Corpay fields to be used in the bank account creation setup */
```

2025-01-22 07:04 UTC, MrMuzyk commented on src/ONYXKEYS.ts
> +    /** Corpay fieds to be used in the bank account creation setup */
Fixed

2025-01-22 09:29 UTC, madmax330 approved these changes

2025-01-22 09:30 UTC, merged

2025-01-22 09:39 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2026-08-06 05:52 UTC, suneox commented on src/libs/actions/BankAccounts.ts
> +    return API.read(READ_COMMANDS.GET_CORPAY_ONBOARDING_FIELDS, {countryISO: country});
Coming from #96784 checklist:

This PR introduced the Corpay NonUSD "Step 3" (Business Info) onboarding, including the `getCorpayOnboardingFields` action and the `BusinessInfo` mount effect. Both shipped without a guard against an empty `country`, so during the Onyx hydration window (deep-link / refresh / continue-setup) the effect fires `GetCorpayOnboardingFields` with `countryISO: ''` → `402 Missing countryISO` → Business Info fields fail to load. The sibling `BankInfo` step guarded this; this one didn't.

The current fix in #97249 guards the shared action (`if (!country) return`), which covers both call sites and any future caller.