fix: Crash on Edge or Opera
Expensify/App pull request #5298
Opened 2021-09-16 15:13 UTC by parasharrajat

Please review @Beamanator 

### Details

### Fixed Issues

$ GH_LINK

### Tests | QA Steps

 1. Open Microsoft Edge
 2. Navigate New Expensify
 3. Navigate to Profile or Preferences in settings

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

![Screenshot 2021-09-16 20:40:43](https://user-images.githubusercontent.com/24370807/133638207-5f460b2e-85a2-4918-aca7-cd07b282c47b.png)

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-09-16 15:15 UTC, parasharrajat commented
I am not sure why Marc is getting assigned to all of my PRs. :shield:

2021-09-17 07:53 UTC, Beamanator commented
> I am not sure why Marc is getting assigned to all of my PRs. 🛡️

Thanks for noticing this, I am pretty sure I know why, a change to the PR template negatively affected how some internal auto-assigner was working 😅

2021-09-17 08:02 UTC, Beamanator commented
@parasharrajat can you also test on Opera?

2021-09-17 08:15 UTC, Beamanator commented on src/libs/getBrowser/index.web.js
>          temp = userAgent.match(/\b(OPR|Edge)\/(\d+)/);
Looking at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent, I don't see a case `Edge` will be defined in the userAgent, especially for Opera. Should it be removed?

2021-09-17 08:20 UTC, Beamanator requested changes
2 little comments - about Opera regex matching & returning browser w/out version # for opera and edge

2021-09-17 08:20 UTC, Beamanator commented on src/libs/getBrowser/index.web.js
> +            return temp.slice(1).join(' ').replace('OPR', 'Opera');
If I remember correctly, we decided we don't care about version number yet (this function is only for getting browser name). So I think we can just `return 'Opera';` here, and on line 27 below just `return 'Edge';` right?

2021-09-17 12:05 UTC, parasharrajat commented
@Beamanator Changes done.

2021-09-17 12:30 UTC, Beamanator approved these changes
Nice, thanks man 👍

2021-09-17 13:54 UTC, merged

2021-09-17 13:55 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-09-20 21:51 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1255112380) to staging by @Beamanator in version: 1.0.99-5 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-09-22 00:45 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1259726831) to production by @Jag96 in version: 1.1.0-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅