[GR Phase 3] Step 5 - navigation, default data, logic and API call to save it
Expensify/App pull request #53053
Opened 2024-11-25 09:22 UTC by burczu

### Explanation of Change

### Fixed Issues

$: https://github.com/Expensify/App/issues/50907
PROPOSAL: n/a

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2025-03-29 16:44 UTC, hungvu193 commented
I couldn't pass step 5. I got `message:  "400 Invalid field in inputs"` I think there will be a validation mismatch between BE and FE:


https://github.com/user-attachments/assets/65d25cbc-2765-45d4-87b4-ad4ac13a1417

2025-03-31 08:49 UTC, burczu commented
hey @hungvu193 - what country and currency do you use in the scenario you are testing in the above video?

2025-03-31 09:28 UTC, burczu commented
@hungvu193 Thank you. 

@madmax330 Could you please take a look at this one? The payload seem to be correct; also we are sending `addressProof` and `copyOfID` files for GBP and UK, which is correct.

2025-03-31 09:42 UTC, madmax330 commented
@hungvu193 this is the error that was thrown in the request: 

> Invalid field found in inputs ~~ field: 'addressProof'

Looking at the doc this is what it says:

> Address Proof for Signatories & Beneficial Owners who DO NOT RESIDE in GB

So I think we can skip that one, I'll make the update BE side b/c right now we always expect it. So if you pass it it should work

2025-03-31 09:45 UTC, hungvu193 commented
> Also for it to be easier for me to debug you can just share the requestID that is in the response and I can find it easily

Sure. Here you are:
```javascript
{
    "jsonCode": 400,
    "message": "400 Invalid field in inputs",
    "source": "auth-via-api",
    "onyxData": [],
    "requestID": "928ee952397de2df-HKG"
}
```

2025-03-31 09:49 UTC, hungvu193 commented
@madmax330 and @burczu, I think we should add RBR for Workflow if there's error in our bank account flow, currently there's RBR in WorkspaceListPage. However we couldn't see where it is. Wdyt? We can implement it as a follow-up.

https://github.com/user-attachments/assets/0664f4c5-ad21-4dfd-92e3-f9a67c21c977

2025-03-31 10:21 UTC, madmax330 commented
@hungvu193 that also doesn't have `addressProof` it need to be passed as a file for each director

2025-03-31 10:21 UTC, madmax330 commented
> However we couldn't see where it is. Wdyt? We can implement it as a follow-up.

yeah I'm working on that separately

2025-03-31 10:44 UTC, hungvu193 commented
> @hungvu193 that also doesn't have `addressProof` it need to be passed as a file for each director

I think I see the `addressProof` in the payload, but I'm not sure if it's the correct format:

<img width="517" alt="Screenshot 2025-03-31 at 17 30 28" src="https://github.com/user-attachments/assets/85c3a804-ecd1-4c52-8fe4-54dde971b192" />

2025-03-31 10:48 UTC, hungvu193 commented
I switched to EUR and got the same error. Here's the requestID: 
```javascript
requestID:  "928f43a97bfeb852-LAX"
```

2025-03-31 12:34 UTC, madmax330 commented
The format is not correct, it should be like in the previous step `director_currentUser_addressProof`

2025-03-31 12:40 UTC, burczu commented
@madmax330 Hmm... this must have been changed:
> The format is not correct, it should be like in the previous step director_currentUser_addressProof

We discussed on slack the expected payload should look like below:
```
{
     "proofOfDirectors": binary,
     "inputs": {
          "signerCompleteResidentialAddress": "",
          "signerDateOfBirth": "",
          "signerEmail": "",
          "signerFullName": "",
          "signerJobTitle": "",
          "director_currentUser_fullName": "",
          "director_currentUser_jobTitle": "",
          "director_currentUser_occupation": "",
          "director_UID1_fullName": "",
          "director_UID1_jobTitle": "",
          "director_UID1_occupation": "",
          "director_UID2_fullName": "",
          "director_UID2_jobTitle": "",
          "director_UID2_occupation": ""
     }
     "directorIDs": "currentUser,UID1,UID2"
}
```

2025-03-31 14:40 UTC, madmax330 commented
When we did the previous step with @MrMuzyk we realized the files don't parse when you put them inside inputs. 
So for the files where their is one for each person (each director will have his own proof of address) 
We have to include them in the base level as well, but they still need to have the IDs so we know where they belong to.

Maybe I hadn't mentioned that explicitly before.

2025-04-01 07:02 UTC, burczu commented
@madmax330 Ok, so I need to slightly change the flow in that case... I'll work on this today. All the files are specific to each person and we need to collect them for all directors separately?

2025-04-02 08:23 UTC, burczu commented
@madmax330 Ok, so I've changed the flow to address the requirement of passing files outside of the `inputs` object but with the ID, similar to what we do for beneficial owner step. Here's how the example payload look now:

```
{
    "inputs": {
        "signerFullName":"test",
        "signerEmail":"bartek.dybowski+518@callstack.com",
        "signerJobTitle":"test",
        "signerDateOfBirth":"2007-03-21",
        "signerCompleteResidentialAddress":"Main Street, Park City, UT, 84060",
        "director_currentUser_occupation":"test",
        "director_currentUser_fullName":"test",
        "director_currentUser_jobTitle":"test"
    },
    "director_currentUser_proofOfDirectors": (binary),
    "directorIDs": "currentUser",
    "bankAccountID": 6991239,
```

but I'm still getting the error:

![Screenshot 2025-04-02 at 10 21 41](https://github.com/user-attachments/assets/29c66417-9114-4441-ae74-0518df73ac0a)

What is incorrect here (the requestID is `929ee383e84d34d0-LAX`)?

2025-04-04 04:23 UTC, hungvu193 commented
@burczu Let me know when it's ready 😄

2025-04-08 06:53 UTC, burczu commented
@hungvu193 Sure thing - after discussing it with @madmax330 we had to change the flow once again, and now I'm waiting for the endpoint to be deployed on staging. I think we are close to finalize this.

2025-04-11 09:22 UTC, burczu commented
@tgolen I think you can get back to reviewing this - the flow is updated, and I've updated screen recordings. Still waiting for translations confirmation - I think I'll have it soon.

2025-04-11 09:27 UTC, madmax330 commented
Did you mean @hungvu193?

2025-04-11 09:30 UTC, burczu commented
> Did you mean @hungvu193?

Ahhh... you are right :)

2025-04-11 10:58 UTC, hungvu193 commented
Nice. It's working 🎉 . I'll complete the review this week

2025-04-12 17:00 UTC, hungvu193 requested changes

2025-04-12 17:04 UTC, hungvu193 commented on src/components/UploadFile.tsx
> +                allowMultiple={fileLimit > 0}
For an example, when the file limit is 1, I can choose 2 files without error but it only displays 1 file on the result.


https://github.com/user-attachments/assets/7ff0e547-3160-4d6f-80bb-281a360fb384

2025-04-14 09:03 UTC, burczu commented on src/components/UploadFile.tsx
> +                allowMultiple={fileLimit > 0}
Yeah, you are right - makes sense. Fixed

2025-04-14 09:37 UTC, hungvu193 commented
All good. Then I think the final thing here is the translations right? @burczu

2025-04-14 09:47 UTC, burczu commented
@hungvu193 Yes, I'm still waiting for it - will let you know once I apply them in the code.

2025-04-15 05:41 UTC, burczu commented
@hungvu193 Spanish translations updated.

2025-04-15 06:06 UTC, hungvu193 approved these changes
LGTM

2025-04-15 06:06 UTC, hungvu193 commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified that the composer does not automatically focus or open the keyboard on mobile unless explicitly intended. This includes checking that returning the app from the background does not unexpectedly open the keyboard.
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] For any bug fix or new feature in this PR, I verified that sufficient [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) are included to prevent regressions in this flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expect [...]

2025-04-15 06:09 UTC, hungvu193 approved these changes

2025-04-15 08:07 UTC, madmax330 commented on src/libs/API/parameters/SaveCorpayOnboardingDirectorInformationParams.ts
> +    directorIDs?: string;
This is also out of date

2025-04-15 08:07 UTC, madmax330 commented on src/libs/API/parameters/SaveCorpayOnboardingDirectorInformationParams.ts
> +    PRDandFSG?: FileObject;
This is out of date right?

2025-04-15 08:07 UTC, madmax330 commented on src/pages/ReimbursementAccount/NonUSD/SignerInfo/HangTight.tsx
> +        // TODO this should send a message to the email provided in the previous step
What was this for?

2025-04-15 08:07 UTC, madmax330 commented on src/pages/ReimbursementAccount/NonUSD/SignerInfo/index.tsx
> +            directorIDs: `${directorKeys.toString()}`,
We don't need this anymore since we're doing them one at a time

2025-04-15 08:07 UTC, madmax330 commented on src/pages/ReimbursementAccount/NonUSD/SignerInfo/index.tsx
> +        // TODO: the message to the email provided in the previous step should be sent
Not sure what this is? Isn't think done in the `AskForCorpaySignerInformation` command?

2025-04-15 08:13 UTC, burczu commented on src/pages/ReimbursementAccount/NonUSD/SignerInfo/index.tsx
> +        // TODO: the message to the email provided in the previous step should be sent
yes - this is placeholder for handling this endpoint, we do it in other PR, as this was intented to be done as separate issue

2025-04-15 08:13 UTC, burczu commented on src/pages/ReimbursementAccount/NonUSD/SignerInfo/index.tsx
> +            directorIDs: `${directorKeys.toString()}`,
alright, I'll remove it, thanks

2025-04-15 08:16 UTC, burczu commented on src/pages/ReimbursementAccount/NonUSD/SignerInfo/HangTight.tsx
> +        // TODO this should send a message to the email provided in the previous step
It is a handler for the button on the last screen below, on the right:

![Screenshot 2025-04-15 at 10 15 22](https://github.com/user-attachments/assets/5bbfca3d-871c-479e-b518-5e9a74b7780b)

I presumed I will call the `AskForCorpaySignerInformation` endpoint, is it correct? And this is part of another issue, will be done in separate PR after we merge this one.

2025-04-15 08:17 UTC, burczu commented on src/libs/API/parameters/SaveCorpayOnboardingDirectorInformationParams.ts
> +    PRDandFSG?: FileObject;
right, I'll fix it

2025-04-15 08:17 UTC, burczu commented on src/libs/API/parameters/SaveCorpayOnboardingDirectorInformationParams.ts
> +    directorIDs?: string;
👍

2025-04-15 08:23 UTC, burczu commented on src/libs/API/parameters/SaveCorpayOnboardingDirectorInformationParams.ts
> +    directorIDs?: string;
fixed

2025-04-15 08:23 UTC, burczu commented on src/libs/API/parameters/SaveCorpayOnboardingDirectorInformationParams.ts
> +    PRDandFSG?: FileObject;
done

2025-04-15 08:23 UTC, madmax330 commented on src/pages/ReimbursementAccount/NonUSD/SignerInfo/HangTight.tsx
> +        // TODO this should send a message to the email provided in the previous step
Ah ok yeah, sounds good

2025-04-15 08:23 UTC, madmax330 commented on src/pages/ReimbursementAccount/NonUSD/SignerInfo/index.tsx
> +        // TODO: the message to the email provided in the previous step should be sent
sounds good 👍🏽

2025-04-15 08:23 UTC, burczu commented on src/pages/ReimbursementAccount/NonUSD/SignerInfo/index.tsx
> +            directorIDs: `${directorKeys.toString()}`,
resolved

2025-04-15 09:08 UTC, madmax330 approved these changes

2025-04-15 09:09 UTC, merged

2025-04-15 09:18 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.