fix: update how we show pending and scanning status
Expensify/App pull request #53112
Opened 2024-11-26 07:41 UTC by nkdengineer

### Explanation of Change

### Fixed Issues

$ https://github.com/Expensify/App/issues/52921
PROPOSAL: https://github.com/Expensify/App/issues/52921#issuecomment-2491797324

### Tests

- [x] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-12-10 03:37 UTC, nkdengineer commented on src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
> +        if (TransactionUtils.isPending(transaction)) {
friendly bump @grgia

2024-12-17 19:52 UTC, shawnborton commented
What's the latest on this one? Seems like we hit a slowdown. Let's keep the momentum going so we can get this merged!

2024-12-18 03:45 UTC, nkdengineer commented on src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
> +        if (TransactionUtils.isPending(transaction)) {
kindly reminder @grgia

2024-12-18 15:20 UTC, grgia commented on src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
> +        if (TransactionUtils.isPending(transaction)) {
usePendingUI is a better description if it includes scanning.

2024-12-18 15:21 UTC, grgia approved these changes, later dismissed
Code LGTM, I like your suggestion to change the name, could you push that? @nkdengineer

2024-12-19 09:47 UTC, nkdengineer commented on src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
> +        if (TransactionUtils.isPending(transaction)) {
thanks @grgia @ntdiary, i updated

2024-12-19 14:21 UTC, shawnborton commented on src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
> +        if (TransactionUtils.isPending(transaction)) {
Hmm if the receipt is just Scanning, it doesn't mean it's pending the same way that a credit card transaction would be pending. So for the scanning case, I don't think we should show that there. 

Also, I thought the idea was to also remove the "Receipt scan in progress" small text from the bottom? cc @Expensify/design for a gut check there!

2024-12-19 16:57 UTC, trjExpensify commented on src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
> +        if (TransactionUtils.isPending(transaction)) {
^^ same, I thought so too!

2024-12-23 03:41 UTC, nkdengineer commented on src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx
> +        if (TransactionUtils.isPending(transaction)) {
I'll update soon

2024-12-23 09:51 UTC, nkdengineer commented
@ntdiary i fixed lint and updated

2024-12-24 15:31 UTC, shawnborton commented on src/components/ReportActionItem/ReportPreview.tsx
> +            return {shouldShow: false, messageIcon: Expensicons.ReceiptScan, messageDescription: translate('iou.receiptScanInProgress')};
Hmm interesting, I feel like we should also get rid of the `Receipt scan in progress` text from the report preview given that you see `(1 scanning)` in the title above. So yeah, let's update it here too.

2024-12-29 16:28 UTC, dannymcclain commented on src/components/ReportActionItem/ReportPreview.tsx
> +            return {shouldShow: false, messageIcon: Expensicons.ReceiptScan, messageDescription: translate('iou.receiptScanInProgress')};
Agree with Shawn. Let's ditch it 🔪

2024-12-30 02:38 UTC, nkdengineer commented
@ntdiary i updated, please check again

2025-01-02 10:25 UTC, grgia reviewed
Let me know when this is ready for a re-review and I'll trigger a final test build

2025-01-07 16:22 UTC, grgia reviewed
Do you have an ETA on addressing comments? thanks!

2025-01-08 14:01 UTC, ntdiary requested changes
@nkdengineer, can you please fill the QA test steps and provide test videos for other platforms? :D

2025-01-10 09:13 UTC, shawnborton commented on src/components/ReportActionItem/ReportPreview.tsx
> -        }
Rather than use the footer for "Receipt scan in progress" - let's just append a ` • Scanning` in the top eye brow after after the word `Receipt`

2025-01-10 14:28 UTC, dannymcclain commented on src/components/ReportActionItem/ReportPreview.tsx
> -        }
Big agree with that suggestion Shawn.

2025-01-14 16:16 UTC, grgia submitted a review, later dismissed
@nkdengineer do you have an update on the review?

2025-01-15 12:58 UTC, ntdiary reviewed
@nkdengineer, dude, still have sompe problems. 😂

https://github.com/user-attachments/assets/e7ee3d7f-291d-4b29-b189-bf5d089780f7

1. `scanning` duplicate.
2. should replace the large `Receipt scanning...` in the middle with `Scanning...`.
3. the third line incorrectly displays `Receipt pending match with card transaction`, maybe need to replace with: 
```js
if (isScanning) {
  return {shouldShow: false};
}
```

<hr />

FYI, `ReportPreview` **renders a report** with only one expense, while the `MoneyRequestPreviewContent` **renders one of expenses** in a report with multiple expenses.

`ReportPreview` has more types of pending messages, which we haven't modified yet:
1. `This booking is pending`
2. `Transaction pending`
3. `Receipt pending match with card transaction`

In `MoneyRequestPreviewContent`, there are only items 2 and 3, and we have already modified them to `Card • Pending`.



cc @shawnborton @grgia

2025-01-15 18:23 UTC, grgia commented
> ReportPreview has more types of pending messages, which we haven't modified yet:
This booking is pending
Transaction pending
Receipt pending match with card transaction
In MoneyRequestPreviewContent, there are only items 2 and 3, and we have already modified them to Card • Pending.

Yeah we definitely should handle the ReportPreview cases @nkdengineer. Thank you!

2025-01-20 08:10 UTC, dubielzyk-expensify commented
> As for that third line that says "Receipt pending match match with card transaction" - I'm pretty sure we shouldn't show that until the receipt has been fully scanned, right? 

Agree 👍

2025-01-20 15:24 UTC, shawnborton commented on src/components/ReportActionItem/ReportPreview.tsx
> +            return {shouldShow: !isScanning, messageIcon: Expensicons.Hourglass, messageDescription: translate('iou.pendingMatchWithCreditCard')};
Can you show me what you mean with an image? I'm not following exactly.

2025-01-20 16:10 UTC, shawnborton commented on src/components/ReportActionItem/ReportPreview.tsx
> +            return {shouldShow: !isScanning, messageIcon: Expensicons.Hourglass, messageDescription: translate('iou.pendingMatchWithCreditCard')};
Ah okay yes, we're on the same page. I agree we want to remove the third line.

2025-01-22 08:45 UTC, ntdiary requested changes
@nkdengineer, I think it would be better to move `hasPendingRTERViolation` out of the `isScanning` condition, because when it is true, `isScanning` might be false. :) This way, we can achieve the following effect:
| status | screenshots |
|--------|--------|
| submit a scanning report  | <img width="400" alt="image" src="https://github.com/user-attachments/assets/6843afe0-db79-4823-98c3-77e9014fa259" /> |
| submit a manual report and then upload receipt  | <img width="400" alt="image" src="https://github.com/user-attachments/assets/c1c6ca3a-fe52-4220-8ab9-c9bc4d25a3be" /> |
| multi expenses with one scanning | <img width="400" alt="image" src="https://github.com/user-attachments/assets/1b7b9dc5-2db2-4b1e-b4da-35d16179c1a8" /> |
| one pending | <img width="400" alt="image" src="https://github.com/user-attachments/assets/bc34fb78-77ec-483d-b1ba-5789a810b624" /> | 
| one pending match | <img width="400" alt="image" src="https://github.com/user-attachments/assets/f7f79778-fda5-4f17-9439-895baf24d314" /> |

2025-01-27 17:41 UTC, ntdiary approved these changes
I've uploaded many test screenshots in the [check list](https://github.com/Expensify/App/pull/53112#issuecomment-2577398471), will approve it for now. And once the [translation above](https://github.com/Expensify/App/pull/53112#issuecomment-2615702726) is confirmed, I think it's fine to :shipit: .
BTW, I noticed that on Android platform, the `Cash • Pending match • Review required` wraps to the next line, and I think that's normal behavior (case 9, or could be `Card • Pending match • Review required`). :D

2025-01-30 11:35 UTC, grgia commented
Bump on conflicts @nkdengineer. Let's not hold on the translations, they are easy to update

2025-02-06 17:44 UTC, grgia approved these changes, later dismissed
Code changes LGTM

2025-02-06 17:45 UTC, grgia commented
@shawnborton @dannymcclain do you wanna do a final review?

2025-02-06 18:29 UTC, shawnborton commented
Nice, gonna run a test build!

2025-02-06 23:26 UTC, shawnborton commented
Feeling pretty good to me, let's get this into final review?

2025-02-14 15:21 UTC, grgia approved these changes

2025-02-14 15:21 UTC, merged