[HOLD 9/24] Updates NewDot homepage to reflect N6 campaign
Expensify/App pull request #5318
Opened 2021-09-17 12:22 UTC by Gonals

cc @shawnborton 

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/176436

### Tests
1. Open newdot. See the new image.
2. Refresh a few times. Check that the image randomly rotates between 4 colors.

### QA Steps
1. Open newdot. See the new image.
2. Refresh a few times. Check that the image randomly rotates between 4 colors.

### Tested On

- [X] Web
- [ ] Mobile Web
- [X] Desktop
- [X] iOS
- [X] Android

### Screenshots

#### Web
<img width="1617" alt="Screen Shot 2021-09-17 at 12 16 52 PM" src="https://user-images.githubusercontent.com/19366280/133781728-0dffc221-22d5-4c13-9190-42b6cebe9082.png">

#### Desktop
<img width="1388" alt="Screen Shot 2021-09-17 at 12 22 12 PM" src="https://user-images.githubusercontent.com/19366280/133781750-493925fc-b1e3-4b72-98a8-851940b2b53a.png">

#### iOS
Not displayed on mobiles

#### Android
Not displayed on mobiles

2021-09-17 14:36 UTC, HorusGoul requested changes
These backgrounds look great! 

Regarding the code: 

- We should add an `alt` to these images for accessibility.

- And we could optimize the SVGs using [SVGOMG](https://jakearchibald.github.io/svgomg/) or a similar tool to improve load times.

Let me know what you think.

2021-09-20 14:51 UTC, Gonals commented
> These backgrounds look great!
> 
> Regarding the code:
> 
> * We should add an `alt` to these images for accessibility.
> * And we could optimize the SVGs using [SVGOMG](https://jakearchibald.github.io/svgomg/) or a similar tool to improve load times.
> 
> Let me know what you think.

Hey! 
Looking around the code, it doesn't look like we consistently add `alt`. Since this image isn't really relevant for usage, I don't think we need one.

As for the load time optimizer, I think it could be a good idea to discuss it somewhere on Slack and see if this is something we want to use across the app. I think it is a bit out of scope for this PR, but it could certainly be interesting as an app-wide initiative.

2021-09-20 14:56 UTC, Gonals commented
Comments answered!

2021-09-20 16:24 UTC, shawnborton commented
Can you share some more screenshots at various screen widths? It also looks like the text might not be vertically centered as well.

2021-09-21 08:26 UTC, Gonals commented
> Can you share some more screenshots at various screen widths? It also looks like the text might not be vertically centered as well.

@shawnborton  It may very well be the case. I've been having trouble centering it since the image's proportions don't really fit the screen's. Would it be possible to simply get the text with a clear background? That way I can easily center it and I'll just rotate between the images and background colors.

2021-09-21 08:30 UTC, Gonals commented
A few examples:
<img width="1033" alt="Screen Shot 2021-09-21 at 10 28 53 AM" src="https://user-images.githubusercontent.com/19366280/134138336-3eea8044-bd7a-43ee-b810-ced9a8f28294.png">
<img width="944" alt="Screen Shot 2021-09-21 at 10 29 26 AM" src="https://user-images.githubusercontent.com/19366280/134138368-ee66f66e-25fb-436b-a52c-73554577cc03.png">
<img width="949" alt="Screen Shot 2021-09-21 at 10 29 40 AM" src="https://user-images.githubusercontent.com/19366280/134138385-976fb265-fd99-4dfb-888e-ade136cb3aba.png">

2021-09-21 08:44 UTC, shawnborton commented
Well the thing with centering it is that then the image itself won't scale proportionally. Were you able to get it working with `object-fit: cover` or as a background image using `background-size: cover`?

2021-09-21 09:35 UTC, Gonals commented
> Well the thing with centering it is that then the image itself won't scale proportionally. Were you able to get it working with `object-fit: cover` or as a background image using `background-size: cover`?

It doesn't look like we can set `.svg` as images/background images. They are sort of their own components 🤷

2021-09-21 10:51 UTC, Gonals commented
> > Well the thing with centering it is that then the image itself won't scale proportionally. Were you able to get it working with `object-fit: cover` or as a background image using `background-size: cover`?
> 
> It doesn't look like we can set `.svg` as images/background images. They are sort of their own components in react-native 🤷

Nevermind! I was wrong. They can't be images, but they can be background-images! Changes incoming!

2021-09-21 11:29 UTC, shawnborton commented
Great news!

2021-09-21 15:53 UTC, Gonals commented
Sooo... Not looking great. Works well on web, but on desktop:
Without cover:
<img width="873" alt="Screen Shot 2021-09-21 at 4 52 27 PM" src="https://user-images.githubusercontent.com/19366280/134204395-0af6ba1b-e150-4206-be31-39e3b5a2bb85.png">

With cover:
<img width="1208" alt="Screen Shot 2021-09-21 at 5 53 06 PM" src="https://user-images.githubusercontent.com/19366280/134204499-77bdb8a3-8952-4ac7-a38e-e0cde5d7f3a5.png">

2021-09-21 16:06 UTC, Gonals commented
Yep, that was my next step. It looks good:
<img width="1207" alt="Screen Shot 2021-09-21 at 5 55 25 PM" src="https://user-images.githubusercontent.com/19366280/134206566-a20ff2db-40a9-4076-a2a8-eea1e6855803.png">
<img width="1619" alt="Screen Shot 2021-09-21 at 5 56 44 PM" src="https://user-images.githubusercontent.com/19366280/134206596-eb155ab3-2755-4f4f-93b5-8b93ed325638.png">

2021-09-21 16:08 UTC, Gonals commented
Some resizes:
<img width="1057" alt="Screen Shot 2021-09-21 at 6 08 00 PM" src="https://user-images.githubusercontent.com/19366280/134206916-234beb36-89d6-4c3e-93a7-68a4d91d61cc.png">
![Uploading Screen Shot 2021-09-21 at 6.08.10 PM.png…]()

2021-09-21 16:11 UTC, shawnborton commented
Sweet, I say we go with that then - I think it will end up looking good in most situations.

2021-09-21 16:18 UTC, Gonals commented
Coolio! This should be ready for code-review, then!

2021-09-22 07:59 UTC, MonilBhavsar approved these changes, later dismissed
Tested 😄 🔥  and looks good to me

2021-09-22 17:17 UTC, yuwenmemon approved these changes, later dismissed
NIce - I'm presuming we don't need to reinvent the carousel here, right?

2021-09-23 08:10 UTC, shawnborton commented
Meaning - does this PR just show a random image on load, instead of rotating through the images? 

I think it's okay if we get this out the door as it is, and then follow up to make it rotate through the images to mirror OldDot. Thoughts on that approach?

2021-09-24 06:10 UTC, kevinksullivan commented
updating date for Monday per [this conversation](https://expensify.slack.com/archives/C020EPP9B9A/p1632446258403800)

2021-09-27 11:29 UTC, HorusGoul approved these changes, later dismissed

2021-10-04 05:05 UTC, MonilBhavsar commented
@Gonals @kevinksullivan should this still be on hold 🤔

2021-10-04 09:19 UTC, Gonals commented
> @Gonals @kevinksullivan should this still be on hold 🤔

Yep. We'll deploy it when the free plan actually goes live

2021-10-04 10:41 UTC, MonilBhavsar commented
Alright 👍 I thought this was supposed to go out during soft launch

2021-10-15 18:32 UTC, MitchExpensify commented
Merge and CP please!

2021-10-15 19:12 UTC, luacmartins approved these changes
LGTM and tested well!

2021-10-15 19:45 UTC, merged

2021-10-16 02:44 UTC, isagoico commented
Found this issue that's related to this PR - https://github.com/Expensify/App/issues/5912

2021-10-21 18:44 UTC, ogumen commented
The text displayed in the right side of the screen is not conveyed to screen reader users. It is implemented as a background image of text which is a failure of WCAG success criteria 1.4.5.

2021-10-23 01:34 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1374292176) to staging by @luacmartins in version: 1.1.8-10 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅