Enabling Receipt drag and drop inside the confirmation step
Expensify/App pull request #53849
Opened 2024-12-10 12:57 UTC by abzokhattab

### Explanation of Change

### Fixed Issues

$ https://github.com/Expensify/App/issues/53089 
PROPOSAL: https://github.com/Expensify/App/issues/53089#issuecomment-2499098938
  

### Tests

1. Create a manual expense.
2. On the expense confirmation page, drag and drop a receipt in either image or PDF format.
3. Verify that the receipt is seamlessly attached to the expense confirmation page.

### Offline tests

Same as tests

### QA Steps

Same as tests

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android: Native
    - [X] Android: mWeb Chrome
    - [X] iOS: Native
    - [X] iOS: mWeb Safari
    - [X] MacOS: Chrome / Safari
    - [X] MacOS: Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [X] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [X] I verified that all the inputs inside a form are aligned with each other.
    - [X] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

Not applicable

</details>

<details>
<summary>Android: mWeb Chrome</summary>

Not applicable

</details>

<details>
<summary>iOS: Native</summary>

Not applicable

</details>

<details>
<summary>iOS: mWeb Safari</summary>

Not applicable

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/d2f66fac-1402-489c-93b7-6de188bc69da

https://github.com/user-attachments/assets/13175d72-4fa7-4ee5-a0e5-d29e49bf6208

</details>

<details>
<summary> [...]

2024-12-10 15:04 UTC, dannymcclain commented
Agree with Shawn.

2024-12-12 14:30 UTC, dannymcclain commented
@shawnborton @dubielzyk-expensify do you think we should be using our light button text color here instead of the dark?

![CleanShot 2024-12-12 at 08 27 50@2x](https://github.com/user-attachments/assets/2bc2c74f-5953-46fd-bc21-4809228e891d)

Here's what the "import spreadsheet" version looks like:
![CleanShot 2024-12-12 at 08 29 04@2x](https://github.com/user-attachments/assets/d6087a3c-13fe-4d1c-ac2e-a1d07381ac7b)

And actually—can we make sure the green overlay is the same between these two? I can't tell if they're different, but let's make sure we're matching the CSV import one since we just built that recently. Yeah?

2024-12-12 14:31 UTC, dannymcclain commented
FORGET EVERYTHING I SAID! It's just a light mode vs. dark mode thing 🤦‍♂️

Light mode CSV import:
![CleanShot 2024-12-12 at 08 30 58@2x](https://github.com/user-attachments/assets/88a2d274-fdb7-4741-8aa7-839b8376be7a)

2024-12-12 14:31 UTC, shawnborton commented
I can get down with that, let's make sure everything is aligned. I think the "Let it go" UI shown above is the same thing found in the Scan receipt on desktop flow, so let's update that too. But yeah, I like using lighter text as well as the green you pointed out for import spreadsheet.

2025-01-13 14:44 UTC, shawnborton commented
Good catch on that, let's definitely fix that!

2025-01-14 06:51 UTC, shawnborton commented
Any reason why the content (illustration + text) isn't vertically centered? It looks like it's shifted down quite a bit:
![CleanShot 2025-01-14 at 07 51 27@2x](https://github.com/user-attachments/assets/97ffa2c2-a1c5-4b42-b30c-70bd00b9a5e9)

2025-01-14 14:54 UTC, shawnborton commented on src/components/ReceiptEmptyState.tsx
> +            <View onLayout={({nativeEvent}) => setReceiptImageTopPosition(PixelRatio.roundToNearestPixel((nativeEvent.layout as DOMRect).top))}>
Nice, that seems much simpler right? I say we do it that way instead!

2025-01-20 12:58 UTC, Ollyws approved these changes
LGTM, aside from the lint check failing.

2025-01-27 08:25 UTC, shawnborton commented
I think @marcaaron is OOO, so I'm gonna hit @Expensify/pullerbear to find a new final reviewer here.

2025-01-27 08:26 UTC, shawnborton commented
Hmm @Ollyws how do you normally get a review from an Expensify engineer on these things? Looks like we have some conflicts too.

2025-01-27 08:29 UTC, Ollyws approved these changes
Let's see if approving again adds an engineer.

2025-01-27 08:32 UTC, shawnborton commented
Hmm it keeps adding Marc. I will see if anyone is up for taking it over.

2025-01-27 08:35 UTC, shawnborton commented
In the meantime, @abzokhattab can you fix the conflicts? Thanks!

2025-01-27 08:42 UTC, shawnborton commented
Thanks!

2025-01-27 17:39 UTC, luacmartins submitted a review, later dismissed
@abzokhattab we have conflicts again. Can you please resolve them? Code LGTM otherwise

2025-01-27 17:39 UTC, luacmartins commented on src/components/ReceiptEmptyState.tsx
> +            // With the image size > 24MB, we use manipulateAsync to resize the image.
NAB but this comment can get outdated if we change the const value
```suggestion
            // With the image size > CONST.API_ATTACHMENT_VALIDATIONS.MAX_SIZE, we use manipulateAsync to resize the image.
```

2025-01-28 03:58 UTC, luacmartins commented
@abzokhattab we still have a conflict in the submodule. Can you please run `npm update submodule`? We shouldn't push the submodule changes here

2025-01-28 15:42 UTC, luacmartins requested changes

2025-01-28 15:42 UTC, luacmartins commented on Mobile-Expensify
We should remove these changes

2025-01-28 16:15 UTC, luacmartins commented
Thanks!

2025-01-28 16:24 UTC, luacmartins approved these changes
LGTM

2025-01-28 16:24 UTC, merged

2025-01-28 16:33 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2025-01-29 10:27 UTC, shawnborton commented
Looks like this caused a regression - can we please fix ASAP? Thanks! https://github.com/Expensify/App/issues/55931

2025-01-29 14:13 UTC, luacmartins commented
The PR was reverted, let's work on v2 and fix the issues below:

- https://github.com/Expensify/App/issues/55933
- https://github.com/Expensify/App/issues/55934
- https://github.com/Expensify/App/issues/55935
- https://github.com/Expensify/App/issues/55937
- https://github.com/Expensify/App/issues/55938
- https://github.com/Expensify/App/issues/55931