feat: Provide education/confirmation before creating workspaces in New Workspace flows
Expensify/App pull request #53845
Opened 2024-12-10 12:24 UTC by Krishna2323

### Explanation of Change
- Problem: When users attempting to submit expenses are inadvertently led to create workspaces, it causes confusion about how to submit an expense to their boss, leading to frustration and a poor user experience.
- This PR adds a workspace confirmation page which will be shown before a workspace is created. Workspace confirmation page will have avatar picker, name input and currency selector, users can now choose custom avatar, workspace name and currency before creating a workspace.
- This PR also fixes regressions from the [previous PR](https://github.com/Expensify/App/pull/52164). Issues: 
$ https://github.com/Expensify/App/issues/53765
$ https://github.com/Expensify/App/issues/53766
$ https://github.com/Expensify/App/issues/53768
$ https://github.com/Expensify/App/issues/53771
$ https://github.com/Expensify/App/issues/53793

### Fixed Issues
$ https://github.com/Expensify/App/issues/51504
PROPOSAL: https://github.com/Expensify/App/issues/51504#issuecomment-2445925882

### Tests
1. Go to workspace lists page > Click on `Create workspace` 
2. Verify RHP is opened with avatar selector, name input and currency selector.
3. Select any avatar > Enter custom name > Select a different currency
4. Click confirm 
5. Verify workspace is created with the selected avatar, name and currency.
6. Repeat Step 1 to 4 with default avatar
7. Verify workspace is created with the default avatar, name and currency.
8. Repeat Step 1 to 4 with default currency 
9. Verify workspace is created with the selected avatar, name and default currency.
10. Click on `Create workspace` > Enter any custom name
11. Verify default avatar uses the first character of the name.
12. Log out and login with a new account > Complete onboarding
13. Open FAB > Select `New workspace` > Verify RHP is opened with avatar selector, name input and currency selector.
14. Select any avatar > Enter custom name > Select a different currency
15. Click confirm 
16. Verify workspace is created with the selected avatar, name and currency.
17. Delete the single workspace from workspace list page 
18. On workspace list page click `New Workspace` button 
19. Verify RHP is opened with avatar selector, name input and currency selector.
20. Select any avatar > Enter custom name > Select a different currency
21. Click confirm 
22. Verify workspace is created with the selected avatar, name and currency.

- [x] Verify that no errors appear in the JS console

### Offline tests
1. Go to workspace lists page > Click on `Create workspace` 
2. Verify RHP is opened with avatar selector, name input and currency selector.
3. Select any avatar > Enter custom name > Select a different currency
4. Click confirm 
5. Verify workspace is created with the selected avatar, name and currency.
6. Repeat Step 1 to 4 with default avatar
7. Verify workspace is created with the default avatar, name and currency.
8. Repeat Step 1 to 4 with default currency 
9. Verify workspace is created with the selected avatar, name and default currency.
10. Click on `Create workspace` > Enter any custom name
11. Verify default avatar uses the first character of the name.
12. Log out and login with a new account > Complete onboarding
13. Open FAB > Select `New workspace` > Verify RHP is opened with avatar selector, name input and currency selector.
14. Select any avatar > Enter custom name > Select a different currency
15. Click confirm 
16. Verify workspace is created with the selected avatar, name and currency.
17. Delete the single workspace from workspace list page 
18. On workspace list page click `New Workspace` button 
19. Verify RHP is opened with avatar selector, name input and currency selector.
20. Select any avatar > Enter custom name > Select a different currency
21. Click confirm 
22. Verify workspace is created with the selected avatar, name and currency.

### QA Steps
1. Go to workspace lists page > Click on `Create workspace` 
2. Verify RHP is opened with avatar selector, name input and currency selector.
3. Select any avatar > Enter custom name > Select a different currency
4. Click confirm 
5. Verify workspace is created with the selected avatar, name and currency.
6. Repeat Step 1 to 4 with default avatar
7. Verify workspace is created with the default avatar, name and currency.
8. Repeat Step 1 to 4 with default currency 
9. Verify workspace is created with the selected avatar, name and default currency.
10. Click on `Create workspace` > Enter any custom name
11. Verify default avatar uses the first character of the name.
12. Log out and login with a new account > Complete onboarding
13. Open FAB > Select `New workspace` > Verify RHP is opened with avatar selector, name input and currency selector.
14. Select any avatar > Enter custom name > Select a different currency
15. Click confirm 
16. Verify workspace is created with the selected avatar, name and currency.
17. Delete the single workspace from workspace list page 
18. On workspace list page click `New Workspace` button 
19. Verify RHP is opened with avatar selector, name input and currency selector.
20. Select any avatar > Enter custom name > Select a different currency
21. Click confirm 
22. Verify workspace is created with the selected avatar, name and currency.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack mes [...]

2024-12-18 17:42 UTC, danielrvidal commented
I can also reproduce the issue. You can see it here: 
https://github.com/user-attachments/assets/9f2267d5-72c8-4c98-899e-189183126c0b

2024-12-24 15:25 UTC, shawnborton commented
I can kick it off 🚀

2024-12-24 17:38 UTC, allgandalf requested changes
I will do a review again tomorrow morning, I guess there isn't much left to change, looks good overall

2025-01-02 16:21 UTC, shawnborton commented
Let's try to keep the momentum up - what else do we need to do to get this one merged? We're so close!

2025-01-08 09:54 UTC, shawnborton commented
How is this one going? We really want to get this one merged ASAP. What else do we need to do to finish this up?

2025-01-08 17:17 UTC, danielrvidal commented
Let us know if you need anything from us @allgandalf, it would be a good one to get out and done.

2025-01-09 23:44 UTC, CyberAndrii commented on src/libs/fileDownload/FileUtils.ts
> +};
```suggestion
const createFile = (file: File): FileObject => {
    if (getPlatform() === CONST.PLATFORM.ANDROID || getPlatform() === CONST.PLATFORM.IOS) {
        return {
            uri: file.uri,
            name: file.name,
            type: file.type,
        };
    }
    return new File([file], file.name, {
        type: file.type,
        lastModified: file.lastModified,
    });
};
```

Shouldn't it be like this? Pretty sure it won't work on desktop. I'm also confused why we need this function. Is there the same issue in other places where we use `AvatarWithImagePicker`?

> It was causing issues on native app because in native the file object requires different properties.

I see in some places that we set the `uri` property (which is required) like this, perhaps we need to do something similar

https://github.com/Expensify/App/blob/fcd16e4f45f1fb119ced7786114a33363f757849/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L796

2025-01-14 13:31 UTC, cristipaval commented
> this branch is having conflicts , please fix those, also lets keep this PR a top priority @Krishna2323

yes @Krishna2323, this PR is holding the progress on [this issue](https://github.com/Expensify/App/issues/48305) which has super high priority on our roadmap.

2025-01-17 11:59 UTC, cristipaval commented
I just tested this locally, and it doesn't reproduce for me either. I also think the bug is not related to this PR, and given that it is already being investigated, I don't think we should duplicate efforts here.

2025-01-17 12:00 UTC, cristipaval commented
Thanks @allgandalf for the rigorous testing and @Krishna2323 for investigating 🙏

2025-01-17 12:15 UTC, allgandalf approved these changes

2025-01-20 13:42 UTC, cristipaval approved these changes
I see @grgia is still ooo and we really need this one to get the travel issue unblocked as we're approaching the external commit. I'll merge it to get it in today's deploy.

2025-01-20 14:47 UTC, shawnborton commented
Awesome, thanks @cristipaval - super excited to finally get this one into the product!

2025-01-20 19:46 UTC, merged

2025-01-20 19:56 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2025-01-21 17:20 UTC, grgia commented on src/languages/en.ts
> +            subtitle: 'Create a workspace to track receipts, reimburse expenses, send invoices, and more — all at the speed of chat.',
@shubham1206agra can you make sure you include this in the above PR

2025-04-30 09:37 UTC, jayeshmangwani commented on src/pages/workspace/WorkspaceConfirmationPage.tsx
> +    const policyOwnerEmail = currentUrl ? new URL(currentUrl).searchParams.get('ownerEmail') ?? '' : '';
Coming from this issue https://github.com/Expensify/App/issues/59776, we're using `currentUrl` to retrieve the `policyOwnerEmail`, but on native platforms, `currentUrl` is empty—resulting in a missing email value.

To resolve this, we can add fallback value of `currentUserLogin` to `generateDefaultWorkspaceName`. More context can be found here: https://github.com/Expensify/App/issues/59776#issuecomment-2785231787