New product training tooltips
Expensify/App pull request #54064
Opened 2024-12-12 20:18 UTC by ishpaul777

### Explanation of Change

### Fixed Issues

$ https://github.com/Expensify/App/issues/53087
PROPOSAL:

### Tests

- [x] Verify that no errors appear in the JS console
- Sign in with new account, complete onboarding flow.
- On small screen verify "Get started!" tooltip show on conceirge chat. Dismiss it clicking anywhere on screen.
- On large screen, verify tooltip on FAB  button appears.  Dismiss it clicking anywhere on screen.
- Create a workspace if not already, veriffy when there's a workspace chat in LHN verify tooltip on workspace chat shows. (on both large and small screen)  Dismiss it clicking anywhere on screen.
- click on search bottom tab, verify tooltip on filter button shows up. Dismiss it clicking anywhere on screen.
- Verify a tooltip on inbox icon in  bottom tab shows up. Dismiss it clicking anywhere on screen.

### Offline tests

### QA Steps

Same as tests

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://githu [...]

2024-12-12 22:07 UTC, rayane-d requested changes

2024-12-12 22:29 UTC, rayane-d requested changes

2024-12-13 14:02 UTC, shawnborton commented
The video looks pretty good to me, let's fire up a test build though for easier testing as well.

2024-12-13 16:25 UTC, shawnborton commented
I think this tooltip has an extra space before "create expenses":
![CleanShot 2024-12-13 at 11 24 50@2x](https://github.com/user-attachments/assets/edf6b2bc-dece-453c-8836-fe3b34906188)

2024-12-13 16:26 UTC, shawnborton commented
For the tooltips, I wonder if we want slightly more space between the icon and text? cc @Expensify/design for a gut check there. It feels a little tight right now.

2024-12-13 16:34 UTC, dannymcclain commented
>For the tooltips, I wonder if we want slightly more space between the icon and text?

I agree, it does feel a little tight. Maybe even just 4px more would do it? (Or 8px?)

I also kinda feel like the arrow/caret/pointy part of the tooltip is a little small. Is that just me though?

2024-12-13 16:40 UTC, shawnborton commented
I could totally see that too.

2024-12-13 17:34 UTC, rayane-d requested changes

2024-12-13 17:37 UTC, dannymcclain commented
>Do we need to make it 8px?

At least 8px, but maybe even 12px. We can start with 8 though unless Shawn has strong feelings?

2024-12-13 17:40 UTC, shawnborton commented
I say let's see 8px and go from there?

2024-12-13 17:54 UTC, shawnborton commented
I think the 8px gap works for me, let's see what Danny and Jon think though!

2024-12-13 18:04 UTC, rayane-d requested changes

2024-12-13 18:05 UTC, dannymcclain commented
Yeah I think 8 works for me too.

2024-12-13 18:09 UTC, dannymcclain commented
Actually, sorry, I just checked the Figma and Jon has it at 12px 🙈. I say we update it to match the design file.

Also I think the lightbulb icon might be using `green-500` but in Figma it's `green-400`.

2024-12-13 18:10 UTC, shawnborton commented
Nice, good catches - let's go with what Jon has in Figma!

2024-12-13 18:41 UTC, shawnborton commented
Feels good to me 👍

2024-12-13 18:54 UTC, rayane-d approved these changes
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

2024-12-13 19:09 UTC, dannymcclain commented
Sorry to be so nitpicky 🙈, but can we check the padding values and the border radius for the tooltip?

In Figma, the tooltips have 12px vertical padding and 16px horizontal padding, and a border radius of 8px.

2024-12-13 19:25 UTC, rayane-d reviewed
@ishpaul777 Did you confirm the translations on Slack?

2024-12-13 20:20 UTC, puneetlath approved these changes, later dismissed

2024-12-13 21:41 UTC, puneetlath approved these changes

2024-12-13 21:41 UTC, merged

2024-12-13 21:51 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2024-12-13 23:17 UTC, titaniumdev80 commented
@puneetlath Sorry, could you let me know where I can find the instructions to generate certificates? Thanks

2024-12-13 23:29 UTC, titaniumdev80 commented
@puneetlath No worries. I've just found it out. Thanks

2024-12-18 16:24 UTC, puneetlath commented
FYI we had to revert this because it created a HybridApp crash for a yet-unknown reason: https://github.com/Expensify/App/pull/54260

2024-12-19 23:16 UTC, kavimuru commented
Failing with original bug #53087 in all the platforms
https://platform.applause.com/services/links/v1/external/46b2e50f5196600800df127a5e890af9cc2a75c5122c2c4608cfdd9b77793ef9
https://platform.applause.com/services/links/v1/external/5df9372f5bfe31f197c0ba58373c1ddd791fe93d07daa5580695964b37aef059
https://platform.applause.com/services/links/v1/external/63795e9f82011fde4aa3e0e7031d287db841688dbf1e92737842af3ef481a7dc

2025-02-22 02:09 UTC, ahmedGaber93 commented on src/components/Search/SearchPageHeader.tsx
> +                            vertical: CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.BOTTOM,
Coming from here https://github.com/Expensify/App/issues/57070, because of the tooltip overlaps the expensify logo,  we decide to change the vertical alignment to `TOP`.

2025-04-04 07:58 UTC, c3024 commented on src/pages/Search/SearchTypeMenu.tsx
> +        shouldShowSavedSearchesMenuItemTitle,
We need to check if the screen is focused too here when showing the tooltip. More details here. #58138.

2025-07-07 11:36 UTC, shubham1206agra commented on src/components/ProductTrainingContext/index.tsx
> +                <Text style={[styles.productTrainingTooltipText, styles.textWrap, styles.mw100]}>
@ishpaul777 Can you tell me why did you use additional styles here? Such as `styles.textWrap` and `styles.mw100`.

2025-07-07 14:26 UTC, ishpaul777 commented on src/components/ProductTrainingContext/index.tsx
> +                <Text style={[styles.productTrainingTooltipText, styles.textWrap, styles.mw100]}>
cant remember on top of my head, in latest code i see these are removed now