[HOLD Web-Expensify 31985] CreatePolicyRoom Client-Side API
Expensify/App pull request #5416
Opened 2021-09-22 16:36 UTC by jasperhuangg

### Details
Add an API function and Report Action for the new CreatePolicyRoom API command.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/176849

### Tests

### QA Steps

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-09-23 00:33 UTC, thienlnam requested changes

2021-09-23 00:33 UTC, thienlnam commented on src/libs/actions/Report.js
> +            }
Is a missing response ever going to occur? I think we can just make this and remove the !response

if (response && response.jsonCode !== 200)

2021-09-23 00:33 UTC, thienlnam commented on src/libs/actions/Report.js
> +                console.error('Unable to grab policy room after creation');
This needs a return

2021-11-11 16:32 UTC, Julesssss commented on src/libs/API.js
> +        parameters, commandName);
NAB: Any reason for the newline here?

2021-11-11 19:07 UTC, jasperhuangg commented on src/libs/API.js
> +        parameters, commandName);
nopee, removed!

2021-11-11 20:11 UTC, thienlnam requested changes

2021-11-11 20:11 UTC, thienlnam commented on src/libs/actions/Report.js
> +        console.debug(`[Report] Failed to populate IOU Collection: ${error.message}`);
Forgot to update these back 😅

2021-11-11 20:11 UTC, thienlnam commented on src/libs/actions/Report.js
> -            handleInaccessibleReport();
Are there any other expected failures than err.message === CONST.REPORT.ERROR.INACCESSIBLE_REPORT?

2021-11-11 20:11 UTC, thienlnam commented on src/libs/actions/Report.js
> +            Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT}${reportID}`, {maxSequenceNumber});
What are these changes for?

2021-11-11 20:11 UTC, thienlnam commented on src/libs/actions/Report.js
> +            }
Same here, curious what these changes are for

2021-11-11 20:22 UTC, closed without merging