Markdown in task titles
Expensify/App pull request #54165
Opened 2024-12-15 10:39 UTC by Krishna2323

### Explanation of Change

### Fixed Issues
$ https://github.com/Expensify/App/issues/53175
PROPOSAL: https://github.com/Expensify/App/issues/53175#issuecomment-2524888381

### Tests
1. Open a report > Click on "+" icon in composer > Select "Assign task"
2. Paste the text below in title and description field:
```
This is a sentence without any markdown styling.
Simple sentence with a [link](https://github.com/Expensify/App/issues) , `inline code` and ~line-through~ text.
# heading with a [link](https://github.com/Expensify/App/issues) and `inline code`.
> Blockquote with a [link](https://github.com/Expensify/App/issues) and `inline code`.
A simple text with a ~line-through~ and _italic_ word.
# A heading with a line-through and italic word.
*This sentence is bolded using "**"*
> We should also check emojis 😅
# And emojis in a heading 😅
> Whats missing🤔? Please test the missing ones🥶.
```
3. Verify the markdown is rendered correctly in the title input field > Click "Next"
4. Verify the the markdown is rendered correctly in the title field and is rendered same as the description field
5. Click "Confirm Task"
6. Verify the markdown is correctly rendered for the task preview
7. Open task details page 
8. Verify everything is rendered correctly and text after # (h1) & between ** (strong) is not bolded.

- [x] Verify that no errors appear in the JS console

### Offline tests
1. Open a report > Click on "+" icon in composer > Select "Assign task"
2. Paste the text below in title and description field:
```
This is a sentence without any markdown styling.
Simple sentence with a [link](https://github.com/Expensify/App/issues) , `inline code` and ~line-through~ text.
# heading with a [link](https://github.com/Expensify/App/issues) and `inline code`.
> Blockquote with a [link](https://github.com/Expensify/App/issues) and `inline code`.
A simple text with a ~line-through~ and _italic_ word.
# A heading with a line-through and italic word.
*This sentence is bolded using "**"*
> We should also check emojis 😅
# And emojis in a heading 😅
> Whats missing🤔? Please test the missing ones🥶.
```
3. Verify the markdown is rendered correctly in the title input field > Click "Next"
4. Verify the the markdown is rendered correctly in the title field and is rendered same as the description field
5. Click "Confirm Task"
6. Verify the markdown is correctly rendered for the task preview
7. Open task details page 
8. Verify everything is rendered correctly and text after # (h1) & between ** (strong) is not bolded.

### QA Steps
1. Open a report > Click on "+" icon in composer > Select "Assign task"
2. Paste the text below in title and description field:
```
This is a sentence without any markdown styling.
Simple sentence with a [link](https://github.com/Expensify/App/issues) , `inline code` and ~line-through~ text.
# heading with a [link](https://github.com/Expensify/App/issues) and `inline code`.
> Blockquote with a [link](https://github.com/Expensify/App/issues) and `inline code`.
A simple text with a ~line-through~ and _italic_ word.
# A heading with a line-through and italic word.
*This sentence is bolded using "**"*
> We should also check emojis 😅
# And emojis in a heading 😅
> Whats missing🤔? Please test the missing ones🥶.
```
3. Verify the markdown is rendered correctly in the title input field > Click "Next"
4. Verify the the markdown is rendered correctly in the title field and is rendered same as the description field
5. Click "Confirm Task"
6. Verify the markdown is correctly rendered for the task preview
7. Open task details page 
8. Verify everything is rendered correctly and text after # (h1) & between ** (strong) is not bolded.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I v [...]

2025-03-03 03:25 UTC, mananjadhav commented
I will review this today.

2025-03-05 02:02 UTC, mananjadhav commented
Meanwhile @Krishna2323 can you specifically check these issues from the previous PR to ensure these are working fine in the new PR.

- https://github.com/Expensify/App/pull/55967#issuecomment-2640760692 font size
- https://github.com/Expensify/App/pull/55967#issuecomment-2640709784 keyboard shortcuts and multiple save attempts

2025-03-05 02:13 UTC, mananjadhav reviewed
Left some comments and also asked to test some issues from previous PR. Still need to review some renderer and styling changes.

2025-03-05 02:13 UTC, mananjadhav commented on src/libs/actions/Task.ts
> +        htmlTitle: reportName,
Does backend already support `htmlTitle`? @roryabraham Can you confirm? and is this tested on staging as well as prod APIs?

2025-03-05 02:13 UTC, mananjadhav commented on src/libs/actions/Task.ts
> +        htmlTitle: reportName,
why not send `parsedTitle`?

2025-03-05 02:13 UTC, mananjadhav commented on src/libs/actions/Task.ts
> +    // const reportName = (title ?? report?.reportName)?.trim();
Can we get rid of this comment?

2025-03-05 02:13 UTC, mananjadhav commented on src/libs/actions/Task.ts
>      // Sometimes title or description is undefined, so we need to check for that, and we provide it to multiple functions
Let's update this comment to reflect using getParsedcomment?

2025-03-05 02:13 UTC, mananjadhav commented on src/libs/actions/Task.ts
> +    const reportName = title ? ReportUtils.getParsedComment(title) : report?.reportName ?? '';
Is it not throwing a lint error to use named import?

2025-03-05 02:13 UTC, mananjadhav commented on src/libs/ReportUtils.ts
> +                html: getParsedComment(changelog),
Any reason this check is not needed anymore?

2025-03-05 02:13 UTC, mananjadhav commented on src/components/HTMLEngineProvider/HTMLRenderers/TaskTitleRendered.tsx
> +import React from 'react';
Can we rename the file as `TaskTitleRenderer`?

2025-03-05 05:05 UTC, mananjadhav commented
If I use the keyboard shortcuts to make the content bold/italic and save them the previous PR had issues where it rendered the HTML tags.

Can you check the following test steps?
 
> 1. Create a task with `Title` say in italic, save the task.
> 2. Add a description, use a keyboard shortcut to make it bold/italic.
> 3. Save the description, you'll end up seeing the title with tags `<em>Title</em>`.
> 4. You keep editing the description, you'll end up having encoded title.
> 5. Add the title with heading `# Title` will cause an alignment issue with the checkbox.

2025-03-05 05:28 UTC, roryabraham requested changes

2025-03-05 05:28 UTC, roryabraham commented on src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.tsx
> +    const isChildOfTaskTitle = HTMLEngineUtils.isChildOfTaskTitle(tnode);
hmmm did you know that in React Native, the only styles that actually cascade like css are text styles? So you might be able to just alter the text style higher up in the component tree and have it cascade down.

2025-03-05 05:28 UTC, roryabraham commented on src/libs/ReportUtils.ts
> +    if (isTaskReport(report)) {
please add unit tests to cover this change

2025-03-05 05:28 UTC, roryabraham commented on src/libs/TaskUtils.ts
>  function getTaskTitleFromReport(taskReport: OnyxEntry<Report>, fallbackTitle = ''): string {
can we also add unit tests for this change?

2025-03-05 05:28 UTC, roryabraham commented on src/libs/actions/Task.ts
> +        // title: optimisticTaskReport.reportName,
please do not include commented-out code

2025-03-05 05:28 UTC, roryabraham commented on src/pages/tasks/NewTaskDetailsPage.tsx
> +                        value={Parser.htmlToMarkdown(Parser.replace(taskTitle))}
NAB but maybe we should memoize this so we don't run the parser regex matching on the taskTitle for every render, even if it hasn't changed

2025-03-05 05:28 UTC, roryabraham commented on src/pages/tasks/TaskTitlePage.tsx
> -            {({didScreenTransitionEnd}) => (
why was this change needed?

2025-03-05 07:01 UTC, mananjadhav commented
> @mananjadhav, can you help me with the keyboard shortcut to make the text bold/italic? I don't know how to do that.

Using Cmd+B (Mac) or Ctrl+B (Windows) by selecting the text.

2025-03-06 01:43 UTC, roryabraham approved these changes, later dismissed

2025-03-06 02:35 UTC, mananjadhav commented
I'll review this again and start with the checklist in an hour or two.

2025-03-06 05:29 UTC, mananjadhav commented on src/pages/tasks/TaskTitlePage.tsx
> +            const parsedTitle = getParsedComment(title);
I tested this scenario, the lint should take care of this. The reason I asked to add the check was because we're using `text.length` inside `getParsedComment`.

2025-03-06 05:34 UTC, mananjadhav commented
Just finished with the review, I'll start with the QA now. I think this should be ready in a few hours.

2025-03-06 10:19 UTC, mananjadhav commented
I thought I had a different react-native-live-markdown version from another task. But I deleted and reinstalled all dependencies. Still get the same errors.

Looks like description doesn't allow long markdown. Need to update the lengh.

<img width="697" alt="Screenshot 2025-03-06 at 3 47 25 PM" src="https://github.com/user-attachments/assets/1d4ba973-3186-44f5-9639-2699a9f3552c" />

2025-03-06 10:40 UTC, mananjadhav commented
While editing using any special characters for markdown ends up into a crash too.

https://github.com/user-attachments/assets/92379828-0ceb-4885-ad37-d0ead7f19115

2025-03-06 12:41 UTC, mananjadhav commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified that the composer does not automatically focus or open the keyboard on mobile unless explicitly intended. This includes checking that returning the app from the background does not unexpectedly open the keyboard.
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] For any bug fix or new feature in this PR, I verified that sufficient [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) are included to prevent regressions in this flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expect [...]

2025-03-06 14:20 UTC, mananjadhav commented
@Krishna2323 I found an issue with Android. The markdown rendered has elongated space when I copy the content.

https://github.com/user-attachments/assets/82882c12-e428-4051-b237-ca248159d9d9

2025-03-06 16:06 UTC, mananjadhav commented
@Krishna2323 Looks like the problem on both the native platforms.


https://github.com/user-attachments/assets/50df8799-0c25-46b3-8110-0bcc1127b343

2025-03-07 06:42 UTC, mananjadhav commented
@Krishna2323 This is better than before but still has issues with the render.

https://github.com/user-attachments/assets/32421f35-52da-403b-83ae-7845652cf99f

2025-03-08 03:21 UTC, mananjadhav commented
There are minor issues with the native renders when using large markdown with block quote and spaces. Let's merge this and fix any issues as follow up. ([discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1741374016219829?thread_ts=1734840786.675329&cid=C01GTK53T8Q))

2025-03-08 03:22 UTC, mananjadhav approved these changes

2025-03-08 03:30 UTC, roryabraham approved these changes

2025-03-08 03:30 UTC, merged

2025-03-08 03:38 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2025-03-11 10:26 UTC, izarutskaya commented
@Krishna2323 Found issue https://github.com/Expensify/App/issues/58189

2025-03-11 10:54 UTC, NikkiWines commented
@Krishna2323 @mananjadhav this PR is tied to [this deploy blocker](https://github.com/Expensify/App/issues/58194)

2025-04-07 07:41 UTC, jjcoffee commented on src/components/HTMLEngineProvider/HTMLRenderers/StrongRenderer.tsx
> +function StrongRenderer({tnode}: CustomRendererProps<TText | TPhrasing>) {
Coming from https://github.com/Expensify/App/issues/58242, the styles here caused a regression for the display of a user's custom display name vs. email in the header. More details in the [proposal](https://github.com/Expensify/App/issues/58242#issuecomment-2715296960).

2025-04-22 08:42 UTC, rojiphil commented
Nested markdown support was missing. This was addressed in #58468