Frontend: Private Domain Onboarding Check
Expensify/App pull request #54186
Opened 2024-12-16 10:39 UTC by allgandalf

### Explanation of Change

Check whether public domain and SMS sign-ups have a work email in the New Expensify onboarding flow. If they’re new accounts, we'll merge them, and if the work email is tied to an existing account, we’ll redirect them to OldDot. 

### Fixed Issues

$ https://github.com/Expensify/App/issues/54075
PROPOSAL: N/A

### Tests

Same as QA
- [x] Verify that no errors appear in the JS console

### Offline tests

-
### QA Steps

# Test Scenarios

## 1. Add Private Domain When Account Doesn’t Already Exist (Scenario A)

- **Login:** 
  - Login to Expensify using a public domain email address (e.g. Gmail).

- **Onboarding Modal:**
  - Verify the modal appears with the screen asking: “What’s your work email?”
  - Verify the input field is auto-focused on web and desktop but **not** on mobile platforms.
  - Verify you can type into the input field.

- **Entering Email:**
  - Type a public domain email address into the input field.
  - Verify the modal displays an error message stating: “Please enter a valid work email from a private domain.”

- **Adding Work Email:**
  - Enter a valid private domain email address that is not connected to an existing account.
  - Click **"Add work email"**.
  - Verify that the onboarding process continues.

- **Post-Onboarding Verification:**
  - Navigate to **Settings > Profile > Contact Method**.
  - Verify that both the private domain and the public domain email addresses are listed as contact methods.
  - Verify that the private domain email is set as the primary contact method (it should be the email displayed under the username in the top left corner of the settings screen).

---

## 2. Add Private Domain When Account  Already Exist (Scenario B)

- **Initial Account Setup:**
  - Create an Expensify account using a private domain email address (e.g. `foobar@work.com`), validate it, then log out.
  - Create a new account using a public domain email address (e.g. Gmail).

- **Onboarding Modal:**
  - Verify the onboarding modal appears with the screen asking: “What’s your work email?”
  - Verify the input field is auto-focused on web and desktop but **not** on mobile platforms.
  - Verify you can type into the input field.

- **Linking Existing Private Domain:**
  - Enter the private domain email address that was used to create the initial account.
  - Click **"Add work email"**.
  - Verify that the screen transitions to a validate code screen.
  - Verify that you receive an email with the validation code.
  - Enter the validation code and click **"verify"**.
  - Verify that the onboarding process continues, with the next screen displaying: “What do you want to do today?”

- **Post-Onboarding Verification:**
  - Navigate to **Settings > Profile > Contact Method**.
  - Verify that both the private domain and the public domain email addresses are listed as contact methods.
  - Verify that the private domain email is set as the primary contact method (it should be the email displayed under the username in the top left corner of the settings screen).

---

## 3. Don’t Ask for Work Email if Domain Is Private

- **Account Creation:**
  - Create an Expensify account using a private domain email address.

- **Verification:**
  - Verify that the onboarding modal does **not** display a screen asking: “What’s your work email?”

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined [...]

2025-02-11 19:46 UTC, ikevin127 commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] For any bug fix or new feature in this PR, I verified that sufficient [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) are included to prevent regressions in this flow.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add sc [...]

2025-02-16 01:53 UTC, ikevin127 requested changes

2025-02-16 01:53 UTC, ikevin127 commented on src/libs/actions/Session/index.ts
> +            value: 'onboarding.error',
From [design doc](https://docs.google.com/document/d/1JlM9G3jZpaHDlcILWL9170ancMLtOnI2a73dQgX6ENo/edit), we have the following logic requirement:
- **verify that when `MergeIntoAccountAndLogin` fails and it’s not related to magic code validation, we display the “Merging blocked” screen on which if user clicks “Got it”, we’ll move forward with the onboarding flow**

which does not seem to be implemented accordingly. This is how I went about reproducing and here are the details of what I found:
- I went with testing the second case (work email already tied to existing account)
- I set `CONST.MAX_REQUEST_RETRIES` to `0` and proceeded to the private domain magic code screen
- set **Settings > Troubleshooting > `Simulate failing network requests`** to **ON** (used CMD + D shortcut)
- proceeded to add the correct magic code received in private domain email inbox
- the `Couldn’t add work email` modal screen showed briefly (most likely same issue detailed here)
- then I was navigated to the OnboardingPurpose screen with `onboarding.error` error showing at the bottom (see screenshot below), most likely coming from here where this error was added in `MergeIntoAccountAndLogin` failureData.

<details>
<summary>Screenshot</summary>

<img width="509" alt="onboarding error" src="https://github.com/user-attachments/assets/19e82154-aa3b-43f7-ae9a-cc5b406963fb" />

</details>

2025-02-16 01:55 UTC, ikevin127 commented
@allgandalf I started testing the PR using the list mentioned in https://github.com/Expensify/App/issues/54075#issuecomment-2635544922 which was created based on the [**design doc**](https://docs.google.com/document/d/1JlM9G3jZpaHDlcILWL9170ancMLtOnI2a73dQgX6ENo/edit), find the results breakdown below.

**Legend**:
- ✅ (complete and working as expected)
- ⚠️ (incomplete or not working as expected) + include details where not self-explanatory
- ❌ (not implemented) + include details where not self-explanatory

##

🧪 **Testing list**:
- ❌ verify the new feature is behind beta (`canUsePrivateDomainCheck`)
- ✅ on signup, verify public domain check (both email and phone [phones always public domain]) via isFromPublicDomain and if true -> show new private domain onboarding screen 
- ✅ on new onboarding flow screen, verify that user is asked for work email 
- ✅ verify that Skip button exists, which checks whether user comes from OD and if their `signupQualifier` is `VSB` then navigate the user to Accounting Onboarding Page  
- ✅ verify that when user will press “Add work email” we validate to check for valid private domain email  
- ❌ on mobile devices (mWeb / Native), verify there’s no `autoFocus` on the Work Email input (see ❌  details below)
  - looks like this was **not implemented** because autofocus does happen when the modal screen / input is mounted (see iOS: mWeb and Native videos below)
    <details>
    <summary>Videos</summary>
    
    | iOS: mWeb | iOS: Native |
    | ------------- | ------------- |
    | <video src="https://github.com/user-attachments/assets/1b915d7a-c156-4424-9959-08b45ded953b"> | <video src="https://github.com/user-attachments/assets/59c442df-b0b1-4163-8b22-1a4e3ea22e4f"> |
    
    </details>
- ⚠️ next, verify whether work email is NOT tied to an existing account then skip magic code, otherwise request magic code (see ⚠️ details below)
  - first case (work email NOT tied to existing account) works as expected when it comes to adding a not existing work email to new account, but there's a weird mismatch in **Settings > Profile > Contact method** where is now showing the private domain email, while if clicked on the field, RHP is showing the public domain email used on account creation before work email was added (see screenshow below)
    <details>
    <summary>Screenshot</summary>
    
    <img width="1187" alt="Screenshot 2025-02-15 at 16 32 41" src="https://github.com/user-attachments/assets/db751239-7dcd-4470-832b-2cc420bf1864" />
    
    </details>
  - in the second case (work email already tied to existing account) -> I received a `'Merge account request'` email with the magic code, when entered, onboarding modal screen changed to `Couldn’t add work email` but shortly after changed to OnboardingPurpose and looks like merge was successful (dropped a [comment](https://github.com/Expensify/App/pull/54186#discussion_r1957214331) in the code logic detailing the issue).
- ✅ verify that there’s an option to Skip the magic code validation, which won’t save the private domain email as contact method in user profile, continuing with the onboarding flow
- ⚠️ verify that when `MergeIntoAccountAndLogin` fails and it’s not related to magic code validation, we display the “Merging blocked” screen on which if user clicks “Got it”, we’ll move forward with the onboarding flow (see ⚠️ details below)
  - I went with testing the second case (work email already tied to existing account), I set `CONST.MAX_REQUEST_RETRIES` to `0` and proceeded to the private domain magic code screen then set **Settings > Troubleshooting > `Simulate failing network requests`** to **ON** (used CMD + D shortcut) then proceeded to add the correct magic code received in private domain email inbox -> the `Couldn’t add work email` modal screen showed briefly (most likely same issue detailed here), then I was navigated to the OnboardingPurpose screen with `onboarding.error` error showing at the bottom, most likely coming from [here](https://github.com/Expensify/App/pull/54186#discussion_r1957221463) where this error was added in `MergeIntoAccountAndLogin` failureData. This tells me that the "`MergeIntoAccountAndLogin` fails and it’s not related to magic code validation" logic seems to be incomplete / not working as expected.
- ⚠️ depending on whether the private domain was validated or not, if the `shouldRedirectToClassicAfterMerge` NVP value is `true` we redirect the user to OD, otherwise continue with current ND onboarding flow (see ⚠️ details below)
  - looks like in the case of a non-validated private domain, when `AddWorkEmail` is called we get `401 work account isn't validated` in response which displays the same UI [issue](https://github.com/Expensify/App/pull/54186#discussion_r1957221463) described above (`onboarding.error` at the bottom of OnboardingPurpose modal)

2025-04-02 03:55 UTC, ikevin127 commented
@allgandalf ♻️ Retested the list mentioned in https://github.com/Expensify/App/pull/54186#issuecomment-2661187227 after the latest updates and here are the results:

🧪 **Testing list**:
- ~~❌ verify the new feature is behind beta (`canUsePrivateDomainCheck`)~~: [dismissed](https://github.com/Expensify/App/pull/54186#issuecomment-2665972885) by PR author as dropped
- ✅ on mobile devices (mWeb / Native), verify there’s no `autoFocus` on the Work Email input ([fixed](https://github.com/Expensify/App/pull/54186#issuecomment-2666079001))
- ⚠️ next, verify whether work email is NOT tied to an existing account then skip magic code, otherwise request magic code (see ⚠️ details below)
  - ~~first case (work email NOT tied to existing account) works as expected when it comes to adding a not existing work email to new account, but there's a weird mismatch in **Settings > Profile > Contact method** where is now showing the private domain email, while if clicked on the field, RHP is showing the public domain email used on account creation before work email was added (see screenshow below)~~:
  - ⚠️ issue now is that as soon as we add private domain email and click `Continue` the private domain onboarding modal screen becomes blank and the UI is locked there until we click outside the modal - noting thatthe route becomes `/onboarding/purpose` and the `AddWorkEmail` API call seems to be successful even though this UI issue occurs -> once clicked outside the blank screen modal, the OnboardingPurpose modal screen will show up with an error at the bottom: `Select an option to move forward.`
    <details>
    <summary>Screenshot</summary>
    
    <img width="1440" alt="i1" src="https://github.com/user-attachments/assets/cb87155b-7df1-474f-94cf-7daaa3ed70d4" />

    </details>

    <details>
    <summary>AddWorkEmail - Response (JSON)</summary>
    
    ```js
    {
        "jsonCode": 200,
        "requestID": "929d21ce29bb1746-LAX",
        "onyxData": [
            {
                "key": "loginList",
                "onyxMethod": "merge",
                "value": {
                    "contact+100@baderproductions.com": {
                        "partnerID": 1,
                        "partnerName": "expensify.com",
                        "partnerUserID": "contact+100@baderproductions.com",
                        "validateCodeSent": false,
                        "validatedDate": ""
                    }
                }
            },
            {
                "key": "report_4043611273773663",
                "onyxMethod": "merge",
                "value": {
                    "lastReadTime": "2024-11-05 01:24:02.075"
                }
            },
            {
                "key": "report_4043611273773663",
                "onyxMethod": "merge",
                "value": {
                    "participants": {
                        "19478700": {
                            "notificationPreference": "daily"
                        }
                    }
                }
            },
            {
                "key": "report_4043611273773663",
                "onyxMethod": "merge",
                "value": {
                    "chatType": "domainAll",
                    "lastActorAccountID": 18633110,
                    "lastMessageText": "",
                    "lastVisibleActionCreated": "2024-11-05 01:24:02.075",
                    "managerID": 0,
                    "nonReimbursableTotal": 0,
                    "ownerAccountID": 18633110,
                    "parentReportActionID": null,
                    "parentReportID": null,
                    "policyID": "_FAKE_",
                    "reportID": "4043611273773663",
                    "reportName": "#baderproductions.com",
                    "stateNum": 0,
                    "statusNum": 0,
                    "total": "0",
                    "type": "chat",
                    "visibility": ""
                }
            },
            {
                "key": "account",
                "onyxMethod": "merge",
                "value": {
                    "primaryLogin": "contact+100@baderproductions.com"
                }
            },
            {
                "key": "session",
                "onyxMethod": "merge",
                "value": {
                    "email": "contact+100@baderproductions.com"
                }
            },
            {
                "key": "userMetadata",
                "onyxMethod": "merge",
                "value": {
                    "email": "contact+100@baderproductions.com"
                }
            },
            {
                "key": "credentials",
                "onyxMethod": "merge",
                "value": {
                    "login": "contact+100@baderproductions.com"
                }
            },
            {
                "key": "personalDetailsList",
                "onyxMethod": "merge",
                "value": {
                    "19478700": {
                        "accountID": 19478700,
                        "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_13.png",
                        "displayName": "contact+100@baderproductions.com",
                        "firstName": "",
                        "lastName": "",
                        "login": "contact+100@baderproductions.com",
                        "phoneNumber": "",
                        "pronouns": "",
                        "status": null,
                        "timezone": {
                            "automatic": true,
                            "selected": "America\/Los_Angeles"
                        },
                        "validated": false
                    }
                }
            },
            {
                "key": "nvp_onboarding",
                "onyxMethod": "set",
                "value": {
                    "hasCompletedGuidedSetupFlow": false,
                    "shouldValidate": false
                }
            }
        ],
        "previousUpdateID": 4651247245,
        "lastUpdateID": 4651254010
    }
    ```

    </details>
  - ~~in the second case (work email already tied to existing account) -> I received a `'Merge account request'` email with the magic code, when entered, onboarding modal screen changed to `Couldn’t add work email` but shortly after changed to OnboardingPurpose and looks like merge was successful (dropped a [comment](https://github.com/Expensify/App/pull/54186#discussion_r1957214331) in the code logic detailing the issue).~~
  - ⚠️ issue now is that once magic code is added, the private domain modal closes and OnboardingPurpose modal does not appear (flow is skipped entirely), we're just landed on the app
- ⚠️ verify that when `MergeIntoAccountAndLogin` fails and it’s not related to magic code validation, we display the “Merging blocked” screen on which if user clicks “Got it”, we’ll move forward with the onboarding flow (see ⚠️ details below)
  - I went with testing the second case (work email already tied to existing account), I set `CONST.MAX_REQUEST_RETRIES` to `0` and proceeded to the private domain magic code screen then set **Settings > Troubleshooting > `Simulate failing network requests`** to **ON** (used CMD + D shortcut) then proceeded to add the correct magic code received in private domain email inbox -> the `Couldn’t add work email` modal screen showed briefly (most likely same issue detailed here), then I was navigated to the OnboardingPurpose screen with `onboarding.error` error showing at the bottom, most likely coming from [here](https://github.com/Expensify/App/pull/54186#discussion_r1957221463) where this error was added in `MergeIntoAccountAndLogin` failureData. This tells me that the "`MergeIntoAccountAndLogin` fails and it’s not related to magic code validation" logic seems to be incomplete / not working as expected.
- ~~depending on whether the private domain was validated or not, if the `should [...]

2025-04-04 18:08 UTC, ikevin127 commented
@allgandalf ♻️ Retested again using list mentioned in https://github.com/Expensify/App/pull/54186#issuecomment-2661187227 after the latest updates and here are the results:

🧪 **Testing list**:
- ✅ on mobile devices (mWeb / Native), verify there’s no `autoFocus` on the Work Email input ([fixed](https://github.com/Expensify/App/pull/54186#issuecomment-2666079001))
- ✅ next, verify whether work email is NOT tied to an existing account then skip magic code, otherwise request magic code
  - ~~first case (work email NOT tied to existing account) works as expected when it comes to adding a not existing work email to new account, but there's a weird mismatch in **Settings > Profile > Contact method** where is now showing the private domain email, while if clicked on the field, RHP is showing the public domain email used on account creation before work email was added (see screenshow below)~~:
  - ✅ ~~issue now is that as soon as we add private domain email and click `Continue` the private domain onboarding modal screen becomes blank and the UI is locked there until we click outside the modal - noting thatthe route becomes `/onboarding/purpose` and the `AddWorkEmail` API call seems to be successful even though this UI issue occurs -> once clicked outside the blank screen modal, the OnboardingPurpose modal screen will show up with an error at the bottom: `Select an option to move forward.`~~ (fixed)

  - ~~in the second case (work email already tied to existing account) -> I received a `'Merge account request'` email with the magic code, when entered, onboarding modal screen changed to `Couldn’t add work email` but shortly after changed to OnboardingPurpose and looks like merge was successful (dropped a [comment](https://github.com/Expensify/App/pull/54186#discussion_r1957214331) in the code logic detailing the issue).~~
  - ✅ ~~issue now is that once magic code is added, the private domain modal closes and OnboardingPurpose modal does not appear (flow is skipped entirely), we're just landed on the app~~ (fixed)
- ✅ verify that when `MergeIntoAccountAndLogin` fails and it’s not related to magic code validation, we display the “Merging blocked” screen on which if user clicks “Got it”, we’ll move forward with the onboarding flow (see ⚠️ details below)
  - ✅ ~~I went with testing the second case (work email already tied to existing account), I set `CONST.MAX_REQUEST_RETRIES` to `0` and proceeded to the private domain magic code screen then set **Settings > Troubleshooting > `Simulate failing network requests`** to **ON** (used CMD + D shortcut) then proceeded to add the correct magic code received in private domain email inbox -> the `Couldn’t add work email` modal screen showed briefly (most likely same issue detailed here), then I was navigated to the OnboardingPurpose screen with `onboarding.error` error showing at the bottom, most likely coming from [here](https://github.com/Expensify/App/pull/54186#discussion_r1957221463) where this error was added in `MergeIntoAccountAndLogin` failureData. This tells me that the "`MergeIntoAccountAndLogin` fails and it’s not related to magic code validation" logic seems to be incomplete / not working as expected.~~ (can't reproduce anymore)
- ~~depending on whether the private domain was validated or not, if the `shouldRedirectToClassicAfterMerge` NVP value is `true` we redirect the user to OD, otherwise continue with current ND onboarding flow (see ⚠️ details below)~~
  - ~~looks like in the case of a non-validated private domain, when `AddWorkEmail` is called we get `401 work account isn't validated` in response which displays the same UI [issue](https://github.com/Expensify/App/pull/54186#discussion_r1957221463) described above (`onboarding.error` at the bottom of OnboardingPurpose modal)~~
  - ✅ ~~there does not seem to be any error / issue with this one anymore, but regarding of email being validated or not, the `AddWorkEmail` is successful and we're moved to OnboardingPurpose, then in Settings we have to validate both the private domain email and public domain emails - no redirect to OD happens~~ (can't reproduce anymore)

##

⚠️ The only failing test from OP is `2. Add Private Domain When Account Doesn’t Already Exist (Scenario B)`, video:

https://github.com/user-attachments/assets/edb46845-fd74-49b9-899e-8dbd69a04f3f

2025-04-07 19:44 UTC, blimpich commented
I'm not getting what Kevin is getting, but I am now on the latest getting a weird black screen after a successful merge. Clicking elsewhere on the screen fixes it.

https://github.com/user-attachments/assets/db129738-0d7a-44e0-8fe1-704a2290be25

2025-04-09 19:24 UTC, ikevin127 commented
♻️ Performing final review, will get back with results soon and approve if everything works as expected.

2025-04-09 19:48 UTC, ikevin127 approved these changes

2025-04-09 22:22 UTC, blimpich commented
Strange, it definitely works for me now. Black screen is gone too.

https://github.com/user-attachments/assets/e905d7f0-33b7-4d97-bfa2-07d244f95b68

2025-04-09 22:27 UTC, blimpich commented
`hasCompletedGuidedSetup` is returned in my response for MergeIntoAccountAndLogIn, strange that it isn't for Kevin

![Screenshot 2025-04-09 at 3 26 27 PM](https://github.com/user-attachments/assets/819afb33-b6d6-4eb8-821c-e80722aa8fe9)

2025-04-09 23:22 UTC, blimpich commented
@allgandalf any idea why Kevin might be getting the weird behavior? Also can you merge in the latest main?

2025-04-09 23:50 UTC, blimpich commented
Ah I think I've figured it out. This is a backend issue I think. For some reason Kevin's onboarding nvp is not being found by the backend. That part I don't get. But when it can't find the onboarding nvp it creates a new one, and for the MergeIntoAccountAndLogIn command it doesn't init the `hasCompletedGuidedSetupFlow` key. Since it's a set operation and not a merge operation this causes Kevin's onboarding flow to stop. I can make the backend init that value to be false in this case. It should always be false since a person calling this command should only ever call it if they are in the onboarding modal. I'll put up a backend PR.

@ikevin127 when you get a chance can you show me what your onboarding nvp looks like right before `MergeIntoAccountAndLogIn` is called?

2025-04-10 01:31 UTC, ikevin127 commented
@blimpich This is what my `nvp_onboarding` holds after calling `AddWorkEmail`, but before actually validating (`MergeIntoAccountAndLogIn `):

```ts
> Onyx.get('nvp_onboarding');

{
    "hasCompletedGuidedSetupFlow": false,
    "shouldValidate": true
}
```

##

@allgandalf While testing this I found another, what looks like a FE issue:

**Steps**: Follow the `2. Add Private Domain When Account Already Exist (Scenario B)` steps, but instead of adding the magic code to validate, go back and press on the `Add work email` button once again and notice how nothing happens flow-wise except for button loading state and `AddWorkEmail` being called.

☝️ Same if we're trying to input another email address of an account that already exists.

2025-04-10 17:06 UTC, blimpich commented
I'll update the backend to set the reports to up to date. Thanks for looking into it! Hopefully will have a PR up by end of day.

2025-04-10 17:56 UTC, blimpich commented
Created an issue here if you want to follow along: https://github.com/Expensify/App/issues/60055

2025-04-15 04:05 UTC, ikevin127 commented
@blimpich 🟢 Issue was fixed, latest testing looks good 👍 

https://github.com/user-attachments/assets/76ab5a13-5a90-4250-b683-10ccfee88b6e

##

⚠️ However this [other issue](https://github.com/Expensify/App/pull/54186#issuecomment-2791323719) (end of comment) is still present and should be addressed before merging the PR.

2025-04-15 16:46 UTC, blimpich commented
Yeah I agree. The main flows work here. This is a huge PR, lets deal with other more edge case issues / bugs as follow up. I think this is ready to merge 👍

2025-04-15 17:51 UTC, blimpich commented
It was a trivially simple merge conflict to resolve so I just resolved it myself. Once this goes green lets merge!

2025-04-15 17:56 UTC, blimpich commented
Ugh, linting changed as a result of merging in the latest main. Will let @allgandalf handle that.

2025-04-15 17:57 UTC, blimpich approved these changes, later dismissed

2025-04-15 18:27 UTC, blimpich commented
All good @allgandalf! One more day won't hurt us 🙂. We could probably merge but lets just wait till you can update the code to meet the new linter requirements and get a full green build.

2025-04-16 17:01 UTC, blimpich approved these changes
WOOOOOOHHOOOO LETS MERGE!!!! 🎉

2025-04-16 17:02 UTC, merged

2025-04-16 17:10 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.