Implemented per diem request flow
Expensify/App pull request #54252
Opened 2024-12-17 15:47 UTC by shubham1206agra

### Explanation of Change

### Fixed Issues

$ https://github.com/Expensify/App/issues/50868

### Tests

1. Click into the Submit Expense flow
2. Confirm that the segmented control shows 4 options (with an icon for the 3 that are not selected, and an icon + text for the option selected)
3. Click Per diem and confirm you are presented with a list of Destinations to choose from
4. Select a Destination and confirm you are taken to a screen to select the Start date, Start time, End date, End time
5. Confirm that each of these options works as expected (calendar choice for date, time choice for time)
6. Click Next and confirm you are taken to the page to select the Subrate
7. Click into the Subrate selection and confirm it matches the expected list of subrates for that destination 
8. Return to the Subrate page and enter a quantity 
9. Click Next and confirm you are presented with a summary page listing:
 - To - who the expense will be submitted to
 - Destination
 - Time - a concatenation of start time + date, and end time + date
 - Subrate - a concatenation of the selected subrate, and a Qty: X for the quantity selected 
 - Description - free text field to add a description to the expense
 - Category 
 - Tag

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as Tests

### QA Steps

Same as Tests but you can't submit the expense just yet.

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added  [...]

2024-12-18 16:51 UTC, dannymcclain commented
>QQ, What should I call this button? It will send me to per diem page of the workspace.

I would say `Edit per diem rates`.

For this:
![CleanShot 2024-12-18 at 10 48 59@2x](https://github.com/user-attachments/assets/14330d4e-7121-4148-bc1b-463554acc877)

I think we're missing some padding on the left/right of that tab. Here's the Figma design for reference:
![CleanShot 2024-12-18 at 10 50 38@2x](https://github.com/user-attachments/assets/a8149831-6787-49d0-82d4-0f0cc7c4f335)

Those tabs should have a minimum of `12px` of padding on the left and right.

2024-12-18 17:29 UTC, shawnborton commented
What's happening in this screen here?
![CleanShot 2024-12-18 at 12 29 04@2x](https://github.com/user-attachments/assets/88ca811e-4fbb-4dc3-bfaa-c399094fa825)

I would think that the rows wouldn't have a checkmark, you need to first select on of these rows to continue?

2024-12-18 17:32 UTC, dannymcclain commented
>I would think that the rows wouldn't have a checkmark, you need to first select on of these rows to continue?

Ah yeah good catch.

2024-12-18 17:38 UTC, shawnborton commented
Ah okay. Should we use the correct BG color then for the highlighted row? Basically the same background color we use on other list selctions.

2024-12-18 17:48 UTC, dannymcclain commented
That tab padding looks better to me.

2024-12-19 00:51 UTC, dubielzyk-expensify commented
Are we still doing this treatment @dannymcclain or am I looking at old mocks? 
![CleanShot 2024-12-19 at 10 51 28@2x](https://github.com/user-attachments/assets/870885a8-0b5f-413d-b35e-621011e7eb50)

2024-12-19 14:01 UTC, c3024 commented
<img width="1438" alt="Screenshot 2024-12-19 at 7 12 09 PM" src="https://github.com/user-attachments/assets/d4327dc6-8c4e-45a5-92b6-b41d6d3e79af" />

@shubham1206agra , please make [this](https://github.com/Expensify/App/pull/54252#issuecomment-2551822000) change.

2024-12-19 14:04 UTC, c3024 commented
Refreshing with per diem RHP (without pre diem rates added) open takes to not found page.


https://github.com/user-attachments/assets/3e1a3ab1-97bc-4fa2-ab96-f9f6b46a7cd5

2024-12-19 14:27 UTC, dannymcclain commented
>Are we still doing this treatment @dannymcclain or am I looking at old mocks?

We are—mocks are [here in Figma](https://www.figma.com/design/xlfM156dLAYhPDv1Ld7ZlH/Per-Diem?node-id=65-38063&t=rWaD24443NIfidUD-11) (I think that's where you grabbed that screenshot from too).

Latest styles of those for this are in [this screenshot](https://github.com/Expensify/App/pull/54252#issuecomment-2551917410). The padding on the tabs is a _little_ different, but I think that's just the nature of how we're using flexbox to distribute these.

2024-12-28 08:21 UTC, c3024 commented on src/pages/iou/request/step/IOURequestStepConfirmation.tsx
> +                return;
Will this be implemented in a follow-up PR?

2024-12-28 12:33 UTC, c3024 commented
<img width="1438" alt="Screenshot 2024-12-28 at 5 58 25 PM" src="https://github.com/user-attachments/assets/28b1a43e-664b-4923-b19d-3fb6997c5b02" />



Should we enforce the total number of subrate days be less than the trip days?

2024-12-28 15:43 UTC, c3024 requested changes
Code changes look good. I will test and update if I find anything.

2024-12-28 15:43 UTC, c3024 commented on src/pages/iou/request/step/IOURequestStepDestination.tsx
> +    explictPolicyID,
```suggestion
    explicitPolicyID,
```

2024-12-30 10:44 UTC, c3024 commented
![Screenshot 2024-12-30 at 4 12 19 PM](https://github.com/user-attachments/assets/59e05d6e-9bf9-4ca9-911e-d504cbe16d23)

@shubham1206agra 

There is extra space on top on the time selection page on iOS.

2024-12-30 15:22 UTC, c3024 commented
Everything looks good. My Android build is failing. It will likely work now. I will complete the checklist in a while.

2024-12-30 17:37 UTC, c3024 commented
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] For any bug fix or new feature in this PR, I verified that sufficient [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) are included to prevent regressions in this flow.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

<!-- add sc [...]

2024-12-30 17:41 UTC, c3024 approved these changes
LGTM!

2025-01-02 09:16 UTC, Gonals approved these changes

2025-01-02 09:16 UTC, merged

2025-01-02 09:25 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2025-01-06 21:42 UTC, IuliiaHerets commented
This PR is failing for mWeb because of issue #54845

2025-01-07 05:37 UTC, c3024 commented on src/pages/iou/request/step/IOURequestStepSubrate.tsx
> +function IOURequestStepWaypoint({
```js
-IOURequestStepWaypoint
+IOURequestStepSubRate
```

2025-01-07 09:50 UTC, izarutskaya commented
@shubham1206agra found issues when validation this PR - issues https://github.com/Expensify/App/issues/54831, https://github.com/Expensify/App/issues/54833, https://github.com/Expensify/App/issues/54845

https://platform.applause.com/services/links/v1/external/b00e3061203c6449d2d2426ed73f47af66da6deb42d3ef34e57216ee33090d66

https://platform.applause.com/services/links/v1/external/de924be17c74e919b3b736c50bae52c427d9a3eabf15597f0d978467af1e2ca2

2025-01-27 18:25 UTC, ahmedGaber93 commented on src/components/TabSelector/TabSelectorItem.tsx
> +    shouldShowLabelWhenInactive?: boolean;
Coming from here https://github.com/Expensify/App/issues/55032, we decide to add a tooltip on web when `shouldShowLabelWhenInactive` is false

2025-06-15 12:20 UTC, shubham1206agra commented on src/components/TimeModalPicker.tsx
> +function TimeModalPicker({value, errorText, label, onInputChange = () => {}}: TimeModalPickerProps) {
Missing forwardRef here, which caused https://github.com/Expensify/App/issues/61595

2025-07-08 10:44 UTC, dukenv0307 commented on src/libs/PolicyUtils.ts
> +    return !isEmptyObject(perDiemCustomUnit) && !!perDiemCustomUnit?.enabled;
Comming from: https://github.com/Expensify/App/issues/64913, the user can't submit the per diem expense from WS if `policy?.isPolicyExpenseChatEnabled` is false

2025-08-11 18:12 UTC, ikevin127 commented on src/pages/iou/request/IOURequestStartPage.tsx
> +                                    </TopTab.Screen>
The addition of the new tab screen here led to the following issue on native due to conflicting horizontal vs vertical scroll list coming from the tab navigator and per diem page scroll list:
- https://github.com/Expensify/App/issues/65746

we addressed this with a mixed approach between native and web based platforms by dismissing the keyboard when any direction swipe starts on native and disabling tab navigator swipe on mweb while on the Per Diem tab only.

2025-12-04 10:06 UTC, ahmedGaber93 commented on src/pages/iou/request/step/IOURequestStepDestination.tsx
> +    const shouldShowEmptyState = isEmptyObject(customUnit?.rates);
Coming from https://github.com/Expensify/App/issues/74272, when have an edge case, after clearing cache, it shows empty state page briefly instead of loading.

2026-02-03 17:44 UTC, rojiphil commented on src/pages/iou/request/step/IOURequestStepTime.tsx
> +    const shouldShowNotFound = !IOUUtils.isValidMoneyRequestType(iouType) || isEmptyObject(transaction?.comment?.customUnit) || isEmptyObject(policy);
NAB but a brief display of `Not here` page is displayed because of empty `transaction` during creation of per diem expense. We handled this in #78920

2026-10-28 02:03 UTC, huult commented on src/pages/iou/request/step/IOURequestStepDestination.tsx
> +                        containerStyle={[styles.flex1, styles.justifyContentCenter]}
`WorkspaceEmptyStateSection` caps its width at 720px (`styles.workspaceSection`) but doesn't center itself, and this `containerStyle` doesn't add `alignSelf: center`. Between 720px and 799px the empty state on the Per diem step sticks to the left edge instead of being centered. Fixed in https://github.com/Expensify/App/pull/104669.