fix: apply safe area padding for workspace screens
Expensify/App pull request #54285
Opened 2024-12-18 10:41 UTC by kirillzyusko

### Explanation of Change

### Fixed Issues

$ https://github.com/Expensify/App/issues/53186
PROPOSAL: N/A

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

![image](https://github.com/user-attachments/assets/813a9324-edb3-4d78-8878-bbf71e6615cf)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-12-18 13:51 UTC, kirillzyusko commented
@paultsimura they are coming not because of my changes (I think recently new eslint rule was introduced and it hasn't been fixed yet).

Not sure if I should fix it in this PR (or should I fix it at all?..)

2024-12-18 14:01 UTC, kirillzyusko commented
> now, when a file you edit has some default IDs, you should fix it in the PR

Ah, okay, cool, thanks for clarifications - will do that soon!

2024-12-19 16:26 UTC, paultsimura requested changes

2024-12-20 10:15 UTC, kirillzyusko commented
> we kinda sacrifice the look on the gesture-controlled devices for the sake of those with 3-buttons navigation

Just for an additional context - we already did the same fix for "Search" screens group (and it was accepted) 👀

2024-12-20 10:21 UTC, kirillzyusko commented
> Same issue on WorkspaceProfilePage.

And

> Now with all these changes it looks like the majority of WorkspacePageWithSections usages is with includeSafeAreaPaddingBottom=true. Maybe it makes sense to default it to true and pass false in exceptional cases?

If UX team is happy with a proposed approach in this PR then I'll change `includeSafeAreaPaddingBottom=true` by default and will check other screens to be sure all screens follow the same pattern 👍

2024-12-20 13:48 UTC, dannymcclain commented
Man I'm pretty torn. I get why we'd want to add in the safe area... But most of the apps I'm looking at on my phone do not include that safe area padding on screens that don't have bottom tabs. @Expensify/design any strong feelings?

![image](https://github.com/user-attachments/assets/21d4e92c-30d8-4b99-9745-069f40c90ae2)

2024-12-20 14:02 UTC, shawnborton commented
Personally, at least on iOS, I feel strongly that we should do it exactly like you are showing in your examples Danny. I find this version to feel completely broken IMO: 
![image](https://github.com/user-attachments/assets/78d97168-b544-4763-b7e6-6d82089ead13)

That being said, I'm not sure what is standard for Android in this situation.

2024-12-20 21:07 UTC, shawnborton commented
@Julesssss or @dubielzyk-expensify - do you know what is expected for Android? Should those buttons have a background behind them, or should they float on top of the content like we'd expect on iOS?

2024-12-22 16:55 UTC, mountiny commented
I agree that with iOS its better without the padding

The problem with android with the buttons is that its bad ux imho when you show interactive elements under the android navigation buttons it leads to confusion as you can see two buttons overlayed - hence i think in that case we should definitely include safe area

2024-12-22 17:50 UTC, mountiny commented
We could make it android specific, right @kirillzyusko

2024-12-23 16:02 UTC, kirillzyusko commented
> We could make it android specific, right @kirillzyusko

Yes, we can make it platform specific.

Moreover on Android I think we can also make those padding transparent if it's gesture-navigation bar, and for 3 button navigation - we can apply a padding.

However such refactoring may introduce some problems. Let me explain my concerns.

### 1️⃣ Non consistent paddings across various screens

As you could observe, somewhere we had transparent navigation bar (Search screens, workspaces screen). On some screens we always applied padding (settings screen).

The current approach that we aim to follow is to always have that padding. But as you can see in this PR some screens are still have old behavior and not always add the padding.

### 2️⃣ Additional padding from `ScreenWrapper` gets removed when keyboard is shown

Me and @hannojg (while re-working the approach with insets handling) discovered, that in all cases we don't want this navigation bar padding to be present when keyboard gets shown, so we re-structured the code to make it by default.

If we are goind to refactor that code again, we should also consider this point and try to change the `ScreenWrapper` API with as small as possible changes.

<hr />

Now, when we want to make changes again I would prefer to have a codebase in a valid state and move atomically from one consistent state to another.

So I have several steps in my head:
- merge this PR as is, because it adds consistency on how we handle paddings on screens (always include padding and be consistent on all screens)
- to remove unused code in app (at the moment we often specify `includeSafeAreaPaddingBottom={true}` property, even if it's `true` by default) - something that I planned to do when app will be in a stable form after all our changes.
- to add a conditional code, that will apply transparent padding on gesture-based nav bar and will keep padding for 3 buttons navigation.

I think such approach will help us to have as small as possible intermediate issues and will assure we are always in consistent state. Let me know what do you think 👀 🙌

2024-12-23 16:09 UTC, kirillzyusko commented
> If we go this way, I would encourage to cover more pages than these in the PR. At least add the ones I've mentioned during the initial review.

Yeah, sure, absolutely agree 🙂 Just want to understand whether we are okay to follow a proposed approach or not and then I can proceed and make corresponding changes based on a chosen decision 👀

2024-12-28 23:04 UTC, mountiny commented
@kirillzyusko Thanks for the explanation. Would your proposed steps lead to the state where the iOS native wont have the extra padding either (same as android without the navigation buttons)? 

If yes, I am fine with this atomic approach.

2024-12-30 12:35 UTC, kirillzyusko commented
> Would your proposed steps lead to the state where the iOS native wont have the extra padding either (same as android without the navigation buttons)?

@mountiny yes, the last step will lead to this 😊

2025-01-07 21:43 UTC, mountiny commented
I think we can go ahead with this plan, but lets prepare it a bit more, I dont like that ios would have this extra padding for more time than needed cc @lakchote 

Also we can use this thread to discuss https://expensify.slack.com/archives/C049HHMV9SM/p1736238279772929

2025-01-08 18:19 UTC, lakchote commented
Posted in Slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1736360325497079?thread_ts=1736238279.772929&cid=C049HHMV9SM) for the next steps.

2025-02-19 10:33 UTC, chrispader commented
Ok, so this PR now removes `includeSafeAreaPaddingBottom={false}` from all screens/components, which will apply (additional) bottom safe area padding to all components/screens, that disabled this before.

Ideally we'll want to merge https://github.com/Expensify/App/pull/55633 right after this. That PR also removes `includeSafeAreaPadding={true}` (or simply `includeSafeAreaPadding`), and disables bottom safe area padding in `ScreenWrapper` alltogether. In that PR, i fix the paddings based on both of these changes. The changes from the first PR (removing `includeSafeAreaPaddingBottom={false}`) will effectively cancel out, because the safe area padding is disabled completely.

Still, there are some more issues to consider, that i'm explaining in the original issue.

2025-02-19 10:44 UTC, mountiny commented
cc @lakchote for visibility.

@chrispader would be great to write down the plan anad also I think we should ask QA to test these on adhoc builds. Should it just be this pr to start with?

2025-02-22 09:12 UTC, chrispader commented
@kirillzyusko i think we can close this PR, since we decided to go with a new plan discussed [here](https://github.com/Expensify/App/issues/53186#issuecomment-2668265406)

This is the new "Base PR" that we'll use instead: https://github.com/Expensify/App/pull/57128

2025-03-05 14:57 UTC, closed without merging