[WIP] align default IDs in ReportUtils file
Expensify/App pull request #54297
Opened 2024-12-18 14:39 UTC by VickyStash

### Explanation of Change

### Fixed Issues

$ https://github.com/Expensify/App/issues/50360
PROPOSAL: https://github.com/Expensify/App/issues/50360#issuecomment-2405820991

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2024-12-19 11:27 UTC, VickyStash commented on .eslintrc.changed.js
> +            files: ['src/libs/actions/IOU.ts', 'src/libs/actions/Report.ts', 'src/libs/actions/Task.ts', 'src/libs/OptionsListUtils.ts'],
`OptionsListUtils` will be anyway ignored in [this PR](https://github.com/Expensify/App/pull/54288)

2024-12-19 11:39 UTC, VickyStash commented on src/libs/ReportUtils.ts
>      if (!moneyRequestReportID) {
It looks like before `moneyRequestReportID` always was a **truly** value. So this condition never worked. Should I remove it maybe?

2024-12-19 17:59 UTC, VickyStash commented
I have some issues with ios build, so I'll attach the recording tomorrow.

2024-12-20 20:01 UTC, paultsimura reviewed
Overall – solid work 🔥 
I'm sure we could break something but it's nearly impossible to test everything on such a change. Too bad we don't have robust unit tests yet 😞

2024-12-24 12:05 UTC, VickyStash commented on src/libs/ReportUtils.ts
> +            : undefined,
Defaulting to `{}` causes TS errors.
I'm not sure if there was no `originalMessage` before, update function should create one...

2024-12-24 12:46 UTC, VickyStash commented on src/libs/ReportUtils.ts
Applied: https://github.com/Expensify/App/pull/54297/commits/964115d3ed4e9e5d55cb068688d65126c8aaad18

2024-12-24 12:51 UTC, VickyStash commented
@paultsimura I've applied your feedback. I'm going to be OOO 25-29 Dec 🎄 , maybe it would be good not to merge this PR during the time, so I can be around to monitor any regressions.

2024-12-30 09:54 UTC, VickyStash commented
@paultsimura Conflicts are resolved!

2024-12-30 18:52 UTC, paultsimura approved these changes
Tested as thoroughly as I could. Hopefully, we won't break anything as the diff is large 😟 
LGTM ✔️

2024-12-30 20:52 UTC, VickyStash commented on src/libs/ReportUtils.ts
>  function getReportMetadata(reportID?: string) {
Done!

2024-12-31 20:47 UTC, neil-marcellini requested changes
Thanks for this. Mostly looks good. I left some NAB suggestions and I also have a few questions I would like answered before we merge it.

2024-12-31 20:47 UTC, neil-marcellini commented on src/libs/ReportUtils.ts
> +    }
NAB: Let's also log a warning here if there's no reportID for some reason. We could also navigate back to the concierge chat in that case which would be a better fallback than doing nothing.

2024-12-31 20:47 UTC, neil-marcellini commented on src/libs/ReportUtils.ts
> +        }
NAB: Again let's log a warning here

2024-12-31 20:47 UTC, neil-marcellini commented on src/pages/home/report/PureReportActionItem.tsx
> +                    iouReportID={ReportActionsUtils.getIOUReportIDFromReportActionPreview(action) as string}
Instead can we have the component set iouReportID as an optional string?

2024-12-31 20:47 UTC, neil-marcellini commented on .eslintrc.changed.js
> +                'src/pages/home/report/PureReportActionItem.tsx',
Does this mean we're planning to migrate this one separately? I'm ok with that, just asking.

2025-01-02 11:44 UTC, VickyStash commented on src/libs/ReportUtils.ts
> +        }
Applied in https://github.com/Expensify/App/pull/54297/commits/a7516f56fc644c1dd7e5a4b9448843e24191a1cc

2025-01-02 11:53 UTC, VickyStash commented on src/pages/home/report/PureReportActionItem.tsx
> +                    iouReportID={ReportActionsUtils.getIOUReportIDFromReportActionPreview(action) as string}
Yes, and it should be done during `PureReportActionItem` updates. I didn't include it in this PR cause it's already complex enough and touches different functionality.
Updating `PureReportActionItem` + `ReportPreview` will require dealing with at least 40 more lint/ts cases, which should be then tested. So I think it would be safe to handle it separately.

2025-01-02 11:53 UTC, VickyStash commented on .eslintrc.changed.js
> +                'src/pages/home/report/PureReportActionItem.tsx',
Yes, I've explained it here https://github.com/Expensify/App/pull/54297#discussion_r1900803728

2025-01-02 18:04 UTC, neil-marcellini approved these changes
Good to go, thank you

2025-01-02 18:05 UTC, merged

2025-01-02 18:13 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.