Recreate a receipt for native
Expensify/App pull request #54358
Opened 2024-12-19 11:37 UTC by rezkiy37

### Explanation of Change

The PR fixes a case when submitting the scanned expense is errored when the user kills the app while the request is in the queue. I propose reconstructing a blob of the receipt if the request is created while the user is offline. 

### Fixed Issues

$ https://github.com/Expensify/App/issues/51761
PROPOSAL: https://github.com/Expensify/App/issues/51761#issuecomment-2561302724

### Tests

1. Go offline.
2. Submit an expense and scan a receipt with the in app camera, submit it to anyone.
3. Kill the app.
4. Re-open the app.
5. Go back online.
6. The receipt is uploaded and scanned correctly. If it fails for some reason, then the user is able to download the receipt.

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as tests.

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

Same as tests.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</d [...]

2024-12-28 11:16 UTC, rezkiy37 commented
I struggle to build Android so I haven't attached a video to this platform. Please build it on your side.

2025-01-08 11:24 UTC, rezkiy37 commented
Android works well.

<details><summary>Video</summary>
<p>

https://github.com/user-attachments/assets/3e881812-1f7d-4946-919f-3df24cfc1dff

</p>
</details>

2025-01-09 14:32 UTC, rezkiy37 commented
@allgandalf, I just tested your case and it works properly on my iPhone in dev mode.

<details><summary>Video</summary>
<p>




https://github.com/user-attachments/assets/53556fcb-31b0-4adb-bc02-b8d1c1e6da0d




</p>
</details>

2025-01-10 09:22 UTC, rezkiy37 commented
@allgandalf, no. I mentioned "_in dev mode_", not a staging build. I still don't have access to it. I can probably build a `.ipa` file locally and test it.

2025-01-13 14:32 UTC, rezkiy37 commented
I've synced the PR up. https://github.com/Expensify/App/pull/54628 has been merged where they integrated `validateFormDataParameter`. I moved this function into a separate file to utilize inside `prepareRequestPayload`. I am retesting the PR now.

2025-01-13 15:23 UTC, rezkiy37 commented
I just tested Android, IOS, and web. They all work properly. 

<details><summary>Videos</summary>
<p>


https://github.com/user-attachments/assets/8ee390b3-4203-4a0b-ae58-b423c469b268


https://github.com/user-attachments/assets/db3b2f71-1e9d-47c7-bae1-0bf47e60d5ef


https://github.com/user-attachments/assets/a93334e2-a636-496f-92ae-1c35db3179fb



</p>
</details>

2025-01-13 16:24 UTC, CyberAndrii requested changes

2025-01-13 17:33 UTC, rezkiy37 commented on src/libs/prepareRequestPayload/index.native.ts
> +                        formData.append(key, file);
Done - 9d86ba4.

2025-01-13 23:13 UTC, CyberAndrii commented on src/libs/prepareRequestPayload/index.native.ts
> +                        formData.append(key, file);
Looks good!

2025-01-14 09:40 UTC, rezkiy37 commented
@allgandalf, done 🙂

2025-01-15 12:10 UTC, rezkiy37 commented
@allgandalf, fixed 🙂

2025-01-20 09:28 UTC, rezkiy37 commented
I am going to sync the branch up.

2025-01-21 09:53 UTC, rezkiy37 commented
> sorry, my android is crashing on runtime still testing this 😓

@allgandalf, probably it can help you - https://expensify.slack.com/archives/C01GTK53T8Q/p1737374303845769.

2025-01-22 08:41 UTC, allgandalf requested changes
Thanks for all the hard work here @rezkiy37 , LGTM

2025-01-22 10:00 UTC, rezkiy37 commented
@allgandalf, just to clarify the status because you have **suggested changes** with **LGTM** 🙂 

<img width="638" alt="Screenshot 2025-01-22 at 10 59 27" src="https://github.com/user-attachments/assets/6767dbe9-0045-4955-a237-8617676b3c60" />

2025-01-22 10:02 UTC, allgandalf approved these changes

2025-01-22 20:03 UTC, neil-marcellini requested changes
Great work. I have some questions and suggestions I would like to see resolved before we merge please.

2025-01-22 20:03 UTC, neil-marcellini commented on src/libs/prepareRequestPayload/index.native.ts
> +                return import('@libs/fileDownload/FileUtils').then(({readFileAsync}) =>
Is there a way to resolve circular dependencies so we don't need the dynamic import? If not or it's very hard please explain why, and we can create an issue to clean this up if needed. We don't do this most places in the code so I rather not have this outlier if possible.

2025-01-22 20:03 UTC, neil-marcellini commented on src/types/onyx/Request.ts
> +    /** Whether the request is initiated offline */
Yes obviously. Please also explain why we have this field, how it's meant to be used.

2025-01-23 17:56 UTC, rezkiy37 commented
I am working to address comments.

2025-01-24 12:33 UTC, rezkiy37 commented on src/types/onyx/Request.ts
> +    /** Whether the request is initiated offline */
Done - c21920e821040862237868a1e815ec6f0f92f96b.

2025-01-24 12:33 UTC, rezkiy37 commented on src/libs/Network/SequentialQueue.ts
> +    const updatedRequest = {...newRequest, initiatedOffline: isOffline()};
Done - 28efbe4dcba3462265fc0df964106e729ab5ef98.

2025-01-24 12:33 UTC, rezkiy37 commented on src/libs/prepareRequestPayload/index.native.ts
Done - faa122a.

2025-01-24 12:33 UTC, rezkiy37 commented on src/libs/prepareRequestPayload/index.native.ts
> +                return import('@libs/fileDownload/FileUtils').then(({readFileAsync}) =>
Still working on it.

2025-01-24 16:02 UTC, rezkiy37 commented
@neil-marcellini, all comments have been addressed 🙂 

cc @allgandalf

2025-01-24 17:32 UTC, neil-marcellini submitted a review, later dismissed
Thanks for the updates, good to go

2025-01-24 17:35 UTC, neil-marcellini commented
Oh, actually unit tests are failing @rezkiy37

2025-01-28 11:24 UTC, rezkiy37 commented
@allgandalf, done 🙂

2025-01-28 16:06 UTC, neil-marcellini requested changes
I'm not really understanding why you changed the assertions for one of the tests, it seems wrong. Also, I see that you mocked the fileDownload util in almost all of the tests, then had to change many files to use named imports, I assume because this PR now touches those files.

Instead, can we set up a single global mock for all the tests, and then the PR won't have to change so many files? Please let me know if you have different ideas.

2025-01-28 16:06 UTC, neil-marcellini commented on tests/actions/ReportTest.ts
> +        TestHelper.expectAPICommandToHaveBeenCalled(WRITE_COMMANDS.DELETE_COMMENT, 0);
These assertions are in violation of the goal of the test "it('should send DeleteComment request and remove UpdateComment accordingly'". Please revert the changes here and figure out why it's broken.

2025-01-29 13:48 UTC, rezkiy37 commented on tests/actions/ReportTest.ts
> +        TestHelper.expectAPICommandToHaveBeenCalled(WRITE_COMMANDS.DELETE_COMMENT, 0);
Fixed.

2025-01-29 17:48 UTC, neil-marcellini approved these changes
Thanks for the fixes, I think it's good to go.

2025-01-29 17:49 UTC, merged

2025-01-29 17:58 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2026-01-07 03:33 UTC, dukenv0307 commented on src/libs/prepareRequestPayload/index.native.ts
> +                return readFileAsync(source, path, () => {}).then((file) => {
Coming from https://github.com/Expensify/App/issues/76975, we should use the actual file name if available, otherwise fall back to extracting from path/uri