[Internal QA]: Add additional navigation for not existing export
Expensify/App pull request #54433
Opened 2024-12-20 18:48 UTC by narefyev91

### Explanation of Change

Since you accessed the accounting integration settings from the card-level export, the nav structure tries to bring you back to the card-level export selection page. However, that page is no longer supported based on the new integration settings. I suggest that where you landed on this "no accounts found" page previously when going back, you instead land directly on the card details page, with the card-level export row gone.-->

### Fixed Issues

$ https://github.com/Expensify/App/issues/54371
PROPOSAL:

### Tests
1. Set non-reimbursable exports to something that supports card-level export settings (like QBO credit cards). go to the card details page of an assign card.
2. Click the card export row.
3. Click the link in the subheader to go to the accounting integration settings.
4. Change the non-reimbursable exports to something that doesn't support card-level export settings (like QBO vendor bills).
5. Click back couple of times.
6. Verify that user lands directly to card details page
7. Verify that Export menu item is not shown

- [x] Verify that no errors appear in the JS console

### Offline tests
No changes

### QA Steps
1. Set non-reimbursable exports to something that supports card-level export settings (like QBO credit cards). go to the card details page of an assign card.
2. Click the card export row.
3. Click the link in the subheader to go to the accounting integration settings.
4. Change the non-reimbursable exports to something that doesn't support card-level export settings (like QBO vendor bills).
5. Click back couple of times.
6. Verify that user lands directly to card details page
7. Verify that Export menu item is not shown

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving component [...]

2024-12-20 18:48 UTC, narefyev91 commented
I added logic using backTo to just one connection. There are some other places which should be changed for other connections to use correct go back logic. Also needs to add util function which will return true/false based on check for valid export account (which is available for company card details page menu item). I will be back on Monday 30th and will add all these changes. For now will leave it draft

2025-01-03 10:44 UTC, dukenv0307 approved these changes
LGTM

2025-01-06 15:53 UTC, mountiny requested changes

2025-01-06 15:56 UTC, narefyev91 commented on src/pages/workspace/accounting/intacct/export/SageIntacctExportPage.tsx
> +    const isConnectionShouldBeRemovedFromCompanyCard = exportConfig?.reimbursable === CONST.SAGE_INTACCT_REIMBURSABLE_EXPENSE_TYPE.EXPENSE_REPORT && backTo;
In menu item for company card - we have a row name Export %connection name%. And in some cases we should not show that row if connection is not supported. Sorry did not find a good name for variable

2025-01-06 15:57 UTC, narefyev91 commented on src/pages/workspace/accounting/intacct/export/SageIntacctExportPage.tsx
> +            onBackButtonPress={isConnectionShouldBeRemovedFromCompanyCard ? () => Navigation.navigate(backTo) : undefined}
It will be default Navigation.goback()

2025-01-06 16:24 UTC, mountiny commented on src/pages/workspace/accounting/netsuite/export/NetSuiteExportConfigurationPage.tsx
> +    const isConnectionShouldBeRemovedFromCompanyCard =
Maybe lets name it more specifically to what it will cause/ do. It would be great to also add some comment explaining why we need it
```suggestion
    const shouldgoBackToSpecificRoute =
```

2025-01-06 16:39 UTC, mountiny commented on src/pages/workspace/accounting/netsuite/export/NetSuiteExportConfigurationPage.tsx
> +    const isConnectionShouldBeRemovedFromCompanyCard =
I discussed with @narefyev91 these changes, and he is out until Friday. These are NAB changes but we should make them for better DX. We can add it to some future fixes to the flow and not hold in this

2025-01-06 17:05 UTC, mountiny approved these changes

2025-01-06 17:06 UTC, merged

2025-01-06 17:15 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2025-01-07 21:35 UTC, joekaufmanexpensify commented
Not fully working. After changing from credit card > vendor bills with QBO, you land on the "hmm not here" page when navigating backward instead of the card details page. 


https://github.com/user-attachments/assets/74228f3a-5147-445e-a4c6-9e89c46f98c7

2025-01-07 21:36 UTC, joekaufmanexpensify commented
Checking off on deploy checklist as this is NAB

2025-01-07 21:53 UTC, mountiny commented
@narefyev91 something to look into when you back

2025-03-10 16:40 UTC, mananjadhav commented on src/pages/workspace/companyCards/WorkspaceCompanyCardAccountSelectCardPage.tsx
> +    const exportMenuItem = getExportMenuItem(connectedIntegration, policyID, translate, policy, card, backTo);
We should've passed the active route here, which we fixed it [here](https://github.com/Expensify/App/issues/55752)