Resubmit contacts import module
Expensify/App pull request #54459
Opened 2024-12-23 09:26 UTC by perunt

### Explanation of Change

### Fixed Issues

$ https://github.com/Expensify/App/issues/47938
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2025-01-07 10:35 UTC, staszekscp commented
Hey! I've created [a PR](https://github.com/Expensify/Mobile-Expensify/pull/13347) with adjustments so everything works fine with HybridApp

2025-01-07 11:37 UTC, mateuuszzzzz commented
Hi! @perunt what's your Xcode version locally?

2025-01-07 14:02 UTC, mateuuszzzzz commented
Nevertheless I think this is not a serious issue and we can proceed further with this PR 😅

People experiencing issues with the Swift compiler can try downgrading their Xcode version or using a physical device if available.

2025-01-07 20:27 UTC, blimpich submitted a review, later dismissed
Tentatively approving, seems like we need to confirm first that this doesn't break hybrid app for simulator's as per above comments.

2025-01-07 20:34 UTC, blimpich commented
Also I think we need to merge main due to [xcode being bumped](https://github.com/Expensify/App/pull/54424), which is why the validate github actions check is failing.

2025-01-10 15:28 UTC, perunt commented
I'm still dealing with Android errors after bumping RN. I'll ping you once it's done

2025-01-13 21:25 UTC, blimpich commented
> I'm not sure about the lint error `Do not default string IDs to any value` since I didn't work on that area. I see we're still using '-1' as the ID in the codebase, so I assume it should be migrated in a separate PR?
> 
> Apart from this, everything works on my end. As before, I didn't test the Hybrid App because I don't have access to it

Ah this is from a new eslint rule we made. See announcement [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1736530661470629). Its unrelated because we're trying to tackle the changes incrementally instead of doing it all at once in a big PR. So if you touch a file (ex: `src/pages/iou/request/MoneyRequestParticipantsSelector.tsx`) then the linter asks you to update the rest of the file.

I'm fine with ignoring it for this PR, its big and complicated enough already that I don't want to add that to the list of things this PR changes, but for future reference we probably want to update those linter issues as we encounter them.

2025-01-13 21:31 UTC, blimpich submitted a review, later dismissed
Approving, checking with hybrid app engineers before merging: https://expensify.slack.com/archives/C04878MDF34/p1736803862458899?thread_ts=1736210982.318679&cid=C04878MDF34

2025-01-15 10:25 UTC, DylanDylann commented
I verified that it works well on Hybrid Android App (I am getting some problems while building Hybrid IOS App, will try to give an update in the end of day)

https://github.com/user-attachments/assets/cddf030c-1fc2-4c3a-abfa-183cb531d245

2025-01-15 10:25 UTC, DylanDylann commented
@perunt Could you please resolve conflict?

2025-01-15 14:25 UTC, mateuuszzzzz commented
> I verified that it works well on the Hybrid Android App (I am getting some problems while building a Hybrid IOS App, will try to give an update at the end of the day)
> 
>  Screen.Recording.2025-01-15.at.17.23.26.mov 
>  Screen.Recording.2025-01-15.at.17.30.14.mov

@DylanDylann what kind of problems?

2025-01-15 14:33 UTC, DylanDylann commented
@mateuuszzzzz No problem on Android, the IOS build failed because of this error 
 
<img width="1405" alt="Screenshot 2025-01-15 at 21 33 26" src="https://github.com/user-attachments/assets/0506d2cb-7c32-42d0-9d3f-4dc74903d987" />

2025-01-15 14:48 UTC, mateuuszzzzz commented
> @mateuuszzzzz No problem on Android, the IOS build failed because of this error
> 
> <img alt="Screenshot 2025-01-15 at 21 33 26" width="1405" src="https://private-user-images.githubusercontent.com/141406735/403456842-0506d2cb-7c32-42d0-9d3f-4dc74903d987.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NTE5MjcsIm5iZiI6MTczNjk1MTYyNywicGF0aCI6Ii8xNDE0MDY3MzUvNDAzNDU2ODQyLTA1MDZkMmNiLTdjMzItNDJkMC05ZDNmLTRkYzc0OTAzZDk4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNVQxNDMzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjVmNWQyOTgwN2RkZTFlMjI2NDc3M2I0ZTZiMTBlYjBjYmNmZmRmOGI5OTdmZmU0N2FjNTczZTI0NzMwZmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.17D-tgdwwqaacgP6N1l2Fvx4_Do_HlrRtil_s81UyXE">

Could you expand details of `SwiftCompile` error?

2025-01-15 17:11 UTC, mateuuszzzzz commented
Sorry, I meant this block 😅
![image](https://github.com/user-attachments/assets/871b5086-d3c5-4a43-8d4b-e30053ea776c)

2025-01-15 18:11 UTC, DylanDylann commented
## First error

```
CompileC /Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ContactsModule.build/Objects-normal/x86_64/HybridContactsModuleSpecSwift.o /Users/dhd/Infratech/Expensify/App/modules/ContactsNitroModule/nitrogen/generated/ios/c++/HybridContactsModuleSpecSwift.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'ContactsModule' from project 'Pods')
    cd /Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -ivfsstatcache /Users/dhd/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator17.2-21C52-4f2951bfe8f3cd53c99228b0131e163e.sdkstatcache -target x86_64-apple-ios15.1-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -std\=c++20 -stdlib\=libc++ -fmodules -gmodules -fmodules-cache-path\=/Users/dhd/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/dhd/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -fmodule-name\=ContactsModule -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -DFOLLY_NO_CONFIG -DFOLLY_CFG_NO_COROUTINES -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -fvisibility-inlines-hidden -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -fprofile-instr-generate -fcoverage-mapping -index-store-path /Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Index.noindex/DataStore -iquote /Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ContactsModule.build/ContactsModule-generated-files.hmap -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ContactsModule.build/ContactsModule-own-target-headers.hmap -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ContactsModule.build/ContactsModule-all-non-framework-target-headers.hmap -ivfsoverlay /Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ContactsModule.build/all-product-headers.yaml -iquote /Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ContactsModule.build/ContactsModule-project-headers.hmap -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ContactsModule/include -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ReactCommon/ReactCommon.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ReactCommon/ReactCommon.framework/Headers/react/nativemodule/core -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ReactCommon-Samples/ReactCommon_Samples.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ReactCommon-Samples/ReactCommon_Samples.framework/Headers/platform/ios -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers/react/renderer/components/view/platform/cxx -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-NativeModulesApple/React_NativeModulesApple.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-graphics/React_graphics.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-graphics/React_graphics.framework/Headers/react/renderer/graphics/platform/ios -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public/FBLazyVector -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public/RCTRequired -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public/React-callinvoker -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public/React-runtimeexecutor -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public/React-timing -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public/hermes-engine -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/boost -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Private/Yoga -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/DoubleConversion -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/fmt/include -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-graphics/React_graphics.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-graphics/React_graphics.framework/Headers/react/renderer/graphics/platform/ios -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers/react/renderer/components/view/platform/cxx -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-FabricImage/React_FabricImage.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ReactCommon/ReactCommon.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ReactCommon/ReactCommon.framework/Headers/react/nativemodule/core -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-NativeModulesApple/React_NativeModulesApple.framewo [...]

2025-01-15 18:13 UTC, DylanDylann commented
## First error

```
CompileC /Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ContactsModule.build/Objects-normal/x86_64/HybridContactsModuleSpecSwift.o /Users/dhd/ns/Expensify/App/modules/ContactsNitroModule/nitrogen/generated/ios/c++/HybridContactsModuleSpecSwift.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'ContactsModule' from project 'Pods')
    cd /Users/dhd/ns/Expensify/App/Mobile-Expensify/iOS/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -ivfsstatcache /Users/dhd/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator17.2-21C52-4f2951bfe8f3cd53c99228b0131e163e.sdkstatcache -target x86_64-apple-ios15.1-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -std\=c++20 -stdlib\=libc++ -fmodules -gmodules -fmodules-cache-path\=/Users/dhd/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/dhd/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -fmodule-name\=ContactsModule -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -DFOLLY_NO_CONFIG -DFOLLY_CFG_NO_COROUTINES -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.2.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -fvisibility-inlines-hidden -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -fprofile-instr-generate -fcoverage-mapping -index-store-path /Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Index.noindex/DataStore -iquote /Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ContactsModule.build/ContactsModule-generated-files.hmap -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ContactsModule.build/ContactsModule-own-target-headers.hmap -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ContactsModule.build/ContactsModule-all-non-framework-target-headers.hmap -ivfsoverlay /Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ContactsModule.build/all-product-headers.yaml -iquote /Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/ContactsModule.build/ContactsModule-project-headers.hmap -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ContactsModule/include -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ReactCommon/ReactCommon.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ReactCommon/ReactCommon.framework/Headers/react/nativemodule/core -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ReactCommon-Samples/ReactCommon_Samples.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ReactCommon-Samples/ReactCommon_Samples.framework/Headers/platform/ios -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers/react/renderer/components/view/platform/cxx -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-NativeModulesApple/React_NativeModulesApple.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-graphics/React_graphics.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-graphics/React_graphics.framework/Headers/react/renderer/graphics/platform/ios -I/Users/dhd/ns/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public -I/Users/dhd/ns/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public/FBLazyVector -I/Users/dhd/ns/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public/RCTRequired -I/Users/dhd/ns/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public/React-callinvoker -I/Users/dhd/ns/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public/React-runtimeexecutor -I/Users/dhd/ns/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public/React-timing -I/Users/dhd/ns/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Public/hermes-engine -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/boost -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/Headers/Private/Yoga -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/DoubleConversion -I/Users/dhd/Infratech/Expensify/App/Mobile-Expensify/iOS/Pods/fmt/include -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-graphics/React_graphics.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-graphics/React_graphics.framework/Headers/react/renderer/graphics/platform/ios -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-Fabric/React_Fabric.framework/Headers/react/renderer/components/view/platform/cxx -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-FabricImage/React_FabricImage.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ReactCommon/ReactCommon.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/ReactCommon/ReactCommon.framework/Headers/react/nativemodule/core -I/Users/dhd/Library/Developer/Xcode/DerivedData/Expensify-estpnbngqenpigfyvubpsrvdautm/Build/Products/Debug-iphonesimulator/React-NativeModulesApple/React_NativeModulesApple.framework/Headers -I/Users/dhd/Library/Developer/Xcode/DerivedData/Exp [...]

2025-01-15 19:47 UTC, Julesssss commented
I think this may be due to our workflow nmv version. I think we are good on staging but not prod yet (where I think the workflow runs).

```
npm error notsup Required: {"node":"20.18.1","npm":"10.8.2"}
npm error notsup Actual:   {"npm":"10.8.2","node":"v20.18.0"}
```

2025-01-16 11:55 UTC, perunt commented
@DylanDylann, the code is up to date
@blimpich, do we have an ETA on when our team will be able to run the Hybrid app? If it doesn't happen soon, I would like to schedule a debug session with Dylan

2025-01-16 17:30 UTC, blimpich commented
> @DylanDylann, the code is up to date @blimpich, do we have an ETA on when our team will be able to run the Hybrid app? If it doesn't happen soon, I would like to schedule a debug session with Dylan

I don't have an ETA but I think we're actually quite close. See [this issue](https://github.com/Expensify/App/issues/54321). We have a Github team for Margelo that, once you're added to it, should give you access. We just need to increase our seat-count with Github before adding you to the team. I don't know how long that will take but I assume not too long.

2025-01-17 12:43 UTC, perunt commented
@blimpich got it, thanks for the update
@DylanDylann , may I ask you to run it again? And if it fails, could you share a screenshot of the files where it happens, like the `HybridContactsModuleSpecSwift` file?

2025-01-20 14:59 UTC, DylanDylann commented
Let's me check again

2025-01-21 11:38 UTC, DylanDylann commented
@perunt I built again and get this error

<img width="1385" alt="Screenshot 2025-01-21 at 18 38 15" src="https://github.com/user-attachments/assets/f1e4d742-eec7-430a-8042-12a004deeefb" />

2025-01-24 20:25 UTC, blimpich commented
@perunt are you able to build the hybrid app and repro the errors that @DylanDylann is seeing now?

2025-01-28 11:49 UTC, perunt commented
Nice! Yes, I have access to it. Thank you so much guys—I really appreciate your efforts 💪🏻
I'll get back to this later this evening or tomorrow and fix the issue with NitroModule and the Hybrid App

2025-02-04 21:49 UTC, blimpich commented
@perunt any update here? Are you able to fix the issues?

2025-02-05 21:03 UTC, perunt commented
Hey, sorry, no updates yet. I'm currently fixing the E2E pipeline, and once that's done, I'll be able to take a look at this

2025-02-13 18:34 UTC, blimpich commented
@perunt do you have an ETA on when you'll be able to get this over the finish line?

2025-02-18 07:35 UTC, DylanDylann commented
@perunt Kindly bump

2025-02-20 21:34 UTC, blimpich commented
> @DylanDylann @blimpich I was able to run both iOS and Android without any issues. Occasionally, I get an `unexpected error creating chat` but the builds assembled fine can you give it a try?

Sweet! Looks like we have failing linting checks though? Can we fix those, then move on to a final (🤞) review by @DylanDylann?

2025-02-21 14:21 UTC, perunt commented
hey, @DylanDylann, can you try it on your end? I assume they've changed something in the Hybrid app setup. If you encounter any issues, I'd be happy to help!

2025-02-25 02:27 UTC, roryabraham requested changes
There's a ton of boilerplate to add a new native module, so I'm wondering if rather than adding a single-purpose `ContactsNitroModule`, we can just call it something more generic like `ExpensifyNativeUtils`? That way, if we want to add some other simple native code in the future, we can just add a few functions rather than going through all the boilerplate of adding a new native module?

2025-02-25 02:27 UTC, roryabraham commented on modules/ContactsNitroModule/package.json
> +{
Why do we need a whole separate subproject/workspace for our nitro module?

2025-02-25 02:27 UTC, roryabraham commented on modules/ContactsNitroModule/package.json
> +    "typecheck": "tsc --noEmit",
typecheck and lint seem like great examples of things that should inherit configs from the parent project. Still not at all convinced that adding a separate subproject is necessary or good in this case.

2025-02-25 02:27 UTC, roryabraham commented on modules/ContactsNitroModule/package.json
> +    "specs-debug": "bun run --filter=\"**\" typescript && bun nitro-codegen --logLevel=\"debug\"",
Let's not introduce bun here. I get that it's fast and developer friendly, but can we just use `npx` instead since that's what we use everywhere else?

2025-02-25 02:27 UTC, roryabraham commented on modules/ContactsNitroModule/src/ContactsModule.nitro.ts
> +interface StringHolder {
Is using `interface` a requirement of nitro modules? We are standardized on `type` everywhere else

2025-02-25 02:27 UTC, roryabraham commented on modules/ContactsNitroModule/src/index.ts
> +export const ContactsNitroModule =
Now, in here I think it would be reasonable to have a setup where this main module is just called `ExpensifyNativeUtils`, and composes more modularized pieces of code (like the contacts module) into multiple hybrid objects.

Then adding new kinds of native modules would be done here by:

- adding `MyNewNativeModule.nitro`
- running `nitrogen` to produce the native stubs
- implementing the native code
- registering the new HybridObject here

skipping all the boilerplate of adding a new podspec, build.gradle, etc...

2025-02-25 02:27 UTC, roryabraham commented on modules/ContactsNitroModule/tsconfig.json
> +{
We should not need to introduce a new ts config here? can we just use the tsconfig from the root project?

2025-02-26 09:40 UTC, DylanDylann commented
@perunt Could you please check the above comments first? It has been a long time since my last reviewing, I will give my review soon.

2025-02-26 09:41 UTC, DylanDylann commented
@perunt Could you please check the above comments first? It has been a long time since my last reviewing, I will give my review soon.

2025-02-28 20:09 UTC, perunt commented
Actually, all of this boilerplate will only be added once, and any future modules will follow the same structure. Once we have a second module planned, we'll set up a more structured folder organization.

That said, I can streamline the current structure to keep things tidy. I'll address these improvements when I return from OOO on March 9

2025-03-18 20:10 UTC, perunt commented
I'm on it now and aiming to wrap it up by mid-next week, but I'll do my best to finish by the end of this week while staying on top of other PRs

2025-03-26 10:54 UTC, perunt commented on modules/ContactsNitroModule/tsconfig.json
> +{
You're right
I just cleaned it

2025-03-26 16:31 UTC, perunt commented on modules/ContactsNitroModule/src/index.ts
> +export const ContactsNitroModule =
I’ve changed the approach a bit - added a draft empty module and set up a structure that makes it easy to add more modules like you described. The only thing I’d tweak is the name. Maybe call it `ExpensifyNitroUtils` or just `NitroUtils` instead of `ExpensifyNativeUtils` wdyt?

2025-03-26 17:24 UTC, roryabraham commented on modules/ExpensifyNativeUtils/android/build.gradle
> +    sourceCompatibility JavaVersion.VERSION_1_8
Any reason we're using Java 8 rather than a newer version?

2025-03-26 17:58 UTC, Julesssss commented on modules/ExpensifyNativeUtils/android/build.gradle
> +    sourceCompatibility JavaVersion.VERSION_1_8
1.8 is pretty stable and I don't think bumping would solve any issue currently. Our libraires also target 1.8 (lower in some cases)

2025-03-31 21:28 UTC, roryabraham commented on modules/ExpensifyNativeUtils/android/build.gradle
> +    sourceCompatibility JavaVersion.VERSION_1_8
well I don't feel that strongly, but just TBC this is a new file, not an existing file. I feel like if it works out of the box with a newer java version, we might as well use that instead of Java 8?

2025-03-31 21:30 UTC, roryabraham commented
@perunt what's the status here? There are a number of failing tests

2025-04-01 13:26 UTC, perunt commented on ios/Podfile.lock
> +  - AirshipServiceExtension (18.14.2)
No, it wasn't intentional. I'll make sure not to bump any other dependencies

2025-04-01 13:34 UTC, perunt commented
> @perunt what's the status here? There are a number of failing tests

Yes, there are a bunch of errors in the tests and ReportUtils, which weren’t touched in this PR. Same with Storybook. I’m working on resolving those. Apart from that, the code is ready, I had some issues with migrating to the latest Nitro on Android, but everything's settled now.
I’ll address the remaining errors later today

2025-04-02 12:13 UTC, perunt commented on modules/ExpensifyNativeUtils/android/build.gradle
> +    sourceCompatibility JavaVersion.VERSION_1_8
Yeah, Java 8 is commonly used and reliable. Meanwhile I checked and RN recommends the 17th version, so I bumped it to that

2025-04-02 12:22 UTC, perunt commented
@roryabraham all green. I’ve cleaned up the boilerplate and slightly changed the structure to make it easier to add a new module. Meanwhile it reuses all config from the root, so it should be good to go now

2025-04-07 19:55 UTC, blimpich submitted a review, later dismissed
LGTM. @roryabraham can you take another look?

We need to resolve merge conflicts but with a PR this big lets just get consensus and then once that is reached we'll make sure to approve and merge right after Taras resolves the most recent round of merge conflicts

2025-04-07 19:56 UTC, blimpich commented
@DylanDylann can you go through the checklist?

2025-04-08 11:00 UTC, DylanDylann commented
Back to this PR today

2025-04-09 08:08 UTC, perunt commented on ios/NewExpensify.xcodeproj/xcshareddata/xcschemes/New Expensify.xcscheme
> +      buildConfiguration = "DebugDevelopment"
No, it was probably messed up in one of those 50+ files during the changes. Thanks for pointing it out!

2025-04-09 08:13 UTC, perunt commented
> @perunt Could you build Hybrid App successfully?

It worked for me. Try using https://github.com/Expensify/Mobile-Expensify/pull/13516 for Mobile-Expensify. But in any case, Android should work even without that PR

2025-04-09 09:29 UTC, DylanDylann commented on src/libs/OptionsListUtils.ts
> +        firstName: (detail?.firstName || ('firstName' in participant ? participant.firstName : '')) ?? '',
```suggestion
        firstName: (detail?.firstName || (participant?.firstName ?? ''))
```

2025-04-09 09:29 UTC, DylanDylann commented on src/libs/OptionsListUtils.ts
> +                source: ('avatar' in participant ? participant.avatar : detail?.avatar) ?? FallbackAvatar,
same above

2025-04-09 22:06 UTC, roryabraham commented on src/CONST.ts
> +    DEVICE_CONTACT: {
I feel like this is duplicated from `modules/ExpensifyNitroUtils/specs/ContactsModule.nitro.ts` - could we just use that as the source of truth?

2025-04-09 22:06 UTC, roryabraham commented on modules/ExpensifyNitroUtils/src/specs/ContactsModule.nitro.ts
> +    getAll(keys: ContactFields[]): Promise<Contact[]>;
I see this is only used once, so you could simplify things by just hard-coding the fields we query to `[FIRST_NAME, LAST_NAME, PHONE_NUMBERS, EMAIL_ADDRESSES, IMAGE_DATA]` since those are the only fields we deep to be using.

2025-04-14 18:44 UTC, blimpich commented
@perunt any update here?

2025-04-16 12:58 UTC, perunt commented on .eslintignore
> +modules/**
it's a bit leftover. It's a bit leftover.
Since we reuse everything from the root and don't use a separate formatting system I need to change it so it ignores only autogenerated nitrogen files

2025-04-21 11:07 UTC, perunt commented on modules/ExpensifyNitroUtils/android/src/main/java/com/margelo/nitro/utils/UtilsModulePackage.java
Make sense. I'll make sure to use proper naming

2025-04-21 11:11 UTC, perunt commented on modules/ExpensifyNitroUtils/android/src/main/java/com/margelo/nitro/utils/contacts/HybridContactsModule.kt
> +    private var estimatedMemorySize: Long = 0
JS runtime does not know the actual memory size of a Hybrid Object. So we declare their memory manually.
It helps to account for any external heap allocations.
So now we can delete these objects sooner by the JS garbage collector preventing memory pressure or frequent garbage collector calls

2025-04-21 12:04 UTC, perunt commented on modules/ExpensifyNitroUtils/UtilsModule.podspec
Yes, I'll rename it so it represents Expensify naming

2025-04-21 12:15 UTC, perunt commented on modules/ExpensifyNitroUtils/android/src/main/java/com/margelo/nitro/utils/contacts/HybridContactsModule.kt
> +        return if (currentActivity != null) {
Yeah, idiomatic Kotlin can sometimes be confusing for developers coming from other languages. I'll change it to improve readability

2025-04-21 12:22 UTC, perunt commented on modules/ExpensifyNitroUtils/android/src/main/java/com/margelo/nitro/utils/contacts/HybridContactsModule.kt
> +        const val REQUIRED_PERMISSION = Manifest.permission.READ_CONTACTS
But it's only one permission currently. Are you suggesting this change to avoid wrapping the permission in an array when requestPermissions is called? I'll change it

2025-04-21 12:23 UTC, perunt commented on modules/ExpensifyNitroUtils/android/src/main/java/com/margelo/nitro/utils/contacts/HybridContactsModule.kt
> +        val result = ContextCompat.checkSelfPermission(context, Manifest.permission.READ_CONTACTS) == PackageManager.PERMISSION_GRANTED
👍🏻

2025-04-21 12:35 UTC, perunt commented on modules/ExpensifyNitroUtils/android/src/main/java/com/margelo/nitro/utils/contacts/HybridContactsModule.kt
> +                val sortOrder = "${ContactsContract.Data.CONTACT_ID} ASC"
We sort it by `CONTACT_ID` because it needs all data pieces belonging to one contact to appear together in the query results. Since Android stores contact details (name, phone, email) as separate database rows, this sorting ensures all related rows appear consecutively. So we can build a complete contact profile before moving to the next person, which wouldn't work if sorted differently. We can change sorting here, but then it needs to be adjusted everywhere

2025-04-21 12:39 UTC, perunt commented on modules/ExpensifyNitroUtils/android/src/main/java/com/margelo/nitro/utils/contacts/HybridContactsModule.kt
> +                    ContactsContract.Data.MIMETYPE,
👍🏻

2025-04-21 12:49 UTC, perunt commented on modules/ExpensifyNitroUtils/src/specs/ContactsModule.nitro.ts
> +    getAll(keys: ContactFields[]): Promise<Contact[]>;
Do you mean hardcoding fields on the native side? If yes, I don't see much benefit since the implementation already fetches the same amount of fields anyway. If you're referring to trimming the type definition in TS to only include fields we actually use, that makes more sense to me

2025-04-21 13:11 UTC, perunt commented on modules/ExpensifyNitroUtils/android/CMakeLists.txt
> +set (CMAKE_CXX_STANDARD 20)
We're keeping C++20 since it's more stable and well-tested for Android development. C++23 is still relatively new and might introduce compatibility issues

2025-04-22 13:38 UTC, perunt commented on package.json
> +    "lint-changed": "NODE_OPTIONS=--max_old_space_size=8192 eslint --max-warnings=0 --config ./.eslintrc.changed.js $(git diff --diff-filter=AM --name-only origin/main HEAD -- \"*.ts\" \"*.tsx\" \":!
It was added when we had a separate lint file for this module. Removed now

2025-04-22 17:56 UTC, blimpich commented
@DylanDylann can you give this another look?

2025-04-22 21:28 UTC, roryabraham commented on modules/ExpensifyNitroUtils/package.json
> +  "clean": "del-cli android/build node_modules/**/android/build lib",
hmmm yeah I don't think we really support Windows development of NewDot, so we should just use `rm -rf`. Windows users probably have to use wsl anyways

2025-04-22 21:29 UTC, roryabraham commented on modules/ExpensifyNitroUtils/src/specs/ContactsModule.nitro.ts
> +    getAll(keys: ContactFields[]): Promise<Contact[]>;
> If you're referring to trimming the type definition in TS to only include fields we actually use, that makes more sense to me

yeah, that's what I was thinking

2025-04-23 00:18 UTC, roryabraham requested changes
good work, this feels much closer to me

2025-04-23 00:18 UTC, roryabraham commented on src/components/ContactPermissionModal/index.native.tsx
> +function ContactPermissionModal({startPermissionFlow, resetPermissionFlow, onDeny, onGrant}: ContactPermissionModalProps) {
I think we can substantially simplify this implementation:

```diff
diff --git a/src/components/ContactPermissionModal/index.native.tsx b/src/components/ContactPermissionModal/index.native.tsx
index 825c8bc4afb..2c5343974b0 100644
--- a/src/components/ContactPermissionModal/index.native.tsx
+++ b/src/components/ContactPermissionModal/index.native.tsx
@@ -1,4 +1,4 @@
-import React, {useEffect, useState} from 'react';
+import React, {useCallback, useEffect, useState} from 'react';
 import {InteractionManager} from 'react-native';
 import {RESULTS} from 'react-native-permissions';
 import ConfirmModal from '@components/ConfirmModal';
@@ -8,49 +8,41 @@ import useThemeStyles from '@hooks/useThemeStyles';
 import {getContactPermission} from '@libs/ContactPermission';
 import type {ContactPermissionModalProps} from './types';
 
-function ContactPermissionModal({startPermissionFlow, resetPermissionFlow, onDeny, onGrant}: ContactPermissionModalProps) {
+function ContactPermissionModal({onGrant}: ContactPermissionModalProps) {
     const [isModalVisible, setIsModalVisible] = useState(false);
 
     const styles = useThemeStyles();
     const {translate} = useLocalize();
 
     useEffect(() => {
-        if (!startPermissionFlow) {
-            return;
-        }
         getContactPermission().then((status) => {
             if (status === RESULTS.GRANTED || status === RESULTS.LIMITED) {
-                return onGrant();
+                onGrant();
+                return;
             }
             if (status === RESULTS.BLOCKED) {
                 return;
             }
             setIsModalVisible(true);
         });
-        // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps -- We only want to run this effect when startPermissionFlow changes
-    }, [startPermissionFlow]);
+        // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps -- We only want to run this effect on mount
+    }, []);
 
-    const handleGrantPermission = () => {
+    const grantPermission = useCallback(() => {
         setIsModalVisible(false);
         InteractionManager.runAfterInteractions(onGrant);
-    };
-
-    const handleDenyPermission = () => {
-        onDeny(RESULTS.DENIED);
-        setIsModalVisible(false);
-    };
+    }, [onGrant]);
 
-    const handleCloseModal = () => {
+    const close = useCallback(() => {
         setIsModalVisible(false);
-        resetPermissionFlow();
-    };
+    }, []);
 
     return (
         <ConfirmModal
             isVisible={isModalVisible}
-            onConfirm={handleGrantPermission}
-            onCancel={handleDenyPermission}
-            onBackdropPress={handleCloseModal}
+            onConfirm={grantPermission}
+            onCancel={close}
+            onBackdropPress={close}
             confirmText={translate('common.continue')}
             cancelText={translate('common.notNow')}
             prompt={translate('contact.importContactsText')}
diff --git a/src/components/ContactPermissionModal/types.ts b/src/components/ContactPermissionModal/types.ts
index 5c831410656..d8cef3876d1 100644
--- a/src/components/ContactPermissionModal/types.ts
+++ b/src/components/ContactPermissionModal/types.ts
@@ -1,17 +1,6 @@
-import type {PermissionStatus} from 'react-native-permissions';
-
 type ContactPermissionModalProps = {
     /** A callback to call when the permission has been granted */
     onGrant: () => void;
-
-    /** A callback to call when the permission has been denied */
-    onDeny: (permission: PermissionStatus) => void;
-
-    /** Should start the permission flow? */
-    startPermissionFlow: boolean;
-
-    /** Reset the permission flow */
-    resetPermissionFlow: () => void;
 };
 
 export default {};
diff --git a/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx b/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
index ecbac67678a..c70abd23865 100644
--- a/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
+++ b/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
@@ -87,7 +87,6 @@ function MoneyRequestParticipantsSelector({
 }: MoneyRequestParticipantsSelectorProps) {
     const {translate} = useLocalize();
     const styles = useThemeStyles();
-    const [softPermissionModalVisible, setSoftPermissionModalVisible] = useState(false);
     const [contactPermissionState, setContactPermissionState] = useState<PermissionStatus>(RESULTS.UNAVAILABLE);
     const showImportContacts = !(contactPermissionState === RESULTS.GRANTED || contactPermissionState === RESULTS.LIMITED);
     const [searchTerm, debouncedSearchTerm, setSearchTerm] = useDebouncedState('');
@@ -105,7 +104,7 @@ function MoneyRequestParticipantsSelector({
         shouldInitialize: didScreenTransitionEnd,
     });
     const [contacts, setContacts] = useState<Array<SearchOption<PersonalDetails>>>([]);
-    const [textInputAutoFocus, setTextInputAutoFocus] = useState(softPermissionModalVisible);
+    const [textInputAutoFocus, setTextInputAutoFocus] = useState(false);
     const cleanSearchTerm = useMemo(() => debouncedSearchTerm.trim().toLowerCase(), [debouncedSearchTerm]);
     const offlineMessage: string = isOffline ? `${translate('common.youAppearToBeOffline')} ${translate('search.resultsAreLimited')}` : '';
 
@@ -304,12 +303,8 @@ function MoneyRequestParticipantsSelector({
     }, []);
 
     useEffect(() => {
-        setSoftPermissionModalVisible(true);
         getContactPermission().then((status) => {
             setContactPermissionState(status);
-            if (status !== RESULTS.BLOCKED && status !== RESULTS.UNAVAILABLE) {
-                setSoftPermissionModalVisible(true);
-            }
         });
     }, []);
 
@@ -459,12 +454,7 @@ function MoneyRequestParticipantsSelector({
         ) : null;
     }, [showImportContacts, inputHelperText, translate, styles, goToSettings]);
 
-    const handleSoftPermissionDeny = useCallback(() => {
-        setSoftPermissionModalVisible(false);
-    }, []);
-
     const handleSoftPermissionGrant = useCallback(() => {
-        setSoftPermissionModalVisible(false);
         InteractionManager.runAfterInteractions(handleContactImport);
         setTextInputAutoFocus(true);
     }, [handleContactImport]);
@@ -563,14 +553,7 @@ function MoneyRequestParticipantsSelector({
 
     return (
         <>
-            {softPermissionModalVisible && (
-                <ContactPermissionModal
-                    startPermissionFlow={softPermissionModalVisible}
-                    resetPermissionFlow={handleSoftPermissionDeny}
-                    onGrant={handleSoftPermissionGrant}
-                    onDeny={handleSoftPermissionDeny}
-                />
-            )}
+            <ContactPermissionModal onGrant={handleSoftPermissionGrant} />
             <SelectionList
                 onConfirm={handleConfirmSelection}
                 sections={areOptionsInitialized ? sections : CONST.EMPTY_ARRAY}

```

2025-04-23 00:19 UTC, roryabraham commented
Also, it looks like those test builds failed, so we should look into that

2025-04-23 08:11 UTC, perunt commented on modules/ExpensifyNitroUtils/src/specs/ContactsModule.nitro.ts
> +    getAll(keys: ContactFields[]): Promise<Contact[]>;
Got it, I'll trim it

2025-04-23 08:21 UTC, perunt commented on modules/ExpensifyNitroUtils/android/src/main/java/com/margelo/nitro/utils/contacts/HybridContactsModule.kt
> +    private var estimatedMemorySize: Long = 0
It's an optimization, and we can safely return 0 here
If we remove it, it will remain in memory until the JS garbage collector discards it
Though I think it's a great feature that allows us to clean it up earlier, which helps us manage memory more effectively.
It doesn't have to be precise, but the closer the estimate, the better.

2025-04-23 08:28 UTC, perunt commented on modules/ExpensifyNitroUtils/package.json
> +  "clean": "del-cli android/build node_modules/**/android/build lib",
Okay, I'll replace it then

2025-04-23 08:50 UTC, perunt commented on modules/ExpensifyNitroUtils/package.json
> +  "homepage": "https://github.com/mrousavy/nitro#readme",
Setting aside the fact that it's Marc's private page, it's still a Nitro module instruction. Maybe it would be better to replace it with a proper documentation page?

2025-04-23 08:51 UTC, perunt commented on modules/ExpensifyNitroUtils/package.json
> +  "eslintIgnore": [ "lib/" ]
👍🏻

2025-04-23 08:51 UTC, perunt commented on modules/ExpensifyNitroUtils/package.json
> +  "author": "Marc Rousavy <me@mrousavy.com> (https://github.com/mrousavy)",
👍🏻

2025-04-23 08:51 UTC, perunt commented on modules/ExpensifyNitroUtils/package.json
> +  "lint": "eslint \"**/*.{js,ts,tsx}\" --fix",
👍🏻

2025-04-23 08:51 UTC, perunt commented on react-native.config.js
> +const pak = require('./modules/ExpensifyNitroUtils/package.json');
👍🏻

2025-04-23 08:55 UTC, perunt commented on src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
> +    const [softPermissionModalVisible, setSoftPermissionModalVisible] = useState(false);
"Soft permission" refers to an app-controlled dialog that appears before triggering the actual system permission request. 
It's called "soft" because it gives users context about why contact access is needed before showing the system's "hard" permission dialog. We use it for location and some other stuff

2025-04-23 08:58 UTC, perunt commented on src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
> +    const handleContactImport = useCallback(() => {
renamed to `importAndSaveContacts`

2025-04-23 10:23 UTC, perunt commented on modules/ExpensifyNitroUtils/package.json
> +  "author": "Marc Rousavy <me@mrousavy.com> (https://github.com/mrousavy)",
The author field is a required option here. I can put Expensify there

2025-04-23 10:39 UTC, perunt commented on src/components/ContactPermissionModal/index.native.tsx
> +function ContactPermissionModal({startPermissionFlow, resetPermissionFlow, onDeny, onGrant}: ContactPermissionModalProps) {
This approach is generally the same as the one we use in the app, so we’ll probably need to update it everywhere later

Hmm, but wait a minute, it looks like you completely removed `startPermissionFlow`.
Are you planning to remove it entirely, or just move it higher up in the component where it's used?
Just curious - was this generated by some kind of AI helper checker?

2025-04-23 10:40 UTC, perunt commented on src/components/ContactPermissionModal/index.native.tsx
> +function ContactPermissionModal({startPermissionFlow, resetPermissionFlow, onDeny, onGrant}: ContactPermissionModalProps) {
This approach is generally the same as the one we use in the app, so we’ll probably need to update it everywhere later

Hmm, but wait a minute, it looks like you completely removed startPermissionFlow.
Are you planning to remove it entirely, or just move it higher up in the component where it's used?
Also, it doesn't handle changing permissions anymore.
Just curious - was this generated by some kind of AI helper checker?

2025-04-23 11:37 UTC, perunt commented on src/components/ContactPermissionModal/index.native.tsx
> +function ContactPermissionModal({startPermissionFlow, resetPermissionFlow, onDeny, onGrant}: ContactPermissionModalProps) {
I mean, if I were you, I'd use some. You’ve got tons of PRs to review every day 😄

2025-04-23 13:14 UTC, perunt commented on package.json
> +    "modules/ExpensifyNitroUtils"
This module was the first one added to that folder, so I initially decided to set it up as a separate workspace to encapsulate it. But now I see we're using a slightly different approach, so I’ll update it to follow the same pattern as the other libraries

2025-04-23 18:13 UTC, blimpich commented
```
Error: could not build module 'NitroModules'
#include <NitroModules/JSIConverter.hpp>
         ^
Error: could not build Objective-C module 'ExpensifyNitroUtils'
```

Hmm, seems like the iOS build failed with this error. @perunt could you take a look and see why this might be? The GH says that the Android build also failed but looking at the workflow it looks like it actually built fine.

2025-04-24 10:17 UTC, DylanDylann commented on ios/Podfile.lock
> +    - Yoga
```suggestion
```

It seems it is created automatically with the old name. I think we can remove it now

2025-04-24 10:47 UTC, DylanDylann commented on src/libs/ContactImport/index.native.tsx
> +import {CONTACT_FIELDS} from '@expensify/nitro-utils/src/specs/ContactsModule.nitro';
Could we move CONTACT_FIELDS defination to the modules/ExpensifyNitroUtils/src/index.ts file? Then we don't need to import from the deep file in the module

2025-04-24 10:47 UTC, DylanDylann commented on src/libs/ContactImport/index.native.tsx
> +import {CONTACT_FIELDS} from '@expensify/nitro-utils/src/specs/ContactsModule.nitro';
If do that we also should remove `"@expensify/nitro-utils/*": ["modules/ExpensifyNitroUtils/*"]` line in tsconfig.json

2025-04-24 11:25 UTC, DylanDylann commented on src/libs/ContactImport/index.native.tsx
> +        }));
It will be better to add a catch block here

```
.catch((error) => {
+            console.error('Error importing contacts:', error);
+            return {
+                contactList: [],
+                permissionStatus,
+            };
+        });
```

2025-04-24 11:25 UTC, DylanDylann commented on modules/ExpensifyNitroUtils/ExpensifyNitroUtils.podspec
> +  s.platforms    = { :ios => min_ios_version_supported }
is min_ios_version_supported defined automatically somewhere?

2025-04-24 11:25 UTC, DylanDylann commented on modules/ExpensifyNitroUtils/src/specs/ContactsModule.nitro.ts
> +type ContactFields = 'FIRST_NAME' | 'LAST_NAME' | 'PHONE_NUMBERS' | 'EMAIL_ADDRESSES' | 'IMAGE_DATA';
```suggestion
type ContactFields = keyof typeof CONTACT_FIELDS;
```

2025-04-24 11:26 UTC, DylanDylann commented on src/libs/ContactImport/index.native.tsx
> +import {CONTACT_FIELDS} from '@expensify/nitro-utils/src/specs/ContactsModule.nitro';
Or we still define CONTACT_FIELDS in ContactsModule.nitro but we export it to outside of module in the  index.ts file

2025-04-24 11:35 UTC, DylanDylann commented on src/components/ContactPermissionModal/index.native.tsx
> +                return;
Should we call onDeny here?

2025-04-24 21:03 UTC, roryabraham commented on src/components/ContactPermissionModal/index.native.tsx
> +function ContactPermissionModal({startPermissionFlow, resetPermissionFlow, onDeny, onGrant}: ContactPermissionModalProps) {
I didn't use any AI to generate this diff - I created it manually (although I admit I didn't test).

>  it looks like you completely removed startPermissionFlow

yeah, that was the intention. My version simplifies things in a couple ways:

1. Remove `startPermissionFlow`. Instead, `ContactPermissionModal` just checks for permissions on mount, and if we haven't asked before, it renders the soft permissions modal.
1. That removes the need to manage the modal state in the parent component

2025-04-25 08:29 UTC, perunt commented on src/libs/ContactImport/index.native.tsx
> +        }));
👍🏻

2025-04-25 08:36 UTC, perunt commented on src/libs/ContactImport/index.native.tsx
> +import {CONTACT_FIELDS} from '@expensify/nitro-utils/src/specs/ContactsModule.nitro';
> Could we move CONTACT_FIELDS defination to the modules/ExpensifyNitroUtils/src/index.ts file?

ExpensifyNitroUtils, it's not only one module, it's a folder for a future set of modules, so I don't want to mess up all definitions in the index file. But yes, I can re-export it from the index file, and it's a good approach, thanks!

2025-04-25 08:46 UTC, perunt commented on modules/ExpensifyNitroUtils/src/specs/ContactsModule.nitro.ts
> +type ContactFields = 'FIRST_NAME' | 'LAST_NAME' | 'PHONE_NUMBERS' | 'EMAIL_ADDRESSES' | 'IMAGE_DATA';
👍🏻

2025-04-25 09:14 UTC, perunt commented on modules/ExpensifyNitroUtils/ExpensifyNitroUtils.podspec
> +  s.platforms    = { :ios => min_ios_version_supported }
If it's not defined there it will pick up version form root podfile

2025-04-25 09:23 UTC, perunt commented on src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
> +    }, []);
Hmm, can you share some examples?
From what I can see, we use it on four screens, and in each case, it's initially set to false
That's intentional, we don't want to show the soft permission modal when the user has already denied access or granted it

2025-04-25 09:30 UTC, perunt commented on src/components/ContactPermissionModal/index.native.tsx
> +                return;
At that moment, the soft permission modal hasn't been shown yet. We call `onDeny` when the user explicitly denies permission

2025-04-25 10:03 UTC, perunt commented on src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
> +    }, []);
Good catch, thanks for pointing it out!
I just removed it

2025-04-25 10:06 UTC, perunt commented
> Hmm, seems like the iOS build failed with this error. @perunt could you take a look and see why this might be? The GH says that the Android build also failed but looking at the workflow it looks like it actually built fine.

Can we get this merged first @roryabraham @blimpich? https://github.com/Expensify/Mobile-Expensify/pull/13516

2025-04-29 19:06 UTC, roryabraham commented
Triggered https://github.com/Expensify/App/actions/runs/14739295677, which uses this branch on E/App and https://github.com/Expensify/Mobile-Expensify/pull/13516 in Mobile-Expensify

2025-04-30 16:52 UTC, roryabraham commented on modules/ExpensifyNitroUtils/package.json
> +  "homepage": "https://github.com/mrousavy/nitro#readme",
I like the idea of writing a brief README in https://github.com/Expensify/App/modules/ExpensifyNitroUtils explaining:

- How it's set up
- How to add or modify nitro modules/hybrid objects
- Linking to that README in the "homepage" field of `modules/ExpensifyNitroUtils/package.json`

2025-04-30 16:53 UTC, roryabraham commented on src/components/ContactPermissionModal/index.native.tsx
> +function ContactPermissionModal({startPermissionFlow, resetPermissionFlow, onDeny, onGrant}: ContactPermissionModalProps) {
@perunt what do you think about this comment? Can we proceed with the simplified version of the code?

2025-04-30 16:57 UTC, roryabraham requested changes
We still haven't resolved [this comment](https://github.com/Expensify/App/pull/54459#discussion_r2055069359)

2025-04-30 16:57 UTC, roryabraham commented on src/libs/RandomAvatarUtils.ts
> +import Avatar1 from '@assets/images/avatars/user/default-avatar_1.svg';
It's probably a good idea to use a dynamic `import` to lazy-load the SVGs only as they're needed.

2025-04-30 16:57 UTC, roryabraham commented on src/libs/OptionsListUtils.ts
> +function getUserToInviteContactOption({
Can we add unit tests covering this function?

2025-05-01 09:09 UTC, perunt commented on src/components/ContactPermissionModal/index.native.tsx
> +function ContactPermissionModal({startPermissionFlow, resetPermissionFlow, onDeny, onGrant}: ContactPermissionModalProps) {
Yeah definitely, we can do it. I should’ve made a better version from the beginning instead of just reusing it.
So am I right that now we’re ditching the ability to trigger the soft input for example, when pressing an 'Import' button? 
Let me update this code

2025-05-01 10:14 UTC, perunt commented on src/components/ContactPermissionModal/index.native.tsx
> +function ContactPermissionModal({startPermissionFlow, resetPermissionFlow, onDeny, onGrant}: ContactPermissionModalProps) {
During the refactor, it felt a bit off that the Permission modal became 'smart'.
 Also the fact that we now have the option to 'check if we have permission and run a function from the parent component' seems a bit messy. (It's needed for fetching contacts)
 So maybe we can leave the permission decision in the parent component and keep everything else inside the modal?

2025-05-01 12:33 UTC, perunt commented on src/components/ContactPermissionModal/index.native.tsx
> +function ContactPermissionModal({startPermissionFlow, resetPermissionFlow, onDeny, onGrant}: ContactPermissionModalProps) {
nvm, I’ve changed the contact importing, and now it works well

2025-05-01 16:48 UTC, roryabraham commented on src/components/ContactPermissionModal/index.native.tsx
> +function ContactPermissionModal({startPermissionFlow, resetPermissionFlow, onDeny, onGrant}: ContactPermissionModalProps) {
Thanks, this looks better now

2025-05-01 18:54 UTC, DylanDylann commented
I still get failed on building locally. But it may caused by my local. I will deep dive into it tomorrow

2025-05-01 21:44 UTC, roryabraham reviewed
Actually, looking a bit closer at `RandomAvatarUtils`, I suggest some further simplifications:

1. Remove unnecessary types
2. Move string hashing logic to `StringUtils`
3. Simplify the hashing logic by hard-coding prime numbers rather than using esoteric logic to choose them
4. Break up some of the math statements in the hashing logic to make it a bit easier to follow without having to do reason about the PEMDAS logic
5. (optional) remove the string slice, since names with significantly more than 8 characters are rare.

```diff
diff --git a/src/libs/ContactUtils.ts b/src/libs/ContactUtils.ts
index e1730bc9925..c9e1bb2ffbc 100644
--- a/src/libs/ContactUtils.ts
+++ b/src/libs/ContactUtils.ts
@@ -3,7 +3,7 @@ import type {PersonalDetails} from '@src/types/onyx';
 import type {DeviceContact, StringHolder} from './ContactImport/types';
 import {getUserToInviteContactOption} from './OptionsListUtils';
 import type {SearchOption} from './OptionsListUtils';
-import {getAvatarForContact} from './RandomAvatarUtils';
+import RandomAvatarUtils from './RandomAvatarUtils';
 
 function sortEmailObjects(emails?: StringHolder[]): string[] {
     if (!emails?.length) {
@@ -29,7 +29,7 @@ const getContacts = (deviceContacts: DeviceContact[] | []): Array<SearchOption<P
         .map((contact) => {
             const email = sortEmailObjects(contact?.emailAddresses ?? [])?.at(0) ?? '';
             // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
-            const avatarSource = (contact?.imageData || getAvatarForContact(`${contact?.firstName}${email}${contact?.lastName}`)) ?? '';
+            const avatarSource = (contact?.imageData || RandomAvatarUtils.getAvatarForContact(`${contact?.firstName}${email}${contact?.lastName}`)) ?? '';
             const phoneNumber = contact.phoneNumbers?.[0]?.value ?? '';
             const firstName = contact?.firstName ?? '';
             const lastName = contact?.lastName ?? '';
diff --git a/src/libs/RandomAvatarUtils.ts b/src/libs/RandomAvatarUtils.ts
index 2aad23b1358..30a6aa685d7 100644
--- a/src/libs/RandomAvatarUtils.ts
+++ b/src/libs/RandomAvatarUtils.ts
@@ -1,5 +1,3 @@
-import type {FC} from 'react';
-import type {SvgProps} from 'react-native-svg';
 import Avatar1 from '@assets/images/avatars/user/default-avatar_1.svg';
 import Avatar2 from '@assets/images/avatars/user/default-avatar_2.svg';
 import Avatar3 from '@assets/images/avatars/user/default-avatar_3.svg';
@@ -24,11 +22,9 @@ import Avatar21 from '@assets/images/avatars/user/default-avatar_21.svg';
 import Avatar22 from '@assets/images/avatars/user/default-avatar_22.svg';
 import Avatar23 from '@assets/images/avatars/user/default-avatar_23.svg';
 import Avatar24 from '@assets/images/avatars/user/default-avatar_24.svg';
+import StringUtils from './StringUtils';
 
-type AvatarComponent = FC<SvgProps>;
-type AvatarArray = readonly AvatarComponent[];
-
-const avatars: AvatarArray = [
+const avatars = [
     Avatar1,
     Avatar2,
     Avatar3,
@@ -55,45 +51,16 @@ const avatars: AvatarArray = [
     Avatar24,
 ] as const;
 
-const AVATAR_LENGTH: number = avatars.length;
-const DEFAULT_AVATAR: AvatarComponent = Avatar1;
-
-// Prime numbers for better distribution
-const MULTIPLIER = AVATAR_LENGTH + 7; // First prime after length
-const OFFSET = AVATAR_LENGTH - 11; // First prime before length
+const DEFAULT_AVATAR = Avatar1;
 
 /**
- * Generate a deterministic avatar based on multiple letters from the name.
- * Uses a rolling hash of the first 5 letters (or available letters if name is shorter)
- * for better distribution while maintaining deterministic results.
- *
- * @example
- * // These will always return the same avatar for the same name
- * const avatar1 = getAvatarForContact("Jonathan")  // Uses 'Jonat' for hash
- * const avatar2 = getAvatarForContact("Jane")  // Uses 'Jane' for hash
- * const avatar3 = getAvatarForContact("J")     // Uses 'J' for hash
- *
- * @param name - Contact name or null/undefined
- * @returns Avatar component
+ * Deterministically choose an avatar for a contact with an even distribution.
  */
-const getAvatarForContact = (name?: string | null): AvatarComponent => {
-    if (!name?.length) {
+const getAvatarForContact = (name?: string | null) => {
+    if (!name) {
         return DEFAULT_AVATAR;
     }
-
-    // Take up to first 8 characters, or all if name is shorter
-    const chars = name.slice(0, 8);
-
-    // Create a rolling hash from the characters
-    let hash = 0;
-    for (let i = 0; i < chars.length; i++) {
-        const charCode = chars.charCodeAt(i);
-        // Use position-based multiplier for better distribution
-        hash = (hash * MULTIPLIER + charCode * (i + 1) + OFFSET) % AVATAR_LENGTH;
-    }
-
-    return avatars.at(Math.abs(hash)) ?? DEFAULT_AVATAR;
+    return avatars.at(StringUtils.hash(name, avatars.length)) ?? DEFAULT_AVATAR;
 };
 
-export type {AvatarComponent};
-export {getAvatarForContact};
+export default {getAvatarForContact};
diff --git a/src/libs/StringUtils.ts b/src/libs/StringUtils.ts
index baa3ed594b4..d026fb776d6 100644
--- a/src/libs/StringUtils.ts
+++ b/src/libs/StringUtils.ts
@@ -121,6 +121,39 @@ function removePreCodeBlock(text = '') {
     return text.replace(/<pre[^>]*>|<\/pre>/g, '');
 }
 
+/**
+ * Hash a string, plus some logic to increase entropy and reduce collisions.
+ *
+ * @param str - the string to generate a whole number hash from
+ * @param max - the hash will not be more than this maximum. It defaults to 2^32 to prevent the hash from overflowing the max number space in JavaScript, which is 2^53
+ *
+ * @example
+ * // deterministically choose an item from an array with an even distribution:
+ * const avatars = [Avatar1, Avatar2, Avatar3, Avatar4];
+ * const email = 'someone@gmail.com';
+ * const defaultAvatarForEmail = avatars[StringUtils.hash(email, avatars.length)];
+ */
+function hash(str: string, max: number = 2 ** 32): number {
+    if (max <= 0) {
+        throw new Error('max must be a positive integer');
+    }
+
+    // Create a rolling hash from the characters
+    let hashCode = 0;
+    for (let i = 0; i < str.length; i++) {
+        // Char code, weighted by position in the string (this way "act" and "cat" will produce different hashes)
+        const charCode = str.charCodeAt(i) * (i + 1);
+
+        // Multiplied and offset by prime numbers for more even distribution.
+        hashCode *= 31;
+        hashCode += charCode + 7;
+
+        // Continuously mod by the max to prevent max number overflow for large strings
+        hashCode %= max;
+    }
+    return Math.abs(hashCode);
+}
+
 export default {
     sanitizeString,
     isEmptyString,
@@ -132,4 +165,5 @@ export default {
     removeDoubleQuotes,
     removePreCodeBlock,
     sortStringArrayByLength,
+    hash,
 };
```

2025-05-02 14:15 UTC, perunt commented on src/libs/RandomAvatarUtils.ts
> +const MULTIPLIER = AVATAR_LENGTH + 7; // First prime after length
You're right, a bit outdated comment

2025-05-02 14:19 UTC, perunt commented
> I still get failed on building locally. But it may caused by my local. I will deep dive into it tomorrow

What errors are you seeing? Also, make sure you’ve switched to `@perunt/nitro-module` in Mobile-Expensify, as running `git submodule update --init --progress --depth 100` will automatically switch it back to the main branch.

2025-05-02 19:05 UTC, roryabraham submitted a review, later dismissed
Code LGTM, awaiting C+ testing and checklist

2025-05-02 19:05 UTC, roryabraham commented on src/libs/ContactUtils.ts
> +    return emails
NAB micro-optimization:

```ts
return emails
    .reduce((memo, email) => {
        if (email?.value) {
            memo.push(email);
        }
        return memo;
    }, [])
    .sort(...);
```

2025-05-03 06:02 UTC, DylanDylann commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified that the composer does not automatically focus or open the keyboard on mobile unless explicitly intended. This includes checking that returning the app from the background does not unexpectedly open the keyboard.
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: HybridApp
    - [x] Android: mWeb Chrome
    - [x] iOS: HybridApp
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified there are no new alerts related to the `canBeMissing` param for `useOnyx`
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] For any bug fix or new feature in this PR, I verified that sufficient [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) are included to prevent regressions in this flow.
- [x] If the `main` branch [...]

2025-05-03 06:47 UTC, DylanDylann commented on src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
> +        Linking.openSettings();
This method only be available on mobile. It will cause the crash on the web laptop

https://github.com/user-attachments/assets/86f76381-0951-4338-8a1b-d04b3833bded

2025-05-03 07:13 UTC, DylanDylann commented on src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
> +        Linking.openSettings();
@perunt I think we need to hide all related contact button on web and desktop including import button on the footer and on the header (when no result found)

2025-05-03 07:14 UTC, DylanDylann commented on src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
> +        Linking.openSettings();
Let's move Linking.openSettings(); method to .native file for safe

2025-05-03 07:15 UTC, DylanDylann commented on src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
> +        Linking.openSettings();
And only trigger importAndSaveContacts if it is native app

2025-05-03 07:16 UTC, DylanDylann commented
BUG: The Contact Permission Modal always appears even though users already imported their contacts

https://github.com/user-attachments/assets/f08082ba-d0ca-43e9-8be8-2069a9c524a2

2025-05-03 07:28 UTC, DylanDylann commented
BUG: on Android Hybrid App, after turning off the contact permission manually, users still can see the contact list but the ContactPermissionModal always appears 

I am not sure if this is a bug, but we can discuss it later to improve this flow

https://github.com/user-attachments/assets/a3fadc72-84eb-4221-aa3a-5f1ea621c11d

2025-05-03 07:29 UTC, DylanDylann commented
@perunt Could you please provide a video on IOS hybrid App?

2025-05-06 11:06 UTC, DylanDylann commented
@perunt Kindly bump

2025-05-06 13:21 UTC, perunt commented
I'm back on it, let me address your issue

2025-05-06 14:27 UTC, perunt commented on src/libs/ContactUtils.ts
> +    return emails
Good microoptimizations, thanks!
Just to double check - did you test it with Hermes and not only on web? Because Hermes did a lot of work with array methods and they're pretty good, and when I tested it a few months ago the difference was negligible

2025-05-06 16:33 UTC, perunt commented on src/libs/ContactUtils.ts
> +    return emails
Pushed it, thanks again!

2025-05-06 17:39 UTC, roryabraham commented
@perunt Looks like you need to re-run pod install and update the Podfile.lock

2025-05-07 08:33 UTC, perunt commented on src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
> +        Linking.openSettings();
Nice catch, thanks for pointing it out

2025-05-07 14:56 UTC, perunt commented
@DylanDylann, I'm sorry. It was my fault, I didn't test the simplified soft permission modal properly. Can you check it again?

Now I've added `useAppStateContactPermissionHandler`, which is supposed to resolve all issues above. Also, I changed the behavior a bit, and now the soft modal appears only once per app start.

Here is the iOS Hybrid app. But it's a dev version since I don't have a cert for building the release version, unfortunately.

https://github.com/user-attachments/assets/5c0339bb-617d-4ea8-823a-373bdedcbf87

For testing app in the release version, I'm using the standalone app

> @perunt Looks like you need to re-run pod install and update the Podfile.lock
Thanks, somehow `npm run pod-install` doesn't fix it.

2025-05-08 16:26 UTC, roryabraham commented
@perunt you've got conflicts again

2025-05-09 12:11 UTC, perunt commented
❗ ❗ ❗  I just bumped `react-native-permissions` from `2.x` to `5.4.0` since it had a problem with 'limited contact access'. And I assume a similar issue can be found in another permission in the app. As the latest two iOS releases changed the permission flow a bit.
Looks like no breaking changes, but I'm still checking the rest of the permissions flow

2025-05-12 08:07 UTC, DylanDylann commented
@perunt please ping me when the PR is ready again

2025-05-12 20:46 UTC, blimpich commented
Looks like android build went through fine, but iOS ad-hoc build [failed](https://github.com/Expensify/App/actions/runs/14978134236/job/42075586692) with 
```
The following build commands failed:
	CompileSwift normal arm64 (in target 'ExpensifyNitroUtils' from project 'Pods')
	SwiftCompile normal arm64 Compiling\ Contact.swift,\ ContactFields.swift,\ ExpensifyNitroUtilsAutolinking.swift,\ Func_void_std__exception_ptr.swift,\ Func_void_std__vector_Contact_.swift,\ HybridContactsModule.swift,\ HybridContactsModuleSpec.swift,\ HybridContactsModuleSpec_cxx.swift,\ StringHolder.swift /Users/runner/work/App/App/modules/ExpensifyNitroUtils/nitrogen/generated/ios/swift/Contact.swift /Users/runner/work/App/App/modules/ExpensifyNitroUtils/nitrogen/generated/ios/swift/ContactFields.swift /Users/runner/work/App/App/modules/ExpensifyNitroUtils/nitrogen/generated/ios/ExpensifyNitroUtilsAutolinking.swift /Users/runner/work/App/App/modules/ExpensifyNitroUtils/nitrogen/generated/ios/swift/Func_void_std__exception_ptr.swift /Users/runner/work/App/App/modules/ExpensifyNitroUtils/nitrogen/generated/ios/swift/Func_void_std__vector_Contact_.swift /Users/runner/work/App/App/modules/ExpensifyNitroUtils/ios/contacts/HybridContactsModule.swift /Users/runner/work/App/App/modules/ExpensifyNitroUtils/nitrogen/generated/ios/swift/HybridContactsModuleSpec.swift /Users/runner/work/App/App/modules/ExpensifyNitroUtils/nitrogen/generated/ios/swift/HybridContactsModuleSpec_cxx.swift /Users/runner/work/App/App/modules/ExpensifyNitroUtils/nitrogen/generated/ios/swift/StringHolder.swift (in target 'ExpensifyNitroUtils' from project 'Pods')
```

2025-05-12 20:47 UTC, blimpich commented
I don't quite understand the failure, since I believe both @perunt and @DylanDylann have been able to build the HybridApp version of this locally. @perunt do you know why the ad-hoc build might've failed?

2025-05-13 08:21 UTC, perunt commented
> I don't quite understand the failure, since I believe both @perunt and @DylanDylann have been able to build the HybridApp version of this locally. @perunt do you know why the ad-hoc build might've failed?

For getting it to work for ad-hoc build we need to have merged [this](https://github.com/Expensify/Mobile-Expensify/pull/13516) PR into `Mobile-Expensify`

> https://github.com/Expensify/Mobile-Expensify/pull/13516 - use this PR for Mobile-Expensify

We can't merge this PR beforehand as it is trying to import a lib that doesn't exist in main.
So for testing we manually switch `Mobile-Expensify` from main branch to `@perunt/nitro-module`
Once we finish testing we can merge both PRs and this mismatch will be gone.

2025-05-13 17:59 UTC, blimpich commented
I see, thank you for the explanation!

2025-05-13 18:42 UTC, roryabraham commented
@blimpich it's possible to run AdHoc builds using a specific branches from E/App and E/Mobile-Expensify for scenarios like this with dependent PRs. You have to use https://github.com/Expensify/App/actions/workflows/testBuildHybrid.yml instead of https://github.com/Expensify/App/actions/workflows/testBuild.yml. We should generally use the former instead of the latter unless you have a good reason to want to test standalone.

Let's see if this works: https://github.com/Expensify/App/actions/runs/15004215351

2025-05-13 19:11 UTC, roryabraham commented
Created https://github.com/Expensify/App/issues/61935 to clear this up in the future

2025-05-14 12:00 UTC, DylanDylann approved these changes
LGTM, Testing well

2025-05-14 22:08 UTC, roryabraham commented
@perunt let's work on some detailed test and QA steps here, too. Also, if you can think of any automated tests to add, now would be a good time. We're going to have our QA team perform some regression tests on the AdHoc build too

2025-05-17 14:04 UTC, roryabraham commented
conflicts

2025-05-17 16:57 UTC, IuliiaHerets commented
# Android - No option to Import contacts in Start chat page and Invite member page


**Version Number:** 9.1.42-0 PR:54559
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** ddksskskls@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- App permission to access device contact is disabled.

1. Launch adhoc app.
2. Open FAB > Start chat > Chat.
3. Go to Workspace settings > Members.
4. Tap Invite member.

## Expected Result:
There should be an option to Import contacts in Start chat page and Invite member page.

## Actual Result:
There is no option to Import contacts in Start chat page and Invite member page.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/23a75955-9ff1-474d-8e5b-a8e09ea9357e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2025-05-17 17:28 UTC, IuliiaHerets commented
# Android - Missing pagination "Showing x of y" & Show more button when contact access is denied

**Version Number:** 9.1.42-0 PR:54559
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** ddksskskls@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Log in with Expensifail account (has more than 500 contacts).
- App contact permission is not allowed.

1. Launch adhoc app.
2. Open FAB > Create expense > Manual.
3. Enter amount > Next.
4. Tap Not now if contact permission prompt shows up.
5. Scroll down to the bottom of the list.

## Expected Result:
There will be pagination "Showing x of y" and Show more button.

## Actual Result:
App is missing the pagination "Showing x of y" and Show more button when contact list is very long

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/687a5464-a582-4a68-a077-3c33740e5329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2025-05-17 18:09 UTC, IuliiaHerets commented
# Android - Contacts - Missing Import contacts button when contact list is empty

**Version Number:** 9.1.42-0 PR:54559
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** ddksskskls@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Android - Contacts - Missing Import contacts button when contact list is empty

## Expected Result:
In Step 6, Import contacts button should be present when there is no contact.

## Actual Result:
In Step 6, Import contacts button is missing when there is no contact.
In Step 12, Import contacts button is only shown when there is at least one contact.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ae203ee3-4f95-4a5b-8516-9f4fc4e29b28

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2025-05-17 19:10 UTC, IuliiaHerets commented
#  iOS&Android - Members - "Select" widget at bottom not triggered on long pressing member name

**Version Number:** 9.1.42-0 PR:54559
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** ddksskskls@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch Hybrid app
2. Create new gmail account
3. Create workspace >> go to Invite member page >> tap Invite member CTA
4. Invite few members
5. Long press on a existing member

## Expected Result:
On long pressing member name, "Select" widget at the bottom should be triggered

## Actual Result:
"Select" widget at bottom not triggered on long pressing member name, hence owner cannot select members

On Android app - Select widget is displayed at the bottom, but the "Select" checkboxes is not triggered on clicking Select

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [ ] Android: mWeb Chrome
- [x] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3389be29-605f-4496-84e2-0fbdd4aa9828


https://github.com/user-attachments/assets/f60b5456-836d-4e82-8cac-17d3d8a1455d



[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2025-05-19 06:37 UTC, mitarachim commented
#  iOS - Contacts - Searched contact does not appear until background app & reopen

**Version Number:** 9.1.42-0 PR:54559
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** ddksskskls@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch Hybrid app
2. Create new gmail account
3. Create workspace >> go to Invite member page >> tap Invite member CTA
4. Enter email to search contact
5. Wait for few seconds & observe searched contact does not appear below
6. Background app & reopen it
7. Observe infinite loading appears in search field (Note: Searched contact now displayed below)

## Expected Result:
When user searches for a contact in invite member page, the contact should appear immediately to select in contacts below

## Actual Result:
Searched contact does not appear until background app & reopen. Also, infinite loading appears in search field when background app & reopen

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [x] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e6378e79-20fc-4d26-927a-d841f901e2e5



[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2025-05-19 06:48 UTC, mitarachim commented
#  iOS - Invite-User not automatically taken to confirm details page on selecting different roles

**Version Number:** 9.1.42-0 PR:54559
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** kiatest.80+ck517251@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch Hybrid app
2. Create new gmail account
3. Create workspace >> go to Invite member page >> tap Invite member CTA
4. Search contact & select it >> Tap Next button
5. Select a different role - Auditor or Admin

## Expected Result:
User should be automatically redirected to confirm details page when selecting different roles

## Actual Result:
User remains on role page & not automatically taken to confirm details page on selecting different roles. User has to manually tap back button to go back to confirm details page

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [x] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos


https://github.com/user-attachments/assets/91404429-80a8-4463-a2cd-fa5bfee76394


[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2025-05-19 07:00 UTC, mitarachim commented
#  iOS - Invite- Invite button not responsive in confirm details page

**Version Number:** 9.1.42-0 PR:54559
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** kiatest.80+ck517251@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch Hybrid app
2. Create new gmail account
3. Create workspace >> go to Invite member page >> tap Invite member CTA
4. Select contact >> tap Next button
5. Tap on Invite button
6. Observe user not redirected to members page
7. Back ground app & reopen it or tap on back button twice to go back to members page
8. Observe invited user appears in Members page

## Expected Result:
On step 5 - On tapping Invite button, user should be redirected to members page & all listed members displayed

## Actual Result:
Invite button not responsive in confirm details page. User not redirected to members page on tapping invite button. However, the invited user appears in members page and can be seen only after background app & reopening it

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [x] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos


https://github.com/user-attachments/assets/af3b2b50-269a-4672-af13-fb546005571a


[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2025-05-19 07:17 UTC, mitarachim commented
#  iOS - Profile & Role fields remain highlighted after going back from profile or role page

**Version Number:** 9.1.42-0 PR:54559
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** kiatest.80+ck517251@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch Hybrid app
2. Create new gmail account
3. Create workspace >>Invite few members
4. Tap on existing member
5. Tap on Profile option
6. Go back (Note: Profile field remain highlighted)
7. Tap on Role option
8. Go back (Note: Role field remain highlighted)

## Expected Result:
Profile & Role fields should not be highlighted after going back from profile or role page

## Actual Result:
Profile & Role fields remain highlighted after going back from profile or role page

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [x] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos



https://github.com/user-attachments/assets/f4759393-1f8e-45bd-b34d-2b95e7cbce5d




[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2025-05-19 07:24 UTC, mitarachim commented
#   iOS-Profile option does not respond after visiting 1:1 DM & then selecting profile second time

**Version Number:** 9.1.42-0 PR:54559
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** kiatest.80+ck517251@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch Hybrid app
2. Create new gmail account
3. Create workspace >>Invite few members
4. Tap on existing member
5. Tap on Profile option
6.Tap on Message button to go to 1:1 chat
7. Tap back button to go back to Profile
8. Tap back button to go back to user details page
9. Tap profile option >> tap back button
10. Tap on profile option again

## Expected Result:
On step 10 - User able to visit details page on tapping profile option

## Actual Result:
Profile option does not respond after visiting 1:1 DM & then selecting profile second time

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [x] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos


https://github.com/user-attachments/assets/b0481c3a-6a13-453a-9034-bf0a469b0f81




[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2025-05-19 08:30 UTC, mitarachim commented
# Android-Contacts - Contact middle name is not displayed

**Version Number:** 9.1.42-0 PR:54559
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** ddksskskls@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- There is a contact on device with first, middle and last name.
- App contact permission is allowed.

1. Launch adhoc app.
2. Go to FAB.
3. Tap Create expense > Manual.
4. Enter amount > Next.

## Expected Result:
The contact middle name will be displayed.

## Actual Result:
The contact middle name is not displayed.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos


https://github.com/user-attachments/assets/bc3b2cfa-d209-40a6-affb-280d5df23b44





[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2025-05-19 08:45 UTC, mitarachim commented
#   iOS - Infinite loading on navigating to Private Notes page first time

**Version Number:** 9.1.42-0 PR:54559
**Reproducible in staging?:** No
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp
**Email or phone of affected tester (no customers):** kiatest.80+ck517251@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch Hybrid app
2. Create new gmail account
3. Create workspace
4. Invite few members to workspace
5. Select member >> tap on Profile >> tap on message button
6. Go back to profile page
7. Tap on Private notes

## Expected Result:
Privates page should open when navigated to the page first time

## Actual Result:
Infinite loading on navigating to Private Notes page first time

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [x] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos


https://github.com/user-attachments/assets/d9aa3a7d-a155-4169-bde5-0b8d943347c2



[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

2025-05-19 13:08 UTC, mvtglobally commented
QA is completed

2025-05-20 13:52 UTC, perunt commented
1. [Android - No option to Import contacts in Start chat page and Invite member page](https://github.com/Expensify/App/pull/54459#issuecomment-2888492139) - 🟡  I didn't discuss this properly but originally my idea was to deliver contact import to expenses pages and later spread around the app. Since we have 4k changes now and adding that to the rest of the app will bring another 1 - 1.5k changes. Do you think we should deliver it within this PR? @roryabraham 
2. [Android - Missing pagination "Showing x of y" & Show more button when contact access is denied](https://github.com/Expensify/App/pull/54459#issuecomment-2888504390) 🟢 Done
3. [Android - Contacts - Missing Import contacts button when contact list is empty
](https://github.com/Expensify/App/pull/54459#issuecomment-2888520015) - 🟡  @Expensify/design, what do you think about this? I remember we removed the button and put a clickable text for the search mode. In this case, we have the same layout, but not for search, instead for the main screen list. I assume we also apply some clickable text? How should it look, and what should it say?
4. [iOS&Android - Members - "Select" widget at bottom not triggered on long pressing member name](https://github.com/Expensify/App/pull/54459#issuecomment-2888543082) - ⚠️ Not related to this PR. The bug originated in the main branch and disappeared after merging the latest changes from main
5. [iOS - Contacts - Searched contact does not appear until background app & reopen](https://github.com/Expensify/App/pull/54459#issuecomment-2889791049)  ⚠️ Not related to this PR. The bug originated in the main branch and disappeared after merging the latest changes from main
(same as the first report. I didn't touch this screen. @roryabraham should I add contact import here within this PR?)
6. [iOS - Invite-User not automatically taken to confirm details page on selecting different roles](https://github.com/Expensify/App/pull/54459#issuecomment-2889814975) - ⚠️ Not related to this PR. The bug originated in the main branch and disappeared after merging the latest changes from main
7. [iOS - Invite- Invite button not responsive in confirm details page](https://github.com/Expensify/App/pull/54459#issuecomment-2889842637) - ⚠️ Not related to this PR. The bug originated in the main branch and disappeared after merging the latest changes from main
8. [iOS - Profile & Role fields remain highlighted after going back from profile or role page ](https://github.com/Expensify/App/pull/54459#issuecomment-2889884106) - ⚠️ Not related to this PR. The bug originated in the main branch and disappeared after merging the latest changes from main
9. [iOS-Profile option does not respond after visiting 1:1 DM & then selecting profile second time](https://github.com/Expensify/App/pull/54459#issuecomment-2889903557) - ⚠️ Not related to this PR. The bug originated in the main branch and disappeared after merging the latest changes from main
10. [iOS-Notification - No notification is received for 1:1 DM](https://github.com/Expensify/App/pull/54459#issuecomment-2889983107) -  ⚠️ This PR has nothing to do with notifications. Are we sure that this type of build that you're testing can receive notifications? @mitarachim
11. [Android-Contacts - Contact middle name is not displayed](https://github.com/Expensify/App/pull/54459#issuecomment-2890110911) - 🟡  originally I did this intentionally. @roryabraham since we have only firstName and lastName do you think that we can merge middle name to lastName? What do you think about adding middle name in general?
12. [iOS - Infinite loading on navigating to Private Notes page first time](https://github.com/Expensify/App/pull/54459#issuecomment-2890156335) - ⚠️ Not related to this PR. The bug originated in the main branch and disappeared after merging the latest changes from main

2025-05-20 14:21 UTC, dannymcclain commented
>https://github.com/Expensify/App/pull/54459#issuecomment-2888520015
>- 🟡 @Expensify/design, what do you think about this?

I'm not sure I am completely following, so I apologize if I'm missing something, but could we include the same little text component beneath the search bar as in your right screenshot, but just remove the first sentence saying "No results found"?

So we'd just have a little message under there that says "[Import your contacts](url) so your favorite people
are always a tap away."

Thoughts on something like that?

2025-05-26 15:04 UTC, perunt commented
Good idea moving it to beta. I’ll do it

2025-05-26 21:22 UTC, roryabraham commented
back-end PR to create the beta: https://github.com/Expensify/Web-Expensify/pull/46918

Note that it _must_ be called `nativeContactImport`

2025-05-28 18:55 UTC, blimpich commented
[Beta was deployed to staging](https://github.com/Expensify/Web-Expensify/pull/46918#issuecomment-2917128787). Should be deployed to production tomorrow. Bumped QA on creating some TC's for this feature [here](https://expensify.slack.com/archives/C9YU7BX5M/p1748458370012139?thread_ts=1747260442.439719&cid=C9YU7BX5M). However, even without the full set of TC's I think we should still be good to merge as long as the beta is in place and in production. So we could merge this as early as tomorrow I think.

2025-05-29 18:53 UTC, blimpich approved these changes, later dismissed
[Beta is on production](https://github.com/Expensify/Web-Expensify/pull/46918#issuecomment-2920109529) and core [e2e regression tests](https://expensify.slack.com/archives/C9YU7BX5M/p1748465839563949?thread_ts=1747260442.439719&cid=C9YU7BX5M) have been written. I think we're good to move forward here 👍 🚀 

@perunt one more round of merge conflict resolution 🤞 

@roryabraham how do you feel about moving forward?

2025-05-30 03:33 UTC, roryabraham requested changes

2025-06-04 16:47 UTC, roryabraham commented
@perunt it seemed like we were close here? Let's keep pushing this forward

2025-06-04 17:47 UTC, perunt commented
I'll switch all my focus to it tomorrow morning
I see some leftovers were committed there. I'll rewatch it and clean it, then ping you @roryabraham . Thanks for helping me to do it better!

2025-06-05 11:17 UTC, perunt commented on src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
> +    const [betas] = useOnyx(ONYXKEYS.BETAS, {canBeMissing: true});
Didn't know that we have that hook, thanks
But I didn't add that thing, I just moved it to the top. I'll use that hook but will keep the 'betta' call here since it's used for 'getValidOptions'

2025-06-05 11:21 UTC, perunt commented on src/libs/ContactPermission/useAppStateContactPermissionHandler.ts
> +    useFocusEffect(
I did this since TS wasn't happy with ```useFocusEffect(checkPermissionAndReact);```

2025-06-05 12:57 UTC, perunt commented on src/libs/ContactPermission/useAppStateContactPermissionHandler.ts
> +    const checkPermissionAndReact = useCallback(() => {
👍🏻

2025-06-05 12:57 UTC, perunt commented on src/libs/ContactPermission/useAppStateContactPermissionHandler.ts
> +    useEffect(() => {
Nice improvement 👍🏻

2025-06-05 12:58 UTC, perunt commented on src/pages/iou/request/goToSettings/index.native.tsx
👍🏻

2025-06-05 13:20 UTC, perunt commented
@roryabraham Here's what I've done:
- updated `useAppState`
- cleaned `project.pbxproj`
- refactored `useContactPermissions`
- replaced union type `ContactFields` that we added recently since they are not supported by Nitrogen yet

Spellcheck is off due to the margelo lib in the code. I don't want to exclude that file since it can be useful there

EDIT: Currently running the build for all platforms to double-check everything works

2025-06-05 19:36 UTC, roryabraham commented on modules/ExpensifyNitroUtils/.watchmanconfig
> +{}
Is this file doing anything?

2025-06-05 19:36 UTC, roryabraham commented on modules/ExpensifyNitroUtils/.gitignore
> +# OSX
NAB but since this isn't a submodule we could just use the `.gitignore` at the root, right?

2025-06-05 19:36 UTC, roryabraham commented on ios/Podfile.lock
> -  react-native-webrtc: 0f1c94069ff1eb9d8fb1618c2dc71f73542c8cfa
Not sure if this change was intentional? Seems unrelated?

2025-06-05 19:36 UTC, roryabraham commented on src/hooks/useWorkletStateMachine/index.ts
> -import fastMerge from 'expensify-common/dist/fastMerge';
Is this change related?

2025-06-05 19:36 UTC, roryabraham commented on modules/ExpensifyNitroUtils/.gitignore
> +# OSX
not important to change this, we can keep the 2nd `.gitignore`

2025-06-06 17:15 UTC, perunt commented on src/hooks/useWorkletStateMachine/index.ts
> -import fastMerge from 'expensify-common/dist/fastMerge';
As far as I remember, I got an error while using fastMerge with worklets

2025-06-06 19:06 UTC, perunt commented on modules/ExpensifyNitroUtils/.watchmanconfig
> +{}
I've removed it already, let me check if the spec generation doesn't recreate it

2025-06-09 09:55 UTC, perunt commented on modules/ExpensifyNitroUtils/.gitignore
> +# OSX
Indeed, it's not a git submodule, and we can use .gitignore from the root. The reason I left it separate was just to keep these specific patterns isolated. However, since we expect to have a new Nitro module in the future I'm moving it to the root

2025-06-09 10:23 UTC, perunt commented on src/hooks/useWorkletStateMachine/index.ts
> -import fastMerge from 'expensify-common/dist/fastMerge';
I just realized that it originates from merge conflicts from another PR. Reverted now

2025-06-09 10:46 UTC, perunt commented on ios/Podfile.lock
> -  react-native-webrtc: 0f1c94069ff1eb9d8fb1618c2dc71f73542c8cfa
It came from merge conflicts, reverted 👍🏻

2025-06-09 21:41 UTC, blimpich commented
Looks like we still have lint failures. Can you fix that @perunt?

2025-06-10 09:19 UTC, perunt commented
@blimpich, it wants me to remove `TABLE_REPORT_VIEW` from all screens since I touched beta files by adding `NATIVE_CONTACT_IMPORT`. Can we ignore it since there's a separate PR with removing `TABLE_REPORT_VIEW`? https://github.com/Expensify/App/issues/63254

2025-06-10 17:06 UTC, blimpich commented
> @blimpich, it wants me to remove `TABLE_REPORT_VIEW` from all screens since I touched beta files by adding `NATIVE_CONTACT_IMPORT`. Can we ignore it since there's a separate PR with removing `TABLE_REPORT_VIEW`? #63254

Yup sounds good thanks for the explanation!

2025-06-10 18:00 UTC, roryabraham commented
We can fix cspell by adding `margelo` [here](https://github.com/Expensify/App/blob/4274c7cbea0e51e537d9b830469d2e53db67ceab/cspell.json#L318)

2025-06-10 18:04 UTC, roryabraham approved these changes

2025-06-10 18:05 UTC, roryabraham commented
I agree with ignoring the changed-files eslint check, and I'm willing to ignore the cspell and fix it separately just because I don't want to further delay this long-standing PR.

2025-06-10 18:05 UTC, merged

2025-06-10 18:05 UTC, roryabraham commented
skipped tests explained in my last comment

2025-06-10 18:16 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2025-06-10 20:12 UTC, pac-guerreiro commented on src/components/SelectionList/BaseSelectionList.tsx
> +                                {footerContentAbovePagination}
@roryabraham @perunt 

This change broke some components that are passing `listFooterContent` to SelectionList!

Here is an example:

![Screenshot 2025-06-10 at 20 52 28](https://github.com/user-attachments/assets/f82ab5a3-293d-4e91-ab6e-3c718f0b65e9)

2025-06-12 08:07 UTC, DylanDylann commented on src/components/SelectionList/BaseSelectionList.tsx
> +                                {footerContentAbovePagination}
@perunt It seems this is a serious bug, could you please raise a quick PR to update it again?

2025-06-12 09:02 UTC, pac-guerreiro commented on src/components/SelectionList/BaseSelectionList.tsx
> +                                {footerContentAbovePagination}
@DylanDylann a fix was already merged here: https://github.com/Expensify/App/pull/63887 😄

2025-08-20 15:34 UTC, suneox commented on src/libs/OptionsListUtils.ts
> +        text: displayName,
Coming from #66839 checklist: We’re missing firstName and lastName because userToInvite is typed as SearchOption<PersonalDetails>.

2025-12-16 04:23 UTC, shubham1206agra commented on src/libs/OptionsListUtils.ts
> +        login: effectiveSearchValue,
This was not handled correctly for mobile numbers which caused https://github.com/Expensify/App/issues/71739

2026-02-03 16:34 UTC, Krishna2323 commented on src/pages/iou/request/MoneyRequestParticipantsSelector.tsx
> +                footerContentAbovePagination={footerContentAbovePaginationComponent}
Using `footerContentAbovePagination` for the Import Contact button caused [this issue](https://github.com/Expensify/App/issues/76667), where the button was not clickable because it was placed at the end of the list. Each time we scrolled to the button, more options loaded and pushed it further down.