Animate payment icon in money request preview
Expensify/App pull request #54490
Opened 2024-12-24 02:23 UTC by abzokhattab

### Explanation of Change

### Fixed Issues

$ https://github.com/Expensify/App/issues/53474
PROPOSAL: https://github.com/Expensify/App/issues/53474#issuecomment-2515075829

### Tests

Scenario one: 

1. Create a new workspace
2. Submit an expense
3. Click Pay elsewhere in the report preview
4. Validate that the payment animation is working as expected
5. Submit another expense
6. Click on the report preview
7. click on pay elsewhere in the report header
8. Validate that the payment animation is working as expected

Scenario two: 

1. Create a new workspace
2. Click on more features and enable workflows 
3. Click on the Workflows tab, then enable Add approvals
4. Go to workspace chat and and Submit an expense
5. in the report preview, Click on Approve 
6. Validate that the approval animation is working as expected. 
7. Click Pay elsewhere in the report preview
8. Validate that the payment animation is working as expected
9. Submit another expense
10. Click on the report preview
11. click on Approve in the report header
12. Validate that the approval animation is working as expected. 
13. Click Pay elsewhere in the report header
14. Validate that the payment animation is working as expected

### Offline tests

Same as tests
### QA Steps

Same as tests

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android: Native
    - [X] Android: mWeb Chrome
    - [X] iOS: Native
    - [X] iOS: mWeb Safari
    - [X] MacOS: Chrome / Safari
    - [X] MacOS: Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [X] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [X] I verified that all the inputs inside a form are aligned with each other.
    - [X] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new f [...]

2025-01-02 10:18 UTC, shawnborton commented
Good catches, we should make sure those are fixed before this is merged.

2025-01-06 05:24 UTC, dubielzyk-expensify commented
Agree with all the bugs posted above 👍 A few notes as well:

The recording on iOS native in the OG post feel perfect to me. That should be what we're aiming for. The last video on [this comment](https://github.com/Expensify/App/pull/54490#issuecomment-2565040423) labeled `This PR` has the checkmarks appearing on the button and preview card at different times and I think we should make sure these match.


I don't think the approved button should have the checkmark in the button. Feels like we should either not use a checkmark there or use the thumbs up there as well (keen to hear @Expensify/design 's thoughts here. I wonder if we should actually just say "Payment complete" and "Approved" without the icon in the button to avoid double icons?): 

![CleanShot 2025-01-06 at 15 17 28@2x](https://github.com/user-attachments/assets/1967d09b-cf0b-48d4-9521-909d25d71f70)


Also there's a weird bug on the video MacOS Desktop video where it goes from paid -> approved -> paid again?
https://github.com/user-attachments/assets/5d119963-1c9f-40a1-b91a-2c74de909ef4

2025-01-06 14:58 UTC, dannymcclain commented
>I don't think the approved button should have the checkmark in the button. Feels like we should either not use a checkmark there or use the thumbs up there as well (keen to hear @Expensify/design 's thoughts here. I wonder if we should actually just say "Payment complete" and "Approved" without the icon in the button to avoid double icons?):

Definitely agree that approved should use the thumbs up icon. But I'm not against not including the icon here since the preview gets it. I think in the report header it would be nice to keep the icon in the button, so I'm ALSO not against leaving them and just having the double-icon for a brief moment before the button disappears. But either way, let's make sure the icon matches the action (pay = checkmark, approve = thumbs up).

2025-01-07 01:31 UTC, dubielzyk-expensify commented
Fair points. Let's leave them in the button for now and make all the other changes, then see how it feels 👍

2025-01-09 13:37 UTC, lakchote commented
Any updates @abzokhattab?

2025-01-13 09:17 UTC, lakchote commented
> Any updates @abzokhattab?
>

@abzokhattab could you please give us a status update? Thanks!

2025-01-14 06:58 UTC, shawnborton commented
For this confirm approval modal, did we make any changes here? I'm surprised the button isn't using a larger size:
![CleanShot 2025-01-14 at 07 57 11@2x](https://github.com/user-attachments/assets/66a36014-a923-4ef4-940b-8cfa92b9c79a)

We have a slightly weird transition between the approved button and the pay button where the card shrinks slightly...
![CleanShot 2025-01-14 at 07 58 00@2x](https://github.com/user-attachments/assets/f1071c91-cd19-4f32-a305-53eded0c2187)

...then grows again:
![CleanShot 2025-01-14 at 07 58 21@2x](https://github.com/user-attachments/assets/18f3e335-33be-4275-a3d6-13fdf5a007db)

Maybe we can clean that up so we don't get the jumping and the card height stays the same as it transitions from approved button to pay button?

2025-01-14 07:00 UTC, shawnborton commented
Also, the animations in the report header feel a little blunt... for example, when we go from the Approved state to then having this Pay button show up:
![CleanShot 2025-01-14 at 07 59 34@2x](https://github.com/user-attachments/assets/678f1712-1fc9-47f0-859f-04a9b453937c)

It would be nice to fade it in, rather than just abruptly showing it like it currently does. Basically it just feels a bit harsh and not as smooth as it could be?

2025-01-14 14:19 UTC, dannymcclain commented
I agree with all of Shawn's comments. Let's try to get all the transitions feeling nice and smooth. When they're harsh, it kinda undermines the point of the animation IMO.

2025-01-20 16:24 UTC, shawnborton commented
I think they look pretty good, the worst example happens to be when the "Review duplicates" button (last video) disappears which I think causes the more noticeable effect. Otherwise they feel pretty smooth to me? 

Also, can we please update the button size in the confirmation modal for approval to use a larger button size?
![CleanShot 2025-01-20 at 17 24 13@2x](https://github.com/user-attachments/assets/c597ceba-0607-496c-a2b8-0011b489b0bb)

2025-01-20 16:25 UTC, shawnborton commented
Actually that modal could use a lot of alignment love. If you are open to squeezing in some changes, let us know. Otherwise we can open up a separate issue for that I suppose.

2025-01-21 02:38 UTC, dubielzyk-expensify commented
I also think part of the jarriness comes from the fact that the animation scale goes from 1 -> 0. When scaling down an element it's usually better to do scale 1 -> 0.8 with opacity going from 1 -> 0, than just it scaling completely down. Especially with bigger buttons etc. So perhaps we could try that?

2025-01-21 07:23 UTC, shawnborton commented
Oh that's good feedback Jon, I think it's worth trying a smaller scaleOut

2025-01-24 10:41 UTC, shawnborton commented
For the modal alignment, we need this:
![CleanShot 2025-01-24 at 11 37 03@2x](https://github.com/user-attachments/assets/485fd44e-b9c4-4eba-a08f-42ca409ca23b)

![CleanShot 2025-01-24 at 11 37 28@2x](https://github.com/user-attachments/assets/2424d097-3f32-4416-8533-f7b7e67d51ba)

It should be standard styles from our alert modal component. 

> Here is the latest animation what do you think?

First video doesn't look too bad. 

For the second video... if the approve button is gray:
![CleanShot 2025-01-24 at 11 40 10@2x](https://github.com/user-attachments/assets/4b73cafb-445b-42f0-b265-8dcd8bfda463)

Then I think the loading spinner should be in a gray button too:
![CleanShot 2025-01-24 at 11 40 10@2x](https://github.com/user-attachments/assets/d4dcae64-5cd8-48a8-8e0c-904b20099d0c)

And I would even say that the final ending button should be gray as well... basically let's keep this button the same style throughout the entire animation. And one thing I am realizing here too, I think the animation feels jarring because the animation changes widths twice. In the very least, we should make the loading spinner button the same width as the first Approved button. Then maybe it's fine if it gets wider once the thumb icon comes in at the end.

2025-01-24 10:42 UTC, shawnborton commented
And on that note, I feel like we need to get rid of the "Review duplicates" button sooner as well, basically as soon as the approved button gets the thumbs up, let's fadeOut the Review duplicates button:
![CleanShot 2025-01-24 at 11 42 05@2x](https://github.com/user-attachments/assets/d1550d74-206f-40fc-8a92-6c13ecc6442d)

2025-01-28 12:18 UTC, trjExpensify commented
@abzokhattab this PR has been open since Dec 24th, what's the ETA here?

2025-01-29 07:16 UTC, shawnborton commented
We still have some jerky behavior in the first video... look at this sequence:

![CleanShot 2025-01-29 at 08 13 34@2x](https://github.com/user-attachments/assets/e2a00481-f9bc-4d58-8846-09027eefd910)

Then for some reason we see the thumbs up icon:
![CleanShot 2025-01-29 at 08 15 03@2x](https://github.com/user-attachments/assets/491ea0cd-26b6-40be-8c40-740d737513fb)

Then it goes into loading:
![CleanShot 2025-01-29 at 08 15 20@2x](https://github.com/user-attachments/assets/9343ec4f-ce57-4424-8849-f70a41965d2a)

Then we get the thumbs up icon again:
![CleanShot 2025-01-29 at 08 15 31@2x](https://github.com/user-attachments/assets/340e321d-b4e0-4517-afc2-f05424100d79)

If we can eliminate that first quick glimpse of the thumbs up icon (my second image above), I think we can smoothen this out quite a bit. Can you take a look at that please? Thanks!

2025-01-30 00:08 UTC, abzokhattab commented
Fixed: 

https://github.com/user-attachments/assets/a14fcf1a-f488-4e44-94e1-a0197b2141c7

2025-01-30 03:32 UTC, dubielzyk-expensify commented
That looks better to me, but looking at the whole segment there's something slightly weird about how it all animates. It feels like there's so many jumps between the buttons and new buttons appearing. I think the scale out together with the width of the buttons changing is the odd thing. 

Not sure if you have this same feeling @Expensify/design ?

2025-01-30 07:33 UTC, shawnborton commented
Hmm I think I see what you are saying, though I will say that the most recent video definitely solves my concerns about the jankiness of the loading spinner. 

I don't have many good questions at this point... when the button does the scaleOut, maybe we need to try a scaleIn for the new button or a fadeIn or something like that? We could also follow up and keep tweaking that, as I think what we have now is a big improvement at least.

2025-01-30 10:02 UTC, dubielzyk-expensify commented
Yeah I recon we maybe do a follow-up and I can make a note to experiment more with the animations in Figma and make a follow-up fix for that if we so prefer?

2025-01-30 14:45 UTC, shawnborton commented
Sounds good to me too!

2025-01-30 14:55 UTC, abzokhattab commented
> That sounds good to me. I think ideally the button would never change size while going through the animation


I agree with you. However, when I tried to implement this, I encountered an issue with the "Approved" button. The final stage text ("Approved + thumbs up") is wider than the initial button, causing the text to get cut off.

To resolve this, I made only the loading stage maintain the same width as the initial button.

What do u think? should we keep it like this?

2025-01-30 15:34 UTC, dannymcclain commented
>I think what you have is okay for now, let's try to get it merged and then we can follow up with any improvement tweaks that we want.

Agree!

2025-01-31 03:34 UTC, dubielzyk-expensify commented
> I think ideally the button would never change size while going through the animation—not exactly sure how we'd accomplish that, but it would make everything feel so much smoother. Right now they feel like 2-3 different buttons, and ideally we want it to feel like 1 button going through different states

Yep this is exactly what I feel too. I think the only way to fix this is by making the potential biggest width instance of the button the min-width. But let's get this merged for now then we can come up with a good follow-up plan 👍

2025-01-31 15:54 UTC, abzokhattab commented
Done

2025-02-03 16:37 UTC, ntdiary requested changes
I have tested all the places where `DecisionModal` is used. Here are some example screenshots:
<details><summary>modal-pay-hold</summary>
<p>
<img width="383" alt="modal-pay-hold" src="https://github.com/user-attachments/assets/e7e12626-8ecb-4569-a238-16970730273f" />
</p>
</details> 

<details><summary>modal-search-download-fail</summary>
<p>
<img width="394" alt="modal-search-download-fail" src="https://github.com/user-attachments/assets/f04506ec-d16e-4642-ad68-c73758cd7f7e" />

</p>
</details> 
<details><summary>modal-search-offline</summary>
<p>
<img width="398" alt="modal-search-offline" src="https://github.com/user-attachments/assets/b7072ef4-9394-4eff-88c1-20f6bbdeb674" />

</p>
</details> 
<details><summary>modal-import-onyx-state</summary>
<p>
<img width="390" alt="modal-import-onyx-state" src="https://github.com/user-attachments/assets/cc90b442-4da7-4ecc-8810-e19a4750134a" />

</p>
</details> 

BTW, maintaining `20` margin at the bottom of the modal will be difficult due to differences in `safeArea`, so I personally think it's fine to keep `20` margin for `top/left/right` for now (and the bottom margin on `web/mWeb` is also `20` ). :)
<details><summary>iOS safe area</summary>
<p>
<img width="738" alt="image" src="https://github.com/user-attachments/assets/3b52119d-3029-4462-8b6d-146b2437a911" />

</p>
</details> 

As for the animation implementation, I am still researching some optimizations and will update tomorrow once the changes are ready.

2025-02-03 18:38 UTC, abzokhattab commented on src/components/DecisionModal.tsx
>              <View style={[styles.m5]}>
Fair point

2025-02-05 17:29 UTC, lakchote commented
> I’ve been repeatedly testing approval and payment many many times this week, trying to address the flickering issue, and have made some progress. Also, I’ve fixed several small bugs on this PR locally. I expect to need one more workday to test and refine my suggestions. Finally, I apologize for the delay in the update, as I really don’t want to push the flickering issue to production. (since it doesn’t exist in production yet)

Thanks for the update. I agree about the flickering issue (we don't want it). Let's take a bit more time but make things right!

2025-02-10 15:27 UTC, abzokhattab commented
I like the new approach using Keyframe... regarding the local state—I removed it because of an issue where "Payment Complete" or "Approved" were no longer occurring. So, in my latest modifications, I removed it from my previous approach to clean up the code: [GitHub Commit](https://github.com/Expensify/App/pull/54490/commits/073ff3006a13603297384a30b1e030ff3bd6b6a4#diff-54e2ffcfb6ed6b1b50650f43a174b7c9509a7565ce969865e5306525c9e13013). 
However, this is not the root cause of the flickering issue 

Additionally, there's another issue (which I also see in the main branch) where, when the user clicks "Submit," it switches to "Approve," then back to "Submit," and then "Approve" again.


https://github.com/user-attachments/assets/e735ebc5-3f97-4d8d-aca6-48a4ed3e9e68

2025-02-11 21:19 UTC, abzokhattab commented
I reviewed it once more and i find another issue in the design, the approved and payment is complete doesnt have enough 

using the keyframe i am not able to adjust the time between the approve and approved state or from the pay to payment is complete 


also i notice that the loading bar is not shown as requested in the design


1. @shawnborton please check this comment and the screenshots provided by @ntdiary  [here](https://github.com/Expensify/App/pull/54490#issuecomment-2643720141) if the keyframe animation looks fine with the current animations then it should be fine
2. if we need to increase the time where the "approved" or the "payment is complete" shows, how can we do that i cannot change it because in the keyframe script there is only the fade out animation duration 

https://github.com/user-attachments/assets/3552e99a-175f-4b92-a4f2-1c53011f56da

2025-02-11 21:25 UTC, shawnborton commented
I'm not too familiar with how `keyframe` works, so let's get the opinion of an engineer on whether or not we should use it.

2025-02-12 14:36 UTC, dannymcclain commented
>I'm not too familiar with how `keyframe` works, so let's get the opinion of an engineer on whether or not we should use it.

Same here. I'm mostly concerned with smoothness and performance. I don't know that I have a strong opinion about the details of how we accomplish that.

2025-02-12 15:12 UTC, abzokhattab commented
> This is actually controlled by the canShow timeout. For example, if I adjust it to 1000 (i.e., CONST.ANIMATION_PAID_BUTTON_HIDE_DELAY), the effect in the release version will be like this:

correct i tried yesterday but maybe the device didnt render ... good i think we are ready now  .. i disabled the container shrinking when clicking on the approval ... can you please review the changes @ntdiary

2025-02-12 19:15 UTC, abzokhattab commented
> Prevent the container height shrinking on approval


for this issue i thought keyframe would act the same way as in the other way ... however after trying it for couple of times it seems that the height doesnt change so i removed this change in the recent commit 


other than that, there is an issue in the `DecisionModal` where the margin is cut off because of [this commit](https://github.com/Expensify/App/pull/54490/commits/7c2135bc14f99066f18d6b3d603460150fc0d3e9) 


<img width="1512" alt="Screenshot 2025-02-12 at 19 33 10" src="https://github.com/user-attachments/assets/96a42366-6bb6-44d7-8910-cfebb2b629eb" />

so i reverted this commit, let me know if u think otherwise @ntdiary 



With this i think we can go ahead with the review.

2025-02-12 20:09 UTC, shawnborton commented
Good catch, I'm not sure why the modal needs to be modified for this PR.

2025-02-12 21:30 UTC, abzokhattab commented
we modified it to address this comment https://github.com/Expensify/App/pull/54490#issuecomment-2589167661 https://github.com/Expensify/App/pull/54490#issuecomment-2612213735

2025-02-12 21:31 UTC, shawnborton commented
Hmm but the comment was just about the button size, not the margins on the modal itself right?

2025-02-12 21:32 UTC, shawnborton commented
Either way, we need to fix it.

2025-02-12 21:34 UTC, abzokhattab commented
Yes i reverted it, but it was a part of the alignment change https://github.com/Expensify/App/pull/54490#issuecomment-2612213735

2025-02-13 09:15 UTC, abzokhattab commented
done

2025-02-13 15:53 UTC, ntdiary requested changes
@abzokhattab, unfortunately, I’m still seeing the `height warning`, so I made some [changes](https://github.com/Expensify/App/pull/54490#discussion_r1954757786) to `AnimatedSettlementButton`, please feel free to test it locally first, and if everything works fine, you can replace it. I’ll make the full test videos and fill out the check list tomorrow.

Also, here are my latest test videos, I think it’s much smoother than before. :)

| position/case | normal | duplicate |
|--------|--------|--------|
| header | <video src="https://github.com/user-attachments/assets/6458690c-ea2c-4813-a769-08e4eac2c4e8" /> | <video src="https://github.com/user-attachments/assets/ca41f6ab-7e17-4674-9913-5496c788e354" /> |
| preview | <video src="https://github.com/user-attachments/assets/efd25e9e-a45e-48d4-bfae-1e773fb81ee7" /> | <video src="https://github.com/user-attachments/assets/ee7e9d7a-300f-47f4-89a3-315de2036da2" /> |

2025-02-13 22:34 UTC, abzokhattab commented
LGTM

2025-02-14 12:38 UTC, abzokhattab commented on src/CONST.ts
> +    ANIMATION_HIDE_DELAY: 200,
Cleaned

2025-02-14 17:09 UTC, shawnborton commented
Yeah, it seems like the sequence after Approve is successfully tapped on mWeb is that the button first goes wide:
![CleanShot 2025-02-14 at 12 08 08@2x](https://github.com/user-attachments/assets/822e96e6-a8c5-4ed1-bae1-f19823bf68d4)

Then it goes back to half-width:
![CleanShot 2025-02-14 at 12 08 43@2x](https://github.com/user-attachments/assets/49d7c780-38d0-4160-9d5e-0a9367ba9c92)

Then it shrinks down:
![CleanShot 2025-02-14 at 12 08 57@2x](https://github.com/user-attachments/assets/3ac4c73c-b245-4cfd-bfe0-07c3fea03744)

And then the whole Pay button appears:
![CleanShot 2025-02-14 at 12 09 10@2x](https://github.com/user-attachments/assets/e9bab3c3-085b-43f7-bb51-893624a309ca)


I think we could make this feel a lot smoother if we just didn't immediately remove the "Review duplicates" button and allowed it to stay in that 50% space while the approved button animates... then once the approved button animates out, replace that whole thing with the Pay button. Could we try something like that?

2025-02-14 17:10 UTC, shawnborton commented
And then it would be nice if we could do that on the native platforms too. I would be curious to see an option like that first.

2025-02-16 22:20 UTC, abzokhattab commented
@ntdiary, I fixed the bug on the web by removing the hidden overflow from the container styles. However, if we want to keep the duplicate button visible while it’s being animated, the review button overflows on top of the animated button. I'm still looking for a way to maintain the duplicate button during the animation. Please let me know if you have any ideas.






https://github.com/user-attachments/assets/139a53d6-f9f2-4b3b-973c-6beeb1db9753

2025-02-20 14:07 UTC, dannymcclain commented
@Expensify/design curious for your thoughts here. I mean it certainly works, but to me, it doesn't feel super great. Feels pretty slow and stutter-y, but maybe that's something we tackle as a follow-up since we have it working here?

2025-02-20 16:07 UTC, dannymcclain commented
>could you please share more which part you feel is slow and stutter-y? Is it the entire interaction and animation, or something like the button transition from Pay...elsewhere to Payment complete?

It's mostly all the button transitions—they feel pretty harsh and abrupt to me, but I totally recognize this is already much better than it was before and the issues I'm talking about are likely not in scope for this specific PR. I'd just like us to keep thinking about how we might make all of these feel more fluid and smooth instead of "jumping" between all the different states and button combinations (again, likely as a follow up to this).

2025-02-21 07:25 UTC, abzokhattab commented
@ntdiary 


I pushed two commits one for fixing the minWidth issue and the other for making the review duplicate button stays until the animation is finished 

Please review them and let me know if we need to change anything more


Here is the POC after the changes 


https://github.com/user-attachments/assets/2a96d51e-64c3-431d-888e-9f7a3781b437

https://github.com/user-attachments/assets/a478a4c7-e151-41bb-b997-9a7c0f9db7c5

2025-02-21 15:14 UTC, ntdiary requested changes
@abzokhattab, please fix the `import` statement error.
Also, if we really want to hide the "duplicate" button immediately after the "Approved" button scaling ends, changing the `isDuplicate` condition would be a better way than adding the new `showReviewDuplicates` state, e.g.,
```ts
    const isDuplicate = isDuplicateTransactionUtils(transaction?.transactionID) && (!isReportApproved({report: moneyRequestReport}) || isApprovedAnimationRunning);
```
Finally, let's wait and see if others also think this animation is ready to be merged. :)

https://github.com/user-attachments/assets/81a09dde-020e-4af3-93e6-84b6543455ee

2025-02-23 22:25 UTC, abzokhattab commented on src/components/MoneyReportHeader.tsx
> +    const [showReviewDuplicates, setShowReviewDuplicates] = useState(true);
Okay very good .. i covered this comment in the last commit

2025-02-24 15:50 UTC, ntdiary approved these changes
Recently, I tested hundreds of expenses, and personally think the current revision is ready to be merged. As for the performance optimizations mentioned [before](https://github.com/Expensify/App/pull/54490#issuecomment-2671849533), it would be better to address them in separate issues. :D

2025-03-03 09:25 UTC, lakchote approved these changes
LGTM!

2025-03-03 09:26 UTC, merged

2025-03-03 09:34 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2025-03-04 10:00 UTC, izarutskaya commented
@abzokhattab Found issue https://github.com/Expensify/App/issues/57721