[WIP] Align default IDs in IOU.ts file
Expensify/App pull request #54534
Opened 2024-12-24 16:23 UTC by VickyStash

### Explanation of Change

Align default IDs in IOU.ts file

### Fixed Issues

$ https://github.com/Expensify/App/issues/50360
PROPOSAL: https://github.com/Expensify/App/issues/50360#issuecomment-2405820991

### Tests

- [ ] Verify that no errors appear in the JS console

### Offline tests

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

2025-01-02 16:42 UTC, VickyStash commented on src/libs/actions/IOU.ts
> +            value: transactionThread?.parentReportActionID ? {[transactionThread.parentReportActionID]: {originalMessage: {whisperedTo: []}}} : null,
You are right! Updated: https://github.com/Expensify/App/pull/54534/commits/6c6026c010e64f7b8001e247dbd840983af5023f

2025-01-02 16:43 UTC, VickyStash commented on src/libs/actions/IOU.ts
> +            oneOnOneIOUReport = participant.policyID
It looks so
https://github.com/Expensify/App/blob/d4eaef9a08d90eed054ed158deeff00161b0464d/src/libs/actions/IOU.ts#L5351

2025-01-02 16:59 UTC, VickyStash commented on src/libs/actions/IOU.ts
> +            oneOnOneIOUReport = participant.policyID
There was a ts warning but it's not the case anymore - updated!

2025-01-02 17:29 UTC, VickyStash commented on src/libs/actions/IOU.ts
> +                [reportPreviewAction.reportActionID]: updatedReportPreviewAction,
Wrong type of reportPreviewAction confused me, updated https://github.com/Expensify/App/pull/54534/commits/64a3bb9cc21188ac53030b11732788add2bccd89

2025-01-02 19:55 UTC, VickyStash commented on src/libs/actions/IOU.ts
> +        // @ts-expect-error TODO: update buildOptimisticTransaction return type to indicate that reportID can be undefined
Updated: https://github.com/Expensify/App/pull/54534/commits/f6e9122ac763f622669be205ef6952e6722ec120

2025-01-03 09:50 UTC, VickyStash commented on src/libs/ReportUtils.ts
> +    if (!policyReportFields || !fieldList) {
I guess `policyReportFields` and `fieldList` won't be truly values if the `policyID` is undefined.
So this part was extra. But I can add an early return.

2025-01-03 10:36 UTC, VickyStash commented on src/ROUTES.ts
> +        getRoute: (policyID: string | undefined, backTo?: string) => getUrlWithBackToParam(`settings/workspaces/${policyID}/profile/address` as const, backTo),
There was one more similar discussion in the slack lately: [link](https://expensify.slack.com/archives/C01GTK53T8Q/p1735561423094949).

1. The approach with `undefined` doesn't change the app logic, considering the invalid `-1` id value was used before. In most of the cases the app behavior is left the same as before in this case - `Not Found` page is showing if you navigate to the page with invalid id.

2. Another approach is to add a condition above and prevent navigation to the invalid page, + add a `Log.warn` so it can be catched and investigated.
```
if (policyID) {
   Navigation.navigate(ROUTES.WORKSPACE_PROFILE_ADDRESS.getRoute(policyID));
} else {
   Log.warn("Invalid policyID .....")
}
```

I think we need to stop on one of the approaches and add it to the guide.

2025-01-03 11:08 UTC, VickyStash commented on src/ROUTES.ts
> +        getRoute: (policyID: string | undefined, backTo?: string) => getUrlWithBackToParam(`settings/workspaces/${policyID}/profile/address` as const, backTo),
@iwiznia @neil-marcellini what do you think?

2025-01-03 17:32 UTC, iwiznia commented on src/ROUTES.ts
> +        getRoute: (policyID: string | undefined, backTo?: string) => getUrlWithBackToParam(`settings/workspaces/${policyID}/profile/address` as const, backTo),
I think I rather navigate to the error page AND log a warning so we can investigate

2025-01-06 18:38 UTC, iwiznia commented on src/ROUTES.ts
> +        getRoute: (policyID: string | undefined, backTo?: string) => getUrlWithBackToParam(`settings/workspaces/${policyID}/profile/address` as const, backTo),
I don't see why not

2025-01-07 16:53 UTC, VickyStash commented on src/ROUTES.ts
> +        getRoute: (policyID: string | undefined, backTo?: string) => getUrlWithBackToParam(`settings/workspaces/${policyID}/profile/address` as const, backTo),
@paultsimura @fabioh8010 I'm going to prepare a PR with the guide update and will apply changes to this PR after that. Thank you!

2025-01-08 09:38 UTC, VickyStash commented
@paultsimura I've updated the PR, please take another look

2025-01-16 10:47 UTC, VickyStash commented
@paultsimura kind bump 🙂

2025-01-16 16:55 UTC, paultsimura approved these changes
LGTM ✔️ 
Tested carefully, but this is probably the most invasive PR as it touches IOU 😟

2025-01-17 08:11 UTC, VickyStash commented
@neil-marcellini maybe we can ask QA team for regression testing of this PR before merging, since it touches key functionality of the app?

2025-01-17 20:28 UTC, neil-marcellini requested changes
Wow, this is a lot of work. Mostly looks great. I have a few requests and several NAB comments.

2025-01-17 20:28 UTC, neil-marcellini commented on src/libs/actions/IOU.ts
> +                    )?.created,
NAB: Can we please extract out some variables to clean this up. It's so ugly looking, hurts my eyes and brain 🥲. It was worse before but could be a lot better.

2025-01-17 20:28 UTC, neil-marcellini commented on src/libs/actions/IOU.ts
> +            value: reportPreviewAction?.reportActionID ? {[reportPreviewAction.reportActionID]: updatedReportPreviewAction} : {},
NAB: For situations like these it would probably be better to not add the whole onyx update object, since it's merging an empty object which will do nothing. Instead we could push it onto the onyxData if we have a value.

2025-01-17 20:28 UTC, neil-marcellini commented on src/libs/actions/IOU.ts
> +            value: reportPreviewAction?.reportActionID ? {[reportPreviewAction.reportActionID]: updatedReportPreviewAction} : {},
Idk probably doesn't really matter, but it would be interesting to compare the performance in Onyx and see if it does make a difference.

2025-01-17 20:28 UTC, neil-marcellini commented on src/libs/API/parameters/CreateDistanceRequestParams.ts
> +    createdChatReportActionID: string | undefined;
This should be optional, chat reports aren't always created.

2025-01-17 20:28 UTC, neil-marcellini commented on src/libs/API/parameters/RequestMoneyParams.ts
> +    createdIOUReportActionID: string | undefined;
These should be optional, these reports aren't always created.

2025-01-17 20:28 UTC, neil-marcellini commented on src/libs/API/parameters/TrackExpenseParams.ts
> +    createdChatReportActionID: string | undefined;
This should be optional, chat reports aren't always created.

2025-01-17 20:28 UTC, neil-marcellini commented on src/libs/ReportUtils.ts
> +    policyID: string | undefined,
NAB: Are there times when we might not have a policyID and therefore it should be optional? Can invoices be sent between individuals without a policy involved?

2025-01-20 08:50 UTC, VickyStash commented on src/libs/actions/IOU.ts
> +                    )?.created,
Updated in https://github.com/Expensify/App/pull/54534/commits/1dbedd9bc0c8970a4887fd923f113a66b6509124

2025-01-20 08:54 UTC, VickyStash commented on src/libs/ReportUtils.ts
> +    policyID: string | undefined,
No, `policyID` isn't optional. Invoice can't be sent between individuals, only between workspace-individual(B2C) or workspace-workspace(B2B)

2025-01-20 11:59 UTC, VickyStash commented on src/libs/actions/IOU.ts
> +            value: reportPreviewAction?.reportActionID ? {[reportPreviewAction.reportActionID]: updatedReportPreviewAction} : {},
Updated not to merge empty objects: https://github.com/Expensify/App/pull/54534/commits/a91d701f1039e7d45384ce3f4ea29a2dedee8f5d

2025-01-21 18:48 UTC, neil-marcellini submitted a review, later dismissed

2025-01-21 20:20 UTC, neil-marcellini approved these changes

2025-01-21 20:21 UTC, merged

2025-01-21 20:29 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2025-01-23 21:28 UTC, IuliiaHerets commented
This PR is failing because of issue #55673