fix video dsoe not stop playing when going to inbox from search
Expensify/App pull request #54552
Opened 2024-12-25 09:23 UTC by mkzie2

### Explanation of Change

### Fixed Issues

$ https://github.com/Expensify/App/issues/54166
PROPOSAL: https://github.com/Expensify/App/issues/54166#issuecomment-2544861160

### Tests

1. Open any report and upload a video with sound
2. Go to Search page > Chats
3. Click on the video above to play

- On the large screen (web/desktop)

4. Click on the expand button
5. Verify that the video continues playing instead of another video being played
6. Close the attachment modal
7. Verify that the video continues playing
8. Go to the inbox
9. Verify that the video is stopped

- On the small screen (mweb/native)

4. After clicking on the video, verify that the video attachment modal is opened and the video is played
5. Close the attachment modal and verify that the video is stopped
- [x] Verify that no errors appear in the JS console

### Offline tests

None
### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."
1. Open any report and upload a video with sound
2. Go to Search page > Chats
3. Click on the video above to play

- On the large screen (web/desktop)

4. Click on the expand button
5. Verify that the video continues playing instead of another video being played
6. Close the attachment modal
7. Verify that the video continues playing
8. Go to the inbox
9. Verify that the video is stopped

- On the small screen (mweb/native)

4. After clicking on the video, verify that the video attachment modal is opened and the video is played
5. Close the attachment modal and verify that the video is stopped
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I ad [...]

2024-12-25 09:27 UTC, mkzie2 commented
The Eslint error isn't related to our changes.

2024-12-26 13:00 UTC, suneox commented
> The Eslint error isn't related to our changes.

Could you try to fix the ESLint issues following [this guideline](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#default-value-for-inexistent-ids)?

2024-12-30 04:50 UTC, mkzie2 commented on src/components/HTMLEngineProvider/HTMLRenderers/VideoRenderer.tsx
> +                            reportID={report?.reportID ?? '-1'}
@suneox We cannot remove the default value of reportID here, because if we do that we cannot play the video in the search page.

2025-01-01 16:33 UTC, suneox commented
@mkzie2  After playing a video in Reports/Chats, if you navigate to a report with a posted video and play it, both videos will play simultaneously.

Could you please take a look on this issue?

https://github.com/user-attachments/assets/10ab5bce-d2d3-4535-b7d4-2a0e5b6d977f

2025-01-01 16:42 UTC, suneox commented on src/components/HTMLEngineProvider/HTMLRenderers/VideoRenderer.tsx
> +                            reportID={report?.reportID ?? '-1'}
Can we remove `reportID` prop for  `VideoPlayerPreview` and only control the playing status by videoUrl with usePlaybackContext? If not, we can open a discussion and then add this file to `.eslintrc.changed.js` to ignore

2025-01-13 16:59 UTC, suneox commented
> @suneox I updated to fix this bug, please help to check again.

@mkzie2  It looks like after merging with the latest main branch, we cannot play videos in reports/chat on both latest staging & current PR branch. Could you please investigate the offending PR?


https://github.com/user-attachments/assets/e736a737-eacd-4a75-8eb0-0649f93d005a

2025-01-23 05:12 UTC, suneox commented
> @suneox I fixed the video play in search. Please help to check again.

Thanks for the update, i'll review it today

2025-01-27 08:47 UTC, suneox commented
@mkzie2 Could you please check after navigate between inbox & chat report the video still playing simultaneously?

https://github.com/user-attachments/assets/a5600ecd-a3c6-4045-a1e4-dece39f7d7ed

2025-02-14 04:09 UTC, suneox commented on src/components/VideoPlayer/BaseVideoPlayer.tsx
> +                                                    // playVideo();
Do we need to prevent `playVideo` on this line while we already have additional condition checks at [isCurrentlyURLSet](https://github.com/Expensify/App/pull/54552/files#diff-e8a3241440502ed6c70db5702f3f432fd79c24f1bf2d16c4a0a44ced176f51a5R93)?

2025-02-14 15:46 UTC, suneox commented
@mkzie2 The issue is not fixed in your latest commit [393c10a](https://github.com/Expensify/App/pull/54552/commits/393c10a9e1a8538f82cddcf6ffef779b4263405f). After navigating to the inbox, I am unable to play videos in chat.


https://github.com/user-attachments/assets/141fea99-679e-41e0-97d7-88c53371ca15

2025-02-16 05:50 UTC, suneox commented
@mkzie2 Thank you for the quick update! It looks almost done. Could you please handle the control of the playing state on the video inline controller?

https://github.com/user-attachments/assets/fd1222ab-3053-4c05-bc2a-e4fb7e116bdb

We have a different playing state when playing from the inline controller, this issue doesn’t occur on the latest staging.

2025-02-17 18:37 UTC, suneox commented
> @suneox Works well now, please help to check again.

@mkzie2 Could you please re-verify on all platforms? It looks like it doesn't work on MacOS/Safari.

https://github.com/user-attachments/assets/690171cf-bb10-4100-b8c1-d7ce716b285d

2025-02-19 06:16 UTC, suneox commented
@mkzie2  Could you please reply to this Slack open-source [thread](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1739945355032849)?

cc: @dominictb

2025-02-20 15:40 UTC, suneox commented
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] For any bug fix or new feature in this PR, I verified that sufficient [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) are included to prevent regressions in this flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>


https://gi [...]

2025-02-20 16:52 UTC, suneox approved these changes

2025-02-20 17:57 UTC, aldo-expensify requested changes
Looking good, just a minor correction

2025-02-20 18:59 UTC, aldo-expensify commented
> @aldo-expensify It's fixed.

Thank you!

2025-02-20 18:59 UTC, aldo-expensify approved these changes

2025-02-20 19:15 UTC, merged

2025-02-20 19:26 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2025-03-26 12:12 UTC, Pujan92 commented on src/components/VideoPlayerContexts/PlaybackContext.tsx
> +        if ((!currentReportID && isReportTopmostSplitNavigator()) || (!prevCurrentReportID && !isReportTopmostSplitNavigator()) || currentReportID === prevCurrentReportID) {
This caused the issue https://github.com/Expensify/App/issues/57285, as navigation might not be initialized