[HOLD Auth 5973] Remove password requirement for setting up withdrawal account
Expensify/App pull request #5545
Opened 2021-09-27 22:46 UTC by Jag96

### Details
Per [this thread](https://expensify.slack.com/archives/C020EPP9B9A/p1632722241230600) we want to remove the password requirement for adding a withdrawal account. This PR updates the UI to not include the password field for the `Company Step`, and removes the password param for the `BankAccount_SetupWithdrawal` API call.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/179271

### Tests
0. If https://github.com/Expensify/Auth/pull/5973 isn't merged, check out that branch to test locally
1. Create a new account and create a workspace
2. Click `Get Started` to go through the VBA flow, follow https://stackoverflow.com/c/expensify/questions/342/525#525
3. Confirm that when you get to the `Company Information` step, the password field doesn't appear
<img src='https://user-images.githubusercontent.com/3981102/134993898-93ac7daf-d128-4e3c-9d00-19ef3888b840.png' width='400'/>
4. Confirm you can submit the form, and that there is no error regarding the password

### QA Steps
Tag @Jag96 and I can run through the QA steps for this on staging

### Tested On
- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots
Screenshot in the tests section

2021-09-28 20:55 UTC, Jag96 commented
@jasperhuangg is at 20% this week so requesting another reviewer. The Auth PR has been merged so the code can be reviewed and tested on dev, waiting to remove the hold until after the auth deploy.

2021-09-29 09:35 UTC, pecanoro requested changes

2021-09-29 09:35 UTC, pecanoro commented on src/pages/ReimbursementAccount/CompanyStep.js
> -            password: 'common.passwordCannotBeBlank',
If the `common.passwordCannotBeBlank` copy is not being used anymore, can you remove it as well from the corresponding files?

2021-09-29 18:23 UTC, jasperhuangg approved these changes

2021-09-29 19:05 UTC, pecanoro approved these changes

2021-09-30 05:19 UTC, ctkochan22 approved these changes

2021-09-30 16:49 UTC, Jag96 commented
[Auth PR](https://github.com/Expensify/Auth/pull/5973#issuecomment-930653336) has been deployed, taking off hold

2021-09-30 16:49 UTC, merged

2021-09-30 18:04 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1291947748) to staging by @Jag96 in version: 1.1.3-4 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-09-30 20:12 UTC, isagoico commented
@Jag96 Helloo! Following orders from QA steps and tagging you for QA 🙇

2021-10-01 19:15 UTC, chiragsalian commented
@Jag96, Is this possibly a regression? On dev, it seems like we're unable to go beyond step 2. The UI doesn't show any error for me but the network request says "401 error",
![image](https://user-images.githubusercontent.com/14356145/135674072-93102381-19f8-46ef-aa80-b51ec8a1fafb.png)

@luacmartins tried the same on his end and got,
![image](https://user-images.githubusercontent.com/14356145/135674659-d3c17b6b-918b-4047-8bb4-27de2489bfc3.png)

2021-10-01 19:16 UTC, luacmartins commented
Adding to this, I do see the UI error `Incorrect Expensify password entered`.

2021-10-01 20:07 UTC, chiragsalian commented
Btw i just tested this on staging and it doesn't have password field,
![image](https://user-images.githubusercontent.com/14356145/135680191-29f316ed-a857-4aac-ad3e-8ab9e97a987d.png)

and it clears through just fine on staging,
![image](https://user-images.githubusercontent.com/14356145/135680231-75f8e353-74a7-4640-8bc5-a0b616e28df0.png)

I'm not sure why it failed on dev for me just yet.

2021-10-01 23:18 UTC, chiragsalian commented
Okay, nvm me. I did an updateRepos all and makeAll and once i retested it worked fine for me on dev.

2021-10-04 18:38 UTC, luacmartins commented
Same here, just had to update all the repos! Sorry for the false alarm!