Change style for TextInput area
Expensify/App pull request #5704
Opened 2021-10-06 21:35 UTC by AlfredoAlc

### Details

Set `selectable` prop in `ExpensiTextInputLabel` to `false`.
Move `padding` props from `expensiTextInputContainer` to `expensiTextInput` to prevent the `TextInput` to switch between blur and focus when clicking in the text label.

### Fixed Issues

$ https://github.com/Expensify/App/issues/4515

### Tests

1. Open profile page.
2. Clear the `First Name` text input.
3. Focus the text input.
4. Press inside the `text input container`, it shouldn't blur nor select the text input label

### QA Steps

### Tested On

- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

<img width="2048" alt="Web screenshot" src="https://user-images.githubusercontent.com/53409604/136286632-6154c1b5-031c-4f07-b95a-240ab0c0af00.png">

#### Desktop

<img width="2048" alt="Desktop screenshot" src="https://user-images.githubusercontent.com/53409604/136286530-7df4eb3a-3162-4f20-88d8-d1bbedc9fa26.png">

2021-10-07 18:08 UTC, parasharrajat requested changes
Why is `package-lock.json` changed? It should have not been changed. please revert it.

And don't worry about the CLA checks. As soon as the assigned engineer will trigger the actions, they will be all :heavy_check_mark: .

2021-10-07 18:41 UTC, AlfredoAlc commented
It was modified when ran `npm install`, I forgot to revert that change.

I already revert the file.

2021-10-07 19:27 UTC, parasharrajat approved these changes
~LGTM~. It will be merged after n6-hold is lifted.

2021-10-07 20:12 UTC, parasharrajat requested changes
Sorry, found a regression 
Input on search page got affected by this.

![image](https://user-images.githubusercontent.com/24370807/136455367-692073b0-a53f-4190-9672-300871b151b6.png)

2021-10-08 05:56 UTC, parasharrajat requested changes
A minor lint issue otherwise looks good.

2021-10-08 05:56 UTC, parasharrajat commented on src/components/ExpensiTextInput/BaseExpensiTextInput.js
> +                                style={[inputStyle, !hasLabel && styles.pv0,]}
No Trailing comma here.

2021-10-08 17:13 UTC, AlfredoAlc commented on src/components/ExpensiTextInput/BaseExpensiTextInput.js
> +                                style={[inputStyle, !hasLabel && styles.pv0,]}
Great, let me remove that comma.

2021-10-08 17:33 UTC, parasharrajat approved these changes, later dismissed
LGTM. 

Ready for final review and merge when n6-hold is lifted.

2021-10-12 21:03 UTC, timszot requested changes
Code looks good to me, but you have conflicts now. Please resolve those and this should be ready for merge.

2021-10-12 21:42 UTC, parasharrajat approved these changes

2021-10-12 21:52 UTC, timszot approved these changes

2021-10-12 23:05 UTC, merged

2021-10-12 23:06 UTC, OSBotify commented
@AlfredoAlc, Great job getting your first Expensify/App pull request over the finish line! :tada:

I know there's a lot of information in our [contributing guidelines](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md), so here are some points to take note of :memo::

1. Now that your first PR has been merged, you can be hired for another issue. Once you've completed a few issues, you may be eligible to work on more than one job at a time. 
2. Once your PR is deployed to our staging servers, it will undergo quality assurance (QA) testing. If we find that it doesn't work as expected or causes a regression, you'll be responsible for fixing it. Typically, we would revert this PR and give you another chance to create a similar PR without causing a regression.
3. Once your PR is deployed to _production_, we start a 7-day timer :alarm_clock:. After it has been on production for 7 days without causing any regressions, then we pay out the Upwork job. :moneybag:

So it might take a while before you're paid for your work, but we typically post multiple new jobs every day, so there's plenty of opportunity. I hope you've had a positive experience contributing to this repo! :blush:

2021-10-13 23:37 UTC, marcaaron commented
Probably we want something more like this?
<img width="358" alt="2021-10-13_13-36-51" src="https://user-images.githubusercontent.com/32969087/137227051-8c3ae825-b0d8-42f6-b9f8-4e4cfcd81925.png">

2021-10-15 13:50 UTC, parasharrajat commented
@AlfredoAlc Another regression I found is that label is messing up with the Multiline TextInput. 

![Screenshot 2021-10-15 19:19:46](https://user-images.githubusercontent.com/24370807/137498041-1646ca64-2840-4c1b-84f5-dbf996591b3e.png)

Also, the right corner is overflowing the right edges.

2021-10-15 22:44 UTC, AlfredoAlc commented
@parasharrajat  I suggest adding a background to the label, since the label is an `Animated.Text` if a background is set, it doesn't fill the whole space where it is, so I added a `View` with a white background. But, when it is autofilled the area of the label stays white. See attached video.

https://user-images.githubusercontent.com/53409604/137561773-66887ab2-12ec-4f68-80bf-76c2e2ed1b1f.mov

Let me know if this change is OK, so I can create a new PR with this solution.
Also, I couldn't reproduce the right corner overflowing.

2021-10-19 14:58 UTC, parasharrajat commented
Initially, I was thinking the same but It does not look good. Do you have any other way of fixing it? We can rethink the original solution as well.

Meanwhile, I will try to find someting.

2021-10-20 02:53 UTC, AlfredoAlc commented
@parasharrajat  I will create a new PR with this approach.

2021-10-20 02:57 UTC, parasharrajat commented
Thanks. You can comment on the main issue.

2021-10-23 00:42 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1374284625) to production by @roryabraham in version: 1.1.8-9 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅