[Hold N6] Copy Option Enabled for small screen devices also
Expensify/App pull request #5746
Opened 2021-10-10 19:14 UTC by Santhosh-Sellavel

### Details
Just enabled copy email/phone number options for small screen devices.

### Fixed Issues

$ https://github.com/Expensify/App/issues/4905

### Tests & QA Steps
1. Go to any user chat.
2. Navigate to user details by a tap on the chat header
3. Now copy option will be shown for email/phone.

### Tested On
- [x] Mobile Web
- [x] iOS
- [x] Android

### Screenshots

#### Mobile Web
![mWeb_01](https://user-images.githubusercontent.com/85645967/136709981-2bbd87a2-d4a7-44e1-9759-3e824aa44b26.png)

#### iOS
https://user-images.githubusercontent.com/85645967/136709986-693ad4a9-e2ef-41b0-8db5-0e94d09f85b4.mp4

#### Android
![Android-03](https://user-images.githubusercontent.com/85645967/136709995-bdcfc246-d054-43ec-9c10-0296682f3ad8.png)

2021-10-11 08:36 UTC, parasharrajat commented
@Santhosh-Sellavel Could you please test it on the other remaining platforms?

2021-10-11 19:00 UTC, parasharrajat requested changes

2021-10-11 19:32 UTC, parasharrajat approved these changes
LGTM. 

Ready for final review after n6-hold is lifted. cc. @Luke9389

2021-10-19 17:59 UTC, Luke9389 approved these changes

2021-10-19 17:59 UTC, merged

2021-10-19 18:00 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-10-23 01:32 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1374292176) to staging by @Luke9389 in version: 1.1.8-10 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅