Don't dismiss the Reimbursement Account Page after validating a withdrawal account
Expensify/App pull request #5803
Opened 2021-10-13 06:44 UTC by yuwenmemon

@luacmartins please review

### Details
Make sure we don't close the Reimbursement Account Page after validating a withdrawal account, regardless if you have the Expensify Card or not.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/180851

### Tests
1. Create workspace
2. Go to `connect bank account` page
3. Select `Connect bank account` and use steps in [option (1) of this SO](https://stackoverflow.com/c/expensify/questions/342/525#525)
4. Enter validation amounts to finalize setup
5. Make sure that the right docked modal stays open after you finish the setup.
![Kapture 2021-10-13 at 11 32 21](https://user-images.githubusercontent.com/4741899/137192990-71068c1a-e48f-4035-9d7c-125fe5a1fbae.gif)

2021-10-13 07:59 UTC, MariaHCD submitted a review, later dismissed

2021-10-13 16:24 UTC, luacmartins requested changes
Code LGTM and it tested well. Could we just address some of the later comments in the issue?

1. [Remove growl](https://github.com/Expensify/App/blob/7dd3d27e855614b78ba45d8f1b635e2f6afb2fe2/src/libs/actions/BankAccounts.js#L569)
2. Change `Save & continue` button to `Finish setup`

2021-10-13 19:22 UTC, luacmartins approved these changes
Thank you so much for this!

2021-10-13 19:23 UTC, merged

2021-10-14 01:33 UTC, OSBotify commented
🚀 [Cherry-picked](https://github.com/Expensify/App/actions/runs/1338968109) to staging by @luacmartins in version: 1.1.7-10 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

@Expensify/applauseleads please QA this PR and check it off on the [deploy checklist](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3AStagingDeployCash) if it passes.

2021-10-23 00:42 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1374284625) to production by @roryabraham in version: 1.1.8-9 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅