Bubble API errors up.
Expensify/App pull request #588
Opened 2020-10-02 23:28 UTC by alex-mechler

@marcaaron and @cead22 will you review please?

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/142656

### Tests
1. Signed in
1. Sent a message
1. Signed out
1. Signed in again

### Screenshots
n/a

2020-10-05 14:36 UTC, tgolen submitted a review, later dismissed

2020-10-05 15:35 UTC, cead22 submitted a review, later dismissed

2020-10-05 22:09 UTC, marcaaron requested changes

2020-10-05 23:55 UTC, marcaaron submitted a review, later dismissed
LGTM

2020-10-06 23:43 UTC, cead22 submitted a review, later dismissed

2020-10-06 23:58 UTC, marcaaron submitted a review, later dismissed

2020-10-07 00:23 UTC, cead22 submitted a review, later dismissed

2020-10-09 00:59 UTC, cead22 approved these changes

2020-10-09 01:22 UTC, marcaaron approved these changes

2020-10-14 17:56 UTC, Jag96 approved these changes

2020-10-14 17:58 UTC, merged