Added Workspace Menu
Expensify/App pull request #5921
Opened 2021-10-17 19:04 UTC by mananjadhav

@chiragsalian 

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/5185

### Tests

### QA Steps

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-10-17 19:10 UTC, mananjadhav commented
Hi @chiragsalian,
I've got the whole PR ready except for the delete API call.

One major question is, I was trying to get the latest pull and it turns out I am not able to access this component. Did we change the flow? 

![image](https://user-images.githubusercontent.com/3069065/137641438-eca9f21a-4c3b-4232-9766-b2542296ee24.png)

This is the sidebar I see on click. Does the component have to be moved to this one?

2021-10-21 03:23 UTC, mananjadhav commented
@chiragsalian  Were you able to check the questions in the previous comment ?

2021-11-02 20:30 UTC, mananjadhav commented
@chiragsalian I've made updates to the PR and currently testing. Can you help with one last thing? 

```
return Onyx.set(`${ONYXKEYS.COLLECTION.POLICY}${response.policyID}`, null);
```

I am using the above code to unset the value for the policy.  How do I delete a key from Onyx?

2021-11-05 00:51 UTC, chiragsalian commented
So there is no way to delete a key from Onyx atm. We usually just set it to empty string or null just as you have.
So your code looks good. The only thing i would say is that i don't think request returns a policyID so that code of yours should most likely be,
```
return Onyx.set(`${ONYXKEYS.COLLECTION.POLICY}${policyID}`, null);
```
Once you update that just make sure to test that setting it to null doesn't break anything else 🙂

2021-11-08 15:24 UTC, mananjadhav commented
@chiragsalian finally the PR complete but for some reason, E2E iOS Tests failed.

2021-11-14 04:30 UTC, mananjadhav commented
@chiragsalian Reminder.

I'll resolve the conflicts once the review is complete. `WorkspaceInitialPage` is a functional component so even the smallest change is conflicting and I have to fix it all over again.

2021-11-16 20:14 UTC, chiragsalian commented
Sorry for the delay. Last week i was really busy with other tasks and then i was on vacation for a few days. Now I'm back 100%. Looking into this. Hmm, the E2E test failure looks odd. As a first step, whenever there is an unusual travis test failure first re-run the test, and then update branch with main branch (you can do just the latter if you want since it will trigger travis test). Anyway i've re-run the job. Let's see if it fails at the same spot. I'll review the code in the meantime.

2021-11-16 21:05 UTC, chiragsalian requested changes
Tested the PR. I'm facing a few issues,
1. The options show up beyond the screen,
![image](https://user-images.githubusercontent.com/14356145/142062957-150a2740-29f4-4aff-81fc-d35a19ca3223.png)
(To reproduce the above, refresh the page, click on your profile icon->workspace->3 dots to see the problem. If you refresh the page while in the workspace view the issue doesn't happen)
2. The moment a new workspace is created the URL show the reportID i.e., http://localhost:8080/r/255 for me instead of the workspace policyID url i.e., http://localhost:8080/workspace/52E30B06BC2CE462 (the only way to get the correct URL is by closing the workspace menu and opening it again which is weird)
3. Deleting a workspace doesn't clear the data in localstorage so clicking on the profile icon still shows the deleted workspace which should be corrected.

2021-11-16 21:05 UTC, chiragsalian commented on src/libs/actions/Policy.js
> +function deletePolicy(policyID = '', shouldGrowl = true, shouldAutomaticallyReroute = true) {
Why is policyID optional? It shouldn't be since the backend needs a policyID to know what to delete.

2021-11-16 21:05 UTC, chiragsalian commented on src/libs/actions/Policy.js
> +function deletePolicy(policyID = '', shouldGrowl = true, shouldAutomaticallyReroute = true) {
I don't see shouldGrowl and shouldAutomaticallyReroute passed when we call this method. If that's the case let's not preoptimize here and remove these two params from the method call and just do the growl and reroute in the method. In future if there is a scenario to not show growl or reroute then we'll update as needed.

2021-11-16 21:05 UTC, chiragsalian commented on src/libs/actions/Policy.js
> +            return Onyx.set(`${ONYXKEYS.COLLECTION.POLICY}${policyID}`, null);
i believe you are missing the underscore `_` between your policy and policyID thats why the actual onyx variable is not getting cleared which is why i can still see the workspace after deleting it.

2021-11-20 22:15 UTC, mananjadhav commented
@chiragsalian: PR Updated with the changes. About the two issues:

1. It seems to be happening due to `Navigation.dismissModal()` in `Policy.js:navigateToPolicy` method. If I remove the `dismissModal` call, it works fine. I am not sure why it was added. Can you confirm?

2. I had this issue when I raised the first draft, but not later when I submitted with screenshots. Tried creating multiple workspaces and it didn't end into a loop. Can you take the latest pull and check?

2021-11-26 22:03 UTC, mananjadhav commented
@chiragsalian Any updates for me on this one? As I've mentioned earlier I'll resolve conflicts once all review is complete or when there are changes. I keep getting conflicts because I've updated the function component to class component.

2021-11-30 00:24 UTC, chiragsalian commented
Sorry yes, I was out for Thanksgiving week. Checking this now.

2021-11-30 00:49 UTC, chiragsalian commented
> It seems to be happening due to Navigation.dismissModal() in Policy.js:navigateToPolicy method. If I remove the dismissModal call, it works fine. I am not sure why it was added. Can you confirm?

My guess is because earlier we use to show a large full screen modal and when we clicked new workspace there we wanted the modal to close. But we don't show that full-screen modal anymore so i'm pretty sure you are safe to remove it. Its usages are also only in two spots so it should be easy enough to confirm if everything runs fine.

> I had this issue when I raised the first draft, but not later when I submitted with screenshots. Tried creating multiple workspaces and it didn't end into a loop. Can you take the latest pull and check?

Cool on investigation it looks like its not because of your PR and the issue lies elsewhere.

2021-11-30 01:01 UTC, chiragsalian approved these changes, later dismissed
Changes LGTM. Feel free to address the conflicts and then i can merge your PR 👍

2021-11-30 12:09 UTC, mananjadhav commented
> Sorry yes, I was out for Thanksgiving week. Checking this now.

@chiragsalian  No problem. Thanks for the reviewing, PR updated.

2021-11-30 19:11 UTC, chiragsalian approved these changes
LGTM and works well. Thank you for the changes.

2021-11-30 19:12 UTC, merged

2021-11-30 19:12 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-12-07 00:21 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1547012777) to staging by @chiragsalian in version: 1.1.17-8 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-12-08 20:13 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1555704648) to production by @roryabraham in version: 1.1.18-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-12-16 00:20 UTC, marcaaron commented
>My guess is because earlier we use to show a large full screen modal and when we clicked new workspace there we wanted the modal to close. But we don't show that full-screen modal anymore so i'm pretty sure you are safe to remove it. Its usages are also only in two spots so it should be easy enough to confirm if everything runs fine.

It was actually because when creating a new workspace via the `LogInWithShortLivedTokenPage` we must dismiss the modal that shows a loading spinner here:

https://github.com/Expensify/App/blob/6433741e0080f9767602829871c1ea34d4ec6de3/src/pages/LogInWithShortLivedTokenPage.js#L92

And the removal of the call to `dismissModal()` broke this is not obvious ways e.g.

https://github.com/Expensify/Expensify/issues/188048

This was probably hard (maybe impossible) to see because the line from `LoginWithShortLivedTokenPage` to policy creation (and which modal needs to be dismissed) isn't super clear.

cc @roryabraham @ctkochan22

2021-12-16 02:48 UTC, mananjadhav commented
@marcaaron Then should I add a param to the function and add the `Navigation.dismissModal` back.

2021-12-16 02:57 UTC, marcaaron commented
No worries @mananjadhav we'll take care of it.

2021-12-16 03:16 UTC, mananjadhav commented
Thanks, @marcaaron. Do let me know if any help is required.