Use sublocality when locality is missing - AddressSearch
Expensify/App pull request #5950
Opened 2021-10-19 18:02 UTC by aldo-expensify

### Details
There are addresses that have the component "locality" missing. We use the "locality" as the city. This PR will make us use the "sublocality" as the city when the "locality" is missing.

### Fixed Issues

$ https://github.com/Expensify/App/issues/5867

### Tests / QA Steps

1. Create account in NewDot, verify it and log in
2. Create Workspace
3. Start add VBA flow and get to the "Company information" step (/bank-account/company)
4. Input in the "Company address" field: `64 Noll Street, Brooklyn, NY, USA` and select the first (and only) result
5. Fill the rest of the fields
6. You should be able to continue to the next step without errors.

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-10-19 21:23 UTC, roryabraham requested changes
> Do console.debug logging eventually reach our logging servers?

Nope, please use the [`Log` library](https://github.com/Expensify/App/blob/main/src/libs/Log.js). See [this PR](https://github.com/Expensify/App/pull/5827).

2021-10-19 22:13 UTC, aldo-expensify commented
> Nope, please use the [`Log` library](https://github.com/Expensify/App/blob/main/src/libs/Log.js). See [this PR](https://github.com/Expensify/App/pull/5827).

Thanks, I would think these logs are interesting enough to be sent to the server. They may eventually reveal other problematic cases that we don't know about, sounds correct?

2021-10-19 22:22 UTC, aldo-expensify commented
Update: Changed `console.debug` for `Log.hmmm`

2021-10-19 23:59 UTC, roryabraham reviewed
Log changes look good. Let's add some unit tests for this!

2021-10-19 23:59 UTC, roryabraham commented on src/components/AddressSearch.js
> +                Log.hmmm('Replacing missing locality with sublocality: ', {address: details.formatted_address, sublocality: city});
I would add the `[AddressSearch]` prefix here as well.

2021-10-20 00:13 UTC, aldo-expensify commented
> Log changes look good. Let's add some unit tests for this!

Thanks for the review, I'll be looking into the testing stuff tomorrow to finish this up!

2021-10-21 00:33 UTC, aldo-expensify commented on tests/unit/GooglePlacesUtilsTest.js
> +                formatted_address: 'Quail Ridge Rd, Escondido, CA 92027, USA',
I left this here even if it not used in the tests just as a way to remember these addresses that gave up problems.

2021-10-21 00:55 UTC, aldo-expensify commented
hmm, any ideas on why this could be happening? 

![Uploading Screen Shot 2021-10-20 at 5.54.49 PM.png…]()

2021-10-21 14:52 UTC, TomatoToaster commented
Seems unrelated to your changes, @aldo-expensify, try merging the main branch into your PR, it might fix that issue.

2021-10-22 22:58 UTC, roryabraham requested changes
Thanks for adding these tests, that's huge. Just had some minor suggestions.

2021-10-22 23:33 UTC, roryabraham requested changes
Sorry, one last thing 😅

2021-10-22 23:45 UTC, roryabraham approved these changes

2021-10-23 00:31 UTC, merged