feature: Background updates on mobile
Expensify/App pull request #5953
Opened 2021-10-19 22:19 UTC by mananjadhav

cc - @Julesssss 

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/4264

### Tests

### QA Steps

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-11-07 14:35 UTC, Julesssss commented
> Sure. Quick question outside the PR, do we have a process where if contributors want to go on vacation they can notify?

We don't at the moment, but I don't think it's a problem here as I've caused some delays here myself.

2021-12-09 11:59 UTC, Julesssss commented
Hey @mananjadhav. Once again, sorry for my long delay here. Now that I'm back and caught up I will make sure not to delay us again. 

Do you remember what exactly was failing? I'm seeing a lot of these errors in both iOS and Android:

![Screenshot 2021-12-09 at 11 40 19](https://user-images.githubusercontent.com/10736861/145390089-70852316-3b7d-48f3-97cf-fe003a87e7e4.png)

2021-12-09 12:26 UTC, mananjadhav commented
I'll check and get back to you. But as far as I remember the task was getting initialized but was getting timed out.

2021-12-10 19:42 UTC, kidroca requested changes
Left some notes mostly on changes that shouldn't have been committed

2021-12-10 19:42 UTC, kidroca commented on index.js
> +    // Get task id from event {}:
The task should not be defined here in `index.js`
It should be defined in `libs` and then registered during `setup` or in `Expensify.js` `didMount` phase

---

I see this is already done, and there's a lib about this, so the code here seems like a leftover that should be removed

2021-12-10 19:42 UTC, kidroca commented on ios/NewExpensify.xcodeproj/project.pbxproj
> +						ProvisioningStyle = Automatic;
This should probably be reverted

2021-12-10 19:42 UTC, kidroca commented on ios/NewExpensify.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 72TRNPHV7D;
This should definitely be reverted

2021-12-10 19:42 UTC, kidroca commented on ios/NewExpensify.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
This should definitely be reverted

2021-12-10 19:42 UTC, kidroca commented on ios/NewExpensify.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 72TRNPHV7D;
This should definitely be reverted

2021-12-10 19:42 UTC, kidroca commented on ios/NewExpensify.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "";
This should definitely be reverted

2022-01-11 10:43 UTC, merged

2022-01-11 10:43 UTC, botify commented
@robertjchen looks like this was merged without passing tests. Please add a note explaining why this was done and remove the `Emergency` label if this is not an emergency.

2022-01-11 10:47 UTC, robertjchen commented
Wait, what happened here? I merged https://github.com/Expensify/App/pull/6641 but somehow this was merged as well? 🤔

2022-01-11 10:48 UTC, robertjchen commented
I'm going to revert this- this was not supposed to be merged.

2022-01-11 10:52 UTC, Julesssss commented
Wow, that was unexpected! 

It's my fault, as [my PR](https://github.com/Expensify/App/pull/5953) accidentally branched from this PR. I made a lot of changes and rebased a couple of times, which made removing these commits very time-consuming (I didn't notice this immediately).

I'll get this PR reverted

2022-01-11 10:53 UTC, mananjadhav commented
Wooahh, let me close this PR and raise one more as draft that shouldn't have allow merging?

2022-01-11 11:02 UTC, Julesssss commented
Hi @mananjadhav. Don't worry, I think you can just create a new PR. You might need to cherry-pick the commits though, so they have a new commit ID.

I had a large PR that accidentally branched from yours, I tried to rebase them away but was unsuccessful as it was such a large PR with many conflicts over the last month.  

I think the draft status was ignored by Github as technically your commits are now in `main` -- but they are not aware that I reverted in my later commits

2022-01-11 11:04 UTC, mananjadhav commented
I'll cherry-pick or move the commits as a fresh set of changes. Tracking my branch separately.

2022-01-11 11:13 UTC, Julesssss commented
Thanks, @mananjadhav. Sorry for the confusion.