Removes onTransitionEnd callback
Expensify/App pull request #5965
Opened 2021-10-20 21:15 UTC by AlfredoAlc

### Details

Removes `onTransitionEnd` callback where the focus is set to `TextInput`.

### Fixed Issues

$ https://github.com/Expensify/App/issues/5403

### Tests

1. Sign in to [New Expensify](new.expensify.com) with any account.
2. Navigate to Settings.
3. Click on Payments.
4. If no Paypal account is added, add one.
5. Click on Paypal account.
6. Verify that the name is not autofocused.

### QA Steps

1. Sign in to [New Expensify](new.expensify.com) with any account.
2. Navigate to Settings.
3. Click on Payments.
4. If no Paypal account is added, add one.
5. Click on Paypal account.
6. Verify that the name is not autofocused.

### Tested On

- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

https://user-images.githubusercontent.com/53409604/138172338-c1d855bf-a80f-43c1-a280-ef3fa011a38b.mov

#### Desktop

https://user-images.githubusercontent.com/53409604/138172349-91151c47-26e4-47e3-b6f7-4c435277ba6b.mov

#### iOS

https://user-images.githubusercontent.com/53409604/138173222-e22a537d-dad1-4469-a000-1e9497b4ed2f.mp4

#### Android

https://user-images.githubusercontent.com/53409604/138173017-d20b3048-e62d-4da7-bee4-e10faee29dd9.mov

2021-10-20 23:31 UTC, Luke9389 requested changes
It doesn't look like the `paypalUsernameInputRef` is used anywhere else, so you can take it out of the constructor and the ExpensiTextInput.

2021-10-20 23:53 UTC, Luke9389 approved these changes

2021-10-20 23:54 UTC, Luke9389 commented
Went to go see what's going on with the iOS test, looks like we have some versioning issues.

2021-10-21 00:57 UTC, parasharrajat requested changes
This PR is going against the issue and the proposal. It should place the cursor at the end instead of removing the autofocus.

cc: @Luke9389

2021-10-21 01:00 UTC, AlfredoAlc commented
@parasharrajat It was later discussed that it would be better to remove the autofocus.
https://github.com/Expensify/App/issues/5403#issuecomment-942594654

2021-10-21 01:37 UTC, Luke9389 commented
I've got a PR up to fix the iOS tests. Once that's merged you should be able to pull master and we can get this squared away.

2021-10-21 01:53 UTC, AlfredoAlc commented
@Luke9389  Thanks for keeping me updated!

2021-10-21 18:45 UTC, Luke9389 approved these changes

2021-10-21 18:57 UTC, parasharrajat reviewed
LGTM based on new proposal.

2021-10-21 18:57 UTC, parasharrajat approved these changes

2021-10-21 19:15 UTC, merged