Add Payment Method fill when menu is active
Expensify/App pull request #5981
Opened 2021-10-21 19:11 UTC by Santhosh-Sellavel

### Details
Add fill background to `Add Payment method` when payment options are active.

### Fixed Issues

$ https://github.com/Expensify/App/issues/5915

### Tests & QA Steps
1. Go to Settings > Payments
2. Tap or click on the `Add Payment Method` button
3. Payment options will be shown, also now `Add Payment Method` will have active background fill

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web
<img width="1440" alt="Screenshot 2021-10-23 at 12 32 07 AM" src="https://user-images.githubusercontent.com/85645967/138569122-8888459e-be40-42e6-8854-b7444a896f24.png">

#### Mobile Web
![Simulator Screen Shot - iPhone 12 - 2021-10-23 at 01 55 29](https://user-images.githubusercontent.com/85645967/138569167-220e408d-96d3-4f29-813d-c33baad7d6d6.png)

#### Desktop
<img width="1201" alt="Screenshot 2021-10-23 at 1 54 30 AM" src="https://user-images.githubusercontent.com/85645967/138569173-c0ebfaf9-6705-44f7-9997-d95a28bb3ca1.png">

#### iOS
![Simulator Screen Shot - iPhone 12 - 2021-10-23 at 01 54 47](https://user-images.githubusercontent.com/85645967/138569187-03e51038-0074-41c2-aa8a-ce6d26b5317e.png)

#### Android
![Screenshot_1634934344](https://user-images.githubusercontent.com/85645967/138569200-ddbe4e66-0152-4985-bc34-538b167d5699.png)

2021-10-21 19:12 UTC, Santhosh-Sellavel commented on src/pages/settings/Payments/PaymentMethodList.js
> +    /** Is payment options in menu visible to user? */
Any other comment suggestion here? @Beamanator

2021-10-22 17:29 UTC, Beamanator requested changes
A few tiny comments, but I also think @shawnborton and I may have confused you since [here](https://github.com/Expensify/App/issues/5915#issuecomment-947970566) we decided we want the background color to be the color when the button is "active" (darker gray) and I see in the code you're using `CONST.BUTTON_STATES.ACTIVE`, but that ends up giving this effect:

https://user-images.githubusercontent.com/3885503/138497915-42873277-37a7-4980-86fe-cc972e5275ad.mov

Is it easy to make the background that darker gray we see when clicking on the "Add payment menu" button?

2021-10-27 09:58 UTC, Beamanator approved these changes
Looks great 💪

2021-10-27 09:58 UTC, merged

2021-10-29 22:13 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1400749961) to production by @roryabraham in version: 1.1.11-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅