Ensures mini actions menu will disappear when attachment modal opens up
Expensify/App pull request #6083
Opened 2021-10-27 16:07 UTC by sidferreira

### Details
The `={false}` value of the prop was forcing the mini action menu to keep visible even when it lost the focus.

### Fixed Issues
https://github.com/Expensify/App/issues/5972

### Tests
When tapping to open the attachment, should NOT show the mini actions menu after closing the attachments modal

### QA Steps
1. Navigate to a conversation
2. Send an image
3. Open the image preview
4. Click on the top right X to close the modal
5. Close the modal

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [X] iOS
- [x] Android

### Recording

- Web https://www.dropbox.com/s/vt1vat6ib52bcb7/MINI_ACTION_TEST_WEB.mp4?dl=0
- Mobile Web https://www.dropbox.com/s/78icy876lrzodxq/MINI_ACTION_TEST_WEB_IOS.mp4?dl=0
- Desktop https://www.dropbox.com/s/8v8hmkrfbj7046t/MINI_ACTION_TEST_DESKTOP.mp4?dl=0
- iOS https://www.dropbox.com/s/6j9ofxvtrjuncnm/MINI_ACTION_IOS.mp4?dl=0
- Android https://www.dropbox.com/s/jmax9etffmz3k9g/MINI_ACTIONS_ANDROID.mp4?dl=0

2021-11-01 04:03 UTC, sidferreira commented
@parasharrajat Updated

2021-11-01 04:15 UTC, parasharrajat commented
Thanks for uploading those. It would help us review this PR faster. 
Did you test **Right-click Context Menu behavior**?

I will test this later.

2021-11-02 21:03 UTC, sidferreira commented
@parasharrajat @mallenexpensify Did the test, but not sure if recorded them (recording was made after the tests/pr)

2021-11-03 01:33 UTC, parasharrajat commented
Thanks, I will test it today in a few hours.

2021-11-03 18:31 UTC, parasharrajat requested changes
LGTM, Tested on the web. Works well.

2021-11-03 18:31 UTC, parasharrajat commented on src/pages/home/report/ReportActionItem.js
> +                <Hoverable resetsOnClickOutside>
You can completely omit this prop. it defaults to true.

2021-11-03 18:36 UTC, parasharrajat commented on src/pages/home/report/ReportActionItem.js
> +                <Hoverable resetsOnClickOutside>
Oops, It's fine.  Ignore this.

2021-11-03 18:38 UTC, parasharrajat approved these changes
All yours @pecanoro

2021-11-03 18:57 UTC, pecanoro approved these changes

2021-11-03 20:01 UTC, merged

2021-11-03 20:01 UTC, OSBotify commented
@sidferreira, Great job getting your first Expensify/App pull request over the finish line! :tada:

I know there's a lot of information in our [contributing guidelines](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md), so here are some points to take note of :memo::

1. Now that your first PR has been merged, you can be hired for another issue. Once you've completed a few issues, you may be eligible to work on more than one job at a time. 
2. Once your PR is deployed to our staging servers, it will undergo quality assurance (QA) testing. If we find that it doesn't work as expected or causes a regression, you'll be responsible for fixing it. Typically, we would revert this PR and give you another chance to create a similar PR without causing a regression.
3. Once your PR is deployed to _production_, we start a 7-day timer :alarm_clock:. After it has been on production for 7 days without causing any regressions, then we pay out the Upwork job. :moneybag:

So it might take a while before you're paid for your work, but we typically post multiple new jobs every day, so there's plenty of opportunity. I hope you've had a positive experience contributing to this repo! :blush:

2021-11-03 20:01 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-11-04 22:15 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1423222652) to staging by @pecanoro in version: 1.1.13-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-11-15 22:51 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1464371259) to production by @Jag96 in version: 1.1.14-4 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-11-18 15:47 UTC, parasharrajat commented
Oops, I didn't notice that this PR didn't have signed commits. I am not sure what should we do now?

2021-11-18 15:57 UTC, pecanoro commented
@parasharrajat oh interesting, I didn't notice either, in our other repos, we block people from being able to merge PRs with unsigned commits, we should definitely enable that here too.

2021-11-18 15:58 UTC, parasharrajat commented
Yeah, I raised this in the Slack. Let's put this suggestion there.

2021-11-18 17:47 UTC, sidferreira commented
@parasharrajat should I sign this too?

2021-11-18 17:50 UTC, parasharrajat commented
I think this is not possible now. It is merged so skip this unless someone raises a flag.

2021-11-19 14:23 UTC, ogumen commented
Accessibility issues found:

2021-11-21 15:11 UTC, ogumen commented
Accessibility issues found in this PR:
1. Keyboard Navigation: New Chat: The invisible clickable message is focusable with tab key - failure of WCAG SC 2.4.3, similar to https://github.com/Expensify/App/issues/5452
https://user-images.githubusercontent.com/88733897/142638431-2e3277c0-91bc-46f3-8b8e-982f5fbf9740.mp4
2. Keyboard Navigation: Chat: Focus order through messages is reversed bottom-to-top - failure of WCAG SC 2.4.3, same as https://github.com/Expensify/App/issues/5676
3. The image attachment does not have a visible outline on focus - failure of WCAG SC 2.4.7
https://user-images.githubusercontent.com/88733897/142766775-7575d720-9e65-4a6a-9f86-a2a05ca09b98.mp4
4. The image attachment cannot be focused with Tab key when the screen reader is enabled - failure of WCAG SC 2.1.1
https://user-images.githubusercontent.com/88733897/142766965-407741e9-e8c9-4101-8e85-374614a14f6c.mp4
5. The "Download attachment" button is announced without button role and with no context, as "Attachment" - failure of WCAG SC 4.1.2, similar to https://github.com/Expensify/App/issues/5446 and https://github.com/Expensify/App/issues/5519
https://user-images.githubusercontent.com/88733897/142767093-92a98a7c-9f18-4f73-8b9f-f6e7075cc41e.mp4
6. The non-interactive dialog title is focusable with Tab key - failure of WCAG SC 2.4.3
https://user-images.githubusercontent.com/88733897/142767239-77f22450-8003-4389-82b4-043f4613c42b.mp4
7. The zoom-in and zoom-out functionality is not available for screen reader users - failure of WCAG SC 2.1.1
https://user-images.githubusercontent.com/88733897/142767259-469da5e0-05fb-405f-b302-866fc5ba1925.mp4
8. The "Close" and "Download attachment" buttons in the opened image attachment modal dialog do not meet the minimum color contrast requirements of 3.0:1. The grey buttons (#C6C9CA) against white background (#FFFFFF) have a color contrast ratio of 1.66:1 - failure of WCAG SC 1.4.11
![Image attachment dialog_Grey buttons on white background do not meet minimum color contrast requirements](https://user-images.githubusercontent.com/88733897/142767463-6645234e-ada4-4754-9e8b-6c8eb439dcf9.png)
9. The image attachment modal dialog has no programmatic label - failure of WCAG SC 1.3.1
![Image attachment_modal dialog has no programmatic label](https://user-images.githubusercontent.com/88733897/142767537-908a36b1-1eb8-48e9-ac79-3f231a9f9289.png)
10. The visual "Attachment" heading in the image attachment dialog is not implemented programmatically as a heading - failure of SCAG SC 1.3.1, similar to https://github.com/Expensify/App/issues/5458
![Image attachment_the visual heading not implemented as a heading programmatically](https://user-images.githubusercontent.com/88733897/142767604-524c17c5-3ee6-49e2-9e29-fc092da9973a.png)

2021-11-23 17:11 UTC, stitesExpensify commented
FYI we're going to revert this, I will make the same change myself so that it is signed, and then we're going to merge that PR. No action required on your parts @parasharrajat @sidferreira. Thanks for bringing it up and we'll keep a closer eye on this moving forward until we make it a requirement for the repo :smile: