Added download links to the workspace invite message
Expensify/App pull request #6292
Opened 2021-11-14 01:52 UTC by akshayasalvi

### Details

- Added app download page link to the Workspace invite page

### Fixed Issues

$ https://github.com/Expensify/App/issues/5774

### Tests
1. Tested the email invite from all platforms
2. Tested email link redirection
3. Edited message content removing link

### QA Steps
1. Go to any workspace using sidebar
2. Click on Manage Members
3. Click on Invite button at the top
4. The default welcome note should have `use.expensify.com/download` link in the message 
5. Enter any email address and click on Invite
6. You should also receive the email with the `use.expensify.com/download` as a clickable link

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-11-16 15:10 UTC, Beamanator requested changes
Can you actually make this tiny text change? (also in the spanish translation) I think it's a bit clearer to users

2021-11-16 15:10 UTC, Beamanator commented on src/languages/en.js
> +            welcomeNote: ({workspaceName}) => `You have been invited to ${workspaceName || 'a workspace'}! Download the Expensify mobile app using use.expensify.com/download to start tracking your ex
```suggestion
            welcomeNote: ({workspaceName}) => `You have been invited to ${workspaceName || 'a workspace'}! Download the Expensify mobile app at use.expensify.com/download to start tracking your expenses.`,
```

2021-11-18 15:25 UTC, akshayasalvi commented
PR updated

2021-11-19 12:09 UTC, Beamanator approved these changes
Looks great, nice work - thanks for sticking with this 👍

2021-11-19 12:09 UTC, merged

2021-11-19 12:10 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-11-22 20:53 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1491857468) to staging by @Beamanator in version: 1.1.15-18 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-11-29 18:48 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1517346221) to production by @roryabraham in version: 1.1.16-10 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅