Added frequently used emojis support
Expensify/App pull request #6498
Opened 2021-11-26 18:19 UTC by mananjadhav

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/4559

### Tests

### QA Steps

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-11-26 20:24 UTC, mananjadhav commented
@stitesExpensify While my work is done, I've got a regression from the existing `main` branch, where EmojiPicker has some extra padding on the left. 

![image](https://user-images.githubusercontent.com/3069065/143627002-b5c33d3f-6852-4e0a-9017-2d4d764c5ed9.png)

2021-11-26 21:12 UTC, mananjadhav commented
@stitesExpensify I've fixed the above padding issue with a small fix in `Popover/index.native.js`. Please review that as well.

2021-11-30 17:45 UTC, Jag96 commented
@mananjadhav https://github.com/Expensify/App/pull/6523 has fixed the padding issue so if [this commit](https://github.com/Expensify/App/pull/6498/commits/c27d334f38448ed50ec1a3f65171d44ff6ab08a5) is no longer necessary please remove it

2021-11-30 18:34 UTC, mananjadhav commented
@Jag96 yeah it won't be needed I'll take the latest pull of main and remove my commit.

2021-12-01 15:49 UTC, mananjadhav commented
Commit removed and PR updated. @stitesExpensify Any updates for me on this one?

2021-12-01 22:44 UTC, Jag96 commented
@stitesExpensify is OOO, assigning pullerbear to get another reviewer on this one

2021-12-02 20:30 UTC, Jag96 reviewed
Works well! A few requests, will let @stitesExpensify do a final review when he's back from OOO

2021-12-03 13:47 UTC, mananjadhav commented
@Jag96 PR updated

2021-12-07 00:46 UTC, Jag96 requested changes
Just one missed usage, otherwise LGTM

2021-12-07 00:46 UTC, Jag96 commented on src/libs/actions/User.js
> + * @param {Array} frequentlyUsedEmojis
Missed an `{Array}` usage here

2021-12-07 04:33 UTC, mananjadhav commented on src/libs/actions/User.js
> + * @param {Array} frequentlyUsedEmojis
Sorry about that. Fixed and updated PR.

2021-12-07 18:45 UTC, Jag96 approved these changes
Thanks @mananjadhav, this LGTM, @stitesExpensify when you get back from OOO feel free to leave a review if there are any follow-ups you'd like addressed.

2021-12-07 18:45 UTC, merged

2021-12-07 18:46 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-12-07 19:45 UTC, stitesExpensify commented
:fire: I didn't review the code but I just tested it and it seems to work great! Thanks for the work @mananjadhav and thanks for taking over the review for me @Jag96 I appreciate it

2021-12-08 21:09 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1555712987) to staging by @Jag96 in version: 1.1.18-4 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-12-20 12:10 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1601848621) to production by @Julesssss in version: 1.1.21-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅