Allow scrolling for Report Group Details Page
Expensify/App pull request #6555
Opened 2021-12-01 05:56 UTC by ctkochan22

@Expensify/pullerbear 
@TomatoToaster @jasperhuangg (suggested by github)

### Details
If you go to a group's details page, the page is not scrollable. This is an issue if you go to that page on mobile, and rotate to landscape. You need to scroll to get to members:
![SfslPPLTCa](https://user-images.githubusercontent.com/12980144/144179642-63b2e7a3-27c1-4f91-89ca-022a5bd33a00.gif)

### Fixed Issues

$ [GH_LINK](https://github.com/Expensify/App/issues/6495)

### TestsQA
Have a report group made. I had to create a new account/domain for it to show up. 
1. Go to group
2. Click on the group title for details
3. Rotate to landscape
4. Scroll down, verify that you can

### QA Steps

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [x] iOS
- [ ] Android

2021-12-01 20:34 UTC, Jag96 requested changes
Per https://github.com/Expensify/App/issues/6495#issuecomment-983999721 can you update the Details page as well?

2021-12-01 22:32 UTC, ctkochan22 commented
Updated

2021-12-01 23:02 UTC, TomatoToaster approved these changes

2021-12-02 00:09 UTC, deetergp commented
`#waystar.com` I know what you've been watching 😂

2021-12-02 00:09 UTC, deetergp approved these changes
Easy breezy!

2021-12-02 00:19 UTC, Jag96 approved these changes

2021-12-02 00:19 UTC, merged

2021-12-02 00:20 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-12-07 00:21 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1547012777) to staging by @Jag96 in version: 1.1.17-8 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-12-08 20:12 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1555704648) to production by @roryabraham in version: 1.1.18-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅