Fix italic-bold font difference
Expensify/App pull request #6561
Opened 2021-12-02 11:40 UTC by developvsn

### Details

Changed fontFamily for `strong` and `em` elements.
### Fixed Issues

$ [#6489](https://github.com/Expensify/App/issues/6489)

### Tests

1. Open any report dialog.
2. Write `*_bold-italic_*` and `_*italic-bold*_`.
3. Check if there is any difference.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

<img width="400" alt="web" src="https://user-images.githubusercontent.com/71173662/144397331-13d3428f-f44f-4f8b-a309-fecc563d7253.png">

#### Mobile Web

<img width="548" alt="mobileWeb" src="https://user-images.githubusercontent.com/71173662/144397397-87f41ff8-648b-45a4-b91e-44c00ee960b4.png">

#### Desktop

<img width="821" alt="desktop" src="https://user-images.githubusercontent.com/71173662/144397470-99a8b2fd-c420-4b13-9487-d25299650028.png">

#### iOS

![ios](https://user-images.githubusercontent.com/71173662/144398282-3014ead2-f45d-4d05-be34-1b34cfc384f0.jpg)

#### Android

![android](https://user-images.githubusercontent.com/71173662/144398077-36cb30ee-4599-470c-8c2e-f67fe2a4ddb8.jpg)

2021-12-02 11:43 UTC, Julesssss reviewed
LGTM, reviewing this as the [last PR](https://github.com/Expensify/App/pull/6560#event-5705227403) was assigned to me then closed.

2021-12-02 11:44 UTC, Julesssss submitted a review, later dismissed

2021-12-02 11:57 UTC, parasharrajat requested changes
Please sign the commits.... cc: @Julesssss

2021-12-02 14:07 UTC, Julesssss approved these changes

2021-12-02 14:07 UTC, merged

2021-12-02 14:08 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-12-07 00:20 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1547012777) to staging by @Julesssss in version: 1.1.17-8 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-12-08 20:12 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1555704648) to production by @roryabraham in version: 1.1.18-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅