change pronoun input margin to value for grouped form elements
Expensify/App pull request #6586
Opened 2021-12-05 17:26 UTC by anthony-hull

### Details

### Fixed Issues
<!---
Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing.
Do NOT add the special GH keywords like `fixed` etc, we have our own process of managing the flow.
It MUST be an entire link to the issue; otherwise, the linking will not work as expected.

Make sure this section looks similar to this (you can link multiple issues using the same formatting, just add a new line):

$ https://github.com/Expensify/App/issues/5556

### QA Steps

1. View Profile
2. Change preferred pronouns to Self-select
3. The margin between the pronoun form elements is equal to that between First name and Last name

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots
Web
![image](https://user-images.githubusercontent.com/47184118/144756038-7737d45e-55ca-40aa-aaa8-b6e4ef791d58.png)

Tablet mobile web
![image](https://user-images.githubusercontent.com/47184118/144756094-6e2c553d-f9c1-4e0e-ac4f-ec3a86fea928.png)

Mobile Web
![image](https://user-images.githubusercontent.com/47184118/144756130-cb9b2122-d1ad-454a-a317-b092c886d79e.png)

iOS
![image](https://user-images.githubusercontent.com/47184118/144755887-36149956-c6bd-4a42-8bb0-4cd246f5d35c.png)

Android
![image](https://user-images.githubusercontent.com/47184118/144756662-a394cb2b-f176-4e6e-8b2f-6b8b5dfe8318.png)

2021-12-05 17:50 UTC, parasharrajat requested changes
It increases the gap between select dropdown and next element when there is no custom Pronoun input. Could you please fix that? 
it should not affect the UI when the custom input is hidden. Could you please test it carefully?

2021-12-05 18:11 UTC, anthony-hull commented
I'm very sorry! You are right, even simple changes need full attention.

2021-12-05 18:44 UTC, anthony-hull commented
![image](https://user-images.githubusercontent.com/47184118/144759282-c1ad38d8-ca97-4235-a458-6fed9847d838.png)
![image](https://user-images.githubusercontent.com/47184118/144759307-1a6c8f53-1f0b-437e-9dab-7c19f56e347f.png)

2021-12-05 18:48 UTC, parasharrajat approved these changes
LGTM. 

All yours @puneetlath.

2021-12-05 21:28 UTC, puneetlath approved these changes
Looks good!

2021-12-05 21:28 UTC, merged

2021-12-05 21:29 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-12-07 00:20 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1547012777) to staging by @puneetlath in version: 1.1.17-8 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-12-08 20:12 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1555704648) to production by @roryabraham in version: 1.1.18-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅