Fix Ion.clear
Expensify/App pull request #661
Opened 2020-10-16 15:50 UTC by iwiznia

All I will say is: async programming is hard.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/143104

### Tests
Did all the tests in https://github.com/Expensify/ReactNativeChat/pull/603

2020-10-16 16:26 UTC, marcaaron requested changes

2020-10-16 18:15 UTC, roryabraham requested changes

2020-10-22 16:41 UTC, roryabraham approved these changes
Noice, LGTM 👍

2020-10-22 17:39 UTC, roryabraham reviewed
Actually, just the one NAB for me.

2020-10-22 18:58 UTC, marcaaron approved these changes

2020-10-22 18:58 UTC, merged