Show Empty Chat with draft messages in LHN
Expensify/App pull request #6698
Opened 2021-12-10 19:13 UTC by parasharrajat

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/6619

### Tests | QA Steps
1. Make sure the focus Mode is not on from the Preference Page.
1. Open any new chat that does not have any messages yet.
2. Check that it is listed in LHN when active.
3. Create a draft message on the same chat.
4. Switch to another chat.
5. Confirm that the old chat is still visible in LHN with the pencil icon.
6. Open the old chat.
7. Clear the draft.
8. Switch to another chat.
9. Confirm that chat is not more visible in LHN.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

https://user-images.githubusercontent.com/24370807/145628834-d9e41fc3-2fe1-44f4-9644-d2049e73d54a.mp4

I think other videos are not needed I just moved one flag from Focus mode to both modes and thus it should work if it works on one platform.
#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-12-10 21:47 UTC, roryabraham requested changes
Sorry for not noticing during your proposal @parasharrajat, but the goal of this PR is to show reports with drafts for both the focus and standard modes. Given that, I think there will no longer be a use-case where we want to exclude a report from a `getOptions` result just because it contains a draft comment.

So instead of the implementation you have in this PR, we should just get rid of the `showReportsWithDrafts` parameter of `getOptions` entirely, since it will no longer be used and we don't need it to default to false. We should also get rid of the logic [here](https://github.com/Expensify/App/blob/28e353bef6e8aad64fc1fc7de6a63d2737b35085/src/libs/OptionsListUtils.js#L404) that filters out reports with a draft comment.

2021-12-10 21:48 UTC, parasharrajat commented
Oh yeah, overlooked that. Thanks for noticing

2021-12-13 20:12 UTC, roryabraham approved these changes

2021-12-13 20:56 UTC, merged

2021-12-13 20:57 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-12-16 01:26 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1584318208) to staging by @roryabraham in version: 1.1.20-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2021-12-20 12:08 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1601848621) to production by @Julesssss in version: 1.1.21-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅