Make sure that we reduce the unread message count when we delete an unread message
Expensify/App pull request #6746
Opened 2021-12-14 02:53 UTC by yuwenmemon

@Julesssss please review
cc @parasharrajat

### Details
This will call `setLocalLastRead` when we see that the message being updated is getting deleted. Also a small change to make a variable name a bit clearer.

### Fixed Issues
$ https://github.com/Expensify/App/issues/6472

### Tests/QA
1. From account A, send account B a message. Make sure that Account B is logged in but not viewing the message of accountA
2. From Account A, delete the message you just sent
3. From account B, verify that the unread indicator for your app does not show anything

Video:
https://user-images.githubusercontent.com/4741899/145924224-69ac2239-bc67-495c-84db-5b2e8539d62f.mp4

---

1. From account A, send account B **two messages.** Make sure that Account B is logged in but not viewing the messages of accountA
2. From Account A, delete the first message you just sent
3. From account B, verify that the unread indicator for your app shows `1`

Video:
https://user-images.githubusercontent.com/4741899/145924341-b8f5ea80-1e36-40e5-a832-f1360098e334.mp4

---

1. From account A, send account B **two messages.** Make sure that Account B is logged in but not viewing the messages of accountA
2. From Account A, delete the **second** message you just sent
3. From account B, verify that the unread indicator for your app shows `1`

Video:
https://user-images.githubusercontent.com/4741899/145924454-2dc772b3-0dcd-4e90-b759-b1eb6c7dc48e.mp4

2021-12-14 03:34 UTC, nickmurray47 reviewed
Tests well and lgtm minus one linting change

2021-12-14 03:34 UTC, nickmurray47 commented on src/libs/actions/Report.js
> +        }
is this what the linter is looking for?

```suggestion
        if (message.text) {
            return;
        }
        setLocalLastRead(reportID, lastReadSequenceNumbers[reportID]);
```

2021-12-14 04:00 UTC, parasharrajat requested changes
I can't see the whole code on GH mobile app 🤭. But this function should be called on live delete pusher event.

I think it is but just to be sure.

2021-12-14 05:52 UTC, yuwenmemon commented
Updated!

2021-12-14 06:56 UTC, nickmurray47 approved these changes
nice 👍 will leave this for Jules to final approve/merge

2021-12-14 07:24 UTC, parasharrajat approved these changes

2021-12-14 10:47 UTC, Julesssss approved these changes

2021-12-14 10:48 UTC, merged

2021-12-14 10:49 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-12-16 01:26 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1584318208) to staging by @Julesssss in version: 1.1.20-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2021-12-20 12:08 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1601848621) to production by @Julesssss in version: 1.1.21-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅