fix: Added translation for room visibility dropdown
Expensify/App pull request #6786
Opened 2021-12-15 21:33 UTC by mananjadhav

### Details
- Added translations for room visibility dropdown

### Fixed Issues

$ https://github.com/Expensify/App/issues/6733

### Tests
1. Verified translations in English as well as Spanish
2. Verified Room creation visibility values being passed.

### QA Steps
1. Go to Preferences -> change your language
2. On the home screen, click on the FAB and open the quick options menu
3. Click on New Room
4. Ensure that the visibility dropdown options are in the correct language translation

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2021-12-15 21:37 UTC, parasharrajat requested changes

2021-12-15 21:37 UTC, parasharrajat commented on src/pages/workspace/WorkspaceNewRoomPage.js
> +        const visibilityOptions = _.map(_.values(CONST.REPORT.VISIBILITY), v => ({
Can you please use a more descriptive name?

2021-12-16 03:15 UTC, mananjadhav commented
@parasharrajat  PR updated.

2021-12-16 06:40 UTC, parasharrajat approved these changes
LGTM

Cc:@puneetlath 


:ribbon: :eyes: :ribbon:

2021-12-16 17:50 UTC, puneetlath approved these changes
Looks good!

2021-12-16 17:50 UTC, merged

2021-12-16 17:51 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-12-17 17:58 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1593203524) to staging by @puneetlath in version: 1.1.21-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2021-12-21 19:45 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1608329881) to production by @sketchydroide in version: 1.1.22-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅