Anthony  remove second secure inputs
Expensify/App pull request #6809
Opened 2021-12-16 21:45 UTC by anthony-hull

### Details

### Fixed Issues
$ https://github.com/Expensify/App/issues/6565

### QA Steps
1. Create a new account
2. Click the link in the email
3. Verify the password form works (including some invalid password states)
4. Submit the form and verify it allows you to set the password with a valid password

1. Given being logged in
2. Navigate to the change password setting
3. Verify the password form works (including some invalid password states)
4. Submit the form and verify it allows you to change with a valid password

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [ ] Android

### Screenshots

#### Web
![image](https://user-images.githubusercontent.com/47184118/146436230-dc9f906c-fdc4-40c8-a274-7035652aac82.png)

#### Mobile Web
![image](https://user-images.githubusercontent.com/47184118/146437501-24442dbb-5183-41d4-bb9f-db8d38f58d12.png)

#### Desktop
![image](https://user-images.githubusercontent.com/47184118/146440918-8c16bb5a-4685-4335-977b-21f7b93350ac.png)

#### iOS
![image](https://user-images.githubusercontent.com/47184118/146445837-42929dbf-3e2b-4b0d-b17e-0da93fefdfb3.png)

#### Android

2021-12-20 11:46 UTC, parasharrajat commented
I will wait for your tests..

2021-12-20 18:23 UTC, parasharrajat requested changes

2021-12-20 18:23 UTC, parasharrajat commented on src/pages/settings/PasswordPage.js
> -            confirmNewPassword: '',
Not needed.

2021-12-20 18:23 UTC, parasharrajat commented on src/pages/settings/PasswordPage.js
> -                confirmPasswordMatch: false,
Not needed.

2021-12-20 18:23 UTC, parasharrajat commented on src/pages/settings/PasswordPage.js
> -            confirmPasswordMatch: 'setPasswordPage.passwordsDontMatch',
not needed.

2021-12-20 18:26 UTC, parasharrajat commented on src/pages/settings/PasswordPage.js
> -                confirmPasswordMatch: false,
hmm.,,,line above it.

2021-12-20 18:26 UTC, parasharrajat commented on src/pages/settings/PasswordPage.js
> -            confirmPasswordMatch: 'setPasswordPage.passwordsDontMatch',
line 68. Sorry

2021-12-20 20:01 UTC, anthony-hull commented on src/pages/settings/PasswordPage.js
> -                confirmPasswordMatch: false,
good catch, thanks

2021-12-21 14:22 UTC, parasharrajat commented
@anthony-hull Could you please test it on Android? Thanks

2021-12-21 14:39 UTC, anthony-hull commented
I've updated the post with the android screenshot

2021-12-21 14:41 UTC, parasharrajat approved these changes
LGTM. 

cc: @chiragsalian

2021-12-22 17:18 UTC, chiragsalian approved these changes
Changes LGTM.

2021-12-22 17:18 UTC, merged

2021-12-22 17:19 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-12-26 19:59 UTC, mountiny commented
Edited the PR body to also link to the other issue this PR fixes.

2021-12-29 00:50 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1632229625) to staging by @chiragsalian in version: 1.1.23-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|failure ❌
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2022-01-04 01:34 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1651668199) to production by @francoisl in version: 1.1.24-8 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅