Rename ExpensiTextInput
Expensify/App pull request #6838
Opened 2021-12-20 02:04 UTC by mateusbra

### Details

Rename component `ExpensiTextInput` to `TextInput`
### Fixed Issues

$ https://github.com/Expensify/App/issues/6760

### Tests

1. Run the app and see that TextInput still working
### QA Steps

1. Run the app and see that TextInput still working
### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

![Web](https://user-images.githubusercontent.com/56851391/146701273-edb4775f-dc52-440c-a96b-dd30ff171c7e.png)

#### Mobile Web

![Mobile Web](https://user-images.githubusercontent.com/56851391/146701344-9004bd0f-fcb3-4233-9bdc-fe774294fb83.jpeg)

#### Desktop

![Desktop](https://user-images.githubusercontent.com/56851391/146701309-d997a307-9dc9-4f33-8693-3ee1623d29bd.png)

#### iOS

![IOS](https://user-images.githubusercontent.com/56851391/146701365-1e739612-519c-476f-be3c-e8d3235dbb4c.png)

#### Android

![Android](https://user-images.githubusercontent.com/56851391/146701381-b97ad94e-90c4-4b73-b96b-360cf4f33b07.jpeg)

2021-12-20 11:34 UTC, parasharrajat requested changes

2021-12-20 11:34 UTC, parasharrajat commented on src/styles/styles.js
> +    TextInputContainer: {
All styles in camelCase

2021-12-20 19:11 UTC, mateusbra commented
We had a lint error due to having two style names that are the same:
TextInput and TextInput(expensiTextInput previously).
How you think we should rename it?

2021-12-20 19:22 UTC, parasharrajat commented
you can try baseTextInput if that works.

2021-12-20 21:13 UTC, puneetlath commented
It looks like we previously did it as `RNText` here: https://github.com/Expensify/App/blob/d28716a694af1bdc9449ec5f5f40e57a7ecc6eb1/src/components/ExpensifyText.js#L5

So maybe that's a good format to follow for when we import these components from React Native?

2021-12-22 22:55 UTC, mateusbra commented
> It looks like we previously did it as `RNText` here:
> 
> https://github.com/Expensify/App/blob/d28716a694af1bdc9449ec5f5f40e57a7ecc6eb1/src/components/ExpensifyText.js#L5
> 
> So maybe that's a good format to follow for when we import these components from React Native?


You're saying we should change these imports:
https://github.com/Expensify/App/blob/d28716a694af1bdc9449ec5f5f40e57a7ecc6eb1/src/components/ExpensiTextInput/BaseExpensiTextInput.js#L3-L5
into:
```js
import {
    Animated as AnimatedRN, 
View as ViewRN, 
TouchableWithoutFeedback as TouchableWithoutFeedbackRN, 
Pressable as PressableRN,
} from 'react-native';
```

2021-12-25 19:38 UTC, puneetlath commented
Ah perhaps I've misunderstood. Can you help me understand why we need to call the files `BaseExpensiTextInput` instead of just `TextInput`?

2021-12-25 21:15 UTC, mateusbra commented
@puneetlath our file structure will be this:
![Captura de Tela 2021-12-25 às 18 11 18](https://user-images.githubusercontent.com/56851391/147393674-108a6155-43c8-48f0-974f-11e6188ce0b8.png)
we won't call `BaseExpensiTextInput`, we will call `BaseTextInput`

2021-12-28 13:55 UTC, parasharrajat requested changes
Small changes...

2021-12-28 13:55 UTC, parasharrajat commented on src/components/TextInput/index.js
> +import {propTypes, defaultProps} from './baseTextInputPropTypes';
```suggestion
import * as baseTextInputPropTypes from './baseTextInputPropTypes';
```

2021-12-28 13:55 UTC, parasharrajat commented on src/components/TextInput/index.js
> +TextInput.defaultProps = defaultProps;
This will change too..

2021-12-28 13:55 UTC, parasharrajat commented on src/components/TextInput/index.native.js
> +import {propTypes, defaultProps} from './baseTextInputPropTypes';
Similar to above.

2021-12-28 14:33 UTC, mateusbra commented on src/components/TextInput/index.native.js
> +import {propTypes, defaultProps} from './baseTextInputPropTypes';
ok

2021-12-28 14:33 UTC, mateusbra commented on src/components/TextInput/index.js
> +TextInput.defaultProps = defaultProps;
ok

2021-12-28 14:33 UTC, mateusbra commented on src/components/TextInput/index.js
> +import {propTypes, defaultProps} from './baseTextInputPropTypes';
ok

2021-12-28 14:54 UTC, parasharrajat approved these changes, later dismissed
LGTM
cc: @puneetlath

2022-01-04 00:33 UTC, puneetlath submitted a review, later dismissed
@mateusbra thanks for your patience through the holidays. Everything looks good to me, but you've picked up some merge conflicts. Once you fix those I can quickly re-approve and merge. Thanks!

2022-01-04 20:41 UTC, parasharrajat approved these changes

2022-01-05 05:42 UTC, puneetlath approved these changes

2022-01-05 05:42 UTC, merged

2022-01-05 05:43 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-01-06 00:55 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1660824895) to staging by @puneetlath in version: 1.1.25-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-01-10 19:03 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1678913881) to production by @Jag96 in version: 1.1.26-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅