fix: New chat aren't showing bold in Left Hand Nav
Expensify/App pull request #6898
Opened 2021-12-23 22:51 UTC by aswin-s

### Details

This PR fixes an issue where new chat messages were not being shown in bold inside LHN.

### Fixed Issues

$ https://github.com/Expensify/App/issues/6874

### Tests

1.  Sign in as User A in one browser tab & as User B in another tab
2. Open chat with the other user in each tab.
3. Now navigate to a separate conversation in LHN for User B. (For example Concierge)
4. Send a message from User A to User B.
5. The new message should be highlighted in bold on the LHN for User B.
6. Verify that it works other way around as well.

### QA Steps

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

![image](https://user-images.githubusercontent.com/6880914/147296376-a5e5809d-9053-4b25-90ef-bfab21f49448.png)

https://user-images.githubusercontent.com/6880914/147296695-7ecb1139-320b-4f91-8a5b-3b55dc6aa356.mp4

#### Mobile Web

N.A

#### Desktop

![image](https://user-images.githubusercontent.com/6880914/147296590-bffa2c89-b743-43c4-bb4d-8dfea980d0e9.png)

#### iOS

![image](https://user-images.githubusercontent.com/6880914/147297073-42cdeec0-1098-419a-8db0-4d8862b6afd1.png)

#### Android

![Screenshot_1640299864](https://user-images.githubusercontent.com/6880914/147297586-ca5f0894-1cf2-4788-8c54-535f3394dd55.png)

2021-12-24 19:05 UTC, marcochavezf approved these changes
Looks good to me! cc @parasharrajat

2021-12-27 18:31 UTC, merged

2021-12-27 18:33 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2021-12-27 18:38 UTC, marcochavezf commented
Merging it and applying the `CP Staging` label because more employees are going to experience this issue.

2021-12-27 18:39 UTC, parasharrajat requested changes
Thanks for the changes @aswin-s and waiting for review I was on vacation. This looks good. 

Could you please add videos for all platforms and present the following features;
1. The current issue.
2. Unread Message when the app is put to foreground from background.

2021-12-27 18:39 UTC, parasharrajat commented on src/Expensify.js
> +        if (!this.appStateChangeListener) { return; }
Could you please expand this to multiple lines?
```suggestion
        if (!this.appStateChangeListener) {
        	return;
        }
```

2021-12-27 18:39 UTC, parasharrajat commented on src/Expensify.js
> +        this.appStateChangeListener = null;
```suggestion

```

2021-12-27 18:39 UTC, parasharrajat commented on src/pages/home/report/ReportActionsView.js
> +        this.appStateChangeListener = null;
```suggestion

```

2021-12-27 19:17 UTC, aswin-s commented
@parasharrajat Should I raise a follow up PR with the suggested changes?

2021-12-27 19:27 UTC, parasharrajat commented
These changes are no blocker for me so If @marcochavezf says we should do these then yeah please add a follow-up?

2021-12-27 19:59 UTC, marcochavezf commented
> These changes are no blocker for me so If @marcochavezf says we should do these then yeah please add a follow-up?

@parasharrajat Yeah, I think we could include these changes as a follow-up, thank you for doing it @aswin-s

2021-12-28 18:45 UTC, roryabraham commented
Hi, I'm now seeing the following error on `main`:

![image](https://user-images.githubusercontent.com/47436092/147597236-56e43e21-8847-4f0d-bc30-9ecfff8c4ba4.png)

2021-12-28 18:52 UTC, roryabraham commented
It looks like this change was made in react-native `0.65`, but we're still using react-native `0.64.1`

2021-12-28 19:01 UTC, roryabraham commented
I think we need to either revert this PR or upgrade the whole app to RN `0.65`

2021-12-28 19:14 UTC, aswin-s commented
@roryabraham as explained over [here](https://github.com/Expensify/App/issues/6874#issuecomment-1000493831), removeEventListener was not working on react-native-web. I guess upgrading to  0.65 will solve it for both platforms, considering there is only a small diff between both versions. 

https://react-native-community.github.io/upgrade-helper/?from=0.64.1&to=0.65.0

Related to this, I would also like to point out that dependencies like `react-native-modal` is also consistently throwing similar error on web which is fixed in their latest release. Unfortunately that dependency upgrade is also blocked by react-native peer dependency requirement of ">=0.65.0"

WDYT?

2021-12-28 19:18 UTC, roryabraham commented
I suppose we should update react-native and the other dependencies that are throwing the error.

2021-12-28 21:17 UTC, roryabraham commented
I have an upgrade PR [here](https://github.com/Expensify/App/pull/6914), but I could use help testing it. Works well on iOS from my testing so far.

2021-12-29 00:50 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1632229625) to staging by @marcochavezf in version: 1.1.23-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|failure ❌
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2022-01-04 01:34 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1651668199) to production by @francoisl in version: 1.1.24-8 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅