[No QA] Fix api usage inside `AddEncryptedAuthToken` migration
Expensify/App pull request #6915
Opened 2021-12-28 21:18 UTC by kidroca

@marcaaron

### Details

Refactoring API usgages to `import *` seems to hsbr

### Fixed Issues
$ N/A

### Tests

### QA Steps

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web
![image](https://user-images.githubusercontent.com/12156624/147607763-47a02c01-a5ed-4e51-b578-b8e800f082d2.png)

![image](https://user-images.githubusercontent.com/12156624/147607802-736c7c3c-ada6-463d-b65c-80aa15cdad96.png)

2021-12-28 21:58 UTC, ctkochan22 approved these changes, later dismissed
Simple change. @marcaaron let you merge

2021-12-29 05:27 UTC, marcaaron requested changes
Thanks! This was on my list of things to fix, but never found the time to do it. Guessing not many were affected, but it was a careless mistake.

2021-12-29 05:27 UTC, marcaaron commented on src/libs/migrations/AddEncryptedAuthToken.js
> +import * as Api from '../API';
Mind changing this to `API` for consistency?

2021-12-30 19:23 UTC, ctkochan22 approved these changes

2021-12-30 19:25 UTC, marcaaron approved these changes

2021-12-30 19:25 UTC, merged

2021-12-30 19:26 UTC, marcaaron commented
Looks great, thanks again!

2021-12-30 19:26 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-01-04 01:53 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1651672957) to staging by @marcaaron in version: 1.1.24-19 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|failure ❌
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|failure ❌

2022-01-04 02:40 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1651839606) to production by @francoisl in version: 1.1.24-19 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|failure ❌
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|failure ❌