Implement infinite sessions
Expensify/App pull request #7
Opened 2020-08-08 18:54 UTC by AndrewGable

Implemented infinite sessions:
1. On the sign in page pass `useExpensifyLogin = true` for the first `Authenticate` which will create a new login via `CreateLogin`
2. In `CreateLogin` use `React-Native-Chat-${guid}` for the login name and `${guid}` for the password
3. Store the random login and password 
4. Store the last time we successfully authenticated
5. When calling `verifyAuthToken` check the last time, if it's more than 90 minutes use the random login and password to call authenticate
6. Delete the login we created on sign out

2020-08-08 19:00 UTC, tgolen requested changes

2020-08-08 19:58 UTC, tgolen requested changes

2020-08-08 20:17 UTC, tgolen approved these changes

2020-08-08 20:17 UTC, merged

2021-04-19 22:41 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/Expensify.cash
    /actions/runs/765130740) 🚀 to 
    staging on Mon Apr 19 2021 at 22:41:56 GMT+0000 (Coordinated Universal Time)

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-03-16 07:49 UTC, Stutikuls commented
Checked all PRs and added comments to all PRs where accessibility issues were found without the Android platform (due to build issues on Android) only one issue is left and have query on #7864 
The non-applicable PRs are - #7594, #7662, #7701, #7744, #7805, #7827 
Impossibility to verify (After client confirmation) - #7804