fix: Change emoji navigation with arrow keys
Expensify/App pull request #7127
Opened 2022-01-11 13:20 UTC by mananjadhav

### Details

- Allow the user to go to the first emoji on click of the right arrow
- Allow the user to go to the search input clicking on the left arrow while first emoji is selected.

### Fixed Issues

$ https://github.com/Expensify/App/issues/7035

### Tests

- [ ] Verify that no errors appear in the JS console

### QA Steps

- [ ] Verify that no errors appear in the JS console

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2022-01-11 16:43 UTC, rushatgabhane commented
Yeah sure, go ahead

2022-01-14 04:31 UTC, mananjadhav commented
The `selection` prop isn't working fine with `TextInputFocussable`. It automatically resets to `{start: 0, end: 0}` even if I am setting it `{start: 5, end: 5}`. 

I need this resolved because we want the emoji to be highlighted only if the cursor is at the end of the string. Once this is resolved rest is done.

2022-01-14 05:41 UTC, rushatgabhane commented
> Allow the user to go to the first emoji on click of the right arrow

Just to clarify, we only wanna go to the first emoji when cursor is at the end of search query.

2022-01-14 05:55 UTC, rushatgabhane commented
> The selection prop isn't working fine with TextInputFocussable. It automatically resets to {start: 0, end: 0} even if I am setting it {start: 5, end: 5}.

I think we should skip it then. React Native has an open issue on controlled selection https://github.com/facebook/react-native/issues/29063

Let's do it the way up arrow is done. What do you think?

2022-01-14 06:11 UTC, mananjadhav commented
> When search is refocused, we should highlight the search query, so it can be replaced by typing.

That is what is handled with ArrowUp that the whole string is selected. This can be done.

2022-01-14 06:18 UTC, mananjadhav commented
> That is what is handled with ArrowUp that the whole string is selected. This can be done.

@rushatgabhane Looks like I was wrong. This isn't how `ArrowUp` and `ArrowDown` work. Just confirmed on staging.

1. Irrespective of where my cursor is in the search string, and I click on `ArrowDown`, it'll go to the first emoji.
2. Clicking on `ArrowUp` on the first emoji, takes the cursor to the beginning of the search string

While the second one is easy, I feel we might need a `selection` prop to know the cursor position so that either it goes to the next character or to the first emoji.

2022-01-14 07:40 UTC, rushatgabhane commented
Gothu, but to verify.

- On `ArrowRight`, go to first emoji if and only if cursor is at end.
- On `ArrowLeft` from first emoji, highlight the text.
- Change `ArrowUp` from just focus to highlight the text.

> selection prop for the first one to know the cursor position so that either it goes to the next character or to the first emoji. Any other suggestions to handle this?

Umm, I think you can check if cursor is at end using `onSelectionChange`.

2022-01-14 19:47 UTC, mananjadhav commented
> * On `ArrowRight`, go to first emoji if and only if cursor is at end.
> * On `ArrowLeft` from first emoji, highlight the text.
> * Change `ArrowUp` from just focus to highlight the text.
> 

@rushatgabhane  Yeah the updated PR covers the above cases.

2022-01-14 21:48 UTC, luacmartins reviewed
Just left a small comment. Otherwise LGTM and tests well. Great work @mananjadhav!

2022-01-14 21:48 UTC, luacmartins commented on src/pages/home/report/EmojiPickerMenu/index.js
>          // Arrow Down enable arrow navigation when search is focused
We should update the comment to include Arrow right

2022-01-14 22:50 UTC, rushatgabhane commented on src/pages/home/report/EmojiPickerMenu/index.js
> +            if (['ArrowDown', 'ArrowRight'].indexOf(arrowKey) === -1) {
Can this be changed to something like `arrowKey !== 'ArrowDown' || arrowKey !== 'ArrowRight'`

2022-01-14 23:25 UTC, rushatgabhane commented on src/pages/home/report/EmojiPickerMenu/index.js
> +        // Reaching start of the list, arrow left/up set the focus to searchInput.
This comment should be removed. Instead add JSDoc for this function.

2022-01-14 23:27 UTC, rushatgabhane requested changes
Nice work! Minor suggestions

2022-01-15 04:12 UTC, rushatgabhane approved these changes
LGTM! 🎉

cc: @luacmartins

2022-01-17 16:44 UTC, luacmartins approved these changes

2022-01-17 16:44 UTC, luacmartins commented
Thanks! @mananjadhav and @parasharrajat!

2022-01-17 16:44 UTC, merged

2022-01-17 16:45 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-01-18 22:45 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1714969452) to staging by @luacmartins in version: 1.1.30-4 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-01-21 00:15 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1726158569) to production by @chiragsalian in version: 1.1.31-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅