[NO QA] ignore "coverage" folder generated by Jest
Expensify/App pull request #7214
Opened 2022-01-13 21:24 UTC by marcochavezf

### Details

This change ignores in git the `coverage` folder generated by Jest:
<img width="491" alt="Screen Shot 2022-01-13 at 15 17 13" src="https://user-images.githubusercontent.com/6829422/149410540-4e582a26-748d-4beb-a588-8e5176a698e7.png">

### Fixed Issues

N/A

### Tests

Run `npm run test -- --coverage` and verify the `coverage` folder is created and its files are ignored by git:

<img width="500" alt="Screen Shot 2022-01-13 at 15 23 19" src="https://user-images.githubusercontent.com/6829422/149411301-1d9a3aa9-aba9-4f17-a3d0-58b420b8510f.png">

<img width="500" alt="Screen Shot 2022-01-13 at 15 23 27" src="https://user-images.githubusercontent.com/6829422/149411305-4238bf0e-b9b0-40cb-9f90-c6f2b353ae4d.png">

### QA Steps

N/A

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

N/A

#### Web

N/A

#### Mobile Web

N/A

#### Desktop

N/A

#### iOS

N/A

#### Android

N/A

2022-01-13 21:37 UTC, thienlnam requested changes

2022-01-18 02:39 UTC, marcochavezf commented on .gitignore
> +coverage/
Hi @thienlnam! are you referring to a new line at the end of the file, right? Also, just curious, why we should ignore `/coverage.data` too?

2022-01-18 17:54 UTC, thienlnam commented on .gitignore
> +coverage/
Ah nvm, was checking other instances of gitignore using jest but it doesn't seem that we have that anyways.  Will merge

2022-01-18 17:54 UTC, thienlnam commented on .gitignore
> +coverage/
We still need a new line at the end of the file though

2022-01-18 21:17 UTC, marcochavezf commented on .gitignore
> +coverage/
Oh I see, I'm going to add it, probably there are different files/data included when the report format is changed.

2022-01-18 21:20 UTC, marcochavezf commented
Updated with the suggested changes

<img width="350" alt="Screen Shot 2022-01-18 at 15 18 41" src="https://user-images.githubusercontent.com/6829422/150020479-dd628218-a42f-4551-a6cf-227bd5a5c653.png">

2022-01-18 21:54 UTC, thienlnam approved these changes

2022-01-18 22:20 UTC, merged

2022-01-18 23:28 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1715133333) to staging by @thienlnam in version: 1.1.30-5 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-01-21 00:14 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1726158569) to production by @chiragsalian in version: 1.1.31-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅