Fixes IOU - Unable to paste the amount copied from Notes on MacOS Safari
Expensify/App pull request #7219
Opened 2022-01-14 08:34 UTC by songlang1994

### Details

Use `TextInput` directly imported from React Native in `TextInputAutoWidthWithoutKeyboard`. Because `TextInputFocusable` will transform styled text into markdown format when pasting. That's not what we want. See also: https://github.com/Expensify/App/issues/6931#issuecomment-1008097420

### Fixed Issues

$ https://github.com/Expensify/App/issues/6931

### Tests

1. Copy a piece of bold text of amount number format. Some examples is in the following step 2:
2. **12.50** or **1,234.8** or **0.5**
3. Verify they can be pasted into the amount input.

### QA Steps

Same as above.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2022-01-14 08:41 UTC, parasharrajat requested changes

2022-01-14 08:41 UTC, parasharrajat commented on src/components/TextInputAutoWidthWithoutKeyboard/BaseTextInputAutoWidthWithoutKeyboard.js
> +    TextInput,
```suggestion
    TextInput as RNTextInput
```

2022-01-14 08:41 UTC, parasharrajat commented on src/components/TextInputAutoWidthWithoutKeyboard/BaseTextInputAutoWidthWithoutKeyboard.js
> +                    <TextInput
```suggestion
                    <RNTextInput
```

2022-01-14 08:51 UTC, songlang1994 commented
I have read the CLA Document and I hereby sign the CLA

2022-01-14 08:53 UTC, parasharrajat commented
Could you please add screenshots of all the platforms?

2022-01-14 10:47 UTC, parasharrajat requested changes
Please fix the styling so that it look the same as before.
|Current|Previous|
|----|----|
|![image](https://user-images.githubusercontent.com/24370807/149503088-f2f289bc-9d0a-4308-b970-fd7bccc6388d.png)|![image](https://user-images.githubusercontent.com/24370807/149503141-2c44553f-b276-4da1-8e8b-2d99fd1ca0b7.png)|

2022-01-14 17:24 UTC, parasharrajat requested changes

2022-01-14 17:24 UTC, parasharrajat commented on src/components/TextInputAutoWidthWithoutKeyboard/BaseTextInputAutoWidthWithoutKeyboard.js
> +    // eslint-disable-next-line no-restricted-imports
```suggestion

    // eslint-disable-next-line no-restricted-imports
```

2022-01-15 07:13 UTC, parasharrajat approved these changes
LGTM. 

cc: @Julesssss 

:ribbon: :eyes: :ribbon:  C+ reviewed

2022-01-17 15:18 UTC, Julesssss approved these changes
Tests well.

2022-01-17 15:18 UTC, merged

2022-01-17 15:19 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-01-18 22:45 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1714969452) to staging by @Julesssss in version: 1.1.30-4 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-01-21 00:15 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1726158569) to production by @chiragsalian in version: 1.1.31-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅