[No QA] Use manual signing for provisioning profile
Expensify/App pull request #7241
Opened 2022-01-14 20:16 UTC by Jag96

cc @Julesssss 

### Details
In https://github.com/Expensify/App/pull/6773/files#diff-1b579b2c321f383fcd88594bcf7023d2154da98817b50ee7ec9bc523acb56f35R290 we accidentally changed the signing options (likely for local testing) which resulted in a deploy failure [here](https://expensify.slack.com/archives/C03V9A4TB/p1642190414341000). This PR reverts the automatic signing change to use our manual provisioning profile.

### Fixed Issues
Slack thread: https://expensify.slack.com/archives/C03V9A4TB/p1642190414341000

### Tests
1. Confirm the app builds and runs
2. Confirm that when this is CPd, the build is successful on staging

- [x] Verify that no errors appear in the JS console

### QA Steps
No QA

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [x] iOS
- [ ] Android

2022-01-14 20:37 UTC, roryabraham requested changes
Oh, I'm 99% sure I've made this same mistake in the past. Let's add a simple automated test in `test.yml` to make sure it doesn't happen again?

```bash
if grep -q 'ProvisioningStyle = Automatic;' ios/NewExpensify.xcodeproj/project.pbxproj; then
  echo 'Error: Automatic provisioning style is not allowed!'
  exit 1
else
  exit 0
fi
```

2022-01-14 21:14 UTC, roryabraham approved these changes
LGTM

2022-01-14 21:30 UTC, AndrewGable approved these changes

2022-01-14 21:54 UTC, merged

2022-01-14 23:07 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1699756601) to staging by @roryabraham in version: 1.1.29-9 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-01-18 22:02 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1714965683) to production by @roryabraham in version: 1.1.30-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅