[No QA] fix: Fixed error with frequently used emojis not showing up
Expensify/App pull request #7255
Opened 2022-01-15 04:15 UTC by mananjadhav

### Details

- When working with #7125 we changed the logic for dynamic spacing. A bug was introduced where Frequently Used Emojis stopped showing up and this PR fixes it.

### Fixed Issues

$ https://github.com/Expensify/App/issues/7074

### Tests
1. Tested frequently used emojis in the EmojiPicker

- [x] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

![image](https://user-images.githubusercontent.com/3069065/149608455-d5277e4d-d113-4852-9cf0-a265d6c4861e.png)

#### Mobile Web

<img width="378" alt="Screenshot 2022-01-15 at 9 47 10 AM" src="https://user-images.githubusercontent.com/3069065/149608511-46ddc904-591c-473e-a13b-0f4671614f3d.png">

#### Desktop

<img width="459" alt="Screenshot 2022-01-15 at 9 50 09 AM" src="https://user-images.githubusercontent.com/3069065/149608683-54e9db87-afa0-4e77-925d-44b31ddc0ff7.png">

#### iOS

![image](https://user-images.githubusercontent.com/3069065/149609162-c6bfac4c-79a7-4ac5-af38-fa0b78bc7623.png)

#### Android

<img width="365" alt="Screenshot 2022-01-15 at 10 03 50 AM" src="https://user-images.githubusercontent.com/3069065/149608959-28002cf2-2df6-449a-aea1-6fec43f94bae.png">

2022-01-15 04:16 UTC, mananjadhav commented
@stitesExpensify  @parasharrajat @rushatgabhane When working with the last EmojiPicker PR, I introduced a bug where frequently used emojis were not showing up. Adding a fix for this and I am hoping if this can be CPed to staging.

2022-01-15 05:10 UTC, rushatgabhane commented on src/libs/EmojiUtils.js
> +    allEmojis = addSpacesToEmojiCategories(allEmojis);
return `addSpacesToEmojiCategories(allEmojis)` directly.

2022-01-15 05:11 UTC, rushatgabhane requested changes
Thanks for noticing and pushing the fix! 
Small change requested

2022-01-15 06:17 UTC, parasharrajat commented on src/libs/EmojiUtils.js
> +    allEmojis = addSpacesToEmojiCategories(allEmojis);
+1

2022-01-15 07:29 UTC, mananjadhav commented on src/libs/EmojiUtils.js
> +    allEmojis = addSpacesToEmojiCategories(allEmojis);
Updated

2022-01-15 07:30 UTC, mananjadhav commented
PR updated

2022-01-17 04:31 UTC, rushatgabhane approved these changes
LGTM!
cc: @stitesExpensify

2022-01-17 16:49 UTC, stitesExpensify approved these changes
LGTM

2022-01-17 16:50 UTC, merged

2022-01-17 18:10 UTC, roryabraham commented
Whoa, it seems like the CP label may not have worked here ... 🤔 I've never seen this so I'm going to investigate.

2022-01-17 18:10 UTC, roryabraham commented
Oh, the CP label was added _after_ the PR was merged.

2022-01-17 19:31 UTC, OSBotify commented
🚀 [Cherry-picked](https://github.com/Expensify/App/actions/runs/1709366304) to staging by @roryabraham in version: 1.1.30-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-01-18 22:02 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1714965683) to production by @roryabraham in version: 1.1.30-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅