fix: misspelled copy in bank account validation step
Expensify/App pull request #7289
Opened 2022-01-18 11:35 UTC by mdneyazahmad

### Details

Update copy in bank account validation step.
### Fixed Issues

$ https://github.com/Expensify/App/issues/6980

### Tests

1. Workspace -> Connect bank account
- [x] Verify that no errors appear in the JS console

### QA Steps

1. Same as test steps
- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

<img width="1440" alt="Screenshot 2022-01-18 at 4 19 05 PM" src="https://user-images.githubusercontent.com/77761491/149929358-c39809df-66d7-4bda-94cf-b0f58ccbe74e.png">
<img width="1440" alt="Screenshot 2022-01-18 at 4 41 13 PM" src="https://user-images.githubusercontent.com/77761491/149929428-f288dc98-ae6b-4530-a612-ad64ffc4b48d.png">

#### Mobile Web

![Simulator Screen Shot - iPhone 13 - 2022-01-18 at 16 45 26](https://user-images.githubusercontent.com/77761491/149929521-4a3b3048-f629-43b6-a42f-1038d7bfa1d3.png)
![Simulator Screen Shot - iPhone 13 - 2022-01-18 at 16 43 19](https://user-images.githubusercontent.com/77761491/149929538-272d259f-4698-41ac-acf2-a6b23e5d799a.png)

#### Desktop

<img width="1440" alt="Screenshot 2022-01-18 at 4 51 41 PM" src="https://user-images.githubusercontent.com/77761491/149929571-f590b248-8b44-4724-8ce2-7eb006259194.png">
<img width="1440" alt="Screenshot 2022-01-18 at 4 20 47 PM" src="https://user-images.githubusercontent.com/77761491/149929619-43e3e0ce-916a-4312-9665-04a120a2fdb6.png">

#### iOS

![Simulator Screen Shot - iPhone 13 - 2022-01-18 at 16 27 24](https://user-images.githubusercontent.com/77761491/149929691-100b4578-3126-404c-9874-1af1bc4b0a4a.png)
![Simulator Screen Shot - iPhone 13 - 2022-01-18 at 16 39 13](https://user-images.githubusercontent.com/77761491/149929739-ef267e60-1250-4fe2-8086-4152d2019586.png)

#### Android

Same as iOS

2022-01-18 15:30 UTC, rushatgabhane commented on src/languages/es.js
> +        letsChatText: 'Gracias Necesitamos tu ayuda para verificar la información, pero podemos hacerlo rápidamente a través del chat. ¿Estás listo?',
You're missing a period after Gracias

2022-01-18 15:35 UTC, rushatgabhane requested changes
looks good, suggested a change

2022-01-18 16:02 UTC, rushatgabhane approved these changes
@AndrewGable LGTM! 🎉

Adding Spanish copy as it isn't in screenshots.
<img src="https://user-images.githubusercontent.com/29673073/149973094-48e9e697-5619-4c2f-bfb5-4cd606bbbb49.png" height=500>

2022-01-18 23:47 UTC, AndrewGable approved these changes

2022-01-18 23:47 UTC, merged

2022-01-19 00:55 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1715417780) to staging by @AndrewGable in version: 1.1.30-6 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-01-21 00:14 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1726158569) to production by @chiragsalian in version: 1.1.31-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅