use preferred skin tone emoji when add using enter
Expensify/App pull request #7292
Opened 2022-01-18 19:06 UTC by thesahindia

### Details

Fixed the default emoji issue when added using enter

### Fixed Issues

$ https://github.com/Expensify/App/issues/7264

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Open a chat
2. Open the emoji picker
3. Change the default skin tone to something other than yellow
4. Select an emoji and hit enter/return on the keyboard
5. Verify the added emoji's skin tone is the preferred skin tone
- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

https://user-images.githubusercontent.com/83179295/150001950-4eb24f4d-1e45-48ba-8415-2275e25d2885.mov

#### Mobile Web

#### Desktop

https://user-images.githubusercontent.com/83179295/150001966-0bfbc41a-56c0-430b-8f89-dd098fb1ec05.mov

#### iOS

#### Android

2022-01-18 19:12 UTC, parasharrajat requested changes

2022-01-18 19:12 UTC, parasharrajat commented on src/pages/home/report/EmojiPickerMenu/index.js
> +                const emoji = item.types && item.types[this.props.preferredSkinTone]
use lodashGet instead.

2022-01-18 22:14 UTC, luacmartins requested changes
What @parasharrajat said

2022-01-19 16:26 UTC, thesahindia commented on src/pages/home/report/EmojiPickerMenu/index.js
> +                const emoji = item.types && item.types[this.props.preferredSkinTone]
Done.

2022-01-19 17:59 UTC, luacmartins approved these changes
LGTM and tests well. Thanks @thesahindia!

2022-01-19 17:59 UTC, merged

2022-01-19 18:00 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-01-19 18:38 UTC, parasharrajat reviewed
LGTM.  a little late but I reviewed it already.

:ribbon: :eyes: :ribbon:  C+ reviewed

2022-01-21 01:00 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1726162980) to staging by @luacmartins in version: 1.1.31-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-01-25 19:47 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1747303610) to production by @AndrewGable in version: 1.1.32-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2023-02-24 04:34 UTC, hayata-suenaga commented
I'll link a related [regression](https://github.com/Expensify/App/issues/15232) reported here, although this PR might have not directly caused the issue.

There is a possibility that emoji is not highlighted when there is no emoji candidates. When that happens `emoji` is `undefined`, and accessing `code` property of `undefined` causes an error.