fix: Added web link for desktop error page
Expensify/App pull request #7364
Opened 2022-01-21 22:17 UTC by mananjadhav

### Details

- Added web link for desktop error page

### Fixed Issues

$ https://github.com/Expensify/App/issues/7316

### Tests
1. Tested link for the Desktop App

- [x] Verify that no errors appear in the JS console

### QA Steps
Need to follow the reproduction steps from https://github.com/Expensify/App/pull/6856#issuecomment-1014869242 for Desktop.

- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

<img width="1435" alt="web-mobile-web-link" src="https://user-images.githubusercontent.com/3069065/150607424-c57dba0d-7263-47a3-a2f3-0fcd5a14a906.png">

#### Mobile Web

#### Desktop

<img width="1311" alt="desktop-link" src="https://user-images.githubusercontent.com/3069065/150607457-ccac7477-aeb6-4c1b-91a3-82c04726f2d4.png">

#### iOS

#### Android

2022-01-21 22:20 UTC, parasharrajat submitted a review, later dismissed
LGTM.

cc: @NikkiWines 
:ribbon: :eyes: :ribbon:  C+ reviewed

2022-01-21 23:44 UTC, NikkiWines requested changes

2022-01-21 23:44 UTC, NikkiWines commented on src/CONST.js
> +
extra line

2022-01-21 23:49 UTC, NikkiWines commented
Just a note that the linked QA steps don't work currently on dev - looks like someone fixed the room details issue. I would update the QA steps to direct the tester to go to a malformed URL like `https://new.expensify.com/r/75431276____/details`

2022-01-22 10:19 UTC, mananjadhav commented
> Just a note that the linked QA steps don't work currently on dev - looks like someone fixed the room details issue. I would update the QA steps to direct the tester to go to a malformed URL like `https://new.expensify.com/r/75431276____/details`

@NikkiWines Anyway to get this working for Desktop App? Because we can't enter URL there.

2022-01-24 18:33 UTC, NikkiWines commented
@mananjadhav oh, right - in that case if we can use the following steps for desktop (this flow works fine on web, oddly): 

1. Create a new room using the `+` FAB 
2. Click on the room's icon to open up the room details 
3. Click on `Settings`
4. Confirm you see the error page and that it directs you to switch to web 

https://user-images.githubusercontent.com/16747822/150841469-9b20c382-2184-48f8-9e2b-90cf77b79ddb.mov

2022-01-24 18:35 UTC, NikkiWines approved these changes
👍

2022-01-28 17:36 UTC, NikkiWines commented
@mananjadhav since you [mentioned tackling the url constant updates in a separate issue/PR](https://github.com/Expensify/App/issues/7316#issuecomment-1022314139), I'm going to go ahead and merge this - sound good?

2022-01-30 13:43 UTC, mananjadhav commented
Yeah thanks, will you also help create an issue then? It'll be easier to track?

2022-01-31 22:43 UTC, NikkiWines commented
@roryabraham created one already [here](https://github.com/Expensify/App/issues/7489)

2022-01-31 22:43 UTC, merged

2022-01-31 22:44 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-02-01 18:47 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1779801091) to staging by @NikkiWines in version: 1.1.33-4 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-02-02 18:51 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1785535610) to production by @sketchydroide in version: 1.1.34-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅