[NO-QA]Use renamed git repo for change step
Expensify/App pull request #7409
Opened 2022-01-25 23:59 UTC by AndrewGable

### Details
`futuratrepadeira/changed-files` was renamed to `umani/changed-files`, I'm not sure it's causing errors in this repo, but it was in a different one, so let's just update to the renamed repo just in case.

### Fixed Issues

$ GH_LINK

### Tests

- [ ] Verify that no errors appear in the JS console

### QA Steps

- [ ] Verify that no errors appear in the JS console

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2022-01-26 00:04 UTC, roryabraham requested changes
I don't see this commit hash in the umani repo:

![image](https://user-images.githubusercontent.com/47436092/151080328-1a003a17-8a27-4df1-8114-e6717be813c4.png)

I guess the commits got renamed along with the repo 🤷

2022-01-26 00:07 UTC, AndrewGable commented
I see it here: https://github.com/umani/changed-files/commit/1d252c611c64289d35243fc37ece7323ea5e93e1

2022-01-26 01:00 UTC, roryabraham commented
Weird, I see the same commit with a different hash:

![image](https://user-images.githubusercontent.com/47436092/151085266-7e81d66b-dc0f-477d-9c12-aae9afbe129a.png)

https://github.com/umani/changed-files/commit/ca328ebf8ca65f94258677cea8478f0094d76a8e

2022-01-26 01:01 UTC, roryabraham approved these changes

2022-01-26 01:01 UTC, merged

2022-01-26 01:02 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-01-26 01:02 UTC, AndrewGable commented
<img width="1382" alt="Screen Shot 2022-01-25 at 6 01 26 PM" src="https://user-images.githubusercontent.com/2838819/151085385-c633556b-6a5f-4194-a142-e9ed5387c202.png">
<img width="1393" alt="Screen Shot 2022-01-25 at 6 01 19 PM" src="https://user-images.githubusercontent.com/2838819/151085387-d5d71049-b18a-4044-b0ae-659203e50cb3.png">

I think the hash changes based on which branch you are looking at.

I used the hash that was listed under the lastest release, which must not have used the `master` branch

<img width="1418" alt="Screen Shot 2022-01-25 at 6 02 18 PM" src="https://user-images.githubusercontent.com/2838819/151085462-4d7bb466-e97f-415f-8a3c-d00c14135e50.png">

2022-02-01 18:48 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1779801091) to staging by @roryabraham in version: 1.1.33-4 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-02-02 18:52 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1785535610) to production by @sketchydroide in version: 1.1.34-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅