Separate report name and icon configuration from personal details
Expensify/App pull request #7453
Opened 2022-01-28 16:13 UTC by sobitneupane

### Details

Solves the issue "Private Room - Chair icon not displayed for private room created". I have tested on Web, mWeb and Android. But no on IOS and MacOS. So, I would like to request reviewer to double check for IOS and MacOS.

### Fixed Issues

$ https://github.com/Expensify/App/issues/7261

### Tests

- Create New Room (Private) and check report name and icon
- Create New Room (Restricted) and check report name and icon
- Create New Group and check report name and icon
- Create New Chat and check report name and icon

### QA Steps

- Create New Room (Private) and check report name and icon
- Create New Room (Restricted) and check report name and icon
- Create New Group and check report name and icon
- Create New Chat and check report name and icon

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [x] Android

### Screenshots

#### Web

![Screenshot from 2022-01-28 20-28-14](https://user-images.githubusercontent.com/25876548/151580490-ecb783a4-9eac-4dbd-bbdb-f3c1d722a46b.png)
![Screenshot from 2022-01-28 20-27-13](https://user-images.githubusercontent.com/25876548/151580531-afecd8e5-8097-490a-95a6-f3e65f4736eb.png)
![Screenshot from 2022-01-28 20-26-50](https://user-images.githubusercontent.com/25876548/151580563-300ef07a-9225-435a-8d16-a65e86d61bae.png)
![Screenshot from 2022-01-28 20-26-18](https://user-images.githubusercontent.com/25876548/151580591-3bae7c8f-da6a-4e29-996c-17dedd91a46d.png)

#### Mobile Web

![Screenshot_20220128-213159_Chrome](https://user-images.githubusercontent.com/25876548/151581134-beecf59c-0dd4-4503-b2e4-2bacec6e395d.jpg)
![Screenshot_20220128-213418_Chrome](https://user-images.githubusercontent.com/25876548/151581142-043f255b-0eed-424a-968b-52326dbae872.jpg)

#### Desktop

#### iOS

#### Android

![Screenshot_20220128-211519_New Expensify](https://user-images.githubusercontent.com/25876548/151581672-a0506fd5-6869-489b-93db-264d78e259ac.jpg)
![Screenshot_20220128-210044_New Expensify](https://user-images.githubusercontent.com/25876548/151581683-e427539f-a831-4ae1-b6d8-384f5998a4a9.jpg)
![Screenshot_20220128-205843_New Expensify](https://user-images.githubusercontent.com/25876548/151581824-407ffb8d-28f1-433b-89dc-05862dc38417.jpg)

2022-01-29 04:29 UTC, parasharrajat commented
@sobitneupane What change did you make to resolve the regression over your previous changes?

2022-01-29 05:06 UTC, sobitneupane commented
> @sobitneupane What change did you make to resolve the regression over your previous changes?

I was trying to get reportName from details instead of formattedPersonalDetails in the following line:
https://github.com/sobitneupane/App/blob/efb1f415fcbb823a64f5d6126bb10449e5ba0bf0/src/libs/actions/Report.js#L341

2022-01-29 06:16 UTC, parasharrajat requested changes

2022-01-29 06:16 UTC, parasharrajat commented on src/libs/actions/Report.js
> +                    formattedPersonalDetails,
```suggestion
                    PersonalDetails.formatPersonalDetails(details),
```

2022-01-29 06:16 UTC, parasharrajat commented on src/libs/actions/Report.js
> +    const formattedPersonalDetails = PersonalDetails.formatPersonalDetails(details);
```suggestion
```

2022-01-29 07:55 UTC, parasharrajat submitted a review, later dismissed
LGTM. This PR contains logical changes which should work across platforms thus skipping checks for Mac or iOS screenshots.

Note: @sobitneupane we are planning to make IOS check mandatory so you should plan accordingly for future tasks. [More details](https://expensify.slack.com/archives/C01GTK53T8Q/p1643332235703469)


cc: @tgolen 

:ribbon: :eyes: :ribbon:  C+ reviewed

2022-01-31 17:11 UTC, tgolen requested changes

2022-01-31 17:11 UTC, tgolen commented on src/libs/actions/Report.js
> +        const avatars = ReportUtils.isChatRoom(report) ? (['']) : OptionsListUtils.getReportIcons(report, details);
It would be nice to have a comment in the code to explain why both of the ternaries exist.

2022-01-31 17:11 UTC, tgolen commented on src/libs/actions/Report.js
> +        const reportName = ReportUtils.isChatRoom(report)
I see `ReportUtils.isChatRoom(report)` referenced twice in this code, so moving it to a local variable would be better.

2022-02-02 17:03 UTC, tgolen requested changes
Looks good! Just this one last change and I'll merge it.

2022-02-02 17:03 UTC, tgolen commented on src/libs/actions/Report.js
> +        const avatars = isChatRoom ? (['']) : OptionsListUtils.getReportIcons(report, details);
```suggestion
        const avatars = isChatRoom ? [''] : OptionsListUtils.getReportIcons(report, details);
```

2022-02-02 17:24 UTC, parasharrajat commented on src/libs/actions/Report.js
> +        const avatars = isChatRoom ? (['']) : OptionsListUtils.getReportIcons(report, details);
+1.

2022-02-03 16:04 UTC, tgolen approved these changes

2022-02-03 16:05 UTC, merged

2022-02-03 16:05 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-02-04 12:23 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1794653053) to staging by @tgolen in version: 1.1.36-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-02-07 18:50 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1808141397) to production by @roryabraham in version: 1.1.36-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅