Sync workspace member across devices after removing member(s)
Expensify/App pull request #7460
Opened 2022-01-31 02:07 UTC by K4tsuki

### Details

Sync workspace member across device after member(s) removed.

### Fixed Issues

$ https://github.com/Expensify/App/issues/7095

### Tests

- [x] Verify that no errors appear in the JS console

1. Open workspace member page with same account on two device
2. Remove member(s) on a device and refresh member page in other device
3. Members of workspace must be same on those two device
4. In android must go back to setting page and then go to member page to update the member list.

### QA Steps

- [x] Verify that no errors appear in the JS console

1. Open workspace member page with same account on two device
2. Remove member(s) on a device and refresh member page in other device
3. Members of workspace must be same on those two device
4. In android must go back to setting page and then go to member page to update the member list.

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [x] Android

### Screenshots

#### Web

https://user-images.githubusercontent.com/1313124/151729076-e7d437b3-51b1-4dc9-87f5-e146f4b476f2.mp4

#### Mobile Web

https://user-images.githubusercontent.com/1313124/151729110-04065df4-ff0b-499c-85f6-80e8a625601a.mp4

#### Desktop

#### iOS

#### Android

https://user-images.githubusercontent.com/1313124/151729126-27f8df6a-67f1-4e2a-a7dc-6f5cec888f0b.mp4

2022-01-31 08:10 UTC, parasharrajat requested changes

2022-01-31 08:10 UTC, parasharrajat commented on src/libs/actions/Policy.js
> +            Onyx.set(`${ONYXKEYS.COLLECTION.POLICY}${policy.id}`, updatedPolicyObject);
```suggestion
             Onyx.set(`${ONYXKEYS.COLLECTION.POLICY}${policy.id}`, {
            	... allPolicies[`${ONYXKEYS.COLLECTION.POLICY}${policy.id}`],
            	...getSimplifiedPolicyObject(policy),
            });
```

2022-02-01 06:31 UTC, K4tsuki commented
Fix linter

2022-02-01 09:49 UTC, parasharrajat submitted a review, later dismissed
Works fine for the linked issue. 

There could be unintended side-effects of this change. `withFullPolicy` is used on all workspace pages. we use `Onyx.merge` to merge the changes but for this we are using `Onyx.set`. There are `limitations` of using `Onyx.set`. It cancels the `merge` requests which could interfere with other Workspace pages operations. **This is an assumption so It is possible that it never happens**. 

But Onyx poses a challenge for us and it does not give us any other choice to fix the linked issue ATM. So I am approving this. 

cc: @Luke9389 

:ribbon: :eyes: :ribbon:  C+ reviewed

2022-02-03 00:06 UTC, K4tsuki commented
cc: @Luke9389  All checks have passed

2022-02-03 19:47 UTC, Luke9389 commented
> There could be unintended side-effects of this change.

@parasharrajat, this concerns me. Before approving I'm going to go read up on Onyx and be sure this change is exactly what we want it to be.

2022-02-03 23:20 UTC, K4tsuki commented
@Luke9389  We have been using Onyx.set in `removeMember` and there was no problem because of this.

https://github.com/Expensify/App/blob/16d38de1a943bc8393d34b745898f9d546a9e5be/src/libs/actions/Policy.js#L299

Also Kidroca tell to us to using Onyx.set in this issue in slack conversation. 

I have tested it on navigating between workspaces, add and remove members and there is no problem.

2022-02-04 00:17 UTC, Luke9389 requested changes
Looks like there's now a merge conflict. Please merge main

2022-02-04 02:18 UTC, K4tsuki commented
@Luke9389 main merged.

2022-02-04 20:19 UTC, Luke9389 approved these changes
After reviewing some materials, I think this is fine.

2022-02-04 20:19 UTC, merged

2022-02-04 20:20 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-02-07 19:33 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1808152862) to staging by @Luke9389 in version: 1.1.37-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-02-09 17:14 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1819294181) to production by @roryabraham in version: 1.1.37-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅