Remove null values when calling Ion.merge() batch merge updates
Expensify/App pull request #751
Opened 2020-11-04 20:17 UTC by marcaaron

cc @quinthar @tgolen 

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/145190

### Tests
1. Verify data is able to be set and merged normally
1. Run this test to verify that `Ion.merge('someKey', {test: null})` can remove a key safely

e.g. add this diff to `Expensify.js`

```diff
diff --git a/src/Expensify.js b/src/Expensify.js
index 56623e01..59c516f1 100644
--- a/src/Expensify.js
+++ b/src/Expensify.js
@@ -10,6 +10,20 @@ import IONKEYS from './IONKEYS';
 import withIon from './components/withIon';
 import styles from './styles/StyleSheet';
 import Log from './libs/Log';
+import AsyncStorage from '@react-native-community/async-storage';
+
+Ion.merge('testing', {1: '1'});
+Ion.merge('testing', {2: '2'});
+Ion.merge('testing', {3: '3'});
+Ion.merge('testing', {4: '4'});
+
+Ion.merge('testing', {1: null});
+Ion.merge('testing', {2: null});
+
+setTimeout(() => {
+    AsyncStorage.getItem('testing')
+        .then(result => console.log(result));
+}, 2000);
```
and verify you see that the keys have been removed and an object like this remains `{3: '3', 4: '4'}`

### Screenshots
❌

2020-11-04 22:39 UTC, tgolen requested changes

2020-11-05 00:02 UTC, tgolen requested changes

2020-11-05 13:00 UTC, Gonals submitted a review, later dismissed
Looks good to me, although reviewing it has likely been more useful for me than for you. It made me take a better look at our ReactNative storage stuff.
Thanks!

2020-11-09 17:20 UTC, tgolen submitted a review, later dismissed

2020-11-09 18:31 UTC, tgolen approved these changes

2020-11-09 18:31 UTC, merged