fix the thumnail size relative to viewport
Expensify/App pull request #7600
Opened 2022-02-07 14:47 UTC by parasharrajat

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/7382

### Tests | QA Steps
1. 

- [x] Verify that no errors appear in the JS console

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2022-02-11 16:54 UTC, parasharrajat commented
Do we want to keep a minimum height for all images? For e.g. 40px takes from existing code. 

Otherwise, the image height could be very small based on the original upload image. 

try this image. 
![image](https://user-images.githubusercontent.com/24370807/153633818-b03c81d2-2ccc-4b44-aee1-ed66df5cddb5.png)


Setting the minimum 40px height will show as. 
|Before|After|
|------------|-------|
|![image](https://user-images.githubusercontent.com/24370807/153634062-56aeec1b-c7e3-4b39-acd3-97ff8a9935d5.png)|![image](https://user-images.githubusercontent.com/24370807/153633953-5d81b5a6-49da-4029-89b1-2707370b2d67.png)|

2022-02-11 17:20 UTC, NikkiWines commented
Yeah, I think a minimum height is good. Images that are long + skinny can be hard to click on because they're so small. Slack does something very similar to what you're suggesting as well 👍 

![image](https://user-images.githubusercontent.com/16747822/153638237-12beaa70-f6e0-469e-a962-89d02e490e9a.png)

2022-02-11 18:23 UTC, NikkiWines requested changes
Some minor minor comments but overall looks good

2022-02-11 18:23 UTC, NikkiWines commented on src/components/ThumbnailImage.js
> +
Extra blank line

2022-02-11 18:23 UTC, NikkiWines commented on src/components/ThumbnailImage.js
> +        if (thumbnailScreenHeight > thumbnailScreenWidth) {
A comment here about what this is doing might be nice

2022-02-11 18:23 UTC, NikkiWines commented on src/components/ThumbnailImage.js
>          const scaleFactor = width / thumbnailScreenWidth;
NAB: scale factor doesn't really need to be its own variable. 

```Javascript
        const imageHeight = height / (width / thumbnailScreenWidth);

2022-02-11 22:41 UTC, NikkiWines approved these changes
Looks good! One minor note, QA steps say "Send the attached image" but I don't see an attached image to send.

2022-02-11 22:41 UTC, merged

2022-02-11 22:51 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-02-15 19:32 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1848714986) to staging by @NikkiWines in version: 1.1.39-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-02-23 21:21 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1889636234) to production by @timszot in version: 1.1.39-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅