[NO QA]Run tests and lint on merge into main
Expensify/App pull request #7632
Opened 2022-02-08 17:40 UTC by AndrewGable

### Details
Runs both the lint and test workflows when we merge code into `main`, which will hopefully prevent us from trying to deploy unlinted code that will cause the builds to fail.

### Fixed Issues
$ https://github.com/Expensify/App/issues/7026

### Tests
1. Merge this PR
2. Verify both tests and lint run and pass ✅ 

### QA Steps
N/A

### Tested On
N/A

2022-02-08 17:50 UTC, mountiny submitted a review, later dismissed
LGTM, but Rory knows the actions way better. Leaving it over to you.

2022-02-09 05:30 UTC, roryabraham requested changes
Is your intention to prevent preDeploy from triggering a staging deploy if tests fail? If so, I think you need to make other jobs, particularly `version`, dependent upon the results of the `confirmPassingBuilds` job using the `needs` keyword and the job-level `if` clause for the `version` job.

2022-02-09 16:15 UTC, AndrewGable commented
Ok so I _think_ the latest changes will do what we want? Basically if lint or tests do not pass, don't continue the deploy workflow?

2022-02-10 23:48 UTC, roryabraham approved these changes

2022-02-10 23:58 UTC, merged

2022-02-15 19:33 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1848714986) to staging by @roryabraham in version: 1.1.39-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-02-23 21:22 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1889636234) to production by @timszot in version: 1.1.39-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅