Add GitHub Action linting (Expect lint to *fail*)
Expensify/App pull request #7697
Opened 2022-02-11 00:43 UTC by AndrewGable

### Details

### Fixed Issues

$ GH_LINK

### Tests

- [ ] Verify that no errors appear in the JS console

### QA Steps

- [ ] Verify that no errors appear in the JS console

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2022-02-11 23:00 UTC, roryabraham requested changes

2022-02-11 23:18 UTC, AndrewGable commented on .github/workflows/deployBlocker.yml
> +          { echo "DEPLOY_BLOCKER_URL=${{ github.event.issue.html_url }}"; echo "DEPLOY_BLOCKER_NUMBER=${{ github.event.issue.number }}"; echo "DEPLOY_BLOCKER_TITLE=$(sed -e "s/'/'\\\\''/g; s/\`/\\\\\
It was complaining that I needed to lump the commands together, but I will try new lines with `\`

2022-02-12 01:26 UTC, roryabraham commented on .github/workflows/deployBlocker.yml
> +          { echo "DEPLOY_BLOCKER_URL=${{ github.event.issue.html_url }}"; echo "DEPLOY_BLOCKER_NUMBER=${{ github.event.issue.number }}"; echo "DEPLOY_BLOCKER_TITLE=$(sed -e "s/'/'\\\\''/g; s/\`/\\\\\
Well ... still NAB because you didn't introduce this.

2022-02-14 17:21 UTC, neil-marcellini reviewed
Looks pretty good to me as much as I understand it.

2022-02-14 17:22 UTC, AndrewGable commented
Thanks for the review @roryabraham and @neil-marcellini! I will pick up the review comments later today.

2022-02-14 22:18 UTC, roryabraham approved these changes

2022-02-15 18:31 UTC, merged

2022-02-15 19:56 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1848796786) to staging by @AndrewGable in version: 1.1.39-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-02-23 21:20 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1889636234) to production by @timszot in version: 1.1.39-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅