[No QA] Update getInputIDPropTypes docs
Expensify/App pull request #7754
Opened 2022-02-15 16:03 UTC by luacmartins

### Details
Updates docs for `getInputIDPropTypes`

### Fixed Issues
$ https://github.com/Expensify/App/issues/7753

### Tests
N/A docs changes only!

- [X] Verify that no errors appear in the JS console

### QA Steps
N/A

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2022-02-15 17:06 UTC, tgolen requested changes

2022-02-15 17:13 UTC, luacmartins commented
Updated!

2022-02-15 17:33 UTC, tgolen approved these changes

2022-02-15 17:34 UTC, merged

2022-02-15 17:34 UTC, botify commented
@tgolen looks like this was merged without passing tests. Please add a note explaining why this was done and remove the `Emergency` label if this is not an emergency.

2022-02-15 17:44 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-02-23 21:20 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1889636234) to production by @timszot in version: 1.1.39-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅