Keep chats with draft comments in the LHN
Expensify/App pull request #781
Opened 2020-11-10 10:39 UTC by Gonals

@nickmurray47 @tgolen, can you review?

### Fixed Issues
Fixes $ https://github.com/Expensify/Expensify/issues/145380

### Tests
1. Open a chat in Native Chat, make sure it is not pinned and write a comment. Don't send it.
2. While you are in the chat, nothing should change in the LHN.
3. Leave the chat by selecting a different one. The first chat should remain in the LHN and have a little icon by it:
<img width="303" alt="Screen Shot 2020-11-20 at 10 29 40 AM" src="https://user-images.githubusercontent.com/19366280/99786240-87114000-2b1e-11eb-8359-f9afe5d19527.png">
4. Go back to the chat and delete the comment. When you leave the chat, it should go away from the LHN.

### Screenshots
<img width="320" alt="Screen Shot 2020-11-27 at 10 59 48 AM" src="https://user-images.githubusercontent.com/19366280/100437585-3f9c2e00-30a1-11eb-8763-b5e80f98d75d.png">
<img width="454" alt="Screen Shot 2020-11-27 at 11 09 34 AM" src="https://user-images.githubusercontent.com/19366280/100437592-432fb500-30a1-11eb-8a8b-5927137d5bf8.png">

2020-11-20 16:02 UTC, tgolen requested changes

2020-11-20 17:57 UTC, nickmurray47 reviewed
Looks good and tests well! A few small changes to make it seems.

2020-11-23 17:31 UTC, tgolen requested changes

2020-11-24 16:12 UTC, tgolen requested changes

2020-12-01 17:11 UTC, tgolen approved these changes

2020-12-01 17:11 UTC, merged