P2P KYC - Fix errors at field level
Expensify/App pull request #7812
Opened 2022-02-18 09:57 UTC by nkuoch

### Details
When there was an error at field level, the field didn't get red, and the corresponding error didn't show up.
It's because getErrors was always sending the original props, not the updated ones that were received after an Onyx change.
Now, I'm passing the right props.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/197281

### Tests / QA Steps
Try to transfer your wallet balance.
When asked for your personal additional details, submit the form with empty fields.
Required fields should get red and with a corresponding error message.

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots
![image](https://user-images.githubusercontent.com/2463975/154660039-fc7e8798-cba6-495d-8743-55d477bb71f0.png)

#### Web

2022-02-18 17:18 UTC, marcaaron requested changes
Thanks for finding this! 🙇  Just left a couple style comments.

2022-02-18 17:18 UTC, marcaaron commented on src/pages/EnablePayments/AdditionalDetailsStep.js
> +    clearError(path) {
style - needs a doc with `@param {String} path`

2022-02-18 19:46 UTC, nkuoch commented
Updated

2022-02-18 19:48 UTC, nkuoch commented
updated

2022-02-22 17:39 UTC, marcaaron approved these changes

2022-02-22 17:39 UTC, merged

2022-02-23 21:59 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1889649076) to staging by @marcaaron in version: 1.1.40-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-02-24 19:25 UTC, nkuoch commented
I just checked it off thanks

2022-03-01 18:49 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1917947501) to production by @yuwenmemon in version: 1.1.40-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅