P2P KYC - Handle Idology questions
Expensify/App pull request #7813
Opened 2022-02-18 10:01 UTC by nkuoch

### Details

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/193505

### Tests

- [ ] Verify that no errors appear in the JS console

### QA Steps

- [ ] Verify that no errors appear in the JS console

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2022-02-20 13:27 UTC, nkuoch commented
Tested with this [secure PR](https://github.com/Expensify/Web-Secure/pull/2154).

Click on your profile pic.

![image](https://user-images.githubusercontent.com/2463975/154844744-c7206b7c-fdb4-43ba-8d6a-dd879b016095.png)

Click on Payment

![image](https://user-images.githubusercontent.com/2463975/154844761-d8590a87-00c5-406d-acff-6334377ec43f.png)

Click on Transfert balance

Run in the console: `Onyx.merge('userWallet', {currentStep: 'AdditionalDetailsStep'});`

![image](https://user-images.githubusercontent.com/2463975/154844813-479baf3d-e8cb-4cf4-94e3-e426315e5506.png)

Enter your info then **Save & Continue**

![image](https://user-images.githubusercontent.com/2463975/154844843-c1b59d51-da5f-4bb0-b8e3-db0864609dc4.png)

You should see the questions and answers to pick ... This is what we need to design.

2022-02-22 16:34 UTC, botify commented
Hey, I noticed you changed some webpack configuration files. This can break production builds. Did you remember to run a production build locally to verify they still work?

2022-03-02 14:40 UTC, nkuoch commented
Tested birthDate error:
![image](https://user-images.githubusercontent.com/2463975/156378875-6bf9474b-a125-440f-be95-fb40ceb4c3db.png)

![image](https://user-images.githubusercontent.com/2463975/156382658-21e5fba8-27a5-4c2a-9a72-f869de1cc5e7.png)

Tested address error:
![image](https://user-images.githubusercontent.com/2463975/156379123-e0a755f5-5f92-4c2e-a469-29f1b36a97b7.png)

![image](https://user-images.githubusercontent.com/2463975/156382610-0a6401cd-f420-4142-b135-13ef280aaf92.png)

Tested ssn error:
![image](https://user-images.githubusercontent.com/2463975/156379522-6e93f2a3-0e31-47a9-94b9-075e9734f5bb.png)

![image](https://user-images.githubusercontent.com/2463975/156382551-ec0e2a8b-e0a6-436b-89a1-5aa4f8b5a22e.png)

Tested lastName error:
![image](https://user-images.githubusercontent.com/2463975/156379651-98be5d30-5215-42b1-a146-4a04b3a4064a.png)

![image](https://user-images.githubusercontent.com/2463975/156382476-c958e6e7-eccf-405d-b3e8-cf5d85a553a8.png)

Tested combining 2 errors:
![image](https://user-images.githubusercontent.com/2463975/156381574-52f6a9c7-1f1a-4b0a-8e73-1cbdf46b800a.png)

![image](https://user-images.githubusercontent.com/2463975/156382398-ff91492c-a9ac-4ad4-9bf2-2b84b94dd24d.png)

Tested combining 3 errors:
![image](https://user-images.githubusercontent.com/2463975/156381676-d12c2eea-4c3a-4846-825b-0e6c68f23bc3.png)

![image](https://user-images.githubusercontent.com/2463975/156382292-ce02a564-abfb-488b-8e37-6819e63037aa.png)

2022-03-03 23:37 UTC, marcaaron commented on src/components/RadioButtons.js
> +    <RadioForm
Gonna tag in @shawnborton on this to get his thoughts. 

I wouldn't push back on this. I also feel like a radio button component is simple enough that we can design something custom with JS and not have another dependency to review. We made our own [checkbox](https://github.com/Expensify/App/blob/692f92d08ff5025de0c03aeea9a996e088cb4f40/src/components/Checkbox.js#L27-L28) and a radio button is kind of just a circular checkbox 😄

2022-03-03 23:52 UTC, marcaaron reviewed
Changes are looking good. Just leaving a few style notes to start off. Haven't tested yet.

2022-03-03 23:52 UTC, marcaaron commented on src/libs/Localize.js
> + * @return {string}
```suggestion
 * @param {Array} anArray
 * @return {String}
```

2022-03-03 23:52 UTC, marcaaron commented on src/libs/Localize.js
> + * Format an array into a string with coma and "and" ("a dog, a cat and a chicken")
```suggestion
 * Format an array into a string with comma and "and" ("a dog, a cat and a chicken")
```

2022-03-03 23:52 UTC, marcaaron commented on src/libs/actions/Wallet.js
> + * @param {string} [idNumber]
```suggestion
 * @param {String} [idNumber]
```

2022-03-03 23:52 UTC, marcaaron commented on src/libs/actions/Wallet.js
> + * @return {string}
```suggestion
 * @param {Array} idologyErrors
 * @return {String}
```

2022-03-03 23:52 UTC, marcaaron commented on src/pages/EnablePayments/IdologyQuestions.js
> +     * @param {string} answer
```suggestion
     * @param {Number} questionIndex
     * @param {String} answer
```

2022-03-04 10:43 UTC, nkuoch commented on src/components/RadioButtons.js
> +    <RadioForm
ah yes interesting - I'll try to do something similar to our checkbox, see if it's easy, I'll switch to that

2022-03-04 11:23 UTC, nkuoch commented on src/components/RadioButtons.js
> +    <RadioForm
Looks easy enough :)

![image](https://user-images.githubusercontent.com/2463975/156754889-82fe4ba7-1dc8-484a-a86a-13f00aa3d79a.png)

2022-03-04 11:33 UTC, nkuoch commented on src/components/RadioButtons.js
> +    <RadioForm
Extracted into a separate PR: https://github.com/Expensify/App/pull/8009

2022-03-05 00:36 UTC, shawnborton commented on src/components/RadioButtons.js
> +    <RadioForm
Commented over there :) Thanks Nathalie!

2022-03-07 07:07 UTC, ctkochan22 commented
Looks good. Going to test first thing tomorrow

2022-03-08 19:59 UTC, nkuoch commented
Ok, I rebased main, squashed all my commits together so it's cleaner, forced push, and now that it's not holding on anything anymore, it's ready to be reviewed, tested and merge!

2022-03-10 07:09 UTC, ctkochan22 submitted a review, later dismissed

2022-03-10 07:17 UTC, marcaaron requested changes
Really great stuff, thanks for the changes. Just spotted a few minor things after doing a full review. Will give it a test first thing tomorrow.

2022-03-10 07:17 UTC, marcaaron commented on src/libs/actions/Wallet.js
> +                    let qualifiers = _.get(response, ['data', 'requestorIdentityID', 'apiResult', 'qualifiers', 'qualifier'], []);
Oh yeah small thing but we have [standardized](https://github.com/Expensify/App/blob/main/STYLE.md#accessing-object-properties-and-default-values) on using `lodashGet()`. A `get()` was added to underscore in a recent version, but doesn't have the path based syntax like (`lodashGet(response, 'data. requestorIdentityID.apiResult.etc')`) so we avoid using it to keep things consistent.

2022-03-10 07:17 UTC, marcaaron commented on src/libs/actions/Wallet.js
> +                    if (_.get(response, ['data', 'requestorIdentityID', 'apiResult', 'results', 'key']) === 'result.no.match'
`lodashGet()`

2022-03-10 07:17 UTC, marcaaron commented on src/pages/EnablePayments/IdologyQuestions.js
> +        const possibleAnwers = _.filter(_.map(question.answer, (answer) => {
```suggestion
        const possibleAnswers = _.filter(_.map(question.answer, (answer) => {
```

2022-03-10 13:53 UTC, nkuoch commented
Tests:

Have your US IP whitelisted by Idology.

Create account gold@p2pkyc.com using `../script/clitools.sh generator:account`
Set his wallet to gold using `../script/clitools.sh validator:wallet`
Create a VBA using `../script/clitools.sh generator:bankaccount`
![image](https://user-images.githubusercontent.com/2463975/157659615-9ec6e544-6f30-4f3f-b4da-aeea76db8db5.png)
Run `UPDATE bankAccounts SET defaultCredit=1 WHERE bankAccountID={vbaBankAccountID};`

Create account recipient@p2pkyc.com using `../script/clitools.sh generator:account` 

Send money from gold@p2pkyc.com to recipient@p2pkyc.com
![image](https://user-images.githubusercontent.com/2463975/157665314-1eab0db8-78f9-4c6b-a859-543e89f8d23e.png)

Sign into recipient@p2pkyc.com, and click on Payments > Transfer Balance > Bank Account
![image](https://user-images.githubusercontent.com/2463975/157665559-88f259dc-fb55-4dda-99b8-36909c5b5753.png)

Add Plaid Chase credentials
![image](https://user-images.githubusercontent.com/2463975/157665789-81591e74-761a-453c-9c48-a8047bced07c.png)

Now that your Payment Method has been added, click again on Transfer Balance
![image](https://user-images.githubusercontent.com/2463975/157665933-2380093b-f8d7-4e4b-815b-c7b40dc8eb1c.png)

![image](https://user-images.githubusercontent.com/2463975/157665995-209f9336-022b-42f7-9936-d51a6877cbd7.png)

You should see Onfido flow
![image](https://user-images.githubusercontent.com/2463975/157666094-e74e9039-6591-4757-957b-d09e82ae42a2.png)

Did `./script/ngrok.sh nkuoch --secure` and commented in secure `if (Onfido_API::checkSignature` so we can receive Onfido webhook.

2022-03-14 05:51 UTC, nkuoch commented
bump @marcaaron ?

2022-03-14 17:29 UTC, ctkochan22 approved these changes

2022-03-14 21:00 UTC, marcaaron approved these changes
Looks great thanks!

2022-03-14 21:00 UTC, merged

2022-03-14 21:09 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-03-15 21:36 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1989064633) to staging by @marcaaron in version: 1.1.43-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-03-17 17:56 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1999874717) to production by @roryabraham in version: 1.1.43-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅