fix: Move extension field to the next line
Expensify/App pull request #7826
Opened 2022-02-19 07:33 UTC by mananjadhav

### Details

- Extension field label "Extension (Optional)" was overlapping with the text for smaller screen devices. 

### Fixed Issues

$ https://github.com/Expensify/App/issues/7645

### Tests
1. Tested the field in all the platforms
2. Tested the label in small screen device.

- [x] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2022-02-19 13:14 UTC, mountiny reviewed
LGTM, gonna wait for Rajat with approval.

2022-02-19 14:20 UTC, parasharrajat requested changes

2022-02-19 14:20 UTC, parasharrajat commented on src/pages/RequestCallPage.js
> +                            <View style={[styles.flex1]}>
I don't think flex1 is needed so just remove this view.

2022-02-19 14:20 UTC, parasharrajat commented on src/pages/RequestCallPage.js
> +                            <View style={[styles.mt4, styles.flex1]}>
we can remove this view as well and add the mt4 to text input and remove flex1.

2022-02-19 16:27 UTC, mananjadhav commented
@parasharrajat PR updated

2022-02-19 16:38 UTC, parasharrajat approved these changes
LGTM. 

CC: @mountiny 

:ribbon: :eyes: :ribbon:  C+ reviewed

2022-02-20 16:12 UTC, mountiny approved these changes
Thank you both!

2022-02-20 16:12 UTC, merged

2022-02-20 16:22 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-02-23 21:59 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1889649076) to staging by @mountiny in version: 1.1.40-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-03-01 18:49 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1917947501) to production by @yuwenmemon in version: 1.1.40-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅