refactor add payment dynamic
Expensify/App pull request #7847
Opened 2022-02-20 15:54 UTC by phivh

### Details
- Added one window listener that observed resize event and re-set position of the menu, there is a reason that needs to migrate the listener into dimension method.

### Fixed Issues

$ [#7385](https://github.com/Expensify/App/issues/7385)

### Tests

- [x] Tested by access to the payment page from the setting page.

### QA Steps

- [x] Login on web / desktop app
- [x] Select profile > payments
- [x] Select add payment method
- [x] Change screen width
- [x] Verify

### Tested On

- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

#### Web

https://user-images.githubusercontent.com/5449119/154851435-85db3ef8-618a-40d2-bb15-f1bd8fbef35b.mp4

#### Mobile Web

NA
#### Desktop

https://user-images.githubusercontent.com/5449119/152561282-dffec0b4-24e0-4a76-b9a2-4b98856d6065.mp4

#### iOS

NA
#### Android

NA

2022-02-22 00:16 UTC, rushatgabhane requested changes
@phivh small issue here - payment popover jumps down on resizing.

https://user-images.githubusercontent.com/29673073/155041131-62b56ebc-22a9-409f-9d5f-f921e2d21819.mp4

2022-02-27 13:51 UTC, phivh commented
@rushatgabhane @deetergp updated!

2022-02-28 05:00 UTC, rushatgabhane commented
@phivh could you please post a quick explaination on what fixed the resizing bug? Thanks

2022-02-28 16:34 UTC, rushatgabhane requested changes
@phivh really minor changes

2022-02-28 16:34 UTC, rushatgabhane commented on src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
> +        this.dimensionsSubscription = null;
This isn't needed, and can be removed

2022-02-28 16:34 UTC, rushatgabhane commented on src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
> +            addPaymentMethodButton: null,
Are you sure we need to put this in state? wouldn't a class variable suffice?

2022-02-28 16:34 UTC, rushatgabhane commented on src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
> +        const btnPosition = getClickedElementLocation(this.state.addPaymentMethodButton);
rename to `buttonPosition`

2022-02-28 21:31 UTC, deetergp requested changes
I don't have anything to add to what @rushatgabhane has requested already. Let's get those changes made and this will be good to go! 👍

2022-03-01 15:57 UTC, phivh commented on src/components/KYCWall/BaseKYCWall.js
> +            transferBalanceButton: null,
The position of the menu belongs to position of the button that user clicking on. Thus, when use listener we need to re-assign this button when any click event happens, the possible way to re-assign any variables to the listener in this case needs to use state.

2022-03-01 16:03 UTC, phivh commented on src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js
> +            addPaymentMethodButton: null,
I've explained the reason for the comment below.

2022-03-01 16:06 UTC, phivh commented
@rushatgabhane @deetergp updated.
There are not many changes from the previous PR, the only things that only update window listener to Dimension of RN.

2022-03-02 01:08 UTC, rushatgabhane approved these changes
@deetergp LGTM! 🎉️

2022-03-02 18:38 UTC, deetergp approved these changes
LGTM

2022-03-02 18:38 UTC, merged

2022-03-02 18:48 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-03-11 01:00 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1965977435) to staging by @deetergp in version: 1.1.42-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-03-15 20:53 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1989053438) to production by @chiragsalian in version: 1.1.42-6 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-07-15 23:50 UTC, marcaaron commented on src/components/KYCWall/BaseKYCWall.js
> +            transferBalanceButton: null,
I know this is old, but I don't understand this explanation and it seems wrong. @rushatgabhane please try to address all comments before approving 🙇‍♂️

2022-07-16 01:03 UTC, rushatgabhane commented on src/components/KYCWall/BaseKYCWall.js
> +            transferBalanceButton: null,
@marcaaron im sorry about it
> please try to address all comments before approving

yess!