Upload image preview placeholder - Follow-up #7569
Expensify/App pull request #7874
Opened 2022-02-23 10:29 UTC by okansahin

### Details

It's a follow-up PR of [7569](https://github.com/Expensify/App/pull/7569) to fixing show placeholder when image upload by drag&drop.

### Fixed Issues

$ https://github.com/Expensify/App/issues/7463

$ https://github.com/Expensify/App/pull/7569

$ https://github.com/Expensify/App/pull/7723

### Tests

- [x] Verify that no errors appear in the JS console

### Tests | QA Steps

1. Open a chat window
2. Click (+ button / add attachment / choose from gallery)
3. Select an image
4. Click Send button in preview modal

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

##### Safari

https://user-images.githubusercontent.com/1966034/155301225-20e4774a-4152-4799-ae47-79af6c29f137.mov

##### Chrome

https://user-images.githubusercontent.com/1966034/155301249-2bc1e662-66dc-490a-a707-70bfcc1673ce.mov

#### Mobile Web

https://user-images.githubusercontent.com/1966034/155301270-2e2c5b70-7fa4-4966-81a4-bff7d532631d.mov

#### Desktop

https://user-images.githubusercontent.com/1966034/155301290-c451b42d-5786-4e66-b309-910fd216f9d0.mov

#### iOS

https://user-images.githubusercontent.com/1966034/155301311-27600604-7d75-40a3-a142-ded600b9c04c.mov

#### Android

https://user-images.githubusercontent.com/1966034/155301580-388f5d64-9535-45a3-a863-c146a9dfa04f.mov

2022-02-23 14:55 UTC, parasharrajat commented
@okansahin Just add the original issue which this PR is concerned with. 
![image](https://user-images.githubusercontent.com/24370807/155344336-4053b742-01eb-4d40-9c40-3824dbac6f13.png)

2022-02-23 15:02 UTC, parasharrajat requested changes

2022-02-23 15:02 UTC, parasharrajat commented on src/libs/actions/Report.js
> +    let attachmentInfo = {};
Just add source to the file object 
https://github.com/Expensify/App/blob/853db572e36748541ec6c809d12a3ff2b61be8b5/src/components/AttachmentModal.js#L115

``` _.extend(file, {source: this.state.sourceURL});```

2022-02-24 18:25 UTC, parasharrajat commented on src/libs/actions/Report.js
> +            attachmentInfo: file,
```suggestion
            attachmentInfo: file,
```

Please revert this.

2022-02-24 18:27 UTC, parasharrajat requested changes

2022-02-24 18:27 UTC, parasharrajat commented on src/libs/actions/Report.js
> -    const attachmentInfo = isAttachment ? file : {};
Revert this change.

2022-02-24 18:28 UTC, parasharrajat requested changes
Please add proper QA steps. Another set for drag and drop feature.

2022-02-24 18:53 UTC, okansahin commented
> Please add proper QA steps. Another set for drag and drop feature.

https://user-images.githubusercontent.com/1966034/155588680-67f3a00c-35c7-4786-bf3e-dcb2e7112f18.mov

2022-02-24 19:14 UTC, parasharrajat commented
Thanks for the video @okansahin. I meant to add the QA steps for the drag and drop feature as well on the PR desktop under the QA section. 
![image](https://user-images.githubusercontent.com/24370807/155591578-a42c9ebb-ac76-4634-b819-1dc8051ba547.png)

These are meant for the QA team to test the PR. Thanks.

2022-02-26 15:11 UTC, okansahin commented
### Tests | QA Steps
1. Open a chat window
2. Click (+ button / add attachment / choose from gallery)
3. Select an image
4. Click Send button in preview modal

and

1. Open a chat window
2. Drag an image from your computer to chat window
3. Click Send button in preview modal

2022-02-26 15:25 UTC, parasharrajat commented
> on the PR description

2022-02-26 15:29 UTC, okansahin commented
> > on the PR description

sure. done.

2022-02-27 15:37 UTC, parasharrajat approved these changes
LGTM. Tests well. 

@Julesssss 
:ribbon: :eyes: :ribbon:  C+ reviewed

2022-02-28 10:09 UTC, Julesssss approved these changes

2022-02-28 10:19 UTC, Julesssss commented
Tests well for me 👍

2022-02-28 10:19 UTC, merged

2022-02-28 10:29 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-03-01 19:53 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1917958711) to staging by @Julesssss in version: 1.1.41-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|failure ❌

2022-03-02 10:47 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1917958711) to staging by @Julesssss in version: 1.1.41-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|failure ❌

2022-03-04 10:34 UTC, okansahin commented
@Julesssss @JmillsExpensify 
Any news about regression period start?

2022-03-04 11:21 UTC, Julesssss commented
Hi @okansahin, I'll comment in the linked issue.

2022-03-11 00:03 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1965958569) to production by @francoisl in version: 1.1.41-6 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-03-14 02:32 UTC, Stutikuls commented
**Issue1 -**

**Title**- [Medium]: Chrome + Jaws: Screen Reader:  Role is not defined for the 'Send' control.
**Actual** - Role is not defined for the 'Send' control. Screen reader is reading "only send" when focus lands on the control.
**Expected** - Role - 'Button' should define for the 'Send' control and screen reader should read like "Send button".
**WCAG failure** - 4.1.2
**Reproducible in staging?:** - Yes
**Version Number**: - v1.1.42-2
**Platforms** - Desktop (MAC + Voiceover), Web(Chrome + Jaws), Mobile-web(iOS), iOS

**Note** - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/97600950/158092571-cab7623e-0daa-4a13-9f84-6cc33dc05bb9.mp4


**Issue 2 -**

**Title**- [Medium]: MAC : Screen Reader:  Name & Role is not defined for the 'Action (+)' control.
**Actual** - Name & Role is not defined for the 'Action (+)'  control. Screen reader is reading some extra information when focus lands on the Action (+) control.
**Expected** - Name = 'Action/Add (+) & Role - 'Button' should define for the 'Action (+)' control and screen reader should read like "Acton Add button".
**WCAG failure** - 4.1.2
**Reproducible in staging?:** - Yes
**Version Number**: - v1.1.42-2
**Platforms** - Desktop (MAC + Voiceover), Web(Chrome + Jaws)

**Note** - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/97600950/158092897-e7ff4bbd-1a19-4560-a090-e5dc1e190785.mp4

**Issue 3 -**

**Title**- [High]: Mobile - web (Safari + Voiceover) : 'Action (+)' control is not accessible using screen reader.
**Actual** - Action (+)' control is not accessible using screen reader.
**Expected** - Action (+)' control should accessible using screen reader.
**WCAG failure** - 2.1.1
**Reproducible in staging?:** - Yes
**Version Number**: - v1.1.42-2
**Platforms** - Mobile -web(Safari +Voiceover)

**Note** - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/97600950/158094306-2a0604dd-5b65-4b16-bba7-e7a1fd3ae333.mp4


**Issue 4 -**

**Title**- Functional : [Medium]: Chrome : Not able to drag the image using keyboard.
**Actual** - Not able to drag the image using keyboard. Using Mouse will do it but with keyboard not possible.
**Expected** - Some key combinations (like - Shift+ Down arrow key, etc.) should provide to drag the image using keyboard.
**WCAG failure** - Nil 
**Reproducible in staging?:** - Yes
**Version Number**: - v1.1.42-2
**Platforms** - Web (Chrome), Desktop (MAC)

https://user-images.githubusercontent.com/97600950/158094890-5088c386-5728-4840-b5f6-78c693993d1f.mp4