add informative text for visibility settings
Expensify/App pull request #7876
Opened 2022-02-23 14:49 UTC by thesahindia

### Details

Added informative text for visibiilty settings in New Room page
### Fixed Issues

$ https://github.com/Expensify/App/issues/7669

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Click "+"
2. Click "New Room"
3. Check that there is some informative text below the Visibility settings
- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

https://user-images.githubusercontent.com/83179295/155342651-5678bb40-74ae-44c2-926a-d0e58079bf7b.mov

#### Mobile Web

https://user-images.githubusercontent.com/83179295/155342669-e066d867-64fa-4cef-b2dc-4d8003ae44a2.mov

#### Desktop

https://user-images.githubusercontent.com/83179295/155342714-bfe78e5c-1395-486e-908e-b580e90c721f.mov

#### iOS

https://user-images.githubusercontent.com/83179295/155342744-c13191f8-58e0-4275-a651-2bab6e871cac.mov

#### Android

Uploading Screen Recording 2022-02-23 at 8.02.37 PM.mov…

2022-02-23 14:58 UTC, thesahindia commented
I have used the description that we already had as it was also in the mockup. Do we wanna use the description that was given in the issue?

Adding both here -

Given in the issue:-
"Restricted": "Members of your workspace can find this room"
"Private": "Only members explicitly invited can find this room"

Currently we are using:-
       "Restricted": 'People in your workspace are able to find this room using Search',
       "Private":  'Only people invited to this room are able to find it',

2022-02-23 17:34 UTC, puneetlath commented
I prefer the existing ones. @MitchExpensify what do you think?

2022-02-24 00:10 UTC, rushatgabhane commented
> Restricted: People in your workspace can find this room
Private: People invited to this room can find it

Asked for translations on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1645661373276219) just in case we go with this.

2022-02-24 17:27 UTC, iwiznia commented
Hi!
Why are we removing `using Search` from the first one?

Anyway, if we want to make that change, the only thing we would need to change in the spanish translations is to remove ` a través de "Buscar"`. The rest should remain the same, as the meaning did not really change from what it was.

2022-02-24 17:40 UTC, puneetlath commented
I don't think the "using search" part is necessary for the description. It's just about who can find it. They don't need to know the mechanism for finding it.

2022-02-28 05:32 UTC, rushatgabhane requested changes

2022-02-28 16:51 UTC, thesahindia commented on src/pages/workspace/WorkspaceNewRoomPage.js
> +                        <View style={styles.mb2}>
> 1. Let's update the copy

Done.

> 2. Picker alignment seems off. (`styles.w100` might help)

It's the default behaviour I guess as it's same on other places. Attaching a screenshot.
<img width="375" alt="Screenshot 2022-02-28 at 10 16 51 PM" src="https://user-images.githubusercontent.com/83179295/156023703-261d1424-4ef1-45a1-a60e-92a1ad0d74b3.png">

2022-02-28 22:41 UTC, rushatgabhane commented on src/pages/workspace/WorkspaceNewRoomPage.js
> +                        <View style={styles.mb2}>
ohh, that's weird

2022-02-28 22:53 UTC, rushatgabhane approved these changes
@puneetlath LGTM!

2022-03-01 00:07 UTC, puneetlath approved these changes

2022-03-01 00:08 UTC, merged

2022-03-01 00:19 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-03-01 19:53 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1917958711) to staging by @puneetlath in version: 1.1.41-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|failure ❌

2022-03-02 10:46 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1917958711) to staging by @puneetlath in version: 1.1.41-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|failure ❌

2022-03-11 00:03 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1965958569) to production by @francoisl in version: 1.1.41-6 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-03-25 06:37 UTC, Stutikuls commented
**Issue 1 -**

**Title**- [Medium]: Chrome +Talkback: Screen reader : Focus stuck on the 'Visibility' control twice.
**Actual** - Focus lands on the Visibility control twice. first time its reading "Restricted" and 2nd time screen reader is reading "Visibility".
**Expected** - Focus should stay on the control only once and screen reader should read like "Visibility Restricted drop down button collapsed".
**WCAG failure -** 2.4.3
**Reproducible in staging?**: - Yes
**Version Number:** - v1.1.44-3
**Platforms** - Android

https://user-images.githubusercontent.com/97600950/160066638-cdccea30-e806-4d26-ba07-3d58207b9907.mp4


**Issue 2 -**

**Title**- [Medium]: Talkback+ Chrome: Screen reader : Incorrect role and state is defined for the 'Visibility' control.
**Actual** - When focus lands on the Visibility control then screen reader is reading "Restricted" and 2nd time screen reader is reading "Visibility"  and focus lands on the label, value of the control individually.
**Expected** - Role = Drop down, State = Collapsed/expanded, Value = Restricted/private. Focus should land on the control only once and when focus lands on the control then screen reader should read like "Visibility Restricted drop down button collapsed".
**WCAG failure -** 4.1.2
**Reproducible in staging?**: - Yes
**Version Number:** - v1.1.44-3
**Platforms** - Android

https://user-images.githubusercontent.com/97600950/160067552-c2958704-040e-403f-9f4f-9c1782a3354e.mp4

**Issue 3 -**

**Title**- [Medium]: Talkback+ Chrome: Screen reader :'Visibility' control drop down is not accessible using screen reader.
**Actual** -  Visibility control is not accessible using screen reader.
**Expected** - 'Visibility' control drop down should accessible using screen reader.
**WCAG failure -** 2.1.1
**Reproducible in staging?**: - Yes
**Version Number:** - v1.1.44-3
**Platforms** - Android

https://user-images.githubusercontent.com/97600950/160067266-a1f4cedd-875a-405d-ae01-c051cf0c7e69.mp4