Refactor the API and Network libs to remove application logic
Expensify/App pull request #791
Opened 2020-11-13 00:05 UTC by tgolen

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/145178

### Tests
1. Need to do general regression tests on just about all the functionality you can imagine. The best way to test expired authTokens is to sign in, leave the app for 2+ hours without doing anything, come back and try to do something like post a comment. It should work flawlessly without the flow being interrupted. 
1. Be sure to test going offline and reconnecting

2020-11-13 17:42 UTC, cead22 reviewed
LGTM so far, out of curiosity
- Why the change from API.get to expensifyAPI.get?
- Why the change from `addReportComment` to `expensifyAPI.Report.addComment`? I ask because this adds a third and new way of naming these API commands and I feel we should try to standardize on one. Eg, on web we have things like `Report_AddComment`

2020-11-13 18:23 UTC, marcaaron reviewed
Looks great so far! Love the `PusherConnectionManager` idea and feels like there's much stronger separation of concerns now. Have a few initial things but will wait to give a more substantial review.

I agree with @cead22 about the API naming. Personally, I think it would be best if we enforced that all `API` commands matched the commands that we use in `api.php`. It makes the link between these two things more clear which I think can help when you're trying to follow the path a request takes.

You will see `API.Report_AddComment()` and there is no need to see what `command` this uses since the names are the same.

2020-11-17 19:10 UTC, AndrewGable submitted a review, later dismissed
Tests pass on iOS/Android simulators. Big fan of the refactoring 👍

2020-11-18 00:31 UTC, cead22 submitted a review, later dismissed

2020-11-24 23:24 UTC, TomatoToaster submitted a review, later dismissed
It's mostly looking good to me. I had some NAB type comments and I think the comments so far have been addressed.

2020-11-30 01:01 UTC, marcaaron requested changes
Really nice changes!! I think we're almost there? Just a heads up I might have some delay in getting around to actually testing this as my work laptop are dead.

2020-11-30 16:35 UTC, tgolen reviewed
Thanks for the review, Marc! I have addressed everything and updated the branch.

2020-11-30 18:08 UTC, marcaaron submitted a review, later dismissed
Thanks for the changes. Looks really great so I'm going to approve. @TomatoToaster would you be up for helping out with testing this while I get my dev environment back up and running?

2020-12-01 21:27 UTC, TomatoToaster approved these changes
LGTM - I'm testing this locally right now.

2020-12-01 23:06 UTC, cead22 approved these changes

2020-12-01 23:12 UTC, marcaaron approved these changes

2020-12-01 23:17 UTC, merged

2025-04-22 12:04 UTC, Pujan92 commented on src/libs/API.js
> +    ], parameters, commandName);
I think we should handle the thrown error by `requireParameters` here to redirect a user to login page. Issue https://github.com/Expensify/App/issues/58384