fix android first load
Expensify/App pull request #7922
Opened 2022-02-25 19:51 UTC by ahmdshrif

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/7476

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Set phone language to any RTL ( Settings  -> Languages & input -> Languages ) chose Arabic for example 
2. Open the app
3. Login & Browse
4. make sure the UI element is in its normal  position 
5. make sure the  normal text also does not align to right instead of left 
6. got to text input and use English keyboard (RTL language  not supported)
7. make sure text input aligns to left 
8. test on android and ios . and flow all previous steps. 

- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

![Screen Shot 2022-02-07 at 2 22 50 AM](https://user-images.githubusercontent.com/21364901/152708094-adcf11c4-0d59-49a3-a8a3-fa8987a29876.png)

#### Mobile Web

![Screenshot_20220207-211827_Chrome.jpg](https://user-images.githubusercontent.com/21364901/152856683-83521792-81fd-484f-90de-f4d8667c13fa.jpg)

#### Desktop

![Screen Shot 2022-02-07 at 2 30 40 AM](https://user-images.githubusercontent.com/21364901/152708477-21fdccfc-2c65-4fbb-a6dc-18fb7d3f23ba.png)

#### iOS

![Screen Shot 2022-02-07 at 2 02 02 AM](https://user-images.githubusercontent.com/21364901/152707316-6795bb7d-7e94-4b97-b10c-1d527e64a5e1.png)
55b-d8534034caed.png)

https://user-images.githubusercontent.com/21364901/153756257-fa241dcb-c853-473f-bbe9-4d5c2bd2a2c5.mov

#### Android

![Screen Shot 2022-02-07 at 1 45 17 AM](https://user-images.githubusercontent.com/21364901/152706775-65553260-6ef4-4176-8e10-908e80a65524.png)

2022-02-25 20:02 UTC, marcaaron commented
What's the context for this PR? Was there a regression somewhere?

2022-02-25 20:12 UTC, ahmdshrif commented
I find the edge case here when you install the app for the first time app does not read the RTL config from js until you reload it . and will work after that very fine. 

the js config we add before. work fine with us because the app was installed.

2022-02-25 20:13 UTC, marcaaron commented
Got it thanks!

2022-02-26 00:00 UTC, parasharrajat requested changes
Thanks for submitting a PR @ahmdshrif Appreciate it.

2022-02-26 00:00 UTC, parasharrajat commented on ios/NewExpensify/AppDelegate.m
> +  //force app to work lrt
```suggestion
  // Force the app to LTR mode.
```

2022-02-27 16:11 UTC, parasharrajat approved these changes
LGTM. 

cc: @marcaaron 

:ribbon: :eyes: :ribbon:  C+ reviewed

2022-02-28 17:24 UTC, marcaaron approved these changes

2022-02-28 17:25 UTC, merged

2022-02-28 17:34 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-03-01 19:53 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1917958711) to staging by @marcaaron in version: 1.1.41-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|failure ❌

2022-03-02 10:47 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1917958711) to staging by @marcaaron in version: 1.1.41-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|failure ❌

2022-03-07 04:04 UTC, mvtglobally commented
Team is having a bit hard time validating this PR on Desktop/Web as it requires device language change and introducing navigation issues to flip language back as options shift.
We validated mWeb/IOS and Android. It would be great if someone can validate internally Desktop/Web

2022-03-07 08:08 UTC, ahmdshrif commented
HI, @mvtglobally   I will suggest here to change the language for the app and browser **only**  from setting here. 


![Screen Shot 2022-03-07 at 10 05 30 AM](https://user-images.githubusercontent.com/21364901/156991779-7545dbec-3723-465a-a00e-b2b60aa4b3b5.png)

2022-03-08 17:56 UTC, francoisl commented
Hi @mvtglobally, were you able to test with the suggestion just above?

2022-03-11 00:03 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1965958569) to production by @francoisl in version: 1.1.41-6 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅