Fix avatar online status icon always show sync icon
Expensify/App pull request #7977
Opened 2022-03-02 07:43 UTC by K4tsuki

### Details

### Fixed Issues

$ https://github.com/Expensify/App/issues/7730

### Tests

- [x] Verify that no errors appear in the JS console
In web: 
1. Open App
2. Turn off and turn on wifi/internet
3. when sync icon appear and before disappear in avatar online status, close browser tab (shortcut in firefox `ctrl + w`)
4. Open the expensify again
5. Verify online icon doesn't display sync icon, but green / online icon

In Desktop:
1. Open App
2. Turn off and turn on wifi/internet
3. when sync icon appear and before disappear in avatar online status, quit the App by pressing shortcut `Command (⌘)-Q`
4. Open the expensify again in browser
5. Verify online icon doesn't display sync icon, but green / online icon

In Android/IOS: 
1. Open App
2. Turn off and turn on wifi/internet
3. when sync icon appear and before disappear in avatar online status, force close the application (not backgrounding it)
4. Open the expensify application again
5. Verify online icon doesn't display sync icon, but green / online icon

### PR Review Checklist

#### Contributor (PR Author) Checklist
- [x] I made sure to pull `main` before submitting my PR for review
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I clearly indicated the environment tests should be run in (Staging vs Production)
- [x] I wrote testing steps that cover success & fail scenarios (if applicable)
- [x] I ran the tests & they passed on **all platforms**
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified there are no console errors related to changes in this PR
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I added comments when the code was not self explanatory
    - [x] I put all copy / text shown in the product in all `src/languages/*` files (if applicable)
    - [x] I followed proper naming convention for platform-specific files (if applicable)
    - [x] I followed style guidelines (in [`Styling.md`](https://github.com/Expensify/App/blob/main/STYLING.md)) for all style edits I made
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)

#### PR Reviewer Checklist
- [x] I verified the Author pulled `main` before submitting the PR
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the testing environment is mentioned in the test steps
- [x] I verified testing steps cover success & fail scenarios (if applicable)
- [x] I verified tests pass on **all platforms** & I tested again on all platforms
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified there are no console errors related to changes in this PR
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified comments were added when the code was not self explanatory
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
    - [x] I verified proper naming convention for platform-specific files was followed (if applicable)
    - [x] I verified [style guidelines](https://github.com/Expensify/App/blob/main/STYLING.md) were followed
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)

### QA Steps

- [x] Verify that no errors appear in the JS console
In web: 
1. Open App
2. Turn off and turn on wifi/internet
3. when sync icon appear and before disappear in avatar online status, close browser tab (shortcut in firefox `ctrl + w`)
4. Open the expensify again
5. Verify online icon doesn't display sync icon, but green / online icon

In Desktop:
1. Open App
2. Turn off and turn on wifi/internet
3. when sync icon appear and before disappear in avatar online status, quit the App by pressing shortcut `Command (⌘)-Q`
4. Open the expensify again in browser
5. Verify online icon doesn't display sync icon, but green / online icon

In Android: 
1. Open App
2. Turn off and turn on wifi/internet
3. when sync icon appear and before disappear in avatar online status, force close the application (not backgrounding it)
4. Open the expensify application again
5. Verify online icon doesn't display sync icon, but green / online icon

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

#### Web

Before:

https://user-images.githubusercontent.com/1313124/156316877-70bfda9b-39ff-48a7-9357-6eca73d00cce.mp4

After:

https://user-images.githubusercontent.com/1313124/156316902-d8067c52-1029-45bd-85ca-c029c37c8f8c.mp4

#### Mobile Web

https://user-images.githubusercontent.com/1313124/156316917-2ff24bbb-2a70-4acd-8d4a-8652cd670a7c.mp4

#### Desktop

https://user-images.githubusercontent.com/1313124/157999125-58d6fabb-3dbe-48e3-98d2-4b0b05d6741f.mp4

#### iOS

https://user-images.githubusercontent.com/1313124/158012949-c9f26db5-4069-463c-8c5d-08a62848c733.mp4

#### Android

https://user-images.githubusercontent.com/1313124/156313919-15f813c9-42d7-4325-8323-2fac052eb770.mp4

2022-03-02 11:58 UTC, parasharrajat requested changes
Changes look good. but screenshots for all platforms must be added to the PR. I can make an exception for this PR but you will need it for other PRs so I suggest it is a good time to set up Mac.

2022-03-02 11:59 UTC, parasharrajat requested changes
Also, you will have to sign all commits before this PR can be merged.

2022-03-05 23:54 UTC, K4tsuki commented
@parasharrajat  I have sign all commits.

2022-03-06 08:35 UTC, parasharrajat commented
Let's wait for the QA team to mention that on GH first.

2022-03-08 18:40 UTC, parasharrajat requested changes
Code :+1: 

@K4tsuki Please do the following: 
1. Add a video for Desktop. 
2. Then tick the checkboxes on the checklist. 
3. Please add more descriptive QA steps. Mention the platform in the tests. Write down steps that are different on each platform. 

Thanks.

2022-03-12 02:01 UTC, K4tsuki commented
@parasharrajat I have attached desktop video, update QA steps and add ticks on checkbox list.

2022-03-12 02:29 UTC, parasharrajat commented
Sorry, I just saw that iOS is also missing. Please add that as well.

2022-03-12 09:45 UTC, K4tsuki commented
@parasharrajat I have attached IOS video.

2022-03-12 15:04 UTC, parasharrajat approved these changes
LGTM, 

cc: @flodnv 

#### PR Reviewer Checklist
- [x] I verified the PR has a small number of commits behind `main`
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the testing environment is mentioned in the test steps
- [x] I verified testing steps cover success & fail scenarios (if applicable)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors related to changes in this PR
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified comments were added when the code was not self explanatory
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
    - [x] I verified proper naming convention for platform-specific files was followed (if applicable)
    - [x] I verified [style guidelines](https://github.com/Expensify/App/blob/main/STYLING.md) were followed
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components are not impacted by changes in this PR (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified the UI performance was not affected (the performance is the same than `main` branch)
- [x] If a new component is created I verified that a similar component doesn't exist in the codebase

:ribbon: :eyes: :ribbon:  C+ reviewed

2022-03-14 12:30 UTC, flodnv approved these changes

2022-03-14 12:30 UTC, merged

2022-03-15 21:36 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1989064633) to staging by @flodnv in version: 1.1.43-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-03-17 17:56 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1999874717) to production by @roryabraham in version: 1.1.43-2 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅