Remove Invite and Leave button from Default Room Settings
Expensify/App pull request #8024
Opened 2022-03-07 05:30 UTC by sobitneupane

### Details

Remove Invite and Leave button from Default Room Settings
### Fixed Issues

$ https://github.com/Expensify/App/issues/7791

### Tests

1. Open Default Room (#admins and #announce) Settings.
2. Invite and Leave button should be hidden.
3. Open User-Created Room Settings.
4. Invite and Leave button should be visible.

- [x] Verify that no errors appear in the JS console

### PR Review Checklist

#### Contributor (PR Author) Checklist
- [x] I verified the PR has a small number of commits behind `main`
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I clearly indicated the environment tests should be run in (Staging vs Production)
- [x] I wrote testing steps that cover success & fail scenarios (if applicable)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests & veryfy they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors related to changes in this PR
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I added comments when the code was not self explanatory
    - [ ] I put all copy / text shown in the product in all `src/languages/*` files (if applicable)
    - [ ] I followed proper naming convention for platform-specific files (if applicable)
    - [ ] I followed style guidelines (in [`Styling.md`](https://github.com/Expensify/App/blob/main/STYLING.md)) for all style edits I made
    - [ ] I followed the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs))
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I corroborated the UI performance was not affected (the performance is the same than `main` branch)
- [ ] If I created a new component I verified that a similar component doesn't exist in the codebase

#### PR Reviewer Checklist
- [ ] I verified the PR has a small number of commits behind `main`
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the testing environment is mentioned in the test steps
- [ ] I verified testing steps cover success & fail scenarios (if applicable)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors related to changes in this PR
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified comments were added when the code was not self explanatory
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
    - [ ] I verified proper naming convention for platform-specific files was followed (if applicable)
    - [ ] I verified [style guidelines](https://github.com/Expensify/App/blob/main/STYLING.md) were followed
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components are not impacted by changes in this PR (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified the UI performance was not affected (the performance is the same than `main` branch)
- [ ] If a new component is created I verified that a similar component doesn't exist in the codebase

### QA Steps

1. Open Default Room (#admins and #announce) Settings.
2. Invite and Leave button should be hidden.
3. Open User-Created Room Settings.
4. Invite and Leave button should be visible.

- [x] Verify that no errors appear in the JS console

### Screenshots

#### Web

Default Room            |  User-Created Room
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/25876548/156972485-c648134d-20f4-4a49-97c3-182918f365b8.png)  |  ![](https://user-images.githubusercontent.com/25876548/156972503-1ecb34e3-0432-4f2a-8729-5175606dbf36.png)

#### Mobile Web

Default Room            |  User-Created Room
:-------------------------:|:-------------------------:
![Simulator Screen Shot - iPhone 13 - 2022-03-07 at 10 46 04](https://user-images.githubusercontent.com/25876548/156973391-676a7847-4f14-4845-a02c-cbeeadf41bfe.png) | ![Simulator Screen Shot - iPhone 13 - 2022-03-07 at 10 45 44](https://user-images.githubusercontent.com/25876548/156973369-3be0f531-054f-404a-af78-52898d9ffca0.png)

#### Desktop

Default Room            |  User-Created Room
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/25876548/156972821-0f7f7f53-fdcf-4235-9ae9-20909fedfb46.png)  |  ![](https://user-images.githubusercontent.com/25876548/156972839-063cbc1a-a5cf-4831-8cf9-a23fc2357af6.png)

#### iOS

Default Room            |  User-Created Room
:-------------------------:|:-------------------------:
![Simulator Screen Shot - iPhone 13 - 2022-03-07 at 10 45 14](https://user-images.githubusercontent.com/25876548/156973297-12d19c7a-80d3-40a1-b0b3-7991c4c6b041.png) | ![Simulator Screen Shot - iPhone 13 - 2022-03-07 at 10 44 28](https://user-images.githubusercontent.com/25876548/156973287-a047cf15-c42d-4b27-92d5-10281876b565.png)

#### Android

Default Room            |  User-Created Room
:-------------------------:|:-------------------------:
![Screenshot_1646628735](https://user-images.githubusercontent.com/25876548/156973070-47bd9f9e-85e6-416a-a343-ad631ce3368a.png)  |  ![Screenshot_1646628716](https://user-images.githubusercontent.com/25876548/156973064-de9eeec9-0773-4e16-bcfa-95e1bc915581.png)

2022-03-07 08:16 UTC, parasharrajat requested changes

2022-03-07 08:16 UTC, parasharrajat commented on src/pages/ReportDetailsPage.js
>          if (ReportUtils.isChatRoom(this.props.report)) {
Let's use early return here.  If not chatroom return.

2022-03-07 08:16 UTC, parasharrajat commented on src/pages/ReportDetailsPage.js
> +            if (!ReportUtils.isDefaultRoom(this.props.report)) {
Same for here. If default room return.

2022-03-09 17:16 UTC, parasharrajat approved these changes
LGTM. 

cc: @chiragsalian 

#### PR Reviewer Checklist
- [x] I verified the Author pulled `main` before submitting the PR
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the testing environment is mentioned in the test steps
- [x] I verified testing steps cover success & fail scenarios (if applicable)
- [x] I verified tests pass on **all platforms** & I tested again on all platforms
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified there are no console errors related to changes in this PR
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified comments were added when the code was not self explanatory
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
    - [x] I verified proper naming convention for platform-specific files was followed (if applicable)
    - [x] I verified [style guidelines](https://github.com/Expensify/App/blob/main/STYLING.md) were followed
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)

:ribbon: :eyes: :ribbon:  C+ reviewed

2022-03-10 18:58 UTC, chiragsalian approved these changes
LGTM

2022-03-10 18:58 UTC, merged

2022-03-10 19:08 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-03-11 00:59 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1965977435) to staging by @chiragsalian in version: 1.1.42-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-03-15 20:51 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/1989053438) to production by @chiragsalian in version: 1.1.42-6 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅