[WIP] Handle Wallet Onfido flow
Expensify/App pull request #8093
Opened 2022-03-11 14:39 UTC by nkuoch

### Details

### Fixed Issues

$ GH_LINK

### Tests

- [ ] Verify that no errors appear in the JS console

### PR Review Checklist

#### Contributor (PR Author) Checklist
- [ ] I verified the PR has a small number of commits behind `main`
- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I clearly indicated the environment tests should be run in (Staging vs Production)
- [ ] I wrote testing steps that cover success & fail scenarios (if applicable)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests & veryfy they passed on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors related to changes in this PR
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I added comments when the code was not self explanatory
    - [ ] I put all copy / text shown in the product in all `src/languages/*` files (if applicable)
    - [ ] I followed proper naming convention for platform-specific files (if applicable)
    - [ ] I followed style guidelines (in [`Styling.md`](https://github.com/Expensify/App/blob/main/STYLING.md)) for all style edits I made
    - [ ] I followed the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs))
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I corroborated the UI performance was not affected (the performance is the same than `main` branch)
- [ ] If I created a new component I verified that a similar component doesn't exist in the codebase

#### PR Reviewer Checklist
- [ ] I verified the PR has a small number of commits behind `main`
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the testing environment is mentioned in the test steps
- [ ] I verified testing steps cover success & fail scenarios (if applicable)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors related to changes in this PR
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified comments were added when the code was not self explanatory
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
    - [ ] I verified proper naming convention for platform-specific files was followed (if applicable)
    - [ ] I verified [style guidelines](https://github.com/Expensify/App/blob/main/STYLING.md) were followed
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components are not impacted by changes in this PR (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified the UI performance was not affected (the performance is the same than `main` branch)
- [ ] If a new component is created I verified that a similar component doesn't exist in the codebase

### QA Steps

- [ ] Verify that no errors appear in the JS console

### Screenshots

#### Web

#### Mobile Web

#### Desktop

#### iOS

#### Android

2022-03-21 10:04 UTC, nkuoch commented
Friendly Bump @marcaaron @ctkochan22 and @francoisl for review

2022-03-21 21:08 UTC, marcaaron requested changes

2022-03-21 21:08 UTC, marcaaron commented on src/pages/EnablePayments/AdditionalDetailsStep.js
> -            key: ONYXKEYS.WALLET_ADDITIONAL_DETAILS_DRAFT,
Looks like we are removing this subscription, but still referencing it in the code.

2022-03-21 21:08 UTC, marcaaron commented on src/pages/EnablePayments/EnablePaymentsPage.js
> +        if (this.props.userWallet.currentStep === CONST.WALLET.STEP.ONFIDO) {
Could we do this in the `OnfidoStep` instead of `EnablePaymentsPage`?

2022-03-21 21:08 UTC, marcaaron commented on src/pages/EnablePayments/EnablePaymentsPage.js
> +                this.currentStep = CONST.WALLET.STEP.ADDITIONAL_DETAILS;
`this.currentStep` seems unused

2022-03-21 21:08 UTC, marcaaron commented on src/pages/EnablePayments/AdditionalDetailsStep.js
> -            key: ONYXKEYS.WALLET_ADDITIONAL_DETAILS_DRAFT,
Oh nevermind I see you are moving it to props now. Both work fine :D

2022-03-22 08:53 UTC, nkuoch commented on src/libs/actions/Wallet.js
> +                    if (response.title === CONST.WALLET.ERROR.ONFIDO_FIXABLE_ERROR) {
It's the pattern we've been using everywhere else in this method. I agree with you, although I'm not a fan of using the uuid either.
I think the proper way would be either via another type of exception php (extending from ExpError), or via a key `errorType` in data? (Either way, let's do it in a follow up PR, so I can do it for all the other places too).

2022-03-22 20:14 UTC, marcaaron commented on src/libs/actions/Wallet.js
> +                    if (response.title === CONST.WALLET.ERROR.ONFIDO_FIXABLE_ERROR) {
Would be good to try to start a wider conversation about this and propose a holistic fix. There's a lot of inconsistency in the new app in general WRT error handling - in many places we look at `jsonCode` in others the `response.message` etc.

2022-03-22 20:18 UTC, marcaaron approved these changes

2022-03-22 21:19 UTC, francoisl approved these changes

2022-03-22 21:56 UTC, merged

2022-03-22 22:06 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-03-24 21:00 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2036324386) to staging by @nkuoch in version: 1.1.46-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-03-30 19:27 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2066850138) to production by @timszot in version: 1.1.46-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2022-04-13 14:06 UTC, ogumen commented
Hi @nkuoch, could you please let us know if there is an easy way to get to this screen in order to test it from the accessibility perspective? Can we use any testing account to get to it? Thanks!
CC @SumitDiyora @Stutikuls