Build Desktop for x64 and arm64 only
Expensify/App pull request #8160
Opened 2022-03-15 16:44 UTC by kidroca

cc @roryabraham 

### Details

- Build desktop for 2 mac architectures: x64 and arm64
- Use different artifact (file) names for each output so it does not mess up hosting

### Fixed Issues

$ https://github.com/Expensify/App/issues/8004

### Tests

- [ ] Verify you can still build the Desktop App (`npm run desktop-build-staging`)
- [ ] Verify you can still run the Desktop App locally (`npm run desktop`)

### PR Review Checklist

#### Contributor (PR Author) Checklist
- [x] I verified the PR has a small number of commits behind `main`
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I clearly indicated the environment tests should be run in (Staging vs Production)
- [x] I wrote testing steps that cover success & fail scenarios (if applicable)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests & verified they passed on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [x] I verified there are no console errors related to changes in this PR
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I added comments when the code was not self explanatory
    - [ ] I put all copy / text shown in the product in all `src/languages/*` files (if applicable)
    - [ ] I followed proper naming convention for platform-specific files (if applicable)
    - [ ] I followed style guidelines (in [`Styling.md`](https://github.com/Expensify/App/blob/main/STYLING.md)) for all style edits I made
    - [ ] I followed the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs))
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I corroborated the UI performance was not affected (the performance is the same than `main` branch)
- [ ] If I created a new component I verified that a similar component doesn't exist in the codebase

#### PR Reviewer Checklist
- [ ] I verified the PR has a small number of commits behind `main`
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the testing environment is mentioned in the test steps
- [ ] I verified testing steps cover success & fail scenarios (if applicable)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors related to changes in this PR
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified comments were added when the code was not self explanatory
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
    - [ ] I verified proper naming convention for platform-specific files was followed (if applicable)
    - [ ] I verified [style guidelines](https://github.com/Expensify/App/blob/main/STYLING.md) were followed
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components are not impacted by changes in this PR (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified the UI performance was not affected (the performance is the same than `main` branch)
- [ ] If a new component is created I verified that a similar component doesn't exist in the codebase

### QA Steps

- [ ] Verify you can download the version x64 version from `/NewExpensify.dmg`
- [ ] Verify you can download the version arm64 version from `/NewExpensify-arm64.dmg`

### Screenshots

#### Web

#### Mobile Web

#### Desktop

![Screenshot 2022-03-15 at 18 32 29](https://user-images.githubusercontent.com/12156624/158428179-63db012f-45fe-422b-9aa2-c60811a3338c.png)

##### Build directory content
![Screenshot 2022-03-15 at 18 31 40](https://user-images.githubusercontent.com/12156624/158428202-77fcc5fa-146c-4d47-95db-bdba9f63f8d1.png)

#### iOS

#### Android

2022-03-15 17:18 UTC, roryabraham requested changes

2022-03-15 17:18 UTC, roryabraham commented on scripts/build-desktop.sh
> +"$LOCAL_PACKAGES/electron-builder" --config config/electronBuilder.config.js --x64 "$@"
Can we refactor this to run both builds in parallel in the background? I did something similar with the `.github/scripts/buildActions.sh` that you could use as a reference if needed.

2022-03-16 16:37 UTC, roryabraham commented on scripts/build-desktop.sh
> +"$LOCAL_PACKAGES/electron-builder" --config config/electronBuilder.config.js --x64 "$@"
Okay, thanks for looking into it.

2022-03-22 07:50 UTC, roryabraham approved these changes

2022-03-22 07:50 UTC, merged

2022-03-22 08:01 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-03-24 21:01 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2036324386) to staging by @roryabraham in version: 1.1.46-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-03-28 13:24 UTC, mvtglobally commented
@roryabraham  We validated Desktop - Mac x64 version, it is pass, but unfortunately, we dont have Mac arm64 version to QA. Can maybe someone check internally?

2022-03-28 16:55 UTC, johnmlee101 commented
Downloaded and it opened just fine 👍

2022-03-28 17:00 UTC, Santhosh-Sellavel commented
Working fine for me too!
<img width="530" alt="Screenshot 2022-03-28 at 10 29 55 PM" src="https://user-images.githubusercontent.com/85645967/160449598-bff3ecce-fe22-4681-b0d7-bea3bf69dae8.png">

2022-03-30 19:27 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2066850138) to production by @timszot in version: 1.1.46-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅