Notifications redirection fix
Expensify/App pull request #840
Opened 2020-11-24 15:41 UTC by sketchydroide

When a mobile notification from User A is clicked, Chat isn't opening to the chat with User A

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/144636

### Tests (iOS and/or Android)
- You need to run this in your personal device, this [SO](https://stackoverflow.com/c/expensify/questions/6735) helps.
- You also need 3 users for this test, one to test on the device User1, another to be UserA and another to be UserB. I just added the other 2 users to User1 policy.

1. run the app on your device and login with User1, accept notifications.
1. run the app on chrome, and login with UserA
1. run the app on firefox or safary and login with UserB
1. Send a message to User1 from UserA, verify that it arrives and you get a push, and when you tap it you go to that conversation.
1. Send a message to User1 from UserB, verify that it arrives and you get a push, and when you tap it you go to that conversation.
1. Kill the app and restart it, verify that you don't have to login again.
1. Send a message to User1 from UserA, verify that it arrives and you get a push, and when you tap it you go to that conversation.
1. Send a message to User1 from UserB, verify that it arrives and you get a push, and when you tap it you go to that conversation.
1. Put the app into background.
1. Send a message to User1 from UserA, verify that it arrives and you get a push. Verify that when you tap it the app comes into the foreground and you are directed to the conversation with UserA.

2020-11-24 18:58 UTC, roryabraham requested changes
Code change looks fine but I'm not sure about the code signing changes to the xcode project.

2020-11-30 17:34 UTC, TomatoToaster submitted a review, later dismissed

2020-11-30 18:24 UTC, roryabraham reviewed
I'm fine with moving the registration to `componentDidUpdate`, but is there any reason to not just do it in `componentDidMount`?

And if you are going to leave in `componentDidUpdate`, then NAB maybe we should do something like this instead:

```javascript
componentDidUpdate(prevProps, prevState) {
    if (this.state.accountID && this.state.accountID !== prevState.accountID) {
        PushNotifications.register(this.state.accountID);
    }
}
```

Then (optionally) remove the double-registration check from `PushNotification.register`. The reason I suggest that is because in `Expensify` there's just more context about why we would be double-registering.

2020-11-30 19:24 UTC, roryabraham approved these changes
Nice, LGTM 👍

2020-11-30 19:24 UTC, merged