Create a local proxy server + npm script
Expensify/App pull request #868
Opened 2020-12-02 00:07 UTC by marcaaron

Adds a local proxy server to get around cors issues + some webpack configs

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/146052

### Tests
1. First verify you can run `npm run web` without any issues
1. Copy the `.env.production` variables into `.env`
1. Set `EXPENSIFY_URL_COM` to be empty like so
```
EXPENSIFY_URL_COM=
EXPENSIFY_URL_CASH=https://www.chat.expensify.com/
```
4. `npm i`
5. `npm run proxy`
6. Verify you can sign in with your production user name
7. Verify Pusher is working
8. Verify you can leave a comment
9. Verify you can view images in chats
10. Verify you can upload images and files to chats

### Screenshots
<Add any necessary screenshots for all platforms if your change added or updated UI>

2020-12-03 14:45 UTC, sketchydroide submitted a review, later dismissed
LGTM

2020-12-03 21:48 UTC, tgolen requested changes
Looks pretty good. I think the proxy looks a _bit_ complex, so I will help think if there are any ways to simplify it further. It seems like if Node is accepting a network request from the front-end, it shouldn't be necessary to do anything to the request data in order to pass it in another request to the production API, so I'm a bit curious about why all the form parsing is there. I haven't actually tried this, so I'm more just exploring the code than anything.

I guess I'm thinking something like [this](https://nodejs.org/en/knowledge/advanced/streams/how-to-use-stream-pipe/) where the first response (a readable stream) is piped to the second request (a writeable stream), and that response (another readable stream) is piped back to the initial request's response (another writeable stream).

Request from App -> piped to Request to API -> piped to response back to App

I hope that makes sense. 

It also could be that using a better third-party lib could really clean this up. I was looking at https://github.com/http-party/node-http-proxy and it seems like it would make the implementation very simple:

```
httpProxy.createProxyServer({target:'https://www.expensify.com'}).listen(9000);
```

One last thing that's missing from this PR are some instructions in the README.

2020-12-04 03:17 UTC, tgolen approved these changes

2020-12-07 12:02 UTC, sketchydroide approved these changes
stil LGTM

2020-12-07 16:20 UTC, merged