remove hyphens, brackets from phone number
Expensify/App pull request #8845
Opened 2022-05-01 20:35 UTC by thesahindia

### Details

At phone number field on company step and additional details page we couldn't add hyphens, brackets and +1 this PR deals with that. We are stripping hyphens, brackets and +1 from the phone number.

### Fixed Issues

$ https://github.com/Expensify/App/issues/7007

### Tests | QA Steps

Note: You will need to test it on Desktop and Native

Routing no. 011401533
Account no. 1111222233331111

1. Navigate to workspace > Connect bank Account > Connect manually > Fill the details give above and save
2. Enter phone number in the company phone field with different formats (e.g with/without parentheses/dashes)
3. Verify you don't get any error related to phone number

---

1. Click on Fab icon > send money > onfido verification > Additional details page
3. Enter phone number in Phone number field with different formats (e.g with/without parentheses/dashes)
4. Verify you don't get any error related to phone number

- [x] Verify that no errors appear in the JS console

### PR Review Checklist

#### Contributor (PR Author) Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

<details>
<summary><h4>PR Reviewer Checklist</h4></summary>

- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and  [...]

2022-05-03 15:27 UTC, parasharrajat requested changes
The code is looking fine. Please add detailed QA steps to cover each change in this PR.

2022-05-04 14:18 UTC, thesahindia commented
> The code is looking fine. Please add detailed QA steps to cover each change in this PR.

Done ✅

2022-05-05 12:22 UTC, parasharrajat approved these changes, later dismissed
LGTM. 

cc: @marcaaron 

:ribbon: :eyes: :ribbon:  C+ reviewed

2022-05-06 21:13 UTC, neil-marcellini commented
👀 reviewing now

2022-05-06 22:41 UTC, neil-marcellini requested changes
All good to go except for 1 confusing comment. Then I will approve!

2022-05-06 22:41 UTC, neil-marcellini commented on src/libs/ValidationUtils.js
> +    // Remove alphanumeric characters from phone number
```suggestion
    // Remove non alphanumeric characters from phone number
```

2022-05-08 09:56 UTC, thesahindia commented on src/pages/EnablePayments/AdditionalDetailsStep.js
>                                      errorText={this.getErrorText('phoneNumber')}
Ahh I forgot to mention this, currently we are showing `xyz is a required field` for all the fields
Like here the error message should say `Please enter valid last 4 digits of SSN`
<img width="374" alt="Screenshot 2022-05-08 at 3 21 56 PM" src="https://user-images.githubusercontent.com/83179295/167290916-41048881-32b9-4d94-93ca-47a5a35ac186.png">

I think we should open a new issue for this as we will need to add specific error messages for all the fields like we do at [CompanyStep.js](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/CompanyStep.js)


Here's what we are doing right now -
https://github.com/Expensify/App/blob/724ccb46ca4b2f48f6052592cbacc7ffe9528c5c/src/pages/EnablePayments/AdditionalDetailsStep.js#L143

2022-05-09 15:28 UTC, neil-marcellini commented on src/pages/EnablePayments/AdditionalDetailsStep.js
>                                      errorText={this.getErrorText('phoneNumber')}
Yes please go ahead and open a new issue for that. Thanks!

2022-05-09 15:28 UTC, neil-marcellini approved these changes
Good to go!

2022-05-09 15:29 UTC, merged

2022-05-09 15:40 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-05-09 16:12 UTC, thesahindia commented on src/pages/EnablePayments/AdditionalDetailsStep.js
>                                      errorText={this.getErrorText('phoneNumber')}
@neil-marcellini, just for the clarification, I should report it on slack right? or can I just open the issue on github directly?

2022-05-09 16:14 UTC, parasharrajat commented on src/pages/EnablePayments/AdditionalDetailsStep.js
>                                      errorText={this.getErrorText('phoneNumber')}
Slack..it.

2022-05-09 16:15 UTC, neil-marcellini commented on src/pages/EnablePayments/AdditionalDetailsStep.js
>                                      errorText={this.getErrorText('phoneNumber')}
Please report it on Slack following the pinned template.

2022-05-13 22:04 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2320539573) to staging by @neil-marcellini in version: 1.1.58-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2022-05-16 17:06 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2333359574) to production by @AndrewGable in version: 1.1.60-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅