Revert "Open old dot links with openOldDotLink() function"
Expensify/App pull request #8952
Opened 2022-05-11 21:12 UTC by thienlnam

Reverts Expensify/App#8769 to fix https://github.com/Expensify/App/issues/8943

2022-05-12 16:33 UTC, joelbettner requested changes
@thienlnam Can you put some QA steps in for this?

2022-05-12 22:38 UTC, joelbettner approved these changes

2022-05-12 22:39 UTC, merged

2022-05-12 22:40 UTC, joelbettner commented
@thienlnam ping me if you want me to CP this to staging for ya. I think today we are in a DBS mode because of the earnings call and wanting everything to remain stable.

2022-05-12 23:07 UTC, thienlnam commented
@joelbettner I thought PRs with the CP Staging label automatically got deployed to staging in App / Did we change this for the earnings call?

2022-05-13 22:03 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2320539573) to staging by @joelbettner in version: 1.1.58-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅

2022-05-16 17:05 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2333359574) to production by @AndrewGable in version: 1.1.60-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅