Use same logic without link regression
Expensify/App pull request #8980
Opened 2022-05-12 23:36 UTC by mateusbra

### Details

We are going to use the `openOldDotLink()` function when we have oldDot links, it will open the oldDot link with our account logged in.
### Fixed Issues

$ https://github.com/Expensify/App/issues/7909
$ https://github.com/Expensify/App/issues/8943

### Tests

1. Launch the app
2. Open the report with Concierge
3. Click on any link Concierge sends to you.

Old dot links:
4. It should open an old dot URL with the user logged in.

New dot links:
4. If link is a new dot link it should navigate to a screen within the app.

Other links:
4. Whatever other link(not new dot nor old dot) should open in a new tab.

- As we store attachments within `expensify.com` URL testers should also test attachments:
1. Launch the app
2. Open the report with Concierge
3. Send a video attachment
4. Verify it works like an attachment e.g.:
5. 
![image](https://user-images.githubusercontent.com/56851391/168184016-978cda9a-9a25-435b-a213-bb4eab45147d.png)

### PR Review Checklist

#### Contributor (PR Author) Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

<details>
<summary><h4>PR Reviewer Checklist</h4></summary>

- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained “why” the code was  [...]

2022-05-18 18:48 UTC, rushatgabhane reviewed
@mateusbra please change the title of PR to something like 'Open old dot link with openOldDotLink()'

In tests, the video doesn't need to be sent to Concierge. It can be sent to any user.
1. Launch the app
2. Open the report with Concierge <----- this
3. Send a video attachment

2022-05-18 18:48 UTC, rushatgabhane commented on src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
> +    // If we are handling an old dot Expensify link we need to open it with openOldDotLink() so we can navigate to it with the user already logged in.
please update the comment to mention about attachment

2022-05-20 15:39 UTC, rushatgabhane commented on src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js
> +    // As we store attachments under expensify.com URL we don't want it working the same as links.
@mateusbra gonna be nitpicky here

```suggestion
    // As attachments also use expensify.com we don't want it working the same as links.
```

2022-05-22 23:58 UTC, rushatgabhane requested changes
@mateusbra a few issues

Actual: Clicking the download for a video on web opens it in a new tab. 
Expected: Video starts downloading immediately.

Actual: On mWeb, clicking download does nothing.

https://user-images.githubusercontent.com/29673073/169721657-8cf129d8-6ba7-45f0-81c9-baff3a53ae37.mp4

2022-05-23 01:26 UTC, mateusbra commented
@rushatgabhane I noticed this happenned, I think its a regression from another PR,  it was also reproducible running main on dev, could you confirm that for me?

2022-05-23 09:07 UTC, rushatgabhane commented
> I noticed this happenned, I think its a regression from another PR

@mateusbra please report the bug on slack if you haven't already.
<hr />

This bug isn't present on `main`
1. Send a video
2. Right click to open context menu
3. Download

Expected: video downloads
Actual: nothing happens

https://user-images.githubusercontent.com/29673073/169784440-c20c6abd-6a2a-4cb6-ae4e-aeb8813cf8a5.mov

2022-05-23 15:32 UTC, mateusbra commented
I wasn't able to reproduce this bug from my side.
This video shows what happens to me running `openOldDotLinksRegression` after merging main(didn't tested this specific bug before merging it), I think its working fine, am I missing something?

https://user-images.githubusercontent.com/56851391/169854283-921408fb-55f5-4447-b298-0a32054a8c8e.mp4

2022-05-23 21:39 UTC, rushatgabhane approved these changes
@iwiznia LGTM! 

<details>
<summary><h4> #### PR Reviewer Checklist</h4></summary>

- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

</details>

2022-05-23 21:43 UTC, rushatgabhane commented
> I wasn't able to reproduce this bug from my side.

@mateusbra yeah you're right. I can't replicate that bug after you've merged with `main`.
Also, thanks for logging the regression on slack :)

2022-05-23 21:54 UTC, rushatgabhane commented
@mateusbra could you please reformat the tests and QA steps to something like this? I think this is more easier to read.

#### Test 1 - old dot links
1. Launch the app.
2. Open the report with Concierge.
3. Click on any link Concierge sends to you.
4. Verify It should open an old dot URL with the user logged in.

#### Test 2- new dot links
1. Open any report
2. Send this link - https://new.expensify.com/statements/123
4. Verify that clicking on the link navigates the app to a screen within the app ().


#### Test 3 - Attachments
1. Open any report.
2. Send a video, photo and pdf attachment.
3. Verify that there are no regressions related to viewing, sending, downloading etc.

#### Test 3 - Other links
1. Open any report.
2. Send a link eg: http://google.com
4. The link should open in a new tab.

2022-05-24 01:11 UTC, mateusbra commented
tests updated!

2022-05-24 15:46 UTC, iwiznia approved these changes

2022-05-24 15:46 UTC, merged

2022-05-24 15:57 UTC, OSBotify commented
:hand: This PR was not deployed to staging yet because QA is ongoing. It will be automatically deployed to staging after the next production release.

2022-05-24 19:16 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2379256573) to staging by @iwiznia in version: 1.1.66-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-05-25 20:53 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2386992591) to production by @chiragsalian in version: 1.1.66-1 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|success ✅

2022-05-26 01:18 UTC, mateusbra commented
I don't think its a regression, we only changed how `old dot` links works in the PR.

2022-05-26 10:53 UTC, iwiznia commented
The timeline also doesn't line up, the [issue](https://github.com/Expensify/App/issues/9158) was opened 2 days ago and says it was reproducible in production, this PR was not in production 2 days ago

2022-05-26 10:58 UTC, rushatgabhane commented
> the https://github.com/Expensify/App/issues/9158 was opened 2 days ago and says it was reproducible in production

@iwiznia I think that's a mistake or some misunderstanding

Because J. Nam can repro the issue on staging, but _not_ on production - https://github.com/Expensify/App/issues/9158#issuecomment-1137650295

2022-05-26 11:03 UTC, iwiznia commented
Oh... if that's the case, then it is probable this was the cause. @mateusbra can you check it out? Should be easy to test, replicate the bug on main, then try to replicate it with this PR reverted.

2022-05-26 11:11 UTC, rushatgabhane commented
@iwiznia our emails (eg: rushatgabhane@gmail.com) don't have access to `wallets` so we always see a white screen. So we can't really test the bug.

2022-05-26 11:17 UTC, iwiznia commented
Oh... I don't have access either 😢 
Do you need to actually have a wallet set up or just have access to the feature? Because if it's the latter, I can give you temporary access, if it is the former I probably can't because only people with an SSN from USA can enable the feature.

2022-05-26 11:20 UTC, rushatgabhane commented
@iwiznia I have no idea about wallets 😅
@thienlnam can you help us out with https://github.com/Expensify/App/pull/8980#issuecomment-1138424543

2022-05-26 15:22 UTC, mateusbra commented
I couldn't reproduce the bug neither on `main` or `this PR reverted` on prod. It navigates me to this blank screen(it doesn't open new tab on browser):
![image](https://user-images.githubusercontent.com/56851391/170519450-e80bd924-2be7-4f1f-8aec-6083b6eb2446.png)

2022-05-26 17:05 UTC, thienlnam commented
> I don't think its a regression, we only changed how old dot links works in the PR.

The statements page is an OldDot link btw.

Yeah I've tested this on production again, and haven't run into problems so I think this was just a configuration issue on staging that cause it not to work.  

Doesn't seem like there is a regression here

<img width="381" alt="Screen Shot 2022-05-26 at 10 03 46 AM" src="https://user-images.githubusercontent.com/30609178/170538341-00b136dd-60b6-453e-bc2c-30fecc39a5de.png">

2022-05-27 21:11 UTC, rushatgabhane commented
> Doesn't seem like there is a regression here

Thanks a lot for confirming!