Create interface detection library
Expensify/App pull request #903
Opened 2020-12-08 16:47 UTC by roryabraham

Coming from [this slack thread](https://expensify.slack.com/archives/C03TQ48KC/p1607393233000700). I got to thinking about scenarios where we can improve the UX by offering a more tailored experience for different interface types.

For now, we assume all native applications are going to be running on touch-only devices. However, with the web application it is completely feasible that the interface can be one of three types:

1) A mouse-only web interface, such as on a regular macBook
2) A touch-only web interface, such as on a regular iPhone's web browser
3) A hybrid interface, such as on a Microsoft Surface laptop w/ a mouse AND a touchscreen (these are increasingly common).

### Fixed Issues
No particular issue, but it came from https://github.com/Expensify/ReactNativeChat/pull/902 - where I was thinking we could use this kind of paradigm:

- On mouse-only interfaces, listen for right-click but not longPress
- On touch-only interfaces, listen for longPress but not right-click
- On hybrid interfaces, listen for both

### Tests
1) Import the library into the `Expensify` component.
2) Add this code into `componentDidMount`:

    ```javascript
    console.log(InterfaceTypes.getInterfaceType());
    ```
3) Run `npm run web`
4) In another terminal, run `ngrok http --host-header rewrite localhost:8080`
5) Go to `localhost:8080` in the web browser on your mac - see that the console logs `mouseOnly`
6) Go to the ngrok url in the web browser on your phone - see that the console logs `touchOnly`
7) Go to the ngrok url in the web browser an iPad - see that the console logs `hybrid` (because you can connect an Apple magic mouse to an iPad)

Of course, there are many other devices out there, but these were the devices I had on-hand to test with.

2020-12-08 18:07 UTC, alex-mechler requested changes

2020-12-08 19:12 UTC, alex-mechler submitted a review, later dismissed

2020-12-08 21:23 UTC, alex-mechler approved these changes

2020-12-09 04:21 UTC, marcaaron requested changes
I like the idea of adding some kind of feature detection for platforms that might be able to both use a mouse and touch. But I'm wondering if this might be clearer as an API that describes a client's capability instead of what they can "only do". 

e.g. something like 

```js
import {canTouch, canMouse} from './clientCapabilities'

if (canTouch() && canMouse()) {
    // do hybrid stuff
}
```

Would also be great to see an example of how this will be used.

2020-12-11 01:31 UTC, closed without merging