[HOLD] Submit or close modal based on keyboard events
Expensify/App pull request #939
Opened 2020-12-12 05:03 UTC by roryabraham

There is a bug in this as-is where after the file input is closed the button that was last clicked (the paperclip) has the focus instead of the modal. I tried focusing the modal element but I'm not sure it is focusable. Not sure what the workaround here should be.

**NOTE:** This PR is held on [this one](https://github.com/Expensify/react-native-onyx/pull/24), because `withOnyx` needs to forward refs for this to work.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/148091#event-4101474960

### Tests

#### Web/Desktop
1) Open a chat.
2) Type a text message, hit `Return` to send it. Make sure that it sends.
3) Click on the paperclip to upload an attachment.
4) Choose an attachment, and hit enter or use the button to confirm your selection.
5) Immediately hit `Escape`, and verify that the modal is closed and the attachment is _not_ uploaded.
6) Repeat steps 3 and 4
7) Hit `Return` and make sure the attachment is uploaded and sent.

#### iOS/Android/mWeb
1) Open a chat.
2) Type a text message and send it. Make sure that it sends.
3) Tap the paperclip to upload an attachment.
4) Choose an attachment and send it. Make sure that it sends.

### Tested on:
- [x] Web
- [x] Desktop
- [x] iOS
- [x] Android
- [x] mWeb

2020-12-14 18:18 UTC, marcaaron requested changes

2020-12-14 20:21 UTC, tgolen reviewed
I spoke with Marc about this, but I think there are some good ideas to refactor how the modals work which will make what's being done in this PR easier and more simple to implement. I'll pause on reviewing this for now.

2021-01-05 02:50 UTC, marcaaron commented
Is this PR still happening? I think I saw some contributors working on the close modals with escape key so just wondering what the status is here?

2021-01-05 03:12 UTC, thienlnam commented
IIRC this was paused for the modal refactor but then ended up getting contracted out https://github.com/Expensify/Expensify/issues/148091#issuecomment-754128464

2021-01-05 16:32 UTC, tgolen commented
I'd love for us to keep marching forward with this one and getting the refactoring done. It's only going to hurt us the longer we go with the current modal framework.

2021-01-05 19:02 UTC, marcaaron commented
>It's only going to hurt us the longer we go with the current modal framework

Not sure what is meant by this if you can clarify @tgolen. We refactored the modals and the framework is in a pretty nice spot. There are some contractors working on closing all modals via the escape key, but none working on a submit action via the Enter key from what I've seen/heard.

2021-01-05 19:12 UTC, roryabraham commented
Yeah, I could easily have redone this (having already gotten to a working solution prior to the refactor), but then the issue was sort of flagged as "low hanging fruit" and posted on Upwork while I was ooo for the holidays, so I abandoned this PR. Closing it out now.

2021-01-05 19:12 UTC, closed without merging

2021-01-05 20:48 UTC, tgolen commented
Sorry Marc, I completely spaced that the refactoring was done and merged in https://github.com/Expensify/Expensify.cash/pull/959

Thanks for the update, Rory!