Generalize Modal / Refactor AttachmentModal
Expensify/App pull request #959
Opened 2020-12-14 23:40 UTC by marcaaron

cc @tgolen @roryabraham @thienlnam 

**Summary of Changes**

- Creates a `Modal.js` component with just one "type" - `centered` this will show either the full page view on smaller screens or the nearly full page modal with overlay on larger screens
- Removed several components and styles to simplify the code and make more reusable
- Refactored web styles so that the image will take up the max area it can take if larger than modal width or height (using CSS styles instead of hardcoded values)

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/148264

### Tests
**Web (Chrome, Safari, Firefox) / Desktop**

1. Upload an image via the paperclip icon
2. Verify that the image is centered in the modal and that the modal has 40px of space around it 
3. Reduce the screen size and verify that the edges of the modal take up the entire screen and the rounded corners disappear
4. Reduce the screen size more and verify that the image scales to fit inside the window (e.g. test a mobile web size screen)
5. Enlarge the window again and click on the grey overlay around the modal and verify it can be closed.
6. Test with a variety of image sizes.
7. Test with an image that has already been uploaded.

**iOS / Android**

1. Upload an image via the paperclip icon
2. Verify that a Modal appears and takes up the entire screen
3. Verify that clicking on the `x` will close this modal
4. Verify the image inside the modal can only take up the width of the device (not zoomed)
5. Verify that the pinch and zoom features are working normally

### Screenshots

**Web**

![Screen Shot 2020-12-14 at 3 02 42 PM](https://user-images.githubusercontent.com/32969087/102155146-07c21400-3e1f-11eb-89ed-5cc212e6d635.png)
![Screen Shot 2020-12-14 at 3 03 32 PM](https://user-images.githubusercontent.com/32969087/102155161-0e508b80-3e1f-11eb-8bf6-bb0386dccdd2.png)
![Screen Shot 2020-12-14 at 3 04 17 PM](https://user-images.githubusercontent.com/32969087/102155168-11e41280-3e1f-11eb-858b-d9f28ac69d15.png)
![Screen Shot 2020-12-14 at 3 04 31 PM](https://user-images.githubusercontent.com/32969087/102155183-1ad4e400-3e1f-11eb-9491-3b0e18b7bfb1.png)

**Desktop**
![Screen Shot 2020-12-14 at 3 08 32 PM](https://user-images.githubusercontent.com/32969087/102155192-21fbf200-3e1f-11eb-965e-7d5db001ba7e.png)

**Android**
![Screen Shot 2020-12-14 at 3 12 20 PM](https://user-images.githubusercontent.com/32969087/102155214-2f18e100-3e1f-11eb-9d7f-21fca983573a.png)
![Screen Shot 2020-12-14 at 3 11 39 PM](https://user-images.githubusercontent.com/32969087/102155221-317b3b00-3e1f-11eb-9fd5-89bd99455686.png)

**iOS**
![Screen Shot 2020-12-14 at 3 13 45 PM](https://user-images.githubusercontent.com/32969087/102155236-3b04a300-3e1f-11eb-91a0-7b2d5c44cfe1.png)
![Screen Shot 2020-12-14 at 3 12 46 PM](https://user-images.githubusercontent.com/32969087/102155239-3dff9380-3e1f-11eb-95e8-d9cf491c9064.png)

2020-12-15 06:29 UTC, roryabraham reviewed
Overall great work! This is a huge improvement, just had a few suggestions.

2020-12-15 22:12 UTC, tgolen requested changes

2020-12-16 01:11 UTC, roryabraham submitted a review, later dismissed
Love the way this turned out

2020-12-16 16:37 UTC, shawnborton submitted a review, later dismissed

2020-12-16 20:03 UTC, roryabraham submitted a review, later dismissed

2020-12-16 21:06 UTC, TomatoToaster submitted a review, later dismissed

2020-12-16 23:03 UTC, tgolen requested changes

2020-12-17 22:03 UTC, tgolen approved these changes
Looks like the install got it working! Testing worked fine.

2020-12-17 22:49 UTC, shawnborton approved these changes

2020-12-17 23:12 UTC, merged