Add documentation about error onyx best practice under API.md
Expensify/App pull request #9629
Opened 2022-06-29 18:01 UTC by yuwenmemon

Pullerbearing (@neil-marcellini)
cc @nkuoch @marcaaron @tgolen @iwiznia @Julesssss @MariaHCD @aldo-expensify @luacmartins 

### Details
Adding what was discussed in [this thread](https://expensify.slack.com/archives/C02HWMSMZEC/p1655291987616659) about errors returned and stored in Onyx being stored under `error`

### Fixed Issues
None

### Tests
None

2022-06-29 18:12 UTC, luacmartins submitted a review, later dismissed

2022-06-29 18:36 UTC, neil-marcellini reviewed
Nice, simple and to the point. I agree with Aldo's suggestion.

2022-06-29 18:49 UTC, iwiznia approved these changes, later dismissed

2022-06-29 20:12 UTC, aldo-expensify approved these changes, later dismissed

2022-06-29 20:54 UTC, iwiznia submitted a review, later dismissed

2022-06-29 21:01 UTC, luacmartins approved these changes, later dismissed

2022-06-30 05:09 UTC, robertjchen requested changes

2022-06-30 05:09 UTC, robertjchen commented on docs/API.md
> +    'onyxMethod' => 'merge',
Looks like we have a [dedicated constant](https://github.com/Expensify/Web-Expensify/blob/0384b1208459602ca88836b0b805a163dc9ee80c/lib/Onyx.php#L9) for this now:
```suggestion
    'onyxMethod' => Onyx::METHOD_MERGE,
```

2022-06-30 05:21 UTC, MariaHCD commented on docs/API.md
> +Error messages should be returned and stored as a String under the `error` property. If absoultely needed, additional error properties can be stored under other, more specific fields that sit at the
```suggestion
Error messages should be returned and stored as a String under the `error` property. If absolutely needed, additional error properties can be stored under other, more specific fields that sit at the same level as `error`:
```

2022-06-30 05:28 UTC, MariaHCD approved these changes

2022-06-30 05:41 UTC, robertjchen approved these changes

2022-06-30 07:45 UTC, nkuoch approved these changes

2022-06-30 09:22 UTC, Julesssss approved these changes
Thanks for adding, looks good

2022-06-30 13:00 UTC, neil-marcellini approved these changes

2022-06-30 15:23 UTC, aldo-expensify approved these changes

2022-06-30 16:23 UTC, luacmartins approved these changes

2022-06-30 16:26 UTC, merged

2022-07-08 01:34 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2633108093) to staging by @yuwenmemon in version: 1.1.81-0 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|failure ❌ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|success ✅ 
🕸 web 🕸|failure ❌

2022-07-13 01:20 UTC, OSBotify commented
🚀 [Deployed](https://github.com/Expensify/App/actions/runs/2658853938) to production by @roryabraham in version: 1.1.82-5 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎|failure ❌ 
🕸 web 🕸|success ✅