Fix Text in compose box disappears when photo is uploaded #895
Expensify/App pull request #969
Opened 2020-12-15 20:03 UTC by Avais392

### Fixed Issues
Fixes https://github.com/Expensify/ReactNativeChat/issues/895

 ### Tests

1. Run the desktop app (dev build or production build)
2. Sign in to an account
3. Open the left-hand navigation and search for your test user to chat with. Select the user.
4. Type a message in the compose text box at the bottom of the chat, but do not submit it.
5. Hit the paperclip icon on the left side of the text box and select an image.
6. Ensure the text value is not cleared while the image is uploading and after the image has finished uploading.

### Screenshots

**Issue**
http://g.recordit.co/0H9sKgBfE0.gif

**Fixed**
web
![Bug-fix](https://user-images.githubusercontent.com/38623507/102264031-e48a8800-3f36-11eb-9838-53277c315f20.gif)

desktop
![desktop](https://user-images.githubusercontent.com/38623507/102266522-63cd8b00-3f3a-11eb-8920-9436c303b762.gif)

2020-12-16 01:48 UTC, Jag96 requested changes

2020-12-16 19:31 UTC, deetergp submitted a review, later dismissed
Aside from the unexplained change to `package.lock` that @Jag96 mentioned, the code and the tests look good.

2020-12-17 01:54 UTC, Jag96 requested changes
Added a comment about fixing the `package-lock.json`, otherwise works well

2020-12-17 02:56 UTC, Jag96 approved these changes

2020-12-17 02:57 UTC, merged