fixed .XX issue
Expensify/App pull request #9924
Opened 2022-07-14 20:09 UTC by Gen0106

### Details
Currently, the regex is ^\d+(,\d+)*(\.\d{0,2})?$ in validateAmount function of /src/pages/iou/steps/IOUAmountPage.js

### Fixed Issues
I updated the regex to ^(\.\d{0,2})|\d+(,\d+)*(\.\d{0,2})?$

$ https://github.com/Expensify/App/issues/9389

### Tests
I tested it on regex101.com

2022-07-14 20:16 UTC, Gen0106 commented
I have read the CLA Document and I hereby sign the CLA

2022-07-20 17:00 UTC, chiragsalian requested changes
@Gen0106, we require every commit made in App repo to be signed. So that we know its from a trusted source.
Could you check out [these steps](https://expensify.slack.com/archives/C01GTK53T8Q/p1650473803872499?thread_ts=1650391778.438379&cid=C01GTK53T8Q) to begin signing your commits.

Once you can sign them i think you'll have you rebase so that your existing commit gets signed or you can create a new PR and commit so that its signed this time.

2022-07-20 17:05 UTC, parasharrajat commented
This is an unauthorized PR and should be closed.

2022-07-25 18:05 UTC, chiragsalian commented
Ah yes, definitely an unauthorized PR. Closing.

2022-07-25 18:05 UTC, closed without merging